Repository hashicorp/consul, pull requests merged in 2018-10, with the labels that each got.

#4677 UI: Reduce in-development deprecations (also use toLocaleString)
  ui-v2/app/controllers/dc/acls/index.js
  ui-v2/app/controllers/dc/intentions/index.js
  ui-v2/app/helpers/format-number.js
  ui-v2/app/mixins/with-health-filtering.js
  ui-v2/app/templates/components/healthchecked-resource.hbs
  ui-v2/app/templates/components/tomography-graph.hbs
  ui-v2/app/templates/dc/nodes/-rtt.hbs
  ui-v2/app/templates/dc/nodes/-services.hbs
  ui-v2/app/templates/dc/services/index.hbs
  ui-v2/app/templates/dc/services/show.hbs
  ui-v2/app/utils/helpers/call-if-type.js
  ui-v2/package.json
  ui-v2/tests/integration/helpers/format-number-test.js
  ui-v2/tests/unit/utils/helpers/call-if-type-test.js
  ui-v2/yarn.lock
Labels: ui

#4487 Add Deployment Guide and update links
  website/source/assets/images/consul-arch-single.png
  website/source/assets/images/consul-ref-arch-diagram.png
  website/source/docs/guides/deployment-guide.html.md
  website/source/docs/guides/deployment.html.md
  website/source/docs/guides/performance.html.md
  website/source/docs/guides/servers.html.md
  website/source/layouts/docs.erb
Labels: docs

#4767 UI: Move the text encoding polyfill to a a proper detecting polyfill
  ui-v2/app/index.html
  ui-v2/app/utils/atob.js
  ui-v2/app/utils/btoa.js
  ui-v2/ember-cli-build.js
Labels: ui

#4723 ui: Reduce the breakpoint at which the smaller footer kicks in
  ui-v2/app/styles/variables/custom-query.scss
Labels: ui

#4756 UI: [BUGFIX] Cope with service names that contain slashes
  ui-v2/app/adapters/service.js
  ui-v2/package.json
  ui-v2/tests/acceptance/dc/services/show-with-slashes.feature
  ui-v2/tests/acceptance/steps/dc/services/show-with-slashes-steps.js
  ui-v2/yarn.lock
Labels: ui

#4760 ui: Add truncation to the `.Address`
  ui-v2/app/styles/components/healthchecked-resource/layout.scss
Labels: ui

#4761 ui: Improve layout of node cards on large and small screens
  ui-v2/app/components/list-collection.js
  ui-v2/app/controllers/dc/services/show.js
  ui-v2/app/styles/components/list-collection.scss
  ui-v2/app/styles/variables/custom-query.scss
  ui-v2/app/templates/components/healthchecked-resource.hbs
  ui-v2/app/templates/dc/nodes/index.hbs
  ui-v2/app/templates/dc/services/show.hbs
Labels: ui

#4819 ui: [BUGFIX] Fix freetext searching within the nodes page
  ui-v2/app/components/list-collection.js
  ui-v2/tests/acceptance/components/catalog-filter.feature
Labels: bug, ui

#4814 ui: Adds multi syntax linting to the code editor
  ui-v2/app/components/code-editor.js
  ui-v2/app/index.html
  ui-v2/app/initializers/ivy-codemirror.js
  ui-v2/app/styles/components/code-editor.scss
  ui-v2/app/styles/components/code-editor/index.scss
  ui-v2/app/styles/components/code-editor/layout.scss
  ui-v2/app/styles/components/code-editor/skin.scss
  ui-v2/app/templates/components/code-editor.hbs
  ui-v2/app/templates/dc/acls/policies/-fieldsets.hbs
  ui-v2/app/utils/editor/lint.js
  ui-v2/ember-cli-build.js
  ui-v2/package.json
  ui-v2/yarn.lock
Labels: ui

#4845 Make it clear that the SecretID is used when configuring an agents tokens.
  website/source/docs/guides/acl.html.md
Labels: docs

#4728 UI: Some trivial test additions, support env var passing of port numbers
  ui-v2/app/helpers/last.js
  ui-v2/app/helpers/split.js
  ui-v2/app/utils/distance.js
  ui-v2/app/utils/injectableRequestToJQueryAjaxHash.js
  ui-v2/app/utils/tomography.js
  ui-v2/package.json
  ui-v2/tests/integration/components/feedback-dialog-test.js
  ui-v2/tests/integration/helpers/env-test.js
  ui-v2/tests/integration/helpers/last-test.js
  ui-v2/tests/integration/helpers/slugify-test.js
  ui-v2/tests/integration/helpers/split-test.js
  ui-v2/tests/unit/utils/btoa-test.js
  ui-v2/tests/unit/utils/callable-type-test.js
  ui-v2/tests/unit/utils/createURL-test.js
  ui-v2/tests/unit/utils/isFolder-test.js
  ui-v2/yarn.lock
Labels: ui
