Repository hashicorp/consul, pull requests merged in 2019-12, with the labels that each got.

#6753 docs: Rename TTL to Timeout in Script/TCP checks
  website/source/api/agent/check.html.md
  website/source/api/agent/service.html.md
Labels: docs

#6843 ui: Ensure %app-content > %app-view-content rename is complete
  ui-v2/app/styles/components/app-view.scss
  ui-v2/app/styles/components/app-view/skin.scss
  ui-v2/app/styles/components/form-elements.scss
  ui-v2/app/styles/core/layout.scss
  ui-v2/app/styles/core/typography.scss
Labels: ui

#6868 docs: Fix expose path HTTP listener ports
  website/source/docs/connect/registration/service-registration.html.md
Labels: docs

#5265 fix watch event behavior
  api/watch/watch.go
Labels: needs-discussion

#6839 ui: Ensure AbortErrors have a zero status
  ui-v2/app/adapters/http.js
Labels: ui

#6917 ui: Explicitly remove properties that shouldn't be sent when saving
  ui-v2/app/adapters/role.js
  ui-v2/app/adapters/token.js
Labels: ui

#6928 Update CONTRIBUTING.md w/ stipulation that go 1.13 is not yet supported
  .github/CONTRIBUTING.md
Labels: docs

#6853 ui: Remove some javascript files we no longer use
  ui-v2/app/components/confirmation-dialog.js
  ui-v2/app/models/intention.js
  ui-v2/app/models/policy.js
  ui-v2/app/models/token.js
  ui-v2/app/services/confirm.js
  ui-v2/app/services/error.js
  ui-v2/app/utils/confirm.js
  ui-v2/app/utils/error.js
  ui-v2/app/utils/injectableRequestToJQueryAjaxHash.js
  ui-v2/app/utils/makeAttrable.js
  ui-v2/tests/unit/services/confirm-test.js
  ui-v2/tests/unit/services/error-test.js
  ui-v2/tests/unit/utils/confirm-test.js
  ui-v2/tests/unit/utils/makeAttrable-test.js
Labels: ui

#6881 ui: Use base fonts throughout the app
  ui-v2/app/styles/app.scss
  ui-v2/app/styles/base/components/buttons/layout.scss
  ui-v2/app/styles/base/components/pill/layout.scss
  ui-v2/app/styles/base/components/tabs/skin.scss
  ui-v2/app/styles/base/components/tooltip/layout.scss
  ui-v2/app/styles/base/components/tooltip/skin.scss
  ui-v2/app/styles/base/reset/index.scss
  ui-v2/app/styles/base/typography/base-placeholders.scss
  ui-v2/app/styles/components/app-view.scss
  ui-v2/app/styles/components/app-view/layout.scss
  ui-v2/app/styles/components/confirmation-dialog/layout.scss
  ui-v2/app/styles/core/layout.scss
  ui-v2/app/styles/core/typography.scss
  ui-v2/app/styles/routes/dc/acls/index.scss
  ui-v2/app/styles/routes/dc/acls/policies/index.scss
Labels: ui

#6926 Fix formatting and add version info
  website/source/docs/connect/ca/aws.html.md
Labels: docs

#6805 change sysctl call to use absolute path
  sdk/freeport/ephemeral_linux.go
Labels: waiting-pr-merge

#6934 ui: Remove `writable` usage from policy and use the request instead
  ui-v2/app/adapters/policy.js
  ui-v2/app/models/policy.js
  ui-v2/app/models/token.js
  ui-v2/app/serializers/policy.js
  ui-v2/app/serializers/token.js
Labels: ui

#6936 ui: Fixes styling of 'duplicate intention' error message
  ui-v2/app/styles/components/flash-message.scss
Labels: bug, ui

#6952 ui: %form-element-textarea > %form-element-text-input typo
  ui-v2/app/styles/core/typography.scss
Labels: ui

#6933 ui: Namespace authorization integration
  ui-v2/app/adapters/application.js
  ui-v2/app/adapters/nspace.js
  ui-v2/app/components/hashicorp-consul.js
  ui-v2/app/env.js
  ui-v2/app/helpers/env.js
  ui-v2/app/helpers/nspace/or.js
  ui-v2/app/initializers/nspace.js
  ui-v2/app/instance-initializers/event-source.js
  ui-v2/app/instance-initializers/nspace.js
  ui-v2/app/router.js
  ui-v2/app/routes/application.js
  ui-v2/app/routes/dc.js
  ui-v2/app/routes/settings.js
  ui-v2/app/serializers/application.js
  ui-v2/app/serializers/nspace.js
  ui-v2/app/services/client/http.js
  ui-v2/app/services/repository/nspace/disabled.js
  ui-v2/app/services/repository/nspace/enabled.js
  ui-v2/app/services/store.js
  ui-v2/app/templates/application.hbs
  ui-v2/app/templates/components/hashicorp-consul.hbs
  ui-v2/app/templates/dc.hbs
  ui-v2/app/templates/dc/intentions/-form.hbs
  ui-v2/app/templates/dc/intentions/index.hbs
  ui-v2/app/templates/dc/nspaces/-notifications.hbs
  ui-v2/app/templates/dc/services/-upstreams.hbs
  ui-v2/app/templates/error.hbs
  ui-v2/app/templates/settings.hbs
  ui-v2/config/environment.js
  ui-v2/tests/acceptance/page-navigation.feature
  ui-v2/tests/acceptance/token-header.feature
  ui-v2/tests/integration/helpers/nspace/or-test.js
  ui-v2/tests/steps/assertions/http.js
  ui-v2/yarn.lock
Labels: ui

#6941 ui: Keyboard-ize main navigation menu
  ui-v2/app/components/aria-menu.js
  ui-v2/app/components/popover-menu.js
  ui-v2/app/components/toggle-button.js
  ui-v2/app/styles/base/components/buttons/layout.scss
  ui-v2/app/styles/base/components/buttons/skin.scss
  ui-v2/app/styles/base/components/stats-card/skin.scss
  ui-v2/app/styles/base/components/table/skin.scss
  ui-v2/app/styles/base/reset/system.scss
  ui-v2/app/styles/components/anchors.scss
  ui-v2/app/styles/components/buttons.scss
  ui-v2/app/styles/components/main-nav-horizontal/index.scss
  ui-v2/app/styles/components/main-nav-horizontal/layout.scss
  ui-v2/app/styles/components/main-nav-horizontal/skin.scss
  ui-v2/app/styles/core/typography.scss
  ui-v2/app/templates/components/aria-menu.hbs
  ui-v2/app/templates/components/hashicorp-consul.hbs
  ui-v2/app/templates/components/popover-menu.hbs
  ui-v2/app/templates/components/toggle-button.hbs
  ui-v2/tests/integration/components/aria-menu-test.js
  ui-v2/tests/integration/components/popover-menu-test.js
  ui-v2/tests/pages/components/page.js
Labels: ui

#6949 Add CI test-integrations job for connect Vault CA provider
  .circleci/config.yml
  GNUmakefile
Labels: enhancement, theme/connect

#6964 CI: Extract remaining values of /tmp/test-results into yaml reference
  .circleci/config.yml
Labels: build, enhancement

#6965 ui: Various amends for 1.7beta
  ui-v2/app/adapters/discovery-chain.js
  ui-v2/app/components/aria-menu.js
  ui-v2/app/components/discovery-chain.js
  ui-v2/app/helpers/href-mut.js
  ui-v2/app/instance-initializers/nspace.js
  ui-v2/app/routes/application.js
  ui-v2/app/routes/dc.js
  ui-v2/app/routes/dc/acls.js
  ui-v2/app/routes/dc/services/show.js
  ui-v2/app/styles/components/discovery-chain/layout.scss
  ui-v2/app/styles/components/healthchecked-resource.scss
  ui-v2/app/styles/components/index.scss
  ui-v2/app/styles/components/main-nav-horizontal/layout.scss
  ui-v2/app/styles/components/tooltip.scss
  ui-v2/app/styles/core/typography.scss
Labels: ui

#6957 Add 'kind = connect-proxy' to mesh_gateway.html
  website/source/docs/connect/mesh_gateway.html.md
Labels: docs

#6948 Restore a few more service-kind index updates so blocking in ServiceDump works in more cases
  agent/consul/state/catalog.go
  agent/consul/state/catalog_oss.go
  agent/consul/state/catalog_test.go
Labels: bug

#6974 Ensure ember-data ids are created correct taking into account the nspace
  ui-v2/app/serializers/application.js
  ui-v2/app/utils/create-fingerprinter.js
  ui-v2/tests/unit/utils/create-fingerprinter-test.js
Labels: ui

#6975 ui: Cope with the possibility of receiving no namespaces
  ui-v2/app/templates/components/hashicorp-consul.hbs
Labels: ui

#6973 ui: Make sure that the namespace is passed when changing a token via [Use]
  ui-v2/app/mixins/token/with-actions.js
  ui-v2/app/routes/dc.js
  ui-v2/tests/acceptance/dc/acls/tokens/own-no-delete.feature
  ui-v2/tests/acceptance/dc/acls/tokens/use.feature
Labels: ui

#6978 Move bootstrapACLs under global key in Helm docs
  website/source/docs/platform/k8s/helm.html.md
Labels: docs
