Repository hashicorp/consul, pull requests merged in 2019-01, with the labels that each got.

#5093 Re-worked the ACL guide into two docs and an updated guide.
  website/source/docs/agent/acl-rules.html.md
  website/source/docs/agent/acl-system.html.md
  website/source/docs/guides/acl.html.md
  website/source/layouts/docs.erb
Labels: docs

#5212 Language change cluster -> datacenter
  website/source/docs/guides/backup.html.md
  website/source/docs/guides/index.html.md
  website/source/layouts/docs.erb
Labels: docs

#5135 ui: Fix typo in acl-migration guide link
  ui-v2/app/templates/dc/acls/tokens/edit.hbs
  ui-v2/app/templates/dc/acls/tokens/index.hbs
Labels: ui

#5115 UI: Text change Node Health > Health Checks
  ui-v2/app/styles/components/table.scss
  ui-v2/app/templates/dc/services/index.hbs
Labels: ui

#5227 Add acl.enable_key_list_policy to agent config docs.
  website/source/docs/agent/options.html.md
Labels: docs

#5206 UI: [BUGFIX] Decode/encode urls
  ui-v2/app/adapters/application.js
  ui-v2/app/adapters/service.js
  ui-v2/app/helpers/href-to.js
  ui-v2/app/initializers/route-urldecode-params.js
  ui-v2/app/router.js
  ui-v2/app/templates/dc/kv/index.hbs
  ui-v2/app/utils/createURL.js
  ui-v2/app/utils/routing/walk.js
  ui-v2/app/utils/routing/wildcard.js
  ui-v2/tests/acceptance/dc/kvs/update.feature
  ui-v2/tests/acceptance/dc/services/show-with-slashes.feature
  ui-v2/tests/pages/dc/kv/edit.js
  ui-v2/tests/unit/utils/routing/walk-test.js
  ui-v2/tests/unit/utils/routing/wildcard-test.js
Labels: ui

#5083 ui: Adds XHR connection management to HTTP/1.1 installs
  ui-v2/app/adapters/application.js
  ui-v2/app/initializers/client.js
  ui-v2/app/services/client/http.js
  ui-v2/app/services/dom.js
  ui-v2/app/utils/get-object-pool.js
  ui-v2/app/utils/http/request.js
  ui-v2/tests/integration/services/repository/intention-test.js
  ui-v2/tests/unit/services/client/http-test.js
  ui-v2/tests/unit/utils/get-object-pool-test.js
  ui-v2/tests/unit/utils/http/request-test.js
Labels: ui

#5262 Corrects `defile` to `defined`
  website/source/docs/agent/checks.html.md
Labels: bug, docs

#5279 UI: Bump footer date
  ui-v2/config/environment.js
Labels: ui

#5283 Fixing broken link.
  website/source/docs/guides/index.html.md
  website/source/layouts/docs.erb
Labels: docs

#5260 [Docs] New ACL Landing Page
  website/source/docs/guides/acl-index.html.md
  website/source/docs/guides/index.html.md
  website/source/layouts/docs.erb
Labels: docs

#5237 Check ACLs more often for xDS endpoints.
  agent/agent.go
  agent/xds/server.go
  agent/xds/server_test.go
Labels: theme/connect

#5245 ui: Custom version of ember-block-slots compatible with ember 3
  ui-v2/app/components/app-view.js
  ui-v2/app/components/confirmation-dialog.js
  ui-v2/app/components/feedback-dialog.js
  ui-v2/app/components/modal-dialog.js
  ui-v2/app/components/tabular-collection.js
  ui-v2/app/components/tabular-details.js
  ui-v2/app/components/token-list.js
  ui-v2/lib/block-slots/LICENSE.md
  ui-v2/lib/block-slots/README.md
  ui-v2/lib/block-slots/addon/components/block-slot.js
  ui-v2/lib/block-slots/addon/components/yield-slot.js
  ui-v2/lib/block-slots/addon/helpers/block-params.js
  ui-v2/lib/block-slots/addon/index.js
  ui-v2/lib/block-slots/addon/mixins/slots.js
  ui-v2/lib/block-slots/addon/templates/components/block-slot.hbs
  ui-v2/lib/block-slots/addon/templates/components/yield-slot.hbs
  ui-v2/lib/block-slots/app/components/block-slot.js
  ui-v2/lib/block-slots/app/components/yield-slot.js
  ui-v2/lib/block-slots/app/helpers/block-params.js
  ui-v2/lib/block-slots/app/mixins/slots.js
  ui-v2/lib/block-slots/index.js
  ui-v2/lib/block-slots/package.json
  ui-v2/package.json
  ui-v2/yarn.lock
Labels: ui
