Repository hashicorp/consul, pull requests merged in 2019-02, with the labels that each got.

#5321 [DOCS] website: Update UI Policy recommendations from Guide
  website/source/docs/guides/acl.html.md
Labels: docs

#5310 Documentation - New plugin for frontend applications based in webpack
  website/source/api/libraries-and-sdks.html.md
Labels: docs

#5336 Docs EA update RA and DG
  website/source/docs/guides/deployment-guide.html.md
  website/source/docs/guides/deployment.html.md
Labels: docs

#5315 [Docs] New KV documentation
  website/source/docs/agent/kv.html.md
  website/source/layouts/docs.erb
Labels: docs

#5267 UI: EventSource project implementation to enable blocking queries for service and node listings
  ui-v2/app/adapters/application.js
  ui-v2/app/controllers/dc/nodes/index.js
  ui-v2/app/controllers/dc/services/index.js
  ui-v2/app/instance-initializers/event-source.js
  ui-v2/app/mixins/with-event-source.js
  ui-v2/app/mixins/with-filtering.js
  ui-v2/app/mixins/with-health-filtering.js
  ui-v2/app/services/lazy-proxy.js
  ui-v2/app/services/repository/type/event-source.js
  ui-v2/tests/acceptance/dc/list-blocking.feature
  ui-v2/tests/acceptance/page-navigation.feature
  ui-v2/tests/acceptance/steps/dc/list-blocking-steps.js
  ui-v2/tests/steps.js
  ui-v2/yarn.lock
Labels: ui

#5334 [docs] ACL reset procedure
  website/source/docs/commands/acl/acl-bootstrap.html.md.erb
  website/source/docs/guides/acl.html.md
Labels: docs

#5350 [Docs] Helm Chart
  website/source/docs/platform/k8s/helm.html.md
Labels: docs

#5352 UI: Add setting to enable/disable blocking queries
  ui-v2/app/controllers/settings.js
  ui-v2/app/router.js
  ui-v2/app/routes/settings.js
  ui-v2/app/services/client/http.js
  ui-v2/app/services/repository/type/event-source.js
  ui-v2/app/templates/components/hashicorp-consul.hbs
  ui-v2/app/templates/settings.hbs
  ui-v2/app/utils/dom/event-source/cache.js
  ui-v2/app/utils/form/builder.js
  ui-v2/tests/unit/controllers/settings-test.js
  ui-v2/tests/unit/routes/settings-test.js
  ui-v2/tests/unit/utils/dom/event-source/cache-test.js
Labels: ui

#5070 UI: Add EventSource ready for implementing blocking queries
  ui-v2/.eslintignore
  ui-v2/app/adapters/application.js
  ui-v2/app/controllers/dc/nodes/index.js
  ui-v2/app/controllers/dc/services/index.js
  ui-v2/app/controllers/settings.js
  ui-v2/app/instance-initializers/event-source.js
  ui-v2/app/mixins/with-event-source.js
  ui-v2/app/mixins/with-filtering.js
  ui-v2/app/mixins/with-health-filtering.js
  ui-v2/app/router.js
  ui-v2/app/routes/settings.js
  ui-v2/app/services/client/http.js
  ui-v2/app/services/lazy-proxy.js
  ui-v2/app/services/repository/type/event-source.js
  ui-v2/app/templates/components/hashicorp-consul.hbs
  ui-v2/app/templates/settings.hbs
  ui-v2/app/utils/dom/event-source/blocking.js
  ui-v2/app/utils/dom/event-source/cache.js
  ui-v2/app/utils/dom/event-source/callable.js
  ui-v2/app/utils/dom/event-source/index.js
  ui-v2/app/utils/dom/event-source/proxy.js
  ui-v2/app/utils/dom/event-source/reopenable.js
  ui-v2/app/utils/dom/event-source/resolver.js
  ui-v2/app/utils/dom/event-source/storage.js
  ui-v2/app/utils/dom/event-target/event-target-shim/LICENSE
  ui-v2/app/utils/dom/event-target/event-target-shim/event.js
  ui-v2/app/utils/dom/event-target/rsvp.js
  ui-v2/app/utils/form/builder.js
  ui-v2/tests/acceptance/dc/list-blocking.feature
  ui-v2/tests/acceptance/page-navigation.feature
  ui-v2/tests/acceptance/steps/dc/list-blocking-steps.js
  ui-v2/tests/integration/utils/dom/event-source/callable-test.js
  ui-v2/tests/steps.js
  ui-v2/tests/unit/controllers/settings-test.js
  ui-v2/tests/unit/routes/settings-test.js
  ui-v2/tests/unit/utils/dom/event-source/blocking-test.js
  ui-v2/tests/unit/utils/dom/event-source/cache-test.js
  ui-v2/tests/unit/utils/dom/event-source/callable-test.js
  ui-v2/tests/unit/utils/dom/event-source/index-test.js
  ui-v2/tests/unit/utils/dom/event-source/proxy-test.js
  ui-v2/tests/unit/utils/dom/event-source/reopenable-test.js
  ui-v2/tests/unit/utils/dom/event-source/resolver-test.js
  ui-v2/tests/unit/utils/dom/event-source/storage-test.js
  ui-v2/tests/unit/utils/dom/event-target/rsvp-test.js
  ui-v2/yarn.lock
Labels: ui

#5255 UI: Add ember steps:list command for listing available steps
  ui-v2/GNUmakefile
  ui-v2/lib/commands/index.js
  ui-v2/lib/commands/lib/list.js
  ui-v2/lib/commands/package.json
  ui-v2/package.json
  ui-v2/tests/acceptance/steps/steps.js
  ui-v2/tests/steps.js
  ui-v2/tests/steps/assertions/dom.js
  ui-v2/tests/steps/assertions/http.js
  ui-v2/tests/steps/assertions/model.js
  ui-v2/tests/steps/assertions/page.js
  ui-v2/tests/steps/debug/index.js
  ui-v2/tests/steps/doubles/http.js
  ui-v2/tests/steps/doubles/model.js
  ui-v2/tests/steps/interactions/click.js
  ui-v2/tests/steps/interactions/form.js
  ui-v2/tests/steps/interactions/visit.js
  ui-v2/yarn.lock
Labels: ui

#5362 website: fix errant mention of 'snapshot save' on docs for 'snapshot restore'
  website/source/docs/commands/snapshot/restore.html.markdown.erb
  website/source/docs/commands/snapshot/save.html.markdown.erb
Labels: docs

#5358 Add common blocking implementation details to docs
  website/source/api/index.html.md
Labels: docs

#5345 Add more details on SkipNodeUpdate option
  website/source/api/catalog.html.md
Labels: docs

#5328 ACL Token Persistence and Reloading
  agent/acl_test.go
  agent/agent.go
  agent/agent_endpoint.go
  agent/agent_endpoint_test.go
  agent/agent_test.go
  agent/config/builder.go
  agent/config/config.go
  agent/config/runtime.go
  agent/config/runtime_test.go
  agent/consul/acl_endpoint_test.go
  agent/consul/acl_replication.go
  agent/consul/acl_replication_legacy.go
  agent/consul/acl_replication_legacy_test.go
  agent/consul/acl_replication_test.go
  agent/consul/acl_server.go
  agent/consul/acl_test.go
  agent/consul/config.go
  agent/consul/leader.go
  agent/http_test.go
  agent/local/state_test.go
  agent/token/store.go
  agent/token/store_test.go
  api/agent.go
  api/agent_test.go
  command/acl/agenttokens/agent_tokens.go
  lib/file/atomic.go
  website/source/api/agent.html.md
  website/source/docs/agent/options.html.md
Labels: theme/acls, theme/operator-usability
