Repository hashicorp/consul, pull requests merged in 2019-06, with the labels that each got.

#5912 ui: Upgrade fstream
  ui-v2/yarn.lock
Labels: ui

#5907 Fix acl.enable_key_list to be acl.enable_key_list_policy in docs
  website/source/docs/agent/options.html.md
Labels: docs, theme/acls

#5871 Update links to envoy docs on xDS protocol
  agent/xds/server.go
  agent/xds/server_test.go
  agent/xds/xds.go
  website/source/docs/connect/proxies/envoy.md
Labels: docs

#5738 ui: Provide options for event source runners (behind flags)
  ui-v2/app/utils/dom/event-source/index.js
Labels: ui

#5836 ui: ACL Policies. Catch all server errors
  ui-v2/app/components/policy-selector.js
  ui-v2/app/templates/components/policy-form.hbs
  ui-v2/tests/acceptance/dc/acls/policies/as-many/add-new.feature
  ui-v2/tests/pages.js
  ui-v2/tests/pages/components/policy-form.js
  ui-v2/tests/pages/components/policy-selector.js
  ui-v2/tests/steps/assertions/page.js
Labels: ui

#5837 ui: [BUGFIX] Replaces destroyRecord with unloadRecord for KV 404's
  ui-v2/app/services/repository/kv.js
Labels: ui

#5838 ui: Ensures nested policy forms are reset properly
  ui-v2/app/components/policy-selector.js
  ui-v2/app/components/role-selector.js
  ui-v2/app/templates/components/policy-form.hbs
  ui-v2/app/templates/components/policy-selector.hbs
  ui-v2/tests/acceptance/dc/acls/policies/as-many/reset.feature
  ui-v2/tests/acceptance/steps/dc/acls/policies/as-many/reset-steps.js
  ui-v2/tests/steps.js
  ui-v2/tests/steps/assertions/form.js
Labels: ui

#5804 [docs] Enterprise Landing Page
  website/source/docs/enterprise/index.html.md
Labels: docs

#5865 UI: Test readonly ServiceIdentity rules
  ui-v2/tests/acceptance/dc/acls/policies/as-many/add-new.feature
  ui-v2/tests/steps/interactions/form.js
Labels: ui

#5926 ui: Upgrade js-yaml
  ui-v2/yarn.lock
Labels: ui

#5934 ui: Enable ember environment configuration to be set via the go binary at runtime
  ui-v2/app/index.html
  ui-v2/lib/startup/index.js
Labels: ui

#5941 ui: Mod context path
  ui-v2/app/index.html
  ui-v2/lib/startup/index.js
Labels: ui

#5945 ui: 1930 - Move everything to use javascript template literals
  ui-v2/lib/startup/index.js
  ui-v2/lib/startup/templates/body.html.js
  ui-v2/lib/startup/templates/head.html.js
  ui-v2/tests/index.html
Labels: ui

#5933 ui: Ensure Service Instance pages account for nodes
  ui-v2/app/models/proxy.js
  ui-v2/app/router.js
  ui-v2/app/routes/dc/services/instance.js
  ui-v2/app/services/repository/proxy.js
  ui-v2/app/services/repository/service.js
  ui-v2/app/templates/dc/services/-instances.hbs
  ui-v2/tests/acceptance/dc/services/instances/error.feature
  ui-v2/tests/acceptance/dc/services/instances/proxy.feature
  ui-v2/tests/acceptance/dc/services/instances/show.feature
  ui-v2/tests/acceptance/dc/services/instances/sidecar-proxy.feature
  ui-v2/tests/acceptance/dc/services/instances/with-proxy.feature
  ui-v2/tests/acceptance/dc/services/instances/with-sidecar.feature
  ui-v2/tests/pages/dc/services/instance.js
Labels: ui

#5957 Update questions issue template directing q's to the forum
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/question.md
Labels: docs

#5959 Update production-acls.html.md
  website/source/docs/guides/production-acls.html.md
Labels: docs

#5864 [docs] Reorganize connect documentation for clarity
  website/source/api/agent/connect.html.md
  website/source/api/agent/service.html.md
  website/source/docs/agent/config_entries.html.md
  website/source/docs/agent/options.html.md
  website/source/docs/agent/services.html.md
  website/source/docs/commands/connect/envoy.html.md.erb
  website/source/docs/commands/connect/proxy.html.md.erb
  website/source/docs/connect/configuration.html.md
  website/source/docs/connect/connect-internals.html.md
  website/source/docs/connect/index.html.md
  website/source/docs/connect/native.html.md
  website/source/docs/connect/observability.html.md
  website/source/docs/connect/proxies.html.md
  website/source/docs/connect/proxies/built-in.md
  website/source/docs/connect/proxies/envoy.md
  website/source/docs/connect/registration.html.md
  website/source/docs/connect/registration/service-registration.html.md
  website/source/docs/connect/registration/sidecar-service.md
  website/source/docs/enterprise/connect-multi-datacenter/index.html.md
  website/source/layouts/docs.erb
  website/source/redirects.txt
Labels: docs

#5921 ui: Further CSS amends/migration
  ui-v2/app/styles/base/components/table/layout.scss
  ui-v2/app/styles/base/components/tabs/index.scss
  ui-v2/app/styles/base/components/tabs/layout.scss
  ui-v2/app/styles/base/components/tooltip/index.scss
  ui-v2/app/styles/base/components/tooltip/layout.scss
  ui-v2/app/styles/base/components/tooltip/skin.scss
  ui-v2/app/styles/base/icons/base-variables.scss
  ui-v2/app/styles/base/icons/icon-placeholders.scss
  ui-v2/app/styles/components/app-view.scss
  ui-v2/app/styles/components/breadcrumbs.scss
  ui-v2/app/styles/components/table.scss
  ui-v2/app/styles/components/tabular-details/layout.scss
  ui-v2/app/styles/components/tooltip.scss
  ui-v2/app/templates/components/token-list.hbs
  ui-v2/app/templates/dc/acls/policies/index.hbs
  ui-v2/app/templates/dc/acls/roles/index.hbs
  ui-v2/app/templates/dc/acls/tokens/index.hbs
  ui-v2/app/templates/dc/services/index.hbs
Labels: ui

#5952 ui: Adds ember-auto-import and replaces the 3 places where we used `npm:`
  ui-v2/app/utils/atob.js
  ui-v2/app/utils/btoa.js
  ui-v2/package.json
  ui-v2/tests/helpers/yadda.js
  ui-v2/yarn.lock
Labels: ui

#5979 [docs] Internals
  website/source/docs/internals/architecture.html.md
  website/source/docs/internals/consensus.html.md
  website/source/docs/internals/gossip.html.md
Labels: docs

#5944 ui: Normal proxies link to services, sidecars to instances
  ui-v2/app/services/repository/proxy.js
  ui-v2/app/templates/dc/services/instance.hbs
  ui-v2/tests/acceptance/dc/services/instances/error.feature
  ui-v2/tests/acceptance/dc/services/instances/proxy.feature
  ui-v2/tests/acceptance/dc/services/instances/show.feature
  ui-v2/tests/acceptance/dc/services/instances/with-sidecar.feature
Labels: ui

#5972 [docs] Fix invalid curl request on session API
  website/source/api/session.html.md
Labels: docs

#5998 [docs] Sidecar Registration
  website/source/docs/connect/registration/sidecar-service.md
Labels: docs

#5422 [docs] update documentation for connect-service-upstreams
  website/source/docs/platform/k8s/connect.html.md
Labels: docs

#5967 ui: Implements a testable clipboard {{copy-button}}
  ui-v2/app/components/copy-button.js
  ui-v2/app/services/clipboard/local-storage.js
  ui-v2/app/services/clipboard/os.js
  ui-v2/package.json
  ui-v2/tests/steps.js
  ui-v2/tests/steps/assertions/dom.js
  ui-v2/tests/test-helper.js
  ui-v2/tests/unit/services/clipboard/local-storage-test.js
  ui-v2/tests/unit/services/clipboard/os-test.js
  ui-v2/yarn.lock
Labels: ui

#5977 Document reset license
  website/source/api/operator/license.html.md
Labels: docs

#6010 [docs] Architecture Node vs Agent
  website/source/docs/internals/architecture.html.md
Labels: docs

#5999 [docs] New Glossary Page
  website/source/docs/glossary.html.md
  website/source/docs/internals/anti-entropy.html.md
  website/source/docs/internals/architecture.html.md
  website/source/docs/internals/consensus.html.md
  website/source/docs/internals/coordinates.html.md
  website/source/docs/internals/gossip.html.md
  website/source/docs/internals/index.html.md
  website/source/docs/internals/security.html.md
  website/source/docs/internals/sessions.html.md
  website/source/layouts/docs.erb
Labels: docs

#5870 docs: fixed typos on a few doc pages
  website/source/docs/agent/cloud-auto-join.html.md
  website/source/docs/agent/sentinel.html.markdown.erb
  website/source/docs/commands/kv/put.html.markdown.erb
  website/source/docs/connect/intentions.html.md
  website/source/docs/platform/k8s/service-sync.html.md
  website/source/docs/upgrade-specific.html.md
Labels: docs

#5958 Add feature test for copy button
  ui-v2/app/templates/components/healthcheck-output.hbs
  ui-v2/tests/acceptance/components/copy-button.feature
  ui-v2/tests/acceptance/steps/components/copy-button-steps.js
Labels: ui

#5217 Allow service deregistration with node write permission
  agent/consul/acl.go
  agent/consul/acl_test.go
  agent/consul/catalog_endpoint_test.go
Labels: needs-discussion
