Repository hashicorp/consul, pull requests merged in 2019-08, with the labels that each got.

#6239 docs: Fix minor mistakes in Connect main page
  website/source/docs/connect/index.html.md
Labels: docs

#6242 connect: simplify the compiled discovery chain data structures
  agent/consul/config_endpoint.go
  agent/consul/discoverychain/compile.go
  agent/consul/discoverychain/compile_test.go
  agent/consul/discoverychain/testing.go
  agent/proxycfg/state.go
  agent/structs/discovery_chain.go
  agent/xds/clusters.go
  agent/xds/endpoints.go
  agent/xds/endpoints_test.go
  agent/xds/routes.go
Labels: theme/connect

#6136 ui: Upgrade ember-cli-api-double. Adds new staging env
  ui-v2/config/environment.js
  ui-v2/package.json
  ui-v2/tests/helpers/api.js
  ui-v2/tests/helpers/set-cookies.js
  ui-v2/yarn.lock
Labels: ui

#6166 ui: [Bugfix] - Sticky KV Sessions
  ui-v2/app/routes/dc/kv/edit.js
  ui-v2/app/templates/dc/kv/edit.hbs
  ui-v2/tests/acceptance/dc/kvs/edit.feature
  ui-v2/tests/acceptance/steps/dc/kvs/edit-steps.js
  ui-v2/tests/pages.js
  ui-v2/tests/pages/dc/kv/edit.js
Labels: bug, ui

#6196 ui: Adds readonly meta data to the serviceInstance and node detail pages
  ui-v2/app/helpers/object-entries.js
  ui-v2/app/styles/routes/dc/nodes/index.scss
  ui-v2/app/styles/routes/dc/service/index.scss
  ui-v2/app/templates/dc/nodes/metadata.hbs
  ui-v2/app/templates/dc/nodes/show.hbs
  ui-v2/app/templates/dc/services/instance.hbs
  ui-v2/app/templates/dc/services/metadata.hbs
  ui-v2/tests/acceptance/dc/nodes/show.feature
  ui-v2/tests/acceptance/dc/services/instances/show.feature
  ui-v2/tests/pages/dc/nodes/show.js
  ui-v2/tests/pages/dc/services/instance.js
Labels: ui

#6246 connect: detect and prevent circular discovery chain references
  agent/consul/discoverychain/compile.go
  agent/consul/discoverychain/compile_test.go
  agent/consul/discoverychain/string_stack.go
  agent/consul/discoverychain/string_stack_test.go
  agent/consul/state/config_entry.go
  agent/consul/state/config_entry_test.go
  agent/structs/discovery_chain.go
Labels: theme/connect

#6248 connect: expose an API endpoint to compile the discovery chain
  agent/cache-types/discovery_chain.go
  agent/cache-types/discovery_chain_test.go
  agent/consul/acl_endpoint_test.go
  agent/consul/config_endpoint.go
  agent/consul/discovery_chain_endpoint.go
  agent/consul/discovery_chain_endpoint_test.go
  agent/consul/discoverychain/compile.go
  agent/consul/discoverychain/compile_test.go
  agent/consul/server_oss.go
  agent/discovery_chain_endpoint.go
  agent/discovery_chain_endpoint_test.go
  agent/http_oss.go
  agent/internal_endpoint.go
  agent/proxycfg/manager_test.go
  agent/proxycfg/snapshot.go
  agent/proxycfg/state.go
  agent/proxycfg/state_test.go
  agent/proxycfg/testing.go
  agent/structs/config_entry.go
  agent/structs/config_entry_discoverychain.go
  agent/structs/config_entry_discoverychain_test.go
  agent/structs/config_entry_test.go
  agent/structs/discovery_chain.go
  agent/structs/discovery_chain_test.go
  agent/xds/clusters.go
  agent/xds/endpoints.go
  agent/xds/endpoints_test.go
  agent/xds/routes.go
  agent/xds/sni.go
  agent/xds/testdata/endpoints/connect-proxy-with-chain-and-sliding-failover.golden
  api/config_entry.go
  api/config_entry_discoverychain.go
  api/discovery_chain.go
  api/discovery_chain_test.go
  command/config/write/config_write_test.go
Labels: theme/connect

#6194 ui: Enable blocking queries by default
  ui-v2/app/controllers/settings.js
  ui-v2/app/routes/settings.js
  ui-v2/app/services/repository/type/event-source.js
  ui-v2/tests/acceptance/dc/list-blocking.feature
  ui-v2/tests/acceptance/dc/nodes/sessions/invalidate.feature
Labels: ui

#6145 ui: add some additional env level URLs for easier linking
  ui-v2/app/templates/components/hashicorp-consul.hbs
  ui-v2/app/templates/components/policy-form.hbs
  ui-v2/app/templates/components/policy-selector.hbs
  ui-v2/app/templates/dc/acls/-disabled.hbs
  ui-v2/app/templates/dc/acls/-form.hbs
  ui-v2/app/templates/dc/acls/policies/-view.hbs
  ui-v2/app/templates/dc/acls/tokens/-fieldsets-legacy.hbs
  ui-v2/app/templates/dc/acls/tokens/edit.hbs
  ui-v2/app/templates/dc/acls/tokens/index.hbs
  ui-v2/app/templates/dc/kv/edit.hbs
  ui-v2/app/templates/dc/nodes/-sessions.hbs
  ui-v2/app/templates/error.hbs
  ui-v2/config/environment.js
Labels: ui

#6281 ui: HTTPAdapter - Move Tests
  ui-v2/tests/integration/adapters/acl-test.js
  ui-v2/tests/integration/adapters/coordinate-test.js
  ui-v2/tests/integration/adapters/dc-test.js
  ui-v2/tests/integration/adapters/intention-test.js
  ui-v2/tests/integration/adapters/kv-test.js
  ui-v2/tests/integration/adapters/node-test.js
  ui-v2/tests/integration/adapters/policy-test.js
  ui-v2/tests/integration/adapters/role-test.js
  ui-v2/tests/integration/adapters/service-test.js
  ui-v2/tests/integration/adapters/session-test.js
  ui-v2/tests/integration/adapters/token-test.js
  ui-v2/tests/integration/serializers/acl-test.js
  ui-v2/tests/integration/serializers/coordinate-test.js
  ui-v2/tests/integration/serializers/dc-test.js
  ui-v2/tests/integration/serializers/intention-test.js
  ui-v2/tests/integration/serializers/kv-test.js
  ui-v2/tests/integration/serializers/node-test.js
  ui-v2/tests/integration/serializers/policy-test.js
  ui-v2/tests/integration/serializers/role-test.js
  ui-v2/tests/integration/serializers/service-test.js
  ui-v2/tests/integration/serializers/session-test.js
  ui-v2/tests/integration/serializers/token-test.js
Labels: ui

#6288 connect: ensure intention replication continues to work when the replication ACL token changes
  agent/consul/acl_endpoint_test.go
  agent/consul/leader_connect.go
  agent/consul/leader_connect_test.go
Labels: theme/connect

#6298 ui: Make sure filtering tokens by roles works (as well as policies)
  ui-v2/app/adapters/token.js
  ui-v2/tests/integration/adapters/token-test.js
Labels: ui

#6302 connect: allow mesh gateways to use central config
  agent/service_manager.go
  agent/service_manager_test.go
Labels: theme/connect

#6308 ui: fix/replace magnifier icon
  ui-v2/app/styles/base/icons/base-variables.scss
  ui-v2/app/styles/base/icons/icon-placeholders.scss
  ui-v2/app/styles/components/freetext-filter.scss
  ui-v2/app/styles/components/icons/index.scss
  ui-v2/app/styles/components/product.scss
Labels: ui

#6265 ui: Leader icon for node listing view
  ui-v2/app/adapters/node.js
  ui-v2/app/routes/dc/nodes/index.js
  ui-v2/app/services/repository/node.js
  ui-v2/app/services/repository/type/event-source.js
  ui-v2/app/services/store.js
  ui-v2/app/styles/components/healthchecked-resource.scss
  ui-v2/app/templates/components/healthchecked-resource.hbs
  ui-v2/app/templates/dc/nodes/index.hbs
  ui-v2/package.json
  ui-v2/tests/acceptance/dc/nodes/index.feature
  ui-v2/tests/acceptance/dc/nodes/no-leader.feature
  ui-v2/tests/acceptance/page-navigation.feature
  ui-v2/tests/acceptance/steps/dc/nodes/no-leader-steps.js
  ui-v2/tests/pages/dc/nodes/index.js
  ui-v2/yarn.lock
Labels: ui

#6034 ui: Adds a `sort-control` component for asc/desc sorting of columns etc
  ui-v2/app/components/sort-control.js
  ui-v2/app/helpers/starts-with.js
  ui-v2/app/styles/base/components/sort-control/index.scss
  ui-v2/app/styles/base/components/sort-control/skin.scss
  ui-v2/app/styles/components/index.scss
  ui-v2/app/styles/components/sort-control.scss
  ui-v2/app/templates/components/sort-control.hbs
  ui-v2/tests/integration/components/sort-control-test.js
  ui-v2/tests/integration/helpers/starts-with-test.js
Labels: ui

#6300 Fix 404
  website/source/discovery.html.erb
Labels: docs

#6312 xds: improve how envoy metrics are emitted
  agent/xds/sni.go
  agent/xds/testdata/clusters/connect-proxy-with-chain-and-overrides.golden
  agent/xds/testdata/endpoints/connect-proxy-with-chain-and-overrides.golden
  agent/xds/testdata/routes/connect-proxy-with-chain-and-overrides.golden
  command/connect/envoy/bootstrap_config.go
  command/connect/envoy/bootstrap_config_test.go
  command/connect/envoy/envoy_test.go
  command/connect/envoy/testdata/access-log-path.golden
  command/connect/envoy/testdata/custom-bootstrap.golden
  command/connect/envoy/testdata/defaults.golden
  command/connect/envoy/testdata/extra_-multiple.golden
  command/connect/envoy/testdata/extra_-single.golden
  command/connect/envoy/testdata/grpc-addr-config.golden
  command/connect/envoy/testdata/grpc-addr-env.golden
  command/connect/envoy/testdata/grpc-addr-flag.golden
  command/connect/envoy/testdata/grpc-addr-unix.golden
  command/connect/envoy/testdata/stats-config-override.golden
  command/connect/envoy/testdata/token-arg.golden
  command/connect/envoy/testdata/token-env.golden
  command/connect/envoy/testdata/token-file-arg.golden
  command/connect/envoy/testdata/token-file-env.golden
  command/connect/envoy/testdata/zipkin-tracing-config.golden
  test/integration/connect/envoy/case-dogstatsd-udp/verify.bats
  test/integration/connect/envoy/case-gateways-local/primary/verify.bats
  test/integration/connect/envoy/case-gateways-remote/primary/verify.bats
  test/integration/connect/envoy/case-grpc/verify.bats
  test/integration/connect/envoy/case-http-badauthz/verify.bats
  test/integration/connect/envoy/case-http/verify.bats
  test/integration/connect/envoy/case-http2/verify.bats
  test/integration/connect/envoy/case-prometheus/verify.bats
  test/integration/connect/envoy/case-statsd-udp/verify.bats
  test/integration/connect/envoy/case-zipkin/verify.bats
Labels: theme/connect

#6342 connect: updating a service-defaults config entry should leave an unset protocol alone
  agent/consul/config_endpoint_test.go
  agent/structs/config_entry.go
Labels: theme/connect

#6324 connect: introduce ExternalSNI field on service-defaults
  agent/config/runtime_test.go
  agent/consul/discoverychain/compile.go
  agent/consul/discoverychain/compile_test.go
  agent/proxycfg/testing.go
  agent/structs/config_entry.go
  agent/structs/config_entry_test.go
  agent/structs/discovery_chain.go
  agent/xds/clusters.go
  agent/xds/clusters_test.go
  agent/xds/endpoints_test.go
  agent/xds/listeners_test.go
  agent/xds/routes_test.go
  agent/xds/testdata/clusters/connect-proxy-with-chain-external-sni.golden
  agent/xds/testdata/endpoints/connect-proxy-with-chain-external-sni.golden
  agent/xds/testdata/listeners/connect-proxy-with-chain-external-sni.golden
  agent/xds/testdata/routes/connect-proxy-with-chain-external-sni.golden
  api/config_entry.go
  api/config_entry_test.go
  api/discovery_chain.go
  command/config/write/config_write_test.go
Labels: theme/connect

#6340 connect: generate the full SNI names for discovery targets in the compiler rather than in the xds package
  agent/cache-types/discovery_chain_test.go
  agent/connect/ca/provider_consul.go
  agent/connect/ca/provider_consul_test.go
  agent/connect/sni.go
  agent/connect/sni_test.go
  agent/connect/testing_ca.go
  agent/consul/connect_ca_endpoint.go
  agent/consul/connect_ca_endpoint_test.go
  agent/consul/discovery_chain_endpoint.go
  agent/consul/discovery_chain_endpoint_test.go
  agent/consul/discoverychain/compile.go
  agent/consul/discoverychain/compile_test.go
  agent/consul/discoverychain/testing.go
  agent/consul/fsm/commands_oss_test.go
  agent/consul/fsm/snapshot_oss_test.go
  agent/consul/leader_connect.go
  agent/consul/state/config_entry.go
  agent/consul/state/connect_ca.go
  agent/consul/state/connect_ca_test.go
  agent/discovery_chain_endpoint_test.go
  agent/proxycfg/manager_test.go
  agent/proxycfg/state_test.go
  agent/proxycfg/testing.go
  agent/structs/discovery_chain.go
  agent/xds/clusters.go
  agent/xds/endpoints.go
  agent/xds/listeners.go
  agent/xds/naming.go
  agent/xds/routes.go
  agent/xds/sni.go
  api/discovery_chain.go
  api/discovery_chain_test.go
Labels: theme/connect

#6348 connect: ensure time.Duration fields retain their human readable forms in the API
  agent/structs/config_entry_discoverychain.go
  agent/structs/discovery_chain.go
  api/config_entry.go
  api/config_entry_discoverychain.go
  api/discovery_chain.go
Labels: theme/connect

#6352 docs: Fix typo layey > layer
  website/source/intro/vs/proxies.html.md
Labels: docs

#6350 docs: document how envoy escape hatches work with the discovery chain
  agent/xds/clusters.go
  agent/xds/config.go
  agent/xds/listeners.go
  website/source/docs/connect/l7-traffic-management.html.md
  website/source/docs/connect/proxies/envoy.md
Labels: docs, theme/connect

#6372 docs: remove beta references; leave version notation
  website/source/api/discovery-chain.html.md
  website/source/docs/agent/config-entries/proxy-defaults.html.md
  website/source/docs/agent/config-entries/service-defaults.html.md
  website/source/docs/agent/config-entries/service-resolver.html.md
  website/source/docs/agent/config-entries/service-router.html.md
  website/source/docs/agent/config-entries/service-splitter.html.md
  website/source/docs/agent/config_entries.html.md
  website/source/docs/agent/services.html.md
  website/source/docs/connect/l7-traffic-management.html.md
  website/source/docs/connect/mesh_gateway.html.md
  website/source/docs/connect/proxies/envoy.md
  website/source/docs/connect/registration/service-registration.html.md
  website/source/docs/internals/discovery-chain.html.md
  website/source/docs/internals/index.html.md
  website/source/downloads.html.erb
  website/source/layouts/api.erb
  website/source/layouts/docs.erb
Labels: docs

#6285 ui: Change signature of request/respond methods to take serialized and unserialized data
  ui-v2/app/adapters/acl.js
  ui-v2/app/adapters/application.js
  ui-v2/app/adapters/http.js
  ui-v2/app/adapters/intention.js
  ui-v2/app/adapters/kv.js
  ui-v2/app/adapters/policy.js
  ui-v2/app/adapters/role.js
  ui-v2/app/adapters/session.js
  ui-v2/app/adapters/token.js
  ui-v2/app/serializers/application.js
  ui-v2/app/serializers/token.js
  ui-v2/app/services/client/http.js
  ui-v2/app/services/store.js
  ui-v2/app/templates/dc/acls/tokens/edit.hbs
  ui-v2/tests/acceptance/dc/acls/tokens/clone.feature
  ui-v2/tests/acceptance/steps/dc/acls/tokens/clone-steps.js
  ui-v2/tests/integration/adapters/acl-test.js
  ui-v2/tests/integration/adapters/intention-test.js
  ui-v2/tests/integration/adapters/kv-test.js
  ui-v2/tests/integration/adapters/policy-test.js
  ui-v2/tests/integration/adapters/role-test.js
  ui-v2/tests/integration/adapters/session-test.js
  ui-v2/tests/integration/adapters/token-test.js
  ui-v2/tests/pages/dc/acls/tokens/edit.js
  ui-v2/tests/pages/dc/acls/tokens/index.js
  ui-v2/tests/unit/serializers/application-test.js
  ui-v2/tests/unit/serializers/kv-test.js
Labels: ui

#6376 Only require verify_incoming_rpc for auto_encrypt.allow_tls
  agent/config/builder.go
  agent/config/runtime_test.go
Labels: theme/tls

#6386 ui: HTTPAdapter queryLeader refactor
  ui-v2/app/adapters/acl.js
  ui-v2/app/adapters/application.js
  ui-v2/app/adapters/node.js
  ui-v2/app/adapters/token.js
  ui-v2/app/serializers/node.js
  ui-v2/app/services/store.js
  ui-v2/tests/acceptance/dc/services/instances/show.feature
  ui-v2/tests/helpers/set-cookies.js
  ui-v2/tests/integration/adapters/node-test.js
  ui-v2/tests/integration/serializers/node-test.js
Labels: ui
