Repository hashicorp/consul, pull requests merged in 2020-04, with the labels that each got.

#7552 ui: Fix token duplication bug
  ui-v2/app/adapters/application.js
Labels: backport/1.7, ui

#7393 Fix documentation registering service checks
  website/source/api/agent/check.html.md
Labels: docs

#7533 agent/xds: small cleanup
  agent/xds/clusters.go
  agent/xds/clusters_test.go
  agent/xds/endpoints.go
  agent/xds/listeners.go
  agent/xds/routes.go
  agent/xds/server.go
  agent/xds/xds.go
Labels: theme/internal-cleanup

#7519 cli: send requested help text to stdout
  go.mod
  go.sum
  main.go
  vendor/github.com/mitchellh/cli/.travis.yml
  vendor/github.com/mitchellh/cli/Makefile
  vendor/github.com/mitchellh/cli/cli.go
  vendor/github.com/mitchellh/cli/go.mod
  vendor/github.com/mitchellh/cli/ui_mock.go
  vendor/modules.txt
Labels: theme/cli-cleanup

#7465 docs: Update config reference for log-file
  website/source/docs/agent/options.html.md
Labels: docs, docs-cherrypick

#7427 docs: fix some errors in upgrade-specific
  website/source/docs/upgrade-specific.html.md
Labels: docs, docs-cherrypick

#7568 ui: Add `<ConsulMetadataList />` and use it in 2 places
  ui-v2/app/components/consul-metadata-list/README.mdx
  ui-v2/app/components/consul-metadata-list/index.hbs
  ui-v2/app/components/consul-metadata-list/index.js
  ui-v2/app/templates/dc/nodes/-metadata.hbs
  ui-v2/app/templates/dc/services/-metadata.hbs
Labels: ui

#7575 Fix flapping of mesh gateway connect-service watches
  agent/proxycfg/state.go
  agent/proxycfg/state_test.go
  test/integration/connect/envoy/case-gateways-local/primary/verify.bats
Labels: backport/1.7

#7573 ui: Change global/env url to start at / instead of /consul
  ui-v2/app/components/hashicorp-consul/index.hbs
  ui-v2/config/environment.js
Labels: ui

#7577 Ensure that token clone copies the roles
  agent/consul/acl_endpoint.go
  agent/consul/acl_endpoint_test.go
Labels: backport/1.7

#7586 Document bootstrapACLs deprecation
  website/source/docs/platform/k8s/helm.html.md
Labels: docs, docs-cherrypick

#7595 docs: Add Helm docs for auto-encrypt and external servers
  website/source/docs/platform/k8s/helm.html.md
Labels: docs, docs-cherrypick

#7604 ui: Logout button
  ui-v2/app/components/app-view/index.hbs
  ui-v2/app/components/data-sink/README.mdx
  ui-v2/app/components/data-sink/index.hbs
  ui-v2/app/components/data-sink/index.js
  ui-v2/app/components/empty-state/index.hbs
  ui-v2/app/components/empty-state/index.js
  ui-v2/app/components/hashicorp-consul/index.hbs
  ui-v2/app/components/hashicorp-consul/index.js
  ui-v2/app/mixins/acl/with-actions.js
  ui-v2/app/mixins/token/with-actions.js
  ui-v2/app/routes/application.js
  ui-v2/app/routes/dc/acls.js
  ui-v2/app/services/data-sink/protocols/http.js
  ui-v2/app/services/data-sink/protocols/local-storage.js
  ui-v2/app/services/data-sink/service.js
  ui-v2/app/services/env.js
  ui-v2/app/services/repository/type/event-source.js
  ui-v2/app/styles/base/components/menu-panel/layout.scss
  ui-v2/app/styles/base/components/menu-panel/skin.scss
  ui-v2/app/styles/base/components/popover-menu/index.scss
  ui-v2/app/styles/base/components/popover-menu/layout.scss
  ui-v2/app/styles/components/app-view.scss
  ui-v2/app/styles/components/app-view/skin.scss
  ui-v2/app/styles/components/empty-state.scss
  ui-v2/app/styles/components/empty-state/index.scss
  ui-v2/app/styles/components/empty-state/layout.scss
  ui-v2/app/styles/components/empty-state/skin.scss
  ui-v2/app/styles/components/feedback-dialog.scss
  ui-v2/app/styles/components/index.scss
  ui-v2/app/styles/components/main-nav-horizontal/skin.scss
  ui-v2/app/styles/core/typography.scss
  ui-v2/app/styles/routes/dc/acls/tokens/index.scss
  ui-v2/app/templates/dc/acls/-authorization.hbs
  ui-v2/app/templates/dc/acls/-disabled.hbs
  ui-v2/app/templates/dc/acls/-notifications.hbs
  ui-v2/app/templates/dc/acls/policies/edit.hbs
  ui-v2/app/templates/dc/acls/policies/index.hbs
  ui-v2/app/templates/dc/acls/roles/edit.hbs
  ui-v2/app/templates/dc/acls/roles/index.hbs
  ui-v2/app/templates/dc/acls/tokens/-notifications.hbs
  ui-v2/app/templates/dc/acls/tokens/edit.hbs
  ui-v2/app/templates/dc/acls/tokens/index.hbs
  ui-v2/app/templates/dc/services/index.hbs
  ui-v2/tests/acceptance/dc/acls/tokens/own-no-delete.feature
  ui-v2/tests/acceptance/dc/acls/tokens/use.feature
  ui-v2/tests/steps.js
  ui-v2/tests/unit/mixins/acl/with-actions-test.js
Labels: ui

#7620 docs: Fix broken link to Nomad Consul Connect guide
  website/source/docs/connect/platform/nomad.html.md
Labels: docs, docs-cherrypick

#7624 support envoy 1.14.1
  .circleci/config.yml
  command/connect/envoy/envoy.go
  command/connect/envoy/testdata/access-log-path.golden
  command/connect/envoy/testdata/defaults.golden
  command/connect/envoy/testdata/existing-ca-file.golden
  command/connect/envoy/testdata/extra_-multiple.golden
  command/connect/envoy/testdata/extra_-single.golden
  command/connect/envoy/testdata/grpc-addr-config.golden
  command/connect/envoy/testdata/grpc-addr-env.golden
  command/connect/envoy/testdata/grpc-addr-flag.golden
  command/connect/envoy/testdata/grpc-addr-unix.golden
  command/connect/envoy/testdata/stats-config-override.golden
  command/connect/envoy/testdata/token-arg.golden
  command/connect/envoy/testdata/token-env.golden
  command/connect/envoy/testdata/token-file-arg.golden
  command/connect/envoy/testdata/token-file-env.golden
  command/connect/envoy/testdata/zipkin-tracing-config.golden
  test/integration/connect/envoy/run-tests.sh
  website/source/docs/connect/proxies/envoy.md
Labels: envoy

#7626 Adding API version for example call
  website/source/api/operator/autopilot.html.md
Labels: docs

#7596 agent/cache: move typeEntry lookup to the edge
  agent/cache/cache.go
  agent/cache/watch.go
Labels: theme/internal-cleanup

#7585 agent/cache: Small changes to hopefully improve readability
  agent/agent.go
  agent/cache/cache.go
  agent/cache/entry.go
  agent/cache/watch.go
  agent/snapshot_endpoint.go
Labels: theme/internal-cleanup

#7387 docs: Link to compatibility matrix for imageEnvoy
  website/source/docs/platform/k8s/helm.html.md
Labels: docs

#7642 Consul on Kubernetes Learn Guide Links
  website/source/docs/platform/k8s/eks.html.md
  website/source/docs/platform/k8s/index.html.md
  website/source/layouts/docs.erb
Labels: docs, docs-cherrypick

#7614 Allow the bootstrap endpoint to be disabled in enterprise.
  agent/consul/acl_endpoint.go
  agent/consul/acl_server_oss.go
Labels: backport/1.7

#7558 Update the Client code to use the common version checking infrastructure
  agent/consul/acl_client.go
  agent/consul/acl_server.go
  agent/consul/leader.go
  agent/consul/leader_test.go
  agent/consul/util.go
Labels: backport/1.7

#7632 ui: Redesign - Create ConsulExternalSource
  ui-v2/app/components/consul-external-source/index.hbs
  ui-v2/app/components/consul-external-source/index.js
  ui-v2/app/components/consul-service-list/index.hbs
  ui-v2/app/styles/base/icons/base-variables.scss
  ui-v2/app/styles/components/composite-row/layout.scss
  ui-v2/app/styles/components/composite-row/skin.scss
  ui-v2/app/styles/components/consul-external-source.scss
  ui-v2/app/styles/components/consul-service-list/layout.scss
  ui-v2/app/styles/components/consul-service-list/skin.scss
  ui-v2/app/styles/components/index.scss
  ui-v2/app/styles/components/list-collection.scss
  ui-v2/app/styles/components/tag-list/layout.scss
  ui-v2/app/templates/dc/services/index.hbs
  ui-v2/ember-cli-build.js
  ui-v2/tests/acceptance/dc/services/index.feature
  ui-v2/tests/integration/components/consul-external-source-test.js
Labels: ui

#7644 ui: Lazily detect HTTP protocol
  ui-v2/app/utils/get-environment.js
Labels: backport/1.7, ui

#7615 ui: Per Service Intentions Tab
  ui-v2/app/adapters/intention.js
  ui-v2/app/controllers/dc/services/show/intentions.js
  ui-v2/app/instance-initializers/event-source.js
  ui-v2/app/mixins/intention/with-actions.js
  ui-v2/app/routes/dc/intentions/edit.js
  ui-v2/app/routes/dc/services/show.js
  ui-v2/app/routes/dc/services/show/intentions.js
  ui-v2/app/services/repository/intention.js
  ui-v2/app/templates/dc/intentions/edit.hbs
  ui-v2/app/templates/dc/services/show.hbs
  ui-v2/app/templates/dc/services/show/intentions.hbs
  ui-v2/tests/acceptance/dc/intentions/index.feature
  ui-v2/tests/acceptance/dc/services/show/intentions.feature
  ui-v2/tests/acceptance/steps/dc/intentions/index-steps.js
  ui-v2/tests/acceptance/steps/dc/services/show/intentions-steps.js
  ui-v2/tests/pages.js
  ui-v2/tests/pages/components/consul-intention-list.js
  ui-v2/tests/pages/dc/intentions/index.js
  ui-v2/tests/pages/dc/services/show.js
Labels: theme/ui

#7649 Adding links to new GS track in learn
  website/source/docs/connect/connect-internals.html.md
  website/source/docs/connect/index.html.md
  website/source/docs/connect/security.html.md
  website/source/docs/platform/k8s/index.html.md
  website/source/docs/platform/k8s/run.html.md
Labels: type/docs

#7650 agent/structs: Remove ServiceID.Init and CheckID.Init
  agent/agent.go
  agent/agent_endpoint.go
  agent/local/state.go
  agent/structs/structs.go
  agent/ui_endpoint.go
Labels: theme/internal-cleanup

#7647 agent/cache: Make all cache options RegisterOptions
  agent/agent.go
  agent/cache-types/catalog_datacenters.go
  agent/cache-types/catalog_list_services.go
  agent/cache-types/catalog_service_list.go
  agent/cache-types/catalog_services.go
  agent/cache-types/config_entry.go
  agent/cache-types/connect_ca_leaf.go
  agent/cache-types/connect_ca_leaf_test.go
  agent/cache-types/connect_ca_root.go
  agent/cache-types/discovery_chain.go
  agent/cache-types/federation_state_list_gateways.go
  agent/cache-types/gateway_services.go
  agent/cache-types/health_services.go
  agent/cache-types/intention_match.go
  agent/cache-types/node_services.go
  agent/cache-types/options.go
  agent/cache-types/prepared_query.go
  agent/cache-types/resolved_service_config.go
  agent/cache-types/service_checks.go
  agent/cache-types/service_dump.go
  agent/cache/cache.go
  agent/cache/cache_test.go
  agent/cache/mock_Request.go
  agent/cache/mock_Type.go
  agent/cache/testing.go
  agent/cache/type.go
  agent/cache/watch.go
  agent/cache/watch_test.go
  agent/proxycfg/testing.go
Labels: theme/internal-cleanup

#7641 agent/cache: reduce function arguments by removing duplicates
  agent/cache/cache.go
  agent/cache/watch.go
Labels: theme/internal-cleanup

#7680 ci: Upgrade gotestsum to v0.4.2
  .circleci/config.yml
Labels: type/ci

#7683 ui: Instance detail redesign
  ui-v2/app/components/healthcheck-list/index.hbs
  ui-v2/app/router.js
  ui-v2/app/routes/dc/services/instance/healthchecks.js
  ui-v2/app/routes/dc/services/instance/index.js
  ui-v2/app/routes/dc/services/instance/servicechecks.js
  ui-v2/app/styles/app.scss
  ui-v2/app/styles/base/components/tabs/layout.scss
  ui-v2/app/styles/components/app-view/layout.scss
  ui-v2/app/styles/routes/dc/service/index.scss
  ui-v2/app/templates/dc/services/instance.hbs
  ui-v2/app/templates/dc/services/instance/healthchecks.hbs
  ui-v2/app/templates/dc/services/instance/nodechecks.hbs
  ui-v2/app/templates/dc/services/instance/servicechecks.hbs
  ui-v2/tests/acceptance/dc/services/instances/gateway.feature
  ui-v2/tests/acceptance/dc/services/instances/proxy.feature
  ui-v2/tests/acceptance/dc/services/instances/show.feature
  ui-v2/tests/acceptance/dc/services/instances/sidecar-proxy.feature
  ui-v2/tests/acceptance/dc/services/instances/with-proxy.feature
  ui-v2/tests/acceptance/dc/services/instances/with-sidecar.feature
  ui-v2/tests/pages/dc/services/instance.js
Labels: theme/ui

#7681 ui: Use DataSources in ACLs area
  ui-v2/app/components/child-selector/index.hbs
  ui-v2/app/components/child-selector/index.js
  ui-v2/app/components/data-source/index.js
  ui-v2/app/components/policy-form/index.hbs
  ui-v2/app/components/policy-form/index.js
  ui-v2/app/components/policy-selector/index.hbs
  ui-v2/app/components/policy-selector/index.js
  ui-v2/app/mixins/with-event-source.js
  ui-v2/app/models/policy.js
  ui-v2/app/models/role.js
  ui-v2/app/services/data-source/protocols/http.js
  ui-v2/app/services/data-source/service.js
  ui-v2/app/services/repository.js
  ui-v2/tests/acceptance/dc/acls/policies/as-many/remove.feature
  ui-v2/tests/integration/services/repository/policy-test.js
  ui-v2/tests/integration/services/repository/role-test.js
Labels: theme/ui

#7687 ui: Redesign - Breadcrumbs styling
  ui-v2/app/styles/base/components/breadcrumbs/index.scss
  ui-v2/app/styles/base/components/breadcrumbs/layout.scss
  ui-v2/app/styles/base/components/breadcrumbs/skin.scss
  ui-v2/app/templates/dc/services/instance.hbs
Labels: theme/ui

#7690 Fix check deletion in anti-entropy sync
  agent/local/state.go
Labels: backport/1.7

#7548 Add callouts to Enterprise features
  website/components/enterprise-alert/index.jsx
  website/layouts/api.jsx
  website/layouts/docs.jsx
  website/layouts/intro.jsx
  website/pages/api-docs/acl/auth-methods.mdx
  website/pages/api-docs/acl/binding-rules.mdx
  website/pages/api-docs/acl/index.mdx
  website/pages/api-docs/acl/policies.mdx
  website/pages/api-docs/acl/roles.mdx
  website/pages/api-docs/acl/tokens.mdx
  website/pages/api-docs/agent/connect.mdx
  website/pages/api-docs/agent/index.mdx
  website/pages/api-docs/catalog.mdx
  website/pages/api-docs/config.mdx
  website/pages/api-docs/coordinate.mdx
  website/pages/api-docs/health.mdx
  website/pages/api-docs/kv.mdx
  website/pages/api-docs/namespaces.mdx
  website/pages/api-docs/operator/area.mdx
  website/pages/api-docs/operator/license.mdx
  website/pages/api-docs/operator/segment.mdx
  website/pages/api-docs/query.mdx
  website/pages/api-docs/session.mdx
  website/pages/api-docs/txn.mdx
  website/pages/docs/acl/acl-legacy.mdx
  website/pages/docs/acl/acl-rules.mdx
  website/pages/docs/acl/acl-system.mdx
  website/pages/docs/acl/auth-methods/kubernetes.mdx
  website/pages/docs/agent/config-entries/index.mdx
  website/pages/docs/agent/config-entries/proxy-defaults.mdx
  website/pages/docs/agent/config-entries/service-defaults.mdx
  website/pages/docs/agent/dns.mdx
  website/pages/docs/agent/options.mdx
  website/pages/docs/agent/sentinel.mdx
  website/pages/docs/commands/license.mdx
  website/pages/docs/commands/members.mdx
  website/pages/docs/commands/namespace/create.mdx
  website/pages/docs/commands/namespace/delete.mdx
  website/pages/docs/commands/namespace/index.mdx
  website/pages/docs/commands/namespace/list.mdx
  website/pages/docs/commands/namespace/read.mdx
  website/pages/docs/commands/namespace/update.mdx
  website/pages/docs/commands/namespace/write.mdx
  website/pages/docs/commands/operator/area.mdx
  website/pages/docs/commands/operator/autopilot.mdx
  website/pages/docs/commands/operator/index.mdx
  website/pages/docs/commands/snapshot/agent.mdx
  website/pages/docs/commands/snapshot/index.mdx
  website/pages/docs/enterprise/backups.mdx
  website/pages/docs/enterprise/federation.mdx
  website/pages/docs/enterprise/namespaces.mdx
  website/pages/docs/enterprise/network-segments.mdx
  website/pages/docs/enterprise/read-scale.mdx
  website/pages/docs/enterprise/redundancy.mdx
  website/pages/docs/enterprise/sentinel.mdx
  website/pages/docs/enterprise/upgrades.mdx
  website/pages/docs/k8s/helm.mdx
Labels: type/docs

#7702 ui: Fixup intention notifications and add SyncTime
  ui-v2/app/models/intention.js
  ui-v2/app/templates/dc/intentions/-notifications.hbs
  ui-v2/tests/integration/services/repository/intention-test.js
Labels: theme/ui

#7703 ui: Reuse repo.reconcile and restartWhenAvailable
  ui-v2/app/services/data-source/protocols/http.js
  ui-v2/app/services/repository/type/event-source.js
Labels: theme/ui

#7705 ui: Fix up the padding for FilterBar
  ui-v2/app/styles/routes/dc/acls/tokens/index.scss
Labels: theme/ui

#7704 add validations for auto_encrypt.{tls,allow_tls}
  agent/config/builder.go
  agent/config/runtime_test.go
Labels: backport/1.7

#7697 cli: fix usage of gzip.Reader to better detect corrupt snapshots during save/restore
  command/snapshot/inspect/snapshot_inspect_test.go
  command/snapshot/restore/snapshot_restore_test.go
  command/snapshot/save/snapshot_save_test.go
  go.mod
  go.sum
  lib/testing_httpserver.go
  snapshot/archive.go
  snapshot/snapshot.go
  snapshot/snapshot_test.go
  vendor/github.com/mitchellh/go-testing-interface/README.md
  vendor/github.com/mitchellh/go-testing-interface/go.mod
  vendor/github.com/mitchellh/go-testing-interface/testing.go
  vendor/github.com/mitchellh/go-testing-interface/testing_go19.go
  vendor/modules.txt
Labels: type/bug

#7698 cli: ensure that 'snapshot save' is fsync safe and also only writes to the requested file on success
  command/snapshot/save/snapshot_save.go
  command/snapshot/save/snapshot_save_test.go
  go.mod
  go.sum
  vendor/github.com/rboyer/safeio/.gitignore
  vendor/github.com/rboyer/safeio/.travis.yml
  vendor/github.com/rboyer/safeio/LICENSE
  vendor/github.com/rboyer/safeio/README.md
  vendor/github.com/rboyer/safeio/file.go
  vendor/github.com/rboyer/safeio/go.mod
  vendor/github.com/rboyer/safeio/go.sum
  vendor/github.com/rboyer/safeio/safeio.go
  vendor/modules.txt
Labels: type/bug

#7711 ui: replace Makefile sed directive for coverage
  ui-v2/.istanbul.yml
  ui-v2/GNUmakefile
Labels: theme/ui

#7727 docs: add Helm docs for external servers and bootstrapToken
  website/source/docs/platform/k8s/helm.html.md
Labels: type/docs

#7719 ui: ConsulLoader component
  ui-v2/app/components/app-view/index.hbs
  ui-v2/app/components/consul-loader/README.mdx
  ui-v2/app/components/consul-loader/index.hbs
  ui-v2/app/components/consul-loader/index.js
  ui-v2/app/templates/application.hbs
Labels: theme/ui

#7722 ui: Add a way to reliably figure out where the UI is running
  ui-v2/app/utils/get-environment.js
  ui-v2/tests/unit/utils/get-environment-test.js
Labels: theme/ui

#7729 ui: Add background-color: currentColor to all our icon masks
  ui-v2/app/styles/base/icons/base-placeholders.scss
Labels: theme/ui

#7734 ui: Fix using 'ui-like' KVs when using an empty default nspace
  ui-v2/app/adapters/application.js
  ui-v2/app/helpers/href-mut.js
  ui-v2/app/routes/nspace.js
  ui-v2/app/utils/routing/transitionable.js
  ui-v2/tests/acceptance/dc/kvs/edit.feature
  ui-v2/tests/unit/utils/routing/transitionable-test.js
Labels: backport/1.7, theme/ui

#7744 Fix multiline note on docs website
  website/pages/docs/connect/proxies/envoy.mdx
Labels: type/website

#7739 website: update link to HashiCorp security page
  website/source/downloads.html.erb
Labels: type/website
