Repository hashicorp/consul, pull requests merged in 2020-12, with the labels that each got.

#9305 ui: New overlays
  ui/packages/consul-ui/app/components/action/index.hbs
  ui/packages/consul-ui/app/components/confirmation-alert/action/index.hbs
  ui/packages/consul-ui/app/components/confirmation-alert/action/index.js
  ui/packages/consul-ui/app/components/confirmation-alert/index.hbs
  ui/packages/consul-ui/app/components/informed-action/index.hbs
  ui/packages/consul-ui/app/components/informed-action/index.scss
  ui/packages/consul-ui/app/components/informed-action/layout.scss
  ui/packages/consul-ui/app/components/informed-action/skin.scss
  ui/packages/consul-ui/app/components/overlay/index.scss
  ui/packages/consul-ui/app/components/overlay/none.scss
  ui/packages/consul-ui/app/components/overlay/square-tail.scss
  ui/packages/consul-ui/app/components/tooltip/index.scss
  ui/packages/consul-ui/app/components/topology-metrics/down-lines/index.hbs
  ui/packages/consul-ui/app/components/topology-metrics/down-lines/index.js
  ui/packages/consul-ui/app/components/topology-metrics/popover/index.hbs
  ui/packages/consul-ui/app/components/topology-metrics/popover/index.js
  ui/packages/consul-ui/app/components/topology-metrics/popover/index.scss
  ui/packages/consul-ui/app/components/topology-metrics/up-lines/index.hbs
  ui/packages/consul-ui/app/components/topology-metrics/up-lines/index.js
  ui/packages/consul-ui/app/modifiers/with-overlay.js
  ui/packages/consul-ui/app/styles/base/color/base-variables.scss
  ui/packages/consul-ui/app/styles/base/components/confirmation-alert/index.scss
  ui/packages/consul-ui/app/styles/base/components/confirmation-alert/layout.scss
  ui/packages/consul-ui/app/styles/base/components/confirmation-alert/skin.scss
  ui/packages/consul-ui/app/styles/base/components/index.scss
  ui/packages/consul-ui/app/styles/base/components/menu-panel/index.scss
  ui/packages/consul-ui/app/styles/base/icons/base-variables.scss
  ui/packages/consul-ui/app/styles/base/typography/base-placeholders.scss
  ui/packages/consul-ui/app/styles/components.scss
  ui/packages/consul-ui/app/styles/components/confirmation-alert.scss
  ui/packages/consul-ui/app/styles/typography.scss
  ui/packages/consul-ui/package.json
  ui/yarn.lock
Labels: backport/1.9, theme/ui

#9312 ui: Asyncify Service Model Hooks
  ui/packages/consul-ui/app/models/service-instance.js
  ui/packages/consul-ui/app/routes/dc/services/index.js
  ui/packages/consul-ui/app/routes/dc/services/instance.js
  ui/packages/consul-ui/app/routes/dc/services/show.js
  ui/packages/consul-ui/app/routes/dc/services/show/services.js
Labels: backport/1.9, theme/ui

#9313 ui: Reorganize Tabs CSS
  ui/packages/consul-ui/app/components/tab-nav/index.scss
  ui/packages/consul-ui/app/components/tab-nav/layout.scss
  ui/packages/consul-ui/app/components/tab-nav/skin.scss
  ui/packages/consul-ui/app/components/tab-section/index.hbs
  ui/packages/consul-ui/app/components/tab-section/index.js
  ui/packages/consul-ui/app/styles/base/components/index.scss
  ui/packages/consul-ui/app/styles/components.scss
  ui/packages/consul-ui/app/styles/components/tabs.scss
  ui/packages/consul-ui/app/templates/dc/services/show/topology.hbs
  ui/packages/consul-ui/tests/integration/components/tab-section-test.js
Labels: backport/1.9, theme/ui

#9318 connect: Fix issue with updating config in secondary
  agent/consul/connect_ca_endpoint_test.go
  agent/consul/leader_connect_ca.go
Labels: backport/1.8, backport/1.9, theme/connect

#9273 merge: release/1.9.0
  .changelog/8685.txt
  .changelog/8703.txt
  .changelog/8822.txt
  .changelog/8834.txt
  .changelog/8877.txt
  .changelog/9036.txt
  .changelog/9198.txt
  .changelog/changelog.tmpl
  api/go.mod
  go.mod
  website/data/version.js
  website/pages/downloads/index.jsx
Labels: pr/dependencies, theme/api, type/docs

#9316 ui: ServiceInstance.Name should be the Service.Name, never the Service.ID
  ui/packages/consul-ui/app/models/service-instance.js
  ui/packages/consul-ui/tests/acceptance/dc/services/show.feature
Labels: backport/1.9, theme/ui

#9322 changelog: add entries for secondary datacenter CA fixes
  .changelog/9009.txt
Labels: backport/1.8, backport/1.9

#9323 changelog: add entry for fixing active CA root unset
  .changelog/9009.txt
  .changelog/9318.txt
Labels: backport/1.8, backport/1.9

#9328 changelog: update 1.8.0 goroutine leak to note increasing memory usage
  CHANGELOG.md
Labels: backport/1.8, backport/1.9

#9325 docs: reword lack of additional required files
  website/pages/docs/install/index.mdx
Labels: type/docs, type/docs-cherrypick

#9321 ui: Don't pluralize words when there is only 1 of the item
  ui/packages/consul-ui/app/components/consul/service/list/index.hbs
Labels: backport/1.9, theme/ui

#9333 ui: Lowercase the word 'instance' in Service listings
  ui/packages/consul-ui/app/components/consul/service/list/index.hbs
Labels: backport/1.9, theme/ui

#9337 ui: Native-ize class based helpers
  ui/packages/consul-ui/app/helpers/dom-position.js
  ui/packages/consul-ui/app/helpers/env.js
  ui/packages/consul-ui/app/helpers/filter-predicate.js
  ui/packages/consul-ui/app/helpers/href-mut.js
  ui/packages/consul-ui/app/helpers/href-to.js
  ui/packages/consul-ui/app/helpers/is-href.js
  ui/packages/consul-ui/app/helpers/refresh-route.js
  ui/packages/consul-ui/app/helpers/state-matches.js
  ui/packages/consul-ui/app/helpers/tween-to.js
  ui/packages/consul-ui/app/helpers/uri.js
  ui/packages/consul-ui/package.json
  ui/yarn.lock
Labels: backport/1.9, theme/ui

#9339 ui: Refactor topology components
  ui/packages/consul-ui/app/components/topology-metrics/card.hbs
  ui/packages/consul-ui/app/components/topology-metrics/index.hbs
  ui/packages/consul-ui/app/components/topology-metrics/index.js
  ui/packages/consul-ui/app/components/topology-metrics/series/index.hbs
  ui/packages/consul-ui/app/components/topology-metrics/stats/index.hbs
  ui/packages/consul-ui/app/components/topology-metrics/up-lines/index.js
  ui/packages/consul-ui/app/routes/dc/services/show/topology.js
  ui/packages/consul-ui/app/templates/dc/services/show/topology.hbs
Labels: backport/1.9, theme/ui

#9347 Add changelog for fixing the namespace replication bug from #9271
  .changelog/9271.txt
Labels: backport/1.7, backport/1.8, backport/1.9

#9332 docs: Fix broken URLs in Helm docs
  website/pages/docs/k8s/helm.mdx
Labels: type/docs, type/docs-cherrypick

#9349 Docs: Update the NIA integration program diagram
  website/public/img/nia-integration-program.png
Labels: theme/consul-terraform-sync, type/docs, type/docs-cherrypick

#9336 ui: document-attrs helper
  ui/packages/consul-ui/app/components/app-view/index.hbs
  ui/packages/consul-ui/app/helpers/document-attrs.js
  ui/packages/consul-ui/app/instance-initializers/nspace.js
  ui/packages/consul-ui/app/styles/components/app-view/layout.scss
  ui/packages/consul-ui/app/styles/layout.scss
  ui/packages/consul-ui/app/templates/application.hbs
  ui/packages/consul-ui/app/templates/dc/kv/index.hbs
  ui/packages/consul-ui/tests/unit/helpers/document-attrs-test.js
Labels: backport/1.9, theme/ui

#9344 ui: Change URI helper to a template based approach
  ui/packages/consul-ui/app/components/data-form/index.hbs
  ui/packages/consul-ui/app/components/topology-metrics/series/index.hbs
  ui/packages/consul-ui/app/components/topology-metrics/stats/index.hbs
  ui/packages/consul-ui/app/helpers/render-template.js
  ui/packages/consul-ui/app/helpers/uri.js
  ui/packages/consul-ui/app/services/encoder.js
  ui/packages/consul-ui/app/templates/dc/services/show/intentions/index.hbs
Labels: backport/1.9, theme/ui

#9326 ui: New search/sort/filtering bar for Node > ServiceInstances
  ui/packages/consul-ui/app/adapters/http.js
  ui/packages/consul-ui/app/components/consul/service-instance/list/index.hbs
  ui/packages/consul-ui/app/components/consul/service-instance/search-bar/index.hbs
  ui/packages/consul-ui/app/controllers/dc/nodes/show/services.js
  ui/packages/consul-ui/app/models/node.js
  ui/packages/consul-ui/app/routes/dc/nodes/show/services.js
  ui/packages/consul-ui/app/routes/dc/services/show/instances.js
  ui/packages/consul-ui/app/serializers/http.js
  ui/packages/consul-ui/app/serializers/node.js
  ui/packages/consul-ui/app/serializers/service-instance.js
  ui/packages/consul-ui/app/templates/dc/nodes/show/services.hbs
  ui/packages/consul-ui/app/templates/dc/services/show/instances.hbs
  ui/packages/consul-ui/app/utils/create-fingerprinter.js
  ui/packages/consul-ui/tests/acceptance/components/catalog-filter.feature
  ui/packages/consul-ui/tests/integration/serializers/node-test.js
Labels: backport/1.9, theme/ui

#9350 Create consul version metric with version label
  agent/agent.go
  agent/setup.go
  website/pages/docs/agent/telemetry.mdx
Labels: backport/1.9, theme/telemetry

#9343 docs: Add developer documentation and diagrams for streaming
  contributing/README.md
  contributing/streaming/README.md
  contributing/streaming/event-filtering.mmd
  contributing/streaming/event-filtering.svg
  contributing/streaming/event-publisher-layout.mmd
  contributing/streaming/event-publisher-layout.svg
  contributing/streaming/framing-events.mmd
  contributing/streaming/framing-events.svg
  contributing/streaming/overview.mmd
  contributing/streaming/overview.svg
Labels: theme/contributing, theme/streaming

#9346 ui: Update UI README
  ui/package.json
  ui/packages/consul-ui/README.md
  ui/packages/consul-ui/package.json
  ui/yarn.lock
Labels: backport/1.9, theme/ui

#9358 ui: Send item name down to Stats to call endpoint
  ui/packages/consul-ui/app/components/topology-metrics/index.hbs
Labels: backport/1.9, theme/ui

#9356 ui: Remove old style 'filterable' searching
  ui/packages/consul-ui/app/components/changeable-set/index.hbs
  ui/packages/consul-ui/app/components/changeable-set/index.js
  ui/packages/consul-ui/app/components/child-selector/index.hbs
  ui/packages/consul-ui/app/components/child-selector/index.js
  ui/packages/consul-ui/app/components/consul/upstream-instance/list/index.hbs
  ui/packages/consul-ui/app/components/consul/upstream-instance/list/index.js
  ui/packages/consul-ui/app/components/consul/upstream-instance/search-bar/index.hbs
  ui/packages/consul-ui/app/components/data-collection/README.mdx
  ui/packages/consul-ui/app/components/data-collection/index.hbs
  ui/packages/consul-ui/app/components/data-collection/index.js
  ui/packages/consul-ui/app/helpers/comparator.js
  ui/packages/consul-ui/app/helpers/searchable.js
  ui/packages/consul-ui/app/helpers/selectable-key-values.js
  ui/packages/consul-ui/app/routes/dc/services/instance/upstreams.js
  ui/packages/consul-ui/app/search/filters/node/service.js
  ui/packages/consul-ui/app/search/filters/policy.js
  ui/packages/consul-ui/app/search/filters/role.js
  ui/packages/consul-ui/app/search/filters/service/node.js
  ui/packages/consul-ui/app/search/predicates/upstream-instance.js
  ui/packages/consul-ui/app/services/search.js
  ui/packages/consul-ui/app/templates/dc/services/instance/upstreams.hbs
  ui/packages/consul-ui/app/utils/search/filterable.js
  ui/packages/consul-ui/tests/integration/components/changeable-set-test.js
  ui/packages/consul-ui/tests/unit/helpers/selectable-key-values-test.js
  ui/packages/consul-ui/tests/unit/search/filters/node/service-test.js
  ui/packages/consul-ui/tests/unit/search/filters/policy-test.js
  ui/packages/consul-ui/tests/unit/search/filters/service/node-test.js
  ui/packages/consul-ui/tests/unit/search/predicates/policy-test.js
  ui/packages/consul-ui/tests/unit/search/predicates/role-test.js
  ui/packages/consul-ui/tests/unit/utils/search/filterable-test.js
Labels: backport/1.9, theme/ui

#9357 ui: Use pill/badge components for intention filter options
  ui/packages/consul-ui/app/components/consul/intention/search-bar/index.hbs
  ui/packages/consul-ui/app/components/consul/intention/search-bar/index.scss
Labels: backport/1.9, theme/ui

#9361 [Website] Update alert banner
  website/data/alert-banner.js
Labels: type/docs, type/docs-cherrypick

#9351 acl: global tokens created by auth methods now correctly replicate to secondary datacenters
  .changelog/9351.txt
  agent/consul/acl_endpoint_test.go
  agent/consul/acl_replication_test.go
  agent/consul/acl_replication_types.go
  agent/consul/fsm/commands_oss.go
  agent/consul/state/acl.go
  agent/consul/state/acl_events_test.go
  agent/consul/state/acl_test.go
  agent/structs/acl.go
Labels: backport/1.8, backport/1.9, type/bug

#9202 Filter API Docs
  website/pages/api-docs/features/filtering.mdx
Labels: type/docs, type/docs-cherrypick

#9362 nia docs: add status api
  website/data/docs-navigation.js
  website/pages/docs/nia/api.mdx
  website/pages/docs/nia/installation/configuration.mdx
  website/pages/docs/nia/tasks.mdx
Labels: theme/consul-terraform-sync, type/docs

#9365 docs/nia: securely configure providers
  website/pages/docs/nia/installation/configuration.mdx
  website/pages/docs/nia/installation/install.mdx
  website/pages/docs/nia/tasks.mdx
Labels: theme/consul-terraform-sync, type/docs

#9371 docs/nia: configure agent http limits
  website/pages/docs/nia/installation/configuration.mdx
  website/pages/docs/nia/installation/requirements.mdx
Labels: theme/consul-terraform-sync, type/docs

#9370 ui: Remove random undefined from codemod run
  ui/packages/consul-ui/app/routes/dc.js
Labels: backport/1.9, theme/ui

#9367 ui: Controller dead code removal
  ui/packages/consul-ui/app/controllers/dc.js
  ui/packages/consul-ui/app/controllers/dc/services/instance/upstreams.js
  ui/packages/consul-ui/app/controllers/dc/services/show.js
  ui/packages/consul-ui/app/controllers/settings.js
  ui/packages/consul-ui/app/styles/routes.scss
  ui/packages/consul-ui/app/styles/routes/dc/settings/index.scss
  ui/packages/consul-ui/tests/unit/controllers/dc-test.js
Labels: backport/1.9, theme/ui

#9372 fix 'agent/check/pass/my-check-id' curl example in documentation
  website/pages/api-docs/agent/check.mdx
Labels: backport/1.9, type/docs, type/docs-cherrypick

#9376 docs/nia decodify field type
  website/pages/docs/nia/api.mdx
  website/pages/docs/nia/installation/configuration.mdx
Labels: theme/consul-terraform-sync, type/docs

#9385 ui: Move linting to the `node:test` script
  ui/packages/consul-ui/.eslintignore
  ui/packages/consul-ui/.storybook/main.js
  ui/packages/consul-ui/.template-lintrc.js
  ui/packages/consul-ui/GNUmakefile
  ui/packages/consul-ui/app/components/child-selector/index.js
  ui/packages/consul-ui/app/components/consul/discovery-chain/index.js
  ui/packages/consul-ui/app/components/consul/intention/list/index.js
  ui/packages/consul-ui/app/components/consul/nspace/list/index.js
  ui/packages/consul-ui/app/components/consul/tomography/graph/index.js
  ui/packages/consul-ui/app/components/data-collection/index.js
  ui/packages/consul-ui/app/components/form-component/index.js
  ui/packages/consul-ui/app/components/list-collection/index.js
  ui/packages/consul-ui/app/components/topology-metrics/popover/index.hbs
  ui/packages/consul-ui/app/filter/predicates/policy.js
  ui/packages/consul-ui/app/models/proxy.js
  ui/packages/consul-ui/app/models/service-instance.js
  ui/packages/consul-ui/app/models/service.js
  ui/packages/consul-ui/app/routes/dc/services/show.js
  ui/packages/consul-ui/app/serializers/node.js
  ui/packages/consul-ui/app/services/repository/service-instance.js
  ui/packages/consul-ui/blueprints/adapter-test/index.js
  ui/packages/consul-ui/blueprints/adapter/index.js
  ui/packages/consul-ui/blueprints/model-test/index.js
  ui/packages/consul-ui/blueprints/model/index.js
  ui/packages/consul-ui/blueprints/repository-test/index.js
  ui/packages/consul-ui/blueprints/serializer-test/index.js
  ui/packages/consul-ui/blueprints/serializer/index.js
  ui/packages/consul-ui/lib/colocated-components/index.js
  ui/packages/consul-ui/lib/startup/index.js
  ui/packages/consul-ui/node-tests/config/environment.js
  ui/packages/consul-ui/node-tests/config/utils.js
  ui/packages/consul-ui/package.json
  ui/packages/consul-ui/server/index.js
  ui/packages/consul-ui/tests/integration/serializers/node-test.js
  ui/packages/consul-ui/tests/steps/assertions/form.js
  ui/packages/consul-ui/tests/steps/assertions/page.js
  ui/packages/consul-ui/tests/steps/interactions/click.js
  ui/packages/consul-ui/tests/steps/interactions/form.js
Labels: backport/1.9, theme/ui

#9377 ui: Show local datacenter by default on first visit
  ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs
  ui/packages/consul-ui/app/models/dc.js
  ui/packages/consul-ui/app/serializers/dc.js
  ui/packages/consul-ui/app/services/repository/dc.js
  ui/packages/consul-ui/tests/integration/services/repository/dc-test.js
Labels: backport/1.9, theme/ui

#9386 docs: call out intentions upgrade issue for 1.9.0+
  website/pages/docs/upgrading/upgrade-specific.mdx
Labels: backport/1.9, type/docs, type/docs-cherrypick

#9387 docs/nia update config empty default value formatting
  website/pages/docs/nia/installation/configuration.mdx
Labels: theme/consul-terraform-sync, type/docs

#9389 docs/nia: Add task_env block for Terraform providers
  website/pages/docs/nia/installation/configuration.mdx
Labels: theme/consul-terraform-sync, type/docs

#9390 docs/nia: omit zero-value defaults
  website/pages/docs/nia/installation/configuration.mdx
Labels: theme/consul-terraform-sync, type/docs

#9391 docs/nia: update api default port
  website/pages/docs/nia/api.mdx
  website/pages/docs/nia/installation/configuration.mdx
Labels: theme/consul-terraform-sync, type/docs

#9345 ui: Dev/Test environment configurable metrics
  ui/packages/consul-ui/app/services/repository/metrics.js
  ui/packages/consul-ui/app/services/ui-config.js
  ui/packages/consul-ui/app/utils/get-environment.js
  ui/packages/consul-ui/lib/startup/templates/head.html.js
  ui/packages/consul-ui/tests/acceptance/dc/services/show.feature
  ui/packages/consul-ui/tests/helpers/yadda-annotations.js
  ui/packages/consul-ui/tests/steps/doubles/model.js
  ui/packages/consul-ui/tests/unit/utils/get-environment-test.js
Labels: backport/1.9, theme/ui

#9400 ui: Lint get-environment.js
  ui/packages/consul-ui/app/utils/get-environment.js
Labels: backport/1.9, theme/ui

#9393 docs/nia: update run page
  website/pages/docs/nia/installation/run.mdx
Labels: theme/consul-terraform-sync, type/docs

#9399 ui: Install ember-intl
  ui/packages/consul-ui/.template-lintrc.js
  ui/packages/consul-ui/app/components/consul/lock-session/list/index.hbs
  ui/packages/consul-ui/app/formats.js
  ui/packages/consul-ui/app/helpers/format-number.js
  ui/packages/consul-ui/app/helpers/format-short-time.js
  ui/packages/consul-ui/config/ember-intl.js
  ui/packages/consul-ui/package.json
  ui/packages/consul-ui/tests/acceptance/dc/services/index.feature
  ui/packages/consul-ui/tests/integration/helpers/format-number-test.js
  ui/packages/consul-ui/tests/integration/helpers/format-short-time-test.js
  ui/packages/consul-ui/translations/en-us.yaml
  ui/yarn.lock
Labels: backport/1.9, theme/ui

#9396 Fixed mesh gateway config instructions
  website/pages/docs/connect/gateways/mesh-gateway/index.mdx
Labels: type/docs, type/docs-cherrypick

#9403 ui: Return empty state for no health check in Topology Cards
  ui/packages/consul-ui/app/components/topology-metrics/card.hbs
  ui/packages/consul-ui/app/components/topology-metrics/skin.scss
  ui/packages/consul-ui/app/helpers/service/health-percentage.js
Labels: theme/ui

#9369 Fix a typo in the CHANGELOG
  CHANGELOG.md
Labels: backport/1.9

#9226 update example for tag_name
  website/pages/docs/install/cloud-auto-join.mdx
Labels: type/docs, type/docs-cherrypick

#9404 Rotate Learn tutorials
  website/pages/home/img/learn/Vault.svg
  website/pages/home/index.jsx
Labels: type/docs, type/docs-cherrypick

#9262 docs: deprecate some old filter parameters
  .changelog/9262.txt
  website/pages/api-docs/catalog.mdx
  website/pages/api-docs/health.mdx
Labels: type/docs, type/docs-cherrypick

#9364 update comment to correctly reflect type of data in the oidc auth method config
  website/pages/docs/security/acl/auth-methods/oidc.mdx
Labels: type/docs-cherrypick

#9406 docs/nia: update status api with new language and calculations
  website/pages/docs/nia/api.mdx
  website/pages/docs/nia/tasks.mdx
Labels: theme/consul-terraform-sync, type/docs

#9401 ui: Rearrange Service > Show to load Topology and Routing tabs separately
  ui/packages/consul-ui/app/controllers/dc/services/show.js
  ui/packages/consul-ui/app/routes/dc.js
  ui/packages/consul-ui/app/routes/dc/services/show.js
  ui/packages/consul-ui/app/routes/dc/services/show/index.js
  ui/packages/consul-ui/app/routes/dc/services/show/instances.js
  ui/packages/consul-ui/app/routes/dc/services/show/routing.js
  ui/packages/consul-ui/app/routes/dc/services/show/topology.js
  ui/packages/consul-ui/app/services/repository/dc.js
  ui/packages/consul-ui/app/templates/dc/services/show.hbs
  ui/packages/consul-ui/app/templates/dc/services/show/routing.hbs
  ui/packages/consul-ui/app/templates/dc/services/show/topology.hbs
Labels: backport/1.9, theme/ui

#9402 ui: Set overflow: auto on the tab nav
  ui/packages/consul-ui/app/components/tab-nav/layout.scss
Labels: backport/1.9, theme/ui, type/bug

#9411 ui: Add new dev UI environment variables to the README
  ui/packages/consul-ui/README.md
Labels: backport/1.9, theme/ui

#9408 docs/nia: Add configuration overview and move config page to top level
  website/_redirects
  website/data/docs-navigation.js
  website/pages/docs/nia/api.mdx
  website/pages/docs/nia/configuration.mdx
  website/pages/docs/nia/installation/configure.mdx
  website/pages/docs/nia/installation/install.mdx
  website/pages/docs/nia/installation/requirements.mdx
  website/pages/docs/nia/network-drivers.mdx
  website/pages/docs/nia/tasks.mdx
Labels: theme/consul-terraform-sync, type/docs

#9405 nia/docs 0.1.0-techpreview2
  website/_redirects
  website/data/docs-navigation.js
  website/pages/docs/nia/api.mdx
  website/pages/docs/nia/cli.mdx
  website/pages/docs/nia/configuration.mdx
  website/pages/docs/nia/installation/configuration.mdx
  website/pages/docs/nia/installation/configure.mdx
  website/pages/docs/nia/installation/install.mdx
  website/pages/docs/nia/installation/requirements.mdx
  website/pages/docs/nia/installation/run.mdx
  website/pages/docs/nia/network-drivers.mdx
  website/pages/docs/nia/tasks.mdx
Labels: theme/consul-terraform-sync, type/docs, type/docs-cherrypick

#9413 ui: Show the No Dependencies message when a Topology has no streams
  ui/packages/consul-ui/app/templates/dc/services/show/topology.hbs
Labels: backport/1.9, theme/ui

#9412 ui: Change references in any copy that say L7 to say Layer 7
  ui/packages/consul-ui/app/components/consul/discovery-chain/index.hbs
  ui/packages/consul-ui/app/components/consul/intention/form/fieldsets/index.hbs
  ui/packages/consul-ui/app/components/consul/intention/form/index.hbs
  ui/packages/consul-ui/app/components/consul/intention/list/check/index.hbs
  ui/packages/consul-ui/app/components/consul/intention/list/table/index.hbs
Labels: backport/1.9, theme/ui

#9414 ui: Misc changes for Catalog area
  ui/packages/consul-ui/app/components/consul/service/notifications/index.hbs
  ui/packages/consul-ui/app/controllers/dc/services/instance.js
  ui/packages/consul-ui/app/controllers/dc/services/show.js
  ui/packages/consul-ui/app/routes/dc/services/instance.js
  ui/packages/consul-ui/app/routes/dc/services/show.js
  ui/packages/consul-ui/app/routes/dc/services/show/topology.js
  ui/packages/consul-ui/app/services/repository/metrics.js
  ui/packages/consul-ui/app/templates/dc/nodes/show.hbs
  ui/packages/consul-ui/app/templates/dc/services/index.hbs
  ui/packages/consul-ui/app/templates/dc/services/instance.hbs
  ui/packages/consul-ui/app/templates/dc/services/show.hbs
  ui/packages/consul-ui/app/templates/dc/services/show/topology.hbs
  ui/packages/consul-ui/app/utils/get-environment.js
  ui/packages/consul-ui/tests/unit/controllers/dc/services/instance-test.js
  ui/packages/consul-ui/tests/unit/controllers/dc/services/show-test.js
Labels: backport/1.9, theme/ui

#9324 Use generated helm docs
  website/content/docs/k8s/helm.mdx
Labels: type/docs, type/docs-cherrypick

#9419 ui: Add Local flag to local dc in dropdown
  ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs
  ui/packages/consul-ui/app/styles/base/components/menu-panel/skin.scss
  ui/packages/consul-ui/app/styles/components/main-nav-horizontal/layout.scss
  ui/packages/consul-ui/app/styles/components/main-nav-horizontal/skin.scss
Labels: backport/1.9, theme/ui

#9430 docs: Remove beta tag for 1.8 and 1.9 features
  website/content/api-docs/acl/index.mdx
  website/content/api-docs/connect/intentions.mdx
  website/content/docs/agent/config-entries/index.mdx
  website/content/docs/agent/config-entries/service-intentions.mdx
  website/content/docs/k8s/crds/index.mdx
Labels: type/docs, type/docs-cherrypick

#9425 ui: [BUGFIX] Use InformedAction for KV confirmation dialogs
  ui/packages/consul-ui/app/components/consul/kv/list/index.hbs
Labels: backport/1.9, theme/ui, type/bug

#9424 ui: Fuzzy and Regex searching
  ui/packages/consul-ui/app/components/data-collection/index.js
  ui/packages/consul-ui/app/search/predicates/acl.js
  ui/packages/consul-ui/app/search/predicates/health-check.js
  ui/packages/consul-ui/app/search/predicates/intention.js
  ui/packages/consul-ui/app/search/predicates/kv.js
  ui/packages/consul-ui/app/search/predicates/node.js
  ui/packages/consul-ui/app/search/predicates/nspace.js
  ui/packages/consul-ui/app/search/predicates/policy.js
  ui/packages/consul-ui/app/search/predicates/role.js
  ui/packages/consul-ui/app/search/predicates/service-instance.js
  ui/packages/consul-ui/app/search/predicates/service.js
  ui/packages/consul-ui/app/search/predicates/token.js
  ui/packages/consul-ui/app/services/search.js
  ui/packages/consul-ui/app/utils/search/exact.js
  ui/packages/consul-ui/app/utils/search/fuzzy.js
  ui/packages/consul-ui/app/utils/search/predicate.js
  ui/packages/consul-ui/app/utils/search/regexp.js
  ui/packages/consul-ui/tests/unit/search/predicates/acl-test.js
  ui/packages/consul-ui/tests/unit/search/predicates/intention-test.js
  ui/packages/consul-ui/tests/unit/search/predicates/kv-test.js
  ui/packages/consul-ui/tests/unit/search/predicates/node-test.js
  ui/packages/consul-ui/tests/unit/search/predicates/policy-test.js
  ui/packages/consul-ui/tests/unit/search/predicates/role-test.js
  ui/packages/consul-ui/tests/unit/search/predicates/service-test.js
  ui/packages/consul-ui/tests/unit/search/predicates/token-test.js
Labels: backport/1.9, theme/ui

#9429 Update helm docs for external client agents
  website/content/docs/k8s/helm.mdx
Labels: type/docs

#9431 Ensure type shown for maps in k8s docs
  website/content/docs/k8s/helm.mdx
Labels: type/docs

#9450 Update k8s compat matrix with 0.28
  website/content/docs/k8s/upgrade/compatibility.mdx
Labels: type/docs, type/docs-cherrypick

#9463 Update Helm reference docs
  website/content/docs/k8s/helm.mdx
Labels: type/docs, type/docs-cherrypick
