Repository hashicorp/consul, pull requests merged in 2020-08, with the labels that each got.

#8385 ci: Add check-generated-protobuf
  .circleci/config.yml
  GNUmakefile
  build-support/scripts/proto-gen.sh
  proto/pbacl/acl.pb.go
  proto/pbautoconf/auto_config.pb.go
  proto/pbcommon/common.pb.go
  proto/pbcommon/common_oss.pb.go
  proto/pbconfig/config.pb.go
  proto/pbconnect/connect.pb.go
Labels: backport/1.8, type/ci

#8437 cache-type: Return nil value on error
  agent/cache-types/service_checks.go
Labels: backport/1.8

#8404 Use Logger consistently, instead of LogOutput
  agent/acl_test.go
  agent/agent.go
  agent/consul/client.go
  agent/consul/client_test.go
  agent/consul/config.go
  agent/consul/leader_test.go
  agent/consul/rpc.go
  agent/consul/server.go
  agent/consul/server_test.go
  agent/pool/pool.go
  api/watch/plan.go
  api/watch/watch.go
  command/connect/proxy/proxy.go
  logging/logger.go
  logging/logger_test.go
Labels: backport/1.8, theme/internal-cleanup

#8440 xds: revert setting set_node_on_first_message_only to true when generating envoy bootstrap config
  command/connect/envoy/bootstrap_tpl.go
  command/connect/envoy/testdata/CONSUL_HTTP_ADDR-with-https-scheme-enables-tls.golden
  command/connect/envoy/testdata/access-log-path.golden
  command/connect/envoy/testdata/defaults.golden
  command/connect/envoy/testdata/existing-ca-file.golden
  command/connect/envoy/testdata/extra_-multiple.golden
  command/connect/envoy/testdata/extra_-single.golden
  command/connect/envoy/testdata/grpc-addr-config.golden
  command/connect/envoy/testdata/grpc-addr-env.golden
  command/connect/envoy/testdata/grpc-addr-flag.golden
  command/connect/envoy/testdata/grpc-addr-unix.golden
  command/connect/envoy/testdata/ingress-gateway-address-specified.golden
  command/connect/envoy/testdata/ingress-gateway-no-auto-register.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-and-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-without-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway.golden
  command/connect/envoy/testdata/stats-config-override.golden
  command/connect/envoy/testdata/token-arg.golden
  command/connect/envoy/testdata/token-env.golden
  command/connect/envoy/testdata/token-file-arg.golden
  command/connect/envoy/testdata/token-file-env.golden
  command/connect/envoy/testdata/zipkin-tracing-config.golden
Labels: backport/1.6, backport/1.7, backport/1.8, theme/envoy/xds, type/bug

#8439 Update version.js to 1.8.1
  website/data/version.js
Labels: type/docs-cherrypick

#8406 Mark its own cluster as healthy when rebalancing.
  agent/router/manager.go
  agent/router/manager_internal_test.go
Labels: backport/1.8, theme/internals

#8447 Redirect /mesh to /use-cases/multi-platform-service-mesh
  website/_redirects
Labels: type/docs, type/docs-cherrypick

#8426 Add lifecycle sidecar and init container resource settings docs
  website/pages/docs/k8s/helm.mdx
Labels: type/docs-cherrypick

#8433 AutoConfig implies Connect
  agent/config/builder.go
  agent/config/runtime_test.go
  agent/consul/acl_server.go
  website/pages/docs/agent/options.mdx
Labels: backport/1.8

#8451 Require token replication to be enabled in secondary dcs when ACLs are enabled with AutoConfig
  agent/config/builder.go
  agent/config/runtime_test.go
Labels: backport/1.8

#8454 Specify allowed ingress gateway protocols in docs
  website/pages/docs/agent/config-entries/ingress-gateway.mdx
Labels: theme/connect, theme/ingress-gw, type/docs-cherrypick

#8460 api: bump consul/api to v1.6.0 and consul/sdk to v0.6.0
  api/go.mod
  go.mod
Labels: backport/1.8

#8340 ui: Rework popover-menu auto closing
  ui-v2/app/components/aria-menu/index.hbs
  ui-v2/app/components/aria-menu/index.js
  ui-v2/app/components/hashicorp-consul/index.hbs
  ui-v2/app/components/hashicorp-consul/pageobject.js
  ui-v2/app/components/more-popover-menu/index.hbs
  ui-v2/app/components/popover-menu/index.hbs
  ui-v2/app/components/popover-menu/menu-item/index.hbs
  ui-v2/app/components/popover-menu/menu-item/index.js
  ui-v2/app/components/popover-menu/menu-separator/index.hbs
  ui-v2/app/components/popover-menu/menu-separator/index.js
  ui-v2/app/components/popover-select/index.hbs
  ui-v2/app/components/popover-select/index.js
  ui-v2/package.json
  ui-v2/tests/acceptance/dc/error.feature
  ui-v2/tests/acceptance/dc/services/dc-switch.feature
  ui-v2/tests/acceptance/dc/services/error.feature
  ui-v2/tests/acceptance/dc/services/show/dc-switch.feature
  ui-v2/tests/pages.js
  ui-v2/tests/pages/dc/services/index.js
  ui-v2/tests/pages/dc/services/show.js
  ui-v2/yarn.lock
Labels: theme/ui

#8467 ui: Fix up default namespace no delete test
  ui-v2/tests/acceptance/dc/nspaces/index.feature
Labels: theme/ui

#8405 ui: Add sorting to namespaces
  ui-v2/app/components/consul-nspace-list/index.hbs
  ui-v2/app/components/consul-nspace-list/pageobject.js
  ui-v2/app/controllers/dc/nspaces/index.js
  ui-v2/app/initializers/sort.js
  ui-v2/app/routes/dc/nspaces/index.js
  ui-v2/app/sort/comparators/nspace.js
  ui-v2/app/templates/dc/nspaces/index.hbs
  ui-v2/tests/acceptance/dc/nspaces/index.feature
  ui-v2/tests/acceptance/dc/nspaces/sorting.feature
  ui-v2/tests/acceptance/steps/dc/nspaces/sorting-steps.js
  ui-v2/tests/pages.js
  ui-v2/tests/pages/dc/nspaces/index.js
Labels: backport/1.8, theme/ui

#8468 ui: Dropdown/select improvements
  ui-v2/app/components/aria-menu/index.js
  ui-v2/app/styles/base/components/buttons/index.scss
  ui-v2/app/styles/base/components/buttons/layout.scss
  ui-v2/app/styles/base/components/buttons/skin.scss
  ui-v2/app/styles/components/filter-bar.scss
  ui-v2/app/styles/components/filter-bar/layout.scss
  ui-v2/app/styles/components/filter-bar/skin.scss
  ui-v2/app/styles/components/popover-select.scss
Labels: theme/ui

#8479 ui: Add unique slug key id to proxy
  ui-v2/app/models/proxy.js
  ui-v2/app/utils/create-fingerprinter.js
Labels: backport/1.8, theme/ui

#8480 ui: Passthrough any error from a route:application refresh
  ui-v2/app/controllers/application.js
Labels: backport/1.8, theme/ui

#8476 ui: Add Optgroups and selectedItems to multiple select dropdown and use
  ui-v2/app/components/popover-menu/menu-item/index.hbs
  ui-v2/app/components/popover-select/index.hbs
  ui-v2/app/components/popover-select/index.js
  ui-v2/app/components/popover-select/optgroup/index.hbs
  ui-v2/app/components/popover-select/optgroup/index.js
  ui-v2/app/components/popover-select/option/index.hbs
  ui-v2/app/components/popover-select/option/index.js
  ui-v2/app/components/search-bar/index.hbs
  ui-v2/app/controllers/dc/services/show/instances.js
  ui-v2/app/controllers/dc/services/show/intentions/index.js
  ui-v2/app/initializers/sort.js
  ui-v2/app/services/dom.js
  ui-v2/app/sort/comparators/kv.js
  ui-v2/app/styles/components/app-view/skin.scss
  ui-v2/app/styles/components/buttons.scss
  ui-v2/app/templates/dc/acls/policies/index.hbs
  ui-v2/app/templates/dc/acls/roles/index.hbs
  ui-v2/app/templates/dc/acls/tokens/index.hbs
  ui-v2/app/templates/dc/intentions/index.hbs
  ui-v2/app/templates/dc/kv/index.hbs
  ui-v2/app/templates/dc/nspaces/index.hbs
  ui-v2/app/templates/dc/services/index.hbs
  ui-v2/app/templates/dc/services/show/intentions/index.hbs
  ui-v2/tests/acceptance/dc/acls/roles/sorting.feature
  ui-v2/tests/acceptance/dc/services/show/intentions.feature
  ui-v2/tests/acceptance/dc/services/sorting.feature
Labels: theme/ui

#8481 ui: Reduce reconnection attempts on disconnection
  ui-v2/app/services/client/connections.js
  ui-v2/app/services/client/http.js
  ui-v2/app/utils/dom/event-source/blocking.js
  ui-v2/tests/unit/utils/dom/event-source/blocking-test.js
Labels: backport/1.8, theme/ui

#8474 fsm: Fix snapshot bug with restoring node/service/check indexes
  agent/consul/fsm/snapshot_oss.go
  agent/consul/fsm/snapshot_oss_test.go
  agent/consul/state/catalog.go
  agent/consul/state/catalog_test.go
  agent/consul/state/txn.go
  agent/structs/structs.go
Labels: backport/1.6, backport/1.7, backport/1.8

#8453 sdk: mitigate api test timeout
  sdk/testutil/server.go
Labels: theme/internal-cleanup, theme/testing

#8483 docs: update helm chart reference
  website/pages/docs/k8s/helm.mdx
Labels: type/docs, type/docs-cherrypick

#8471 thread local-only through the layers
  agent/consul/internal_endpoint.go
  agent/consul/rpc.go
  agent/consul/server_test.go
  agent/keyring.go
  agent/keyring_test.go
  agent/operator_endpoint.go
  agent/operator_endpoint_test.go
  agent/router/router.go
Labels: backport/1.8

#8449 ci: bump Go to v1.14.7
  .circleci/config.yml
  build-support/docker/Build-Go.dockerfile
  build-support/docker/Test-Flake.dockerfile
Labels: backport/1.8

#8469 config: make Source an interface to avoid the marshal/unmarshal cycle in auto-config
  agent/agent.go
  agent/agent_endpoint_test.go
  agent/agent_test.go
  agent/auto-config/auto_config.go
  agent/auto-config/auto_config_test.go
  agent/auto-config/builder.go
  agent/auto-config/config_translate.go
  agent/auto-config/config_translate_test.go
  agent/config/agent_limits_test.go
  agent/config/builder.go
  agent/config/builder_test.go
  agent/config/config.go
  agent/config/default.go
  agent/config/default_oss.go
  agent/config/runtime_test.go
  agent/testagent.go
  agent/testagent_test.go
Labels: theme/config

#8470 connect: use stronger validation that ingress gateways have compatible protocols defined for their upstreams
  agent/consul/state/config_entry.go
  agent/consul/state/config_entry_test.go
  agent/structs/config_entry_gateways.go
  agent/structs/config_entry_gateways_test.go
  agent/xds/listeners.go
  agent/xds/routes.go
Labels: backport/1.8

#8500 auto-config: reduce awareness of config
  agent/agent.go
  agent/auto-config/auto_config.go
  agent/auto-config/auto_config_test.go
  agent/auto-config/builder.go
  agent/auto-config/config.go
  agent/config/builder.go
  agent/config/builder_test.go
Labels: theme/config

#8505 Update version.js to 1.8.3
  website/data/version.js
Labels: type/docs-cherrypick

#8455 Document k8s sidecar resource annotations
  website/pages/docs/k8s/connect/overview.mdx
  website/pages/docs/k8s/helm.mdx
Labels: type/docs, type/docs-cherrypick

#8452 Update k8s sync docs
  website/pages/docs/k8s/service-sync.mdx
Labels: type/docs, type/docs-cherrypick

#8365 state: speed up tests that use watchLimit
  agent/consul/state/catalog_test.go
  agent/consul/state/state_store.go
Labels: backport/1.8, theme/testing

#8461 agent/consul: Remove NotifyShutdown
  agent/consul/autopilot_test.go
  agent/consul/client_test.go
  agent/consul/config.go
  agent/consul/leader_test.go
  agent/consul/server.go
  agent/consul/server_test.go
Labels: theme/internal-cleanup

#8463 agent: convert NodeID methods to functions
  agent/agent.go
  agent/agent_test.go
  agent/nodeid.go
  agent/nodeid_test.go
Labels: theme/internal-cleanup

#8482 state: remove unused Store method receiver
  agent/agent.go
  agent/consul/state/acl.go
  agent/consul/state/acl_oss.go
  agent/consul/state/acl_test.go
  agent/consul/state/autopilot.go
  agent/consul/state/catalog.go
  agent/consul/state/catalog_oss.go
  agent/consul/state/config_entry.go
  agent/consul/state/config_entry_oss.go
  agent/consul/state/memdb.go
  agent/consul/state/state_store.go
  agent/consul/state/txn.go
Labels: theme/internal-cleanup

#8473 agent: convert consulConfig method to a function
  agent/agent.go
  agent/agent_oss.go
  agent/keyring.go
  agent/testagent.go
Labels: theme/internal-cleanup

#8484 docs: consul on k8s doesn't support external servers requiring mTLS
  website/pages/docs/k8s/installation/deployment-configurations/servers-outside-kubernetes.mdx
Labels: type/docs, type/docs-cherrypick

#8487 Learn/link updates derek
  website/pages/docs/connect/gateways/mesh-gateway.mdx
  website/pages/docs/connect/gateways/terminating-gateway.mdx
  website/pages/docs/connect/gateways/wan-federation-via-mesh-gateways.mdx
  website/pages/docs/connect/index.mdx
  website/pages/docs/connect/intentions.mdx
  website/pages/docs/connect/observability.mdx
  website/pages/docs/connect/proxies/built-in.mdx
  website/pages/docs/connect/proxies/envoy.mdx
  website/pages/docs/connect/registration/sidecar-service.mdx
  website/pages/docs/connect/security.mdx
  website/pages/docs/enterprise/backups.mdx
  website/pages/docs/enterprise/federation.mdx
  website/pages/docs/enterprise/namespaces.mdx
  website/pages/docs/enterprise/network-segments.mdx
  website/pages/docs/enterprise/redundancy.mdx
  website/pages/docs/enterprise/upgrades.mdx
  website/pages/docs/faq.mdx
  website/pages/docs/guides/acl-index.mdx
  website/pages/docs/guides/acl-legacy.mdx
  website/pages/docs/guides/consul-splitting.mdx
  website/pages/docs/guides/containers-guide.mdx
  website/pages/docs/guides/managing-acl-policies.mdx
  website/pages/docs/install/index.mdx
  website/pages/docs/install/performance.mdx
  website/pages/docs/internals/acl.mdx
  website/pages/docs/internals/architecture.mdx
  website/pages/docs/internals/coordinates.mdx
  website/pages/docs/internals/sessions.mdx
  website/pages/docs/k8s/connect/ingress-gateways.mdx
  website/pages/docs/k8s/helm.mdx
  website/pages/docs/k8s/index.mdx
  website/pages/docs/k8s/installation/multi-cluster/kubernetes.mdx
  website/pages/docs/k8s/service-sync.mdx
  website/pages/docs/partnerships.mdx
  website/pages/docs/upgrading/upgrade-specific.mdx
  website/pages/downloads_tools/index.mdx
  website/pages/intro/index.mdx
Labels: type/docs, type/docs-cherrypick

#8464 docs: add docs to use Connect CA providers with Helm
  website/data/docs-navigation.js
  website/pages/docs/k8s/connect/connect-ca-provider.mdx
  website/pages/docs/k8s/connect/overview.mdx
Labels: type/docs, type/docs-cherrypick

#8402 Added link to Secure Consul on K8S Tutorial
  website/pages/docs/k8s/index.mdx
Labels: type/docs, type/docs-cherrypick

#8509 testing: Use t.cleanup in TestAgent , and fix two flaky tests
  agent/acl_test.go
  agent/agent_endpoint_test.go
  agent/agent_test.go
  agent/dns_test.go
  agent/keyring_test.go
  agent/service_manager_test.go
  agent/testagent.go
  sdk/testutil/io.go
Labels: backport/1.8, theme/testing

#8490 Refactor docs links to learn
  website/pages/docs/acl/acl-rules.mdx
  website/pages/docs/acl/acl-system.mdx
  website/pages/docs/acl/index.mdx
  website/pages/docs/agent/checks.mdx
  website/pages/docs/agent/config-entries/ingress-gateway.mdx
  website/pages/docs/agent/config-entries/proxy-defaults.mdx
  website/pages/docs/agent/config-entries/service-defaults.mdx
  website/pages/docs/agent/config-entries/service-resolver.mdx
  website/pages/docs/agent/config-entries/service-router.mdx
  website/pages/docs/agent/config-entries/service-splitter.mdx
  website/pages/docs/agent/config-entries/terminating-gateway.mdx
  website/pages/docs/agent/dns.mdx
  website/pages/docs/agent/encryption.mdx
  website/pages/docs/agent/index.mdx
  website/pages/docs/agent/kv.mdx
  website/pages/docs/agent/options.mdx
  website/pages/docs/agent/services.mdx
  website/pages/docs/agent/telemetry.mdx
Labels: type/docs-cherrypick

#8491 Refactor docs links to learn 2
  website/pages/docs/commands/acl/bootstrap.mdx
  website/pages/docs/commands/acl/token/update.mdx
  website/pages/docs/commands/force-leave.mdx
  website/pages/docs/commands/license.mdx
  website/pages/docs/commands/lock.mdx
  website/pages/docs/commands/operator/area.mdx
  website/pages/docs/commands/operator/autopilot.mdx
  website/pages/docs/commands/operator/index.mdx
  website/pages/docs/connect/configuration.mdx
  website/pages/docs/connect/connect-internals.mdx
  website/pages/docs/connect/connectivity-tasks.mdx
  website/pages/docs/connect/gateways/index.mdx
  website/pages/docs/connect/gateways/ingress-gateway.mdx
Labels: type/docs-cherrypick

#8488 Refactor api-docs links to learn
  website/pages/api-docs/acl-legacy.mdx
  website/pages/api-docs/acl/auth-methods.mdx
  website/pages/api-docs/acl/binding-rules.mdx
  website/pages/api-docs/acl/index.mdx
  website/pages/api-docs/acl/legacy.mdx
  website/pages/api-docs/acl/policies.mdx
  website/pages/api-docs/acl/roles.mdx
  website/pages/api-docs/acl/tokens.mdx
  website/pages/api-docs/kv.mdx
  website/pages/api-docs/operator/area.mdx
  website/pages/api-docs/operator/autopilot.mdx
  website/pages/api-docs/operator/index.mdx
  website/pages/api-docs/operator/segment.mdx
  website/pages/api-docs/query.mdx
  website/pages/api-docs/session.mdx
Labels: type/docs-cherrypick

#8515 config: unexport fields and resolve TODOs in config.Builder
  agent/config/builder.go
  agent/config/runtime_test.go
Labels: backport/1.8, theme/config

#8210 Adding warning for ACL replication data loss
  website/pages/docs/agent/options.mdx
Labels: type/docs, type/docs-cherrypick

#8528 config: Move some config validation from Agent.Start to config.Builder.Validate
  agent/agent.go
  agent/config/builder.go
  agent/config/builder_test.go
  agent/config/runtime_test.go
  agent/dns.go
  agent/dns/dns.go
  agent/dns_test.go
Labels: theme/config

#8514 testing: small improvements to TestSessionCreate and testutil.retry
  agent/http_test.go
  agent/session_endpoint_test.go
  agent/ui_endpoint_test.go
  sdk/testutil/retry/retry.go
Labels: theme/testing

#8507 ui: Increase spacing between detail items in composite row
  ui-v2/app/styles/components/composite-row/layout.scss
Labels: theme/ui

#8511 agent: extract dependency creation from New
  agent/acl.go
  agent/acl_test.go
  agent/agent.go
  agent/config/builder.go
  agent/config/runtime_test.go
  agent/setup.go
  agent/testagent.go
  command/agent/agent.go
  lib/telemetry.go
  logging/grpc.go
  logging/grpc_test.go
  logging/logger.go
Labels: theme/internal-cleanup

#8535 ui: Redesign Node Lock Sessions Tab
  ui-v2/app/components/consul-lock-session-list/README.mdx
  ui-v2/app/components/consul-lock-session-list/index.hbs
  ui-v2/app/components/consul-lock-session-list/index.js
  ui-v2/app/helpers/format-time.js
  ui-v2/app/styles/base/icons/base-variables.scss
  ui-v2/app/styles/base/icons/icon-placeholders.scss
  ui-v2/app/styles/components/composite-row.scss
  ui-v2/app/styles/components/composite-row/layout.scss
  ui-v2/app/styles/components/composite-row/skin.scss
  ui-v2/app/templates/dc/nodes/show/sessions.hbs
  ui-v2/tests/acceptance/dc/nodes/sessions/list.feature
  ui-v2/tests/integration/components/consul-lock-session-list-test.js
  ui-v2/tests/integration/helpers/format-time-test.js
  ui-v2/tests/pages/dc/nodes/show.js
Labels: theme/ui

#8540 logging: cleanup Setup and configuration
  agent/agent.go
  agent/config/builder.go
  agent/config/runtime.go
  agent/config/runtime_test.go
  agent/setup.go
  command/agent/agent.go
  command/connect/proxy/proxy.go
  logging/grpc.go
  logging/logger.go
  logging/logger_test.go
Labels: theme/config

#8537 Fix panic when decoding 'Connect: null'
  agent/structs/structs.go
  agent/structs/structs_test.go
Labels: backport/1.6, backport/1.7, backport/1.8, theme/api, type/bug

#8542 ui: Add new Service.Mesh* properties for improved sorting
  ui-v2/app/components/consul-service-list/index.hbs
  ui-v2/app/components/consul-upstream-list/index.hbs
  ui-v2/app/controllers/dc/services/index.js
  ui-v2/app/helpers/service/health-checks.js
  ui-v2/app/models/service.js
  ui-v2/app/serializers/service.js
  ui-v2/app/sort/comparators/service.js
  ui-v2/app/templates/dc/services/index.hbs
  ui-v2/tests/integration/serializers/service-test.js
  ui-v2/tests/integration/services/repository/service-test.js
  ui-v2/tests/unit/sort/comparators/service-test.js
Labels: backport/1.8, theme/ui

#8546 testing: Fix govet errors
  agent/consul/acl.go
  agent/consul/acl_endpoint.go
  agent/consul/acl_replication_types.go
  agent/consul/config_replication.go
  agent/consul/federation_state_replication.go
  agent/consul/leader_federation_state_ae.go
Labels: backport/1.8, theme/testing

#7807 website: add link to certification on /community
  website/pages/community/index.jsx
Labels: type/docs-cherrypick

#8562 ui: Tooltip Bugs
  ui-v2/app/components/discovery-chain/index.hbs
  ui-v2/app/components/discovery-chain/index.js
  ui-v2/app/styles/base/components/tooltip/layout.scss
  ui-v2/app/styles/components/discovery-chain/layout.scss
Labels: theme/ui

#8557 ui: Split ember-data service model into service/service-instance
  ui-v2/app/adapters/service-instance.js
  ui-v2/app/components/consul-service-instance-list/index.hbs
  ui-v2/app/controllers/dc/services/show.js
  ui-v2/app/controllers/dc/services/show/instances.js
  ui-v2/app/models/service-instance.js
  ui-v2/app/models/service.js
  ui-v2/app/routes/dc/services/instance/addresses.js
  ui-v2/app/routes/dc/services/instance/upstreams.js
  ui-v2/app/routes/dc/services/show.js
  ui-v2/app/serializers/service-instance.js
  ui-v2/app/services/data-source/protocols/http.js
  ui-v2/app/services/repository/proxy.js
  ui-v2/app/services/repository/service-instance.js
  ui-v2/app/services/repository/service.js
  ui-v2/app/templates/dc/services/instance.hbs
  ui-v2/app/templates/dc/services/instance/addresses.hbs
  ui-v2/app/templates/dc/services/instance/proxy.hbs
  ui-v2/app/templates/dc/services/show.hbs
  ui-v2/app/templates/dc/services/show/instances.hbs
  ui-v2/app/templates/dc/services/show/tags.hbs
  ui-v2/app/utils/create-fingerprinter.js
  ui-v2/tests/integration/adapters/service-instance-test.js
  ui-v2/tests/integration/serializers/service-instance-test.js
  ui-v2/tests/integration/serializers/service-test.js
  ui-v2/tests/integration/services/repository/service-test.js
  ui-v2/tests/unit/adapters/service-instance-test.js
  ui-v2/tests/unit/models/service-instance-test.js
  ui-v2/tests/unit/serializers/service-instance-test.js
  ui-v2/tests/unit/services/repository/service-instance-test.js
Labels: theme/ui

#8545 agent: expose the list of supported envoy versions on /v1/agent/self
  .changelog/8545.txt
  agent/agent_endpoint.go
  agent/agent_endpoint_test.go
  agent/xds/proxysupport/proxysupport.go
Labels: backport/1.7, backport/1.8, theme/connect, theme/consul-nomad

#8572 Fixes table formatting
  website/pages/docs/agent/telemetry.mdx
Labels: type/docs-cherrypick

#8575 Add helpers to the API client to help with getting information from `AgentMember` tags
  .changelog/8575.txt
  api/agent.go
  api/agent_test.go
Labels: backport/1.8

#8559 Move RPC router from Client/Server and into BaseDeps
  agent/agent.go
  agent/agent_test.go
  agent/consul/auto_encrypt.go
  agent/consul/client.go
  agent/consul/client_serf.go
  agent/consul/client_test.go
  agent/consul/coordinate_endpoint.go
  agent/consul/options.go
  agent/consul/server.go
  agent/consul/util.go
  agent/router/manager.go
  agent/router/router.go
  agent/router/router_test.go
  agent/setup.go
  types/area.go
Labels: backport/1.8

#8458 Add http2 and grpc support to ingress gateways
  .changelog/8458.txt
  agent/structs/config_entry_gateways.go
  agent/structs/config_entry_gateways_test.go
  api/config_entry_gateways.go
  test/integration/connect/envoy/case-ingress-gateway-grpc/capture.sh
  test/integration/connect/envoy/case-ingress-gateway-grpc/config_entries.hcl
  test/integration/connect/envoy/case-ingress-gateway-grpc/gateway.hcl
  test/integration/connect/envoy/case-ingress-gateway-grpc/s1.hcl
  test/integration/connect/envoy/case-ingress-gateway-grpc/setup.sh
  test/integration/connect/envoy/case-ingress-gateway-grpc/vars.sh
  test/integration/connect/envoy/case-ingress-gateway-grpc/verify.bats
  test/integration/connect/envoy/main_test.go
  website/pages/docs/agent/config-entries/ingress-gateway.mdx
Labels: backport/1.8

#8567 ui: Redesign Node list page
  ui-v2/app/components/consul-node-list/index.hbs
  ui-v2/app/components/consul-node-list/index.js
  ui-v2/app/controllers/dc/nodes/index.js
  ui-v2/app/initializers/search.js
  ui-v2/app/initializers/sort.js
  ui-v2/app/models/node.js
  ui-v2/app/routes/dc/nodes/index.js
  ui-v2/app/sort/comparators/node.js
  ui-v2/app/styles/base/components/pill/layout.scss
  ui-v2/app/styles/base/components/pill/skin.scss
  ui-v2/app/styles/base/icons/base-variables.scss
  ui-v2/app/styles/components/composite-row/layout.scss
  ui-v2/app/styles/components/pill.scss
  ui-v2/app/templates/dc/nodes/index.hbs
  ui-v2/tests/acceptance/components/catalog-filter.feature
  ui-v2/tests/acceptance/dc/nodes/empty-ids.feature
  ui-v2/tests/acceptance/dc/nodes/index.feature
  ui-v2/tests/acceptance/dc/nodes/navigation.feature
  ui-v2/tests/acceptance/dc/nodes/sorting.feature
  ui-v2/tests/acceptance/page-navigation.feature
  ui-v2/tests/acceptance/steps/dc/nodes/navigation-steps.js
  ui-v2/tests/acceptance/steps/dc/nodes/sorting-steps.js
  ui-v2/tests/acceptance/steps/nodes/sorting-steps.js
  ui-v2/tests/integration/components/consul-node-list-test.js
  ui-v2/tests/pages.js
  ui-v2/tests/pages/dc/nodes/index.js
Labels: theme/ui

#8552 Ensure that Cache options are reloaded when `consul reload` is performed
  agent/agent.go
  agent/agent_test.go
  agent/cache/cache.go
  agent/cache/cache_test.go
Labels: backport/1.8, theme/agent-cache, type/enhancement

#8548 Fix flaky TestACLResolver_Client/Concurrent-Token-Resolve
  agent/cache/testing.go
  agent/cache/watch_test.go
  agent/consul/acl_test.go
Labels: backport/1.8, theme/testing

#8586 Added changelog for #8552
  .changelog/8552.txt
Labels: backport/1.8

#8577 Add missing changelog for PR 8537
  .changelog/8537.txt
Labels: backport/1.8

#8523 Merge of auto-config and auto-encrypt code
  agent/agent.go
  agent/auto-config/auto_config.go
  agent/auto-config/auto_config_test.go
  agent/auto-config/auto_encrypt.go
  agent/auto-config/auto_encrypt_test.go
  agent/auto-config/config.go
  agent/auto-config/config_translate.go
  agent/auto-config/config_translate_test.go
  agent/auto-config/mock_test.go
  agent/auto-config/persist.go
  agent/auto-config/run.go
  agent/auto-config/server_addr.go
  agent/auto-config/tls.go
  agent/auto-config/tls_test.go
  agent/cert-monitor/cert_monitor.go
  agent/cert-monitor/cert_monitor_test.go
  agent/cert-monitor/config.go
  agent/consul/auto_encrypt.go
  agent/consul/auto_encrypt_test.go
  agent/setup.go
  proto/translate.go
  proto/translate_test.go
Labels: backport/1.8

#8584 [1.8.x] Fix the build by upgrading x/time
  go.mod
  go.sum
  vendor/golang.org/x/time/rate/rate.go
  vendor/modules.txt
Labels: pr/dependencies

#8581 logging: Remove t.Parallel from tests
  logging/logfile_test.go
  logging/logger_test.go
  logging/monitor/monitor_test.go
Labels: theme/testing
