Repository hashicorp/consul, pull requests merged in 2020-05, with the labels that each got.

#7740 ui: Amends to the data-sink service/component
  ui-v2/app/services/data-sink/protocols/http.js
  ui-v2/app/services/data-sink/protocols/local-storage.js
  ui-v2/app/services/data-sink/service.js
Labels: theme/ui

#7742 ui: Adds `<StateChart />` component for wiring together Ember+XState
  ui-v2/app/components/state-chart/README.mdx
  ui-v2/app/components/state-chart/action/index.hbs
  ui-v2/app/components/state-chart/action/index.js
  ui-v2/app/components/state-chart/guard/index.hbs
  ui-v2/app/components/state-chart/guard/index.js
  ui-v2/app/components/state-chart/index.hbs
  ui-v2/app/components/state-chart/index.js
  ui-v2/app/services/state.js
  ui-v2/package.json
  ui-v2/yarn.lock
Labels: theme/ui

#7743 ui: Misc CSS amends, mainly changes to empty-state
  ui-v2/app/styles/base/components/anchors/index.scss
  ui-v2/app/styles/components/empty-state/index.scss
  ui-v2/app/styles/components/empty-state/layout.scss
  ui-v2/app/styles/components/empty-state/skin.scss
  ui-v2/app/styles/components/form-elements.scss
  ui-v2/app/styles/components/notice.scss
Labels: theme/ui

#7751 ui: Remove headers from the Healthchecks tab
  ui-v2/app/templates/dc/services/instance/healthchecks.hbs
Labels: theme/ui

#7730 docs: add docs for snapshot agent local_scratch_path option
  website/pages/docs/commands/snapshot/agent.mdx
Labels: type/docs, type/website

#7758 acl: change authmethod.Validator to take a logger
  agent/consul/acl_authmethod.go
  agent/consul/acl_endpoint.go
  agent/consul/authmethod/authmethods.go
  agent/consul/authmethod/kubeauth/k8s.go
  agent/consul/authmethod/testauth/testing.go
Labels: theme/acls

#7714 Various updates to support managed service provider token enhancements
  agent/agent.go
  agent/agent_oss.go
  agent/config/builder.go
  agent/config/builder_oss.go
  agent/config/builder_oss_test.go
  agent/config/config.go
  agent/config/config_oss.go
  agent/config/default.go
  agent/config/runtime_oss_test.go
  agent/config/runtime_test.go
  agent/config/segment_oss_test.go
  agent/consul/acl_endpoint_legacy.go
  agent/token/store.go
  agent/token/store_oss.go
  go.mod
  go.sum
  vendor/github.com/mitchellh/mapstructure/.travis.yml
  vendor/github.com/mitchellh/mapstructure/CHANGELOG.md
  vendor/github.com/mitchellh/mapstructure/go.mod
  vendor/github.com/mitchellh/mapstructure/mapstructure.go
  vendor/modules.txt
Labels: backport/1.7

#7767 ui: Metadata cleanup
  ui-v2/app/router.js
  ui-v2/app/templates/dc/nodes/show.hbs
  ui-v2/app/templates/dc/services/-metadata.hbs
  ui-v2/app/templates/dc/services/instance.hbs
  ui-v2/app/templates/dc/services/instance/metadata.hbs
  ui-v2/tests/acceptance/dc/nodes/show.feature
  ui-v2/tests/acceptance/dc/services/instances/show.feature
  ui-v2/tests/pages/dc/nodes/show.js
  ui-v2/tests/pages/dc/services/instance.js
Labels: theme/ui

#7769 acl: add DisplayName field to auth methods
  agent/consul/acl_endpoint_test.go
  agent/structs/acl.go
  api/acl.go
  command/acl/authmethod/create/authmethod_create.go
  command/acl/authmethod/create/authmethod_create_test.go
  command/acl/authmethod/formatter.go
  command/acl/authmethod/update/authmethod_update.go
  command/acl/authmethod/update/authmethod_update_test.go
  command/acl/token/formatter.go
  website/pages/api-docs/acl/auth-methods.mdx
Labels: theme/acls

#7779 acl: add MaxTokenTTL field to auth methods
  agent/consul/acl_endpoint.go
  agent/consul/acl_endpoint_test.go
  agent/structs/acl.go
  api/acl.go
  command/acl/authmethod/create/authmethod_create.go
  command/acl/authmethod/create/authmethod_create_test.go
  command/acl/authmethod/update/authmethod_update.go
  website/pages/api-docs/acl/auth-methods.mdx
Labels: theme/acls

#7725 docs: add Helm docs for external servers and bootstrapToken
  website/pages/docs/k8s/helm.mdx
Labels: type/docs, type/docs-cherrypick

#7783 Construct a default destination if one does not exist
  agent/consul/discoverychain/compile.go
  agent/consul/discoverychain/compile_test.go
Labels: backport/1.7

#7771 ui: Model Layer for SSO Support
  ui-v2/app/adapters/http.js
  ui-v2/app/adapters/oidc-provider.js
  ui-v2/app/adapters/token.js
  ui-v2/app/initializers/oidc-provider.js
  ui-v2/app/models/oidc-provider.js
  ui-v2/app/models/token.js
  ui-v2/app/serializers/application.js
  ui-v2/app/serializers/oidc-provider.js
  ui-v2/app/serializers/token.js
  ui-v2/app/services/client/http.js
  ui-v2/app/services/repository/oidc-provider.js
  ui-v2/app/services/store.js
  ui-v2/app/utils/dom/event-source/blocking.js
  ui-v2/app/utils/http/consul.js
  ui-v2/app/utils/http/headers.js
  ui-v2/package.json
  ui-v2/tests/integration/adapters/oidc-provider-test.js
  ui-v2/tests/integration/services/repository/discovery-chain-test.js
  ui-v2/tests/integration/services/repository/node-test.js
  ui-v2/tests/integration/services/repository/policy-test.js
  ui-v2/tests/integration/services/repository/service-test.js
  ui-v2/tests/integration/services/repository/token-test.js
  ui-v2/tests/unit/adapters/oidc-provider-test.js
  ui-v2/yarn.lock
Labels: theme/ui

#7781 ui: Redesign - Service List page with Gateways
  ui-v2/app/components/consul-external-source/index.hbs
  ui-v2/app/components/consul-kind/index.hbs
  ui-v2/app/components/consul-kind/index.js
  ui-v2/app/components/consul-service-list/index.hbs
  ui-v2/app/controllers/dc/services/index.js
  ui-v2/app/styles/base/components/pill/layout.scss
  ui-v2/app/styles/base/components/pill/skin.scss
  ui-v2/app/styles/base/icons/base-variables.scss
  ui-v2/app/styles/base/icons/icon-placeholders.scss
  ui-v2/app/styles/components/consul-external-source.scss
  ui-v2/app/styles/components/index.scss
  ui-v2/app/styles/components/pill.scss
  ui-v2/ember-cli-build.js
  ui-v2/tests/acceptance/components/catalog-filter.feature
  ui-v2/tests/acceptance/dc/error.feature
  ui-v2/tests/acceptance/dc/nspaces/manage.feature
  ui-v2/tests/acceptance/dc/services/dc-switch.feature
  ui-v2/tests/acceptance/dc/services/index.feature
  ui-v2/tests/acceptance/dc/services/list.feature
  ui-v2/tests/acceptance/page-navigation.feature
  ui-v2/tests/integration/components/consul-kind.js
  ui-v2/tests/pages/dc/services/index.js
  ui-v2/yarn.lock
Labels: theme/ui

#7772 ui: Tab Improvements (animations/branding)
  ui-v2/app/components/tab-nav/index.hbs
  ui-v2/app/components/tab-nav/index.js
  ui-v2/app/styles/base/animation/index.scss
  ui-v2/app/styles/base/color/frame-placeholders.scss
  ui-v2/app/styles/base/components/form-elements/skin.scss
  ui-v2/app/styles/base/components/menu-panel/skin.scss
  ui-v2/app/styles/base/components/tabs/index.scss
  ui-v2/app/styles/base/components/tabs/layout.scss
  ui-v2/app/styles/base/components/tabs/skin.scss
  ui-v2/app/styles/components/main-header-horizontal.scss
  ui-v2/app/styles/components/tabs.scss
  ui-v2/app/styles/routes/dc/acls/index.scss
  ui-v2/app/styles/variables/index.scss
  ui-v2/tests/integration/components/tab-nav-test.js
  ui-v2/tests/lib/page-object/tabgroup.js
Labels: theme/ui

#7786 OSS code changes for network segments
  agent/consul/flood.go
  agent/consul/server.go
  agent/consul/server_serf.go
  agent/consul/server_test.go
  agent/router/serf_flooder.go
Labels: backport/1.7

#7724 Update k8s instructions for new helm repo
  website/data/docs-navigation.js
  website/pages/docs/k8s/installation/consul-enterprise.mdx
  website/pages/docs/k8s/installation/index.mdx
  website/pages/docs/k8s/operations/index.mdx
  website/pages/docs/k8s/operations/upgrading.mdx
Labels: type/docs, type/docs-cherrypick

#7791 ui: Fix CSS typo
  ui-v2/app/styles/components/main-header-horizontal.scss
Labels: theme/ui

#7793 ui: Remove last instances of 'meta data', replace with 'metadata'
  ui-v2/app/templates/dc/nodes/show/metadata.hbs
  ui-v2/app/templates/dc/services/instance/metadata.hbs
Labels: theme/ui

#7796 ui: Redesign - Gateway Instances List page
  ui-v2/app/routes/dc/services/show.js
  ui-v2/app/templates/dc/services/show.hbs
  ui-v2/tests/acceptance/dc/services/show.feature
  ui-v2/tests/acceptance/dc/services/show/intentions.feature
  ui-v2/yarn.lock
Labels: theme/ui

#7794 acl: oss plumbing to support auth method namespace rules in enterprise
  agent/consul/acl_endpoint.go
  agent/consul/acl_endpoint_oss.go
  agent/consul/acl_endpoint_test.go
  agent/consul/authmethod/kubeauth/k8s_oss.go
  agent/structs/acl.go
  agent/structs/acl_oss.go
  api/acl.go
  website/pages/api-docs/acl/auth-methods.mdx
  website/pages/docs/acl/auth-methods/kubernetes.mdx
Labels: theme/acls

#7799 test: make auth method cli crud test helper ignore the default namespace
  command/acl/authmethod/create/authmethod_create_test.go
  command/acl/authmethod/update/authmethod_update_test.go
Labels: theme/acls

#7723 Add alert banner to website
  website/data/alert-banner.js
  website/package-lock.json
  website/package.json
  website/pages/_app.js
  website/pages/style.css
Labels: type/website

#7736 docs: add docs for configuring ACLs with external servers
  website/source/docs/platform/k8s/servers-outside-kubernetes.html.md
Labels: type/docs

#7745 ui: Redesign - Instance Detail Proxy Info tab
  ui-v2/app/components/app-view/index.hbs
  ui-v2/app/components/copy-button-feedback/index.js
  ui-v2/app/components/healthcheck-list/index.hbs
  ui-v2/app/components/list-collection/index.js
  ui-v2/app/router.js
  ui-v2/app/routes/dc/services/instance.js
  ui-v2/app/routes/dc/services/instance/proxy.js
  ui-v2/app/styles/app.scss
  ui-v2/app/styles/base/components/table/layout.scss
  ui-v2/app/styles/base/components/tabs/layout.scss
  ui-v2/app/styles/components/app-view.scss
  ui-v2/app/styles/components/app-view/index.scss
  ui-v2/app/styles/components/app-view/layout.scss
  ui-v2/app/styles/components/app-view/skin.scss
  ui-v2/app/styles/components/composite-row/index.scss
  ui-v2/app/styles/components/composite-row/layout.scss
  ui-v2/app/styles/components/composite-row/skin.scss
  ui-v2/app/styles/components/consul-service-instance-list.scss
  ui-v2/app/styles/components/consul-service-list.scss
  ui-v2/app/styles/components/dom-recycling-table/index.scss
  ui-v2/app/styles/components/filter-bar/layout.scss
  ui-v2/app/styles/components/healthcheck-output/layout.scss
  ui-v2/app/styles/components/healthcheck-output/skin.scss
  ui-v2/app/styles/components/table.scss
  ui-v2/app/styles/core/typography.scss
  ui-v2/app/styles/routes/dc/services/index.scss
  ui-v2/app/templates/dc/acls/policies/index.hbs
  ui-v2/app/templates/dc/acls/roles/index.hbs
  ui-v2/app/templates/dc/acls/tokens/index.hbs
  ui-v2/app/templates/dc/nodes/show.hbs
  ui-v2/app/templates/dc/services/instance.hbs
  ui-v2/app/templates/dc/services/instance/exposedpaths.hbs
  ui-v2/app/templates/dc/services/instance/proxy.hbs
  ui-v2/app/templates/dc/services/instance/upstreams.hbs
  ui-v2/app/templates/dc/services/show.hbs
  ui-v2/tests/acceptance/dc/services/instances/gateway.feature
  ui-v2/tests/acceptance/dc/services/instances/proxyinfo.feature
  ui-v2/tests/acceptance/dc/services/instances/show.feature
  ui-v2/tests/acceptance/steps/dc/services/instances/proxyinfo-steps.js
  ui-v2/tests/pages/dc/services/instance.js
  ui-v2/tests/pages/dc/services/show.js
Labels: theme/ui

#7805 ui: Update Gateway headers to include Service Kind
  ui-v2/app/styles/components/app-view/layout.scss
  ui-v2/app/templates/dc/services/instance.hbs
  ui-v2/app/templates/dc/services/show.hbs
Labels: theme/ui

#7808 ui: Small CSS tweaks
  ui-v2/app/styles/base/components/tabs/skin.scss
  ui-v2/app/styles/components/dom-recycling-table/layout.scss
Labels: theme/ui

#7812 cli: oss refactors to support making the auth method CLI aware of namespace rules in enterprise
  command/acl/authmethod/create/authmethod_create.go
  command/acl/authmethod/create/authmethod_create_oss.go
  command/acl/authmethod/create/authmethod_create_test.go
  command/acl/authmethod/formatter.go
  command/acl/authmethod/update/authmethod_update.go
  command/acl/authmethod/update/authmethod_update_oss.go
Labels: theme/acls

#7814 docs: fix broken link in Helm docs
  website/source/docs/platform/k8s/run.html.md
Labels: type/docs

#7815 Update license.mdx
  website/pages/docs/commands/license.mdx
Labels: type/docs

#7804 Fix spelling of deregister
  agent/consul/segment_oss.go
  agent/consul/state/catalog.go
  agent/consul/state/catalog_test.go
  logging/monitor/monitor.go
  website/pages/api-docs/query.mdx
  website/pages/docs/agent/telemetry.mdx
  website/pages/docs/connect/registration/sidecar-service.mdx
  website/pages/docs/guides/production-acls.mdx
Labels: type/docs-cherrypick

#7489 ui: Create PopoverSelect, CatalogToolbar, and update tests
  ui-v2/.eslintrc.js
  ui-v2/app/components/catalog-toolbar/index.hbs
  ui-v2/app/components/catalog-toolbar/index.js
  ui-v2/app/components/consul-service-list/index.hbs
  ui-v2/app/components/popover-select/index.hbs
  ui-v2/app/components/popover-select/index.js
  ui-v2/app/controllers/dc/services/index.js
  ui-v2/app/helpers/selectable-key-values.js
  ui-v2/app/styles/base/components/buttons/layout.scss
  ui-v2/app/styles/base/components/buttons/skin.scss
  ui-v2/app/styles/base/components/popover-menu/layout.scss
  ui-v2/app/styles/base/components/popover-menu/skin.scss
  ui-v2/app/styles/base/icons/base-variables.scss
  ui-v2/app/styles/base/icons/icon-placeholders.scss
  ui-v2/app/styles/components/filter-bar.scss
  ui-v2/app/styles/components/filter-bar/layout.scss
  ui-v2/app/styles/components/filter-bar/skin.scss
  ui-v2/app/styles/components/index.scss
  ui-v2/app/styles/components/popover-select.scss
  ui-v2/app/templates/dc/services/index.hbs
  ui-v2/tests/acceptance/dc/services/list-blocking.feature
  ui-v2/tests/acceptance/dc/services/sorting.feature
  ui-v2/tests/acceptance/steps/components/catalog-toolbar-steps.js
  ui-v2/tests/acceptance/steps/dc/services/sorting-steps.js
  ui-v2/tests/integration/components/catalog-toolbar-test.js
  ui-v2/tests/pages.js
  ui-v2/tests/pages/components/catalog-toolbar.js
  ui-v2/tests/pages/components/popover-sort.js
  ui-v2/tests/pages/dc/services/index.js
  ui-v2/tests/steps/assertions/page.js
  ui-v2/tests/unit/helpers/selectable-key-values-test.js
Labels: theme/ui

#7828 ui: Moves/loads policy datacenters info into the policy detail panel
  ui-v2/app/components/policy-selector/index.hbs
Labels: theme/ui

#7830 ui: Improve language surrounding marking a token as local/global
  ui-v2/app/templates/dc/acls/tokens/-fieldsets.hbs
Labels: theme/ui

#7831 ui: Change wording used in the intention forms
  ui-v2/app/components/consul-intention-form/index.hbs
Labels: theme/ui

#7802 docs: add docs for configuring ACLs with external servers
  website/pages/docs/k8s/installation/servers-outside-kubernetes.mdx
Labels: type/docs

#7839 cli: ensure 'acl auth-method update' doesn't deep merge the Config field
  agent/consul/authmethod/testauth/testing.go
  command/acl/authmethod/update/authmethod_update.go
  command/acl/authmethod/update/authmethod_update_test.go
Labels: theme/acls

#7773 docs: fix misleading example for HTTP healthcheck
  website/pages/docs/agent/checks.mdx
Labels: type/docs

#7851 ui: Misc SSO w/Namespace amends
  ui-v2/app/components/auth-form/index.hbs
  ui-v2/app/components/oidc-select/index.hbs
  ui-v2/app/controllers/application.js
Labels: theme/ui

#7852 ui: Remove debugging pause from our acceptance tests
  ui-v2/tests/acceptance/dc/services/show.feature
Labels: theme/ui

#7837 ui: refactor out the taglist component to use a recursive pattern
  ui-v2/app/components/consul-service-instance-list/index.hbs
  ui-v2/app/components/consul-service-list/index.hbs
  ui-v2/app/components/tag-list/index.hbs
  ui-v2/app/components/tag-list/index.js
  ui-v2/app/templates/dc/nodes/show/services.hbs
  ui-v2/app/templates/dc/services/index.hbs
  ui-v2/app/templates/dc/services/instance/tags.hbs
  ui-v2/app/templates/dc/services/show/tags.hbs
  ui-v2/tests/integration/components/tag-list-test.js
Labels: theme/ui

#7820 ui: Add and use ProxyFor to get the `connected with proxy` boolean
  ui-v2/app/controllers/dc/services/index.js
  ui-v2/app/models/service.js
  ui-v2/tests/acceptance/page-navigation.feature
  ui-v2/yarn.lock
Labels: theme/ui

#7836 ui: Restrict %secondary-button to only form buttons in the main content
  ui-v2/app/styles/components/buttons.scss
Labels: theme/ui

#7834 ui: Renames CopyButtonFeedback to CopyButton and use it everywhere
  ui-v2/app/components/copy-button-feedback/index.hbs
  ui-v2/app/components/copy-button-feedback/index.js
  ui-v2/app/components/copy-button/README.mdx
  ui-v2/app/components/copy-button/index.hbs
  ui-v2/app/components/copy-button/index.js
  ui-v2/app/components/healthcheck-list/index.hbs
  ui-v2/app/styles/base/components/tooltip/layout.scss
  ui-v2/app/styles/base/components/tooltip/skin.scss
  ui-v2/app/styles/components/feedback-dialog.scss
  ui-v2/app/templates/dc/acls/edit.hbs
  ui-v2/app/templates/dc/acls/tokens/edit.hbs
  ui-v2/app/templates/dc/intentions/edit.hbs
  ui-v2/app/templates/dc/nodes/show.hbs
  ui-v2/app/templates/dc/services/instance/proxy.hbs
  ui-v2/tests/integration/components/copy-button-feedback-test.js
Labels: theme/ui

#7819 test: Remove t.Parallel() from agent/structs tests
  agent/structs/acl_cache_test.go
  agent/structs/acl_legacy_test.go
  agent/structs/acl_test.go
  agent/structs/check_definition_test.go
  agent/structs/config_entry_discoverychain_test.go
  agent/structs/config_entry_gateways_test.go
  agent/structs/config_entry_test.go
  agent/structs/intention_test.go
  agent/structs/service_definition_test.go
  agent/structs/structs_filtering_test.go
  agent/structs/structs_test.go
Labels: theme/internal-cleanup

#7689 Remove some dead code
  agent/config.go
  agent/discovery_chain_endpoint.go
  agent/http.go
  agent/http_decode_test.go
Labels: theme/internal-cleanup

#7855 added files-to-consul-kv to tools
  website/pages/downloads_tools/index.mdx
Labels: type/docs

#7848 ci: debugging for golangci-lint download failing
  .circleci/config.yml
Labels: type/ci

#7858 ui: Create Linked Services Tab for Terminating Gateways
  ui-v2/app/adapters/gateway.js
  ui-v2/app/models/gateway.js
  ui-v2/app/router.js
  ui-v2/app/routes/dc/services/show.js
  ui-v2/app/routes/dc/services/show/services.js
  ui-v2/app/serializers/gateway.js
  ui-v2/app/services/repository/gateway.js
  ui-v2/app/styles/components/consul-service-list.scss
  ui-v2/app/styles/routes/dc/services/index.scss
  ui-v2/app/templates/dc/services/show.hbs
  ui-v2/app/templates/dc/services/show/services.hbs
  ui-v2/config/environment.js
  ui-v2/tests/acceptance/dc/services/show/gateway-services.feature
  ui-v2/tests/acceptance/steps/dc/services/show/gateway-services-steps.js
  ui-v2/tests/integration/adapters/gateway-test.js
  ui-v2/tests/integration/serializers/gateway-test.js
  ui-v2/tests/integration/services/repository/gateway-test.js
  ui-v2/tests/pages/dc/services/show.js
  ui-v2/tests/unit/adapters/gateway-test.js
  ui-v2/tests/unit/models/gateway-test.js
  ui-v2/tests/unit/serializers/gateway-test.js
  ui-v2/tests/unit/services/repository/gateway-test.js
  ui-v2/yarn.lock
Labels: theme/ui

#7816 Update FAQ + formatting
  website/pages/docs/faq.mdx
Labels: type/docs, type/docs-cherrypick

#7865 ui: Create Upstreams tab for Ingress Gateways
  ui-v2/app/router.js
  ui-v2/app/routes/dc/services/show/upstreams.js
  ui-v2/app/styles/components/composite-row/layout.scss
  ui-v2/app/styles/components/composite-row/skin.scss
  ui-v2/app/styles/components/list-collection.scss
  ui-v2/app/styles/routes/dc/services/index.scss
  ui-v2/app/templates/dc/services/show.hbs
  ui-v2/app/templates/dc/services/show/services.hbs
  ui-v2/app/templates/dc/services/show/upstreams.hbs
  ui-v2/config/environment.js
  ui-v2/tests/acceptance/dc/services/show/services.feature
  ui-v2/tests/acceptance/dc/services/show/upstreams.feature
  ui-v2/tests/acceptance/steps/dc/services/show/services-steps.js
  ui-v2/tests/acceptance/steps/dc/services/show/upstreams-steps.js
  ui-v2/tests/pages/dc/services/show.js
Labels: theme/ui

#7870 UI Release Merge (1.8: ui-staging merge)
  ui-v2/app/adapters/gateway.js
  ui-v2/app/models/gateway.js
  ui-v2/app/router.js
  ui-v2/app/routes/dc/services/show.js
  ui-v2/app/routes/dc/services/show/services.js
  ui-v2/app/routes/dc/services/show/upstreams.js
  ui-v2/app/serializers/gateway.js
  ui-v2/app/services/repository/gateway.js
  ui-v2/app/styles/components/composite-row/layout.scss
  ui-v2/app/styles/components/composite-row/skin.scss
  ui-v2/app/styles/components/consul-service-list.scss
  ui-v2/app/styles/components/list-collection.scss
  ui-v2/app/styles/routes/dc/services/index.scss
  ui-v2/app/templates/dc/services/show.hbs
  ui-v2/app/templates/dc/services/show/services.hbs
  ui-v2/app/templates/dc/services/show/upstreams.hbs
  ui-v2/tests/acceptance/dc/services/show/services.feature
  ui-v2/tests/acceptance/dc/services/show/upstreams.feature
  ui-v2/tests/acceptance/steps/dc/services/show/services-steps.js
  ui-v2/tests/acceptance/steps/dc/services/show/upstreams-steps.js
  ui-v2/tests/integration/adapters/gateway-test.js
  ui-v2/tests/integration/serializers/gateway-test.js
  ui-v2/tests/integration/services/repository/gateway-test.js
  ui-v2/tests/pages/dc/services/show.js
  ui-v2/tests/unit/adapters/gateway-test.js
  ui-v2/tests/unit/models/gateway-test.js
  ui-v2/tests/unit/serializers/gateway-test.js
  ui-v2/tests/unit/services/repository/gateway-test.js
  ui-v2/yarn.lock
Labels: theme/ui

#7861 Update FAQ with Compat Matrix information
  website/pages/docs/faq.mdx
  website/pages/docs/install/index.mdx
Labels: type/docs, type/docs-cherrypick

#7847 docs: docs for jwt and oidc auth methods
  website/data/docs-navigation.js
  website/pages/api-docs/acl/auth-methods.mdx
  website/pages/api-docs/acl/index.mdx
  website/pages/docs/acl/acl-system.mdx
  website/pages/docs/acl/auth-methods/index.mdx
  website/pages/docs/acl/auth-methods/jwt.mdx
  website/pages/docs/acl/auth-methods/kubernetes.mdx
  website/pages/docs/acl/auth-methods/oidc.mdx
  website/pages/docs/acl/index.mdx
  website/pages/docs/agent/options.mdx
  website/pages/docs/commands/acl/auth-method/create.mdx
  website/pages/docs/commands/acl/auth-method/update.mdx
  website/pages/docs/commands/login.mdx
  website/pages/docs/enterprise/index.mdx
  website/pages/docs/guides/managing-acl-policies.mdx
  website/pages/docs/k8s/helm.mdx
  website/pages/partials/jwt_claim_mapping_details.mdx
  website/pages/partials/jwt_or_oidc.mdx
Labels: type/docs, type/website

#7823 Redo PR #7430 for new website (docs for WAN federation over mesh gateways)
  website/data/docs-navigation.js
  website/pages/docs/connect/wan-federation-via-mesh-gateways.mdx
Labels: type/docs

#7880 docs: add audit logging docs to agent configuration
  website/pages/docs/agent/options.mdx
Labels: type/docs

#7885 ui: Styling fixes
  ui-v2/app/components/consul-service-instance-list/index.hbs
  ui-v2/app/components/consul-service-list/index.hbs
  ui-v2/app/components/list-collection/index.js
  ui-v2/app/styles/components/composite-row/skin.scss
  ui-v2/app/templates/dc/services/show/services.hbs
  ui-v2/app/templates/dc/services/show/upstreams.hbs
Labels: theme/ui

#7888 ui: Quote service names when filtering for intentions
  ui-v2/app/routes/dc/services/show.js
  ui-v2/app/services/repository/intention.js
  ui-v2/tests/acceptance/dc/services/show/intentions-error.feature
  ui-v2/tests/acceptance/steps/dc/services/show/intentions-error-steps.js
Labels: theme/ui

#7886 ui: Slightly refactor %composite-rows and reuse ConsulServiceList component
  ui-v2/app/components/consul-service-list/index.hbs
  ui-v2/app/routes/dc/services/show.js
  ui-v2/app/styles/app.scss
  ui-v2/app/styles/base/components/breadcrumbs/layout.scss
  ui-v2/app/styles/components/composite-row.scss
  ui-v2/app/styles/components/consul-intention-list.scss
  ui-v2/app/styles/components/consul-intention-list/index.scss
  ui-v2/app/styles/components/consul-intention-list/layout.scss
  ui-v2/app/styles/components/consul-intention-list/skin.scss
  ui-v2/app/styles/components/consul-service-instance-list.scss
  ui-v2/app/styles/components/consul-service-list.scss
  ui-v2/app/styles/components/index.scss
  ui-v2/app/styles/components/table.scss
  ui-v2/app/styles/routes/dc/services/index.scss
  ui-v2/app/templates/dc/services/show/services.hbs
  ui-v2/app/templates/dc/services/show/upstreams.hbs
  ui-v2/tests/acceptance/dc/services/show/services.feature
  ui-v2/tests/acceptance/dc/services/show/upstreams.feature
  ui-v2/tests/pages/dc/services/show.js
Labels: theme/ui

#7890 Unindenting to remove shell pre-formatting
  website/pages/docs/connect/ingress_gateway.mdx
  website/pages/docs/connect/terminating_gateway.mdx
Labels: type/docs-cherrypick

#7895 website: fix image size on learn callout
  website/components/learn-callout/style.css
Labels: type/docs-cherrypick

#7905 website: update flexible architecture image
  website/pages/use-cases/img/flexible-architecture.png
  website/pages/use-cases/img/flexible-architecture.svg
  website/pages/use-cases/network-middleware-automation.jsx
Labels: type/docs-cherrypick

#7892 ui: Misc discovery chain fixes
  ui-v2/app/components/discovery-chain/index.hbs
  ui-v2/app/components/discovery-chain/index.js
  ui-v2/app/components/discovery-chain/utils.js
  ui-v2/tests/unit/components/discovery-chain/get-alternate-services-test.js
  ui-v2/tests/unit/components/discovery-chain/get-resolvers-test.js
  ui-v2/tests/unit/components/discovery-chain/get-splitters-test.js
Labels: theme/ui

#7893 ui: If an error occurs on the server, surface it in the notification
  ui-v2/app/components/app-view/index.hbs
  ui-v2/app/services/feedback.js
  ui-v2/app/templates/dc/acls/policies/-notifications.hbs
  ui-v2/app/templates/dc/acls/policies/edit.hbs
  ui-v2/app/templates/dc/acls/roles/-notifications.hbs
  ui-v2/app/templates/dc/acls/roles/edit.hbs
  ui-v2/app/templates/dc/acls/tokens/-notifications.hbs
  ui-v2/app/templates/dc/acls/tokens/edit.hbs
  ui-v2/app/templates/dc/intentions/-notifications.hbs
  ui-v2/app/templates/dc/intentions/edit.hbs
  ui-v2/app/templates/dc/kv/-notifications.hbs
  ui-v2/app/templates/dc/kv/edit.hbs
  ui-v2/app/templates/dc/nspaces/-notifications.hbs
  ui-v2/app/templates/dc/nspaces/edit.hbs
Labels: theme/ui

#7907 ui: Misc amends for Safari and Firefox
  ui-v2/app/components/toggle-button/index.js
  ui-v2/app/mixins/with-filtering.js
  ui-v2/app/services/dom.js
  ui-v2/app/styles/base/components/buttons/skin.scss
  ui-v2/app/styles/base/components/popover-menu/skin.scss
Labels: theme/ui

#7911 docs: update the 'consul tls' command docs to match the current flags
  website/pages/docs/commands/tls/ca.mdx
  website/pages/docs/commands/tls/cert.mdx
Labels: type/docs-cherrypick

#7913 ui: Ensure value is always passed to CONSUL_SSO_ENABLED
  ui-v2/config/environment.js
  ui-v2/node-tests/config/environment.js
Labels: backport/1.8, theme/ui

#7909 ui: Delete old unused CSS
  ui-v2/app/styles/app.scss
  ui-v2/app/styles/base/components/action-group/index.scss
  ui-v2/app/styles/base/components/action-group/layout.scss
  ui-v2/app/styles/base/components/action-group/skin.scss
  ui-v2/app/styles/base/components/index.scss
  ui-v2/app/styles/base/components/popover-menu/index.scss
  ui-v2/app/styles/base/components/popover-menu/layout.scss
  ui-v2/app/styles/base/components/popover-menu/skin.scss
  ui-v2/app/styles/base/components/sort-control/index.scss
  ui-v2/app/styles/base/components/sort-control/skin.scss
  ui-v2/app/styles/components/anchors.scss
  ui-v2/app/styles/components/app-view.scss
  ui-v2/app/styles/components/breadcrumbs.scss
  ui-v2/app/styles/components/buttons.scss
  ui-v2/app/styles/components/discovery-chain.scss
  ui-v2/app/styles/components/form-elements.scss
  ui-v2/app/styles/components/healthchecked-resource.scss
  ui-v2/app/styles/components/index.scss
  ui-v2/app/styles/components/modal-dialog.scss
  ui-v2/app/styles/components/notice.scss
  ui-v2/app/styles/components/phrase-editor/index.scss
  ui-v2/app/styles/components/phrase-editor/layout.scss
  ui-v2/app/styles/components/phrase-editor/skin.scss
  ui-v2/app/styles/components/pill.scss
  ui-v2/app/styles/components/popover-select.scss
  ui-v2/app/styles/components/sort-control.scss
  ui-v2/app/styles/components/table.scss
  ui-v2/app/styles/components/tabs.scss
  ui-v2/app/styles/components/tooltip.scss
Labels: theme/ui

#7910 ui: Ensure datacenter is sent to the API when loading in a policy panel
  ui-v2/app/components/child-selector/index.js
  ui-v2/app/components/policy-selector/index.hbs
Labels: backport/1.8, theme/ui

#7918 ui: Settings > Only save the specific setting that you've changed not the entire settings object
  ui-v2/app/controllers/settings.js
  ui-v2/app/routes/settings.js
Labels: backport/1.8, theme/ui

#7917 ci: limit parallelism for Ember builds
  .circleci/config.yml
Labels: type/ci

#7842 Make envoy integration tests a `go test` suite
  .circleci/config.yml
  GNUmakefile
  test/integration/connect/envoy/helpers.bash
  test/integration/connect/envoy/main_test.go
  test/integration/connect/envoy/run-tests.sh
Labels: type/ci

#7922 docs: remove todos
  website/pages/docs/agent/options.mdx
Labels: type/docs-cherrypick

#7894 Fix some bugs/issues found by staticcheck
  agent/agent_endpoint.go
  agent/agent_endpoint_test.go
  agent/cache-types/service_checks_test.go
  agent/consul/autopilot/autopilot.go
  agent/consul/leader_routine_manager.go
  agent/consul/prepared_query/template.go
  agent/consul/state/txn.go
  agent/coordinate_endpoint_test.go
  agent/dns_test.go
  agent/http.go
  agent/http_test.go
  agent/kvs_endpoint_test.go
  agent/router/manager.go
  agent/session_endpoint_test.go
  agent/ui_endpoint_test.go
  agent/xds/endpoints.go
  command/connect/envoy/envoy.go
Labels: theme/internal-cleanup

#7902 Documentation | Connect on Kubernetes | Change an "is" into "can be"
  website/pages/docs/k8s/connect.mdx
Labels: type/docs, type/docs-cherrypick

#7884 docs: Add Dart client to list of Libraries and SDKs
  website/pages/api-docs/libraries-and-sdks.mdx
Labels: type/docs, type/docs-cherrypick

#7929 ui: Blink/Webkit input[type=password] workaround
  ui-v2/app/components/auth-form/index.hbs
  ui-v2/app/components/auth-form/index.js
Labels: theme/ui

#7891 Update ingress/terminating gateway ACL docs
  website/pages/docs/connect/ingress_gateway.mdx
  website/pages/docs/connect/terminating_gateway.mdx
Labels: type/docs-cherrypick

#7930 ui: Implement EmberTooltips to Upstreams
  ui-v2/app/components/tooltip/index.hbs
  ui-v2/app/components/tooltip/index.js
  ui-v2/app/styles/base/components/tooltip/layout.scss
  ui-v2/app/styles/base/components/tooltip/skin.scss
  ui-v2/app/styles/core/typography.scss
  ui-v2/app/templates/dc/services/instance/proxy.hbs
  ui-v2/app/templates/dc/services/show/upstreams.hbs
  ui-v2/package.json
  ui-v2/tests/integration/components/tooltip-test.js
  ui-v2/yarn.lock
Labels: theme/ui

#7941 ui: remove some components/javascript we are no longer using
  ui-v2/app/components/action-group/index.hbs
  ui-v2/app/components/action-group/index.js
  ui-v2/app/components/phrase-editor/index.hbs
  ui-v2/app/components/phrase-editor/index.js
  ui-v2/app/routes/dc/acls.js
  ui-v2/app/utils/model/writable.js
  ui-v2/tests/integration/components/action-group-test.js
  ui-v2/tests/integration/components/phrase-editor-test.js
  ui-v2/tests/unit/utils/model/writable-test.js
Labels: theme/ui

#7943 ui: Make only existing services in Upstreams linkabled with hover effect
  ui-v2/app/components/list-collection/index.hbs
  ui-v2/app/helpers/service/exists.js
  ui-v2/app/styles/components/composite-row.scss
  ui-v2/app/templates/dc/services/show/upstreams.hbs
  ui-v2/tests/integration/helpers/service/exists-test.js
Labels: theme/ui

#7938 connect: ensure proxy-defaults protocol is used for upstreams
  agent/consul/config_endpoint.go
  agent/consul/config_endpoint_test.go
Labels: backport/1.6, backport/1.7, backport/1.8

#7319 Connect: Fix endpoints clusterName when using cluster escape hatch
  agent/xds/endpoints.go
  agent/xds/endpoints_test.go
  agent/xds/testdata/endpoints/connect-proxy-with-default-chain-and-custom-cluster.golden
Labels: theme/connect, theme/envoy/xds

#7954 ui: Create Tags & Meta tab
  ui-v2/app/router.js
  ui-v2/app/routes/dc/services/instance/tags.js
  ui-v2/app/styles/base/components/tabs/layout.scss
  ui-v2/app/templates/dc/services/instance.hbs
  ui-v2/app/templates/dc/services/instance/metadata.hbs
  ui-v2/tests/acceptance/dc/services/instances/show.feature
  ui-v2/tests/pages/dc/services/instance.js
Labels: theme/ui

#7940 ui: New Empty States
  ui-v2/app/components/auth-form/index.hbs
  ui-v2/app/components/empty-state/index.hbs
  ui-v2/app/components/hashicorp-consul/index.hbs
  ui-v2/app/components/hashicorp-consul/index.js
  ui-v2/app/components/modal-dialog/index.hbs
  ui-v2/app/controllers/application.js
  ui-v2/app/services/client/http.js
  ui-v2/app/services/data-source/service.js
  ui-v2/app/services/store.js
  ui-v2/app/styles/base/color/base-variables.scss
  ui-v2/app/styles/components/empty-state/index.scss
  ui-v2/app/styles/components/empty-state/layout.scss
  ui-v2/app/styles/components/empty-state/skin.scss
  ui-v2/app/templates/dc/acls/-authorization.hbs
  ui-v2/app/templates/dc/acls/-disabled.hbs
  ui-v2/app/templates/dc/acls/index.hbs
  ui-v2/app/templates/dc/acls/policies/index.hbs
  ui-v2/app/templates/dc/acls/roles/index.hbs
  ui-v2/app/templates/dc/intentions/index.hbs
  ui-v2/app/templates/dc/kv/index.hbs
  ui-v2/app/templates/dc/nodes/index.hbs
  ui-v2/app/templates/dc/nspaces/index.hbs
  ui-v2/app/templates/dc/services/index.hbs
Labels: theme/ui

#7959 ui: SSO Icon cleanup
  ui-v2/app/styles/base/icons/base-variables.scss
  ui-v2/app/styles/base/icons/icon-placeholders.scss
  ui-v2/app/styles/components/oidc-select/skin.scss
Labels: theme/ui

#7931 agent: handle re-bootstrapping in a secondary datacenter when WAN federation via mesh gateways is configured
  agent/consul/federation_state_replication.go
  agent/consul/gateway_locator.go
  agent/consul/gateway_locator_test.go
  agent/consul/server.go
  lib/slice.go
  lib/slice_test.go
Labels: backport/1.8, theme/federation-usability

#7934 create lib/stringslice package
  agent/consul/acl_endpoint_test.go
  agent/consul/catalog_endpoint_test.go
  agent/consul/fsm/snapshot_oss_test.go
  agent/consul/gateway_locator.go
  agent/consul/health_endpoint_test.go
  agent/consul/internal_endpoint_test.go
  agent/consul/session_endpoint_test.go
  agent/consul/state/catalog_test.go
  agent/structs/config_entry_gateways.go
  lib/string.go
  lib/string_test.go
  lib/stringslice/stringslice.go
  lib/stringslice/stringslice_test.go
Labels: backport/1.8

#7936 Helm docs for k8s mesh gateways and federation
  website/pages/docs/k8s/helm.mdx
Labels: type/docs-cherrypick

#7967 ui: Add blocking queries to gateways
  ui-v2/app/adapters/gateway.js
  ui-v2/app/adapters/service.js
  ui-v2/app/models/gateway.js
  ui-v2/app/models/service.js
  ui-v2/app/routes/dc/services/show.js
  ui-v2/app/serializers/gateway.js
  ui-v2/app/services/client/http.js
  ui-v2/app/services/data-source/protocols/http.js
  ui-v2/app/services/repository.js
  ui-v2/app/services/repository/gateway.js
  ui-v2/app/services/repository/service.js
  ui-v2/app/services/repository/type/event-source.js
  ui-v2/app/templates/dc/services/show/services.hbs
  ui-v2/app/templates/dc/services/show/upstreams.hbs
  ui-v2/tests/integration/adapters/gateway-test.js
  ui-v2/tests/integration/adapters/service-test.js
  ui-v2/tests/integration/serializers/gateway-test.js
  ui-v2/tests/integration/serializers/service-test.js
  ui-v2/tests/integration/services/repository/gateway-test.js
  ui-v2/tests/integration/services/repository/service-test.js
  ui-v2/tests/unit/adapters/gateway-test.js
  ui-v2/tests/unit/models/gateway-test.js
  ui-v2/tests/unit/serializers/gateway-test.js
  ui-v2/tests/unit/services/repository/gateway-test.js
  ui-v2/yarn.lock
Labels: theme/ui

#7973 add gobetween to the Consul tools
  website/pages/downloads_tools/index.mdx
Labels: type/website

#7971 Replace whitelist/blacklist terminology with allowlist/denylist
  acl/static_authorizer.go
  agent/agent.go
  agent/blacklist.go
  agent/connect/uri_signing.go
  agent/consul/authmethod/kubeauth/testing.go
  agent/consul/connect_ca_endpoint.go
  agent/consul/intention_endpoint_test.go
  agent/denylist.go
  agent/denylist_test.go
  agent/http.go
  agent/structs/intention.go
  agent/structs/structs_test.go
  api/connect_intention.go
  build-support/functions/10-util.sh
  build-support/functions/40-publish.sh
  command/intention/create/create.go
  website/pages/docs/acl/acl-legacy.mdx
  website/pages/docs/acl/acl-system.mdx
  website/pages/docs/agent/options.mdx
  website/pages/docs/connect/security.mdx
  website/pages/docs/guides/acl-legacy.mdx
  website/pages/docs/guides/production-acls.mdx
  website/pages/docs/internals/security.mdx
Labels: type/docs, type/docs-cherrypick

#7991 acl: remove the deprecated `acl_enforce_version_8` option
  agent/acl.go
  agent/acl_test.go
  agent/agent.go
  agent/agent_endpoint_test.go
  agent/config/builder.go
  agent/config/config.go
  agent/config/default.go
  agent/config/runtime.go
  agent/config/runtime_test.go
  agent/consul/acl.go
  agent/consul/acl_test.go
  agent/consul/catalog_endpoint.go
  agent/consul/catalog_endpoint_test.go
  agent/consul/config.go
  agent/consul/config_endpoint_test.go
  agent/consul/coordinate_endpoint.go
  agent/consul/coordinate_endpoint_test.go
  agent/consul/discovery_chain_endpoint_test.go
  agent/consul/federation_state_endpoint_test.go
  agent/consul/health_endpoint_test.go
  agent/consul/internal_endpoint_test.go
  agent/consul/kvs_endpoint_test.go
  agent/consul/leader_test.go
  agent/consul/operator_raft_endpoint_test.go
  agent/consul/prepared_query_endpoint.go
  agent/consul/prepared_query_endpoint_test.go
  agent/consul/rpc_test.go
  agent/consul/server.go
  agent/consul/server_test.go
  agent/consul/session_endpoint.go
  agent/consul/session_endpoint_test.go
  agent/http_test.go
  agent/local/state_test.go
  agent/testagent.go
  api/api_test.go
  command/version/version.go
  sdk/testutil/server.go
  testrpc/wait.go
  website/pages/docs/agent/options.mdx
  website/pages/docs/upgrading/upgrade-specific.mdx
Labels: theme/acls
