Repository hashicorp/consul, pull requests merged in 2020-07, with the labels that each got.

#8209 ui: Ensure routing tab is always shown when connect enabled
  ui-v2/app/services/repository/discovery-chain.js
Labels: backport/1.8, theme/ui, type/bug

#8217 Update lock.mdx
  website/pages/docs/commands/lock.mdx
Labels: type/docs-cherrypick

#8218 Consul not returning NXDOMAIN for DNS queries to a non-existent datacenter
  agent/consul/prepared_query_endpoint.go
  agent/consul/prepared_query_endpoint_test.go
  agent/dns.go
  agent/dns_test.go
  agent/prepared_query_endpoint.go
  agent/structs/errors.go
Labels: backport/1.7, backport/1.8

#8204 ui: Redesign - Node service instances tab
  ui-v2/app/components/consul-instance-checks/index.hbs
  ui-v2/app/components/consul-instance-checks/index.js
  ui-v2/app/components/consul-service-instance-list/index.hbs
  ui-v2/app/controllers/dc/nodes/show/services.js
  ui-v2/app/helpers/service/instance-checks.js
  ui-v2/app/router.js
  ui-v2/app/styles/components/composite-row/layout.scss
  ui-v2/app/templates/dc/nodes/show.hbs
  ui-v2/app/templates/dc/nodes/show/services.hbs
  ui-v2/tests/acceptance/components/catalog-filter.feature
  ui-v2/tests/acceptance/dc/nodes/services/list.feature
  ui-v2/tests/acceptance/dc/nodes/show.feature
  ui-v2/tests/integration/components/consul-instance-checks-test.js
  ui-v2/tests/pages.js
  ui-v2/tests/pages/dc/nodes/show.js
  ui-v2/yarn.lock
Labels: backport/1.8, theme/ui

#8214 Landing page update.
  website/pages/home/index.jsx
Labels: type/docs-cherrypick

#8211 Fix a handful of auto encrypt issues
  agent/agent.go
  agent/agent_test.go
  agent/cache-types/connect_ca_leaf.go
  agent/consul/auto_encrypt.go
  agent/consul/auto_encrypt_test.go
  agent/consul/connect_ca_endpoint.go
  agent/consul/server.go
  agent/consul/server_connect.go
  tlsutil/config.go
  tlsutil/config_test.go
Labels: backport/1.8

#7997 Fix typo in configuration documentation
  website/pages/docs/agent/options.mdx
Labels: type/docs, type/docs-cherrypick

#8005 docs: Fix formatting issues on built-in proxy page
  website/pages/docs/connect/proxies/built-in.mdx
Labels: type/docs, type/docs-cherrypick

#8227 Fix typos on commandline flags
  website/pages/docs/agent/options.mdx
Labels: type/docs-cherrypick

#8215 agent/consul: Add support for NotModified to two endpoints
  agent/consul/catalog_endpoint.go
  agent/consul/catalog_endpoint_test.go
  agent/structs/structs.go
Labels: theme/internals, type/enhancement

#8242 Update Algolia CI script
  website/package-lock.json
  website/package.json
  website/scripts/index_search_content.js
Labels: type/docs-cherrypick, type/website

#8243 Append redirects
  website/_redirects
Labels: type/docs-cherrypick, type/website

#8244 Update URLs for gateway docs
  ui-v2/app/components/consul-kind/index.hbs
  ui-v2/app/templates/dc/services/show/services.hbs
  ui-v2/app/templates/dc/services/show/upstreams.hbs
Labels: backport/1.8, theme/ui

#8248 docs: fix link to connect authorize endpoint
  website/pages/docs/connect/intentions.mdx
Labels: type/docs, type/docs-cherrypick

#8233 Minor wording update in subnav
  website/data/subnav.js
Labels: type/docs-cherrypick, type/website

#8190 Append port number to ingress host domain
  agent/xds/routes.go
  agent/xds/routes_test.go
  agent/xds/testdata/routes/ingress-http-multiple-services.golden
  agent/xds/testdata/routes/ingress-splitter-with-resolver-redirect.golden
  agent/xds/testdata/routes/ingress-with-chain-and-router.golden
  agent/xds/testdata/routes/ingress-with-chain-and-splitter.golden
  agent/xds/testdata/routes/ingress-with-grpc-router.golden
  test/integration/connect/envoy/case-ingress-gateway-tls/config_entries.hcl
  test/integration/connect/envoy/case-ingress-gateway-tls/verify.bats
  test/integration/connect/envoy/main_test.go
Labels: backport/1.8

#8251 ui: Re-adds gray backgrounds to old style %pills
  ui-v2/app/styles/components/discovery-chain/skin.scss
  ui-v2/app/styles/components/pill.scss
Labels: backport/1.8, theme/ui

#8088 ui: Remove jQuery from the production build
  ui-v2/app/adapters/http.js
  ui-v2/app/services/client/connections.js
  ui-v2/app/services/client/http.js
  ui-v2/app/services/client/transports/xhr.js
  ui-v2/app/utils/createURL.js
  ui-v2/app/utils/get-object-pool.js
  ui-v2/app/utils/http/create-headers.js
  ui-v2/app/utils/http/create-query-params.js
  ui-v2/app/utils/http/create-url.js
  ui-v2/app/utils/http/error.js
  ui-v2/app/utils/http/request.js
  ui-v2/app/utils/http/xhr.js
  ui-v2/lib/startup/index.js
  ui-v2/package.json
  ui-v2/server/index.js
  ui-v2/tests/integration/adapters/kv-test.js
  ui-v2/tests/integration/adapters/oidc-provider-test.js
  ui-v2/tests/integration/adapters/policy-test.js
  ui-v2/tests/integration/adapters/role-test.js
  ui-v2/tests/integration/adapters/service-test.js
  ui-v2/tests/integration/adapters/session-test.js
  ui-v2/tests/integration/adapters/token-test.js
  ui-v2/tests/test-helper.js
  ui-v2/tests/unit/services/client/connections-test.js
  ui-v2/tests/unit/services/client/transports/xhr-test.js
  ui-v2/tests/unit/utils/get-object-pool-test.js
  ui-v2/tests/unit/utils/http/create-headers-test.js
  ui-v2/tests/unit/utils/http/create-query-params-test.js
  ui-v2/tests/unit/utils/http/create-url-test.js
  ui-v2/tests/unit/utils/http/error-test.js
  ui-v2/tests/unit/utils/http/xhr-test.js
  ui-v2/yarn.lock
Labels: backport/1.8, theme/ui

#8252 docs: Document that dns_config.cache_max_age=0 means "no max age"
  website/pages/docs/agent/options.mdx
Labels: type/docs-cherrypick

#8255 Merge http2 integration test case into grpc case
  test/integration/connect/envoy/case-grpc/verify.bats
  test/integration/connect/envoy/case-http2/capture.sh
  test/integration/connect/envoy/case-http2/s1.hcl
  test/integration/connect/envoy/case-http2/s2.hcl
  test/integration/connect/envoy/case-http2/setup.sh
  test/integration/connect/envoy/case-http2/verify.bats
Labels: theme/connect

#8262 ui: Use empty-state for our small empty states
  ui-v2/app/components/empty-state/index.hbs
  ui-v2/app/components/empty-state/index.js
  ui-v2/app/styles/components/empty-state/layout.scss
  ui-v2/app/styles/core/typography.scss
  ui-v2/app/templates/dc/nodes/show/healthchecks.hbs
  ui-v2/app/templates/dc/nodes/show/metadata.hbs
  ui-v2/app/templates/dc/nodes/show/services.hbs
  ui-v2/app/templates/dc/nodes/show/sessions.hbs
  ui-v2/app/templates/dc/services/instance/metadata.hbs
  ui-v2/app/templates/dc/services/instance/tags.hbs
  ui-v2/app/templates/dc/services/show/instances.hbs
  ui-v2/app/templates/dc/services/show/intentions.hbs
  ui-v2/app/templates/dc/services/show/services.hbs
  ui-v2/app/templates/dc/services/show/tags.hbs
  ui-v2/app/templates/dc/services/show/upstreams.hbs
Labels: backport/1.8, theme/ui

#8263 ui: Fix up styling for the Tags tab
  ui-v2/app/styles/components/tag-list/layout.scss
Labels: backport/1.8, theme/ui

#8264 Added undocumented CONSUL_NAMESPACE to website.
  website/pages/docs/commands/index.mdx
Labels: backport/1.8, type/docs, type/docs-cherrypick

#8267 ui: Enable keyboard access for the sorting dropdown menus
  ui-v2/app/components/aria-menu/index.js
  ui-v2/app/components/popover-select/index.hbs
Labels: backport/1.8, theme/ui

#8272 ui: Extract and organize popover-menu and related from main-nav
  ui-v2/app/components/popover-menu/index.hbs
  ui-v2/app/components/popover-select/pageobject.js
  ui-v2/app/components/popover-sort/pageobject.js
  ui-v2/app/styles/base/components/popover-menu/index.scss
  ui-v2/app/styles/base/components/popover-menu/layout.scss
  ui-v2/app/styles/base/components/popover-menu/skin.scss
  ui-v2/app/styles/base/reset/system.scss
  ui-v2/app/styles/components/empty-state/index.scss
  ui-v2/app/styles/components/main-header-horizontal.scss
  ui-v2/app/styles/components/main-nav-horizontal.scss
  ui-v2/app/styles/components/main-nav-horizontal/index.scss
  ui-v2/app/styles/components/main-nav-horizontal/layout.scss
  ui-v2/app/styles/components/main-nav-horizontal/skin.scss
  ui-v2/app/styles/components/more-popover-menu.scss
  ui-v2/app/styles/components/popover-select.scss
  ui-v2/tests/pages.js
  ui-v2/tests/pages/dc/services/index.js
Labels: backport/1.8, theme/ui

#8273 ui: Replace dom-buffering components with ember-stargate Portals
  ui-v2/app/components/dom-buffer-flush/index.hbs
  ui-v2/app/components/dom-buffer-flush/index.js
  ui-v2/app/components/dom-buffer/index.hbs
  ui-v2/app/components/dom-buffer/index.js
  ui-v2/app/components/modal-dialog/index.hbs
  ui-v2/app/components/modal-dialog/index.js
  ui-v2/app/components/modal-layer/index.hbs
  ui-v2/app/components/modal-layer/index.js
  ui-v2/app/services/dom-buffer.js
  ui-v2/tests/integration/components/dom-buffer-flush-test.js
  ui-v2/tests/integration/components/dom-buffer-test.js
  ui-v2/tests/integration/components/modal-dialog-test.js
  ui-v2/tests/unit/services/dom-buffer-test.js
Labels: backport/1.8, theme/ui

#8274 ui: Use top-level 'named index files' instead of in folder index files
  ui-v2/app/styles/app.scss
  ui-v2/app/styles/components.scss
  ui-v2/app/styles/components/index.scss
  ui-v2/app/styles/components/phrase-editor.scss
  ui-v2/app/styles/layout.scss
  ui-v2/app/styles/routes.scss
  ui-v2/app/styles/typography.scss
  ui-v2/app/styles/variables.scss
  ui-v2/app/styles/variables/skin.scss
Labels: backport/1.8, theme/ui

#8253 Agent Auto Configuration: Refactor RPC endpoint to use interface delegate
  agent/agentpb/auto_config.pb.go
  agent/agentpb/auto_config.proto
  agent/auto-config/auto_config.go
  agent/auto-config/auto_config_test.go
  agent/consul/acl_endpoint.go
  agent/consul/acl_endpoint_legacy.go
  agent/consul/auto_config_endpoint.go
  agent/consul/auto_config_endpoint_test.go
  agent/consul/auto_encrypt_endpoint.go
  agent/consul/catalog_endpoint.go
  agent/consul/config_endpoint.go
  agent/consul/connect_ca_endpoint.go
  agent/consul/coordinate_endpoint.go
  agent/consul/discovery_chain_endpoint.go
  agent/consul/federation_state_endpoint.go
  agent/consul/gateway_locator.go
  agent/consul/health_endpoint.go
  agent/consul/intention_endpoint.go
  agent/consul/internal_endpoint.go
  agent/consul/kvs_endpoint.go
  agent/consul/operator_autopilot_endpoint.go
  agent/consul/operator_raft_endpoint.go
  agent/consul/prepared_query_endpoint.go
  agent/consul/rpc.go
  agent/consul/server.go
  agent/consul/server_test.go
  agent/consul/session_endpoint.go
  agent/consul/txn_endpoint.go
  agent/pool/pool.go
Labels: backport/1.8

#8276 ui: Dependency upgrade
  ui-v2/app/components/consul-kind/index.hbs
  ui-v2/app/components/policy-form/index.hbs
  ui-v2/app/components/role-selector/index.hbs
  ui-v2/app/helpers/from-entries.js
  ui-v2/app/initializers/power-select.js
  ui-v2/app/models/policy.js
  ui-v2/package.json
  ui-v2/yarn.lock
Labels: backport/1.8, theme/ui

#8270 ci: Store a jsonfile for go-test and go-test-api
  .circleci/config.yml
Labels: type/ci

#8237 Remove ACLsEnabled from delegate interface
  agent/acl.go
  agent/acl_endpoint.go
  agent/acl_test.go
  agent/agent.go
  agent/consul/acl.go
  agent/consul/acl_client.go
  agent/consul/acl_endpoint.go
  agent/consul/acl_endpoint_legacy.go
  agent/consul/acl_server.go
  agent/consul/acl_test.go
  agent/consul/acl_token_exp.go
  agent/consul/client.go
  agent/consul/leader.go
  agent/consul/server.go
  agent/http.go
Labels: theme/internal-cleanup

#8231 agent/http: un-embed the http.Server
  agent/agent.go
  agent/agent_endpoint_test.go
  agent/http.go
  agent/http_oss_test.go
  agent/http_test.go
  agent/testagent.go
  agent/ui_endpoint_test.go
Labels: theme/internal-cleanup

#8285 ui: Lint staged no longer requires git add to be specified
  ui-v2/package.json
Labels: backport/1.8, theme/ui

#8286 ui: Adds definition-table class to RTT values table
  ui-v2/app/templates/dc/nodes/show/rtt.hbs
Labels: backport/1.8, theme/ui

#8268 Add Revision to version CLI output and add JSON support
  command/commands_oss.go
  command/version/formatter.go
  command/version/formatter_test.go
  command/version/testdata/json.golden
  command/version/testdata/pretty.golden
  command/version/version.go
  command/version/version_test.go
  main.go
  website/pages/docs/commands/version.mdx
Labels: backport/1.8

#8289 ui: Revert ember-composable-helpers to ~4.0.0 due to faster sort-by
  ui-v2/package.json
  ui-v2/yarn.lock
Labels: backport/1.8, theme/ui

#8108 docs: add section for /health/ingress/:service API
  website/pages/api-docs/catalog.mdx
  website/pages/api-docs/health.mdx
Labels: type/docs, type/docs-cherrypick

#8278 Add api mod support for /catalog/gateway-services
  agent/catalog_endpoint_test.go
  api/catalog.go
  api/catalog_test.go
Labels: backport/1.8

#8293 ui: Ensure any colons in http headers aren't split out
  ui-v2/app/utils/http/create-headers.js
  ui-v2/tests/unit/utils/http/create-headers-test.js
Labels: backport/1.8, theme/ui

#8297 ui: Move dc sorting to the view/template
  ui-v2/app/components/hashicorp-consul/index.hbs
  ui-v2/app/services/repository/dc.js
  ui-v2/app/services/repository/node.js
  ui-v2/tests/integration/services/repository/dc-test.js
Labels: backport/1.8, theme/ui

#8298 ui: Replaces old request method with rpc.
  ui-v2/app/adapters/acl.js
  ui-v2/app/adapters/application.js
  ui-v2/app/adapters/node.js
  ui-v2/app/adapters/nspace.js
  ui-v2/app/adapters/oidc-provider.js
  ui-v2/app/adapters/token.js
Labels: backport/1.8, theme/ui

#8216 Update Envoy
  .circleci/config.yml
  agent/xds/clusters_test.go
  command/connect/envoy/envoy.go
  command/connect/envoy/testdata/CONSUL_HTTP_ADDR-with-https-scheme-enables-tls.golden
  command/connect/envoy/testdata/access-log-path.golden
  command/connect/envoy/testdata/defaults.golden
  command/connect/envoy/testdata/existing-ca-file.golden
  command/connect/envoy/testdata/extra_-multiple.golden
  command/connect/envoy/testdata/extra_-single.golden
  command/connect/envoy/testdata/grpc-addr-config.golden
  command/connect/envoy/testdata/grpc-addr-env.golden
  command/connect/envoy/testdata/grpc-addr-flag.golden
  command/connect/envoy/testdata/grpc-addr-unix.golden
  command/connect/envoy/testdata/ingress-gateway-address-specified.golden
  command/connect/envoy/testdata/ingress-gateway-no-auto-register.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-and-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-without-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway-register-without-service-with-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway-without-register.golden
  command/connect/envoy/testdata/ingress-gateway.golden
  command/connect/envoy/testdata/stats-config-override.golden
  command/connect/envoy/testdata/token-arg.golden
  command/connect/envoy/testdata/token-env.golden
  command/connect/envoy/testdata/token-file-arg.golden
  command/connect/envoy/testdata/token-file-env.golden
  command/connect/envoy/testdata/zipkin-tracing-config.golden
  test/integration/connect/envoy/run-tests.sh
  website/pages/docs/commands/connect/envoy.mdx
  website/pages/docs/connect/proxies/envoy.mdx
Labels: theme/connect, theme/envoy/xds, theme/testing

#8305 ui: Only try and load sessions and coordinates if the node exists
  ui-v2/app/routes/dc/nodes/show.js
  ui-v2/app/templates/dc/nodes/show.hbs
Labels: backport/1.8, theme/ui

#8301 Add ability for notifications when one of the agent tokens is updated
  agent/token/store.go
  agent/token/store_test.go
Labels: backport/1.8

#8308 ui: Make sure the intention create form has a cancel button
  ui-v2/app/components/consul-intention-form/index.hbs
Labels: backport/1.8, theme/ui

#8277 Update dependencies, format all files
  website/components/basic-hero/index.jsx
  website/package-lock.json
  website/package.json
  website/pages/api-docs/acl/binding-rules.mdx
  website/pages/api-docs/acl/roles.mdx
  website/pages/api-docs/catalog.mdx
  website/pages/api-docs/config.mdx
  website/pages/api-docs/connect/intentions.mdx
  website/pages/docs/acl/acl-legacy.mdx
  website/pages/docs/acl/acl-system.mdx
  website/pages/docs/acl/auth-methods/index.mdx
  website/pages/docs/acl/auth-methods/jwt.mdx
  website/pages/docs/agent/config-entries/ingress-gateway.mdx
  website/pages/docs/agent/config-entries/terminating-gateway.mdx
  website/pages/docs/agent/index.mdx
  website/pages/docs/agent/options.mdx
  website/pages/docs/agent/telemetry.mdx
  website/pages/docs/commands/connect/expose.mdx
  website/pages/docs/commands/index.mdx
  website/pages/docs/commands/intention/index.mdx
  website/pages/docs/commands/license.mdx
  website/pages/docs/commands/operator/raft.mdx
  website/pages/docs/connect/connect-internals.mdx
  website/pages/docs/connect/ingress-gateway.mdx
  website/pages/docs/connect/proxies/built-in.mdx
  website/pages/docs/connect/proxies/envoy.mdx
  website/pages/docs/connect/wan-federation-via-mesh-gateways.mdx
  website/pages/docs/enterprise/backups.mdx
  website/pages/docs/enterprise/federation.mdx
  website/pages/docs/enterprise/namespaces.mdx
  website/pages/docs/enterprise/network-segments.mdx
  website/pages/docs/enterprise/read-scale.mdx
  website/pages/docs/enterprise/redundancy.mdx
  website/pages/docs/enterprise/sentinel.mdx
  website/pages/docs/enterprise/upgrades.mdx
  website/pages/docs/faq.mdx
  website/pages/docs/guides/acl-legacy.mdx
  website/pages/docs/internals/coordinates.mdx
  website/pages/docs/k8s/helm.mdx
  website/pages/home/index.jsx
  website/pages/partials/jwt_or_oidc.mdx
Labels: backport/1.8, type/docs-cherrypick

#8230 📌 Hard Pin Website Dependencies
  website/components/basic-hero/index.jsx
  website/package-lock.json
  website/package.json
  website/pages/api-docs/acl/binding-rules.mdx
  website/pages/api-docs/acl/roles.mdx
  website/pages/api-docs/catalog.mdx
  website/pages/api-docs/config.mdx
  website/pages/api-docs/connect/intentions.mdx
  website/pages/docs/acl/acl-legacy.mdx
  website/pages/docs/acl/acl-system.mdx
  website/pages/docs/acl/auth-methods/index.mdx
  website/pages/docs/acl/auth-methods/jwt.mdx
  website/pages/docs/agent/config-entries/ingress-gateway.mdx
  website/pages/docs/agent/config-entries/terminating-gateway.mdx
  website/pages/docs/agent/index.mdx
  website/pages/docs/agent/options.mdx
  website/pages/docs/agent/telemetry.mdx
  website/pages/docs/commands/connect/expose.mdx
  website/pages/docs/commands/index.mdx
  website/pages/docs/commands/intention/index.mdx
  website/pages/docs/commands/license.mdx
  website/pages/docs/commands/operator/raft.mdx
  website/pages/docs/connect/connect-internals.mdx
  website/pages/docs/connect/ingress-gateway.mdx
  website/pages/docs/connect/proxies/built-in.mdx
  website/pages/docs/connect/proxies/envoy.mdx
  website/pages/docs/connect/wan-federation-via-mesh-gateways.mdx
  website/pages/docs/enterprise/backups.mdx
  website/pages/docs/enterprise/federation.mdx
  website/pages/docs/enterprise/namespaces.mdx
  website/pages/docs/enterprise/network-segments.mdx
  website/pages/docs/enterprise/read-scale.mdx
  website/pages/docs/enterprise/redundancy.mdx
  website/pages/docs/enterprise/sentinel.mdx
  website/pages/docs/enterprise/upgrades.mdx
  website/pages/docs/faq.mdx
  website/pages/docs/guides/acl-legacy.mdx
  website/pages/docs/internals/coordinates.mdx
  website/pages/docs/k8s/helm.mdx
  website/pages/home/index.jsx
  website/pages/partials/jwt_or_oidc.mdx
Labels: backport/1.8, type/docs-cherrypick, type/website

#8291 K8s/ingress setup docs
  website/pages/docs/k8s/connect/ingress-gateways.mdx
Labels: theme/ingress-gw, theme/kubernetes, type/docs, type/docs-cherrypick

#8140 K8s ingress and terminating gateway setup docs
  website/_redirects
  website/data/docs-navigation.js
  website/pages/docs/connect/configuration.mdx
  website/pages/docs/guides/connect-services.mdx
  website/pages/docs/k8s/ambassador.mdx
  website/pages/docs/k8s/connect/ingress-gateways.mdx
  website/pages/docs/k8s/connect/overview.mdx
  website/pages/docs/k8s/helm.mdx
  website/pages/docs/k8s/installation/deployment-configurations/servers-outside-kubernetes.mdx
  website/pages/docs/k8s/installation/multi-cluster/kubernetes.mdx
  website/pages/docs/k8s/installation/overview.mdx
Labels: theme/ingress-gw, type/docs-cherrypick

#8318 minor: fix docstring of DNSOnlyPassing
  agent/config/runtime.go
Labels: backport/1.8

#8320 ui: Better error message checking for cross dc connect check
  ui-v2/app/services/repository/discovery-chain.js
Labels: backport/1.8, theme/ui

#8282 state: convert methods that don't use their receiver to functions
  agent/consul/state/acl.go
  agent/consul/state/acl_events_test.go
  agent/consul/state/acl_oss.go
  agent/consul/state/acl_test.go
  agent/consul/state/catalog.go
  agent/consul/state/catalog_oss.go
  agent/consul/state/catalog_test.go
  agent/consul/state/config_entry.go
  agent/consul/state/config_entry_oss.go
  agent/consul/state/connect_ca.go
  agent/consul/state/federation_state.go
  agent/consul/state/intention.go
  agent/consul/state/intention_oss.go
  agent/consul/state/kvs.go
  agent/consul/state/kvs_oss.go
  agent/consul/state/prepared_query.go
  agent/consul/state/session.go
  agent/consul/state/session_oss.go
  agent/consul/state/txn.go
Labels: theme/internal-cleanup

#8259 Consul Enterprise docs update
  website/data/docs-navigation.js
  website/pages/docs/enterprise/audit-logging.mdx
  website/pages/docs/enterprise/index.mdx
Labels: type/docs

#8322 docs: Fix link to kv_max_value_size config option
  website/pages/docs/agent/kv.mdx
Labels: type/docs, type/docs-cherrypick

#8313 ui: Change some components to use willDestroyElement vs willDestroy
  ui-v2/app/components/data-sink/index.js
  ui-v2/app/components/data-source/index.js
  ui-v2/app/components/jwt-source/index.js
  ui-v2/app/components/state-chart/guard/index.js
Labels: backport/1.8, theme/ui

#8326 ui: Fix sticky action popover menus
  ui-v2/app/components/more-popover-menu/action/index.hbs
  ui-v2/app/components/more-popover-menu/index.hbs
  ui-v2/app/templates/dc/kv/index.hbs
  ui-v2/app/templates/dc/nspaces/index.hbs
Labels: backport/1.8, theme/ui

#8321 ui: Move routes to use data-sources
  ui-v2/app/adapters/coordinate.js
  ui-v2/app/adapters/discovery-chain.js
  ui-v2/app/adapters/intention.js
  ui-v2/app/adapters/node.js
  ui-v2/app/adapters/nspace.js
  ui-v2/app/adapters/oidc-provider.js
  ui-v2/app/adapters/proxy.js
  ui-v2/app/adapters/service.js
  ui-v2/app/adapters/session.js
  ui-v2/app/components/data-loader/index.hbs
  ui-v2/app/components/data-loader/index.js
  ui-v2/app/components/data-source/index.js
  ui-v2/app/components/data-writer/index.hbs
  ui-v2/app/components/event-source/index.hbs
  ui-v2/app/components/event-source/index.js
  ui-v2/app/controllers/dc/nodes/show.js
  ui-v2/app/controllers/dc/nodes/show/services.js
  ui-v2/app/helpers/uri.js
  ui-v2/app/instance-initializers/event-source.js
  ui-v2/app/routes/dc/nodes/index.js
  ui-v2/app/routes/dc/nodes/show.js
  ui-v2/app/routes/dc/nspaces/index.js
  ui-v2/app/routes/dc/services/index.js
  ui-v2/app/routes/dc/services/instance.js
  ui-v2/app/routes/dc/services/show.js
  ui-v2/app/services/client/connections.js
  ui-v2/app/services/client/http.js
  ui-v2/app/services/client/transports/xhr.js
  ui-v2/app/services/data-sink/protocols/http.js
  ui-v2/app/services/data-source/protocols/http.js
  ui-v2/app/services/data-source/protocols/http/blocking.js
  ui-v2/app/services/data-source/protocols/local-storage.js
  ui-v2/app/services/data-source/service.js
  ui-v2/app/services/encoder.js
  ui-v2/app/services/repository.js
  ui-v2/app/services/repository/coordinate.js
  ui-v2/app/services/repository/intention.js
  ui-v2/app/services/repository/nspace.js
  ui-v2/app/services/repository/nspace/enabled.js
  ui-v2/app/services/repository/proxy.js
  ui-v2/app/services/repository/service.js
  ui-v2/app/services/repository/session.js
  ui-v2/app/templates/dc/nodes/show.hbs
  ui-v2/app/templates/dc/nodes/show/services.hbs
  ui-v2/app/templates/dc/nodes/show/sessions.hbs
  ui-v2/app/templates/dc/services/instance.hbs
  ui-v2/app/templates/dc/services/show.hbs
  ui-v2/app/utils/dom/event-source/callable.js
  ui-v2/tests/integration/adapters/coordinate-test.js
  ui-v2/tests/integration/adapters/discovery-chain-test.js
  ui-v2/tests/integration/adapters/intention-test.js
  ui-v2/tests/integration/adapters/node-test.js
  ui-v2/tests/integration/adapters/nspace-test.js
  ui-v2/tests/unit/services/encoder-test.js
Labels: backport/1.8, theme/ui

#8269 ci: add 'go test -race'
  .circleci/config.yml
Labels: type/ci

#8335 ui: Add some missed spaces in component README files
  ui-v2/app/components/consul-metadata-list/README.mdx
  ui-v2/app/components/consul-policy-list/README.mdx
  ui-v2/app/components/consul-role-list/README.mdx
  ui-v2/app/components/consul-token-list/README.mdx
  ui-v2/app/components/consul-token-ruleset-list/README.mdx
Labels: backport/1.8, theme/ui

#8307 ui: KV Form and List Components
  ui-v2/app/components/confirmation-dialog/index.hbs
  ui-v2/app/components/confirmation-dialog/index.js
  ui-v2/app/components/consul-kv-form/index.hbs
  ui-v2/app/components/consul-kv-form/index.js
  ui-v2/app/components/consul-kv-list/index.hbs
  ui-v2/app/components/consul-kv-list/index.js
  ui-v2/app/components/consul-kv-list/pageobject.js
  ui-v2/app/components/consul-session-form/index.hbs
  ui-v2/app/components/consul-session-form/index.js
  ui-v2/app/components/data-form/index.hbs
  ui-v2/app/components/data-form/index.js
  ui-v2/app/components/data-writer/index.hbs
  ui-v2/app/components/notification/index.js
  ui-v2/app/controllers/dc/kv/create.js
  ui-v2/app/controllers/dc/kv/folder.js
  ui-v2/app/controllers/dc/kv/root-create.js
  ui-v2/app/mixins/kv/with-actions.js
  ui-v2/app/routes/dc/kv/create.js
  ui-v2/app/routes/dc/kv/edit.js
  ui-v2/app/routes/dc/kv/index.js
  ui-v2/app/services/data-sink/protocols/http.js
  ui-v2/app/services/data-source/protocols/http.js
  ui-v2/app/templates/dc/kv/-form.hbs
  ui-v2/app/templates/dc/kv/-notifications.hbs
  ui-v2/app/templates/dc/kv/edit.hbs
  ui-v2/app/templates/dc/kv/index.hbs
  ui-v2/tests/acceptance/components/kv-filter.feature
  ui-v2/tests/acceptance/dc/kvs/delete.feature
  ui-v2/tests/acceptance/dc/kvs/sessions/invalidate.feature
  ui-v2/tests/acceptance/deleting.feature
  ui-v2/tests/acceptance/steps/dc/kvs/delete-steps.js
  ui-v2/tests/integration/components/consul-kind.js
  ui-v2/tests/pages.js
  ui-v2/tests/pages/dc/kv/index.js
  ui-v2/tests/unit/controllers/dc/kv/create-test.js
  ui-v2/tests/unit/controllers/dc/kv/edit-test.js
  ui-v2/tests/unit/controllers/dc/kv/folder-test.js
  ui-v2/tests/unit/controllers/dc/kv/root-create-test.js
  ui-v2/tests/unit/mixins/kv/with-actions-test.js
Labels: backport/1.8, theme/ui

#8331 command: fix cas put when index=0 and better errors in put and delete
  command/kv/del/kv_delete.go
  command/kv/del/kv_delete_test.go
  command/kv/put/kv_put.go
  command/kv/put/kv_put_test.go
Labels: theme/cli, type/bug

#8328 ci: Use go1.14.6
  .circleci/config.yml
Labels: backport/1.8, type/ci

#8290 watch: fix script watches with single arg
  agent/agent.go
  agent/watch_handler.go
  agent/watch_handler_test.go
Labels: backport/1.8, type/bug

#8339 docs: Add raft_multiplier default clarification
  website/pages/docs/install/performance.mdx
Labels: backport/1.8, type/docs-cherrypick

#8338 ui: fix swapped node & serivce checks by fixing filter-by & reject-by
  ui-v2/app/components/consul-service-instance-list/index.hbs
Labels: backport/1.8, theme/ui

#8296 Issue #8294 - Table element's have vertical scrollbars
  ui-v2/app/styles/base/components/table/layout.scss
Labels: backport/1.8, theme/ui

#8316 Add certificate disclaimer for TLS encryption
  website/pages/docs/agent/encryption.mdx
Labels: type/docs-cherrypick, type/website

#8344 stream: handle empty event in TestEventSnapshot
  .circleci/config.yml
  agent/consul/stream/event_snapshot_test.go
Labels: theme/testing

#8311 Fix issue with changing the agent token causing failure to renew the auto-encrypt certificate
  agent/agent.go
  agent/agent_endpoint_test.go
  agent/cache-types/connect_ca_leaf.go
  agent/cache-types/options.go
  agent/cache/cache.go
  agent/cache/cache_test.go
  agent/cert-monitor/cert_monitor.go
  agent/cert-monitor/cert_monitor_test.go
  agent/cert-monitor/config.go
  agent/connect/testing_ca.go
  agent/connect/uri_agent.go
  agent/connect/uri_service.go
  agent/consul/auto_encrypt.go
  agent/consul/auto_encrypt_test.go
  agent/proxycfg/testing.go
Labels: backport/1.8

#7948 testutil: NewLogBuffer - buffer logs until a test fails
  agent/acl_test.go
  agent/ae/ae_test.go
  agent/checks/check.go
  agent/consul/acl_test.go
  agent/consul/client_test.go
  agent/consul/leader_test.go
  agent/consul/server_test.go
  agent/testagent.go
  api/api_test.go
  sdk/testutil/README.md
  sdk/testutil/server.go
  sdk/testutil/testlog.go
Labels: backport/1.8

#8343 gossip: Avoid issue where two unique leave events for the same node could lead to infinite rebroadcast storms
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  vendor/github.com/hashicorp/go-connlimit/LICENSE
  vendor/github.com/hashicorp/go-connlimit/NOTICE.md
  vendor/github.com/hashicorp/serf/serf/config.go
  vendor/github.com/hashicorp/serf/serf/delegate.go
  vendor/github.com/hashicorp/serf/serf/serf.go
  vendor/modules.txt
Labels: backport/1.7, backport/1.8

#8355 ui: Fix service splitter returning service weight or a zero
  ui-v2/app/templates/components/discovery-chain.hbs
Labels: theme/ui

#8356 Restore link to /intro docs in main menu
  website/data/subnav.js
Labels: type/docs

#8361 Update mapstructure to v1.3.3
  go.mod
  go.sum
  vendor/github.com/mitchellh/mapstructure/CHANGELOG.md
  vendor/github.com/mitchellh/mapstructure/mapstructure.go
  vendor/modules.txt
Labels: backport/1.8

#8300 initial rev of terminating gw docs
  website/data/docs-navigation.js
  website/pages/docs/k8s/connect/terminating-gateways.mdx
Labels: type/docs-cherrypick

#8362 Refactor the agentpb package
  agent/auto-config/auto_config.go
  agent/auto-config/auto_config_test.go
  agent/auto-config/config_translate.go
  agent/auto-config/config_translate_test.go
  agent/consul/auto_config_endpoint.go
  agent/consul/auto_config_endpoint_test.go
  agent/consul/state/acl.go
  agent/consul/state/acl_test.go
  agent/structs/protobuf_compat.go
  proto/pbacl/acl.pb.binary.go
  proto/pbacl/acl.pb.go
  proto/pbacl/acl.proto
  proto/pbautoconf/auto_config.go
  proto/pbautoconf/auto_config.pb.binary.go
  proto/pbautoconf/auto_config.pb.go
  proto/pbautoconf/auto_config.proto
  proto/pbcommon/common.go
  proto/pbcommon/common.pb.binary.go
  proto/pbcommon/common.pb.go
  proto/pbcommon/common.proto
  proto/pbcommon/common_oss.pb.binary.go
  proto/pbcommon/common_oss.pb.go
  proto/pbcommon/common_oss.proto
  proto/pbconfig/config.pb.binary.go
  proto/pbconfig/config.pb.go
  proto/pbconfig/config.proto
Labels: backport/1.8

#8367 Adds a cloud offerings section to website
  website/components/basic-hero/index.jsx
  website/components/cloud-offerings-list/index.jsx
  website/components/cloud-offerings-list/style.css
  website/pages/home/img/cloud/hcp.jpg
  website/pages/home/img/cloud/hcs.jpg
  website/pages/home/index.jsx
  website/pages/home/style.css
  website/pages/style.css
Labels: type/docs-cherrypick

#8370 Update alert banner to HCS GA
  website/data/alert-banner.js
Labels: type/docs-cherrypick

#8368 Update terminating-gateways.mdx
  website/pages/docs/k8s/connect/terminating-gateways.mdx
Labels: type/docs-cherrypick

#8323 stream: close subscriptions on shutdown
  agent/consul/stream/event_publisher.go
  agent/consul/stream/event_publisher_test.go
  agent/consul/stream/subscription.go
  agent/consul/stream/subscription_test.go
Labels: theme/streaming

#8371 Fix envoy bootstrap logic to not append multiple self_admin clusters
  command/connect/envoy/bootstrap_config.go
  command/connect/envoy/bootstrap_config_test.go
Labels: backport/1.8, theme/ingress-gw, type/bug

#8363 Move generation of CA Configuration into a method on the `RuntimeConfig`
  agent/agent.go
  agent/config/runtime.go
  agent/config/runtime_test.go
  agent/consul/config.go
  agent/structs/connect_ca.go
Labels: backport/1.8

#8374 Add script to print available module updates
  GNUmakefile
Labels: pr/dependencies

#8364 Move connect root retrieval and cert signing logic out of the RPC endpoints
  agent/consul/connect_ca_endpoint.go
  agent/consul/server_connect.go
Labels: backport/1.8

#8195 Gateway tasks and overview
  website/data/docs-navigation.js
  website/pages/docs/connect/connectivity-tasks.mdx
  website/pages/docs/connect/gateways/index.mdx
  website/pages/docs/connect/gateways/ingress-gateway.mdx
  website/pages/docs/connect/gateways/mesh-gateway.mdx
  website/pages/docs/connect/gateways/terminating-gateway.mdx
  website/pages/docs/connect/gateways/wan-federation-via-mesh-gateways.mdx
Labels: backport/1.8, type/docs-cherrypick

#8380 docs: Add redirect for /docs/k8s/connect.html
  website/_redirects
Labels: type/docs, type/docs-cherrypick

#8382 docs: Modify network segments limitation callout
  website/pages/docs/enterprise/network-segments.mdx
Labels: type/docs, type/docs-cherrypick

#8383 docs: Modify website redirects for gateways
  website/_redirects
Labels: type/docs, type/docs-cherrypick

#8226 Added ratelimit to handle throtling cache
  agent/agent.go
  agent/agent_test.go
  agent/cache/cache.go
  agent/cache/entry.go
  agent/cache/testing.go
  agent/config/builder.go
  agent/config/config.go
  agent/config/runtime.go
  agent/config/runtime_test.go
  agent/proxycfg/manager_test.go
  website/pages/docs/agent/options.mdx
Labels: backport/1.8

#8348 ui: Add sorting to Intentions with tests
  ui-v2/app/controllers/dc/intentions/index.js
  ui-v2/app/initializers/sort.js
  ui-v2/app/routes/dc/intentions/index.js
  ui-v2/app/sort/comparators/intention.js
  ui-v2/app/templates/dc/intentions/index.hbs
  ui-v2/tests/acceptance/components/intention-filter.feature
  ui-v2/tests/acceptance/dc/intentions/navigation.feature
  ui-v2/tests/acceptance/dc/intentions/sorting.feature
  ui-v2/tests/acceptance/page-navigation.feature
  ui-v2/tests/acceptance/steps/dc/intentions/navigation-steps.js
  ui-v2/tests/acceptance/steps/dc/intentions/sorting-steps.js
  ui-v2/tests/pages.js
  ui-v2/tests/pages/dc/intentions/index.js
Labels: backport/1.8, theme/ui

#8391 docs: Fix typo in -pid file description
  website/pages/docs/agent/options.mdx
Labels: type/docs, type/docs-cherrypick

#8389 Fix some broken code in master
  agent/agent_test.go
  agent/cache-types/catalog_list_services_test.go
  agent/cache-types/connect_ca_leaf_test.go
  agent/cache/cache.go
  agent/cache/cache_test.go
  agent/cache/testing.go
  agent/cache/watch_test.go
  agent/cert-monitor/cert_monitor_test.go
  agent/config/builder.go
  agent/proxycfg/testing.go
Labels: backport/1.8

#8360 Agent Auto Config: Implement Certificate Generation
  agent/agent.go
  agent/agent_test.go
  agent/auto-config/auto_config.go
  agent/auto-config/auto_config_test.go
  agent/auto-config/builder.go
  agent/auto-config/config.go
  agent/auto-config/config_translate.go
  agent/cert-monitor/cert_monitor.go
  agent/config/builder.go
  agent/config/runtime.go
  agent/config/runtime_test.go
  agent/consul/auto_config_endpoint.go
  agent/consul/auto_config_endpoint_test.go
  agent/consul/server.go
  proto/pbautoconf/auto_config.pb.go
  proto/pbautoconf/auto_config.proto
  proto/pbconnect/connect.pb.binary.go
  proto/pbconnect/connect.pb.go
  proto/pbconnect/connect.proto
  proto/translate.go
  proto/translate_test.go
Labels: backport/1.8

#8384 ui: Use X-Range header as a signal as to whether to reconcile the ember-data store
  ui-v2/app/adapters/intention.js
  ui-v2/app/adapters/service.js
  ui-v2/app/serializers/application.js
  ui-v2/app/services/client/http.js
  ui-v2/app/services/data-source/protocols/http.js
  ui-v2/app/services/repository.js
  ui-v2/app/services/repository/intention.js
  ui-v2/app/services/repository/service.js
  ui-v2/app/services/repository/type/event-source.js
Labels: backport/1.8, theme/ui

#8359 ui: Add sorting to ACLs tokens with tests
  ui-v2/app/components/consul-token-list/index.hbs
  ui-v2/app/components/consul-token-list/pageobject.js
  ui-v2/app/components/list-collection/index.hbs
  ui-v2/app/controllers/dc/acls/tokens/index.js
  ui-v2/app/initializers/sort.js
  ui-v2/app/routes/dc/acls/tokens/index.js
  ui-v2/app/sort/comparators/token.js
  ui-v2/app/styles/components/notice.scss
  ui-v2/app/templates/dc/acls/tokens/index.hbs
  ui-v2/tests/acceptance/dc/acls/tokens/navigation.feature
  ui-v2/tests/acceptance/dc/acls/tokens/sorting.feature
  ui-v2/tests/acceptance/page-navigation.feature
  ui-v2/tests/acceptance/steps/dc/acls/tokens/navigation-steps.js
  ui-v2/tests/acceptance/steps/dc/acls/tokens/sorting-steps.js
  ui-v2/tests/pages.js
  ui-v2/tests/pages/dc/acls/tokens/index.js
  ui-v2/yarn.lock
Labels: backport/1.8, theme/ui

#8398 ui: Fix up on the onchange value to target for sorting intentions
  ui-v2/app/templates/dc/intentions/index.hbs
Labels: backport/1.8, theme/ui

#8397 ui: Ensure URLs for tabs change when selecting a different DC
  ui-v2/app/components/tab-nav/pageobject.js
  ui-v2/app/helpers/href-to.js
  ui-v2/tests/acceptance/dc/services/show/dc-switch.feature
  ui-v2/tests/acceptance/steps/dc/services/show/dc-switch-steps.js
  ui-v2/tests/pages.js
  ui-v2/tests/pages/dc/services/show.js
  ui-v2/tests/steps/assertions/page.js
Labels: backport/1.8, theme/ui

#8399 ui: Update onchange value target for sorting tokens
  ui-v2/app/templates/dc/acls/tokens/index.hbs
Labels: backport/1.8, theme/ui

#8369 ui: Add sorting to Roles
  ui-v2/app/components/consul-role-list/pageobject.js
  ui-v2/app/controllers/dc/acls/roles/index.js
  ui-v2/app/initializers/sort.js
  ui-v2/app/routes/dc/acls/roles/index.js
  ui-v2/app/sort/comparators/role.js
  ui-v2/app/templates/dc/acls/roles/index.hbs
  ui-v2/tests/acceptance/dc/acls/roles/navigation.feature
  ui-v2/tests/acceptance/dc/acls/roles/sorting.feature
  ui-v2/tests/acceptance/steps/dc/acls/roles/navigation-steps.js
  ui-v2/tests/acceptance/steps/dc/acls/roles/sorting-steps.js
  ui-v2/tests/pages.js
  ui-v2/tests/pages/dc/acls/roles/index.js
Labels: backport/1.8, theme/ui

#8373 ui: Add sorting to Policies
  ui-v2/app/components/consul-policy-list/pageobject.js
  ui-v2/app/controllers/dc/acls/policies/index.js
  ui-v2/app/initializers/sort.js
  ui-v2/app/routes/dc/acls/policies/index.js
  ui-v2/app/sort/comparators/policy.js
  ui-v2/app/templates/dc/acls/policies/index.hbs
  ui-v2/tests/acceptance/dc/acls/policies/navigation.feature
  ui-v2/tests/acceptance/dc/acls/policies/sorting.feature
  ui-v2/tests/acceptance/page-navigation.feature
  ui-v2/tests/acceptance/steps/dc/acls/policies/navigation-steps.js
  ui-v2/tests/acceptance/steps/dc/acls/policies/sorting-steps.js
  ui-v2/tests/pages.js
  ui-v2/tests/pages/dc/acls/policies/index.js
Labels: backport/1.8, theme/ui

#8396 agent/cache test for cache throttling.
  agent/cache/cache_test.go
Labels: backport/1.8

#8394 Allow setting verify_incoming* when using auto_encrypt or auto_config
  agent/cert-monitor/cert_monitor.go
  agent/cert-monitor/cert_monitor_test.go
  agent/config/runtime.go
  agent/config/runtime_test.go
  agent/consul/auto_encrypt_endpoint_test.go
  agent/consul/server.go
  tlsutil/config.go
  tlsutil/config_test.go
Labels: backport/1.8

#8409 Ensure certificates retrieved through the cache get persisted with auto-config
  agent/agent.go
  agent/agent_test.go
  agent/auto-config/auto_config.go
  agent/auto-config/config_translate.go
  agent/cert-monitor/cert_monitor.go
  agent/cert-monitor/cert_monitor_test.go
  agent/cert-monitor/config.go
Labels: backport/1.8

#8410 Add some auto-config docs
  website/pages/docs/agent/options.mdx
Labels: backport/1.8, type/docs

#8413 Update CHANGELOG.md
  CHANGELOG.md
Labels: backport/1.7, backport/1.8
