Repository hashicorp/consul, pull requests merged in 2020-02, with the labels that each got.

#5736 [docs] IDs are UUIDs, /acl/token endpoints manage ACL tokens
  website/source/api/acl/policies.html.md
  website/source/api/acl/tokens.html.md
  website/source/docs/guides/agent-encryption.html.md
  website/source/docs/guides/autopilot.html.md
Labels: docs

#6574 [docs] gRPC Health Checking specific service
  website/source/api/agent/check.html.md
  website/source/docs/agent/checks.html.md
Labels: docs

#7197 Fix org name in Helm chart's imageEnvoy description
  website/source/docs/platform/k8s/helm.html.md
Labels: docs

#7176 Add Flightpath to the list of community tools
  website/source/downloads_tools.html.erb
Labels: waiting-reply

#7195 ui: Hides the Routing tab for a service proxy
  ui-v2/app/routes/dc/services/show.js
  ui-v2/app/templates/dc/services/show.hbs
  ui-v2/tests/acceptance/dc/services/show-routing.feature
  ui-v2/tests/acceptance/steps/dc/services/show-routing-steps.js
  ui-v2/tests/pages.js
  ui-v2/tests/pages/dc/services/show.js
Labels: ui

#6904 Enabling connect requires server restarts
  website/source/docs/connect/configuration.html.md
Labels: docs

#7153 new golang version 1.12.16
  .circleci/config.yml
  build-support/docker/Build-Go.dockerfile
  build-support/docker/Test-Flake.dockerfile
Labels: waiting-reply

#7204 ui: Add ability to search nodes listing page with IP Address
  ui-v2/app/search/filters/node.js
  ui-v2/app/templates/components/catalog-filter.hbs
  ui-v2/tests/acceptance/dc/nodes/index.feature
  ui-v2/tests/unit/search/filters/node-test.js
Labels: ui

#7216 ui: Ensure KV flags are passed through to Consul on update
  ui-v2/app/adapters/kv.js
  ui-v2/tests/acceptance/dc/kvs/update.feature
  ui-v2/tests/integration/adapters/kv-test.js
Labels: ui

#7222 ui: Discovery chain improvements
  ui-v2/app/components/discovery-chain.js
  ui-v2/app/components/route-card.js
  ui-v2/app/templates/components/route-card.hbs
  ui-v2/app/templates/dc/services/show.hbs
  ui-v2/app/utils/components/discovery-chain/index.js
  ui-v2/yarn.lock
Labels: ui

#7230 docs: Indent secretName and secretKey under aclSyncToken
  website/source/docs/platform/k8s/helm.html.md
Labels: docs

#7233 ui: Fix for differences between uncompiled and compiled CSS
  ui-v2/app/styles/base/components/menu-panel/layout.scss
Labels: ui

#7235 ui: UI Release Merge (ui-staging merge)
  .circleci/config.yml
  ui-v2/GNUmakefile
  ui-v2/app/adapters/kv.js
  ui-v2/app/components/aria-menu.js
  ui-v2/app/components/discovery-chain.js
  ui-v2/app/components/route-card.js
  ui-v2/app/routes/dc/services/show.js
  ui-v2/app/search/filters/node.js
  ui-v2/app/styles/base/components/menu-panel/layout.scss
  ui-v2/app/templates/components/catalog-filter.hbs
  ui-v2/app/templates/components/hashicorp-consul.hbs
  ui-v2/app/templates/components/popover-menu.hbs
  ui-v2/app/templates/components/route-card.hbs
  ui-v2/app/templates/dc/services/show.hbs
  ui-v2/app/templates/settings.hbs
  ui-v2/app/utils/components/discovery-chain/index.js
  ui-v2/package.json
  ui-v2/tests/acceptance/dc/kvs/update.feature
  ui-v2/tests/acceptance/dc/nodes/index.feature
  ui-v2/tests/acceptance/dc/nspaces/manage.feature
  ui-v2/tests/acceptance/dc/services/show-routing.feature
  ui-v2/tests/acceptance/settings/show.feature
  ui-v2/tests/acceptance/steps/dc/nspaces/manage-steps.js
  ui-v2/tests/acceptance/steps/dc/services/show-routing-steps.js
  ui-v2/tests/integration/adapters/kv-test.js
  ui-v2/tests/pages.js
  ui-v2/tests/pages/components/page.js
  ui-v2/tests/pages/dc/services/show.js
  ui-v2/tests/pages/settings.js
  ui-v2/tests/steps/assertions/page.js
  ui-v2/tests/unit/search/filters/node-test.js
  ui-v2/yarn.lock
Labels: ui

#7236 agent/consul server: fix LeaderTest_ChangeNodeID
  agent/consul/leader_test.go
Labels: theme/flaky-tests

#7238 ui: oss don't ever POST/PUT Namespaces when writing data
  ui-v2/app/adapters/policy.js
  ui-v2/app/adapters/role.js
  ui-v2/app/adapters/token.js
  ui-v2/tests/acceptance/dc/acls/policies/create.feature
  ui-v2/tests/acceptance/dc/acls/policies/update.feature
  ui-v2/tests/acceptance/dc/acls/roles/create.feature
  ui-v2/tests/acceptance/dc/acls/roles/update.feature
  ui-v2/tests/acceptance/dc/acls/tokens/create.feature
  ui-v2/tests/acceptance/dc/acls/tokens/update.feature
  ui-v2/tests/steps/assertions/http.js
Labels: ui

#6850 ui: Slight refactor 'name deciding' for `request` > `rpc`
  ui-v2/app/adapters/application.js
  ui-v2/app/adapters/http.js
Labels: ui

#7027 ui: Test Coverage Reporting
  .circleci/config.yml
  codecov.yml
  ui-v2/GNUmakefile
  ui-v2/config/environment.js
  ui-v2/lib/startup/index.js
  ui-v2/package.json
  ui-v2/tests/helpers/api.js
  ui-v2/yarn.lock
Labels: ui

#7175 ui: Use the dart-sass implementation of sass
  ui-v2/ember-cli-build.js
  ui-v2/package.json
  ui-v2/yarn.lock
Labels: ui

#7248 ui: Upgrade to node 12 LTS
  build-support/docker/Build-UI.dockerfile
  ui-v2/.nvmrc
Labels: ui

#7212 Adding upgrade-legacy doc
  website/source/docs/commands/acl/token/update.html.md.erb
Labels: docs

#7224 rpc: measure blocking queries
  agent/consul/rpc.go
  agent/consul/server.go
  website/source/docs/agent/telemetry.html.md
  website/source/docs/upgrade-specific.html.md
Labels: theme/telemetry

#7246 Fix broken link to consul-aws guide on Learn
  website/source/docs/partnerships/index.html.md
  website/source/redirects.txt
Labels: docs

#6569 [docs] ACL Rules Update
  website/source/docs/acl/acl-rules.html.md.erb
Labels: docs, pr/needs-rebase, waiting-reply

#6693 Document format for TTL values in Consul config
  website/source/docs/agent/options.html.md
Labels: docs

#7249 ui: Remove custom css-vars 'polyfill' and use native CSS props
  ui-v2/app/helpers/css-var.js
  ui-v2/app/helpers/service/external-source.js
  ui-v2/app/styles/base/icons/base-variables.scss
  ui-v2/app/styles/components/app-view/skin.scss
  ui-v2/app/styles/variables/index.scss
  ui-v2/app/templates/components/discovery-chain.hbs
  ui-v2/app/templates/dc/nodes/-services.hbs
  ui-v2/app/templates/dc/services/-instances.hbs
  ui-v2/app/templates/dc/services/index.hbs
  ui-v2/app/templates/dc/services/instance.hbs
  ui-v2/app/templates/dc/services/show.hbs
  ui-v2/tests/integration/helpers/css-var-test.js
Labels: ui

#6597 Add splitting guide
  website/source/docs/guides/consul-splitting.md
Labels: docs, waiting-reply

#6493 Add f5 guide text
  website/source/docs/guides/consul-f5.md
Labels: docs

#7273 ui: Remove `next` from usage from discovery-chain component
  ui-v2/app/components/discovery-chain.js
Labels: ui

#7276 avoid 'panic: Log in goroutine after TestCacheGet_refreshAge has completed
  agent/cache/cache_test.go
Labels: theme/flaky-tests

#7279 ui: Add consul-service-list presentational component
  ui-v2/app/components/consul-service-list.js
  ui-v2/app/controllers/dc/services/index.js
  ui-v2/app/templates/components/consul-service-list.hbs
  ui-v2/app/templates/dc/services/index.hbs
  ui-v2/tests/integration/components/consul-service-list-test.js
Labels: ui

#7275 ui: Test coverage developer experience
  ui-v2/GNUmakefile
  ui-v2/app/utils/components/discovery-chain/index.js
  ui-v2/package.json
  ui-v2/tests/unit/utils/components/discovery-chain/get-resolvers-test.js
  ui-v2/tests/unit/utils/components/discovery-chain/get-splitters-test.js
Labels: ui

#7287 Upgrade to use structure-icons 1.8 (plus additional mask placeholders)
  ui-v2/app/styles/base/icons/base-variables.scss
  ui-v2/app/styles/base/icons/icon-placeholders.scss
Labels: ui

#7289 Bump default of HTTPMaxConnsPerClient to 200
  agent/config/default.go
  agent/config/runtime.go
  agent/config/runtime_test.go
  website/source/docs/agent/options.html.md
Labels: backport/1.6, backport/1.7, waiting-reply

#7286 Adjust formula for quorum size
  website/source/docs/internals/consensus.html.md
Labels: docs

#7296 Allow the PolicyResolve and RoleResolve endpoints to process namespace defaults
  agent/consul/acl_endpoint.go
  agent/consul/acl_oss.go
Labels: backport/1.7

#7291 ui: Gracefully cope with 500 errors from the disco-chain API endpoint
  ui-v2/app/routes/dc/services/show.js
  ui-v2/tests/acceptance/dc/services/show-routing.feature
Labels: backport/1.7, ui

#7040 ui: Use {{data-source}} for the node listing page
  ui-v2/app/controllers/dc/nodes/index.js
  ui-v2/app/routes/dc/nodes/index.js
  ui-v2/app/services/repository/manager.js
  ui-v2/app/templates/dc/nodes/index.hbs
Labels: ui

#6745 Update libraries-and-sdks.html.md
  website/source/api/libraries-and-sdks.html.md
Labels: docs

#6878 docs: add note bout change case in config files to specific version upgrade notes (#6870)
  website/source/docs/upgrade-specific.html.md
Labels: docs

#7314 ui: Upgrade circle CI node image to use node 12
  .circleci/config.yml
Labels: ui

#7308 ui: Use options.method for keying not options.type
  ui-v2/app/services/client/http.js
Labels: backport/1.7, ui

#7316 ui: Upgrade ember-cli-api-double and ember-data to fix up stage/preview site
  ui-v2/yarn.lock
Labels: ui

#7315 ui: Use a service-proxy to test service removal notification
  ui-v2/tests/acceptance/dc/list-blocking.feature
Labels: ui

#7280 Fix envoy config when both RetryOn* values are set
  agent/xds/routes.go
  agent/xds/testdata/routes/connect-proxy-with-chain-and-router.golden
Labels: backport/1.7

#7309 ui: Be more specific with the display toggling checkboxes
  ui-v2/app/styles/components/main-nav-horizontal/layout.scss
Labels: backport/1.7, ui

#6788 [docs] Register and Discover Services within Namespaces Guide
  website/source/docs/guides/discovery-namespaces.html.md
Labels: docs

#6833 Quote $GOTAGS in .circleci/config.yml
  .circleci/config.yml
Labels: pr/needs-rebase

#7281 let hashibot help us more
  .hashibot.hcl
Labels: waiting-reply

#7294 xDS Mesh Gateway Resolver Subset Fixes
  agent/proxycfg/snapshot.go
  agent/xds/clusters.go
  agent/xds/clusters_test.go
  agent/xds/endpoints.go
  agent/xds/endpoints_test.go
  agent/xds/testdata/clusters/mesh-gateway-ignore-extra-resolvers.golden
  agent/xds/testdata/endpoints/mesh-gateway-default-service-subset.golden
Labels: backport/1.7

#7322 ui: Upgrade ember-cli-api-double
  .circleci/config.yml
  ui-v2/package.json
  ui-v2/yarn.lock
Labels: ui

#7320 ui: Add box-shadow to table items on hover
  ui-v2/app/styles/components/table.scss
Labels: ui

#7323 Properly detect no alt domain set
  agent/dns.go
  agent/dns_test.go
Labels: backport/1.7

#7327 ui: Create a helper to show the last 8 characters of token Accessor ID
  ui-v2/app/helpers/substr.js
  ui-v2/app/templates/dc/acls/tokens/index.hbs
  ui-v2/tests/integration/helpers/substr-test.js
Labels: ui

#7333 ui: Use WithEventSource mixin on intentions to ensure cleanup
  ui-v2/app/controllers/dc/intentions/index.js
Labels: ui

#7337 ui: Create CSS variables for box-shadowing consistency
  ui-v2/app/styles/base/components/buttons/skin.scss
  ui-v2/app/styles/base/components/form-elements/skin.scss
  ui-v2/app/styles/base/components/menu-panel/skin.scss
  ui-v2/app/styles/base/components/modal-dialog/skin.scss
  ui-v2/app/styles/base/components/stats-card/skin.scss
  ui-v2/app/styles/base/components/tooltip/skin.scss
  ui-v2/app/styles/base/decoration/base-variables.scss
  ui-v2/app/styles/components/card/skin.scss
  ui-v2/app/styles/components/expanded-single-select/skin.scss
  ui-v2/app/styles/components/table.scss
  ui-v2/app/styles/components/tabular-details/skin.scss
  ui-v2/app/styles/variables/index.scss
  ui-v2/app/templates/components/discovery-chain.hbs
Labels: ui

#7334 ui: Upgrade to ember 3.16 Octane Edition
  ui-v2/.editorconfig
  ui-v2/.eslintrc.js
  ui-v2/.template-lintrc.js
  ui-v2/.travis.yml
  ui-v2/app/app.js
  ui-v2/app/mixins/with-event-source.js
  ui-v2/app/resolver.js
  ui-v2/app/router.js
  ui-v2/app/services/repository/nspace.js
  ui-v2/app/services/repository/nspace/disabled.js
  ui-v2/app/services/repository/nspace/enabled.js
  ui-v2/app/styles/app.scss
  ui-v2/app/templates/components/child-selector.hbs
  ui-v2/app/templates/components/code-editor.hbs
  ui-v2/app/templates/dc/intentions/-form.hbs
  ui-v2/app/templates/dc/kv/-form.hbs
  ui-v2/app/utils/dom/event-source/proxy.js
  ui-v2/config/optional-features.json
  ui-v2/package.json
  ui-v2/testem.js
  ui-v2/tests/integration/components/changeable-set-test.js
  ui-v2/tests/integration/components/service-identity-test.js
  ui-v2/tests/integration/components/token-list-test.js
  ui-v2/tests/integration/helpers/atob-test.js
  ui-v2/tests/integration/helpers/default-test.js
  ui-v2/tests/integration/helpers/env-test.js
  ui-v2/tests/integration/helpers/format-number-test.js
  ui-v2/tests/integration/helpers/is-href-test.js
  ui-v2/tests/integration/helpers/last-test.js
  ui-v2/tests/integration/helpers/left-trim-test.js
  ui-v2/tests/integration/helpers/object-entries-test.js
  ui-v2/tests/integration/helpers/policy/datacenters-test.js
  ui-v2/tests/integration/helpers/policy/typeof-test.js
  ui-v2/tests/integration/helpers/right-trim-test.js
  ui-v2/tests/integration/helpers/service/external-source-test.js
  ui-v2/tests/integration/helpers/slugify-test.js
  ui-v2/tests/integration/helpers/split-test.js
  ui-v2/tests/integration/helpers/starts-with-test.js
  ui-v2/tests/integration/helpers/substr-test.js
  ui-v2/tests/integration/helpers/token/is-anonymous-test.js
  ui-v2/tests/integration/helpers/token/is-legacy-test.js
  ui-v2/yarn.lock
Labels: ui
