Repository hashicorp/consul, pull requests merged in 2020-10, with the labels that each got.

#8791 ui: Initialize chain variable to null
  ui-v2/app/routes/dc/services/show.js
Labels: theme/ui

#8792 ui: Fix up tab separator CSS to not apply to all tabs
  ui-v2/app/styles/base/components/tabs/layout.scss
  ui-v2/app/styles/routes/dc/services/index.scss
Labels: theme/ui

#8789 Update k8s upgrade docs
  website/pages/docs/k8s/upgrade/index.mdx
Labels: type/docs-cherrypick

#8797 ui: Show service and node checks as a merged list sorted by health
  ui-v2/app/templates/dc/services/instance/healthchecks.hbs
  ui-v2/tests/acceptance/dc/services/instances/show.feature
  ui-v2/tests/pages/dc/services/instance.js
Labels: theme/ui

#8769 state: use protobuf Topic and and export payload type
  agent/consul/fsm/fsm.go
  agent/consul/state/catalog_events.go
  agent/consul/state/catalog_events_test.go
  agent/consul/state/memdb.go
  agent/consul/state/state_store.go
  agent/consul/state/store_integration_test.go
  agent/consul/stream/event_publisher.go
  agent/consul/stream/event_publisher_test.go
Labels: theme/streaming

#8711 proto: add code to convert between protobuf types and structs types
  go.mod
  go.sum
  proto/pbservice/convert.go
  proto/pbservice/convert_oss.go
  proto/pbservice/convert_pbstruct.go
  proto/pbservice/convert_test.go
  proto/pbservice/healthcheck.gen.go
  proto/pbservice/node.gen.go
  proto/pbservice/service.gen.go
  proto/pbservice/service.pb.go
  proto/pbservice/service.proto
  vendor/github.com/google/go-cmp/LICENSE
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/export_unsafe.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_disable.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_enable.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/diff.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/flags.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_legacy.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_recent.go
  vendor/github.com/google/go-cmp/cmp/internal/function/func.go
  vendor/github.com/google/go-cmp/cmp/internal/value/name.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_unsafe.go
  vendor/github.com/google/go-cmp/cmp/internal/value/sort.go
  vendor/github.com/google/go-cmp/cmp/internal/value/zero.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_references.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/google/go-cmp/cmp/report_text.go
  vendor/github.com/google/go-cmp/cmp/report_value.go
  vendor/github.com/google/gofuzz/.travis.yml
  vendor/github.com/google/gofuzz/CONTRIBUTING.md
  vendor/github.com/google/gofuzz/README.md
  vendor/github.com/google/gofuzz/bytesource/bytesource.go
  vendor/github.com/google/gofuzz/fuzz.go
  vendor/golang.org/x/xerrors/LICENSE
  vendor/golang.org/x/xerrors/PATENTS
  vendor/golang.org/x/xerrors/README
  vendor/golang.org/x/xerrors/adaptor.go
  vendor/golang.org/x/xerrors/codereview.cfg
  vendor/golang.org/x/xerrors/doc.go
  vendor/golang.org/x/xerrors/errors.go
  vendor/golang.org/x/xerrors/fmt.go
  vendor/golang.org/x/xerrors/format.go
  vendor/golang.org/x/xerrors/frame.go
  vendor/golang.org/x/xerrors/go.mod
  vendor/golang.org/x/xerrors/internal/internal.go
  vendor/golang.org/x/xerrors/wrap.go
  vendor/modules.txt
Labels: theme/streaming

#8801 ci: fix bindata autoupdate
  .circleci/config.yml
  GNUmakefile
  ui-v2/app/components/hashicorp-consul/index.hbs
  ui-v2/config/environment.js
Labels: type/ci

#8271 Use method and path as labels for http metrics
  agent/config/default.go
  agent/config/runtime_test.go
  agent/http.go
  website/pages/docs/agent/telemetry.mdx
Labels: theme/telemetry, type/enhancement

#8798 ui: Create template-anchor helper and remove component
  ui-v2/app/components/templated-anchor/index.hbs
  ui-v2/app/components/templated-anchor/index.js
  ui-v2/app/helpers/render-template.js
  ui-v2/app/templates/dc/services/show.hbs
  ui-v2/tests/integration/helpers/render-template-test.js
Labels: theme/ui

#8803 ui: Defer requesting gateway related services until the tab is visible
  ui-v2/app/routes/dc/services/show.js
  ui-v2/app/routes/dc/services/show/services.js
  ui-v2/app/routes/dc/services/show/upstreams.js
  ui-v2/app/templates/dc/services/show.hbs
  ui-v2/app/templates/dc/services/show/services.hbs
  ui-v2/app/templates/dc/services/show/upstreams.hbs
Labels: theme/ui

#8796 ui: CSS margin/border alterations
  ui-v2/app/styles/base/components/table/layout.scss
  ui-v2/app/styles/components/app-view.scss
  ui-v2/app/styles/components/app-view/index.scss
  ui-v2/app/styles/components/app-view/layout.scss
  ui-v2/app/styles/components/app-view/skin.scss
  ui-v2/app/styles/components/definition-table/layout.scss
  ui-v2/app/styles/components/filter-bar/layout.scss
  ui-v2/app/styles/layout.scss
  ui-v2/app/styles/typography.scss
Labels: theme/ui

#8808 docs: Add missing helm docs and make link anchors consistent
  website/pages/docs/k8s/helm.mdx
Labels: type/docs, type/docs-cherrypick

#8788 ui: Service Mesh - Topology tab and basic layout
  ui-v2/app/adapters/topology.js
  ui-v2/app/components/consul-service-list/index.hbs
  ui-v2/app/components/topology-metrics/index.hbs
  ui-v2/app/components/topology-metrics/index.js
  ui-v2/app/components/topology-metrics/index.scss
  ui-v2/app/components/topology-metrics/layout.scss
  ui-v2/app/components/topology-metrics/skin.scss
  ui-v2/app/controllers/dc/services/show.js
  ui-v2/app/helpers/service/health-percentage.js
  ui-v2/app/models/topology.js
  ui-v2/app/router.js
  ui-v2/app/routes/dc/services/show.js
  ui-v2/app/routes/dc/services/show/index.js
  ui-v2/app/routes/dc/services/show/topology.js
  ui-v2/app/serializers/topology.js
  ui-v2/app/services/data-source/protocols/http.js
  ui-v2/app/services/repository/topology.js
  ui-v2/app/styles/components.scss
  ui-v2/app/templates/dc/services/show.hbs
  ui-v2/app/templates/dc/services/show/topology.hbs
  ui-v2/package.json
  ui-v2/tests/acceptance/dc/list-blocking.feature
  ui-v2/tests/acceptance/dc/services/show-with-slashes.feature
  ui-v2/tests/acceptance/dc/services/show.feature
  ui-v2/tests/acceptance/dc/services/show/dc-switch.feature
  ui-v2/tests/acceptance/dc/services/show/intentions-error.feature
  ui-v2/tests/acceptance/page-navigation.feature
  ui-v2/tests/integration/adapters/topology-test.js
  ui-v2/tests/integration/helpers/service/health-percentage-test.js
  ui-v2/tests/integration/serializers/topology-test.js
  ui-v2/tests/integration/services/repository/topology-test.js
  ui-v2/yarn.lock
Labels: theme/ui

#8802 lib/retry - extract a new package from lib/retry.go
  agent/auto-config/auto_config.go
  agent/auto-config/auto_config_test.go
  agent/auto-config/auto_encrypt.go
  agent/auto-config/auto_encrypt_test.go
  agent/auto-config/config.go
  agent/consul/replication.go
  lib/retry.go
  lib/retry/retry.go
  lib/retry/retry_test.go
  lib/retry_test.go
Labels: theme/internal-cleanup

#8821 Fixes README overwrite
  .github/repo_management.md
Labels: theme/contributing

#8732 Docs: Add NIA Integration Program page
  website/data/docs-navigation.js
  website/pages/docs/integrate/nia-integration.mdx
  website/public/img/nia-highlevel-diagram.png
  website/public/img/nia-integration-program.png
Labels: type/docs

#8790 Docs: Add outline and basic content for Tech Preview docs
  website/data/docs-navigation.js
  website/pages/docs/nia/architecture.mdx
  website/pages/docs/nia/cli.mdx
  website/pages/docs/nia/index.mdx
  website/pages/docs/nia/installation/configuration.mdx
  website/pages/docs/nia/installation/install.mdx
  website/pages/docs/nia/installation/requirements.mdx
  website/pages/docs/nia/installation/run.mdx
  website/pages/docs/nia/network-drivers.mdx
  website/pages/docs/nia/tasks.mdx
Labels: type/docs

#8805 ui: Allow configuring a Datasource to poll an API endpoint instead of using Blocking Queries
  ui-v2/app/serializers/application.js
  ui-v2/app/services/client/http.js
  ui-v2/app/services/data-source/protocols/http/blocking.js
  ui-v2/app/utils/dom/event-source/blocking.js
Labels: theme/ui

#8804 ui: Replace proxy icon with mesh icon
  ui-v2/app/components/consul-service-instance-list/index.hbs
  ui-v2/app/routes/dc/services/show.js
Labels: theme/ui

#8817 ui: Fixup node tests to account for new runtime env var passing
  ui-v2/node-tests/config/environment.js
Labels: theme/ui

#8830 ui: Restrict header styling to specific tabs
  ui-v2/app/styles/routes/dc/services/index.scss
Labels: theme/ui

#8828 ui: Specify Service instance requests and proxy requests as ranges
  ui-v2/app/adapters/proxy.js
  ui-v2/app/adapters/service-instance.js
Labels: theme/ui

#8826 proto: fix RoundTrip test for enterprise
  proto/pbservice/convert_test.go
Labels: theme/streaming

#8806 rpcclient: Add health.Client and use it in http and dns
  agent/agent.go
  agent/dns.go
  agent/health_endpoint.go
  agent/rpcclient/health/health.go
Labels: theme/streaming

#8799 stream: remove EndOfEmptySnapshot, add NewSnapshotToFollow
  agent/consul/stream/event.go
  agent/consul/stream/event_buffer.go
  agent/consul/stream/event_publisher.go
  agent/consul/stream/event_publisher_test.go
  agent/consul/stream/event_snapshot.go
  agent/consul/stream/event_snapshot_test.go
  agent/consul/stream/event_test.go
  agent/consul/stream/subscription.go
  agent/consul/stream/subscription_test.go
  proto/pbsubscribe/subscribe.pb.go
  proto/pbsubscribe/subscribe.proto
Labels: theme/streaming

#8832 Remove label trigger on edit
  .github/workflows/issue-labeler.yml
Labels: theme/contributing

#8820 ui: add ui test-node
  .circleci/config.yml
Labels: theme/ui, type/ci

#8844 Add auto-labler for Consul Terrform Sync
  .github/issue-labeler.yml
  .github/pr-labeler.yml
  website/pages/docs/nia/index.mdx
Labels: backport/1.8, theme/contributing, type/docs, type/docs-cherrypick

#8836 ui: Fix up Service filtering by whether a Service is in the mesh or not in the mesh
  ui-v2/app/components/consul-service-search-bar/index.hbs
  ui-v2/app/filter/predicates/service.js
  ui-v2/app/models/service.js
Labels: theme/ui

#8850 ui: Move node listing copy button to the detail rather than the title
  ui-v2/app/components/consul-node-list/index.hbs
Labels: theme/ui

#8852 ui: Change qp name for service instance listing from nspace to ns
  ui-v2/app/services/repository/service-instance.js
Labels: theme/ui

#8840 CLI Docs for Consul Terraform Sync
  website/pages/docs/nia/cli.mdx
Labels: theme/consul-terraform-sync, type/docs

#8855 command: remove conditional envoy bootstrap generation for versions <=1.10.0 since those are not supported
  .changelog/8855.txt
  command/connect/envoy/bootstrap_tpl.go
Labels: theme/cli

#8838 Turns PR labeler to only trigger on create
  .github/workflows/pr-labeler.yml
Labels: theme/contributing

#8857 api: unflake some intention-related api tests
  api/connect_intention_test.go
Labels: theme/api

#8860 Task Docs for Consul Terraform Sync
  website/pages/docs/nia/tasks.mdx
Labels: theme/consul-terraform-sync, type/docs

#8870 test(vault): generate test coverage and upload to CodeCov
  .circleci/config.yml
  GNUmakefile
Labels: backport/1.6, backport/1.7, backport/1.8, type/ci

#8768 subscribe: add subscribe service for streaming change events
  agent/consul/options.go
  agent/consul/server.go
  agent/consul/state/acl.go
  agent/consul/stream/subscription.go
  agent/consul/subscribe_backend.go
  agent/grpc/handler.go
  agent/grpc/server_test.go
  agent/grpc/stats_test.go
  agent/rpc/subscribe/auth.go
  agent/rpc/subscribe/logger.go
  agent/rpc/subscribe/subscribe.go
  agent/rpc/subscribe/subscribe_test.go
  agent/setup.go
  agent/structs/structs.go
  agent/structs/structs_test.go
Labels: theme/streaming

#8818 stream: handle batch events as a special case of Event
  agent/consul/state/store_integration_test.go
  agent/consul/stream/event.go
  agent/consul/stream/event_publisher_test.go
  agent/consul/stream/subscription.go
  agent/consul/stream/subscription_test.go
  agent/rpc/subscribe/logger.go
  agent/rpc/subscribe/subscribe.go
Labels: theme/streaming

#8809 Add StreamingHealthServices cache-type
  agent/cache-types/streaming_events_test.go
  agent/cache-types/streaming_health_services.go
  agent/cache-types/streaming_health_services_test.go
  agent/cache-types/streaming_test.go
  agent/cache/cache.go
  agent/cache/cache_test.go
  agent/consul/stream/event_publisher.go
  agent/consul/stream/event_publisher_test.go
  agent/submatview/handler.go
  agent/submatview/materializer.go
Labels: theme/agent-cache, theme/streaming

#8841 streaming: Use an ID that includes namespace to store services in the materialized view
  agent/cache-types/streaming_health_services.go
  proto/pbcommon/common.pb.binary.go
  proto/pbcommon/common.pb.go
  proto/pbcommon/common.proto
  proto/pbcommon/common_oss.pb.binary.go
  proto/pbcommon/common_oss.pb.go
  proto/pbcommon/common_oss.proto
  proto/pbconnect/connect.pb.go
  proto/pbconnect/connect.proto
  proto/pbservice/healthcheck.pb.go
  proto/pbservice/healthcheck.proto
  proto/pbservice/ids.go
  proto/pbservice/ids_test.go
  proto/pbservice/node.pb.go
  proto/pbservice/node.proto
  proto/pbservice/service.pb.go
  proto/pbservice/service.proto
Labels: theme/streaming

#8878 ui: Use a custom request for nspace deletion
  ui-v2/app/components/consul-nspace-list/index.hbs
  ui-v2/app/services/repository/nspace.js
Labels: theme/ui

#8851 ui: L7 intentions improvements
  ui-v2/app/components/consul-intention-form/fieldsets/index.hbs
  ui-v2/app/components/consul-intention-form/fieldsets/skin.scss
  ui-v2/app/components/consul-intention-permission-form/index.hbs
  ui-v2/app/components/consul-intention-permission-form/skin.scss
  ui-v2/app/components/consul-intention-permission-header-form/index.hbs
  ui-v2/app/components/consul-intention-permission-list/index.hbs
  ui-v2/app/components/consul-intention-permission-list/index.scss
  ui-v2/app/components/form-group/element/checkbox/index.hbs
  ui-v2/app/components/form-group/element/error/index.hbs
  ui-v2/app/components/form-group/element/index.hbs
  ui-v2/app/components/form-group/element/index.js
  ui-v2/app/components/form-group/element/label/index.hbs
  ui-v2/app/components/form-group/element/radio/index.hbs
  ui-v2/app/components/form-group/element/text/index.hbs
  ui-v2/app/components/form-group/index.hbs
  ui-v2/app/components/form-group/index.js
  ui-v2/app/styles/base/color/frame-placeholders.scss
  ui-v2/app/styles/components/list-row/layout.scss
  ui-v2/app/styles/routes.scss
  ui-v2/app/styles/routes/dc/intentions/index.scss
  ui-v2/tests/acceptance/dc/intentions/filtered-select.feature
  ui-v2/tests/acceptance/dc/intentions/form-select.feature
Labels: theme/ui

#8871 Add docs for NIA Terraform driver
  website/pages/docs/nia/network-drivers.mdx
Labels: theme/consul-terraform-sync, type/docs

#8873 ui: Add namespaces to downstream cards
  ui-v2/app/components/topology-metrics/index.hbs
Labels: theme/ui

#8846 ui: Add deny SVG lines with icons
  ui-v2/app/components/topology-metrics/down-lines/index.hbs
  ui-v2/app/components/topology-metrics/down-lines/index.js
  ui-v2/app/components/topology-metrics/icon.hbs
  ui-v2/app/components/topology-metrics/index.hbs
  ui-v2/app/components/topology-metrics/index.js
  ui-v2/app/components/topology-metrics/skin.scss
  ui-v2/app/components/topology-metrics/up-lines/index.hbs
  ui-v2/app/components/topology-metrics/up-lines/index.js
  ui-v2/app/helpers/service/intention-permissions.js
  ui-v2/package.json
  ui-v2/tests/integration/helpers/service/intention-permissions-test.js
  ui-v2/yarn.lock
Labels: theme/ui

#8880 chore(ci): remove docs-cherrypick autolabel
  .github/pr-labeler.yml
Labels: theme/contributing

#8781 Add per-agent reconnect timeouts
  .changelog/8781.txt
  agent/agent.go
  agent/config/builder.go
  agent/config/config.go
  agent/config/runtime.go
  agent/config/runtime_test.go
  agent/consul/acl_client.go
  agent/consul/acl_server.go
  agent/consul/client_serf.go
  agent/consul/client_test.go
  agent/consul/config.go
  agent/consul/server_serf.go
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  lib/serf.go
  lib/serf/serf.go
  vendor/github.com/hashicorp/serf/coordinate/phantom.go
  vendor/github.com/hashicorp/serf/serf/config.go
  vendor/github.com/hashicorp/serf/serf/merge_delegate.go
  vendor/github.com/hashicorp/serf/serf/serf.go
  vendor/modules.txt
  website/pages/docs/agent/options.mdx
Labels: pr/dependencies, theme/api, theme/config

#8822 chore: update raft to v1.2.0
  go.mod
  go.sum
  vendor/github.com/hashicorp/raft/CHANGELOG.md
  vendor/github.com/hashicorp/raft/Makefile
  vendor/github.com/hashicorp/raft/README.md
  vendor/github.com/hashicorp/raft/api.go
  vendor/github.com/hashicorp/raft/config.go
  vendor/github.com/hashicorp/raft/file_snapshot.go
  vendor/github.com/hashicorp/raft/future.go
  vendor/github.com/hashicorp/raft/inmem_snapshot.go
  vendor/github.com/hashicorp/raft/inmem_transport.go
  vendor/github.com/hashicorp/raft/net_transport.go
  vendor/github.com/hashicorp/raft/raft.go
  vendor/github.com/hashicorp/raft/replication.go
  vendor/github.com/hashicorp/raft/snapshot.go
  vendor/github.com/hashicorp/raft/tcp_transport.go
  vendor/github.com/hashicorp/raft/testing.go
  vendor/github.com/hashicorp/raft/util.go
  vendor/modules.txt
Labels: pr/dependencies

#8879 ui: Fix up positioning of subpage loader animation
  ui-v2/app/styles/components/app-view/layout.scss
  ui-v2/app/styles/components/breadcrumbs.scss
  ui-v2/app/styles/layout.scss
Labels: theme/ui

#8884 ui: Workaround FF and/or ember problem, trying to set a value=""
  ui-v2/app/components/consul-intention-form/fieldsets/layout.scss
  ui-v2/app/components/radio-card/index.hbs
Labels: theme/ui

#8872 initial high level architecture overview
  website/pages/docs/nia/architecture.mdx
Labels: theme/consul-terraform-sync, type/docs

#8881 Update Installation Docs for Consul Terraform Sync
  website/pages/docs/nia/installation/configuration.mdx
  website/pages/docs/nia/installation/install.mdx
  website/pages/docs/nia/tasks.mdx
Labels: theme/consul-terraform-sync, type/docs

#8877 Add flag for disabling 1.9 metrics backwards compatibility and warnings when set to default
  agent/agent.go
  agent/config/builder.go
  agent/config/config.go
  agent/config/default.go
  agent/config/runtime_test.go
  agent/http.go
  lib/telemetry.go
  website/pages/docs/agent/telemetry.mdx
Labels: theme/config, theme/internals, theme/telemetry, type/docs

#8889 ui: fix the namespace flag
  ui-v2/config/environment.js
  ui-v2/node-tests/config/environment.js
Labels: theme/ui

#8890 website: re-add forgotten updates
  website/pages/commands/snapshot/agent.mdx
Labels: type/docs

#8887 Docs: compatible Terraform modules for Consul-Terraform-Sync
  website/pages/docs/nia/installation/requirements.mdx
  website/pages/docs/nia/network-drivers.mdx
Labels: theme/consul-terraform-sync

#8892 Update Requirements Docs for Consul Terraform Sync
  website/pages/docs/nia/installation/requirements.mdx
Labels: theme/consul-terraform-sync, type/docs

#8895 Docs: add link and fix typo (dup word)
  website/pages/docs/nia/architecture.mdx
Labels: theme/consul-terraform-sync, type/docs

#8888 Docs: Add TF module naming convention, update image and links
  website/pages/docs/integrate/nia-integration.mdx
  website/public/img/nia-highlevel-diagram.png
Labels: theme/consul-terraform-sync, type/docs

#8774 Add capability for the v1/connect/ca/roots endpoint to return a PEM encoded certificate chain
  .changelog/8774.txt
  agent/connect_ca_endpoint.go
  agent/connect_ca_endpoint_test.go
  website/pages/api-docs/connect/ca.mdx
Labels: backport/1.8

#8903 Remove oss/ent divergence of runtime_test.go
  agent/config/runtime_oss_test.go
  agent/config/runtime_test.go
Labels: theme/config

#8885 ui: Update instances count for ingress and terminating gateways
  ui-v2/app/components/consul-service-list/index.hbs
Labels: theme/ui

#8899 ui: Add simple intention check interface to per service intentions
  ui-v2/app/components/consul-intention-list/index.hbs
  ui-v2/app/components/consul-intention-list/index.js
  ui-v2/app/components/consul-intention-list/index.scss
  ui-v2/app/components/consul/intention/list/check/index.hbs
  ui-v2/app/components/consul/intention/list/components.scss
  ui-v2/app/components/consul/intention/list/index.hbs
  ui-v2/app/components/consul/intention/list/index.scss
  ui-v2/app/components/consul/intention/list/layout.scss
  ui-v2/app/components/consul/intention/list/pageobject.js
  ui-v2/app/components/consul/intention/list/skin.scss
  ui-v2/app/components/consul/intention/list/table/index.hbs
  ui-v2/app/styles/components.scss
  ui-v2/app/styles/components/notice.scss
  ui-v2/app/templates/dc/intentions/index.hbs
  ui-v2/app/templates/dc/services/show/intentions/index.hbs
  ui-v2/package.json
  ui-v2/tests/pages.js
  ui-v2/yarn.lock
Labels: theme/ui

#8854 [Website] Add HashiStackMenu to website
  website/next.config.js
  website/package-lock.json
  website/package.json
  website/pages/_app.js
  website/pages/style.css
Labels: type/docs, type/docs-cherrypick

#8848 Docs: NIA integration program small updates
  website/pages/docs/integrate/nia-integration.mdx
Labels: theme/consul-terraform-sync, type/docs

#8904 Remove empty partner module sections
  website/pages/docs/nia/installation/requirements.mdx
Labels: theme/consul-terraform-sync, type/docs

#8896 ci: go test -race more packages
  .circleci/config.yml
  agent/cache-types/connect_ca_leaf.go
  agent/cache-types/connect_ca_leaf_test.go
  agent/cache-types/norace_test.go
  agent/cache-types/race_test.go
  agent/cache-types/testing.go
  agent/grpc/stats_test.go
Labels: theme/streaming, type/ci

#8893 subscribe: add steps to long test cases, and add new cases for converting Events
  agent/rpc/subscribe/subscribe.go
  agent/rpc/subscribe/subscribe_test.go
  agent/user_event.go
Labels: theme/streaming

#8907 Docs: Nia/docs partner integration
  website/data/docs-navigation.js
  website/pages/docs/integrate/nia-integration.mdx
  website/public/img/nia-highlevel-diagram.png
  website/public/img/nia-integration-program.png
Labels: type/docs, type/docs-cherrypick

#8825 streaming: add config and docs
  agent/agent.go
  agent/cache-types/streaming_health_services.go
  agent/config/builder.go
  agent/config/config.go
  agent/config/runtime.go
  agent/config/runtime_test.go
  agent/consul/config.go
  agent/consul/server.go
  agent/rpcclient/health/health.go
  agent/setup.go
  contributing/checklist-adding-config-fields.md
  website/pages/docs/agent/options.mdx
Labels: theme/streaming

#8908 Docs: Nia/docs tech preview
  .github/issue-labeler.yml
  .github/pr-labeler.yml
  website/data/docs-navigation.js
  website/pages/docs/nia/architecture.mdx
  website/pages/docs/nia/cli.mdx
  website/pages/docs/nia/index.mdx
  website/pages/docs/nia/installation/configuration.mdx
  website/pages/docs/nia/installation/install.mdx
  website/pages/docs/nia/installation/requirements.mdx
  website/pages/docs/nia/installation/run.mdx
  website/pages/docs/nia/network-drivers.mdx
  website/pages/docs/nia/tasks.mdx
Labels: theme/consul-terraform-sync, theme/contributing, type/docs, type/docs-cherrypick

#8909 ui: Send kind query to the service-topology endpoint
  ui-v2/app/adapters/topology.js
  ui-v2/app/routes/dc/services/show.js
  ui-v2/app/services/data-source/protocols/http.js
  ui-v2/app/services/repository/topology.js
  ui-v2/tests/integration/adapters/topology-test.js
  ui-v2/tests/integration/services/repository/topology-test.js
Labels: theme/ui

#8910 go-changelog template with ent support
  .changelog/note.tmpl
Labels: backport/1.6, backport/1.7, backport/1.8

#8912 Minor updates to NIA partner docs
  website/pages/docs/integrate/nia-integration.mdx
Labels: theme/consul-terraform-sync, type/docs-cherrypick

#8784 connect: Enable renewing the intermediate cert in the primary DC
  .changelog/8784.txt
  GNUmakefile
  agent/connect/ca/provider.go
  agent/connect/ca/provider_consul.go
  agent/connect/ca/provider_vault.go
  agent/connect/ca/provider_vault_test.go
  agent/connect/ca/testing.go
  agent/consul/leader_connect.go
  agent/consul/leader_connect_test.go
  agent/consul/server.go
Labels: backport/1.8

#8845 doc: Update acl-method command example
  command/acl/authmethod/authmethod.go
  command/acl/authmethod/create/authmethod_create.go
  command/acl/authmethod/update/authmethod_update.go
  website/pages/commands/acl/auth-method/index.mdx
Labels: theme/cli, type/docs, type/docs-cherrypick

#8913 adds missing options.mdx entry for telemetry {disable_compat_1.9}
  website/pages/docs/agent/options.mdx
Labels: type/docs

#8740 add per commit oss->ent merge on master and release branches
  .circleci/config.yml
Labels: type/ci

#8916 [skip ci] ci: fix trigger-oss-merge yaml spacing
  .circleci/config.yml
Labels: type/ci

#8780 Update service-defaults.mdx to add supported protocols
  website/pages/docs/agent/config-entries/service-defaults.mdx
Labels: type/docs, type/docs-cherrypick

#8911 ui: Make the topology cards into links
  ui-v2/app/components/topology-metrics/card.hbs
  ui-v2/app/components/topology-metrics/layout.scss
  ui-v2/app/components/topology-metrics/stats/index.scss
Labels: theme/ui

#8905 ui: CSS amends
  ui-v2/app/styles/components/app-view.scss
  ui-v2/app/styles/components/buttons.scss
  ui-v2/app/styles/components/list-collection.scss
  ui-v2/app/styles/components/tabular-collection.scss
  ui-v2/app/styles/layout.scss
  ui-v2/app/styles/variables/custom-query.scss
Labels: theme/ui

#8925 Docs: Update a link and reword some sentences
  website/pages/docs/integrate/nia-integration.mdx
Labels: type/docs, type/docs-cherrypick

#8833 docs: add Helm docs for openshift; also add other missing Helm docs
  website/pages/docs/k8s/helm.mdx
Labels: type/docs, type/docs-cherrypick

#8928 Update Helm compatibility matrix
  website/pages/docs/k8s/upgrade/compatibility.mdx
Labels: type/docs, type/docs-cherrypick

#8929 Service mesh page updates
  website/pages/use-cases/img/ConsulACI.png
  website/pages/use-cases/img/DynamicFirewalling.svg
  website/pages/use-cases/img/DynamicLoadBalancing.svg
  website/pages/use-cases/img/IntegrateAndExtend.svg
  website/pages/use-cases/img/NIA_logo_grid.svg
  website/pages/use-cases/img/website-app-aware-intentions.png
  website/pages/use-cases/img/website-mesh-viz.png
  website/pages/use-cases/multi-platform-service-mesh.jsx
  website/pages/use-cases/network-infrastructure-automation.jsx
Labels: type/docs

#8926 Include integration docs for NIA with consul-terraform-sync label
  .github/pr-labeler.yml
Labels: theme/contributing

#8935 Update Requirements doc: Terraform module links
  website/pages/docs/nia/installation/requirements.mdx
Labels: theme/consul-terraform-sync, type/docs, type/docs-cherrypick

#8933 ui: Autofill intention destination as opposed to source on creation
  ui-v2/app/templates/dc/services/show/intentions/edit.hbs
Labels: theme/ui

#8931 Docs: Remove email address
  website/pages/docs/integrate/nia-integration.mdx
Labels: theme/consul-terraform-sync, type/docs, type/docs-cherrypick

#8921 Add ui metrics config docs
  website/pages/docs/agent/options.mdx
Labels: type/docs

#8939 website: add v1.9.0-beta1 download callout
  website/pages/downloads/index.jsx
Labels: type/docs

#8943 docs: Add a note about auto-renewing the Vault token
  website/pages/docs/agent/options.mdx
  website/pages/docs/connect/ca/vault.mdx
Labels: type/docs

#8946 Add files via upload
  website/pages/use-cases/img/NIA_logo_grid.svg
Labels: type/docs, type/docs-cherrypick

#8945 Recommend using vault token auto-renew in 1.8.5
  website/pages/docs/k8s/connect/connect-ca-provider.mdx
Labels: type/docs

#8947 Add streaming changelog file
  .changelog/_8825.txt
Labels: theme/streaming

#8920 CRD Docs
  website/data/docs-navigation.js
  website/pages/docs/k8s/crds.mdx
Labels: type/docs

#8957 [Website] Bump HSM version
  website/package-lock.json
  website/package.json
Labels: type/docs

#8960 truncate jepsen.mdx log for length
  website/pages/docs/architecture/jepsen.mdx
Labels: type/docs, type/docs-cherrypick

#8962 Update banner for Consul 1.9
  website/data/alert-banner.js
Labels: type/docs, type/docs-cherrypick

#8958 Fix robots.txt to disallow indexing of all paths
  ui-v2/public/robots.txt
Labels: theme/ui

#8971 [Website] Update HSM version w/ Waypoint
  website/package-lock.json
  website/package.json
Labels: type/docs, type/docs-cherrypick

#8956 Update to CRD docs
  website/pages/docs/k8s/crds.mdx
Labels: type/docs, type/docs-cherrypick

#8950 Docs: Add A10 and Checkpoint TF modules
  website/pages/docs/nia/installation/requirements.mdx
Labels: theme/consul-terraform-sync, type/docs, type/docs-cherrypick

#8922 ui: Upgrade ember-power-select and ember-basic-dropdown
  ui-v2/package.json
  ui-v2/yarn.lock
Labels: theme/ui

#8955 ui: [BUGFIX] Fixup gateway services API call
  ui-v2/app/routes/dc/services/show/services.js
Labels: theme/ui

#8963 ui: Change text around L7 permissions to app aware
  ui-v2/app/components/consul/intention/components.scss
  ui-v2/app/components/consul/intention/form/fieldsets/index.hbs
  ui-v2/app/components/consul/intention/index.scss
  ui-v2/app/components/consul/intention/list/components.scss
  ui-v2/app/components/consul/intention/list/layout.scss
  ui-v2/app/components/consul/intention/list/table/index.hbs
  ui-v2/app/components/consul/intention/permission/list/index.hbs
  ui-v2/app/components/consul/intention/search-bar/index.hbs
  ui-v2/app/components/consul/intention/search-bar/index.scss
  ui-v2/app/styles/base/components/pill/layout.scss
  ui-v2/app/styles/components.scss
  ui-v2/app/styles/components/pill.scss
  ui-v2/app/styles/components/popover-select.scss
Labels: theme/ui

#8954 ui: Depend on less D3
  ui-v2/app/components/topology-metrics/series/index.js
  ui-v2/package.json
  ui-v2/yarn.lock
Labels: theme/ui

#8967 ui: Update route blueprint to use native classes and consul base route
  ui-v2/blueprints/route/files/__root__/__path__/__name__.js
  ui-v2/blueprints/route/files/__root__/__templatepath__/__templatename__.hbs
  ui-v2/blueprints/route/native-files/__root__/__path__/__name__.js
  ui-v2/blueprints/route/native-files/__root__/__templatepath__/__templatename__.hbs
Labels: theme/ui

#8981 ui: Remove nspace value from routeName
  ui-v2/app/components/outlet/index.js
Labels: theme/ui

#8966 ui: Clean up and document environment.js file
  .circleci/config.yml
  ui-v2/config/environment.js
  ui-v2/config/utils.js
  ui-v2/node-tests/config/environment.js
  ui-v2/node-tests/config/utils.js
Labels: theme/ui, type/ci

#8965 ui: Prefer using a base route class instead of reopening routes
  ui-v2/app/initializers/controller-lifecycle.js
  ui-v2/app/initializers/route-urldecode-params.js
  ui-v2/app/routing/route.js
Labels: theme/ui

#8968 ui: Move all our notification partials to components
  ui-v2/app/components/consul/acl/notifications/index.hbs
  ui-v2/app/components/consul/lock-session/notifications/index.hbs
  ui-v2/app/components/consul/nspace/notifications/index.hbs
  ui-v2/app/components/consul/policy/notifications/index.hbs
  ui-v2/app/components/consul/role/notifications/index.hbs
  ui-v2/app/components/consul/service/notifications/index.hbs
  ui-v2/app/components/consul/token/notifications/index.hbs
  ui-v2/app/templates/dc/acls/edit.hbs
  ui-v2/app/templates/dc/acls/index.hbs
  ui-v2/app/templates/dc/acls/policies/edit.hbs
  ui-v2/app/templates/dc/acls/policies/index.hbs
  ui-v2/app/templates/dc/acls/roles/edit.hbs
  ui-v2/app/templates/dc/acls/roles/index.hbs
  ui-v2/app/templates/dc/acls/tokens/edit.hbs
  ui-v2/app/templates/dc/acls/tokens/index.hbs
  ui-v2/app/templates/dc/nodes/-notifications.hbs
  ui-v2/app/templates/dc/nodes/show.hbs
  ui-v2/app/templates/dc/nspaces/edit.hbs
  ui-v2/app/templates/dc/nspaces/index.hbs
  ui-v2/app/templates/dc/services/index.hbs
  ui-v2/app/templates/dc/services/instance.hbs
  ui-v2/app/templates/dc/services/show.hbs
Labels: theme/ui

#8949 Docs: Update links in NIA Integration Program
  website/pages/docs/integrate/nia-integration.mdx
Labels: theme/consul-terraform-sync, type/docs, type/docs-cherrypick

#8989 Refactor metrics provider interface for time series.
  ui-v2/app/components/topology-metrics/index.js
  ui-v2/app/components/topology-metrics/series/index.hbs
  ui-v2/app/components/topology-metrics/series/index.js
  ui-v2/app/components/topology-metrics/series/layout.scss
  ui-v2/app/components/topology-metrics/series/skin.scss
  ui-v2/app/services/repository/metrics.js
  ui-v2/vendor/metrics-providers/prometheus.js
Labels: theme/ui

#8959 Update docs-navigation.js
  website/data/docs-navigation.js
Labels: type/docs, type/docs-cherrypick

#8993 docs: Remove sentence about pluggable CAs
  website/pages/docs/connect/ca/index.mdx
Labels: type/docs, type/docs-cherrypick

#8771 Fix GRPCUseTLS flag HTTP API mapping
  .changelog/8771.txt
  agent/http_decode_test.go
  agent/structs/check_definition.go
  agent/structs/check_type.go
Labels: theme/api, type/bug

#9004 dns: remove goto INVALID and a naked return
  agent/dns.go
Labels: theme/dns

#8997 Add extraEnvVars and client.affinity to Helm values
  website/pages/docs/k8s/helm.mdx
Labels: type/docs, type/docs-cherrypick

#8924 Fix: service LocallyRegisteredAsSidecar property is not persisted
  .changelog/8924.txt
  agent/agent.go
  agent/agent_test.go
Labels: backport/1.8, theme/connect, type/bug

#8973 agent/router: refactor calculation of delay between rebalances.
  agent/router/manager.go
  agent/router/manager_internal_test.go
  agent/router/router.go
Labels: theme/internal-cleanup

#8982 speed up envoy integration tests by removing docker-compose
  test/integration/connect/envoy/case-consul-exec/setup.sh
  test/integration/connect/envoy/docker-compose.yml
  test/integration/connect/envoy/down.sh
  test/integration/connect/envoy/run-tests.sh
Labels: theme/testing

#8985 NIA: document daemon exiting on task errors
  website/pages/docs/nia/tasks.mdx
Labels: theme/consul-terraform-sync, type/docs, type/docs-cherrypick

#9015 move static-assets dist to new path
  .circleci/config.yml
Labels: type/ci

#9011 ui: Notice component
  ui/packages/consul-ui/app/components/anonymous/index.hbs
  ui/packages/consul-ui/app/components/anonymous/index.js
  ui/packages/consul-ui/app/components/notice/index.hbs
  ui/packages/consul-ui/app/styles/base/components/notice/layout.scss
  ui/packages/consul-ui/app/styles/base/components/notice/skin.scss
  ui/packages/consul-ui/app/styles/components/notice.scss
Labels: theme/ui

#9002 ui: Update Topology metrics dashboard and configuration links
  ui/packages/consul-ui/app/components/topology-metrics/index.hbs
  ui/packages/consul-ui/app/components/topology-metrics/skin.scss
  ui/packages/consul-ui/app/routes/dc/services/show.js
  ui/packages/consul-ui/app/templates/dc/services/show/topology.hbs
  ui/packages/consul-ui/app/templates/settings.hbs
  ui/packages/consul-ui/lib/startup/templates/head.html.js
  ui/packages/consul-ui/tests/acceptance/dc/services/show.feature
Labels: theme/ui

#9008 ui: Prevent redirect to topology url and hide Topology tab if service has no services
  ui/packages/consul-ui/app/models/topology.js
  ui/packages/consul-ui/app/routes/dc/services/show/index.js
  ui/packages/consul-ui/app/templates/dc/services/show.hbs
  ui/packages/consul-ui/tests/acceptance/dc/services/show-topology.feature
  ui/packages/consul-ui/tests/acceptance/steps/dc/services/show-topology-steps.js
  ui/packages/consul-ui/tests/pages/dc/services/show.js
Labels: theme/ui

#9014 ui: Fix the pointer events to view the tooltips when hovering over the icons
  ui/packages/consul-ui/app/components/topology-metrics/index.hbs
  ui/packages/consul-ui/app/components/topology-metrics/index.js
  ui/packages/consul-ui/app/components/topology-metrics/layout.scss
  ui/packages/consul-ui/app/components/topology-metrics/series/layout.scss
Labels: theme/ui

#9019 ui: Fixup CSS for create pages
  ui/packages/consul-ui/app/styles/components/tabular-collection.scss
  ui/packages/consul-ui/app/styles/layout.scss
  ui/packages/consul-ui/app/styles/routes/dc/acls/index.scss
  ui/packages/consul-ui/app/styles/routes/dc/kv/index.scss
Labels: theme/ui

#9016 Update managed-deprecated.mdx
  website/pages/docs/connect/proxies/managed-deprecated.mdx
Labels: type/docs-cherrypick

#9005 ci: add parallelism to envoy tests
  .circleci/config.yml
Labels: type/ci

#9003 ui: Initial Intention Permission Integration and acceptance testing
  ui/packages/consul-ui/app/components/consul/intention/form/fieldsets/index.hbs
  ui/packages/consul-ui/app/components/consul/intention/permission/form/index.hbs
  ui/packages/consul-ui/app/components/consul/intention/permission/form/pageobject.js
  ui/packages/consul-ui/app/components/consul/intention/permission/header/form/pageobject.js
  ui/packages/consul-ui/app/components/consul/intention/permission/header/list/pageobject.js
  ui/packages/consul-ui/app/components/consul/intention/permission/list/pageobject.js
  ui/packages/consul-ui/app/components/power-select/pageobject.js
  ui/packages/consul-ui/tests/acceptance/dc/intentions/permissions/create.feature
  ui/packages/consul-ui/tests/acceptance/steps/dc/intentions/permissions/create-steps.js
  ui/packages/consul-ui/tests/acceptance/steps/steps.js
  ui/packages/consul-ui/tests/dictionary.js
  ui/packages/consul-ui/tests/helpers/page.js
  ui/packages/consul-ui/tests/helpers/yadda-annotations.js
  ui/packages/consul-ui/tests/integration/components/consul/intention/permission/form-test.js
  ui/packages/consul-ui/tests/integration/components/consul/intention/permission/header/form-test.js
  ui/packages/consul-ui/tests/lib/page-object/index.js
  ui/packages/consul-ui/tests/pages.js
  ui/packages/consul-ui/tests/pages/dc/intentions/edit.js
  ui/packages/consul-ui/tests/steps.js
  ui/packages/consul-ui/tests/steps/assertions/page.js
  ui/packages/consul-ui/tests/steps/interactions/visit.js
Labels: theme/ui

#8975 stream: close the subscription on Unsubscribe
  agent/consul/state/store_integration_test.go
  agent/consul/stream/event_buffer.go
  agent/consul/stream/event_publisher_test.go
  agent/consul/stream/subscription.go
  agent/consul/stream/subscription_test.go
  agent/rpc/subscribe/subscribe.go
Labels: theme/streaming

#9024 server: config entry replication now correctly uses namespaces in comparisons
  .changelog/9024.txt
  agent/consul/config_replication.go
  agent/consul/config_replication_test.go
  agent/structs/config_entry.go
  agent/structs/connect_proxy_config.go
Labels: backport/1.7, backport/1.8

#9018 ui: Intention Custom Resource Banners
  ui/packages/consul-ui/app/components/consul/intention/form/index.hbs
  ui/packages/consul-ui/app/components/consul/intention/form/index.js
  ui/packages/consul-ui/app/components/consul/intention/list/index.hbs
  ui/packages/consul-ui/app/components/consul/intention/list/index.js
  ui/packages/consul-ui/app/components/consul/intention/list/pageobject.js
  ui/packages/consul-ui/app/components/consul/intention/notice/custom-resource/index.hbs
  ui/packages/consul-ui/app/initializers/search.js
  ui/packages/consul-ui/app/search/filters/intention.js
  ui/packages/consul-ui/app/search/predicates/intention.js
  ui/packages/consul-ui/app/services/repository/intention.js
  ui/packages/consul-ui/app/services/search.js
  ui/packages/consul-ui/app/styles/base/components/notice/skin.scss
  ui/packages/consul-ui/app/templates/dc/intentions/index.hbs
  ui/packages/consul-ui/app/templates/dc/services/show/intentions/index.hbs
  ui/packages/consul-ui/tests/acceptance/dc/intentions/delete.feature
  ui/packages/consul-ui/tests/acceptance/dc/intentions/index.feature
  ui/packages/consul-ui/tests/acceptance/dc/intentions/navigation.feature
  ui/packages/consul-ui/tests/acceptance/dc/intentions/sorting.feature
  ui/packages/consul-ui/tests/acceptance/dc/list-blocking.feature
  ui/packages/consul-ui/tests/acceptance/dc/services/show/intentions.feature
  ui/packages/consul-ui/tests/pages.js
  ui/packages/consul-ui/tests/pages/dc/intentions/index.js
  ui/packages/consul-ui/tests/pages/dc/services/show.js
  ui/packages/consul-ui/tests/steps/assertions/model.js
  ui/packages/consul-ui/tests/steps/assertions/page.js
  ui/packages/consul-ui/tests/steps/interactions/click.js
  ui/packages/consul-ui/tests/unit/search/predicates/intention-test.js
Labels: theme/ui

#9023 NIA: add Terraform version compatibility
  website/pages/docs/nia/installation/requirements.mdx
Labels: theme/consul-terraform-sync, type/docs, type/docs-cherrypick

#9034 website: update version.js
  website/data/version.js
Labels: type/docs, type/docs-cherrypick

#9035 ui: Upgrade the rest of the UI to use the new Notice component
  ui/packages/consul-ui/app/components/auth-form/index.hbs
  ui/packages/consul-ui/app/components/consul/intention/form/fieldsets/index.hbs
  ui/packages/consul-ui/app/components/consul/intention/form/index.hbs
  ui/packages/consul-ui/app/components/consul/intention/notice/custom-resource/index.hbs
  ui/packages/consul-ui/app/components/consul/intention/notice/permissions/index.hbs
  ui/packages/consul-ui/app/components/consul/intention/view/index.hbs
  ui/packages/consul-ui/app/components/notice/index.hbs
  ui/packages/consul-ui/app/components/notice/index.scss
  ui/packages/consul-ui/app/components/notice/layout.scss
  ui/packages/consul-ui/app/components/notice/skin.scss
  ui/packages/consul-ui/app/styles/base/components/index.scss
  ui/packages/consul-ui/app/styles/base/components/notice/index.scss
  ui/packages/consul-ui/app/styles/base/components/notice/skin.scss
  ui/packages/consul-ui/app/styles/components.scss
  ui/packages/consul-ui/app/styles/components/notice.scss
  ui/packages/consul-ui/app/templates/dc/acls/policies/-view.hbs
  ui/packages/consul-ui/app/templates/dc/acls/tokens/edit.hbs
  ui/packages/consul-ui/app/templates/dc/acls/tokens/index.hbs
  ui/packages/consul-ui/app/templates/dc/kv/edit.hbs
  ui/packages/consul-ui/app/templates/settings.hbs
Labels: theme/ui

#9038 ci: upgrade gotestsum
  .circleci/config.yml
Labels: type/ci

#9021 Expose `expirationDate` prop in <AlertBanner/>
  website/data/alert-banner.js
  website/package-lock.json
  website/package.json
  website/pages/style.css
Labels: backport/1.8, type/docs, type/docs-cherrypick

#9045 ui: Upgrade consul-api-double to fix datacenter mocks
  .circleci/config.yml
  ui/packages/consul-ui/package.json
  ui/yarn.lock
Labels: theme/ui, type/ci

#9041 ui: Topology limited access banner
  ui/packages/consul-ui/app/components/topology-metrics/notice/limited-access.hbs
  ui/packages/consul-ui/app/models/topology.js
  ui/packages/consul-ui/app/templates/dc/services/show/topology.hbs
Labels: theme/ui

#9047 Remove auto-docs-cherrypick and update UI label
  .github/issue-labeler.yml
  .github/pr-labeler.yml
Labels: theme/contributing

#9040 ui: Remove downstream dc filter
  ui/packages/consul-ui/app/components/topology-metrics/index.hbs
  ui/packages/consul-ui/app/templates/dc/services/show/topology.hbs
  ui/packages/consul-ui/lib/startup/templates/head.html.js
  ui/packages/consul-ui/tests/acceptance/dc/services/show.feature
  ui/packages/consul-ui/tests/pages/dc/services/show.js
Labels: theme/ui

#9046 ui: Delete old yarn lock file
  ui/packages/consul-ui/.travis.yml
  ui/packages/consul-ui/GNUmakefile
  ui/packages/consul-ui/yarn.lock
Labels: theme/ui

#9044 ui: Metrics - Don't swallow metrics errors
  ui/packages/consul-ui/app/utils/dom/event-source/blocking.js
  ui/packages/consul-ui/tests/unit/utils/dom/event-source/blocking-test.js
  ui/packages/consul-ui/vendor/metrics-providers/prometheus.js
Labels: theme/ui

#8987 streaming: apply filter to a single item
  agent/cache-types/streaming_health_services.go
Labels: theme/streaming

#8998 lib/ttlcache: extract a new package from agent/cache
  agent/cache/cache.go
  agent/cache/cache_test.go
  agent/cache/entry.go
  agent/cache/entry_test.go
  lib/ttlcache/eviction.go
  lib/ttlcache/eviction_test.go
Labels: theme/agent-cache, theme/internals, theme/streaming
