Repository hashicorp/consul, pull requests merged in 2020-03, with the labels that each got.

#7342 ui: Split out product css component into its separate elements
  ui-v2/app/styles/components/action-group.scss
  ui-v2/app/styles/components/app-view.scss
  ui-v2/app/styles/components/brand-loader.scss
  ui-v2/app/styles/components/brand-loader/index.scss
  ui-v2/app/styles/components/brand-loader/layout.scss
  ui-v2/app/styles/components/brand-loader/skin.scss
  ui-v2/app/styles/components/discovery-chain.scss
  ui-v2/app/styles/components/discovery-chain/layout.scss
  ui-v2/app/styles/components/footer.scss
  ui-v2/app/styles/components/footer/index.scss
  ui-v2/app/styles/components/footer/layout.scss
  ui-v2/app/styles/components/footer/skin.scss
  ui-v2/app/styles/components/index.scss
  ui-v2/app/styles/components/loader.scss
  ui-v2/app/styles/components/loader/index.scss
  ui-v2/app/styles/components/loader/layout.scss
  ui-v2/app/styles/components/loader/skin.scss
  ui-v2/app/styles/components/main-header-horizontal.scss
  ui-v2/app/styles/components/main-header-horizontal/index.scss
  ui-v2/app/styles/components/main-header-horizontal/layout.scss
  ui-v2/app/styles/components/main-header-horizontal/skin.scss
  ui-v2/app/styles/components/main-nav-horizontal.scss
  ui-v2/app/styles/components/product.scss
  ui-v2/app/styles/core/typography.scss
  ui-v2/app/styles/variables/index.scss
Labels: ui

#7370 ui: Updates Consul blueprints to be compatible with new ED version
  ui-v2/blueprints/adapter-test/index.js
  ui-v2/blueprints/adapter/index.js
  ui-v2/blueprints/model-test/index.js
  ui-v2/blueprints/model/index.js
  ui-v2/blueprints/repository-test/index.js
  ui-v2/blueprints/repository-test/qunit-files/__root__/__path__/integration/services/repository/__test__.js
  ui-v2/blueprints/repository-test/qunit-files/__root__/__path__/unit/services/repository/__test__.js
  ui-v2/blueprints/serializer-test/index.js
  ui-v2/blueprints/serializer/index.js
Labels: ui

#7372 ui: Delete the Promise rsvp imports from codebase
  ui-v2/app/components/child-selector.js
  ui-v2/app/components/feedback-dialog.js
  ui-v2/app/routes/application.js
  ui-v2/app/services/client/http.js
  ui-v2/app/services/repository/dc.js
  ui-v2/app/services/repository/kv.js
  ui-v2/app/services/repository/nspace/disabled.js
  ui-v2/app/services/repository/policy.js
  ui-v2/app/services/repository/role.js
  ui-v2/app/services/repository/token.js
  ui-v2/app/services/settings.js
  ui-v2/app/services/timeout.js
  ui-v2/app/utils/dom/event-source/blocking.js
  ui-v2/app/utils/dom/event-source/index.js
  ui-v2/app/utils/search/filterable.js
  ui-v2/tests/helpers/yadda-annotations.js
  ui-v2/tests/integration/utils/dom/event-source/callable-test.js
Labels: ui

#7375 ui: Remove settings.findHeaders now we can use promises in our adapters
  ui-v2/app/services/client/http.js
  ui-v2/app/services/settings.js
Labels: ui

#7383 ui: Install ref modifier and use it instead of dom selecting
  ui-v2/app/components/phrase-editor.js
  ui-v2/app/components/toggle-button.js
  ui-v2/app/templates/components/phrase-editor.hbs
  ui-v2/app/templates/components/toggle-button.hbs
  ui-v2/package.json
  ui-v2/yarn.lock
Labels: ui

#7377 ui: Alter position of logic for showing the Round Trip Time tab to prevent DOM refresh
  ui-v2/app/templates/dc/nodes/-rtt.hbs
  ui-v2/app/templates/dc/nodes/show.hbs
Labels: backport/1.7, bug, ui

#7378 ui: Coordinates don't require a nspace, so don't expect one in the repo
  ui-v2/app/services/repository/coordinate.js
  ui-v2/tests/integration/services/repository/coordinate-test.js
Labels: backport/1.7, bug, ui

#7376 docs: Add that `response_headers` also affects the UI
  website/source/docs/agent/options.html.md
Labels: docs

#7391 ui: Update the shadows for radio buttons and the cards
  ui-v2/app/styles/base/components/buttons/skin.scss
  ui-v2/app/styles/base/components/form-elements/skin.scss
  ui-v2/app/styles/base/components/stats-card/skin.scss
  ui-v2/app/styles/base/decoration/base-variables.scss
  ui-v2/app/styles/components/expanded-single-select/skin.scss
  ui-v2/app/styles/components/table.scss
Labels: ui

#7398 Fix session backwards incompatibility with 1.6.x and earlier.
  agent/consul/session_endpoint.go
  agent/consul/session_endpoint_test.go
  agent/session_endpoint.go
  agent/structs/structs.go
Labels: backport/1.7

#7404 ui: Enable recovery from an unreachable datacenter (500 error)
  ui-v2/app/helpers/href-mut.js
  ui-v2/app/routes/application.js
  ui-v2/app/services/repository/dc.js
  ui-v2/app/templates/error.hbs
  ui-v2/tests/acceptance/dc/error.feature
  ui-v2/tests/acceptance/steps/dc/error-steps.js
  ui-v2/tests/pages/dc/services/index.js
Labels: backport/1.7, bug, ui

#7394 Update envoy.html.md.erb
  website/source/docs/commands/connect/envoy.html.md.erb
Labels: docs

#7420 Update namespace docs for config entries
  website/source/api/config.html.md
  website/source/docs/agent/config-entries/proxy-defaults.html.md
  website/source/docs/agent/config-entries/service-defaults.html.md
Labels: docs

#7421 Update intention precedence table in the docs
  website/source/docs/connect/intentions.html.md
Labels: backport/1.7, docs

#7422 fix flaky TestCatalogListNodesCommand_verticalBar test
  command/catalog/list/nodes/catalog_list_nodes_test.go
Labels: theme/flaky-tests

#7431 Update MSP token and filtering
  agent/consul/acl_server.go
Labels: backport/1.7

#7442 ui: Add Ref component
  ui-v2/app/components/ref/index.js
  ui-v2/app/components/ref/index.mdx
  ui-v2/tests/integration/components/ref-test.js
Labels: ui

#7454 Fix typo in consul-template tutorial
  website/source/docs/guides/consul-template.html.md
Labels: docs, docs-cherrypick

#7435 Update namespace docs for some new CLI commands
  website/source/docs/commands/namespace.html.md.erb
  website/source/docs/commands/namespace/create.html.md.erb
  website/source/docs/commands/namespace/update.html.md.erb
  website/source/docs/commands/namespace/write.html.md.erb
  website/source/layouts/docs.erb
Labels: backport/1.7

#7451 Fix ACL mode advertisement and detection
  agent/consul/acl_server.go
  agent/consul/acl_server_oss.go
  agent/consul/enterprise_server_oss.go
  agent/consul/server_lookup.go
  agent/consul/server_serf.go
Labels: backport/1.7

#7455 Don’t pass `-u` to get get inside Go build image dockerfile
  build-support/docker/Build-Go.dockerfile
Labels: backport/1.7

#7456 update website version to 1.7.2
  website/config.rb
Labels: docs-cherrypick

#7459 ui: Move <Ref /> docs to README.mdx
  ui-v2/app/components/ref/README.mdx
Labels: ui

#7462 Log "vew version available" message at info level
  command/agent/agent.go
Labels: backport/1.7

#7444 agent/xds: Update mesh gateway to use service router timeout
  agent/xds/clusters.go
  agent/xds/clusters_test.go
  agent/xds/testdata/clusters/mesh-gateway-service-timeouts.golden
  website/source/docs/connect/proxies/envoy.md
Labels: backport/1.7

#7453 fix consul tls filenames in docs
  command/tls/cert/create/tls_cert_create.go
  command/tls/cert/tls_cert.go
  website/source/docs/commands/tls.html.md
  website/source/docs/commands/tls/cert.html.md.erb
  website/source/docs/guides/agent-encryption.html.md
Labels: docs, docs-cherrypick

#7458 website/docs: small doc improvements to CLI reference
  website/source/docs/commands/join.html.markdown.erb
  website/source/docs/commands/lock.html.markdown.erb
  website/source/docs/commands/operator/area.html.markdown.erb
Labels: docs, docs-cherrypick

#7460 ui: Adds blueprint for creating css-components
  ui-v2/blueprints/css-component/files/__root__/__path__/__name__.scss
  ui-v2/blueprints/css-component/files/__root__/__path__/__name__/index.scss
  ui-v2/blueprints/css-component/files/__root__/__path__/__name__/layout.scss
  ui-v2/blueprints/css-component/files/__root__/__path__/__name__/skin.scss
  ui-v2/blueprints/css-component/index.js
Labels: ui

#7448 ui: Add DataSource component
  ui-v2/app/components/data-source/README.mdx
  ui-v2/app/components/data-source/index.hbs
  ui-v2/app/components/data-source/index.js
  ui-v2/app/services/data-source/protocols/http.js
  ui-v2/app/services/data-source/protocols/http/blocking.js
  ui-v2/app/services/data-source/protocols/http/promise.js
  ui-v2/app/services/data-source/protocols/local-storage.js
  ui-v2/app/services/data-source/service.js
  ui-v2/app/services/repository.js
  ui-v2/app/services/settings.js
  ui-v2/app/utils/dom/event-source/index.js
  ui-v2/app/utils/dom/event-source/storage.js
  ui-v2/app/utils/maybe-call.js
  ui-v2/app/utils/storage/local-storage.js
  ui-v2/package.json
  ui-v2/tests/integration/components/data-source-test.js
  ui-v2/tests/steps.js
  ui-v2/tests/steps/assertions/dom.js
  ui-v2/tests/steps/assertions/model.js
  ui-v2/tests/unit/services/data-source/protocols/http-test.js
  ui-v2/tests/unit/services/data-source/protocols/local-storage-test.js
  ui-v2/tests/unit/utils/maybe-call-test.js
  ui-v2/yarn.lock
Labels: ui

#7472 ui: Adds `selectable-key-values` helper
  ui-v2/app/components/popover-select/index.hbs
  ui-v2/app/components/popover-select/index.js
  ui-v2/app/controllers/dc/nodes/index.js
  ui-v2/app/controllers/dc/services/index.js
  ui-v2/app/helpers/selectable-key-values.js
  ui-v2/app/templates/dc/nodes/index.hbs
  ui-v2/app/templates/dc/services/index.hbs
  ui-v2/tests/unit/helpers/selectable-key-values-test.js
Labels: ui

#7479 ui: Exposes the <ToggleButton /> 'click' action
  ui-v2/app/components/hashicorp-consul/index.hbs
  ui-v2/app/components/popover-menu/index.hbs
  ui-v2/app/components/toggle-button/README.mdx
  ui-v2/app/components/toggle-button/index.hbs
  ui-v2/app/components/toggle-button/index.js
Labels: ui

#7492 Add missing Helm docs
  website/source/docs/platform/k8s/helm.html.md
Labels: docs, docs-cherrypick

#7490 Fix flakey health check reload test
  agent/agent_test.go
Labels: theme/flaky-tests

#6615 Add PolicyReadByName for API
  agent/acl_endpoint.go
  agent/acl_endpoint_test.go
  agent/consul/acl_endpoint.go
  agent/consul/acl_endpoint_test.go
  agent/http_register.go
  agent/structs/acl.go
  api/acl.go
  api/acl_test.go
Labels: backport/1.7

#7498 envoy: small cleanup in cmd and server
  agent/agent.go
  command/connect/envoy/envoy.go
  command/connect/envoy/envoy_test.go
Labels: theme/internal-cleanup

#7515 Exposing paths isn't an upstream configuration
  website/source/docs/connect/registration/service-registration.html.md
Labels: backport/1.7, docs-cherrypick

#7516 agent: Remove unused method Encrypted from delegate interface
  agent/acl_test.go
  agent/agent.go
  agent/consul/client.go
  agent/consul/client_test.go
  agent/consul/server.go
  agent/consul/server_test.go
Labels: theme/internal-cleanup

#7495 updating enterprise documentation with additional clarity
  website/source/docs/enterprise/backups/index.html.md
  website/source/docs/enterprise/index.html.md
  website/source/docs/enterprise/namespaces/index.html.md
  website/source/docs/enterprise/network-segments/index.html.md
  website/source/docs/enterprise/read-scale/index.html.md
  website/source/docs/enterprise/redundancy/index.html.md
  website/source/docs/enterprise/upgrades/index.html.md
Labels: docs, docs-cherrypick

#7501 Add docs for v1/acl/policy/name endpoint
  website/source/api/acl/policies.html.md
Labels: backport/1.7, docs

#7491 Ensure server requirements checks are done against ALL known servers
  agent/consul/acl_server.go
  agent/consul/leader.go
  agent/consul/leader_connect.go
  agent/consul/util.go
  agent/consul/util_test.go
Labels: backport/1.7

#7543 ui: Ensure blocking query configuration is passed through to findInstanceBySlug
  ui-v2/app/services/repository/service.js
  ui-v2/tests/integration/services/repository/service-test.js
Labels: backport/1.7, ui

#7541 FIX flaky test: TestAPI_AgentMonitorJSON
  api/agent_test.go
Labels: backport/1.7

#7528 Updated Security Model and FAQ pages
  website/source/docs/faq.html.md
  website/source/docs/internals/security.html.md
Labels: docs, docs-cherrypick

#7550 ui: Use the `each key=""` parameter to force ember to reuse DOM
  ui-v2/app/templates/dc/nodes/show.hbs
  ui-v2/app/templates/dc/services/instance.hbs
  ui-v2/app/templates/dc/services/show.hbs
Labels: backport/1.7, ui

#7546 testing: Improve logging from TestAgent
  agent/agent.go
  agent/agent_test.go
  agent/local/state_test.go
  agent/testagent.go
  command/agent/agent.go
  command/connect/proxy/proxy.go
  go.mod
Labels: theme/internal-cleanup

#7556 ui: Add `<State /> and `{{state-matches}}` ember component/helper
  ui-v2/app/components/state/README.mdx
  ui-v2/app/components/state/index.hbs
  ui-v2/app/components/state/index.js
  ui-v2/app/helpers/state-matches.js
  ui-v2/app/services/state.js
  ui-v2/tests/integration/components/state-test.js
  ui-v2/tests/integration/helpers/state-matches-test.js
  ui-v2/tests/unit/services/state-test.js
Labels: ui

#7534 Add link to Learn from downloads page
  website/source/downloads.html.erb
  website/source/downloads_tools.html.erb
Labels: docs

#7470 dns: Remove a few unused function parameters
  agent/dns.go
Labels: theme/internal-cleanup
