Repository hashicorp/consul, pull requests merged in 2020-11, with the labels that each got.

#9078 ui: Use eslint vs ember-cli-lint, sass vs dart-sass
  ui/packages/consul-ui/ember-cli-build.js
  ui/packages/consul-ui/package.json
  ui/yarn.lock
Labels: backport/1.9, theme/ui

#9077 ui: Remove string casting when passing index/checked for dropmenus
  ui/packages/consul-ui/app/components/list-collection/index.js
  ui/packages/consul-ui/app/components/tabular-collection/index.hbs
  ui/packages/consul-ui/app/components/tabular-collection/index.js
Labels: backport/1.9, theme/ui

#9081 ui: Update to not return metrics for ingress gateways
  ui/packages/consul-ui/app/components/topology-metrics/card.hbs
  ui/packages/consul-ui/app/components/topology-metrics/index.hbs
  ui/packages/consul-ui/app/components/topology-metrics/index.js
  ui/packages/consul-ui/app/routes/dc/services/show/index.js
  ui/packages/consul-ui/app/templates/dc/services/show.hbs
Labels: theme/ui

#9090 docs/nia: add TF version config option
  website/pages/docs/nia/installation/configuration.mdx
  website/pages/docs/nia/installation/requirements.mdx
Labels: theme/consul-terraform-sync, type/docs

#9092 docs/nia: improve clarity on Consul TLS option
  website/pages/docs/nia/installation/configuration.mdx
Labels: theme/consul-terraform-sync, type/docs

#9049 ui: Storybook Install
  ui/packages/consul-ui/.storybook/main.js
  ui/packages/consul-ui/.storybook/preview.js
  ui/packages/consul-ui/app/components/notice/README.stories.mdx
  ui/packages/consul-ui/package.json
  ui/yarn.lock
Labels: theme/ui

#9094 ui: Metrics - Provide a fetch-like http client that automatically adds the current ACL token
  ui/packages/consul-ui/app/services/client/http.js
  ui/packages/consul-ui/app/services/repository/metrics.js
  ui/packages/consul-ui/vendor/metrics-providers/prometheus.js
Labels: backport/1.9, theme/ui

#9102 [Website] Bump HSM version
  website/package-lock.json
  website/package.json
Labels: type/docs, type/docs-cherrypick

#9109 ui: Fix up typo for the UI config template url
  ui/packages/consul-ui/app/routes/dc/services/show.js
  ui/packages/consul-ui/lib/startup/templates/head.html.js
Labels: theme/ui

#9061 stream: support filtering by namespace
  agent/cache-types/streaming_events_test.go
  agent/cache-types/streaming_health_services_test.go
  agent/consul/state/catalog_events.go
  agent/consul/state/catalog_events_test.go
  agent/consul/state/store_integration_test.go
  agent/consul/stream/event.go
  agent/consul/stream/event_publisher.go
  agent/consul/stream/event_publisher_test.go
  agent/consul/stream/event_snapshot.go
  agent/consul/stream/event_snapshot_test.go
  agent/consul/stream/subscription.go
  agent/consul/stream/subscription_test.go
  agent/rpc/subscribe/subscribe.go
  agent/rpc/subscribe/subscribe_test.go
  agent/structs/structs_oss.go
  proto/pbsubscribe/subscribe.pb.go
  proto/pbsubscribe/subscribe.proto
Labels: backport/1.9, theme/streaming

#9073 streaming: backport namespace changes
  agent/cache-types/streaming_health_services.go
  agent/cache-types/streaming_health_services_test.go
  agent/cache-types/streaming_test.go
  agent/consul/state/catalog_events.go
  agent/consul/state/catalog_events_test.go
  agent/consul/stream/event_publisher.go
  agent/consul/stream/subscription.go
  agent/consul/stream/subscription_test.go
  agent/consul/subscribe_backend.go
  agent/rpc/subscribe/logger.go
  agent/rpc/subscribe/subscribe.go
  agent/rpc/subscribe/subscribe_test.go
  agent/structs/structs.go
  agent/structs/structs_test.go
  proto/pbcommon/common_oss.go
  proto/pbservice/convert_oss.go
  proto/pbservice/convert_oss_test.go
  proto/pbservice/convert_test.go
Labels: backport/1.9, theme/streaming

#9104 agent: sanitize ui metrics proxy header values on agent/self endpoint
  agent/config/runtime.go
  agent/config/runtime_test.go
Labels: backport/1.9, theme/config

#9110 Fix NIA doc links
  website/pages/docs/nia/installation/run.mdx
  website/pages/docs/nia/network-drivers.mdx
Labels: theme/consul-terraform-sync, type/docs, type/docs-cherrypick

#9088 Add prometheus definitions for key metrics.
  go.mod
  go.sum
  lib/telemetry.go
  vendor/github.com/armon/go-metrics/prometheus/prometheus.go
  vendor/github.com/mattn/go-colorable/colorable_windows.go
  vendor/modules.txt
Labels: theme/internals

#9095 ui: Move AppError and ErrorState to glimmer components
  ui/packages/consul-ui/.storybook/main.js
  ui/packages/consul-ui/app/components/app-error/README.stories.mdx
  ui/packages/consul-ui/app/components/app-error/index.hbs
  ui/packages/consul-ui/app/components/app-error/index.js
  ui/packages/consul-ui/app/components/error-state/README.stories.mdx
  ui/packages/consul-ui/app/components/error-state/index.hbs
  ui/packages/consul-ui/app/helpers/href-to.js
  ui/packages/consul-ui/package.json
  ui/yarn.lock
Labels: backport/1.9, theme/ui

#9120 ui: Move gitignore file to workspace root and add storybook ignores
  ui/.gitignore
  ui/packages/consul-ui/.gitignore
Labels: backport/1.9, theme/ui

#9121 ui: Default to glimmer components
  ui/packages/consul-ui/.ember-cli
Labels: backport/1.9, theme/ui

#9108 ui: Intention "Action change" warning modal
  ui/packages/consul-ui/app/components/consul/intention/form/index.hbs
  ui/packages/consul-ui/app/components/consul/intention/form/index.js
  ui/packages/consul-ui/app/components/consul/intention/form/index.scss
  ui/packages/consul-ui/app/components/consul/intention/index.scss
  ui/packages/consul-ui/app/components/modal-dialog/index.hbs
  ui/packages/consul-ui/app/components/modal-dialog/index.js
  ui/packages/consul-ui/app/components/modal-dialog/index.scss
  ui/packages/consul-ui/app/components/modal-dialog/layout.scss
  ui/packages/consul-ui/app/components/modal-dialog/skin.scss
  ui/packages/consul-ui/app/serializers/intention.js
  ui/packages/consul-ui/app/styles/base/components/index.scss
  ui/packages/consul-ui/app/styles/base/components/modal-dialog/index.scss
  ui/packages/consul-ui/app/styles/base/components/modal-dialog/skin.scss
  ui/packages/consul-ui/app/styles/components.scss
  ui/packages/consul-ui/app/styles/components/auth-modal/layout.scss
  ui/packages/consul-ui/app/styles/components/form-elements.scss
  ui/packages/consul-ui/app/styles/components/modal-dialog.scss
  ui/packages/consul-ui/tests/acceptance/dc/intentions/permissions/warn.feature
  ui/packages/consul-ui/tests/acceptance/steps/dc/intentions/permissions/warn-steps.js
  ui/packages/consul-ui/tests/pages.js
  ui/packages/consul-ui/tests/pages/dc/intentions/edit.js
  ui/packages/consul-ui/tests/steps/assertions/page.js
Labels: backport/1.9, theme/ui

#9122 ui: Ensure per service intentions link to the correct place
  ui/packages/consul-ui/app/templates/dc/services/show/intentions/index.hbs
  ui/packages/consul-ui/tests/acceptance/dc/services/show/intentions.feature
Labels: backport/1.9, theme/ui

#9048 UI Metrics documentation
  website/data/docs-navigation.js
  website/pages/docs/agent/options.mdx
  website/pages/docs/connect/observability/index.mdx
  website/pages/docs/connect/observability/ui-visualization.mdx
  website/public/img/ui-dashboard-url-template.png
  website/public/img/ui-service-topology-view.png
Labels: type/docs, type/docs-cherrypick

#9129 changelog: add entries for 1.9.0-beta2
  .changelog/9002.txt
  .changelog/9008.txt
  .changelog/9059.txt
  .changelog/9081.txt
  .changelog/9088.txt
  .changelog/9099.txt
  CHANGELOG.md
Labels: backport/1.9

#9131 website: update callout to 1.9.0-beta2
  website/pages/downloads/index.jsx
Labels: type/docs, type/docs-cherrypick

#9132 changelog: add 1.9.0-beta2 release
  CHANGELOG.md
Labels: backport/1.9

#9115 ui: remove consul-api-double from yarn.lock
  ui/yarn.lock
Labels: backport/1.9, theme/ui

#9116 connect: Switch the default gateway port from 443 to 8443
  .changelog/9113.txt
  command/connect/envoy/flags.go
  command/connect/envoy/flags_test.go
  command/connect/envoy/testdata/ingress-gateway.golden
Labels: backport/1.9, theme/cli

#9126 ui: Move notice storybook to use controls addon
  ui/packages/consul-ui/app/components/notice/README.stories.mdx
Labels: backport/1.9, theme/ui

#9130 ci: Make backporting post-merge a bit easier
  .circleci/scripts/cherry-picker.sh
Labels: type/ci

#9136 ui: Move ember-data classes to use native JS classes/decorators
  ui/packages/consul-ui/app/adapters/acl.js
  ui/packages/consul-ui/app/adapters/application.js
  ui/packages/consul-ui/app/adapters/coordinate.js
  ui/packages/consul-ui/app/adapters/dc.js
  ui/packages/consul-ui/app/adapters/discovery-chain.js
  ui/packages/consul-ui/app/adapters/http.js
  ui/packages/consul-ui/app/adapters/intention.js
  ui/packages/consul-ui/app/adapters/kv.js
  ui/packages/consul-ui/app/adapters/node.js
  ui/packages/consul-ui/app/adapters/nspace.js
  ui/packages/consul-ui/app/adapters/oidc-provider.js
  ui/packages/consul-ui/app/adapters/policy.js
  ui/packages/consul-ui/app/adapters/proxy.js
  ui/packages/consul-ui/app/adapters/role.js
  ui/packages/consul-ui/app/adapters/service-instance.js
  ui/packages/consul-ui/app/adapters/service.js
  ui/packages/consul-ui/app/adapters/session.js
  ui/packages/consul-ui/app/adapters/token.js
  ui/packages/consul-ui/app/adapters/topology.js
  ui/packages/consul-ui/app/models/acl.js
  ui/packages/consul-ui/app/models/coordinate.js
  ui/packages/consul-ui/app/models/dc.js
  ui/packages/consul-ui/app/models/discovery-chain.js
  ui/packages/consul-ui/app/models/intention-permission-http-header.js
  ui/packages/consul-ui/app/models/intention-permission-http.js
  ui/packages/consul-ui/app/models/intention-permission.js
  ui/packages/consul-ui/app/models/intention.js
  ui/packages/consul-ui/app/models/kv.js
  ui/packages/consul-ui/app/models/node.js
  ui/packages/consul-ui/app/models/nspace.js
  ui/packages/consul-ui/app/models/oidc-provider.js
  ui/packages/consul-ui/app/models/policy.js
  ui/packages/consul-ui/app/models/proxy.js
  ui/packages/consul-ui/app/models/role.js
  ui/packages/consul-ui/app/models/service-instance.js
  ui/packages/consul-ui/app/models/service.js
  ui/packages/consul-ui/app/models/session.js
  ui/packages/consul-ui/app/models/token.js
  ui/packages/consul-ui/app/models/topology.js
  ui/packages/consul-ui/app/serializers/acl.js
  ui/packages/consul-ui/app/serializers/application.js
  ui/packages/consul-ui/app/serializers/coordinate.js
  ui/packages/consul-ui/app/serializers/dc.js
  ui/packages/consul-ui/app/serializers/discovery-chain.js
  ui/packages/consul-ui/app/serializers/http.js
  ui/packages/consul-ui/app/serializers/intention.js
  ui/packages/consul-ui/app/serializers/kv.js
  ui/packages/consul-ui/app/serializers/node.js
  ui/packages/consul-ui/app/serializers/nspace.js
  ui/packages/consul-ui/app/serializers/oidc-provider.js
  ui/packages/consul-ui/app/serializers/policy.js
  ui/packages/consul-ui/app/serializers/proxy.js
  ui/packages/consul-ui/app/serializers/role.js
  ui/packages/consul-ui/app/serializers/service-instance.js
  ui/packages/consul-ui/app/serializers/service.js
  ui/packages/consul-ui/app/serializers/session.js
  ui/packages/consul-ui/app/serializers/token.js
  ui/packages/consul-ui/app/serializers/topology.js
  ui/packages/consul-ui/app/services/store.js
Labels: backport/1.9, theme/ui

#9139 Add some autopilot docs and update the changelog
  .changelog/9103.txt
  website/pages/api-docs/operator/autopilot.mdx
Labels: backport/1.9, type/docs

#9119 chore: update to Go 1.14.11
  .circleci/config.yml
  build-support/docker/Build-Go.dockerfile
  build-support/docker/Test-Flake.dockerfile
Labels: backport/1.8, backport/1.9, type/ci

#9145 Fixup the autopilot changelog
  .changelog/9103.txt
Labels: backport/1.9

#9146 ui: Remove unnecessary reopens from sort and form services
  ui/packages/consul-ui/app/initializers/form.js
  ui/packages/consul-ui/app/initializers/sort.js
  ui/packages/consul-ui/app/services/form.js
  ui/packages/consul-ui/app/services/sort.js
Labels: backport/1.9, theme/ui

#9147 ui: Correct AdapterError import
  ui/packages/consul-ui/app/adapters/http.js
Labels: backport/1.9, theme/ui

#9141 ui: Delete proxy info tab
  ui/packages/consul-ui/app/components/consul/upstream-instance/list/index.hbs
  ui/packages/consul-ui/app/components/consul/upstream-instance/list/index.js
  ui/packages/consul-ui/app/components/consul/upstream-instance/list/index.scss
  ui/packages/consul-ui/app/router.js
  ui/packages/consul-ui/app/routes/dc/services/instance/exposedpaths.js
  ui/packages/consul-ui/app/routes/dc/services/instance/proxy.js
  ui/packages/consul-ui/app/routes/dc/services/instance/upstreams.js
  ui/packages/consul-ui/app/styles/components/composite-row.scss
  ui/packages/consul-ui/app/styles/layout.scss
  ui/packages/consul-ui/app/templates/dc/services/instance.hbs
  ui/packages/consul-ui/app/templates/dc/services/instance/exposedpaths.hbs
  ui/packages/consul-ui/app/templates/dc/services/instance/healthchecks.hbs
  ui/packages/consul-ui/app/templates/dc/services/instance/proxy.hbs
  ui/packages/consul-ui/app/templates/dc/services/instance/upstreams.hbs
  ui/packages/consul-ui/tests/acceptance/dc/services/instances/exposed-paths.feature
  ui/packages/consul-ui/tests/acceptance/dc/services/instances/proxyinfo.feature
  ui/packages/consul-ui/tests/acceptance/dc/services/instances/show.feature
  ui/packages/consul-ui/tests/acceptance/dc/services/instances/upstreams.feature
  ui/packages/consul-ui/tests/acceptance/steps/dc/services/instances/exposed-paths-steps.js
  ui/packages/consul-ui/tests/acceptance/steps/dc/services/instances/upstreams-steps.js
  ui/packages/consul-ui/tests/pages/dc/services/instance.js
Labels: theme/ui

#8976 Wrap rpc error object
  agent/pool/pool.go
Labels: backport/1.7, backport/1.8, backport/1.9

#9149 Use error wrapping to preserve error type info
  agent/pool/pool.go
Labels: backport/1.7, backport/1.8, backport/1.9

#9150 docs: add warning in 0.9.0 upgrade notes
  website/pages/docs/upgrading/upgrade-specific.mdx
Labels: type/docs, type/docs-cherrypick

#9153 ui: Inline Topology Intention Actions
  ui/packages/consul-ui/app/components/topology-metrics/down-lines/index.hbs
  ui/packages/consul-ui/app/components/topology-metrics/index.hbs
  ui/packages/consul-ui/app/components/topology-metrics/popover/index.hbs
  ui/packages/consul-ui/app/components/topology-metrics/up-lines/index.hbs
  ui/packages/consul-ui/app/components/topology-metrics/up-lines/index.js
  ui/packages/consul-ui/app/routes/dc/services/show.js
  ui/packages/consul-ui/app/serializers/topology.js
  ui/packages/consul-ui/app/templates/dc/services/show/topology.hbs
  ui/packages/consul-ui/package.json
  ui/yarn.lock
Labels: theme/ui

#9154 ui: Move DiscoveryChain component
  ui/packages/consul-ui/app/components/consul/discovery-chain/index.hbs
  ui/packages/consul-ui/app/components/consul/discovery-chain/index.js
  ui/packages/consul-ui/app/components/consul/discovery-chain/index.scss
  ui/packages/consul-ui/app/components/consul/discovery-chain/layout.scss
  ui/packages/consul-ui/app/components/consul/discovery-chain/resolver-card/index.hbs
  ui/packages/consul-ui/app/components/consul/discovery-chain/route-card/index.hbs
  ui/packages/consul-ui/app/components/consul/discovery-chain/route-card/index.js
  ui/packages/consul-ui/app/components/consul/discovery-chain/skin.scss
  ui/packages/consul-ui/app/components/consul/discovery-chain/splitter-card/index.hbs
  ui/packages/consul-ui/app/components/consul/discovery-chain/utils.js
  ui/packages/consul-ui/app/components/discovery-chain/index.hbs
  ui/packages/consul-ui/app/components/resolver-card/index.js
  ui/packages/consul-ui/app/components/splitter-card/index.hbs
  ui/packages/consul-ui/app/components/splitter-card/index.js
  ui/packages/consul-ui/app/styles/components.scss
  ui/packages/consul-ui/app/styles/components/discovery-chain/index.scss
  ui/packages/consul-ui/app/templates/dc/services/show/routing.hbs
  ui/packages/consul-ui/tests/integration/components/consul/discovery-chain-test.js
  ui/packages/consul-ui/tests/unit/components/consul/discovery-chain/get-alternate-services-test.js
  ui/packages/consul-ui/tests/unit/components/consul/discovery-chain/get-resolvers-test.js
  ui/packages/consul-ui/tests/unit/components/consul/discovery-chain/get-splitters-test.js
Labels: theme/ui

#9156 Add a paramter in state store methods to indicate whether a resource insertion is from a snapshot restoration
  .changelog/9156.txt
  .changelog/_666.txt
  agent/consul/state/catalog.go
  agent/consul/state/catalog_events_test.go
  agent/consul/state/catalog_oss.go
  agent/consul/state/kvs.go
  agent/consul/state/kvs_oss.go
  agent/consul/state/session.go
  agent/consul/state/session_oss.go
Labels: backport/1.7, backport/1.8, backport/1.9

#9157 ui: Add vendor directory as a target for JS linting and lint
  ui/packages/consul-ui/.eslintrc.js
  ui/packages/consul-ui/.template-lintrc.js
  ui/packages/consul-ui/app/components/consul/intention/list/index.js
  ui/packages/consul-ui/app/components/consul/intention/list/pageobject.js
  ui/packages/consul-ui/app/search/predicates/intention.js
  ui/packages/consul-ui/app/services/repository/intention.js
  ui/packages/consul-ui/ember-cli-build.js
  ui/packages/consul-ui/package.json
  ui/packages/consul-ui/testem.js
  ui/packages/consul-ui/tests/pages/dc/intentions/index.js
  ui/packages/consul-ui/tests/steps/assertions/model.js
  ui/packages/consul-ui/tests/steps/doubles/model.js
  ui/packages/consul-ui/tests/steps/interactions/click.js
  ui/packages/consul-ui/tests/unit/helpers/selectable-key-values-test.js
  ui/packages/consul-ui/vendor/metrics-providers/consul.js
  ui/packages/consul-ui/vendor/metrics-providers/prometheus.js
Labels: backport/1.9, theme/ui

#9098 Add detailed key size breakdown to snapshot inspect
  .changelog/9098.txt
  command/snapshot/inspect/formatter.go
  command/snapshot/inspect/formatter_test.go
  command/snapshot/inspect/snapshot_inspect.go
  command/snapshot/inspect/snapshot_inspect_test.go
  command/snapshot/inspect/testdata/TestSnapshotInspectCommand.golden
  command/snapshot/inspect/testdata/TestSnapshotInspectEnhanceCommand.golden
  command/snapshot/inspect/testdata/TestSnapshotInspectKVDetailsCommand.golden
  command/snapshot/inspect/testdata/TestSnapshotInspectKVDetailsDepthCommand.golden
  command/snapshot/inspect/testdata/TestSnapshotInspectKVDetailsDepthFilterCommand.golden
  command/snapshot/inspect/testdata/backupWithKV.snap
  command/snapshot/inspect/testdata/json.golden
  command/snapshot/inspect/testdata/pretty.golden
  website/pages/commands/snapshot/inspect.mdx
Labels: theme/cli, type/enhancement

#9142 Add a CLI command for retrieving the autopilot configuration.
  agent/operator_endpoint_oss.go
  agent/operator_endpoint_test.go
  api/operator_autopilot.go
  command/commands_oss.go
  command/operator/autopilot/state/formatter.go
  command/operator/autopilot/state/operator_autopilot_state.go
  command/operator/autopilot/state/operator_autopilot_state_test.go
  command/operator/autopilot/state/testdata/enterprise/json.golden
  command/operator/autopilot/state/testdata/enterprise/pretty.golden
  command/operator/autopilot/state/testdata/enterprise/state.json
  command/operator/autopilot/state/testdata/oss/json.golden
  command/operator/autopilot/state/testdata/oss/pretty.golden
  command/operator/autopilot/state/testdata/oss/state.json
  website/pages/commands/operator/autopilot.mdx
Labels: backport/1.9, theme/cli, type/docs

#9159 ci: remove nonexistant autopilot directory from go-test-race
  .circleci/config.yml
Labels: backport/1.9, type/ci

#9158 ci: publish bindata_assetfs.go for all release/.x branches
  .circleci/config.yml
Labels: backport/1.7, backport/1.8, backport/1.9, type/ci

#9161 Add changelog entry for autopilot state CLI
  .changelog/9142.txt
Labels: backport/1.9

#9167 chore(backport): use HashiCorp Docker mirror
  .circleci/config.yml
  test/integration/connect/envoy/Dockerfile-bats
  test/integration/connect/envoy/Dockerfile-consul-envoy
  test/integration/connect/envoy/Dockerfile-tcpdump
  test/integration/connect/envoy/docker-compose.yml
  test/integration/connect/envoy/helpers.bash
  test/integration/connect/envoy/run-tests.sh
  website/Dockerfile
Labels: theme/testing, type/ci

#9137 ui: Topology Intentions Popovers
  ui/packages/consul-ui/app/components/topology-metrics/card.hbs
  ui/packages/consul-ui/app/components/topology-metrics/down-lines/index.hbs
  ui/packages/consul-ui/app/components/topology-metrics/icon.hbs
  ui/packages/consul-ui/app/components/topology-metrics/index.hbs
  ui/packages/consul-ui/app/components/topology-metrics/index.js
  ui/packages/consul-ui/app/components/topology-metrics/layout.scss
  ui/packages/consul-ui/app/components/topology-metrics/popover/index.hbs
  ui/packages/consul-ui/app/components/topology-metrics/popover/index.js
  ui/packages/consul-ui/app/components/topology-metrics/popover/index.scss
  ui/packages/consul-ui/app/components/topology-metrics/series/layout.scss
  ui/packages/consul-ui/app/components/topology-metrics/skin.scss
  ui/packages/consul-ui/app/components/topology-metrics/stats/index.scss
  ui/packages/consul-ui/app/components/topology-metrics/up-lines/index.hbs
  ui/packages/consul-ui/app/components/topology-metrics/up-lines/index.js
  ui/packages/consul-ui/app/routes/dc/services/show.js
  ui/packages/consul-ui/app/serializers/topology.js
  ui/packages/consul-ui/app/styles/components.scss
  ui/packages/consul-ui/app/templates/dc/services/show/topology.hbs
  ui/packages/consul-ui/package.json
  ui/packages/consul-ui/tests/integration/serializers/topology-test.js
  ui/yarn.lock
Labels: theme/ui

#9101 agent: return the default ACL policy to callers as a header
  .changelog/9101.txt
  agent/config/runtime.go
  agent/consul/config.go
  agent/http.go
  agent/http_test.go
  api/api.go
  api/api_test.go
  website/pages/api-docs/index.mdx
Labels: theme/api

#9172 ui: Upstream Instance Search and Sort
  ui/packages/consul-ui/app/components/consul/upstream-instance/list/index.hbs
  ui/packages/consul-ui/app/components/consul/upstream-instance/list/index.js
  ui/packages/consul-ui/app/components/consul/upstream-instance/list/index.scss
  ui/packages/consul-ui/app/components/consul/upstream-instance/list/pageobject.js
  ui/packages/consul-ui/app/components/consul/upstream-instance/search-bar/index.hbs
  ui/packages/consul-ui/app/controllers/dc/services/instance/upstreams.js
  ui/packages/consul-ui/app/routes/dc/services/instance/upstreams.js
  ui/packages/consul-ui/app/search/predicates/upstream-instance.js
  ui/packages/consul-ui/app/services/search.js
  ui/packages/consul-ui/app/services/sort.js
  ui/packages/consul-ui/app/sort/comparators/upstream-instance.js
  ui/packages/consul-ui/app/styles/components.scss
  ui/packages/consul-ui/app/styles/components/composite-row.scss
  ui/packages/consul-ui/app/templates/dc/services/instance/upstreams.hbs
  ui/packages/consul-ui/tests/pages.js
  ui/packages/consul-ui/tests/pages/dc/services/instance.js
Labels: backport/1.9, theme/ui

#9162 grpc: fix metrics
  agent/grpc/client.go
  agent/grpc/handler.go
  agent/grpc/stats.go
  agent/grpc/stats_test.go
Labels: backport/1.9, theme/streaming

#9179 Update Helm compatibility matrix
  website/pages/docs/k8s/upgrade/compatibility.mdx
Labels: type/docs, type/docs-cherrypick

#8819 Docs: for consul-k8s health checks
  website/data/docs-navigation.js
  website/pages/docs/k8s/connect/health.mdx
  website/pages/docs/k8s/helm.mdx
Labels: post-beta, type/docs, type/docs-cherrypick

#9177 docs: add link to the OpenShift platform guide to k8s docs
  website/data/docs-navigation.js
Labels: type/docs, type/docs-cherrypick

#9007 server: break up Intention.Apply monolithic method
  .changelog/9007.txt
  agent/consul/intention_endpoint.go
  agent/structs/config_entry_intentions.go
Labels: backport/1.9

#9184 ui: Update to not return metrics for ingress gateways (#9081)
  ui/packages/consul-ui/app/components/topology-metrics/card.hbs
  ui/packages/consul-ui/app/components/topology-metrics/index.hbs
  ui/packages/consul-ui/app/components/topology-metrics/index.js
  ui/packages/consul-ui/app/routes/dc/services/show/index.js
  ui/packages/consul-ui/app/templates/dc/services/show.hbs
Labels: theme/ui

#9175 ui: Pass down nspace and dc from Service model down to prometheus request
  ui/packages/consul-ui/app/components/topology-metrics/card.hbs
  ui/packages/consul-ui/app/components/topology-metrics/index.hbs
  ui/packages/consul-ui/app/components/topology-metrics/series/index.hbs
  ui/packages/consul-ui/app/components/topology-metrics/stats/index.hbs
  ui/packages/consul-ui/app/templates/dc/services/show/topology.hbs
Labels: backport/1.9, theme/ui

#9183 ui: Search/sort improvements
  ui/packages/consul-ui/app/components/consul/intention/search-bar/index.hbs
  ui/packages/consul-ui/app/components/consul/nspace/list/index.hbs
  ui/packages/consul-ui/app/components/consul/policy/search-bar/index.hbs
  ui/packages/consul-ui/app/components/consul/service/search-bar/index.hbs
  ui/packages/consul-ui/app/components/consul/token/search-bar/index.hbs
  ui/packages/consul-ui/app/controllers/dc/acls/policies/index.js
  ui/packages/consul-ui/app/controllers/dc/acls/tokens/index.js
  ui/packages/consul-ui/app/controllers/dc/kv/index.js
  ui/packages/consul-ui/app/controllers/dc/services/index.js
  ui/packages/consul-ui/app/controllers/dc/services/show/intentions/index.js
  ui/packages/consul-ui/app/filter/predicates/intention.js
  ui/packages/consul-ui/app/filter/predicates/node.js
  ui/packages/consul-ui/app/filter/predicates/policy.js
  ui/packages/consul-ui/app/filter/predicates/service-instance.js
  ui/packages/consul-ui/app/filter/predicates/service.js
  ui/packages/consul-ui/app/filter/predicates/token.js
  ui/packages/consul-ui/app/routes/dc/acls/policies/index.js
  ui/packages/consul-ui/app/routes/dc/acls/roles/index.js
  ui/packages/consul-ui/app/routes/dc/acls/tokens/index.js
  ui/packages/consul-ui/app/routes/dc/intentions/index.js
  ui/packages/consul-ui/app/routes/dc/kv/index.js
  ui/packages/consul-ui/app/routes/dc/nodes/index.js
  ui/packages/consul-ui/app/routes/dc/nspaces/index.js
  ui/packages/consul-ui/app/routes/dc/services/index.js
  ui/packages/consul-ui/app/routes/dc/services/show/instances.js
  ui/packages/consul-ui/app/routes/dc/services/show/intentions/index.js
  ui/packages/consul-ui/app/templates/dc/acls/policies/index.hbs
  ui/packages/consul-ui/app/templates/dc/acls/tokens/index.hbs
  ui/packages/consul-ui/app/templates/dc/nspaces/index.hbs
  ui/packages/consul-ui/app/templates/dc/services/index.hbs
  ui/packages/consul-ui/app/utils/filter/index.js
  ui/packages/consul-ui/tests/unit/filter/predicates/service-test.js
Labels: backport/1.9, theme/ui

#9186 server: skip deleted and deleting namespaces when migrating intentions to config entries
  .changelog/9186.txt
  agent/consul/leader_intentions.go
  agent/consul/leader_intentions_oss.go
  agent/consul/leader_intentions_oss_test.go
  agent/consul/leader_intentions_test.go
  agent/consul/leader_routine_manager.go
  agent/consul/leader_routine_manager_test.go
Labels: backport/1.9

#9151 server: remove config entry CAS in legacy intention API bridge code
  .changelog/9151.txt
  agent/consul/config_endpoint.go
  agent/consul/fsm/commands_oss.go
  agent/consul/intention_endpoint.go
  agent/consul/server_register.go
  agent/consul/state/config_entry.go
  agent/consul/state/intention.go
  agent/consul/state/intention_test.go
  agent/structs/config_entry_intentions.go
  agent/structs/config_entry_intentions_test.go
  agent/structs/intention.go
Labels: backport/1.9

#9187 ci: update to go 1.15.5
  .circleci/config.yml
  build-support/docker/Build-Go.dockerfile
  build-support/docker/Test-Flake.dockerfile
Labels: backport/1.9, type/ci

#9165 changelog: merge release/1.9.0-beta3
  .changelog/9119.txt
  CHANGELOG.md
  website/pages/downloads/index.jsx
Labels: type/docs

#9168 chore(backport): use HashiCorp Docker mirror (#9167)
  .circleci/config.yml
  test/integration/connect/envoy/Dockerfile-bats
  test/integration/connect/envoy/Dockerfile-consul-envoy
  test/integration/connect/envoy/Dockerfile-tcpdump
  test/integration/connect/envoy/docker-compose.yml
  test/integration/connect/envoy/helpers.bash
  test/integration/connect/envoy/run-tests.sh
Labels: type/ci

#9193 Remove this constant as it is soon to be changing and we want to prevent backwards compat issues
  api/agent.go
Labels: backport/1.9, theme/api

#9194 server: intentions CRUD requires connect to be enabled
  agent/consul/config_endpoint.go
  agent/consul/intention_endpoint.go
  agent/consul/leader.go
  agent/consul/leader_test.go
Labels: backport/1.9

#9106 Revamp Security Model Documentation
  website/data/docs-navigation.js
  website/pages/docs/security/index.mdx
  website/pages/docs/security/security-models/core.mdx
  website/pages/docs/security/security-models/index.mdx
  website/pages/docs/security/security-models/nia.mdx
Labels: type/docs

#9195 add note about future metric fixes and deprecations under disable_com…
  .changelog/9181.txt
Labels: backport/1.9

#9176 Docs for upgrading to CRDs
  website/data/docs-navigation.js
  website/pages/docs/k8s/crds/index.mdx
  website/pages/docs/k8s/crds/upgrade-to-crds.mdx
  website/pages/docs/k8s/upgrade/index.mdx
Labels: type/docs, type/docs-cherrypick

#9200 ui: Replace NaN and undefined metrics values with `-`
  ui/packages/consul-ui/mock-api/v1/internal/ui/metrics-proxy/api/v1/query
  ui/packages/consul-ui/mock-api/v1/internal/ui/metrics-proxy/api/v1/query_range
  ui/packages/consul-ui/mock-api/v1/internal/ui/service-topology/_
  ui/packages/consul-ui/vendor/metrics-providers/prometheus.js
Labels: backport/1.9, theme/ui

#9114 stream: improve naming of Payload methods
  agent/consul/state/catalog_events.go
  agent/consul/state/catalog_events_test.go
  agent/consul/state/store_integration_test.go
  agent/consul/stream/event.go
  agent/consul/stream/event_publisher.go
  agent/consul/stream/event_publisher_test.go
  agent/consul/stream/event_test.go
  agent/consul/stream/subscription.go
  agent/consul/stream/subscription_test.go
  agent/rpc/subscribe/auth.go
  agent/rpc/subscribe/logger.go
  agent/rpc/subscribe/subscribe.go
  agent/rpc/subscribe/subscribe_test.go
Labels: backport/1.9, theme/streaming

#9166 ci(backport-1.8): publish static assets
  .circleci/config.yml
  ui-v2/config/environment.js
Labels: type/ci

#9203 Add changelog entry for namespace licensing fix
  .changelog/_683.txt
Labels: backport/1.7, backport/1.8, backport/1.9

#9204 Prevent panic if autopilot health is requested prior to leader establishment finishing.
  .changelog/9204.txt
  agent/consul/operator_autopilot_endpoint.go
Labels: backport/1.9

#9198 Add metric definitions for all metrics known at Consul start
  .changelog/9198.txt
  agent/agent_endpoint.go
  agent/cache/cache.go
  agent/catalog_endpoint.go
  agent/config/builder.go
  agent/config/runtime_test.go
  agent/consul/acl.go
  agent/consul/acl_endpoint.go
  agent/consul/acl_endpoint_legacy.go
  agent/consul/autopilot.go
  agent/consul/catalog_endpoint.go
  agent/consul/client.go
  agent/consul/config_endpoint.go
  agent/consul/federation_state_endpoint.go
  agent/consul/fsm/commands_oss.go
  agent/consul/fsm/snapshot.go
  agent/consul/intention_endpoint.go
  agent/consul/kvs_endpoint.go
  agent/consul/leader.go
  agent/consul/prepared_query_endpoint.go
  agent/consul/rpc.go
  agent/consul/segment_oss.go
  agent/consul/server.go
  agent/consul/session_endpoint.go
  agent/consul/session_ttl.go
  agent/consul/txn_endpoint.go
  agent/consul/usagemetrics/usagemetrics.go
  agent/dns.go
  agent/grpc/stats.go
  agent/http.go
  agent/local/state.go
  agent/setup.go
  connect/proxy/proxy.go
  lib/telemetry.go
  lib/telemetry_test.go
Labels: theme/telemetry, type/bug, type/enhancement

#8675 [docs] Change links to the DNS information to the right place
  contributing/INTERNALS.md
  website/pages/api-docs/query.mdx
  website/pages/docs/agent/config-entries/ingress-gateway.mdx
  website/pages/docs/agent/options.mdx
  website/pages/docs/connect/gateways/ingress-gateway.mdx
  website/pages/docs/connect/native/index.mdx
  website/pages/docs/connect/proxies/index.mdx
  website/pages/docs/connect/proxies/managed-deprecated.mdx
  website/pages/docs/discovery/services.mdx
  website/pages/docs/k8s/dns.mdx
  website/pages/docs/k8s/service-sync.mdx
  website/pages/intro/getting-started/agent.mdx
Labels: backport/1.9, type/docs, type/docs-cherrypick

#9209 ui: 1.9GA Changelog changes
  .changelog/9141.txt
Labels: backport/1.9

#9191 Refactor to call non-voting servers read replicas
  .changelog/9191.txt
  agent/agent.go
  agent/config/builder.go
  agent/config/builder_oss.go
  agent/config/builder_oss_test.go
  agent/config/config.go
  agent/config/flags.go
  agent/config/runtime.go
  agent/config/runtime_oss_test.go
  agent/config/runtime_test.go
  agent/consul/config.go
  agent/consul/leader.go
  agent/consul/leader_test.go
  agent/consul/server_serf.go
  agent/consul/server_test.go
  agent/metadata/server.go
  agent/metadata/server_test.go
  agent/structs/structs_filtering_test.go
  api/agent.go
  website/pages/docs/agent/options.mdx
  website/pages/docs/enterprise/read-scale.mdx
Labels: backport/1.9, theme/api, theme/config, type/docs

#9160 ci: change go-test-race package list to exclude list
  .circleci/config.yml
  acl/authorizer_test.go
  acl/chained_authorizer_test.go
  acl/policy_authorizer_test.go
  acl/static_authorizer_test.go
  agent/auto-config/auto_config_test.go
  connect/proxy/config_test.go
  connect/proxy/proxy_test.go
  connect/service_test.go
  connect/testing.go
  connect/tls.go
Labels: backport/1.9, theme/connect, type/ci

#9210 ui: Add triple curlies and reformat style attribute
  ui/packages/consul-ui/app/components/tab-nav/index.hbs
Labels: backport/1.9, theme/ui

#9211 ui: Change title helper to page-title
  ui/packages/consul-ui/app/templates/application.hbs
  ui/packages/consul-ui/app/templates/dc/acls/policies/edit.hbs
  ui/packages/consul-ui/app/templates/dc/acls/policies/index.hbs
  ui/packages/consul-ui/app/templates/dc/acls/roles/edit.hbs
  ui/packages/consul-ui/app/templates/dc/acls/roles/index.hbs
  ui/packages/consul-ui/app/templates/dc/acls/tokens/edit.hbs
  ui/packages/consul-ui/app/templates/dc/acls/tokens/index.hbs
  ui/packages/consul-ui/app/templates/dc/intentions/edit.hbs
  ui/packages/consul-ui/app/templates/dc/intentions/index.hbs
  ui/packages/consul-ui/app/templates/dc/kv/edit.hbs
  ui/packages/consul-ui/app/templates/dc/kv/index.hbs
  ui/packages/consul-ui/app/templates/dc/nodes/index.hbs
  ui/packages/consul-ui/app/templates/dc/nodes/show.hbs
  ui/packages/consul-ui/app/templates/dc/nspaces/edit.hbs
  ui/packages/consul-ui/app/templates/dc/nspaces/index.hbs
  ui/packages/consul-ui/app/templates/dc/services/index.hbs
  ui/packages/consul-ui/app/templates/dc/services/instance.hbs
  ui/packages/consul-ui/app/templates/dc/services/show.hbs
  ui/packages/consul-ui/app/templates/settings.hbs
Labels: backport/1.9, theme/ui

#9218 ui: Remove ember-computed-style to avoid deprecation error
  ui/packages/consul-ui/app/components/list-collection/index.hbs
  ui/packages/consul-ui/app/components/list-collection/index.js
  ui/packages/consul-ui/app/components/tabular-collection/index.hbs
  ui/packages/consul-ui/app/components/tabular-collection/index.js
  ui/packages/consul-ui/package.json
  ui/yarn.lock
Labels: backport/1.9, theme/ui

#9219 ui: Refactor tomography graph component to glimmer and remove deprecation
  ui/packages/consul-ui/app/components/consul/tomography/graph/index.hbs
  ui/packages/consul-ui/app/components/consul/tomography/graph/index.js
  ui/packages/consul-ui/app/components/consul/tomography/graph/index.scss
  ui/packages/consul-ui/app/services/repository/coordinate.js
  ui/packages/consul-ui/app/styles/components.scss
  ui/packages/consul-ui/app/styles/components/tomography-graph.scss
  ui/packages/consul-ui/app/templates/dc/nodes/show/rtt.hbs
Labels: backport/1.9, theme/ui

#9222 ui: Fix mutated nspace argument
  ui/packages/consul-ui/app/components/topology-metrics/stats/index.js
Labels: backport/1.9, theme/ui

#9221 ui: Fix empty state conditional for Series Graph
  ui/packages/consul-ui/app/components/topology-metrics/series/index.hbs
  ui/packages/consul-ui/app/components/topology-metrics/series/index.js
Labels: backport/1.9, theme/ui

#9224 agent: fix bug with multiple listeners
  agent/agent.go
  agent/agent_test.go
  agent/apiserver.go
Labels: backport/1.9, type/bug

#9206 Add docs for envoyExtraArgs
  website/pages/docs/k8s/connect/index.mdx
  website/pages/docs/k8s/helm.mdx
Labels: type/docs

#9091 Correcting text on when default was changed in Consul
  website/pages/docs/upgrading/upgrade-specific.mdx
Labels: type/docs, type/docs-cherrypick

#9220 ui: Remove ghost healthcheck from the service instance healthcheck list
  ui/packages/consul-ui/app/templates/dc/services/instance/healthchecks.hbs
  ui/packages/consul-ui/tests/acceptance/dc/services/instances/show.feature
Labels: backport/1.9, theme/ui

#9223 ui: All metrics cards should default to the default nspace if not set
  ui/packages/consul-ui/app/components/topology-metrics/card.hbs
  ui/packages/consul-ui/app/components/topology-metrics/index.hbs
Labels: backport/1.9, theme/ui

#9234 ui: Sort lists with health by unhealthy/healthy by default
  ui/packages/consul-ui/app/templates/dc/nodes/index.hbs
  ui/packages/consul-ui/app/templates/dc/services/index.hbs
  ui/packages/consul-ui/app/templates/dc/services/show/instances.hbs
  ui/packages/consul-ui/app/templates/dc/services/show/upstreams.hbs
  ui/packages/consul-ui/tests/acceptance/dc/nodes/empty-ids.feature
  ui/packages/consul-ui/tests/acceptance/dc/nodes/index.feature
  ui/packages/consul-ui/tests/acceptance/dc/services/index.feature
  ui/packages/consul-ui/tests/acceptance/dc/services/navigation.feature
  ui/packages/consul-ui/tests/acceptance/dc/services/show.feature
  ui/packages/consul-ui/tests/acceptance/page-navigation.feature
  ui/packages/consul-ui/tests/acceptance/steps/dc/services/navigation-steps.js
Labels: backport/1.9, theme/ui

#9236 ui: ACL Tokens > Roles and Policy search and sort
  ui/packages/consul-ui/app/components/child-selector/index.hbs
  ui/packages/consul-ui/app/components/child-selector/index.js
  ui/packages/consul-ui/app/services/sort.js
  ui/packages/consul-ui/app/sort/comparators/policy.js
  ui/packages/consul-ui/app/sort/comparators/role.js
  ui/packages/consul-ui/app/sort/comparators/upstream-instance.js
  ui/packages/consul-ui/tests/acceptance/dc/acls/policies/as-many/add-existing.feature
  ui/packages/consul-ui/tests/acceptance/dc/acls/roles/as-many/add-existing.feature
Labels: backport/1.9, theme/ui

#9237 ui: Surface 'detail' of API errors in the error page
  ui/packages/consul-ui/app/components/empty-state/index.hbs
  ui/packages/consul-ui/app/components/error-state/index.hbs
  ui/packages/consul-ui/app/routes/application.js
  ui/packages/consul-ui/app/services/repository/dc.js
Labels: backport/1.9, theme/ui

#9238 ui: Alter background color of filter bars
  ui/packages/consul-ui/app/styles/components/filter-bar/skin.scss
Labels: backport/1.9, theme/ui

#9240 Require operator:write to get Connect CA config
  .changelog/9240.txt
  agent/consul/connect_ca_endpoint.go
  agent/consul/connect_ca_endpoint_test.go
  website/pages/api-docs/connect/ca.mdx
Labels: backport/1.6, backport/1.7, backport/1.8, backport/1.9, type/docs

#9228 ui: Card component nspace refactor
  ui/packages/consul-ui/app/components/topology-metrics/card.hbs
  ui/packages/consul-ui/app/components/topology-metrics/stats/index.scss
Labels: backport/1.9, theme/ui

#9229 command: when generating envoy bootstrap configs use the datacenter returned from the agent services endpoint
  .changelog/9229.txt
  agent/agent_endpoint.go
  agent/agent_endpoint_test.go
  api/agent.go
  api/agent_test.go
  command/connect/envoy/envoy.go
  command/connect/envoy/envoy_test.go
  website/pages/api-docs/agent/service.mdx
Labels: backport/1.9, theme/api, theme/cli

#9230 [1.9.0] command: when generating envoy bootstrap configs use the datacenter returned from the agent services endpoint
  .changelog/9229.txt
  agent/agent_endpoint.go
  agent/agent_endpoint_test.go
  api/agent.go
  api/agent_test.go
  command/connect/envoy/envoy.go
  command/connect/envoy/envoy_test.go
  website/pages/api-docs/agent/service.mdx
Labels: theme/api, theme/cli

#9246 Add latest changelog entries and update website version
  CHANGELOG.md
  website/data/version.js
Labels: backport/1.9, type/docs-cherrypick

#9248 ui: Card component nspace refactor (#9228)
  ui/packages/consul-ui/app/components/topology-metrics/card.hbs
  ui/packages/consul-ui/app/components/topology-metrics/stats/index.scss
Labels: theme/ui

#9245 Telemetry/fix missing and stale docs
  agent/catalog_endpoint.go
  agent/consul/acl.go
  website/pages/docs/agent/telemetry.mdx
Labels: theme/telemetry, type/docs, type/docs-cherrypick

#9180 Docs: Update NIA architecture image
  website/pages/docs/integrate/nia-integration.mdx
  website/pages/docs/nia/architecture.mdx
  website/public/img/nia-highlevel-diagram.png
  website/public/img/nia-highlevel-diagram.svg
Labels: theme/consul-terraform-sync, type/docs, type/docs-cherrypick

#9012 logging: prune logs on startup
  logging/logfile.go
  logging/logfile_test.go
  logging/logger.go
Labels: backport/1.9, theme/telemetry

#9259 docs: mark streaming as experimental
  website/pages/docs/agent/options.mdx
Labels: backport/1.9, type/docs, type/docs-cherrypick

#9261 Telemetry/fix missing and stale docs
  agent/cache/cache.go
  agent/consul/catalog_endpoint.go
  agent/consul/fsm/commands_oss.go
  agent/consul/session_ttl.go
  website/pages/docs/agent/telemetry.mdx
Labels: theme/agent-cache, type/docs

#9257 ui: Include nspace in up/downstream link when nspaces are enabled
  ui/packages/consul-ui/app/components/topology-metrics/card.hbs
Labels: backport/1.9, theme/ui

#9269 ui: Ensure the per item logout button logs you out
  ui/packages/consul-ui/app/components/consul/token/list/index.hbs
Labels: backport/1.9, theme/ui

#9254 server: fix panic when deleting a non existent intention
  .changelog/9254.txt
  agent/consul/intention_endpoint.go
  agent/consul/intention_endpoint_test.go
  agent/intentions_endpoint_test.go
Labels: backport/1.9

#9263 docs: adding Consul 1.9.x to compat matrix and link to Envoy compat matrix
  website/pages/docs/k8s/upgrade/compatibility.mdx
Labels: type/docs, type/docs-cherrypick

#9272 Consul 1.9 GA Banner
  website/data/alert-banner.js
Labels: type/docs, type/docs-cherrypick

#9247 [Streaming] Predictable order for results of /health/service/:serviceName to mimic memdb
  .changelog/9247.txt
  agent/cache-types/streaming_health_services.go
  agent/cache-types/streaming_health_services_test.go
Labels: backport/1.9, theme/streaming

#9279 Bump supported chart to 0.27.0 for Consul 1.9
  website/pages/docs/k8s/upgrade/compatibility.mdx
Labels: type/docs, type/docs-cherrypick

#9281 ui: Change metrics link documentation link
  ui/packages/consul-ui/app/components/topology-metrics/index.hbs
Labels: backport/1.9, theme/ui

#9289 fix serf_wan documentation
  agent/config/runtime.go
  website/pages/docs/agent/options.mdx
Labels: theme/config, type/docs, type/docs-cherrypick

#9284 local: mark service as InSync when added to local agent state
  .changelog/9284.txt
  agent/ae/ae.go
  agent/local/state.go
  agent/local/state_test.go
Labels: backport/1.7, backport/1.8, backport/1.9, type/bug

#9275 ui: Nestable DataSources (plus glimmer upgrade)
  ui/packages/consul-ui/app/components/data-source/README.mdx
  ui/packages/consul-ui/app/components/data-source/index.hbs
  ui/packages/consul-ui/app/components/data-source/index.js
  ui/packages/consul-ui/app/services/data-source/service.js
  ui/packages/consul-ui/tests/integration/components/data-source-test.js
Labels: backport/1.9, theme/ui

#9295 Fix typo in explanation of connect command
  website/pages/commands/connect/index.mdx
Labels: type/docs, type/docs-cherrypick

#9297 docs: fix mispelling in connect upstream docs
  website/pages/docs/connect/registration/service-registration.mdx
Labels: type/docs

#9288 ui: Modifier based tooltips
  ui/packages/consul-ui/app/components/consul/discovery-chain/index.hbs
  ui/packages/consul-ui/app/components/consul/discovery-chain/index.js
  ui/packages/consul-ui/app/components/consul/discovery-chain/layout.scss
  ui/packages/consul-ui/app/components/consul/discovery-chain/resolver-card/index.hbs
  ui/packages/consul-ui/app/components/consul/discovery-chain/route-card/index.hbs
  ui/packages/consul-ui/app/components/consul/discovery-chain/skin.scss
  ui/packages/consul-ui/app/components/copy-button/index.hbs
  ui/packages/consul-ui/app/components/copy-button/index.js
  ui/packages/consul-ui/app/components/healthcheck-list/index.hbs
  ui/packages/consul-ui/app/components/tooltip/index.hbs
  ui/packages/consul-ui/app/components/tooltip/index.js
  ui/packages/consul-ui/app/components/tooltip/index.scss
  ui/packages/consul-ui/app/components/topology-metrics/stats/index.hbs
  ui/packages/consul-ui/app/helpers/dom-position.js
  ui/packages/consul-ui/app/modifiers/tooltip.js
  ui/packages/consul-ui/app/styles/base/components/index.scss
  ui/packages/consul-ui/app/styles/base/components/tooltip/index.scss
  ui/packages/consul-ui/app/styles/base/components/tooltip/layout.scss
  ui/packages/consul-ui/app/styles/base/components/tooltip/skin.scss
  ui/packages/consul-ui/app/styles/components.scss
  ui/packages/consul-ui/app/styles/components/app-view.scss
  ui/packages/consul-ui/app/styles/components/composite-row.scss
  ui/packages/consul-ui/app/styles/components/healthcheck-output.scss
  ui/packages/consul-ui/app/styles/components/tooltip.scss
  ui/packages/consul-ui/app/styles/typography.scss
  ui/packages/consul-ui/package.json
  ui/packages/consul-ui/tests/integration/components/tooltip-test.js
  ui/yarn.lock
Labels: backport/1.9, theme/ui

#9290 ui: Round Trip Time Tooltips
  ui/packages/consul-ui/app/components/consul/discovery-chain/index.hbs
  ui/packages/consul-ui/app/components/consul/tomography/graph/index.hbs
  ui/packages/consul-ui/app/components/consul/tomography/graph/index.js
  ui/packages/consul-ui/app/components/consul/tomography/graph/index.scss
  ui/packages/consul-ui/mock-api/v1/coordinate/nodes
Labels: backport/1.9, theme/ui

#9294 ui: Remove unused helpers or swap for helpers in ember-string-fns
  ui/packages/consul-ui/app/components/consul/discovery-chain/index.hbs
  ui/packages/consul-ui/app/components/consul/intention/form/index.hbs
  ui/packages/consul-ui/app/helpers/default.js
  ui/packages/consul-ui/app/helpers/difference.js
  ui/packages/consul-ui/app/helpers/object-entries.js
  ui/packages/consul-ui/app/helpers/starts-with.js
  ui/packages/consul-ui/app/templates/dc/nodes/show/metadata.hbs
  ui/packages/consul-ui/app/templates/dc/services/instance/addresses.hbs
  ui/packages/consul-ui/app/templates/dc/services/instance/metadata.hbs
  ui/packages/consul-ui/tests/integration/helpers/default-test.js
  ui/packages/consul-ui/tests/integration/helpers/object-entries-test.js
  ui/packages/consul-ui/tests/integration/helpers/starts-with-test.js
Labels: backport/1.9, theme/ui

#9293 ui: Moves healthcheck list to Glimmer template-only consul component
  ui/packages/consul-ui/app/components/consul/health-check/list/index.hbs
  ui/packages/consul-ui/app/components/consul/health-check/list/index.scss
  ui/packages/consul-ui/app/components/consul/health-check/list/layout.scss
  ui/packages/consul-ui/app/components/consul/health-check/list/skin.scss
  ui/packages/consul-ui/app/components/healthcheck-list/index.js
  ui/packages/consul-ui/app/styles/components.scss
  ui/packages/consul-ui/app/styles/components/healthcheck-output.scss
  ui/packages/consul-ui/app/styles/components/healthcheck-output/index.scss
  ui/packages/consul-ui/app/templates/dc/nodes/show/healthchecks.hbs
  ui/packages/consul-ui/app/templates/dc/services/instance/healthchecks.hbs
  ui/packages/consul-ui/tests/integration/components/healthcheck-list-test.js
Labels: backport/1.9, theme/ui

#9296 ui: Add copyable IDs to the Role and Policy views
  .changelog/9296.txt
  ui/packages/consul-ui/app/templates/dc/acls/policies/edit.hbs
  ui/packages/consul-ui/app/templates/dc/acls/roles/edit.hbs
Labels: backport/1.9, theme/ui

#9298 ui: Move identity components
  ui/packages/consul-ui/app/components/consul/node-identity/template/index.hbs
  ui/packages/consul-ui/app/components/consul/service-identity/template/index.hbs
  ui/packages/consul-ui/app/components/node-identity/index.js
  ui/packages/consul-ui/app/components/policy-form/index.hbs
  ui/packages/consul-ui/app/components/policy-selector/index.hbs
  ui/packages/consul-ui/app/components/service-identity/index.js
  ui/packages/consul-ui/tests/integration/components/service-identity-test.js
Labels: backport/1.9, theme/ui

#9009 connect: Fix an issue with updating CA config in a secondary datacenter
  agent/connect/ca/provider_consul_test.go
  agent/connect/ca/provider_vault.go
  agent/connect/ca/testing.go
  agent/connect/testing_ca.go
  agent/connect/testing_spiffe.go
  agent/consul/connect_ca_endpoint.go
  agent/consul/connect_ca_endpoint_test.go
  agent/consul/leader.go
  agent/consul/leader_connect.go
  agent/consul/leader_connect_ca.go
  agent/consul/leader_connect_ca_test.go
  agent/consul/leader_connect_test.go
  agent/consul/server.go
  agent/consul/server_connect.go
  agent/consul/server_test.go
  agent/structs/acl.go
  agent/structs/config_entry_intentions.go
  agent/structs/connect_ca.go
Labels: backport/1.8, theme/connect
