Repository hashicorp/consul, pull requests merged in 2021-04, with the labels that each got.

#9960 changelog: fixup release-note formatting
  .changelog/9683.txt
  .changelog/9923.txt
Labels: backport/1.9, pr/no-changelog

#9963 changelog: Auth Method feature release
  .changelog/9617.txt
Labels: pr/no-changelog

#9936 website: homepage changes
  website/components/cta-hero/img/cta-image.jpg
  website/components/cta-hero/index.jsx
  website/components/cta-hero/style.module.css
  website/package-lock.json
  website/package.json
  website/pages/home/img/kubernetes/communication-arrows.svg
  website/pages/home/img/kubernetes/logo.svg
  website/pages/home/index.jsx
  website/pages/home/style.css
  website/pages/style.css
Labels: type/docs, type/docs-cherrypick

#9966 changelog: fixup release-note formatting
  .changelog/8564.txt
Labels: pr/no-changelog

#9964 contributing: add a quick doc on adding new streaming topics.
  contributing/streaming/README.md
  contributing/streaming/adding-a-topic.md
Labels: pr/no-changelog, theme/contributing, theme/streaming, type/docs

#9967 api: ensure v1/health/ingress/:service endpoint works properly when streaming is enabled
  .changelog/9967.txt
  agent/agent.go
  agent/health_endpoint.go
  agent/health_endpoint_test.go
  agent/rpcclient/health/health.go
Labels: theme/health-checks, type/bug

#9968 [1.9.x] api: ensure v1/health/ingress/:service endpoint works properly when streaming is enabled
  .changelog/9967.txt
  agent/agent.go
  agent/health_endpoint.go
  agent/health_endpoint_test.go
  agent/rpcclient/health/health.go
Labels: theme/health-checks

#9958 state: support additional test cases in indexer tests
  agent/consul/state/catalog_oss_test.go
  agent/consul/state/schema_test.go
Labels: pr/no-changelog

#9973 connect: add toggle to globally disable wildcard outbound network access when transparent proxy is enabled
  .changelog/9973.txt
  agent/config/runtime_test.go
  agent/consul/fsm/snapshot_oss_test.go
  agent/consul/state/config_entry.go
  agent/proxycfg/snapshot.go
  agent/proxycfg/state.go
  agent/proxycfg/state_test.go
  agent/structs/config_entry.go
  agent/structs/config_entry_cluster.go
  agent/structs/config_entry_cluster_oss.go
  agent/structs/config_entry_test.go
  agent/xds/listeners.go
  agent/xds/listeners_test.go
  agent/xds/testdata/listeners/transparent-proxy-catalog-destinations-only.envoy-1-17-x.golden
  agent/xds/testdata/listeners/transparent-proxy-catalog-destinations-only.v2compat.envoy-1-17-x.golden
  api/config_entry.go
  api/config_entry_cluster.go
  api/config_entry_test.go
  command/config/write/config_write_test.go
Labels: theme/api, theme/cli, theme/config, theme/envoy/xds

#9974 missed build tag on this file
  agent/structs/config_entry_cluster_oss.go
Labels: pr/no-changelog

#9975 Upgrades the Stackmenu to latest
  website/package-lock.json
  website/package.json
Labels: type/docs, type/docs-cherrypick

#9969 ui: Reformat MaxTokenTTL to sortBy as an integer
  ui/packages/consul-ui/app/components/consul/auth-method/search-bar/index.hbs
  ui/packages/consul-ui/app/models/auth-method.js
  ui/packages/consul-ui/app/sort/comparators/auth-method.js
  ui/packages/consul-ui/package.json
  ui/yarn.lock
Labels: pr/no-changelog, theme/ui

#9980 command: when generating envoy bootstrap configs to stdout do not mix informational logs into the json
  .changelog/9980.txt
  command/connect/envoy/envoy.go
  command/connect/envoy/envoy_test.go
  command/connect/envoy/testdata/CONSUL_HTTP_ADDR-with-https-scheme-enables-tls.golden
  command/connect/envoy/testdata/access-log-path.golden
  command/connect/envoy/testdata/custom-bootstrap.golden
  command/connect/envoy/testdata/defaults.golden
  command/connect/envoy/testdata/existing-ca-file.golden
  command/connect/envoy/testdata/existing-ca-path.golden
  command/connect/envoy/testdata/extra_-multiple.golden
  command/connect/envoy/testdata/extra_-single.golden
  command/connect/envoy/testdata/grpc-addr-config.golden
  command/connect/envoy/testdata/grpc-addr-env.golden
  command/connect/envoy/testdata/grpc-addr-flag.golden
  command/connect/envoy/testdata/grpc-addr-unix.golden
  command/connect/envoy/testdata/ingress-gateway-address-specified.golden
  command/connect/envoy/testdata/ingress-gateway-no-auto-register.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-and-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-without-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway.golden
  command/connect/envoy/testdata/prometheus-metrics.golden
  command/connect/envoy/testdata/stats-config-override.golden
  command/connect/envoy/testdata/token-arg.golden
  command/connect/envoy/testdata/token-env.golden
  command/connect/envoy/testdata/token-file-arg.golden
  command/connect/envoy/testdata/token-file-env.golden
  command/connect/envoy/testdata/zipkin-tracing-config.golden
Labels: backport/1.7, backport/1.8, backport/1.9, theme/cli

#9984 [1.9.x] command: when generating envoy bootstrap configs to stdout do not mix informational logs into the json
  .changelog/9980.txt
  command/connect/envoy/envoy.go
  command/connect/envoy/envoy_test.go
  command/connect/envoy/testdata/CONSUL_HTTP_ADDR-with-https-scheme-enables-tls.golden
  command/connect/envoy/testdata/access-log-path.golden
  command/connect/envoy/testdata/custom-bootstrap.golden
  command/connect/envoy/testdata/defaults.golden
  command/connect/envoy/testdata/existing-ca-file.golden
  command/connect/envoy/testdata/existing-ca-path.golden
  command/connect/envoy/testdata/extra_-multiple.golden
  command/connect/envoy/testdata/extra_-single.golden
  command/connect/envoy/testdata/grpc-addr-config.golden
  command/connect/envoy/testdata/grpc-addr-env.golden
  command/connect/envoy/testdata/grpc-addr-flag.golden
  command/connect/envoy/testdata/grpc-addr-unix.golden
  command/connect/envoy/testdata/ingress-gateway-address-specified.golden
  command/connect/envoy/testdata/ingress-gateway-no-auto-register.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-and-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-without-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway.golden
  command/connect/envoy/testdata/stats-config-override.golden
  command/connect/envoy/testdata/token-arg.golden
  command/connect/envoy/testdata/token-env.golden
  command/connect/envoy/testdata/token-file-arg.golden
  command/connect/envoy/testdata/token-file-env.golden
  command/connect/envoy/testdata/zipkin-tracing-config.golden
Labels: theme/cli

#9977 streaming: Grpc tuning
  agent/cache-types/streaming_health_services.go
  agent/grpc/client.go
  agent/grpc/handler.go
Labels: backport/1.9, pr/no-changelog, theme/streaming

#9978 cache: fix bug where TTLs were ignored leading to leaked memory in client agents
  .changelog/9978.txt
  agent/cache/cache.go
  agent/cache/cache_test.go
Labels: backport/1.9, theme/agent-cache, theme/streaming

#9950 state: use Txn interface everywhere
  agent/consul/state/acl.go
  agent/consul/state/acl_oss.go
  agent/consul/state/autopilot.go
  agent/consul/state/catalog_test.go
  agent/consul/state/config_entry.go
  agent/consul/state/connect_ca.go
  agent/consul/state/coordinate.go
  agent/consul/state/federation_state.go
  agent/consul/state/graveyard.go
  agent/consul/state/graveyard_oss.go
  agent/consul/state/intention.go
  agent/consul/state/prepared_query.go
  agent/consul/state/session.go
  agent/consul/state/session_oss.go
  agent/consul/state/system_metadata.go
Labels: pr/no-changelog

#9988 lib/retry: allow jitter to exceed max wait
  lib/retry/retry.go
  lib/retry/retry_test.go
Labels: pr/no-changelog, theme/internals

#9925 Update memberlist to v0.2.3
  api/go.sum
  go.mod
  go.sum
  vendor/github.com/hashicorp/memberlist/event_delegate.go
  vendor/github.com/hashicorp/memberlist/state.go
  vendor/github.com/hashicorp/memberlist/util.go
  vendor/modules.txt
Labels: pr/dependencies, pr/no-changelog, theme/api

#9042 Auto Rewrite Host Headers for Terminating Gateways
  .changelog/9042.txt
  agent/xds/routes.go
  agent/xds/testdata/routes/terminating-gateway-lb-config.envoy-1-17-x.golden
  agent/xds/testdata/routes/terminating-gateway-lb-config.v2compat.envoy-1-17-x.golden
  test/integration/connect/envoy/case-terminating-gateway-hostnames/config_entries.hcl
  test/integration/connect/envoy/case-terminating-gateway-hostnames/verify.bats
  test/integration/connect/envoy/helpers.bash
Labels: backport/1.8, backport/1.9, theme/connect, theme/terminating-gw

#9976 Fixup centralized upstream config resolution
  agent/consul/config_endpoint.go
  agent/consul/config_endpoint_test.go
  agent/proxycfg/state.go
  agent/proxycfg/state_test.go
  agent/service_manager.go
  agent/structs/config_entry.go
  agent/structs/connect_proxy_config.go
  agent/structs/structs.go
  agent/structs/structs_test.go
  api/config_entry.go
  api/config_entry_test.go
  command/config/write/config_write_test.go
Labels: pr/no-changelog

#9910 cli: Add new `consul connect redirect-traffic` command for applying traffic redirection rules when Transparent Proxy is enabled.
  .changelog/9910.txt
  agent/xds/listeners.go
  build-support/docker/Consul-Dev.dockerfile
  command/commands_oss.go
  command/connect/redirecttraffic/redirect_traffic.go
  command/connect/redirecttraffic/redirect_traffic_test.go
  sdk/go.mod
  sdk/iptables/iptables.go
  sdk/iptables/iptables_executor_linux.go
  sdk/iptables/iptables_executor_unsupported.go
  sdk/iptables/iptables_test.go
  website/content/commands/connect/envoy.mdx
  website/content/commands/connect/index.mdx
  website/content/commands/connect/redirect-traffic.mdx
Labels: pr/dependencies, theme/api, theme/cli

#8431 add http2 ping health checks
  .changelog/8431.txt
  agent/agent.go
  agent/agent_test.go
  agent/checks/check.go
  agent/checks/check_test.go
  agent/config/builder.go
  agent/config/config.go
  agent/config/runtime.go
  agent/config/runtime_test.go
  agent/config/testdata/TestRuntimeConfig_Sanitize.golden
  agent/config/testdata/full-config.hcl
  agent/config/testdata/full-config.json
  agent/structs/check_definition.go
  agent/structs/check_definition_test.go
  agent/structs/check_type.go
  agent/structs/structs.go
  proto/pbservice/healthcheck.gen.go
  proto/pbservice/healthcheck.pb.go
  proto/pbservice/healthcheck.proto
  website/content/api-docs/agent/check.mdx
  website/content/docs/discovery/checks.mdx
Labels: theme/health-checks, type/enhancement

#9989 ui: Return empty string protocol for upstream/downstream metrics request
  ui/packages/consul-ui/app/components/topology-metrics/stats/index.hbs
Labels: pr/no-changelog, theme/ui

#10001 fix(website): docs link text color
  website/pages/style.css
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#9999 Replace TransparentProxy flag with ProxyMode and config struct
  agent/agent_endpoint_test.go
  agent/config/builder.go
  agent/config/config.go
  agent/config/runtime_test.go
  agent/config/testdata/full-config.hcl
  agent/config/testdata/full-config.json
  agent/consul/config_endpoint.go
  agent/consul/config_endpoint_test.go
  agent/dns_test.go
  agent/proxycfg/snapshot.go
  agent/proxycfg/state.go
  agent/proxycfg/state_test.go
  agent/service_manager.go
  agent/service_manager_test.go
  agent/structs/config_entry.go
  agent/structs/connect_proxy_config.go
  agent/structs/connect_proxy_config_test.go
  agent/structs/structs_filtering_test.go
  agent/xds/clusters.go
  agent/xds/clusters_test.go
  agent/xds/listeners.go
  agent/xds/listeners_test.go
  agent/xds/server.go
  api/agent.go
  api/agent_test.go
  api/config_entry.go
  api/config_entry_test.go
  command/config/write/config_write_test.go
  proto/pbservice/service.gen.go
  proto/pbservice/service.pb.binary.go
  proto/pbservice/service.pb.go
  proto/pbservice/service.proto
Labels: pr/no-changelog, theme/api, theme/cli, theme/config, theme/envoy/xds

#10003 Fixup wildcard ent assertion
  agent/proxycfg/state_test.go
Labels: pr/no-changelog

#10000 Remove zero-value validation of upstream cfg structs
  agent/structs/config_entry.go
  agent/structs/config_entry_test.go
Labels: pr/no-changelog

#10005 Avoid nil panic when cluster config doesn't exist
  agent/xds/clusters.go
  agent/xds/listeners.go
Labels: pr/no-changelog, theme/envoy/xds

#9992 refactor: upgrade learn callout
  website/components/learn-callout/index.jsx
  website/components/learn-callout/style.css
  website/package-lock.json
  website/package.json
  website/pages/home/index.jsx
  website/pages/style.css
Labels: type/docs

#9982 add consul-haskell to libraries-and-sdks documentation
  website/content/api-docs/libraries-and-sdks.mdx
Labels: pr/no-changelog, type/docs-cherrypick

#10008 website: update why hashicorp links
  website/pages/home/index.jsx
Labels: type/docs, type/docs-cherrypick

#9987 Remove kube-dns resolution since clusterip will be a tagged addr
  agent/xds/listeners.go
Labels: pr/no-changelog, theme/envoy/xds

#10006 Convert new tproxy structs in api module into ptrs
  agent/agent_endpoint_test.go
  agent/structs/connect_proxy_config.go
  agent/structs/connect_proxy_config_test.go
  api/agent.go
  api/catalog_test.go
  api/config_entry.go
  api/config_entry_test.go
  command/config/write/config_write_test.go
  command/services/config_test.go
Labels: pr/no-changelog, theme/api, theme/cli

#10013 Move static token resolution into the ACLResolver
  .changelog/10013.txt
  agent/acl.go
  agent/acl_endpoint.go
  agent/acl_test.go
  agent/agent.go
  agent/agent_endpoint.go
  agent/connect_auth.go
  agent/consul/acl.go
  agent/consul/acl_oss.go
  agent/consul/acl_server.go
  agent/consul/acl_server_oss.go
  agent/consul/acl_test.go
  agent/consul/client.go
  agent/consul/server.go
  agent/event_endpoint.go
  agent/http.go
  agent/structs/acl.go
  agent/ui_endpoint.go
Labels: backport/1.8, backport/1.9

#10014 Add changelog for enterprise change
  .changelog/_855.txt
Labels: backport/1.8, backport/1.9, pr/no-changelog

#10025 snapshot: fix saving of auth methods
  .changelog/10025.txt
  agent/consul/fsm/snapshot_oss.go
  agent/consul/fsm/snapshot_oss_test.go
Labels: backport/1.7, backport/1.8, backport/1.9, type/bug

#10023 Add content type headers to raw KV responses
  .changelog/10023.txt
  agent/kvs_endpoint.go
  agent/kvs_endpoint_test.go
  website/content/api-docs/kv.mdx
Labels: backport/1.7, backport/1.8, backport/1.9, type/docs

#10040 update changelog for 1.7.14
  CHANGELOG.md
Labels: pr/no-changelog

#10041 update changelog for 1.8.10
  CHANGELOG.md
Labels: pr/no-changelog

#10042 update changelog for 1.9.5
  CHANGELOG.md
Labels: pr/no-changelog

#10039 ui: remove old nspace argument from the proxy instance repository
  .changelog/10039.txt
  ui/packages/consul-ui/app/services/repository/proxy.js
Labels: theme/ui

#10035 ui: Never respond with empty gateway addresses (mock-api)
  ui/packages/consul-ui/mock-api/v1/internal/ui/gateway-services-nodes/_
Labels: pr/no-changelog, theme/ui

#10015 connect: update centralized upstreams representation in service-defaults
  agent/consul/config_endpoint.go
  agent/consul/config_endpoint_test.go
  agent/consul/server_register.go
  agent/structs/config_entry.go
  agent/structs/config_entry_test.go
  agent/structs/connect_proxy_config.go
  agent/structs/structs_filtering_test.go
  api/config_entry.go
  api/config_entry_test.go
  build-support/scripts/proto-gen.sh
  command/config/write/config_write_test.go
  proto/pbservice/healthcheck.gen.go
  proto/pbservice/service.gen.go
  proto/pbservice/service.pb.go
  proto/pbservice/service.proto
Labels: pr/no-changelog, theme/api, theme/cli, theme/envoy/xds

#10031 Split Upstream.Identifier() so non-empty namespace is always prepended in ent
  agent/proxycfg/manager_test.go
  agent/proxycfg/state_test.go
  agent/structs/connect_proxy_config.go
  agent/structs/connect_proxy_config_oss.go
  agent/xds/clusters.go
Labels: pr/no-changelog, theme/envoy/xds

#10002 ui: TProxy Service Mesh Viz Beta Changes
  .changelog/10002.txt
  ui/packages/consul-ui/app/components/consul/transparent-proxy/index.hbs
  ui/packages/consul-ui/app/components/informed-action/layout.scss
  ui/packages/consul-ui/app/components/topology-metrics/card/index.hbs
  ui/packages/consul-ui/app/components/topology-metrics/card/index.scss
  ui/packages/consul-ui/app/components/topology-metrics/down-lines/index.hbs
  ui/packages/consul-ui/app/components/topology-metrics/index.hbs
  ui/packages/consul-ui/app/components/topology-metrics/index.js
  ui/packages/consul-ui/app/components/topology-metrics/layout.scss
  ui/packages/consul-ui/app/components/topology-metrics/notice/index.hbs
  ui/packages/consul-ui/app/components/topology-metrics/notice/limited-access.hbs
  ui/packages/consul-ui/app/components/topology-metrics/popover/index.hbs
  ui/packages/consul-ui/app/components/topology-metrics/popover/index.scss
  ui/packages/consul-ui/app/components/topology-metrics/skin.scss
  ui/packages/consul-ui/app/components/topology-metrics/source-type/index.hbs
  ui/packages/consul-ui/app/components/topology-metrics/source-type/index.scss
  ui/packages/consul-ui/app/helpers/service/intention-permissions.js
  ui/packages/consul-ui/app/models/topology.js
  ui/packages/consul-ui/app/styles/components.scss
  ui/packages/consul-ui/app/styles/components/pill.scss
  ui/packages/consul-ui/app/templates/dc/services/instance.hbs
  ui/packages/consul-ui/app/templates/dc/services/show/topology.hbs
  ui/packages/consul-ui/mock-api/v1/catalog/connect/_
  ui/packages/consul-ui/mock-api/v1/internal/ui/service-topology/_
  ui/packages/consul-ui/translations/en-us.yaml
Labels: theme/ui

#10043 docs: update upgrade guide to use 1.8.10
  website/content/docs/upgrading/instructions/index.mdx
  website/content/docs/upgrading/instructions/upgrade-to-1-8-x.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#10046 Don't panic on nil UpstreamConfiguration.Clone()
  agent/structs/config_entry.go
Labels: pr/no-changelog

#10044 ui: fix mismatched curly brace in mock-api
  ui/packages/consul-ui/mock-api/v1/internal/ui/gateway-services-nodes/_
Labels: pr/no-changelog, theme/ui

#10049 Check for optionally prepended namespace in upstream assertion
  test/integration/connect/envoy/case-basic/verify.bats
  test/integration/connect/envoy/case-http/verify.bats
Labels: pr/no-changelog

#10034 ui: Hoist DC menu into the top navigation bar
  ui/packages/consul-ui/app/components/app/index.scss
  ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs
  ui/packages/consul-ui/app/components/hashicorp-consul/index.scss
  ui/packages/consul-ui/app/components/main-nav-vertical/README.mdx
  ui/packages/consul-ui/app/components/main-nav-vertical/debug.scss
  ui/packages/consul-ui/app/components/main-nav-vertical/layout.scss
  ui/packages/consul-ui/app/components/main-nav-vertical/skin.scss
  ui/packages/consul-ui/app/styles/debug.scss
  ui/packages/consul-ui/lib/startup/templates/head.html.js
Labels: pr/no-changelog, theme/ui

#10054 chore: sync changelog entries back from 1.10.0-beta1, 1.9.5, 1.8.10, 1.7.14
  CHANGELOG.md
Labels: pr/no-changelog

#10004 ci: test against Go1.16.3
  .circleci/config.yml
  connect/tls_test.go
  tlsutil/generate_test.go
Labels: pr/no-changelog, type/ci

#10032 docs: update helm ref docs and connect docs
  website/content/docs/k8s/connect/health.mdx
  website/content/docs/k8s/connect/index.mdx
  website/content/docs/k8s/connect/ingress-gateways.mdx
  website/content/docs/k8s/connect/terminating-gateways.mdx
  website/content/docs/k8s/helm.mdx
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#10038 Add docs for transparent proxy mode and config
  website/content/api-docs/agent/service.mdx
  website/content/api-docs/catalog.mdx
  website/content/api-docs/health.mdx
  website/content/commands/connect/redirect-traffic.mdx
  website/content/docs/connect/config-entries/cluster.mdx
  website/content/docs/connect/config-entries/index.mdx
  website/content/docs/connect/config-entries/proxy-defaults.mdx
  website/content/docs/connect/config-entries/service-defaults.mdx
  website/content/docs/connect/registration/service-registration.mdx
  website/content/docs/connect/transparent-proxy.mdx
  website/content/docs/discovery/services.mdx
  website/data/commands-nav-data.json
  website/data/docs-nav-data.json
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#10055 vendor: commit changes from update-vendor
  go.sum
Labels: pr/dependencies, pr/no-changelog

#10058 website: add 1.10.0 beta callout
  website/pages/downloads/index.jsx
Labels: backport/1.10, pr/no-changelog, type/docs

#10059 website: fix search indexing issue
  website/scripts/index_search_content.js
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#10063 website: v1.9.5
  website/data/version.js
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#10069 Disallow * as service-defaults name
  .changelog/10069.txt
  agent/structs/config_entry.go
  agent/structs/config_entry_test.go
Labels: backport/1.10

#10066 Refactor get started links to new tutorial
  website/content/docs/k8s/installation/install.mdx
  website/pages/home/index.jsx
  website/pages/use-cases/multi-platform-service-mesh.jsx
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#9991 Handle FSM.Apply errors in raftApply
  agent/consul/acl_endpoint.go
  agent/consul/acl_endpoint_legacy.go
  agent/consul/acl_replication_types.go
  agent/consul/acl_token_exp.go
  agent/consul/catalog_endpoint.go
  agent/consul/config_endpoint.go
  agent/consul/config_replication.go
  agent/consul/consul_ca_delegate.go
  agent/consul/coordinate_endpoint.go
  agent/consul/federation_state_endpoint.go
  agent/consul/federation_state_replication.go
  agent/consul/intention_endpoint.go
  agent/consul/kvs_endpoint.go
  agent/consul/leader.go
  agent/consul/leader_connect.go
  agent/consul/leader_connect_test.go
  agent/consul/leader_federation_state_ae.go
  agent/consul/leader_intentions.go
  agent/consul/leader_intentions_test.go
  agent/consul/operator_autopilot_endpoint.go
  agent/consul/prepared_query_endpoint.go
  agent/consul/rpc.go
  agent/consul/session_endpoint.go
  agent/consul/system_metadata.go
  agent/consul/txn_endpoint.go
Labels: pr/no-changelog, theme/internal-cleanup

#10082 Fix missing agent/sentinel page
  website/data/docs-nav-data.json
Labels: type/docs, type/docs-cherrypick

#10079 [1.9.x] connect/ca: Allow ForceWithoutCrossSigning for all providers
  .changelog/9672.txt
  agent/consul/leader_connect_ca.go
  agent/consul/leader_connect_test.go
  api/connect_ca.go
  command/connect/ca/set/connect_ca_set.go
  website/content/api-docs/connect/ca.mdx
  website/content/commands/connect/ca.mdx
Labels: theme/api, theme/cli, type/docs

#10088 docs - Adding json formatting to TProxy HCL examples
  website/content/docs/connect/transparent-proxy.mdx
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#10050 ui: Add information regarding Host header for ingress gateways
  ui/packages/consul-ui/app/components/inline-code/README.mdx
  ui/packages/consul-ui/app/components/inline-code/index.scss
  ui/packages/consul-ui/app/components/inline-code/layout.scss
  ui/packages/consul-ui/app/components/inline-code/skin.scss
  ui/packages/consul-ui/app/instance-initializers/i18n.js
  ui/packages/consul-ui/app/styles/base/components/form-elements/index.scss
  ui/packages/consul-ui/app/styles/base/components/form-elements/layout.scss
  ui/packages/consul-ui/app/styles/base/components/form-elements/skin.scss
  ui/packages/consul-ui/app/styles/components.scss
  ui/packages/consul-ui/app/styles/typography.scss
  ui/packages/consul-ui/app/templates/dc/services/show/upstreams.hbs
  ui/packages/consul-ui/app/templates/debug.hbs
  ui/packages/consul-ui/ember-cli-build.js
  ui/packages/consul-ui/translations/en-us.yaml
Labels: backport/1.10, pr/no-changelog, theme/ui

#10051 ui: Add Admin Partition feature flag
  ui/packages/consul-ui/README.md
  ui/packages/consul-ui/app/utils/get-environment.js
  ui/packages/consul-ui/config/environment.js
  ui/packages/consul-ui/docs/bookmarklets.mdx
  ui/packages/consul-ui/node-tests/config/environment.js
Labels: backport/1.10, pr/no-changelog, theme/ui

#10052 ui: Vertically stack methods listing in the L7 intentions form
  ui/packages/consul-ui/app/components/consul/intention/permission/form/layout.scss
Labels: backport/1.10, backport/1.9, pr/no-changelog, theme/ui

#10073 Add replication metrics
  agent/consul/leader.go
  agent/consul/replication.go
  agent/consul/replication_test.go
  agent/consul/server.go
Labels: backport/1.8, backport/1.9

#10094 updating fingerprint
  .circleci/config.yml
  .circleci/scripts/cherry-picker.sh
Labels: type/ci

#10086 sdk/retry: a few small debug improvements
  sdk/testutil/retry/retry.go
  sdk/testutil/retry/retry_test.go
Labels: pr/no-changelog, theme/internal-cleanup

#10085 lib/ttlcache: never decrease the expiry on update
  lib/ttlcache/eviction.go
  lib/ttlcache/eviction_test.go
Labels: pr/no-changelog, theme/internals

#10087 website: resolve unlinked content
  .github/workflows/check-unlinked-content.js
  .github/workflows/check-unlinked-content.yml
  website/components/_temp-enable-hidden-pages/index.js
  website/data/api-docs-nav-data-hidden.json
  website/data/commands-nav-data-hidden.json
  website/data/docs-nav-data-hidden.json
  website/pages/api-docs/[[...page]].jsx
  website/pages/commands/[[...page]].jsx
  website/pages/docs/[[...page]].jsx
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#10089 CLI: Allow snapshot inspect to work on internal raft snapshots directly.
  .changelog/10089.txt
  command/snapshot/inspect/snapshot_inspect.go
  command/snapshot/inspect/snapshot_inspect_test.go
  command/snapshot/inspect/testdata/TestSnapshotInspectCommandRaw.golden
  command/snapshot/inspect/testdata/raw/meta.json
  command/snapshot/inspect/testdata/raw/state.bin
  website/content/commands/snapshot/inspect.mdx
Labels: theme/cli, theme/reliability, type/docs

#10097 test: switch envoy integration tests to use pgrep+kill instead of ps+grep+awk+kill
  test/integration/connect/envoy/helpers.bash
Labels: backport/1.10, backport/1.7, backport/1.8, backport/1.9, pr/no-changelog

#10091 Fix panic bug in snapshot inspect
  .changelog/10091.txt
  command/snapshot/inspect/snapshot_inspect.go
  command/snapshot/inspect/snapshot_inspect_test.go
Labels: backport/1.7, backport/1.8, backport/1.9, theme/cli

#10107 Update changelog for #10073 and also update the telemetry docs which I forgot to before.
  .changelog/10073.txt
  website/content/docs/agent/telemetry.mdx
Labels: backport/1.10, backport/1.8, backport/1.9, pr/no-changelog, type/docs

#10102 [Backport/1.10.x]: Backport #10073
  .circleci/config.yml
  .circleci/scripts/cherry-picker.sh
  agent/consul/leader.go
  agent/consul/replication.go
  agent/consul/replication_test.go
  agent/consul/server.go
Labels: type/ci

#10104 [Backport/1.9.x] Backport #10073
  .circleci/config.yml
  .circleci/scripts/cherry-picker.sh
  agent/consul/leader.go
  agent/consul/replication.go
  agent/consul/replication_test.go
  agent/consul/server.go
Labels: type/ci

#10108 Fix panic bug in snapshot inspect (#10091)
  .changelog/10091.txt
  command/snapshot/inspect/snapshot_inspect.go
  command/snapshot/inspect/snapshot_inspect_test.go
Labels: theme/cli

#10109 Add prometheus guage definitions for replication metrics.
  agent/consul/replication.go
  agent/setup.go
Labels: backport/1.10, backport/1.9, pr/no-changelog

#10093 ui: Splitting up the translations file into folder structure
  ui/packages/consul-ui/config/ember-intl.js
  ui/packages/consul-ui/translations/common/en-us.yaml
  ui/packages/consul-ui/translations/components/app/en-us.yaml
  ui/packages/consul-ui/translations/components/consul/en-us.yaml
  ui/packages/consul-ui/translations/en-us.yaml
  ui/packages/consul-ui/translations/models/en-us.yaml
  ui/packages/consul-ui/translations/routes/en-us.yaml
Labels: pr/no-changelog, theme/ui

#10078 website: update readme
  website/README.md
Labels: type/docs-cherrypick

#10130 ui: Fix up changelog for 10002
  .changelog/10002.txt
Labels: backport/1.10, pr/no-changelog, theme/ui

#10062 ui: Adds human formatting to nanosecond based session durations
  .changelog/10062.txt
  .circleci/config.yml
  ui/packages/consul-ui/app/components/consul/lock-session/form/index.hbs
  ui/packages/consul-ui/app/components/consul/lock-session/list/index.hbs
  ui/packages/consul-ui/app/helpers/duration-from.js
  ui/packages/consul-ui/app/helpers/duration-from.mdx
  ui/packages/consul-ui/app/services/temporal.js
  ui/packages/consul-ui/package.json
  ui/packages/consul-ui/tests/acceptance/dc/nodes/sessions/list.feature
  ui/packages/consul-ui/tests/integration/helpers/duration-from-test.js
  ui/packages/consul-ui/tests/unit/services/temporal-test.js
  ui/yarn.lock
Labels: backport/1.10, backport/1.8, backport/1.9, theme/ui

#10122 ui: Fix empty SVG height
  .changelog/10122.txt
  ui/packages/consul-ui/app/components/topology-metrics/index.js
Labels: backport/1.10, theme/ui

#10124 ui: Update conditional for topology empty state
  .changelog/10124.txt
  ui/packages/consul-ui/app/templates/dc/services/show/topology.hbs
Labels: backport/1.10, theme/ui

#10133 ui: Update not-defined intention popover and banner
  .changelog/10133.txt
  ui/packages/consul-ui/app/components/topology-metrics/down-lines/index.hbs
  ui/packages/consul-ui/app/components/topology-metrics/popover/index.hbs
  ui/packages/consul-ui/translations/components/consul/en-us.yaml
Labels: backport/1.10, theme/ui

#10136 ui: Add TProxy Mode notice banner to service instance Upstreams tab
  .changelog/10136.txt
  ui/packages/consul-ui/app/templates/dc/services/instance/upstreams.hbs
  ui/packages/consul-ui/translations/routes/en-us.yaml
Labels: backport/1.10, theme/ui

#10145 remove Codecov from CI runs
  .circleci/config.yml
Labels: type/ci

#10146 connect/proxy: fix a few problems with tests
  connect/proxy/config_test.go
  connect/proxy/conn_test.go
  connect/proxy/listener.go
  connect/proxy/listener_test.go
Labels: pr/no-changelog, theme/connect

#10127 Rename "cluster" config entry to "mesh"
  .changelog/10127.txt
  agent/config/runtime_test.go
  agent/consul/fsm/snapshot_oss_test.go
  agent/consul/state/config_entry.go
  agent/proxycfg/snapshot.go
  agent/proxycfg/state.go
  agent/proxycfg/state_test.go
  agent/structs/config_entry.go
  agent/structs/config_entry_cluster.go
  agent/structs/config_entry_cluster_oss.go
  agent/structs/config_entry_test.go
  agent/xds/clusters.go
  agent/xds/clusters_test.go
  agent/xds/listeners.go
  agent/xds/listeners_test.go
  api/config_entry.go
  api/config_entry_cluster.go
  api/config_entry_test.go
  command/config/write/config_write_test.go
  website/content/docs/connect/config-entries/mesh.mdx
  website/data/docs-nav-data.json
Labels: backport/1.10, theme/api, theme/cli, theme/config, theme/envoy/xds, type/docs

#10148 Rename cluster config files to mesh as well
  agent/structs/config_entry_mesh.go
  agent/structs/config_entry_mesh_oss.go
Labels: backport/1.10, pr/no-changelog

#10128 ui: Add a max height and scroll to the intention perm header lists
  ui/packages/consul-ui/app/components/consul/intention/permission/header/list/layout.scss
Labels: backport/1.10, backport/1.9, pr/no-changelog, theme/ui

#10134 Implement traffic redirection exclusion based on proxy config and user-provided values
  .changelog/10134.txt
  command/connect/redirecttraffic/redirect_traffic.go
  command/connect/redirecttraffic/redirect_traffic_test.go
  sdk/iptables/iptables.go
  sdk/iptables/iptables_test.go
  website/content/commands/connect/redirect-traffic.mdx
Labels: backport/1.10, theme/connect, type/enhancement

#10123 Improve doc: add note about address validation
  website/content/docs/discovery/services.mdx
Labels: pr/no-changelog, theme/service-metadata, type/docs, type/docs-cherrypick

#10111 make h2ping changelog entry conform with changelog template
  .changelog/8431.txt
Labels: backport/1.10

#9855 Support Incremental xDS mode
  .changelog/9855.txt
  agent/agent.go
  agent/proxycfg/testing.go
  agent/xds/clusters.go
  agent/xds/clusters_test.go
  agent/xds/config.go
  agent/xds/config_test.go
  agent/xds/delta.go
  agent/xds/delta_test.go
  agent/xds/endpoints.go
  agent/xds/endpoints_test.go
  agent/xds/envoy_versioning.go
  agent/xds/envoy_versioning_test.go
  agent/xds/listeners.go
  agent/xds/listeners_test.go
  agent/xds/protocol_trace.go
  agent/xds/resources.go
  agent/xds/routes.go
  agent/xds/routes_test.go
  agent/xds/server.go
  agent/xds/server_test.go
  agent/xds/testing.go
  agent/xds/version_compat.go
  agent/xds/xds_protocol_helpers_test.go
  command/connect/envoy/bootstrap_tpl.go
  command/connect/envoy/testdata/CONSUL_HTTP_ADDR-with-https-scheme-enables-tls.golden
  command/connect/envoy/testdata/access-log-path.golden
  command/connect/envoy/testdata/defaults.golden
  command/connect/envoy/testdata/existing-ca-file.golden
  command/connect/envoy/testdata/existing-ca-path.golden
  command/connect/envoy/testdata/extra_-multiple.golden
  command/connect/envoy/testdata/extra_-single.golden
  command/connect/envoy/testdata/grpc-addr-config.golden
  command/connect/envoy/testdata/grpc-addr-env.golden
  command/connect/envoy/testdata/grpc-addr-flag.golden
  command/connect/envoy/testdata/grpc-addr-unix.golden
  command/connect/envoy/testdata/ingress-gateway-address-specified.golden
  command/connect/envoy/testdata/ingress-gateway-no-auto-register.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-and-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-without-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway.golden
  command/connect/envoy/testdata/prometheus-metrics.golden
  command/connect/envoy/testdata/stats-config-override.golden
  command/connect/envoy/testdata/token-arg.golden
  command/connect/envoy/testdata/token-env.golden
  command/connect/envoy/testdata/token-file-arg.golden
  command/connect/envoy/testdata/token-file-env.golden
  command/connect/envoy/testdata/zipkin-tracing-config.golden
  go.mod
  logging/names.go
  test/integration/connect/envoy/case-cfg-resolver-dc-failover-gateways-none/primary/verify.bats
  test/integration/connect/envoy/case-cfg-resolver-dc-failover-gateways-remote/primary/verify.bats
  test/integration/connect/envoy/case-gateway-without-services/capture.sh
  test/integration/connect/envoy/case-wanfed-gw/capture.sh
  test/integration/connect/envoy/case-wanfed-gw/primary/verify.bats
  test/integration/connect/envoy/case-wanfed-gw/secondary/server.hcl
  test/integration/connect/envoy/case-wanfed-gw/secondary/verify.bats
  test/integration/connect/envoy/consul-base-cfg/base.hcl
  test/integration/connect/envoy/helpers.bash
  test/integration/connect/envoy/run-tests.sh
Labels: backport/1.10, theme/cli, theme/envoy/xds

#10105 [1.9.x] connect: update supported envoy versions to 1.16.3, 1.15.4, 1.14.7, 1.13.7
  .changelog/10105.txt
  .circleci/config.yml
  agent/xds/envoy_versioning_test.go
  agent/xds/proxysupport/proxysupport.go
  agent/xds/testdata/routes/terminating-gateway-lb-config.envoy-1-17-x.golden
  command/connect/envoy/testdata/CONSUL_HTTP_ADDR-with-https-scheme-enables-tls.golden
  command/connect/envoy/testdata/access-log-path.golden
  command/connect/envoy/testdata/defaults.golden
  command/connect/envoy/testdata/existing-ca-file.golden
  command/connect/envoy/testdata/existing-ca-path.golden
  command/connect/envoy/testdata/extra_-multiple.golden
  command/connect/envoy/testdata/extra_-single.golden
  command/connect/envoy/testdata/grpc-addr-config.golden
  command/connect/envoy/testdata/grpc-addr-env.golden
  command/connect/envoy/testdata/grpc-addr-flag.golden
  command/connect/envoy/testdata/grpc-addr-unix.golden
  command/connect/envoy/testdata/ingress-gateway-address-specified.golden
  command/connect/envoy/testdata/ingress-gateway-no-auto-register.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-and-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-without-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway.golden
  command/connect/envoy/testdata/stats-config-override.golden
  command/connect/envoy/testdata/token-arg.golden
  command/connect/envoy/testdata/token-env.golden
  command/connect/envoy/testdata/token-file-arg.golden
  command/connect/envoy/testdata/token-file-env.golden
  command/connect/envoy/testdata/zipkin-tracing-config.golden
  test/integration/connect/envoy/run-tests.sh
Labels: theme/cli, theme/envoy/xds, type/ci

#10158 dev: adding a make target to regenerate envoy golden files
  GNUmakefile
Labels: backport/1.10, backport/1.8, backport/1.9, pr/no-changelog

#10149 config: default UseStreamingBackend to true
  .changelog/10149.txt
  agent/config/builder.go
  website/content/docs/agent/options.mdx
Labels: backport/1.10, theme/config, theme/streaming, type/docs

#10154 docs(discovery/service): Clarify multiple service definitions
  website/content/docs/discovery/services.mdx
Labels: pr/no-changelog, type/docs-cherrypick
