Repository hashicorp/consul, pull requests merged in 2021-05, with the labels that each got.

#10081 Update brand assets
  .changelog/10081.txt
  ui/packages/consul-ui/app/components/consul/logo/index.hbs
  ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs
  ui/packages/consul-ui/app/styles/base/icons/base-variables.scss
  ui/packages/consul-ui/app/styles/components/brand-loader.scss
  ui/packages/consul-ui/app/styles/components/brand-loader/layout.scss
  ui/packages/consul-ui/app/styles/debug.scss
  ui/packages/consul-ui/app/styles/variables/skin.scss
  ui/packages/consul-ui/lib/startup/templates/body.html.js
  ui/packages/consul-ui/lib/startup/templates/head.html.js
  ui/packages/consul-ui/public/assets/android-chrome-192x192.png
  ui/packages/consul-ui/public/assets/android-chrome-512x512.png
  ui/packages/consul-ui/public/assets/apple-touch-icon-114x114.png
  ui/packages/consul-ui/public/assets/apple-touch-icon-120x120.png
  ui/packages/consul-ui/public/assets/apple-touch-icon-144x144.png
  ui/packages/consul-ui/public/assets/apple-touch-icon-152x152.png
  ui/packages/consul-ui/public/assets/apple-touch-icon-57x57.png
  ui/packages/consul-ui/public/assets/apple-touch-icon-60x60.png
  ui/packages/consul-ui/public/assets/apple-touch-icon-72x72.png
  ui/packages/consul-ui/public/assets/apple-touch-icon-76x76.png
  ui/packages/consul-ui/public/assets/apple-touch-icon.png
  ui/packages/consul-ui/public/assets/consul-logo.png
  ui/packages/consul-ui/public/assets/favicon-128.png
  ui/packages/consul-ui/public/assets/favicon-16x16.png
  ui/packages/consul-ui/public/assets/favicon-196x196.png
  ui/packages/consul-ui/public/assets/favicon-32x32.png
  ui/packages/consul-ui/public/assets/favicon-96x96.png
  ui/packages/consul-ui/public/assets/favicon.ico
  ui/packages/consul-ui/public/assets/favicon.png
  ui/packages/consul-ui/public/assets/favicon.svg
  ui/packages/consul-ui/public/assets/mstile-144x144.png
  ui/packages/consul-ui/public/assets/mstile-150x150.png
  ui/packages/consul-ui/public/assets/mstile-310x150.png
  ui/packages/consul-ui/public/assets/mstile-310x310.png
  ui/packages/consul-ui/public/assets/mstile-70x70.png
  ui/packages/consul-ui/public/assets/safari-pinned-tab.svg
Labels: backport/1.10, theme/ui

#10162 Only consider virtual IPs for transparent proxies
  .changelog/10162.txt
  agent/xds/listeners.go
  agent/xds/listeners_test.go
  agent/xds/testdata/listeners/transparent-proxy-catalog-destinations-only.envoy-1-18-x.golden
  agent/xds/testdata/listeners/transparent-proxy-catalog-destinations-only.v2compat.envoy-1-16-x.golden
  agent/xds/testdata/listeners/transparent-proxy.envoy-1-18-x.golden
  agent/xds/testdata/listeners/transparent-proxy.v2compat.envoy-1-16-x.golden
  website/content/docs/connect/transparent-proxy.mdx
Labels: backport/1.10, theme/envoy/xds, type/docs

#10163 Give descriptive error if auth method not found
  .changelog/10163.txt
  agent/consul/acl_endpoint.go
  agent/consul/acl_endpoint_test.go
  command/login/login_test.go
Labels: backport/1.10, backport/1.9, theme/acls, type/enhancement

#10140 [Backport/1.10.x] Backport #10034
  ui/packages/consul-ui/app/components/app/index.scss
  ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs
  ui/packages/consul-ui/app/components/hashicorp-consul/index.scss
  ui/packages/consul-ui/app/components/main-nav-vertical/README.mdx
  ui/packages/consul-ui/app/components/main-nav-vertical/debug.scss
  ui/packages/consul-ui/app/components/main-nav-vertical/layout.scss
  ui/packages/consul-ui/app/components/main-nav-vertical/skin.scss
  ui/packages/consul-ui/app/styles/debug.scss
  ui/packages/consul-ui/lib/startup/templates/head.html.js
Labels: pr/no-changelog, theme/ui

#10141 [Backport/1.9.x] Backport #10062
  .changelog/10062.txt
  .circleci/config.yml
  ui/packages/consul-ui/app/components/consul/lock-session/form/index.hbs
  ui/packages/consul-ui/app/components/consul/lock-session/list/index.hbs
  ui/packages/consul-ui/app/helpers/duration-from.js
  ui/packages/consul-ui/app/helpers/duration-from.mdx
  ui/packages/consul-ui/app/services/temporal.js
  ui/packages/consul-ui/package.json
  ui/packages/consul-ui/tests/acceptance/dc/nodes/sessions/list.feature
  ui/packages/consul-ui/tests/integration/helpers/duration-from-test.js
  ui/packages/consul-ui/tests/unit/services/temporal-test.js
  ui/yarn.lock
Labels: theme/ui

#10129 Make Raft trailing logs and snapshot timing reloadable
  .changelog/10129.txt
  agent/agent.go
  agent/consul/config.go
  agent/consul/server.go
  agent/consul/server_test.go
  agent/setup.go
  go.mod
  go.sum
  vendor/github.com/armon/go-metrics/prometheus/prometheus.go
  vendor/github.com/hashicorp/raft/CHANGELOG.md
  vendor/github.com/hashicorp/raft/Makefile
  vendor/github.com/hashicorp/raft/README.md
  vendor/github.com/hashicorp/raft/api.go
  vendor/github.com/hashicorp/raft/commitment.go
  vendor/github.com/hashicorp/raft/config.go
  vendor/github.com/hashicorp/raft/configuration.go
  vendor/github.com/hashicorp/raft/fsm.go
  vendor/github.com/hashicorp/raft/future.go
  vendor/github.com/hashicorp/raft/go.mod
  vendor/github.com/hashicorp/raft/go.sum
  vendor/github.com/hashicorp/raft/log.go
  vendor/github.com/hashicorp/raft/log_cache.go
  vendor/github.com/hashicorp/raft/net_transport.go
  vendor/github.com/hashicorp/raft/observer.go
  vendor/github.com/hashicorp/raft/raft.go
  vendor/github.com/hashicorp/raft/replication.go
  vendor/github.com/hashicorp/raft/snapshot.go
  vendor/github.com/hashicorp/raft/tag.sh
  vendor/github.com/hashicorp/raft/testing.go
  vendor/modules.txt
  website/content/docs/agent/options.mdx
  website/content/docs/agent/telemetry.mdx
Labels: pr/dependencies, theme/reliability, type/docs

#10168 Fixup discovery chain handling in transparent mode
  agent/proxycfg/state.go
  agent/proxycfg/state_test.go
  agent/structs/discovery_chain.go
  agent/xds/listeners.go
  agent/xds/listeners_test.go
Labels: backport/1.10, pr/no-changelog, theme/envoy/xds

#10100 ui: Adds CRD popover 'informed action' for intentions managed by CRDs
  .changelog/10100.txt
  ui/packages/consul-ui/app/components/aria-menu/index.js
  ui/packages/consul-ui/app/components/consul/intention/list/layout.scss
  ui/packages/consul-ui/app/components/consul/intention/list/table/index.hbs
  ui/packages/consul-ui/app/components/informed-action/skin.scss
  ui/packages/consul-ui/app/components/menu-panel/index.hbs
  ui/packages/consul-ui/app/components/menu-panel/index.js
  ui/packages/consul-ui/app/components/menu-panel/layout.scss
  ui/packages/consul-ui/app/styles/base/icons/icon-placeholders.scss
Labels: backport/1.10, backport/1.9, theme/ui

#10151 ui: Fix text search for upstream instances
  .changelog/10151.txt
  ui/packages/consul-ui/app/components/data-collection/README.mdx
  ui/packages/consul-ui/app/search/predicates/health-check.js
  ui/packages/consul-ui/app/search/predicates/nspace.js
  ui/packages/consul-ui/app/search/predicates/role.js
  ui/packages/consul-ui/app/search/predicates/service-instance.js
  ui/packages/consul-ui/app/search/predicates/token.js
  ui/packages/consul-ui/app/search/predicates/upstream-instance.js
  ui/packages/consul-ui/app/styles/debug.scss
  ui/packages/consul-ui/config/environment.js
  ui/packages/consul-ui/ember-cli-build.js
  ui/packages/consul-ui/lib/startup/index.js
  ui/packages/consul-ui/lib/startup/templates/head.html.js
Labels: backport/1.10, backport/1.9, theme/ui

#10152 ui: Remove extra nspace value from service upstreams
  .changelog/10152.txt
  ui/packages/consul-ui/app/components/consul/upstream/list/index.hbs
Labels: backport/1.10, backport/1.9, theme/ui

#10167 ci: allow cherry-picking a manual backport to other release branches
  .circleci/config.yml
  .circleci/scripts/cherry-picker.sh
Labels: backport/1.10, backport/1.8, backport/1.9, pr/no-changelog, type/ci

#10161 Update a couple dependencies
  .changelog/10161.txt
  agent/consul/server.go
  agent/consul/wanfed/wanfed.go
  go.mod
  go.sum
  vendor/github.com/armon/go-metrics/inmem.go
  vendor/github.com/hashicorp/memberlist/net.go
  vendor/github.com/hashicorp/memberlist/transport.go
  vendor/github.com/hashicorp/memberlist/util.go
  vendor/github.com/hashicorp/raft/api.go
  vendor/github.com/hashicorp/raft/configuration.go
  vendor/github.com/hashicorp/raft/raft.go
  vendor/modules.txt
Labels: backport/1.10, backport/1.8, backport/1.9, pr/dependencies

#9981 Unix Domain Socket support for upstreams and downstreams
  .changelog/9981.txt
  agent/agent_endpoint_test.go
  agent/config/builder.go
  agent/config/builder_test.go
  agent/config/config.go
  agent/config/runtime_test.go
  agent/config/testdata/full-config.hcl
  agent/config/testdata/full-config.json
  agent/proxycfg/manager_test.go
  agent/proxycfg/state.go
  agent/proxycfg/testing.go
  agent/sidecar_service.go
  agent/structs/connect_proxy_config.go
  agent/structs/service_definition.go
  agent/structs/structs.go
  agent/structs/structs_filtering_test.go
  agent/structs/structs_test.go
  agent/structs/testing_connect_proxy_config.go
  agent/xds/clusters.go
  agent/xds/clusters_test.go
  agent/xds/endpoints.go
  agent/xds/listeners.go
  agent/xds/listeners_test.go
  agent/xds/response.go
  agent/xds/testdata/clusters/downstream-service-with-unix-sockets.envoy-1-18-x.golden
  agent/xds/testdata/clusters/downstream-service-with-unix-sockets.v2compat.envoy-1-16-x.golden
  agent/xds/testdata/listeners/listener-unix-domain-socket.envoy-1-18-x.golden
  agent/xds/testdata/listeners/listener-unix-domain-socket.v2compat.envoy-1-16-x.golden
  api/agent.go
  command/connect/proxy/flag_upstreams.go
  command/connect/proxy/proxy.go
  connect/proxy/config.go
  connect/proxy/proxy.go
  proto/pbservice/service.gen.go
  proto/pbservice/service.pb.go
  proto/pbservice/service.proto
Labels: backport/1.10, theme/connect

#10155 config-entry: remove Kind and Name field from Mesh config entry
  agent/config/runtime_test.go
  agent/config_endpoint_test.go
  agent/consul/config_endpoint.go
  agent/consul/fsm/snapshot_oss_test.go
  agent/proxycfg/state_test.go
  agent/structs/config_entry.go
  agent/structs/config_entry_mesh.go
  agent/structs/config_entry_oss.go
  agent/structs/config_entry_test.go
  agent/xds/listeners_test.go
  api/config_entry.go
  api/config_entry_cluster.go
  api/config_entry_test.go
  command/config/write/config_write.go
  command/config/write/config_write_test.go
Labels: backport/1.10, pr/no-changelog, theme/api, theme/cli, theme/config, theme/envoy/xds

#10178 refactor(downloads): source asset from mktg-logos
  website/pages/downloads/img/consul-logo.svg
  website/pages/downloads/index.jsx
Labels: pr/no-changelog, type/docs-cherrypick

#10185 Fixup UDS failing tests.
  agent/agent_endpoint_test.go
  agent/config/runtime_test.go
  agent/config/testdata/TestRuntimeConfig_Sanitize.golden
  agent/config/testdata/full-config.hcl
  agent/config/testdata/full-config.json
  agent/structs/structs_filtering_test.go
  agent/structs/structs_test.go
  api/agent.go
  api/agent_test.go
  proto/pbservice/node.gen.go
  proto/pbservice/node.pb.go
  proto/pbservice/node.proto
  proto/pbservice/service.gen.go
Labels: backport/1.10, pr/no-changelog, theme/api, theme/config

#10191 ui: add data-enterprise-logo to logo svg for enterprise
  ui/packages/consul-ui/lib/startup/templates/body.html.js
Labels: backport/1.10, pr/no-changelog, theme/ui

#10165 testing: slightly better comparison for x509.CertPool
  connect/tls_test.go
Labels: backport/1.10, pr/no-changelog, theme/connect, theme/testing

#10189 http: set consistency header properly for health endpoint
  .changelog/10189.txt
  agent/health_endpoint.go
Labels: backport/1.10, backport/1.9, theme/health-checks, type/bug

#10047 state: reduce arguments to validateProposedConfigEntryInServiceGraph
  agent/consul/state/config_entry.go
Labels: backport/1.10, pr/no-changelog, theme/internal-cleanup

#10177 docs: remove name field from Mesh config entry
  api/config_entry_test.go
  website/content/api-docs/config.mdx
  website/content/commands/config/delete.mdx
  website/content/commands/config/list.mdx
  website/content/commands/config/read.mdx
  website/content/docs/connect/config-entries/index.mdx
  website/content/docs/connect/config-entries/mesh.mdx
Labels: backport/1.10, pr/no-changelog, type/docs, type/docs-cherrypick

#9998 K8s docs: Manual join: add note that kubeconfig not required
  website/content/docs/k8s/installation/deployment-configurations/clients-outside-kubernetes.mdx
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#10064 docs: fix api-docs namespace descriptions
  website/content/api-docs/namespaces.mdx
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#10197 website: support hidden pages in nav-data (#10180)
  website/data/api-docs-nav-data.json
  website/data/commands-nav-data.json
  website/data/docs-nav-data.json
  website/next.config.js
  website/package-lock.json
  website/package.json
  website/pages/api-docs/[[...page]].jsx
  website/pages/commands/[[...page]].jsx
  website/pages/docs/[[...page]].jsx
Labels: pr/no-changelog, type/docs

#10196 [1.9.x] Backport CI changes
  .circleci/config.yml
  .circleci/scripts/cherry-picker.sh
Labels: backport/1.8, pr/no-changelog, type/ci

#10192 Homepage Updates w/ Service Mesh & HashiStack guides
  website/components/callout-blade/CalloutBlade.module.css
  website/components/callout-blade/index.jsx
  website/components/cta-hero/img/consul-stack.svg
  website/components/cta-hero/img/cta-image.jpg
  website/components/cta-hero/index.jsx
  website/components/cta-hero/style.module.css
  website/package-lock.json
  website/package.json
  website/pages/home/img/stack/consul-and-nomad.svg
  website/pages/home/img/stack/consul-and-terraform.svg
  website/pages/home/img/stack/consul-and-vault.svg
  website/pages/home/index.jsx
  website/pages/style.css
Labels: pr/no-changelog, type/docs

#10187 Test fixes for Ent merge
  agent/config_endpoint_test.go
  agent/proxycfg/state_test.go
Labels: backport/1.10, pr/no-changelog

#10075 rpc: some cleanup of canRetry and ForwardRPC
  agent/consul/acl_endpoint.go
  agent/consul/acl_endpoint_legacy.go
  agent/consul/auto_config_endpoint.go
  agent/consul/auto_config_endpoint_test.go
  agent/consul/auto_encrypt_endpoint.go
  agent/consul/catalog_endpoint.go
  agent/consul/client.go
  agent/consul/config_endpoint.go
  agent/consul/connect_ca_endpoint.go
  agent/consul/coordinate_endpoint.go
  agent/consul/discovery_chain_endpoint.go
  agent/consul/federation_state_endpoint.go
  agent/consul/health_endpoint.go
  agent/consul/intention_endpoint.go
  agent/consul/internal_endpoint.go
  agent/consul/kvs_endpoint.go
  agent/consul/operator_autopilot_endpoint.go
  agent/consul/operator_raft_endpoint.go
  agent/consul/prepared_query_endpoint.go
  agent/consul/rpc.go
  agent/consul/rpc_test.go
  agent/consul/session_endpoint.go
  agent/consul/txn_endpoint.go
  test/integration/connect/envoy/case-basic/verify.bats
  test/integration/connect/envoy/case-http/verify.bats
Labels: backport/1.10, pr/no-changelog

#10199 docs/nia: simplify api and cli url paths
  website/content/docs/nia/api/index.mdx
  website/content/docs/nia/cli/index.mdx
  website/data/docs-nav-data.json
  website/redirects.next.js
Labels: backport/1.10, theme/consul-terraform-sync, type/docs, type/docs-cherrypick

#10198 changelog: add 1.10.0-beta2
  CHANGELOG.md
Labels: pr/no-changelog

#10186 ui: [BUGFIX] De-duplicate Tag rendering
  .changelog/10186.txt
  ui/packages/consul-ui/app/components/tag-list/README.mdx
  ui/packages/consul-ui/app/components/tag-list/index.hbs
  ui/packages/consul-ui/app/components/tag-list/index.js
  ui/packages/consul-ui/tests/acceptance/dc/services/show/tags.feature
  ui/packages/consul-ui/tests/acceptance/steps/dc/services/show/tags-steps.js
  ui/packages/consul-ui/tests/pages/dc/services/show.js
Labels: backport/1.10, backport/1.9, theme/ui, type/bug

#10181 ui: Loader amends/improvements
  .changelog/10181.txt
  ui/packages/consul-ui/app/components/app/index.scss
  ui/packages/consul-ui/app/components/brand-loader/README.mdx
  ui/packages/consul-ui/app/components/brand-loader/enterprise.hbs
  ui/packages/consul-ui/app/components/brand-loader/index.hbs
  ui/packages/consul-ui/app/components/brand-loader/index.scss
  ui/packages/consul-ui/app/components/brand-loader/layout.scss
  ui/packages/consul-ui/app/components/brand-loader/skin.scss
  ui/packages/consul-ui/app/components/consul/loader/README.mdx
  ui/packages/consul-ui/app/components/consul/loader/index.scss
  ui/packages/consul-ui/app/components/consul/loader/layout.scss
  ui/packages/consul-ui/app/components/consul/loader/skin.scss
  ui/packages/consul-ui/app/styles/base/animation/index.scss
  ui/packages/consul-ui/app/styles/base/color/base-variables.scss
  ui/packages/consul-ui/app/styles/components.scss
  ui/packages/consul-ui/app/styles/components/brand-loader.scss
  ui/packages/consul-ui/app/styles/components/brand-loader/layout.scss
  ui/packages/consul-ui/app/styles/components/loader.scss
  ui/packages/consul-ui/app/styles/components/loader/index.scss
  ui/packages/consul-ui/app/styles/debug.scss
  ui/packages/consul-ui/app/styles/layout.scss
  ui/packages/consul-ui/app/styles/variables.scss
  ui/packages/consul-ui/app/styles/variables/layout.scss
  ui/packages/consul-ui/app/styles/variables/skin.scss
  ui/packages/consul-ui/app/templates/application.hbs
  ui/packages/consul-ui/lib/startup/templates/body.html.js
Labels: backport/1.10, theme/ui

#10174 ui: Adds ability to show a 'partial' list in list-collections
  .changelog/10174.txt
  ui/packages/consul-ui/app/components/consul/intention/permission/list/index.hbs
  ui/packages/consul-ui/app/components/list-collection/index.hbs
  ui/packages/consul-ui/app/components/list-collection/index.scss
  ui/packages/consul-ui/app/components/list-collection/layout.scss
  ui/packages/consul-ui/app/components/list-collection/skin.scss
  ui/packages/consul-ui/app/styles/components.scss
  ui/packages/consul-ui/app/styles/components/list-collection.scss
Labels: backport/1.10, backport/1.9, theme/ui

#10203 Adjust order, remove titles, on HashiStack section
  website/components/callout-blade/index.jsx
  website/pages/home/index.jsx
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#10201 website: sync recent commits and 1.10.0-beta2
  website/components/callout-blade/CalloutBlade.module.css
  website/components/callout-blade/index.jsx
  website/components/cta-hero/img/consul-stack.svg
  website/components/cta-hero/img/cta-image.jpg
  website/components/cta-hero/index.jsx
  website/components/cta-hero/style.module.css
  website/package-lock.json
  website/package.json
  website/pages/home/img/stack/consul-and-nomad.svg
  website/pages/home/img/stack/consul-and-terraform.svg
  website/pages/home/img/stack/consul-and-vault.svg
  website/pages/home/index.jsx
  website/pages/style.css
Labels: pr/no-changelog, type/docs

#10202 website: bump beta callout on downloads page to 1.10.0-beta2
  website/pages/downloads/index.jsx
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#10157 ui: Fix nspace spacing issue
  .changelog/10157.txt
  ui/packages/consul-ui/app/components/consul/nspace/list/index.hbs
  ui/packages/consul-ui/app/styles/components/composite-row.scss
Labels: backport/1.10, backport/1.9, theme/ui

#10184 Retroactively update changelog to note metrics contention fixes
  CHANGELOG.md
Labels: theme/reliability

#10214 Flesh out Raft Protocol Support note
  website/content/docs/upgrading/upgrade-specific.mdx
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#10121 ui: Add conditionals to Lock Session list items
  .changelog/10121.txt
  ui/packages/consul-ui/app/components/consul/lock-session/list/index.hbs
  ui/packages/consul-ui/app/styles/components/composite-row.scss
Labels: backport/1.10, backport/1.9, theme/ui

#9995 Add graceful shutdown of client connection and WaitGroup to H2PING
  agent/checks/check.go
Labels: pr/no-changelog

#10226 Update network-infrastructure-automation.jsx
  website/pages/use-cases/network-infrastructure-automation.jsx
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#10218 [1.9.x] agent/local: do not persist the agent or user token
  .changelog/10188.txt
  agent/local/state.go
  agent/local/state_test.go
Labels: backport/1.8

#10231 connect: update supported envoy versions to 1.18.3, 1.17.3, 1.16.4, and 1.15.5
  .changelog/10231.txt
  .circleci/config.yml
  agent/xds/envoy_versioning_test.go
  agent/xds/proxysupport/proxysupport.go
  command/connect/envoy/testdata/CONSUL_HTTP_ADDR-with-https-scheme-enables-tls.golden
  command/connect/envoy/testdata/access-log-path.golden
  command/connect/envoy/testdata/defaults.golden
  command/connect/envoy/testdata/existing-ca-file.golden
  command/connect/envoy/testdata/existing-ca-path.golden
  command/connect/envoy/testdata/extra_-multiple.golden
  command/connect/envoy/testdata/extra_-single.golden
  command/connect/envoy/testdata/grpc-addr-config.golden
  command/connect/envoy/testdata/grpc-addr-env.golden
  command/connect/envoy/testdata/grpc-addr-flag.golden
  command/connect/envoy/testdata/grpc-addr-unix.golden
  command/connect/envoy/testdata/ingress-gateway-address-specified.golden
  command/connect/envoy/testdata/ingress-gateway-no-auto-register.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-and-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-without-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway.golden
  command/connect/envoy/testdata/prometheus-metrics.golden
  command/connect/envoy/testdata/stats-config-override.golden
  command/connect/envoy/testdata/token-arg.golden
  command/connect/envoy/testdata/token-env.golden
  command/connect/envoy/testdata/token-file-arg.golden
  command/connect/envoy/testdata/token-file-env.golden
  command/connect/envoy/testdata/zipkin-tracing-config.golden
  test/integration/connect/envoy/run-tests.sh
  website/content/commands/connect/envoy.mdx
  website/content/docs/connect/proxies/envoy.mdx
Labels: backport/1.10, theme/cli, theme/envoy/xds, type/ci, type/docs

#10232 [1.9.x] connect: update supported envoy versions to 1.16.4, 1.15.5, 1.14.6, and 1.13.7
  .changelog/10232.txt
  .circleci/config.yml
  agent/xds/envoy_versioning_test.go
  agent/xds/proxysupport/proxysupport.go
  command/connect/envoy/testdata/CONSUL_HTTP_ADDR-with-https-scheme-enables-tls.golden
  command/connect/envoy/testdata/access-log-path.golden
  command/connect/envoy/testdata/defaults.golden
  command/connect/envoy/testdata/existing-ca-file.golden
  command/connect/envoy/testdata/existing-ca-path.golden
  command/connect/envoy/testdata/extra_-multiple.golden
  command/connect/envoy/testdata/extra_-single.golden
  command/connect/envoy/testdata/grpc-addr-config.golden
  command/connect/envoy/testdata/grpc-addr-env.golden
  command/connect/envoy/testdata/grpc-addr-flag.golden
  command/connect/envoy/testdata/grpc-addr-unix.golden
  command/connect/envoy/testdata/ingress-gateway-address-specified.golden
  command/connect/envoy/testdata/ingress-gateway-no-auto-register.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-and-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-without-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway.golden
  command/connect/envoy/testdata/stats-config-override.golden
  command/connect/envoy/testdata/token-arg.golden
  command/connect/envoy/testdata/token-env.golden
  command/connect/envoy/testdata/token-file-arg.golden
  command/connect/envoy/testdata/token-file-env.golden
  command/connect/envoy/testdata/zipkin-tracing-config.golden
  test/integration/connect/envoy/run-tests.sh
Labels: theme/cli, theme/envoy/xds, type/ci

#10217 testing: attempt to fix some test flakes
  .circleci/config.yml
  agent/consul/acl_endpoint_test.go
  agent/testagent.go
  go.mod
  sdk/testutil/retry/retry.go
Labels: backport/1.10, backport/1.8, backport/1.9, pr/dependencies, pr/no-changelog, type/ci

#10173 Save exposed ports in agent's store and expose them via API
  .changelog/10173.txt
  agent/agent.go
  agent/agent_test.go
  agent/structs/structs.go
  agent/structs/structs_filtering_test.go
  api/agent.go
  command/connect/redirecttraffic/redirect_traffic.go
  command/connect/redirecttraffic/redirect_traffic_test.go
  proto/pbservice/healthcheck.gen.go
  proto/pbservice/healthcheck.pb.go
  proto/pbservice/healthcheck.proto
Labels: backport/1.10, theme/api

#10234 docs: correct website documentation typo
  website/pages/use-cases/network-infrastructure-automation.jsx
Labels: pr/no-changelog, type/docs-cherrypick

#10194 ui: Serf Health Check warning notice
  .changelog/10194.txt
  ui/packages/consul-ui/app/components/consul/health-check/list/README.mdx
  ui/packages/consul-ui/app/components/consul/health-check/list/index.hbs
  ui/packages/consul-ui/app/components/notice/README.mdx
  ui/packages/consul-ui/app/components/notice/README.stories.mdx
  ui/packages/consul-ui/app/components/notice/index.hbs
  ui/packages/consul-ui/app/decorators/replace.js
  ui/packages/consul-ui/app/filter/predicates/health-check.js
  ui/packages/consul-ui/app/models/health-check.js
  ui/packages/consul-ui/app/search/predicates/health-check.js
  ui/packages/consul-ui/app/styles/debug.scss
  ui/packages/consul-ui/app/templates/dc/nodes/show/healthchecks.hbs
  ui/packages/consul-ui/app/templates/dc/services/instance/healthchecks.hbs
  ui/packages/consul-ui/tests/acceptance/dc/nodes/show.feature
  ui/packages/consul-ui/tests/acceptance/dc/nodes/show/health-checks.feature
  ui/packages/consul-ui/tests/acceptance/dc/services/instances/health-checks.feature
  ui/packages/consul-ui/tests/acceptance/steps/dc/nodes/show/health-checks-steps.js
  ui/packages/consul-ui/tests/acceptance/steps/dc/services/instances/health-checks-steps.js
  ui/packages/consul-ui/tests/pages.js
  ui/packages/consul-ui/tests/pages/dc/nodes/show.js
  ui/packages/consul-ui/tests/pages/dc/services/instance.js
  ui/packages/consul-ui/translations/routes/en-us.yaml
Labels: backport/1.10, theme/ui

#10233 Update k8s fed docs to clarify role of acl token
  website/content/docs/k8s/installation/multi-cluster/vms-and-kubernetes.mdx
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#10241 Add changelog entry for network area timeout updates
  .changelog/_907.txt
Labels: backport/1.10, backport/1.7, backport/1.8, backport/1.9, pr/no-changelog

#10240 agent: ensure we hash the non-deprecated upstream fields on ServiceConfigRequest
  .changelog/10240.txt
  agent/structs/config_entry.go
  agent/structs/config_entry_test.go
Labels: backport/1.10, backport/1.8, backport/1.9, type/bug

#10239 server: ensure that central service config flattening properly resets the state each time
  .changelog/10239.txt
  agent/consul/config_endpoint.go
  agent/consul/config_endpoint_test.go
  agent/structs/config_entry.go
Labels: backport/1.10, backport/1.8, backport/1.9, type/bug

#10244 [1.9.x] agent: ensure we hash the non-deprecated upstream fields on ServiceConfigRequest
  .changelog/10240.txt
  agent/structs/config_entry.go
  agent/structs/config_entry_test.go
Labels: backport/1.8, pr/no-changelog

#10245 [1.9.x] server: ensure that central service config flattening properly resets the state each time
  .changelog/10239.txt
  agent/consul/config_endpoint.go
  agent/consul/config_endpoint_test.go
  agent/structs/config_entry.go
Labels: backport/1.8

#10243 xds: emit a labeled gauge of connected xDS streams by version
  .changelog/10243.txt
  agent/setup.go
  agent/xds/delta.go
  agent/xds/delta_test.go
  agent/xds/server.go
  agent/xds/server_test.go
  agent/xds/xds_protocol_helpers_test.go
  website/content/docs/agent/telemetry.mdx
Labels: backport/1.10

#10237 ui: Use babel plugin to strip calls to runInDebug
  ui/packages/consul-ui/ember-cli-build.js
  ui/packages/consul-ui/package.json
  ui/yarn.lock
Labels: backport/1.10, pr/no-changelog, theme/ui

#10236 docs/nia: Add section on upgrading Terraform in CTS
  website/content/docs/nia/network-drivers.mdx
Labels: pr/no-changelog, theme/consul-terraform-sync, type/docs

#10230 docs: updated the standard upgrade process
  website/content/docs/upgrading/index.mdx
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#10251 Updates AlertBanner for HashiConf EU
  website/data/alert-banner.js
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#10238 ui: Bump node to v14
  .circleci/config.yml
  build-support/docker/Build-UI.dockerfile
  ui/package.json
  ui/packages/consul-ui/.nvmrc
  ui/packages/consul-ui/docs/upgrades.mdx
  ui/packages/consul-ui/package.json
Labels: backport/1.10, pr/no-changelog, theme/ui, type/ci

#8812 GH-8728 add raft default values
  .changelog/8812.txt
  agent/config/default.go
Labels: backport/1.10, backport/1.8, backport/1.9, theme/internals

#10255 chore(website): 'overview' nav item links to home page
  website/data/subnav.js
Labels: type/docs, type/docs-cherrypick

#10225 ui: Miscellaneous Lock Session fixes
  .changelog/10225.txt
  ui/packages/consul-ui/app/components/consul/lock-session/form/index.hbs
  ui/packages/consul-ui/app/components/consul/lock-session/list/index.hbs
  ui/packages/consul-ui/app/components/consul/lock-session/list/index.scss
  ui/packages/consul-ui/app/models/session.js
  ui/packages/consul-ui/app/styles/components.scss
  ui/packages/consul-ui/app/styles/components/composite-row.scss
  ui/packages/consul-ui/mock-api/v1/session/info/_
  ui/packages/consul-ui/mock-api/v1/session/node/_
Labels: backport/1.10, backport/1.9, theme/ui

#10253 redirecttraffic: fix a flaky test
  command/connect/redirecttraffic/redirect_traffic_test.go
Labels: backport/1.10, pr/no-changelog, theme/cli

#10260 ci: update terraform provider versions to within constraints
  .circleci/terraform/load-test/.terraform.lock.hcl
Labels: pr/load-test, pr/no-changelog

#10261 docs: update register check docs (closes #6635)
  website/content/api-docs/agent/check.mdx
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#10269 ui: Adds QUnit toggle bookmarklet to our docs
  ui/packages/consul-ui/docs/bookmarklets.mdx
Labels: pr/no-changelog, theme/ui

#10266 Fix doc note since we switched authorization mechanism in 1.9
  website/content/docs/connect/proxies/envoy.mdx
Labels: type/docs, type/docs-cherrypick

#9309 docs: Add example ACL policy for snapshot agent
  website/content/commands/snapshot/agent.mdx
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#10210 Add OSS bits for supporting specifying the enterprise license via config
  .changelog/10210.txt
  agent/config/builder_oss.go
  agent/config/builder_oss_test.go
  agent/config/config.go
  agent/config/runtime_oss_test.go
  agent/config/testdata/full-config.hcl
  agent/config/testdata/full-config.json
Labels: backport/1.10, theme/config

#10268 Add link for new Cisco TF module
  website/content/docs/nia/installation/requirements.mdx
Labels: theme/consul-terraform-sync, type/docs, type/docs-cherrypick

#10211 Deprecate API driven licensing
  .changelog/10211.txt
  api/operator_license.go
Labels: backport/1.10, theme/api

#10272 Backport some ent changes for serf tags
  .changelog/_917.txt
  agent/consul/client_serf.go
  agent/consul/enterprise_client_oss.go
  agent/consul/enterprise_server_oss.go
  agent/consul/replication.go
  agent/consul/server_serf.go
  agent/metadata/server.go
  agent/metadata/server_test.go
Labels: backport/1.10, backport/1.8, backport/1.9

#10278 ci: allow bash_env in load-test
  .circleci/config.yml
  .circleci/terraform/load-test/main.tf
  .circleci/terraform/load-test/variables.tf
Labels: pr/no-changelog, type/ci

#10277 [1.8.x] Backport some ent changes for serf tags
  .changelog/_917.txt
  agent/consul/client_serf.go
  agent/consul/enterprise_client_oss.go
  agent/consul/enterprise_server_oss.go
  agent/consul/replication.go
  agent/consul/server_serf.go
  agent/metadata/server.go
  agent/metadata/server_test.go
Labels: pr/no-changelog

#10280 docs: fix Amazon EKS service name
  website/content/docs/k8s/index.mdx
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#10257 [Backport/1.9.x] Backport #10225
  .changelog/10225.txt
  ui/packages/consul-ui/app/components/consul/lock-session/form/index.hbs
  ui/packages/consul-ui/app/components/consul/lock-session/list/index.hbs
  ui/packages/consul-ui/app/components/consul/lock-session/list/index.scss
  ui/packages/consul-ui/app/models/session.js
  ui/packages/consul-ui/app/styles/components.scss
  ui/packages/consul-ui/app/styles/components/composite-row.scss
  ui/packages/consul-ui/mock-api/v1/session/info/_
  ui/packages/consul-ui/mock-api/v1/session/node/_
Labels: theme/ui

#10090 Update brand assets (1.9.x)
  .changelog/10090.txt
  ui/packages/consul-ui/app/components/consul/logo/index.hbs
  ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs
  ui/packages/consul-ui/app/styles/base/icons/base-variables.scss
  ui/packages/consul-ui/app/styles/components/brand-loader.scss
  ui/packages/consul-ui/app/styles/components/brand-loader/layout.scss
  ui/packages/consul-ui/app/styles/components/main-header-horizontal/layout.scss
  ui/packages/consul-ui/lib/startup/templates/body.html.js
  ui/packages/consul-ui/lib/startup/templates/head.html.js
  ui/packages/consul-ui/public/assets/android-chrome-192x192.png
  ui/packages/consul-ui/public/assets/android-chrome-512x512.png
  ui/packages/consul-ui/public/assets/apple-touch-icon-114x114.png
  ui/packages/consul-ui/public/assets/apple-touch-icon-120x120.png
  ui/packages/consul-ui/public/assets/apple-touch-icon-144x144.png
  ui/packages/consul-ui/public/assets/apple-touch-icon-152x152.png
  ui/packages/consul-ui/public/assets/apple-touch-icon-57x57.png
  ui/packages/consul-ui/public/assets/apple-touch-icon-60x60.png
  ui/packages/consul-ui/public/assets/apple-touch-icon-72x72.png
  ui/packages/consul-ui/public/assets/apple-touch-icon-76x76.png
  ui/packages/consul-ui/public/assets/apple-touch-icon.png
  ui/packages/consul-ui/public/assets/consul-logo.png
  ui/packages/consul-ui/public/assets/favicon-128.png
  ui/packages/consul-ui/public/assets/favicon-16x16.png
  ui/packages/consul-ui/public/assets/favicon-196x196.png
  ui/packages/consul-ui/public/assets/favicon-32x32.png
  ui/packages/consul-ui/public/assets/favicon-96x96.png
  ui/packages/consul-ui/public/assets/favicon.ico
  ui/packages/consul-ui/public/assets/favicon.png
  ui/packages/consul-ui/public/assets/favicon.svg
  ui/packages/consul-ui/public/assets/mstile-144x144.png
  ui/packages/consul-ui/public/assets/mstile-150x150.png
  ui/packages/consul-ui/public/assets/mstile-310x150.png
  ui/packages/consul-ui/public/assets/mstile-310x310.png
  ui/packages/consul-ui/public/assets/mstile-70x70.png
  ui/packages/consul-ui/public/assets/safari-pinned-tab.svg
Labels: backport/1.8, theme/ui

#10259 ui: change coloring of secondary navigation elements
  ui/packages/consul-ui/app/components/tab-nav/README.mdx
  ui/packages/consul-ui/app/components/tab-nav/index.scss
  ui/packages/consul-ui/app/components/tab-nav/skin.scss
Labels: backport/1.10, backport/1.9, pr/no-changelog, theme/ui

#10223 Preparation for changing where license management is done.
  agent/agent.go
  agent/agent_oss.go
  agent/agent_test.go
  agent/consul/client.go
  agent/consul/client_test.go
  agent/consul/enterprise_client_oss.go
  agent/consul/enterprise_server_oss.go
  agent/consul/enterprise_server_oss_test.go
  agent/consul/options.go
  agent/consul/options_oss.go
  agent/consul/server.go
  agent/routine-leak-checker/leak_test.go
  agent/setup.go
  agent/setup_oss.go
  sdk/testutil/context.go
Labels: backport/1.10

#10284 [Backport Revert 1.9.x] Revert of auto backport #10259
  ui/packages/consul-ui/app/components/tab-nav/README.mdx
  ui/packages/consul-ui/app/components/tab-nav/index.scss
  ui/packages/consul-ui/app/components/tab-nav/skin.scss
Labels: theme/ui

#10248 Prepare for adding license auto-retrieval to auto-config in enterprise
  .changelog/10248.txt
  agent/agent.go
  agent/auto-config/auto_config.go
  agent/auto-config/auto_config_oss.go
  agent/auto-config/auto_config_oss_test.go
  agent/auto-config/auto_config_test.go
  agent/auto-config/auto_encrypt.go
  agent/auto-config/auto_encrypt_test.go
  agent/auto-config/config.go
  agent/auto-config/config_oss.go
  agent/auto-config/mock_oss_test.go
  agent/auto-config/mock_test.go
  agent/consul/client.go
  agent/consul/config.go
  agent/setup.go
  agent/setup_oss.go
  sdk/testutil/testlog.go
  test/integration/connect/envoy/run-tests.sh
Labels: backport/1.10

#10074 Updating Consul Glossary with more industry standard terms
  website/content/docs/install/glossary.mdx
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#10276 upgrade golangci-lint to v1.40.1
  .circleci/config.yml
  GNUmakefile
  agent/dns.go
Labels: pr/no-changelog, type/ci

#10267 Move some things around to allow for license updating via config reload
  .changelog/10267.txt
  agent/agent.go
  agent/config/config.go
  agent/consul/acl_token_exp.go
  agent/consul/enterprise_server_oss.go
  agent/consul/leader.go
  agent/consul/leader_connect.go
  agent/consul/leader_connect_ca.go
  agent/consul/leader_federation_state_ae.go
  agent/consul/leader_intentions.go
  agent/consul/replication_test.go
  agent/consul/server.go
  agent/setup.go
  agent/setup_oss.go
  agent/testagent.go
  lib/routine/routine.go
  lib/routine/routine_test.go
Labels: backport/1.10, theme/config, theme/internals

#10290 docs: rename enterprise to Consul enterprise
  website/content/docs/enterprise/index.mdx
  website/data/docs-nav-data.json
Labels: type/docs, type/docs-cherrypick

#10293 Update Kubernetes docs to point to install pages.
  website/content/docs/k8s/installation/install.mdx
Labels: pr/no-changelog, theme/kubernetes, type/docs, type/docs-cherrypick

#10289 Add readme for network area implementation
  contributing/README.md
  contributing/network-areas/README.md
Labels: pr/no-changelog

#10295 ui: Minor CSS tweaks/layout fixes
  ui/packages/consul-ui/app/components/app-view/layout.scss
  ui/packages/consul-ui/app/styles/routes/dc/services/index.scss
Labels: backport/1.10, pr/no-changelog, theme/ui

#10254 ui: Routlet Params
  ui/packages/consul-ui/app/components/route/README.mdx
  ui/packages/consul-ui/app/components/route/index.hbs
  ui/packages/consul-ui/app/components/route/index.js
  ui/packages/consul-ui/app/services/routlet.js
  ui/packages/consul-ui/app/utils/routing/transitionable.js
Labels: theme/ui

#10287 ui: Unix Domain Socket support
  .changelog/10287.txt
  ui/packages/consul-ui/app/components/consul/service-instance/list/index.hbs
  ui/packages/consul-ui/app/components/consul/upstream-instance/list/index.hbs
  ui/packages/consul-ui/app/models/service-instance.js
  ui/packages/consul-ui/app/styles/components/icon-definition.scss
  ui/packages/consul-ui/mock-api/v1/catalog/connect/_
  ui/packages/consul-ui/mock-api/v1/health/service/_
Labels: backport/1.10, theme/ui

#10288 Consul ecs docs
  website/content/docs/ecs/architecture.mdx
  website/content/docs/ecs/get-started/install.mdx
  website/content/docs/ecs/get-started/requirements.mdx
  website/content/docs/ecs/index.mdx
  website/data/docs-nav-data.json
  website/public/img/consul-ecs-arch.png
  website/public/img/ecs-task-startup.png
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#10300 Add tech preview label
  website/data/docs-nav-data.json
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#10302 Avoid adding original_dst filter when not needed
  .changelog/10302.txt
  agent/xds/listeners.go
  agent/xds/testdata/listeners/transparent-proxy-catalog-destinations-only.envoy-1-18-x.golden
  agent/xds/testdata/listeners/transparent-proxy-catalog-destinations-only.v2compat.envoy-1-16-x.golden
Labels: backport/1.10, theme/envoy/xds

#10301 Ensure passthrough clusters can be created
  .changelog/10301.txt
  agent/xds/clusters.go
  agent/xds/clusters_test.go
  agent/xds/testdata/clusters/transparent-proxy catalog destinations only.envoy-1-18-x.golden
  agent/xds/testdata/clusters/transparent-proxy catalog destinations only.v2compat.envoy-1-16-x.golden
Labels: backport/1.10, theme/envoy/xds

#10303 build: ensure each tool is built separately
  GNUmakefile
Labels: pr/no-changelog

#10305 changelog: add entry for network areas WAN config fix
  .changelog/_923.txt
Labels: backport/1.10, backport/1.9, pr/no-changelog

#10296 ui: Fixup prettier for scss files and run
  ui/packages/consul-ui/app/components/app-view/index.scss
  ui/packages/consul-ui/app/components/app/index.scss
  ui/packages/consul-ui/app/components/collapsible-notices/index.scss
  ui/packages/consul-ui/app/components/consul/auth-method/index.scss
  ui/packages/consul-ui/app/components/consul/discovery-chain/layout.scss
  ui/packages/consul-ui/app/components/consul/intention/form/fieldsets/layout.scss
  ui/packages/consul-ui/app/components/consul/intention/form/index.scss
  ui/packages/consul-ui/app/components/consul/intention/list/index.scss
  ui/packages/consul-ui/app/components/consul/intention/permission/form/layout.scss
  ui/packages/consul-ui/app/components/consul/intention/permission/form/skin.scss
  ui/packages/consul-ui/app/components/consul/intention/permission/header/list/index.scss
  ui/packages/consul-ui/app/components/consul/intention/permission/header/list/skin.scss
  ui/packages/consul-ui/app/components/consul/lock-session/form/index.scss
  ui/packages/consul-ui/app/components/consul/lock-session/list/index.scss
  ui/packages/consul-ui/app/components/filter-bar/layout.scss
  ui/packages/consul-ui/app/components/filter-bar/skin.scss
  ui/packages/consul-ui/app/components/hashicorp-consul/index.scss
  ui/packages/consul-ui/app/components/main-nav-vertical/index.scss
  ui/packages/consul-ui/app/components/main-nav-vertical/layout.scss
  ui/packages/consul-ui/app/components/main-nav-vertical/skin.scss
  ui/packages/consul-ui/app/components/menu-panel/skin.scss
  ui/packages/consul-ui/app/components/modal-dialog/index.scss
  ui/packages/consul-ui/app/components/modal-dialog/layout.scss
  ui/packages/consul-ui/app/components/notice/index.scss
  ui/packages/consul-ui/app/components/overlay/none.scss
  ui/packages/consul-ui/app/components/overlay/square-tail.scss
  ui/packages/consul-ui/app/components/search-bar/index.scss
  ui/packages/consul-ui/app/components/skip-links/index.scss
  ui/packages/consul-ui/app/components/skip-links/layout.scss
  ui/packages/consul-ui/app/components/skip-links/skin.scss
  ui/packages/consul-ui/app/components/tooltip/index.scss
  ui/packages/consul-ui/app/components/topology-metrics/card/index.scss
  ui/packages/consul-ui/app/components/topology-metrics/layout.scss
  ui/packages/consul-ui/app/components/topology-metrics/popover/index.scss
  ui/packages/consul-ui/app/components/topology-metrics/series/layout.scss
  ui/packages/consul-ui/app/components/topology-metrics/series/skin.scss
  ui/packages/consul-ui/app/components/topology-metrics/source-type/index.scss
  ui/packages/consul-ui/app/components/topology-metrics/stats/index.scss
  ui/packages/consul-ui/app/components/topology-metrics/status/index.scss
  ui/packages/consul-ui/package.json
Labels: backport/1.10, pr/no-changelog, theme/ui

#10273 debug: remove the CLI check for debug_enabled
  .changelog/10273.txt
  agent/http.go
  api/debug.go
  command/debug/debug.go
  command/debug/debug_test.go
Labels: theme/api, theme/cli

#10292 ui: Move intention form description field
  ui/packages/consul-ui/app/components/consul/intention/form/fieldsets/index.hbs
Labels: backport/1.10, backport/1.9, pr/no-changelog, theme/ui

#10294 backport(1.8.x): CI release branch auto backport
  .circleci/config.yml
  .circleci/scripts/cherry-picker.sh
Labels: pr/no-changelog, type/ci

#10309 docs: Bump core downloads to beta3
  website/pages/downloads/index.jsx
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#10306 Bump raft-autopilot version to the latest.
  .changelog/10306.txt
  go.mod
  go.sum
  vendor/github.com/hashicorp/raft-autopilot/autopilot.go
  vendor/github.com/hashicorp/raft-autopilot/run.go
  vendor/github.com/hashicorp/raft-autopilot/state.go
  vendor/github.com/hashicorp/raft-autopilot/types.go
  vendor/modules.txt
Labels: backport/1.10, backport/1.9, pr/dependencies

#10310 [1.9.x] Backport #10306
  .changelog/10306.txt
  go.mod
  go.sum
  vendor/github.com/hashicorp/raft-autopilot/autopilot.go
  vendor/github.com/hashicorp/raft-autopilot/run.go
  vendor/github.com/hashicorp/raft-autopilot/state.go
  vendor/github.com/hashicorp/raft-autopilot/types.go
  vendor/modules.txt
Labels: pr/dependencies, pr/no-changelog

#10304 Add note about new ECS ARN format to ECS docs
  website/content/docs/ecs/get-started/install.mdx
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#10312 fix(website): update node version to latest LTS for website
  website/Dockerfile
Labels: pr/no-changelog, type/docs

#10313 ui: Fix broken link format in ECS install page
  website/content/docs/ecs/get-started/install.mdx
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#10317 docs: Fix agent token name under ACL Agent Token
  website/content/docs/security/acl/acl-system.mdx
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#10321 [1.9.x] debug: remove the CLI check for debug_enabled
  .changelog/10273.txt
  agent/http.go
  api/debug.go
  command/debug/debug.go
  command/debug/debug_test.go
Labels: backport/1.7, backport/1.8, theme/api, theme/cli
