Repository hashicorp/consul, pull requests merged in 2021-12, with the labels that each got.

#11656 ui: Don't show policy datacenter selector for non-default partitions
  .changelog/11656.txt
  ui/packages/consul-ui/app/components/policy-form/index.hbs
Labels: theme/ui

#11654 ui: Add `Service.Partition` as available variable for dashboard urls
  .changelog/11654.txt
  ui/packages/consul-ui/app/templates/dc/services/show.hbs
  ui/packages/consul-ui/app/templates/dc/services/show/topology.hbs
  website/content/docs/agent/options.mdx
  website/content/docs/connect/observability/ui-visualization.mdx
Labels: type/docs, theme/ui

#11666 ui: Refactor KV and Lock Sessions following partitions update
  .changelog/11666.txt
  ui/packages/consul-ui/app/components/composite-row/index.scss
  ui/packages/consul-ui/app/components/composite-row/layout.scss
  ui/packages/consul-ui/app/components/composite-row/skin.scss
  ui/packages/consul-ui/app/components/consul/lock-session/form/README.mdx
  ui/packages/consul-ui/app/components/consul/lock-session/form/index.hbs
  ui/packages/consul-ui/app/components/consul/lock-session/form/index.js
  ui/packages/consul-ui/app/components/consul/lock-session/form/index.scss
  ui/packages/consul-ui/app/components/consul/lock-session/list/README.mdx
  ui/packages/consul-ui/app/components/consul/lock-session/list/index.hbs
  ui/packages/consul-ui/app/components/consul/lock-session/list/index.js
  ui/packages/consul-ui/app/components/consul/lock-session/list/index.scss
  ui/packages/consul-ui/app/components/consul/lock-session/notifications/index.hbs
  ui/packages/consul-ui/app/components/data-loader/chart.xstate.js
  ui/packages/consul-ui/app/components/data-loader/index.hbs
  ui/packages/consul-ui/app/components/data-loader/index.js
  ui/packages/consul-ui/app/components/data-writer/index.hbs
  ui/packages/consul-ui/app/components/definition-table/layout.scss
  ui/packages/consul-ui/app/components/list-collection/index.hbs
  ui/packages/consul-ui/app/components/list-row/layout.scss
  ui/packages/consul-ui/app/components/list-row/skin.scss
  ui/packages/consul-ui/app/routes/dc/nodes/show/sessions.js
  ui/packages/consul-ui/app/serializers/kv.js
  ui/packages/consul-ui/app/serializers/session.js
  ui/packages/consul-ui/app/styles/layout.scss
  ui/packages/consul-ui/app/styles/routes/dc/kv/index.scss
  ui/packages/consul-ui/app/styles/routes/dc/nodes/index.scss
  ui/packages/consul-ui/app/styles/typography.scss
  ui/packages/consul-ui/app/templates/dc/kv/edit.hbs
  ui/packages/consul-ui/app/templates/dc/nodes/show/sessions.hbs
  ui/packages/consul-ui/mock-api/v1/session/info/_
  ui/packages/consul-ui/tests/acceptance/dc/kvs/sessions/invalidate.feature
Labels: theme/ui

#11681 ui: Don't cache event sources following a 401
  .changelog/11681.txt
  ui/packages/consul-ui/app/services/data-source/service.js
  ui/packages/consul-ui/app/utils/dom/event-source/callable.js
Labels: theme/ui, backport/1.8, backport/1.9, backport/1.10

#11700 agent: Backport partitioned IDs for updateSyncState
  .changelog/11700.txt
  agent/local/state.go
  agent/structs/catalog.go
  agent/structs/catalog_oss.go
Labels: pr/no-changelog

#11701 Update config.yml to link to consul-k8s instead of consul-helm
  .github/ISSUE_TEMPLATE/config.yml
Labels: theme/contributing, pr/no-changelog

#11699 auto-config: ensure the feature works properly with partitions
  .changelog/11699.txt
  agent/agent_test.go
  agent/auto-config/auto_config.go
  agent/auto-config/config_translate.go
  agent/auto-config/tls.go
  agent/config/builder.go
  agent/connect/uri.go
  agent/connect/uri_test.go
  agent/consul/auto_config_backend.go
  agent/consul/auto_config_backend_test.go
  agent/consul/auto_config_endpoint.go
  agent/consul/auto_config_endpoint_test.go
  proto/pbautoconf/auto_config.pb.go
  proto/pbautoconf/auto_config.proto
  proto/pbautoconf/auto_config_oss.go
  proto/pbconfig/config.pb.go
  proto/pbconfig/config.proto
  website/content/docs/agent/options.mdx
Labels: type/docs, theme/config, theme/connect

#11703 ENT to OSS sync
  agent/acl_endpoint_test.go
  agent/consul/intention_endpoint.go
  agent/consul/status_endpoint_test.go
Labels: pr/no-changelog

#11665 Rename `master` and `agent_master` ACL tokens in the config file format
  .changelog/11665.txt
  agent/auto-config/config_translate.go
  agent/auto-config/config_translate_test.go
  agent/config/builder.go
  agent/config/builder_oss_test.go
  agent/config/config.go
  agent/config/deprecated.go
  agent/config/deprecated_test.go
  agent/config/runtime.go
  agent/config/runtime_test.go
  agent/config/testdata/full-config.hcl
  agent/config/testdata/full-config.json
  website/content/api-docs/acl/index.mdx
  website/content/docs/agent/options.mdx
  website/content/docs/security/acl/acl-rules.mdx
  website/content/docs/security/acl/acl-system.mdx
Labels: type/docs, theme/config

#11710 fix changelog file name
  .changelog/_1368.txt
Labels: pr/no-changelog

#11669 Rename `agent_master` ACL token in the API and CLI
  .changelog/11669.txt
  agent/agent_endpoint.go
  agent/agent_endpoint_test.go
  api/agent.go
  api/agent_test.go
  command/acl/agenttokens/agent_tokens.go
  command/acl/agenttokens/agent_tokens_test.go
  website/content/api-docs/agent/index.mdx
  website/content/commands/acl/set-agent-token.mdx
Labels: type/docs, theme/api, theme/cli

#11693 add MustRevalidate flag to connect_ca_leaf cache type; always use on non-blocking queries
  .changelog/11693.txt
  agent/agent_endpoint.go
  agent/agent_endpoint_test.go
  agent/cache-types/connect_ca_leaf.go
Labels: theme/certificates, backport/1.9, backport/1.10

#11677 sdk: use t.Cleanup in freeport and remove unnecessary calls
  agent/acl_endpoint_test.go
  agent/agent_test.go
  agent/connect/ca/testing.go
  agent/consul/acl_endpoint_test.go
  agent/consul/authmethod/kubeauth/testing.go
  agent/consul/authmethod/ssoauth/sso_test.go
  agent/consul/client_test.go
  agent/consul/operator_raft_endpoint_test.go
  agent/consul/server_test.go
  agent/grpc/client_test.go
  agent/grpc/server_test.go
  agent/testagent.go
  command/login/login_test.go
  command/snapshot/save/snapshot_save_test.go
  connect/proxy/listener_test.go
  connect/proxy/proxy_test.go
  connect/proxy/testing.go
  connect/testing.go
  internal/go-sso/oidcauth/oidcauthtest/testing.go
  lib/testing_httpserver.go
  sdk/freeport/freeport.go
  sdk/testutil/server.go
  sdk/testutil/types.go
Labels: theme/cli, theme/connect, theme/internals, pr/no-changelog

#11671 ca: fix storing the leaf signing cert with Vault provider
  .changelog/11671.txt
  agent/consul/leader_connect_ca.go
  agent/consul/leader_connect_test.go
  agent/structs/connect_ca.go
Labels: type/bug, backport/1.9, backport/1.10

#11713 ca: make test naming consistent
  agent/consul/leader_connect_ca.go
  agent/consul/leader_connect_ca_test.go
  agent/consul/leader_connect_test.go
  agent/consul/server_test.go
Labels: theme/internal-cleanup, backport/1.9, pr/no-changelog, backport/1.10

#11672 ca: set the correct SigningKeyID after config update with Vault provider
  .changelog/11672.txt
  agent/consul/leader_connect_ca.go
  agent/consul/leader_connect_ca_test.go
Labels: type/bug, theme/certificates, backport/1.9, backport/1.10

#11722 agent: add variation of force-leave that exclusively works on the WAN
  .changelog/11722.txt
  agent/agent.go
  agent/agent_endpoint.go
  agent/agent_endpoint_test.go
  agent/consul/server.go
  agent/consul/server_oss.go
  api/agent.go
  command/forceleave/forceleave.go
Labels: theme/api, theme/cli

#11392 website: bump deps to fix print styles
  website/package-lock.json
  website/package.json
  website/pages/print.css
Labels: type/docs, type/docs-cherrypick, pr/no-changelog

#11569 Groundwork for exposing when queries are filtered by ACLs
  .changelog/11569.txt
  agent/consul/acl.go
  agent/consul/acl_endpoint.go
  agent/consul/internal_endpoint.go
  agent/consul/internal_endpoint_test.go
  agent/consul/prepared_query_endpoint.go
  agent/consul/rpc.go
  agent/consul/rpc_test.go
  agent/consul/snapshot_endpoint.go
  agent/consul/txn_endpoint.go
  agent/consul/txn_endpoint_test.go
  agent/http.go
  agent/http_test.go
  agent/structs/protobuf_compat.go
  agent/structs/structs.go
  agent/structs/structs_test.go
  api/api.go
  api/api_test.go
  proto/pbcommon/common.pb.go
  proto/pbcommon/common.proto
Labels: type/enhancement, theme/api

#11629 docs: `X-Consul-Results-Filtered-By-ACLs` header
  website/content/api-docs/index.mdx
Labels: type/docs, pr/no-changelog

#11602 health: support `ResultsFilteredByACLs` flag/header
  agent/consul/acl.go
  agent/consul/acl_test.go
  agent/consul/catalog_endpoint_test.go
  agent/consul/health_endpoint.go
  agent/consul/health_endpoint_test.go
Labels: pr/no-changelog

#11593 kv: support `ResultsFilteredByACLs` flag/header
  agent/consul/kvs_endpoint.go
  agent/consul/kvs_endpoint_test.go
Labels: pr/no-changelog

#11616 event: support `X-Consul-Results-Filtered-By-ACLs` header in list endpoint
  agent/event_endpoint.go
  agent/event_endpoint_test.go
Labels: pr/no-changelog

#11621 config: support `ResultsFilteredByACLs` in list/list all endpoints
  agent/consul/config_endpoint.go
  agent/consul/config_endpoint_test.go
Labels: pr/no-changelog

#11726 Cross port of ent #1383
  agent/consul/acl_endpoint.go
  agent/consul/acl_endpoint_oss.go
  agent/structs/acl_oss.go
Labels: pr/no-changelog

#11723 update connect ca leaf endpoint docs
  website/content/api-docs/agent/connect.mdx
Labels: type/docs, pr/no-changelog

#11612 intention: support `ResultsFilteredByACLs` flag/header
  agent/consul/acl.go
  agent/consul/acl_test.go
  agent/consul/intention_endpoint.go
  agent/consul/intention_endpoint_test.go
Labels: pr/no-changelog

#11734 sessions partitioning tests
  agent/consul/state/catalog.go
  agent/consul/state/session.go
  agent/consul/state/session_oss.go
  agent/consul/state/state_store_test.go
Labels: pr/no-changelog

#11610 agent: support `X-Consul-Results-Filtered-By-ACLs` header in agent-local endpoints
  agent/acl.go
  agent/acl_oss.go
  agent/acl_test.go
  agent/agent_endpoint.go
  agent/agent_endpoint_test.go
Labels: pr/no-changelog

#11632 txn: support `ResultsFilteredByACLs` flag in `Read` endpoint
  agent/consul/txn_endpoint.go
  agent/consul/txn_endpoint_test.go
Labels: pr/no-changelog

#11606 sessions: support `ResultsFilteredByACLs` flag/header
  agent/consul/acl.go
  agent/consul/acl_test.go
  agent/consul/session_endpoint_test.go
Labels: pr/no-changelog

#11458 added Alternative Domain section to dns page in docs
  website/content/docs/discovery/dns.mdx
Labels: type/docs, type/docs-cherrypick

#11617 coordinate: support `ResultsFilteredByACLs` flag/header
  agent/consul/acl.go
  agent/consul/acl_test.go
  agent/consul/coordinate_endpoint_test.go
Labels: pr/no-changelog

#11594 catalog: support `ResultsFilteredByACLs` flag/header
  agent/consul/acl.go
  agent/consul/acl_test.go
  agent/consul/catalog_endpoint.go
  agent/consul/catalog_endpoint_test.go
  agent/consul/internal_endpoint.go
Labels: pr/no-changelog

#11644 fedstate: support `ResultsFilteredByACLs` flag/header
  agent/consul/acl.go
  agent/consul/acl_test.go
  agent/consul/federation_state_endpoint_test.go
Labels: pr/no-changelog

#11720 Use bbolt instead of the legacy bolt implementation
  .changelog/11720.txt
  agent/agent.go
  agent/config/builder.go
  agent/config/config.go
  agent/config/runtime.go
  agent/config/runtime_test.go
  agent/config/testdata/TestRuntimeConfig_Sanitize.golden
  agent/config/testdata/full-config.hcl
  agent/config/testdata/full-config.json
  agent/consul/config.go
  agent/consul/server.go
  go.mod
  go.sum
Labels: theme/config, pr/dependencies

#11736 session timers partition
  agent/consul/session_endpoint.go
  agent/consul/session_ttl.go
  agent/consul/session_ttl_test.go
  agent/consul/state/session_oss.go
Labels: pr/no-changelog

#11620 query: support `ResultsFilteredByACLs` in query list endpoint
  agent/consul/acl.go
  agent/consul/acl_test.go
  agent/consul/prepared_query_endpoint.go
  agent/consul/prepared_query_endpoint_test.go
Labels: pr/no-changelog

#11643 internal: support `ResultsFilteredByACLs` flag/header
  agent/consul/acl.go
  agent/consul/acl_test.go
  agent/consul/internal_endpoint.go
  agent/consul/internal_endpoint_test.go
Labels: pr/no-changelog

#11682 Rename partition CLI command
  website/content/commands/admin-partition.mdx
Labels: type/docs, pr/no-changelog

#11737 Rename internal references for admin partitions to be "partition"
  .changelog/11737.txt
  api/partition.go
  test/integration/connect/envoy/run-tests.sh
Labels: theme/api

#11645 types: add types/tls.go for strongly-typed TLS versions and cipher suites
  .changelog/11645.txt
  types/tls.go
  types/tls_test.go
Labels: theme/internals

#11738 Transparent proxy support for cross-partition
  .changelog/11738.txt
  agent/consul/catalog_endpoint.go
  agent/consul/fsm/snapshot_oss_test.go
  agent/consul/state/catalog.go
  agent/consul/state/catalog_oss.go
  agent/consul/state/catalog_oss_test.go
  agent/consul/state/catalog_schema.go
  agent/consul/state/catalog_test.go
  agent/consul/state/intention.go
  agent/consul/state/schema.go
  agent/consul/state/schema_test.go
  agent/structs/structs.go
  agent/xds/listeners.go
  agent/xds/listeners_test.go
  agent/xds/testdata/listeners/transparent-proxy.envoy-1-20-x.golden
Labels: theme/envoy/xds

#11668 ui: Add documentation link for partitions
  .changelog/11668.txt
  ui/packages/consul-partitions/app/templates/dc/partitions/index.hbs
Labels: theme/ui

#11679 ui: Adds basic support for the Routing tab viz with partitions
  .changelog/11679.txt
  ui/packages/consul-ui/app/components/consul/discovery-chain/README.mdx
  ui/packages/consul-ui/app/components/consul/discovery-chain/index.js
  ui/packages/consul-ui/app/components/consul/discovery-chain/utils.js
  ui/packages/consul-ui/mock-api/v1/discovery-chain/_
  ui/packages/consul-ui/mock-api/v1/internal/ui/services
  ui/packages/consul-ui/tests/unit/components/consul/discovery-chain/get-alternate-services-test.js
  ui/packages/consul-ui/tests/unit/components/consul/discovery-chain/get-resolvers-test.js
Labels: theme/ui

#11696 ui: Adds partition support to Service and Node Identity templates
  .changelog/11696.txt
  ui/packages/consul-ui/app/components/code-editor/README.mdx
  ui/packages/consul-ui/app/components/code-editor/index.hbs
  ui/packages/consul-ui/app/components/consul/node-identity/template/README.mdx
  ui/packages/consul-ui/app/components/consul/node-identity/template/index.hbs
  ui/packages/consul-ui/app/components/consul/service-identity/template/README.mdx
  ui/packages/consul-ui/app/components/consul/service-identity/template/index.hbs
  ui/packages/consul-ui/app/components/inline-code/README.mdx
  ui/packages/consul-ui/app/components/inline-code/layout.scss
  ui/packages/consul-ui/app/components/inline-code/skin.scss
  ui/packages/consul-ui/app/components/policy-form/index.hbs
  ui/packages/consul-ui/app/components/policy-selector/index.hbs
  ui/packages/consul-ui/app/styles/debug.scss
Labels: theme/ui

#11727 ui: Add exported service partition to the source filter menu
  ui/packages/consul-ui/app/components/consul/service/search-bar/index.hbs
  ui/packages/consul-ui/app/components/popover-select/index.scss
  ui/packages/consul-ui/app/filter/predicates/service.js
  ui/packages/consul-ui/app/models/service.js
  ui/packages/consul-ui/app/templates/dc/services/index.hbs
  ui/packages/consul-ui/translations/common/en-us.yaml
Labels: theme/ui

#11712 ui: Add cross partition linking and rollout BucketList
  ui/packages/consul-ui/app/components/consul/bucket/list/index.hbs
  ui/packages/consul-ui/app/components/consul/service/list/index.hbs
  ui/packages/consul-ui/app/components/consul/service/search-bar/index.hbs
  ui/packages/consul-ui/app/components/consul/upstream-instance/list/index.hbs
  ui/packages/consul-ui/app/components/consul/upstream/list/index.hbs
  ui/packages/consul-ui/app/components/popover-select/index.scss
  ui/packages/consul-ui/app/filter/predicates/service.js
  ui/packages/consul-ui/app/models/service.js
  ui/packages/consul-ui/app/templates/dc/services/index.hbs
  ui/packages/consul-ui/app/templates/dc/services/instance/upstreams.hbs
  ui/packages/consul-ui/app/templates/dc/services/show/services.hbs
  ui/packages/consul-ui/app/templates/dc/services/show/upstreams.hbs
  ui/packages/consul-ui/mock-api/v1/health/service/_
  ui/packages/consul-ui/mock-api/v1/internal/ui/gateway-services-nodes/_
  ui/packages/consul-ui/mock-api/v1/internal/ui/services
  ui/packages/consul-ui/translations/common/en-us.yaml
Labels: theme/ui

#11702 ui: Adds basic support for partition exports to Service listings
  .changelog/11702.txt
  ui/packages/consul-ui/app/components/consul/bucket/list/README.mdx
  ui/packages/consul-ui/app/components/consul/bucket/list/index.hbs
  ui/packages/consul-ui/app/components/consul/bucket/list/index.scss
  ui/packages/consul-ui/app/components/consul/service/list/README.mdx
  ui/packages/consul-ui/app/components/consul/service/list/index.hbs
  ui/packages/consul-ui/app/components/consul/service/search-bar/index.hbs
  ui/packages/consul-ui/app/components/consul/upstream-instance/list/index.hbs
  ui/packages/consul-ui/app/components/consul/upstream/list/index.hbs
  ui/packages/consul-ui/app/components/popover-select/index.scss
  ui/packages/consul-ui/app/filter/predicates/service.js
  ui/packages/consul-ui/app/models/service.js
  ui/packages/consul-ui/app/styles/components.scss
  ui/packages/consul-ui/app/templates/dc/services/index.hbs
  ui/packages/consul-ui/app/templates/dc/services/instance/upstreams.hbs
  ui/packages/consul-ui/app/templates/dc/services/show/services.hbs
  ui/packages/consul-ui/app/templates/dc/services/show/upstreams.hbs
  ui/packages/consul-ui/mock-api/v1/health/service/_
  ui/packages/consul-ui/mock-api/v1/internal/ui/gateway-services-nodes/_
  ui/packages/consul-ui/mock-api/v1/internal/ui/services
  ui/packages/consul-ui/translations/common/en-us.yaml
Labels: theme/ui

#11670 ui: Stop tables overlapping with their headers when scrolling
  .changelog/11670.txt
  ui/packages/consul-ui/app/components/consul/intention/list/README.mdx
  ui/packages/consul-ui/app/components/tabular-collection/index.scss
Labels: theme/ui, backport/1.10

#11678 ui: remove old head.hbs file we don't need
  ui/packages/consul-ui/app/templates/head.hbs
Labels: theme/ui, pr/no-changelog

#11697 ui: Improve error messaging for when we can't make a slug
  ui/packages/consul-ui/app/utils/create-fingerprinter.js
Labels: theme/ui, backport/1.8, backport/1.9, pr/no-changelog, backport/1.10

#11717 [1.10.x] Backport of CA system bug fixes
  .changelog/11671.txt
  .changelog/11672.txt
  agent/connect/ca/provider.go
  agent/connect/ca/provider_vault.go
  agent/consul/leader_connect_ca.go
  agent/consul/leader_connect_ca_test.go
  agent/consul/leader_connect_test.go
  agent/consul/server_test.go
  agent/structs/connect_ca.go
Labels: theme/connect, pr/no-changelog

#11718 [1.9.x] Backport of CA system bug fixes
  .changelog/11671.txt
  agent/connect/ca/provider.go
  agent/connect/ca/provider_vault.go
  agent/consul/leader_connect_ca.go
  agent/consul/leader_connect_ca_test.go
  agent/consul/leader_connect_test.go
  agent/consul/server_test.go
  agent/structs/connect_ca.go
Labels: theme/connect, pr/no-changelog

#11755 light refactors to support making partitions and serf-based wan federation are mutually exclusive
  .changelog/_1391.txt
  agent/consul/enterprise_server_oss.go
  agent/consul/merge.go
  agent/consul/merge_test.go
  agent/consul/server.go
  agent/consul/server_oss.go
  agent/consul/server_serf.go
  agent/router/serf_adapter.go
Labels: pr/no-changelog

#11759 sync back 1.11.0-beta3 changelogs
  CHANGELOG.md
Labels: pr/no-changelog

#11757 Allow cross-partition references in disco chain
  .changelog/11757.txt
  agent/config/runtime_test.go
  agent/consul/discoverychain/compile.go
  agent/consul/discoverychain/compile_test.go
  agent/consul/state/config_entry.go
  agent/consul/state/config_entry_test.go
  agent/structs/config_entry_discoverychain.go
  api/config_entry_discoverychain.go
  api/config_entry_discoverychain_test.go
  command/config/write/config_write_test.go
  test/integration/connect/envoy/run-tests.sh
Labels: theme/api, theme/cli, theme/config

#11752 ui: [Backport 1.10.x] Don't cache event sources following a 401
  .changelog/11681.txt
  ui/packages/consul-ui/app/services/data-source/service.js
  ui/packages/consul-ui/app/utils/dom/event-source/callable.js
Labels: theme/ui, pr/no-changelog

#11744 agent/token: rename `agent_master` to `agent_recovery` (internally)
  .changelog/11744.txt
  agent/agent_endpoint.go
  agent/agent_endpoint_test.go
  agent/agent_test.go
  agent/config/builder.go
  agent/config/deprecated_test.go
  agent/config/runtime_test.go
  agent/config/testdata/TestRuntimeConfig_Sanitize.golden
  agent/consul/acl.go
  agent/consul/acl_test.go
  agent/token/persistence.go
  agent/token/persistence_test.go
  agent/token/store.go
  agent/token/store_test.go
Labels: theme/config

#11751 Remove references to "master" ACL tokens in tests
  agent/acl_endpoint_test.go
  agent/agent_endpoint_test.go
  agent/agent_test.go
  agent/dns_test.go
  agent/http_oss_test.go
  agent/http_test.go
  agent/keyring_test.go
  agent/local/state_test.go
  agent/remote_exec_test.go
  agent/routine-leak-checker/leak_test.go
  agent/testagent.go
  command/acl/authmethod/create/authmethod_create_test.go
  command/acl/authmethod/delete/authmethod_delete_test.go
  command/acl/authmethod/list/authmethod_list_test.go
  command/acl/authmethod/read/authmethod_read_test.go
  command/acl/authmethod/update/authmethod_update_test.go
  command/acl/bindingrule/create/bindingrule_create_test.go
  command/acl/bindingrule/delete/bindingrule_delete_test.go
  command/acl/bindingrule/list/bindingrule_list_test.go
  command/acl/bindingrule/read/bindingrule_read_test.go
  command/acl/bindingrule/update/bindingrule_update_test.go
  command/acl/policy/create/policy_create_test.go
  command/acl/policy/delete/policy_delete_test.go
  command/acl/policy/list/policy_list_test.go
  command/acl/policy/read/policy_read_test.go
  command/acl/policy/update/policy_update_test.go
  command/acl/role/create/role_create_test.go
  command/acl/role/delete/role_delete_test.go
  command/acl/role/list/role_list_test.go
  command/acl/role/read/role_read_test.go
  command/acl/role/update/role_update_test.go
  command/acl/rules/translate_test.go
  command/acl/token/clone/token_clone_test.go
  command/acl/token/create/token_create_test.go
  command/acl/token/delete/token_delete_test.go
  command/acl/token/list/token_list_test.go
  command/acl/token/read/token_read_test.go
  command/acl/token/update/token_update_test.go
  command/login/login_test.go
  command/logout/logout_test.go
Labels: theme/cli, pr/no-changelog

#11499 Transition all endpoint tests in agent_endpoint_test.go to go through ServeHTTP
  agent/agent_endpoint.go
  agent/agent_endpoint_test.go
Labels: pr/no-changelog

#11646 docs/nia: new configuration for services condition & source_input
  website/content/docs/nia/configuration.mdx
Labels: type/docs, theme/consul-terraform-sync, pr/no-changelog

#11716 Godoc updates for catalog endpoints
  agent/consul/catalog_endpoint.go
  agent/structs/structs.go
Labels: pr/no-changelog

#11770 improve location of DNS alt domain docs section
  website/content/docs/discovery/dns.mdx
Labels: type/docs, type/docs-cherrypick, backport/1.10, backport/1.11

#11760 website: Upgrade <HashiStackMenu /> to latest
  website/package-lock.json
  website/package.json
Labels: type/docs, type/docs-cherrypick, pr/no-changelog

#11769 docs/nia: Fix typo in CTS CLI options
  website/content/docs/nia/cli/index.mdx
Labels: type/docs, type/docs-cherrypick, theme/consul-terraform-sync, pr/no-changelog

#10895 grpc, xds: recovery middleware to return and log error in case of panic
  .changelog/10895.txt
  agent/consul/server.go
  agent/grpc/client_test.go
  agent/grpc/handler.go
  agent/grpc/handler_test.go
  agent/grpc/server_test.go
  agent/grpc/stats_test.go
  agent/rpc/subscribe/subscribe_test.go
  agent/xds/server.go
  go.mod
  go.sum
Labels: type/enhancement

#11762 docs: add missing verb
  website/content/docs/security/security-models/nia.mdx
Labels: type/docs, type/docs-cherrypick, pr/no-changelog

#11753 ui: [Backport 1.9.x] Don't cache event sources following a 401
  .changelog/11681.txt
  ui/packages/consul-ui/app/services/data-source/service.js
  ui/packages/consul-ui/app/utils/dom/event-source/callable.js
Labels: theme/ui, pr/no-changelog

#11754 ui: [Backport 1.8.x] Don't cache event sources following a 401
  .changelog/11681.txt
  ui-v2/app/services/data-source/service.js
  ui-v2/app/utils/dom/event-source/callable.js
Labels: theme/ui

#11776 Add v1.11.0-rc changelog entry
  CHANGELOG.md
Labels: pr/no-changelog, backport/1.11

#11779 test: test server should auto cleanup
  agent/consul/server_test.go
Labels: pr/no-changelog, backport/1.11

#11721 ca: use the real FSM operation in tests
  agent/connect/ca/provider_consul_test.go
  agent/connect/ca/testing.go
  agent/consul/fsm/commands_oss.go
  agent/consul/leader_connect_ca_test.go
Labels: theme/connect, pr/no-changelog

#11782 acl: ensure that the agent recovery token is properly partitioned
  .changelog/11782.txt
  agent/consul/acl.go
  agent/structs/structs_oss.go
Labels: type/bug, backport/1.11

#11784 update docs
  website/content/docs/k8s/helm.mdx
Labels: type/docs, type/docs-cherrypick, pr/no-changelog

#11756 ui: Make 'dangerous' buttons have white text even in dark theme
  ui/packages/consul-ui/app/styles/themes.scss
Labels: theme/ui, pr/no-changelog, backport/1.11

#11763 ui: Fixup notifications for token using and topology intention saving
  ui/packages/consul-ui/app/components/consul/intention/notifications/index.hbs
  ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs
  ui/packages/consul-ui/app/routes/dc/services/show/topology.js
  ui/packages/consul-ui/app/services/feedback.js
Labels: theme/ui, pr/no-changelog, backport/1.11

#11790 Update alert banner
  website/data/alert-banner.js
Labels: type/docs, type/docs-cherrypick

#11780 ca: improve test coverage for RenewIntermediate
  agent/connect/ca/testing.go
  agent/consul/connect_ca_endpoint_test.go
  agent/consul/leader_connect_ca.go
  agent/consul/leader_connect_ca_test.go
  agent/consul/leader_connect_test.go
  agent/consul/state/connect_ca.go
  agent/structs/connect_ca.go
  testrpc/wait.go
Labels: theme/connect, backport/1.9, pr/no-changelog, backport/1.10, backport/1.11

#11789 Add partitions to prettyformatters
  api/namespace.go
  command/acl/authmethod/formatter.go
  command/acl/bindingrule/formatter.go
  command/acl/policy/formatter.go
  command/acl/role/formatter.go
  command/acl/token/clone/token_clone_test.go
  command/acl/token/formatter.go
Labels: theme/cli, pr/no-changelog, backport/1.11

#11793 Various Boltdb/Raft Documentation Updates
  website/content/docs/agent/options.mdx
  website/content/docs/agent/telemetry.mdx
Labels: type/docs, backport/1.11

#11794 update changelog for ent feature
  .changelog/_1411.txt
Labels: pr/no-changelog, backport/1.11

#11795 [sync ent] increase segment max limit to 4*64, make configurable (#1424)
  .changelog/_1424.txt
  agent/config/builder.go
  agent/config/default.go
  agent/config/runtime_test.go
  agent/config/testdata/full-config.hcl
  agent/config/testdata/full-config.json
Labels: theme/config, pr/no-changelog

#11797 Update stray ref to old admin-partition cmd
  website/content/commands/partition.mdx
  website/data/commands-nav-data.json
Labels: type/docs, type/docs-cherrypick, pr/no-changelog

#11791 ui: Change partitions to expect `[]` from the API
  .changelog/11791.txt
  ui/packages/consul-ui/app/serializers/partition.js
  ui/packages/consul-ui/mock-api/v1/partitions
  ui/packages/consul-ui/tests/integration/serializers/partition-test.js
Labels: theme/ui, backport/1.11

#11786 connect: update SNI label extraction to support new taxonomy for partitions
  .changelog/11786.txt
  command/connect/envoy/bootstrap_config.go
  command/connect/envoy/bootstrap_config_test.go
  command/connect/envoy/testdata/CONSUL_HTTP_ADDR-with-https-scheme-enables-tls.golden
  command/connect/envoy/testdata/access-log-path.golden
  command/connect/envoy/testdata/defaults.golden
  command/connect/envoy/testdata/deprecated-grpc-addr-config.golden
  command/connect/envoy/testdata/existing-ca-file.golden
  command/connect/envoy/testdata/existing-ca-path.golden
  command/connect/envoy/testdata/extra_-multiple.golden
  command/connect/envoy/testdata/extra_-single.golden
  command/connect/envoy/testdata/grpc-addr-env.golden
  command/connect/envoy/testdata/grpc-addr-flag.golden
  command/connect/envoy/testdata/grpc-addr-unix.golden
  command/connect/envoy/testdata/ingress-gateway-address-specified.golden
  command/connect/envoy/testdata/ingress-gateway-no-auto-register.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-and-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-without-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway.golden
  command/connect/envoy/testdata/prometheus-metrics.golden
  command/connect/envoy/testdata/token-arg.golden
  command/connect/envoy/testdata/token-env.golden
  command/connect/envoy/testdata/token-file-arg.golden
  command/connect/envoy/testdata/token-file-env.golden
  command/connect/envoy/testdata/xds-addr-config.golden
  command/connect/envoy/testdata/zipkin-tracing-config.golden
Labels: theme/cli, backport/1.11

#11809 state: fix freed VIP table id index
  agent/consul/state/catalog_events_test.go
  agent/consul/state/catalog_schema.go
  agent/consul/state/catalog_test.go
Labels: pr/no-changelog

#11798 leader: move the virtual IP version check into a goroutine
  agent/consul/leader.go
  agent/consul/leader_connect.go
  agent/consul/leader_test.go
  agent/consul/server.go
Labels: pr/no-changelog

#11812 oss: use wildcard partition in metrics proxy ui endpoint
  agent/ui_endpoint.go
Labels: pr/no-changelog

#11765 ui: reuse BucketList for intention view pages
  ui/packages/consul-ui/app/components/consul/bucket/list/README.mdx
  ui/packages/consul-ui/app/components/consul/bucket/list/index.hbs
  ui/packages/consul-ui/app/components/consul/bucket/list/index.scss
  ui/packages/consul-ui/app/components/consul/intention/view/index.hbs
  ui/packages/consul-ui/app/components/definition-table/layout.scss
Labels: theme/ui, pr/no-changelog, backport/1.11

#11767 ui: Ensure we show a special readonly page for intentions
  .changelog/11767.txt
  ui/packages/consul-ui/app/components/consul/intention/form/index.hbs
  ui/packages/consul-ui/app/components/consul/intention/view/index.hbs
  ui/packages/consul-ui/mock-api/v1/connect/intentions/exact
  ui/packages/consul-ui/tests/acceptance/dc/intentions/read-only.feature
  ui/packages/consul-ui/tests/acceptance/steps/dc/intentions/read-only-steps.js
Labels: theme/ui, backport/1.10, backport/1.11

#11772 ui: Prefer shorter partition word in certain places vs Admin Partition
  ui/packages/consul-partitions/app/components/consul/partition/form/index.hbs
  ui/packages/consul-partitions/app/components/consul/partition/notifications/index.hbs
  ui/packages/consul-partitions/app/components/consul/partition/selector/index.hbs
  ui/packages/consul-partitions/app/templates/dc/partitions/edit.hbs
  ui/packages/consul-partitions/app/templates/dc/partitions/index.hbs
  ui/packages/consul-ui/app/components/auth-form/index.hbs
  ui/packages/consul-ui/app/components/oidc-select/index.hbs
Labels: theme/ui, pr/no-changelog, backport/1.11

#11801 ui: Change the URL prefix of partitions from `-` to `_`
  .changelog/11801.txt
  ui/packages/consul-ui/app/locations/fsm-with-optional.js
  ui/packages/consul-ui/app/services/ui-config.js
Labels: theme/ui, backport/1.11

#11804 ui: Disable setting wildcard partitions for intentions
  .changelog/11804.txt
  ui/packages/consul-ui/app/components/consul/intention/form/fieldsets/index.hbs
  ui/packages/consul-ui/app/components/consul/intention/form/index.js
  ui/packages/consul-ui/app/services/repository/intention.js
Labels: theme/ui, backport/1.11

#11803 ui: Add version information back into the footer
  .changelog/11803.txt
  ui/packages/consul-ui/app/components/app/index.scss
  ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs
Labels: theme/ui, backport/1.10, backport/1.11

#11808 [1.10.x] Update go version to 1.16.12
  .changelog/11808.txt
  .circleci/config.yml
  .github/workflows/build.yml
  agent/dns.go
  build-support/docker/Build-Go.dockerfile
  build-support/docker/Test-Flake.dockerfile
  test/integration/connect/envoy/helpers.bash
Labels: type/ci, theme/contributing

#11807 [1.9.x] Update go version to 1.16.12
  .changelog/11807.txt
  .circleci/config.yml
  .github/workflows/build.yml
  build-support/docker/Build-Go.dockerfile
  build-support/docker/Test-Flake.dockerfile
  connect/tls_test.go
Labels: theme/connect, type/ci, theme/contributing

#11822 various partition related todos
  agent/acl.go
  agent/agent_endpoint.go
  agent/consul/acl.go
  agent/consul/acl_oss.go
  agent/consul/leader.go
  agent/consul/prepared_query/template.go
  agent/consul/state/catalog.go
  agent/proxycfg/connect_proxy.go
  agent/proxycfg/manager_test.go
  agent/proxycfg/state.go
  agent/structs/connect_proxy_config.go
  agent/structs/connect_proxy_config_oss.go
  agent/structs/structs.go
Labels: pr/no-changelog, backport/1.11

#11813 Use anonymousToken when querying by secret ID
  agent/consul/leader.go
  agent/consul/leader_test.go
Labels: pr/no-changelog, backport/1.11

#11823 proxycfg: use external addresses in tproxy when crossing partition boundaries
  agent/proxycfg/upstreams.go
Labels: pr/no-changelog, backport/1.11

#11818 http: improve 404 Not Found response message
  .changelog/11818.txt
  agent/http.go
Labels: theme/api, theme/operator-usability, backport/1.11

#11824 proxycfg: ensure all of the watches are canceled if they are cancelable
  .changelog/11824.txt
  agent/proxycfg/connect_proxy.go
Labels: backport/1.11

#11826 [OSS] Handle discovery chain race
  .changelog/11826.txt
  agent/proxycfg/connect_proxy.go
  agent/proxycfg/ingress_gateway.go
  agent/proxycfg/snapshot.go
  agent/proxycfg/state_test.go
  agent/proxycfg/upstreams.go
  agent/structs/connect_proxy_config.go
  agent/xds/clusters.go
  agent/xds/clusters_test.go
  agent/xds/endpoints.go
  agent/xds/endpoints_test.go
  agent/xds/listeners.go
  agent/xds/listeners_test.go
  agent/xds/routes.go
Labels: theme/envoy/xds, backport/1.11

#11829 Get partition label from upstream metrics
  command/connect/envoy/bootstrap_config.go
  command/connect/envoy/bootstrap_config_test.go
  command/connect/envoy/testdata/CONSUL_HTTP_ADDR-with-https-scheme-enables-tls.golden
  command/connect/envoy/testdata/access-log-path.golden
  command/connect/envoy/testdata/defaults.golden
  command/connect/envoy/testdata/deprecated-grpc-addr-config.golden
  command/connect/envoy/testdata/existing-ca-file.golden
  command/connect/envoy/testdata/existing-ca-path.golden
  command/connect/envoy/testdata/extra_-multiple.golden
  command/connect/envoy/testdata/extra_-single.golden
  command/connect/envoy/testdata/grpc-addr-env.golden
  command/connect/envoy/testdata/grpc-addr-flag.golden
  command/connect/envoy/testdata/grpc-addr-unix.golden
  command/connect/envoy/testdata/ingress-gateway-address-specified.golden
  command/connect/envoy/testdata/ingress-gateway-no-auto-register.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-and-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-without-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway.golden
  command/connect/envoy/testdata/prometheus-metrics.golden
  command/connect/envoy/testdata/token-arg.golden
  command/connect/envoy/testdata/token-env.golden
  command/connect/envoy/testdata/token-file-arg.golden
  command/connect/envoy/testdata/token-file-env.golden
  command/connect/envoy/testdata/xds-addr-config.golden
  command/connect/envoy/testdata/zipkin-tracing-config.golden
Labels: theme/cli, pr/no-changelog, backport/1.11

#11164 Document SDS for ingress gateways
  website/content/docs/connect/config-entries/ingress-gateway.mdx
  website/content/docs/connect/gateways/ingress-gateway.mdx
Labels: type/docs, theme/envoy/xds, pr/no-changelog

#11831 CTS remove deprecated driver.terraform.working_dir
  website/content/docs/nia/configuration.mdx
Labels: type/docs, theme/consul-terraform-sync, pr/no-changelog

#11839 docs: Update exported-services page to include required Name field
  website/content/docs/connect/config-entries/exported-services.mdx
Labels: type/docs, type/docs-cherrypick, pr/no-changelog, backport/1.11

#11840 docs: document partition config flag
  website/content/docs/agent/options.mdx
Labels: type/docs, type/docs-cherrypick, pr/no-changelog, backport/1.11

#11834 docs: Add API docs for Admin Partitions
  website/content/api-docs/admin-partitions.mdx
  website/data/api-docs-nav-data.json
Labels: type/docs, type/docs-cherrypick, pr/no-changelog, backport/1.11

#11837 docs: version specific upgrade content for 1.11.0
  website/content/docs/upgrading/upgrade-specific.mdx
Labels: type/docs, type/docs-cherrypick, pr/no-changelog, backport/1.11

#11843 Update product version extraction for CRT
  .github/workflows/build.yml
Labels: theme/contributing, pr/no-changelog, backport/1.11

#11838 docs: Update dns sections for partition query format and virtual IPs
  website/content/docs/agent/options.mdx
  website/content/docs/discovery/dns.mdx
Labels: type/docs, type/docs-cherrypick, pr/no-changelog, backport/1.11

#11778 Updates for admin partitions to include changes for RC
  website/content/docs/enterprise/admin-partitions.mdx
  website/public/img/admin-partitions/consul-admin-partitions-verify-in-ui.png
Labels: type/docs-cherrypick, pr/no-changelog

#11842 Website fixups for admin partitions
  website/content/commands/acl/auth-method/create.mdx
  website/content/commands/acl/auth-method/delete.mdx
  website/content/commands/acl/auth-method/list.mdx
  website/content/commands/acl/auth-method/read.mdx
  website/content/commands/acl/auth-method/update.mdx
  website/content/commands/acl/binding-rule/create.mdx
  website/content/commands/acl/binding-rule/delete.mdx
  website/content/commands/acl/binding-rule/list.mdx
  website/content/commands/acl/binding-rule/read.mdx
  website/content/commands/acl/binding-rule/update.mdx
  website/content/commands/acl/policy/create.mdx
  website/content/commands/acl/policy/delete.mdx
  website/content/commands/acl/policy/list.mdx
  website/content/commands/acl/policy/read.mdx
  website/content/commands/acl/policy/update.mdx
  website/content/commands/acl/role/create.mdx
  website/content/commands/acl/role/delete.mdx
  website/content/commands/acl/role/list.mdx
  website/content/commands/acl/role/read.mdx
  website/content/commands/acl/role/update.mdx
  website/content/commands/acl/token/clone.mdx
  website/content/commands/acl/token/create.mdx
  website/content/commands/acl/token/delete.mdx
  website/content/commands/acl/token/list.mdx
  website/content/commands/acl/token/read.mdx
  website/content/commands/acl/token/update.mdx
  website/content/commands/catalog/nodes.mdx
  website/content/commands/catalog/services.mdx
  website/content/commands/config/delete.mdx
  website/content/commands/config/list.mdx
  website/content/commands/config/read.mdx
  website/content/commands/config/write.mdx
  website/content/commands/connect/envoy.mdx
  website/content/commands/connect/expose.mdx
  website/content/commands/connect/redirect-traffic.mdx
  website/content/commands/intention/check.mdx
  website/content/commands/intention/create.mdx
  website/content/commands/intention/delete.mdx
  website/content/commands/intention/get.mdx
  website/content/commands/intention/index.mdx
  website/content/commands/intention/match.mdx
  website/content/commands/kv/delete.mdx
  website/content/commands/kv/export.mdx
  website/content/commands/kv/get.mdx
  website/content/commands/kv/import.mdx
  website/content/commands/kv/put.mdx
  website/content/commands/members.mdx
  website/content/commands/namespace/create.mdx
  website/content/commands/namespace/delete.mdx
  website/content/commands/namespace/list.mdx
  website/content/commands/namespace/read.mdx
  website/content/commands/namespace/update.mdx
  website/content/commands/namespace/write.mdx
  website/content/commands/services/deregister.mdx
  website/content/commands/services/register.mdx
  website/content/partials/http_api_partition_options.mdx
Labels: type/docs, type/docs-cherrypick, pr/no-changelog, backport/1.11

#11850 ui: Fixes an issue with the version footer when scrolling
  .changelog/11850.txt
  ui/packages/consul-ui/app/components/app/index.scss
Labels: theme/ui, backport/1.11

#11413 website: fix algolia indexing
  .circleci/config.yml
Labels: type/ci, pr/no-changelog

#11852 state: fix freed VIP table id index
  agent/consul/state/catalog_events_test.go
  agent/consul/state/catalog_schema.go
  agent/consul/state/catalog_test.go
Labels: pr/no-changelog

#11830 ui: Fix sticky namespace selector
  .changelog/11830.txt
  ui/packages/consul-ui/app/routes/dc.js
Labels: theme/ui

#11836 Deprecate workspace_prefix for new workspaces.prefix
  website/content/docs/nia/configuration.mdx
Labels: type/docs, theme/consul-terraform-sync, pr/no-changelog

#11844 Add darwin arm64 support
  .github/workflows/build.yml
Labels: theme/contributing, pr/no-changelog, backport/1.11

#11854 Update golang.org/x/net to address CVE-2021-44716
  .changelog/11854.txt
  go.mod
  go.sum
Labels: pr/dependencies, backport/1.8, backport/1.9, backport/1.10, backport/1.11

#11855 Sync changelog fixes from 1.11.0
  .changelog/10478.txt
  .changelog/10507.txt
  .changelog/10572.txt
  .changelog/11080.txt
  .changelog/11129.txt
  .changelog/11188.txt
  .changelog/11263.txt
  .changelog/11323.txt
  .changelog/11429.txt
  .changelog/11431.txt
  .changelog/11433.txt
  .changelog/11444.txt
  .changelog/11446.txt
  .changelog/11479.txt
  .changelog/11541.txt
  .changelog/11566.txt
  .changelog/11591.txt
  .changelog/11604.txt
  .changelog/11654.txt
  .changelog/11656.txt
  .changelog/11666.txt
  .changelog/11668.txt
  .changelog/11679.txt
  .changelog/11680.txt
  .changelog/11696.txt
  .changelog/11699.txt
  .changelog/11702.txt
  .changelog/11737.txt
  .changelog/11738.txt
  .changelog/11739.txt
  .changelog/11747.txt
  .changelog/11757.txt
  .changelog/11758.txt
  .changelog/11782.txt
  .changelog/11786.txt
  .changelog/11855.txt
  .changelog/_1202.txt
  .changelog/_1203.txt
  .changelog/_1284.txt
  .changelog/_1300.txt
  .changelog/_1342.txt
  .changelog/_1391.txt
  .changelog/_1411.txt
  .changelog/_987.md
  CHANGELOG.md
Labels: backport/1.11

#11766 docs: consul-vault kubernetes integration docs
  website/content/docs/k8s/connect/connect-ca-provider.mdx
  website/content/docs/k8s/installation/vault/connect-ca.mdx
  website/content/docs/k8s/installation/vault/gossip.mdx
  website/content/docs/k8s/installation/vault/index.mdx
  website/content/docs/k8s/installation/vault/server-tls.mdx
  website/data/docs-nav-data.json
Labels: type/docs, type/docs-cherrypick, pr/no-changelog

#11846 docs: Admin Partitions image bump to GA
  website/content/docs/enterprise/admin-partitions.mdx
Labels: type/docs, type/docs-cherrypick

#11845 docs: ExportedServices CRD typo and change heading for services
  website/content/docs/connect/config-entries/exported-services.mdx
Labels: type/docs, type/docs-cherrypick

#11862 docs: Remove BETA from Admin Partitions
  website/data/docs-nav-data.json
Labels: type/docs, type/docs-cherrypick, pr/no-changelog

#11871 docs: Add admin partitions to Enterprise Overview page
  website/content/docs/enterprise/index.mdx
Labels: type/docs, type/docs-cherrypick, pr/no-changelog

#11869 website: Disable alert banner
  website/data/alert-banner.js
Labels: type/docs, type/docs-cherrypick, pr/no-changelog

#11864 docs: fix typo in KV store API
  website/content/api-docs/kv.mdx
Labels: type/docs, type/docs-cherrypick, pr/no-changelog

#11863 docs: remove BETA from Consul K8s CLI
  website/content/docs/k8s/index.mdx
  website/content/docs/k8s/installation/install.mdx
  website/content/docs/k8s/k8s-cli.mdx
  website/content/docs/k8s/upgrade/compatibility.mdx
Labels: type/docs, type/docs-cherrypick, pr/no-changelog

#11819 ui: [Backport 1.10.x] Add version information back into the footer (#11803)
  .changelog/11803.txt
  ui/packages/consul-ui/app/components/app/index.scss
  ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs
Labels: theme/ui, pr/no-changelog

#11879 docs: add Exported Services to overview
  website/content/docs/connect/config-entries/exported-services.mdx
  website/content/docs/connect/config-entries/index.mdx
Labels: type/docs, type/docs-cherrypick, pr/no-changelog

#11881 docs: fix ExportedServices typo on example
  website/content/docs/connect/config-entries/exported-services.mdx
Labels: type/docs, type/docs-cherrypick, pr/no-changelog

#11878 Remove beta notice from CLI doc
  website/content/commands/partition.mdx
Labels: type/docs, type/docs-cherrypick, backport/1.11

#11883 docs: ExportedServices YAML correction
  website/content/docs/connect/config-entries/exported-services.mdx
  website/content/docs/k8s/crds/index.mdx
Labels: type/docs, type/docs-cherrypick, pr/no-changelog

#11885 docs: clarification on Limitations for Vault Secrets backend
  website/content/docs/k8s/installation/vault/index.mdx
  website/content/docs/k8s/k8s-cli.mdx
Labels: type/docs, type/docs-cherrypick, pr/no-changelog

#11536 add a metrics test check GH action
  .github/scripts/metrics_checker.sh
  .github/workflows/pr-metrics-test-checker.yml
Labels: theme/contributing, pr/no-changelog, pr/no-metrics-test

#11897 Update version.js
  website/data/version.js
Labels: type/docs, type/docs-cherrypick, pr/no-changelog

#11886 Document /v1/agent/force-leave prune and wan params
  website/content/api-docs/agent/index.mdx
  website/content/commands/force-leave.mdx
Labels: type/docs, type/docs-cherrypick, pr/no-changelog

#11868 ui: Fix up missing policy delete warning modal
  .changelog/11868.txt
  ui/packages/consul-ui/app/components/buttons/index.scss
  ui/packages/consul-ui/app/components/modal-dialog/README.mdx
  ui/packages/consul-ui/app/components/modal-dialog/index.js
  ui/packages/consul-ui/app/templates/dc/acls/policies/-form.hbs
  ui/packages/consul-ui/tests/pages/dc/acls/policies/edit.js
Labels: type/bug, theme/ui, backport/1.10, backport/1.11

#11880 ui: Check for `intention` ACL resources, not `intentions` ACL resources
  ui/packages/consul-ui/app/services/repository/permission.js
  ui/packages/consul-ui/tests/acceptance/dc/intentions/index.feature
Labels: theme/ui, pr/no-changelog, backport/1.10, backport/1.11

#11892 ui: Various empty state improvements/fixups
  .changelog/11892.txt
  ui/packages/consul-ui/app/components/error-state/README.mdx
  ui/packages/consul-ui/app/components/error-state/index.hbs
  ui/packages/consul-ui/app/templates/dc/nodes/index.hbs
  ui/packages/consul-ui/app/templates/dc/services/index.hbs
  ui/packages/consul-ui/app/templates/dc/services/show/intentions/index.hbs
Labels: theme/ui, backport/1.9, backport/1.10, backport/1.11

#11774 ui: Fixup names of Meta for instance search, also add Node
  .changelog/11774.txt
  ui/packages/consul-ui/app/routes/dc/services/show/instances.js
  ui/packages/consul-ui/app/search/predicates/service-instance.js
  ui/packages/consul-ui/translations/common/en-us.yaml
Labels: theme/ui, backport/1.9, backport/1.10, backport/1.11

#11891 ui: Remove any route level auth checks
  .changelog/11891.txt
  ui/packages/consul-ui/app/routing/route.js
Labels: theme/ui, backport/1.10, backport/1.11

#11887 Minor doc fixes to K8s CA and Admin Partitions guides
  website/content/docs/enterprise/admin-partitions.mdx
  website/content/docs/k8s/connect/connect-ca-provider.mdx
Labels: type/docs, type/docs-cherrypick, pr/no-changelog

#11781 cli: consul tls: create private keys with mode 0600
  .changelog/11781.txt
  command/tls/ca/create/tls_ca_create.go
  command/tls/ca/create/tls_ca_create_test.go
  command/tls/cert/create/tls_cert_create.go
  command/tls/cert/create/tls_cert_create_test.go
Labels: theme/cli, backport/1.9, backport/1.10, backport/1.11

#11902 docs: Fix service_id description on agent deregister API
  website/content/api-docs/agent/service.mdx
Labels: type/docs, type/docs-cherrypick, pr/no-changelog

#11859 clarify mesh gateway docs use cases; include admin partition flow
  website/content/docs/connect/gateways/index.mdx
  website/content/docs/connect/gateways/ingress-gateway.mdx
  website/content/docs/connect/gateways/mesh-gateway/index.mdx
  website/content/docs/connect/gateways/mesh-gateway/service-to-service-traffic-datacenters.mdx
  website/content/docs/connect/gateways/mesh-gateway/service-to-service-traffic-partitions.mdx
  website/data/docs-nav-data.json
Labels: type/docs, type/docs-cherrypick, pr/no-changelog, pr/no-metrics-test

#11894 website: Upgrade <Subnav /> & <ProductDownloadsPage />
  website/package-lock.json
  website/package.json
Labels: type/docs, type/docs-cherrypick, pr/no-changelog

#11796 testing: stop using an old version in testServer
  agent/consul/autopilot_test.go
  agent/consul/intention_endpoint_test.go
  agent/consul/internal_endpoint_test.go
  agent/consul/server_test.go
  agent/consul/system_metadata_test.go
Labels: theme/internal-cleanup, theme/testing, backport/1.9, pr/no-changelog, backport/1.10, backport/1.11
