Repository hashicorp/consul, pull requests merged in 2021-03, with the labels that each got.

#9838 Fix TLS cert creation instruction for Consul federation
  website/content/docs/k8s/installation/multi-cluster/vms-and-kubernetes.mdx
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#9768 Add flags to consul connect envoy for metrics merging.
  .changelog/9768.txt
  command/connect/envoy/bootstrap_config.go
  command/connect/envoy/bootstrap_config_test.go
  command/connect/envoy/bootstrap_tpl.go
  command/connect/envoy/envoy.go
  command/connect/envoy/envoy_test.go
  command/connect/envoy/testdata/prometheus-metrics.golden
  website/content/commands/connect/envoy.mdx
Labels: theme/cli

#9813 ui: Add Route component / routlet service
  ui/packages/consul-ui/app/components/main-nav-horizontal/index.scss
  ui/packages/consul-ui/app/components/main-nav-vertical/index.scss
  ui/packages/consul-ui/app/components/outlet/index.hbs
  ui/packages/consul-ui/app/components/outlet/index.js
  ui/packages/consul-ui/app/components/route/index.hbs
  ui/packages/consul-ui/app/components/route/index.js
  ui/packages/consul-ui/app/helpers/is-href.js
  ui/packages/consul-ui/app/routes/dc.js
  ui/packages/consul-ui/app/routes/dc/services/index.js
  ui/packages/consul-ui/app/routes/dc/services/show/routing.js
  ui/packages/consul-ui/app/routes/dc/services/show/tags.js
  ui/packages/consul-ui/app/services/routlet.js
  ui/packages/consul-ui/app/templates/application.hbs
  ui/packages/consul-ui/app/templates/dc.hbs
  ui/packages/consul-ui/app/templates/dc/services/index.hbs
  ui/packages/consul-ui/app/templates/dc/services/show.hbs
  ui/packages/consul-ui/app/templates/dc/services/show/instances.hbs
  ui/packages/consul-ui/package.json
Labels: theme/ui

#9831 ui: Remove storybook, add docfy
  ui/packages/consul-ui/.docfy-config.js
  ui/packages/consul-ui/.eslintrc.js
  ui/packages/consul-ui/.storybook/main.js
  ui/packages/consul-ui/.storybook/preview.js
  ui/packages/consul-ui/app/components/app-error/README.stories.mdx
  ui/packages/consul-ui/app/components/app/index.scss
  ui/packages/consul-ui/app/components/auth-dialog/README.mdx
  ui/packages/consul-ui/app/components/auth-profile/README.mdx
  ui/packages/consul-ui/app/components/consul/metadata/list/README.mdx
  ui/packages/consul-ui/app/components/copy-button/README.mdx
  ui/packages/consul-ui/app/components/data-collection/README.mdx
  ui/packages/consul-ui/app/components/data-sink/README.mdx
  ui/packages/consul-ui/app/components/data-source/README.mdx
  ui/packages/consul-ui/app/components/debug/navigation/index.hbs
  ui/packages/consul-ui/app/components/event-source/README.mdx
  ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs
  ui/packages/consul-ui/app/components/jwt-source/README.mdx
  ui/packages/consul-ui/app/components/ref/README.mdx
  ui/packages/consul-ui/app/components/state-chart/README.mdx
  ui/packages/consul-ui/app/components/state/README.mdx
  ui/packages/consul-ui/app/components/toggle-button/README.mdx
  ui/packages/consul-ui/app/components/token-source/README.mdx
  ui/packages/consul-ui/app/instance-initializers/debug.js
  ui/packages/consul-ui/app/router.js
  ui/packages/consul-ui/app/styles/debug.scss
  ui/packages/consul-ui/app/styles/prism-coldark-cold.scss
  ui/packages/consul-ui/app/styles/prism-coldark-dark.scss
  ui/packages/consul-ui/app/templates/debug.hbs
  ui/packages/consul-ui/ember-cli-build.js
  ui/packages/consul-ui/lib/startup/index.js
  ui/packages/consul-ui/lib/startup/templates/head.html.js
  ui/packages/consul-ui/package.json
  ui/yarn.lock
Labels: theme/ui

#9671 state: Add terminating gateway events for streaming
  agent/consul/state/catalog.go
  agent/consul/state/catalog_events.go
  agent/consul/state/catalog_events_oss_test.go
  agent/consul/state/catalog_events_test.go
Labels: pr/no-changelog, theme/streaming

#9805 structs: remove EnterpriseMeta.GetNamespace
  agent/cache-types/streaming_health_services.go
  agent/cache-types/streaming_health_services_test.go
  agent/consul/state/catalog_events.go
  agent/consul/state/catalog_events_test.go
  agent/rpc/subscribe/subscribe.go
  agent/structs/structs_oss.go
Labels: pr/no-changelog

#9850 Add docs for service metrics/metrics merging on Consul on K8s
  website/content/docs/k8s/observability/metrics.mdx
  website/public/img/metrics-arch.png
Labels: type/docs

#9856 Gateway metrics docs
  website/content/docs/k8s/observability/metrics.mdx
Labels: type/docs

#9857 UI metrics docs
  website/content/docs/k8s/observability/metrics.mdx
  website/public/img/ui-topology.png
Labels: type/docs

#9859 Docs for helm values introduced by metrics
  website/content/docs/k8s/helm.mdx
Labels: type/docs

#9851 Fix advertise_addr_wan_ipv6 configuration key
  .changelog/9851.txt
  agent/config/config.go
Labels: backport/1.7, backport/1.8, backport/1.9, theme/config, type/bug

#9792 command/kv: Add prefix option to kv import command
  .changelog/9792.txt
  command/kv/imp/kv_import.go
  command/kv/imp/kv_import_test.go
  website/content/commands/kv/import.mdx
Labels: theme/cli, type/enhancement

#9770 Docs: Update terminating-gateway-config-entry
  website/content/docs/connect/config-entries/terminating-gateway.mdx
Labels: type/docs, type/docs-cherrypick

#9672 connect/ca: Allow ForceWithoutCrossSigning for all providers
  .changelog/9672.txt
  agent/consul/leader_connect_ca.go
  agent/consul/leader_connect_test.go
  api/connect_ca.go
  command/connect/ca/set/connect_ca_set.go
  website/content/api-docs/connect/ca.mdx
  website/content/commands/connect/ca.mdx
Labels: theme/api, theme/cli, type/docs

#9869 Update requirements.mdx
  website/content/docs/nia/installation/requirements.mdx
Labels: type/docs-cherrypick

#9867 Update alert banner
  website/data/alert-banner.js
Labels: type/docs, type/docs-cherrypick

#9846 Small changes to gossip related telemetry docs
  website/content/docs/agent/telemetry.mdx
Labels: type/docs

#9874 docs: fixup syntax issue
  website/content/docs/connect/config-entries/terminating-gateway.mdx
Labels: type/docs, type/docs-cherrypick

#9871 website(style): Update gray brand colors
  website/components/basic-hero/style.css
  website/components/case-study-carousel/style.css
  website/components/cloud-offerings-list/style.css
  website/components/enterprise-comparison/style.css
  website/components/footer/style.css
  website/components/hcp-callout-section/HCPCalloutSection.module.css
  website/components/learn-callout/style.css
  website/components/mini-cta/style.css
  website/package-lock.json
  website/package.json
Labels: pr/no-changelog

#8599 AutopilotServerHealth now handles the 429 status code
  .changelog/8599.txt
  api/go.sum
  api/mock_api_test.go
  api/operator_autopilot.go
  api/operator_autopilot_test.go
Labels: backport/1.9

#9152 use streaming backend for connect service health
  agent/agent.go
  agent/consul/state/memdb.go
  agent/proxycfg/manager.go
  agent/proxycfg/manager_test.go
  agent/proxycfg/state.go
  agent/proxycfg/state_test.go
  agent/rpcclient/health/health.go
Labels: pr/no-changelog, theme/streaming

#9107 Add namespaces to prepared query API docs
  website/content/api-docs/query.mdx
Labels: backport/1.9, pr/no-changelog, type/docs, type/docs-cherrypick

#9878 docs: rename SourceAddress to SourceIP
  website/content/docs/connect/config-entries/service-resolver.mdx
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#8698 Use errors.Is() in IsErrEOF()
  lib/eof.go
  lib/eof_test.go
Labels: backport/1.7, backport/1.8, backport/1.9, theme/internal-cleanup, type/bug

#9475 Add support for configuring TLS ServerName for health checks
  .changelog/9475.txt
  agent/agent.go
  agent/config/builder.go
  agent/config/config.go
  agent/config/runtime_test.go
  agent/config/testdata/TestRuntimeConfig_Sanitize.golden
  agent/config/testdata/full-config.hcl
  agent/config/testdata/full-config.json
  agent/http_decode_test.go
  agent/structs/check_definition.go
  agent/structs/check_type.go
  agent/structs/structs.go
  agent/txn_endpoint.go
  api/agent.go
  api/health.go
  proto/pbservice/healthcheck.gen.go
  proto/pbservice/healthcheck.pb.go
  proto/pbservice/healthcheck.proto
  tlsutil/config.go
  tlsutil/config_test.go
  website/content/api-docs/agent/check.mdx
  website/content/docs/discovery/checks.mdx
Labels: theme/certificates, theme/health-checks, type/enhancement

#9886 [SDK] change all cases of *testing.T to testing.TB
  sdk/testutil/assertions.go
  sdk/testutil/io.go
  sdk/testutil/server.go
  sdk/testutil/server_methods.go
  sdk/testutil/server_wrapper.go
Labels: pr/no-changelog, type/enhancement

#9847 ui: CSP Improvements
  .changelog/9847.txt
  ui/packages/consul-ui/app/initializers/ivy-codemirror.js
  ui/packages/consul-ui/app/instance-initializers/ivy-codemirror.js
  ui/packages/consul-ui/ember-cli-build.js
  ui/packages/consul-ui/lib/startup/templates/body.html.js
  ui/packages/consul-ui/server/index.js
  ui/packages/consul-ui/vendor/init.js
Labels: backport/1.9, theme/ui

#9864 ui: Adds warning icon to side menu when ACLs are disabled
  .changelog/9864.txt
  ui/packages/consul-ui/app/abilities/acl.js
  ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs
  ui/packages/consul-ui/app/components/hashicorp-consul/index.scss
  ui/packages/consul-ui/app/components/main-nav-vertical/index.scss
  ui/packages/consul-ui/app/components/main-nav-vertical/layout.scss
  ui/packages/consul-ui/app/components/main-nav-vertical/skin.scss
  ui/packages/consul-ui/app/modifiers/disabled.js
  ui/packages/consul-ui/app/styles/base/icons/base-placeholders.scss
Labels: theme/ui

#9845 ui: Create auth-method show page with General Info Tab
  ui/packages/consul-ui/app/components/certificate/index.hbs
  ui/packages/consul-ui/app/components/certificate/index.js
  ui/packages/consul-ui/app/components/certificate/index.scss
  ui/packages/consul-ui/app/components/consul/auth-method/index.scss
  ui/packages/consul-ui/app/components/consul/auth-method/list/index.hbs
  ui/packages/consul-ui/app/components/consul/auth-method/list/pageobject.js
  ui/packages/consul-ui/app/components/consul/auth-method/view/index.hbs
  ui/packages/consul-ui/app/router.js
  ui/packages/consul-ui/app/routes/dc/acls/auth-methods/show.js
  ui/packages/consul-ui/app/routes/dc/acls/auth-methods/show/auth-method.js
  ui/packages/consul-ui/app/routes/dc/acls/auth-methods/show/index.js
  ui/packages/consul-ui/app/styles/components.scss
  ui/packages/consul-ui/app/styles/components/composite-row.scss
  ui/packages/consul-ui/app/styles/components/pill.scss
  ui/packages/consul-ui/app/templates/dc/acls/auth-methods/show.hbs
  ui/packages/consul-ui/app/templates/dc/acls/auth-methods/show/auth-method.hbs
  ui/packages/consul-ui/mock-api/v1/acl/auth-method/_
  ui/packages/consul-ui/mock-api/v1/acl/auth-methods
  ui/packages/consul-ui/tests/acceptance/dc/acls/auth-methods/navigation.feature
  ui/packages/consul-ui/tests/acceptance/steps/dc/acls/auth-methods/navigation-steps.js
  ui/packages/consul-ui/tests/pages.js
  ui/packages/consul-ui/translations/en-us.yaml
Labels: pr/no-changelog, theme/ui

#9875 ui: Improves UI engineering docs
  ui/packages/consul-ui/.docfy-config.js
  ui/packages/consul-ui/app/components/auth-dialog/README.mdx
  ui/packages/consul-ui/app/components/auth-form/README.mdx
  ui/packages/consul-ui/app/components/auth-profile/README.mdx
  ui/packages/consul-ui/app/components/consul/loader/README.mdx
  ui/packages/consul-ui/app/components/consul/lock-session/list/README.mdx
  ui/packages/consul-ui/app/components/consul/metadata/list/README.mdx
  ui/packages/consul-ui/app/components/consul/nspace/list/README.mdx
  ui/packages/consul-ui/app/components/consul/policy/list/README.mdx
  ui/packages/consul-ui/app/components/consul/role/list/README.mdx
  ui/packages/consul-ui/app/components/consul/token/list/README.mdx
  ui/packages/consul-ui/app/components/consul/token/ruleset/list/README.mdx
  ui/packages/consul-ui/app/components/copy-button/README.mdx
  ui/packages/consul-ui/app/components/data-collection/README.mdx
  ui/packages/consul-ui/app/components/data-sink/README.mdx
  ui/packages/consul-ui/app/components/event-source/README.mdx
  ui/packages/consul-ui/app/components/jwt-source/README.mdx
  ui/packages/consul-ui/app/components/ref/README.mdx
  ui/packages/consul-ui/app/components/state-chart/README.mdx
  ui/packages/consul-ui/app/components/state/README.mdx
  ui/packages/consul-ui/app/components/toggle-button/README.mdx
  ui/packages/consul-ui/app/components/token-source/README.mdx
  ui/packages/consul-ui/app/helpers/flatten-property.js
  ui/packages/consul-ui/app/helpers/is-href.mdx
  ui/packages/consul-ui/app/helpers/to-route.js
  ui/packages/consul-ui/app/instance-initializers/selection.js
  ui/packages/consul-ui/app/modifiers/disabled.mdx
  ui/packages/consul-ui/app/modifiers/tooltip.mdx
  ui/packages/consul-ui/app/modifiers/with-overlay.js
  ui/packages/consul-ui/app/modifiers/with-overlay.mdx
  ui/packages/consul-ui/app/services/env.mdx
  ui/packages/consul-ui/app/styles/base/icons/base-variables.scss
  ui/packages/consul-ui/app/styles/base/icons/icon-placeholders.scss
  ui/packages/consul-ui/app/styles/debug.scss
  ui/packages/consul-ui/app/templates/debug.hbs
  ui/packages/consul-ui/docs/bookmarklets.mdx
  ui/packages/consul-ui/docs/index.mdx
  ui/packages/consul-ui/docs/significant-patterns.mdx
  ui/packages/consul-ui/package.json
  ui/yarn.lock
Labels: pr/no-changelog, theme/ui

#9863 state: move ConfigEntryKindName
  agent/consul/leader_intentions_test.go
  agent/consul/state/config_entry.go
  agent/consul/state/config_entry_test.go
  agent/structs/config_entry.go
Labels: pr/no-changelog

#9881 state: convert services.node and checks.node indexes
  agent/consul/state/catalog.go
  agent/consul/state/catalog_events.go
  agent/consul/state/catalog_oss.go
  agent/consul/state/catalog_oss_test.go
  agent/consul/state/catalog_schema.go
  agent/consul/state/schema_test.go
  agent/consul/state/testdata/TestStateStoreSchema.golden
  agent/structs/identity.go
  agent/structs/structs.go
Labels: pr/no-changelog

#9865 state: convert config-entries table to the new pattern of functional indexers
  agent/consul/state/config_entry.go
  agent/consul/state/config_entry_intention.go
  agent/consul/state/config_entry_oss.go
  agent/consul/state/config_entry_oss_test.go
  agent/consul/state/config_entry_schema.go
  agent/consul/state/indexer.go
  agent/consul/state/intention.go
  agent/consul/state/schema_test.go
  agent/consul/state/testdata/TestStateStoreSchema.golden
Labels: pr/no-changelog

#9872 Create new types for service-defaults upstream cfg
  .changelog/9872.txt
  agent/consul/config_endpoint.go
  agent/consul/config_endpoint_test.go
  agent/service_manager.go
  agent/service_manager_test.go
  agent/structs/config_entry.go
  agent/structs/config_entry_test.go
  agent/xds/clusters.go
  agent/xds/config.go
  agent/xds/config_test.go
  agent/xds/endpoints.go
  agent/xds/listeners.go
  api/config_entry.go
  api/config_entry_test.go
  command/config/write/config_write_test.go
Labels: theme/api, theme/cli, theme/envoy/xds

#9873 Add TransparentProxy opt to proxy definition
  agent/agent_endpoint_test.go
  agent/config/builder.go
  agent/config/config.go
  agent/config/runtime_test.go
  agent/config/testdata/full-config.hcl
  agent/config/testdata/full-config.json
  agent/consul/config_endpoint.go
  agent/consul/config_endpoint_test.go
  agent/service_manager.go
  agent/service_manager_test.go
  agent/structs/config_entry.go
  agent/structs/connect_proxy_config.go
  agent/structs/structs_filtering_test.go
  api/agent.go
  api/agent_test.go
  api/config_entry.go
  api/config_entry_test.go
  command/config/write/config_write_test.go
  proto/pbservice/service.gen.go
  proto/pbservice/service.pb.go
  proto/pbservice/service.proto
Labels: theme/api, theme/cli, theme/config

#9877 Add RPC endpoint to compute upstreams from intentions
  agent/connect/authz.go
  agent/connect/authz_test.go
  agent/connect/uri.go
  agent/connect/uri_agent.go
  agent/connect/uri_agent_test.go
  agent/connect/uri_service.go
  agent/connect/uri_service_test.go
  agent/connect/uri_signing.go
  agent/connect/uri_signing_test.go
  agent/connect_auth.go
  agent/consul/catalog_endpoint.go
  agent/consul/helper_test.go
  agent/consul/intention_endpoint.go
  agent/consul/internal_endpoint.go
  agent/consul/internal_endpoint_test.go
  agent/consul/state/catalog.go
  agent/consul/state/intention.go
  agent/consul/state/intention_test.go
Labels: pr/no-changelog

#9894 Update proxycfg state management and xDS generation for transparent proxy
  .changelog/9894.txt
  agent/agent.go
  agent/cache-types/intention_upstreams.go
  agent/cache-types/intention_upstreams_test.go
  agent/consul/state/intention.go
  agent/consul/state/intention_test.go
  agent/proxycfg/manager_test.go
  agent/proxycfg/snapshot.go
  agent/proxycfg/state.go
  agent/proxycfg/state_test.go
  agent/proxycfg/testing.go
  agent/service_manager.go
  agent/structs/config_entry.go
  agent/structs/config_entry_test.go
  agent/structs/connect_proxy_config.go
  agent/xds/clusters.go
  agent/xds/clusters_test.go
  agent/xds/endpoints.go
  agent/xds/endpoints_test.go
  agent/xds/listeners.go
  agent/xds/listeners_test.go
  agent/xds/routes.go
  agent/xds/server.go
  agent/xds/testdata/clusters/transparent-proxy.envoy-1-17-x.golden
  agent/xds/testdata/clusters/transparent-proxy.v2compat.envoy-1-17-x.golden
  agent/xds/testdata/listeners/transparent-proxy.envoy-1-17-x.golden
  agent/xds/testdata/listeners/transparent-proxy.v2compat.envoy-1-17-x.golden
Labels: theme/envoy/xds

#9899 Add methods to check intention has wildcard src or dst
  agent/consul/state/intention.go
  agent/structs/structs_oss.go
  agent/structs/structs_oss_test.go
Labels: pr/no-changelog

#9900 Fixup enterprise tests from tproxy changes
  agent/consul/config_endpoint_test.go
  agent/proxycfg/state_test.go
  agent/service_manager_test.go
  agent/structs/config_entry_test.go
Labels: pr/no-changelog

#9888 ui: Add all tooltips to the default tabbing order in the page
  ui/packages/consul-ui/app/modifiers/tooltip.js
  ui/packages/consul-ui/app/modifiers/tooltip.mdx
Labels: pr/no-changelog, theme/ui

#9895 ui: Updates to auth-method show page
  ui/packages/consul-ui/app/components/certificate/index.hbs
  ui/packages/consul-ui/app/components/certificate/index.scss
  ui/packages/consul-ui/app/components/consul/auth-method/view/index.hbs
  ui/packages/consul-ui/app/styles/components/empty-state/layout.scss
  ui/packages/consul-ui/app/styles/components/empty-state/skin.scss
  ui/packages/consul-ui/mock-api/v1/acl/auth-method/_
Labels: pr/no-changelog, theme/ui

#9882 state: use constants and add indexer tests for gateway tables
  agent/consul/state/catalog.go
  agent/consul/state/catalog_events.go
  agent/consul/state/catalog_oss_test.go
  agent/consul/state/catalog_schema.go
  agent/consul/state/config_entry.go
  agent/consul/state/schema_test.go
  agent/structs/structs.go
Labels: pr/no-changelog

#9890 Removing unnecessary comment
  website/content/api-docs/agent/connect.mdx
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#8564 support env var expansion in envoy statsd urls
  .changelog/8564.txt
  command/connect/envoy/bootstrap_config.go
  command/connect/envoy/bootstrap_config_test.go
  website/content/docs/connect/proxies/envoy.mdx
Labels: theme/connect, theme/telemetry, type/enhancement

#9848 Add metrics documentation
  website/content/docs/connect/observability/index.mdx
  website/content/docs/connect/observability/ui-visualization.mdx
  website/content/docs/k8s/connect/index.mdx
  website/content/docs/k8s/connect/observability/metrics.mdx
  website/content/docs/k8s/helm.mdx
  website/data/docs-navigation.js
  website/public/img/metrics-arch.png
  website/public/img/ui-topology.png
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#9907 ui: Dependency Upgrade
  ui/package.json
  ui/packages/consul-ui/app/templates/application.hbs
  ui/packages/consul-ui/app/templates/debug.hbs
  ui/packages/consul-ui/package.json
  ui/packages/consul-ui/tests/dictionary.js
  ui/yarn.lock
Labels: pr/no-changelog, theme/ui

#9901 ui: Ensure intention form cancel button works
  .changelog/9901.txt
  ui/packages/consul-ui/app/components/consul/intention/form/index.js
Labels: backport/1.9, theme/ui

#9904 docs: Update Helm reference docs
  website/content/docs/k8s/helm.mdx
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#9866 state: convert services.ID to the new pattern of functional indexers
  agent/consul/state/catalog.go
  agent/consul/state/catalog_events.go
  agent/consul/state/catalog_oss.go
  agent/consul/state/catalog_oss_test.go
  agent/consul/state/catalog_schema.go
  agent/consul/state/catalog_test.go
  agent/consul/state/indexer.go
  agent/consul/state/state_store_test.go
  agent/consul/state/testdata/TestStateStoreSchema.golden
Labels: pr/no-changelog

#9903 api: enable query options on agent endpoints
  .changelog/9903.txt
  api/agent.go
  api/agent_test.go
Labels: theme/api

#9885 state: convert acl-policies table to new functional indexer pattern
  agent/consul/state/acl.go
  agent/consul/state/acl_events.go
  agent/consul/state/acl_oss.go
  agent/consul/state/acl_oss_test.go
  agent/consul/state/acl_schema.go
  agent/consul/state/acl_test.go
  agent/consul/state/catalog_oss.go
  agent/consul/state/query_oss.go
  agent/consul/state/schema_test.go
  agent/consul/state/testdata/TestStateStoreSchema.golden
Labels: pr/no-changelog

#9909 docs/nia: Update CTS configuration example for terraform providers
  website/content/docs/nia/configuration.mdx
Labels: backport/1.9, theme/consul-terraform-sync, type/docs, type/docs-cherrypick

#9606 introduce certopts
  agent/consul/server_test.go
  agent/pool/peek_test.go
  agent/routine-leak-checker/leak_test.go
  agent/testagent.go
  command/tls/cert/create/tls_cert_create.go
  tlsutil/generate.go
  tlsutil/generate_test.go
Labels: backport/1.8, backport/1.9, pr/no-changelog, theme/certificates, theme/cli, theme/tls

#9912 fix(changelog-checker): remove period to fix broken link
  .github/workflows/changelog-checker.yml
Labels: pr/no-changelog, theme/contributing

#9897 Retroactive Chagelog update for header fix
  CHANGELOG.md
Labels: backport/1.9, pr/no-changelog

#9915 Update CHANGELOG.md
  CHANGELOG.md
Labels: pr/no-changelog

#9905 Update telemetry docs
  website/content/docs/agent/telemetry.mdx
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#9908 ui: Add a README to the new Certificate component
  ui/packages/consul-ui/app/components/certificate/README.mdx
Labels: pr/no-changelog, theme/ui

#9918 docs/nia: consul compatibilty
  website/content/docs/nia/compatibility.mdx
  website/content/docs/nia/installation/requirements.mdx
  website/data/docs-navigation.js
Labels: theme/consul-terraform-sync, type/docs

#9919 docs/nia: remove beta callouts
  website/content/docs/nia/index.mdx
  website/content/docs/nia/terraform-modules.mdx
  website/content/docs/security/security-models/nia.mdx
Labels: theme/consul-terraform-sync, type/docs

#9893 Cross linking Learn tutorials
  website/content/docs/nia/architecture.mdx
  website/content/docs/nia/configuration.mdx
  website/content/docs/nia/index.mdx
  website/content/docs/nia/installation/install.mdx
  website/content/docs/nia/installation/run.mdx
  website/content/docs/security/security-models/nia.mdx
Labels: pr/no-changelog, theme/consul-terraform-sync, type/docs, type/docs-cherrypick

#9916 state: convert checks.ID index to the functional indexer pattern
  agent/consul/state/catalog.go
  agent/consul/state/catalog_oss.go
  agent/consul/state/catalog_oss_test.go
  agent/consul/state/catalog_schema.go
  agent/consul/state/catalog_test.go
  agent/consul/state/operations_oss.go
  agent/consul/state/session_oss.go
  agent/consul/state/state_store_test.go
  agent/consul/state/testdata/TestStateStoreSchema.golden
Labels: pr/no-changelog

#9911 state: convert ACLRoles policies index to new functional indexer pattern
  agent/consul/state/acl.go
  agent/consul/state/acl_events.go
  agent/consul/state/acl_oss.go
  agent/consul/state/acl_oss_test.go
  agent/consul/state/acl_schema.go
  agent/consul/state/acl_test.go
  agent/consul/state/catalog.go
  agent/consul/state/indexer.go
  agent/consul/state/query.go
  agent/consul/state/query_oss.go
  agent/consul/state/schema_test.go
  agent/consul/state/testdata/TestStateStoreSchema.golden
Labels: pr/no-changelog

#9923 http: fix a bug that would cause runtimeConfig to be cached
  .changelog/9923.txt
  agent/http.go
  agent/http_oss.go
  agent/uiserver/uiserver.go
  agent/uiserver/uiserver_test.go
Labels: backport/1.9

#9928 Cherrypick NIA doc cross linking
  website/content/docs/nia/architecture.mdx
  website/content/docs/nia/configuration.mdx
  website/content/docs/nia/index.mdx
  website/content/docs/nia/installation/install.mdx
  website/content/docs/nia/installation/run.mdx
  website/content/docs/security/security-models/nia.mdx
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#7324 agent: Prune Unused Test Helper Functions
  agent/agent_endpoint_test.go
Labels: pr/no-changelog

#9917 Document agent token policy requirement for rexec
  website/content/commands/exec.mdx
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#9914 ui: Auth Methods - Create Binding Rules tab
  ui/packages/consul-ui/app/adapters/binding-rule.js
  ui/packages/consul-ui/app/components/consul/auth-method/binding-list/index.hbs
  ui/packages/consul-ui/app/components/consul/auth-method/index.scss
  ui/packages/consul-ui/app/components/tooltip/index.scss
  ui/packages/consul-ui/app/models/binding-rule.js
  ui/packages/consul-ui/app/router.js
  ui/packages/consul-ui/app/routes/dc/acls/auth-methods/show.js
  ui/packages/consul-ui/app/routes/dc/acls/auth-methods/show/binding-rules.js
  ui/packages/consul-ui/app/serializers/binding-rule.js
  ui/packages/consul-ui/app/services/repository/binding-rule.js
  ui/packages/consul-ui/app/styles/base/reset/system.scss
  ui/packages/consul-ui/app/styles/components.scss
  ui/packages/consul-ui/app/styles/components/tabular-dl/index.scss
  ui/packages/consul-ui/app/styles/components/tabular-dl/layout.scss
  ui/packages/consul-ui/app/styles/components/tabular-dl/skin.scss
  ui/packages/consul-ui/app/templates/dc/acls/auth-methods/show.hbs
  ui/packages/consul-ui/app/templates/dc/acls/auth-methods/show/binding-rules.hbs
  ui/packages/consul-ui/mock-api/v1/acl/binding-rules
  ui/packages/consul-ui/tests/integration/adapters/binding-rule-test.js
  ui/packages/consul-ui/tests/integration/serializers/binding-rule-test.js
  ui/packages/consul-ui/tests/unit/adapters/binding-rule-test.js
  ui/packages/consul-ui/tests/unit/serializers/binding-rule-test.js
  ui/packages/consul-ui/translations/en-us.yaml
Labels: pr/no-changelog, theme/ui

#9938 Add Avi Network, AWS ALB and NS1 TF Registries and GitHub links
  website/content/docs/nia/installation/requirements.mdx
Labels: theme/consul-terraform-sync, type/docs, type/docs-cherrypick

#9937 Add link to TF module tutorial and example TF modules
  website/content/docs/integrate/nia-integration.mdx
Labels: theme/consul-terraform-sync, type/docs, type/docs-cherrypick

#9896 website: add should-build script
  website/package-lock.json
  website/package.json
  website/scripts/should-build.sh
Labels: type/docs, type/docs-cherrypick

#9946 nia/docs 0.1.0 ga
  website/content/docs/nia/compatibility.mdx
  website/content/docs/nia/index.mdx
  website/content/docs/nia/installation/requirements.mdx
  website/content/docs/nia/terraform-modules.mdx
  website/content/docs/security/security-models/nia.mdx
  website/data/docs-navigation.js
Labels: pr/no-changelog, theme/consul-terraform-sync, type/docs, type/docs-cherrypick

#9932 Set default enterprise meta in test case
  agent/agent_endpoint_test.go
Labels: pr/no-changelog

#9934 Docs: add enterprise upgrade link
  website/content/docs/upgrading/index.mdx
Labels: pr/no-changelog, type/docs, type/docs-cherrypick

#9935 ui: Auth Methods - Namespace rules tab
  ui/packages/consul-ui/app/components/consul/auth-method/index.scss
  ui/packages/consul-ui/app/components/consul/auth-method/nspace-list/index.hbs
  ui/packages/consul-ui/app/models/auth-method.js
  ui/packages/consul-ui/app/router.js
  ui/packages/consul-ui/app/routes/dc/acls/auth-methods/show/nspace-rules.js
  ui/packages/consul-ui/app/templates/dc/acls/auth-methods/show.hbs
  ui/packages/consul-ui/app/templates/dc/acls/auth-methods/show/nspace-rules.hbs
  ui/packages/consul-ui/mock-api/v1/acl/auth-method/_
  ui/packages/consul-ui/translations/en-us.yaml
Labels: pr/no-changelog, theme/ui

#9947 state: move indexer functions out of oss files
  agent/consul/state/acl_oss.go
  agent/consul/state/acl_schema.go
  agent/consul/state/catalog.go
  agent/consul/state/catalog_oss.go
  agent/consul/state/catalog_schema.go
  agent/consul/state/config_entry_oss.go
  agent/consul/state/config_entry_schema.go
  agent/consul/state/indexer.go
  agent/consul/state/query.go
  agent/consul/state/query_oss.go
  agent/consul/state/schema_test.go
  agent/consul/state/testdata/TestStateStoreSchema.golden
Labels: pr/no-changelog

#9948 state: convert remaining services table indexers to functions
  agent/consul/state/catalog.go
  agent/consul/state/catalog_events.go
  agent/consul/state/catalog_oss.go
  agent/consul/state/catalog_oss_test.go
  agent/consul/state/catalog_schema.go
  agent/consul/state/catalog_test.go
  agent/consul/state/index_connect.go
  agent/consul/state/index_connect_test.go
  agent/consul/state/index_service_kind.go
  agent/consul/state/state_store_test.go
  agent/consul/state/usage.go
Labels: pr/no-changelog

#9949 state: convert remaining checks table indexers to functional pattern
  agent/consul/state/catalog.go
  agent/consul/state/catalog_events.go
  agent/consul/state/catalog_oss.go
  agent/consul/state/catalog_oss_test.go
  agent/consul/state/catalog_schema.go
  agent/consul/state/catalog_test.go
Labels: pr/no-changelog

#9956 Backport enterprise changes to prevent merge conflicts
  agent/consul/state/query.go
  agent/consul/state/schema_oss_test.go
  agent/consul/state/schema_test.go
  proto/pbcommon/common.pb.go
  proto/pbcommon/common.proto
Labels: pr/no-changelog

#9955 website(homepage changes): Callouts
  website/package-lock.json
  website/package.json
  website/pages/home/img/kubernetes/communication-arrows.svg
  website/pages/home/img/kubernetes/logo.svg
  website/pages/home/index.jsx
  website/pages/home/style.css
  website/pages/style.css
Labels: type/docs

#9957 website(homepage changes): "Why Consul?" changes
  website/pages/home/index.jsx
Labels: type/docs
