Repository hashicorp/consul, pull requests merged in 2021-02, with the labels that each got.

#9666 ui: Adds a `Routes()` router DSL dumping function only in dev mode
  ui/packages/consul-ui/README.md
  ui/packages/consul-ui/app/router.js
  ui/packages/consul-ui/app/utils/routing/walk.js
Labels: theme/ui

#9675 ui: Add 'Scenario' debug function for easy saving debug scenarios
  ui/packages/consul-ui/README.md
  ui/packages/consul-ui/app/utils/get-environment.js
Labels: theme/ui

#9680 Release 1.9.3
  CHANGELOG.md
  website/data/version.js
Labels: type/docs

#9641 ci: add script to check for .changelog file in PRs
  .github/workflows/changelog-check.yml
Labels: type/ci

#9676 ui: Adds unique-id helper
  ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs
  ui/packages/consul-ui/app/components/hashicorp-consul/index.js
  ui/packages/consul-ui/app/helpers/unique-id.js
Labels: theme/ui

#9677 website: 2/2 Updates for HCP
  website/components/basic-hero/index.jsx
  website/components/basic-hero/style.css
  website/components/enterprise-comparison/consul/index.jsx
  website/components/enterprise-comparison/index.jsx
  website/components/hcp-callout-section/HCPCalloutSection.module.css
  website/components/hcp-callout-section/index.jsx
  website/components/subnav/index.jsx
  website/data/alert-banner.js
  website/pages/home/img/hcp-consul.svg
  website/pages/home/index.jsx
Labels: type/docs, type/docs-cherrypick

#9684 docs/nia: Update verbiage around securely configuring providers
  website/content/docs/nia/configuration.mdx
Labels: theme/consul-terraform-sync, type/docs, type/docs-cherrypick

#9688 ci: fix changelog check checkout
  .github/workflows/changelog-check.yml
Labels: theme/contributing

#9691 docs/nia: Add link to template repository for building CTS module
  website/content/docs/nia/installation/requirements.mdx
Labels: theme/consul-terraform-sync, type/docs

#9692 docs/nia: recommend sensitive variables for module authoring
  website/content/docs/nia/installation/requirements.mdx
Labels: theme/consul-terraform-sync, type/docs, type/docs-cherrypick

#9694 ci: fix pr file checker
  .github/workflows/pr-file-checker.yml
Labels: theme/contributing

#9693 ci: add nightly load testing on master
  .circleci/config.yml
Labels: type/ci

#9705 docs: Small change to fix broken link to k8s upgrade from k8s tls certs page
  website/content/docs/k8s/operations/certificate-rotation.mdx
Labels: type/docs, type/docs-cherrypick

#9707 docs: fix another broken link to upgrading k8s servers from token rot…
  website/content/docs/k8s/operations/certificate-rotation.mdx
Labels: type/docs, type/docs-cherrypick

#7623 Add support for RSA private key to TLS utils.
  tlsutil/generate.go
  tlsutil/generate_test.go
Labels: theme/certificates, type/enhancement

#9701 state: Remove extra entMeta arg to EnsureConfigEntry
  agent/consul/config_endpoint_test.go
  agent/consul/fsm/commands_oss.go
  agent/consul/fsm/snapshot_oss_test.go
  agent/consul/state/catalog_test.go
  agent/consul/state/config_entry.go
  agent/consul/state/config_entry_test.go
  agent/consul/state/intention.go
  agent/consul/state/intention_test.go
Labels: theme/internal-cleanup

#9664 state: move ACL schema and index definitions to acl_schema.go
  agent/consul/state/acl_oss.go
  agent/consul/state/acl_schema.go
  agent/consul/state/catalog_schema.go
Labels: theme/internal-cleanup

#9711 ci: escape backticks in github comment for website/ change check
  .github/workflows/pr-file-checker.yml
Labels: theme/contributing

#9718 state: convert all table name constants to the new prefix pattern
  agent/consul/state/catalog.go
  agent/consul/state/catalog_oss.go
  agent/consul/state/catalog_schema.go
  agent/consul/state/config_entry.go
  agent/consul/state/connect_ca.go
  agent/consul/state/connect_ca_test.go
  agent/consul/state/federation_state.go
  agent/consul/state/intention.go
  agent/consul/state/intention_oss.go
  agent/consul/state/intention_test.go
  agent/consul/state/system_metadata.go
  agent/consul/state/usage.go
Labels: theme/internal-cleanup

#9719 state: remove registerSchema
  agent/consul/state/acl.go
  agent/consul/state/autopilot.go
  agent/consul/state/catalog_schema.go
  agent/consul/state/config_entry.go
  agent/consul/state/connect_ca.go
  agent/consul/state/coordinate.go
  agent/consul/state/federation_state.go
  agent/consul/state/intention.go
  agent/consul/state/kvs.go
  agent/consul/state/prepared_query.go
  agent/consul/state/schema.go
  agent/consul/state/schema_test.go
  agent/consul/state/session.go
  agent/consul/state/state_store.go
  agent/consul/state/system_metadata.go
  agent/consul/state/usage.go
Labels: theme/internal-cleanup

#9650 xds: deduplicate mesh gateway listeners in a stable way
  .changelog/9650.txt
  agent/xds/listeners.go
  agent/xds/listeners_test.go
Labels: backport/1.7, backport/1.8, backport/1.9, theme/envoy/xds

#9722 Fix main build failing
  tlsutil/generate_test.go
Labels: theme/certificates, theme/tls

#9651 xds: prevent LDS flaps in mesh gateways due to unstable datacenter lists
  .changelog/9651.txt
  agent/proxycfg/snapshot.go
  agent/xds/listeners.go
  agent/xds/listeners_test.go
Labels: backport/1.8, backport/1.9, theme/envoy/xds

#9704 Learn microservices collection crosslinking
  website/content/docs/k8s/index.mdx
  website/content/docs/k8s/installation/install.mdx
  website/content/docs/k8s/installation/multi-cluster/kubernetes.mdx
Labels: type/docs-cherrypick

#9428 connect: connect CA Roots in the primary datacenter should use a SigningKeyID derived from their local intermediate
  .changelog/9428.txt
  GNUmakefile
  agent/agent_endpoint_test.go
  agent/consul/leader_connect_ca.go
  agent/consul/leader_connect_test.go
Labels: backport/1.8, backport/1.9, type/bug

#9689 Avoid potential proxycfg/xDS deadlock using non-blocking send
  .changelog/9689.txt
  agent/proxycfg/state.go
  agent/xds/server.go
  logging/names.go
Labels: backport/1.7, backport/1.8, backport/1.9

#9738 Stop background refresh of cached data for requests that result in ACL not found errors
  .changelog/9738.txt
  agent/cache/cache.go
  agent/cache/cache_test.go
Labels: backport/1.7, backport/1.8, backport/1.9, theme/agent-cache

#9698 website: update next and nextjs-scripts
  website/components/config-entry-reference/index.jsx
  website/package-lock.json
  website/package.json
Labels: type/docs, type/docs-cherrypick

#9742 Backport to release/1.8.x: #9738 - Stop background refresh of cached data for requests that result in ACL not found errors
  .changelog/9738.txt
  agent/cache/cache.go
  agent/cache/cache_test.go
  agent/xds/server.go
Labels: backport/1.7

#9745 streaming: fix a couple bugs
  agent/cache-types/streaming_health_services.go
  agent/health_endpoint.go
  agent/submatview/materializer.go
Labels: backport/1.9, theme/health-checks, theme/streaming, type/bug

#9737 connect: update supported envoy point releases to 1.16.2, 1.15.3, 1.14.6, 1.13.7
  .changelog/9737.txt
  .circleci/config.yml
  agent/xds/envoy_versioning_test.go
  agent/xds/proxysupport/proxysupport.go
  agent/xds/testdata/listeners/http-listener-with-timeouts.envoy-1-13-x.golden
  agent/xds/testdata/listeners/http-listener-with-timeouts.envoy-1-14-x.golden
  agent/xds/testdata/listeners/http-listener-with-timeouts.envoy-1-15-x.golden
  agent/xds/testdata/listeners/http-listener-with-timeouts.envoy-1-16-x.golden
  command/connect/envoy/testdata/CONSUL_HTTP_ADDR-with-https-scheme-enables-tls.golden
  command/connect/envoy/testdata/access-log-path.golden
  command/connect/envoy/testdata/defaults.golden
  command/connect/envoy/testdata/existing-ca-file.golden
  command/connect/envoy/testdata/existing-ca-path.golden
  command/connect/envoy/testdata/extra_-multiple.golden
  command/connect/envoy/testdata/extra_-single.golden
  command/connect/envoy/testdata/grpc-addr-config.golden
  command/connect/envoy/testdata/grpc-addr-env.golden
  command/connect/envoy/testdata/grpc-addr-flag.golden
  command/connect/envoy/testdata/grpc-addr-unix.golden
  command/connect/envoy/testdata/ingress-gateway-address-specified.golden
  command/connect/envoy/testdata/ingress-gateway-no-auto-register.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-and-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-without-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway.golden
  command/connect/envoy/testdata/stats-config-override.golden
  command/connect/envoy/testdata/token-arg.golden
  command/connect/envoy/testdata/token-env.golden
  command/connect/envoy/testdata/token-file-arg.golden
  command/connect/envoy/testdata/token-file-env.golden
  command/connect/envoy/testdata/zipkin-tracing-config.golden
  test/integration/connect/envoy/run-tests.sh
  test/integration/connect/envoy/test-envoy-versions.sh
  website/content/commands/connect/envoy.mdx
  website/content/docs/connect/proxies/envoy.mdx
Labels: backport/1.9, theme/cli, theme/envoy/xds, type/ci, type/docs

#9753 [1.9.x] connect: update supported envoy point releases to 1.16.2, 1.15.3, 1.14.6, 1.13.7
  .changelog/9737.txt
  .circleci/config.yml
  agent/xds/envoy_versioning_test.go
  agent/xds/proxysupport/proxysupport.go
  command/connect/envoy/testdata/CONSUL_HTTP_ADDR-with-https-scheme-enables-tls.golden
  command/connect/envoy/testdata/access-log-path.golden
  command/connect/envoy/testdata/defaults.golden
  command/connect/envoy/testdata/existing-ca-file.golden
  command/connect/envoy/testdata/existing-ca-path.golden
  command/connect/envoy/testdata/extra_-multiple.golden
  command/connect/envoy/testdata/extra_-single.golden
  command/connect/envoy/testdata/grpc-addr-config.golden
  command/connect/envoy/testdata/grpc-addr-env.golden
  command/connect/envoy/testdata/grpc-addr-flag.golden
  command/connect/envoy/testdata/grpc-addr-unix.golden
  command/connect/envoy/testdata/ingress-gateway-address-specified.golden
  command/connect/envoy/testdata/ingress-gateway-no-auto-register.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-and-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-without-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway.golden
  command/connect/envoy/testdata/stats-config-override.golden
  command/connect/envoy/testdata/token-arg.golden
  command/connect/envoy/testdata/token-env.golden
  command/connect/envoy/testdata/token-file-arg.golden
  command/connect/envoy/testdata/token-file-env.golden
  command/connect/envoy/testdata/zipkin-tracing-config.golden
  test/integration/connect/envoy/run-tests.sh
  test/integration/connect/envoy/test-envoy-versions.sh
  website/content/commands/connect/envoy.mdx
  website/content/docs/connect/proxies/envoy.mdx
Labels: theme/cli, theme/envoy/xds, type/ci, type/docs

#9715 ui: [BUGFIX] Replace all replaceAll with split.join for older browsers without replaceAll
  .changelog/9715.txt
  ui/packages/consul-ui/app/components/form-group/element/index.js
  ui/packages/consul-ui/app/components/freetext-filter/index.hbs
  ui/packages/consul-ui/app/components/freetext-filter/layout.scss
  ui/packages/consul-ui/app/utils/intl/missing-message.js
Labels: backport/1.9, theme/ui, type/bug

#9729 ui: Update browser targets
  .changelog/9729.txt
  ui/packages/consul-ui/config/targets.js
  ui/packages/consul-ui/ember-cli-build.js
  ui/packages/consul-ui/package.json
  ui/yarn.lock
Labels: theme/ui

#9749 ui: [BUGFIX] Ensure we show the correct count of instances for each node
  .changelog/9749.txt
  ui/packages/consul-ui/app/components/consul/instance-checks/index.hbs
  ui/packages/consul-ui/app/components/consul/node/list/index.hbs
  ui/packages/consul-ui/app/models/node.js
  ui/packages/consul-ui/app/templates/dc/nodes/show/services.hbs
Labels: backport/1.9, theme/ui, type/bug

#9709 Add docs section on regenerating expired CA certificates
  website/content/commands/tls/ca.mdx
  website/content/docs/connect/ca/index.mdx
Labels: type/docs, type/docs-cherrypick

#9758 http: error if near is used with streaming
  agent/health_endpoint.go
  website/content/api-docs/health.mdx
Labels: backport/1.9, theme/health-checks, theme/streaming, type/docs

#9728 state: document how index table is used
  agent/consul/state/acl.go
  agent/consul/state/catalog.go
  agent/consul/state/catalog_oss.go
  agent/consul/state/kvs_oss.go
  agent/consul/state/schema.go
  agent/consul/state/state_store.go
Labels: theme/internal-cleanup

#9772 streaming: fix snapshot cache bug
  .changelog/9772.txt
  agent/consul/stream/event_publisher.go
  agent/consul/stream/event_publisher_test.go
Labels: backport/1.9, theme/streaming, type/bug

#9663 Update go-memdb
  go.mod
  go.sum
  vendor/github.com/hashicorp/go-memdb/filter.go
  vendor/github.com/hashicorp/go-memdb/txn.go
  vendor/modules.txt
Labels: pr/dependencies

#9720 structs: rename EnterpriseMeta constructor
  agent/cache-types/streaming_health_services_test.go
  agent/consul/state/catalog.go
  agent/consul/state/catalog_events.go
  agent/consul/state/catalog_events_test.go
  agent/consul/state/config_entry.go
  agent/rpc/subscribe/subscribe.go
  agent/structs/structs_oss.go
  agent/txn_endpoint.go
Labels: theme/internal-cleanup

#9452 config: make TestBuilder_BuildAndValidate_ConfigFlagsAndEdgecases easier to work with
  agent/config/builder.go
  agent/config/builder_test.go
  agent/config/runtime_test.go
  agent/config/segment_oss_test.go
  contributing/checklist-adding-config-fields.md
Labels: theme/config

#9696 Add docs for MIME sniffing on metrics endpoint.
  website/content/api-docs/agent/index.mdx
Labels: type/docs, type/docs-cherrypick

#9773 Bump components to remove client-side md processing
  website/package-lock.json
  website/package.json
  website/pages/community/index.jsx
  website/pages/community/style.css
  website/pages/style.css
Labels: type/docs-cherrypick

#9741 Add fields to the /acl/auth-methods endpoint.
  .changelog/9741.txt
  agent/acl_endpoint_test.go
  agent/structs/acl.go
  api/acl.go
  api/acl_test.go
Labels: theme/api

#9761 ui: Use ember-on-resize-modifier to fix bug with sidebar
  ui/packages/consul-ui/app/components/topology-metrics/down-lines/index.hbs
  ui/packages/consul-ui/app/components/topology-metrics/index.hbs
  ui/packages/consul-ui/app/components/topology-metrics/index.js
  ui/packages/consul-ui/app/components/topology-metrics/layout.scss
  ui/packages/consul-ui/app/components/topology-metrics/up-lines/index.hbs
Labels: theme/ui

#9562 Docs describing migrating to CRDs
  website/content/docs/k8s/connect/index.mdx
  website/content/docs/k8s/crds/upgrade-to-crds.mdx
  website/content/docs/k8s/helm.mdx
  website/content/docs/k8s/installation/install.mdx
  website/content/docs/k8s/installation/multi-cluster/kubernetes.mdx
  website/content/docs/k8s/installation/multi-cluster/vms-and-kubernetes.mdx
Labels: type/docs, type/docs-cherrypick

#9779 Update helm docs for consul-helm v0.30.0
  website/content/docs/k8s/helm.mdx
Labels: type/docs, type/docs-cherrypick

#9782 Remove jfrog references
  test/integration/connect/envoy/Dockerfile-bats
  test/integration/connect/envoy/Dockerfile-consul-envoy
Labels: pr/no-changelog

#9783 remove reference to docker/ path for old docker mirror
  test/integration/connect/envoy/Dockerfile-bats
Labels: backport/1.7, backport/1.8, backport/1.9, pr/no-changelog

#9706 ui: Implement read-only KV/Session and Intention views based on ACLs
  ui/packages/consul-ui/README.md
  ui/packages/consul-ui/app/abilities/base.js
  ui/packages/consul-ui/app/abilities/intention.js
  ui/packages/consul-ui/app/abilities/session.js
  ui/packages/consul-ui/app/components/consul/intention/form/index.hbs
  ui/packages/consul-ui/app/components/consul/intention/list/table/index.hbs
  ui/packages/consul-ui/app/components/consul/kv/form/index.hbs
  ui/packages/consul-ui/app/components/consul/kv/list/index.hbs
  ui/packages/consul-ui/app/components/consul/lock-session/form/index.hbs
  ui/packages/consul-ui/app/components/consul/lock-session/list/index.hbs
  ui/packages/consul-ui/app/components/topology-metrics/popover/index.hbs
  ui/packages/consul-ui/app/components/topology-metrics/popover/index.scss
  ui/packages/consul-ui/app/instance-initializers/nspace.js
  ui/packages/consul-ui/app/modifiers/disabled.js
  ui/packages/consul-ui/app/router.js
  ui/packages/consul-ui/app/routes/application.js
  ui/packages/consul-ui/app/routes/dc/kv/edit.js
  ui/packages/consul-ui/app/routing/route.js
  ui/packages/consul-ui/app/services/repository/permission.js
  ui/packages/consul-ui/app/styles/base/components/form-elements/skin.scss
  ui/packages/consul-ui/app/templates/dc/intentions/index.hbs
  ui/packages/consul-ui/app/templates/dc/kv/edit.hbs
  ui/packages/consul-ui/app/templates/dc/kv/index.hbs
  ui/packages/consul-ui/app/templates/dc/nodes/show/sessions.hbs
  ui/packages/consul-ui/app/templates/dc/services/show/intentions/index.hbs
  ui/packages/consul-ui/mock-api/v1/internal/acl/authorize
  ui/packages/consul-ui/tests/acceptance/dc/intentions/index.feature
  ui/packages/consul-ui/tests/acceptance/dc/kvs/edit.feature
  ui/packages/consul-ui/tests/acceptance/dc/kvs/index.feature
  ui/packages/consul-ui/tests/acceptance/steps/dc/kvs/index-steps.js
  ui/packages/consul-ui/tests/pages.js
  ui/packages/consul-ui/tests/pages/dc/kv/edit.js
  ui/packages/consul-ui/tests/steps.js
  ui/packages/consul-ui/tests/steps/doubles/model.js
Labels: theme/ui

#9785 ui: Add some acceptance testing around the Metrics graph
  ui/packages/consul-ui/app/components/topology-metrics/series/index.hbs
  ui/packages/consul-ui/tests/acceptance/dc/services/show/topology.feature
  ui/packages/consul-ui/tests/steps/assertions/dom.js
  ui/packages/consul-ui/tests/steps/doubles/model.js
Labels: theme/ui

#9787 [website] Update Learn Tutorials
  website/pages/home/index.jsx
Labels: type/docs, type/docs-cherrypick

#9777 docs: remove a couple deprecations
  website/content/api-docs/health.mdx
Labels: type/docs, type/docs-cherrypick

#9765 xds: only try to create an ipv6 expose checks listener if ipv6 is supported by the kernel
  .changelog/9765.txt
  agent/xds/listeners.go
  agent/xds/listeners_test.go
  agent/xds/net_fallback.go
  agent/xds/net_linux.go
  agent/xds/testdata/listeners/expose-checks.envoy-1-13-x.golden
  agent/xds/testdata/listeners/expose-checks.envoy-1-14-x.golden
  agent/xds/testdata/listeners/expose-checks.envoy-1-15-x.golden
  agent/xds/testdata/listeners/expose-checks.envoy-1-16-x.golden
  test/integration/connect/envoy/case-expose-checks/capture.sh
  test/integration/connect/envoy/case-expose-checks/service_s1.hcl
  test/integration/connect/envoy/case-expose-checks/service_s2.hcl
  test/integration/connect/envoy/case-expose-checks/setup.sh
  test/integration/connect/envoy/case-expose-checks/verify.bats
  test/integration/connect/envoy/helpers.bash
Labels: backport/1.7, backport/1.8, backport/1.9, theme/envoy/xds

#9763 cache: log a warning when Cache.Notify handles an error
  agent/cache/cache.go
  agent/cache/watch.go
  agent/config/testdata/TestRuntimeConfig_Sanitize.golden
  agent/setup.go
Labels: backport/1.9, theme/agent-cache, theme/internal-cleanup

#9793 ui: Add an optional environment variable to control how testem tests start
  ui/packages/consul-ui/testem.js
Labels: theme/ui

#9801 ui: Update authorization things to use new DataSource decorator/params interface
  ui/packages/consul-ui/app/adapters/permission.js
  ui/packages/consul-ui/app/routes/dc.js
  ui/packages/consul-ui/app/routes/dc/acls/auth-methods/index.js
  ui/packages/consul-ui/app/services/repository.js
  ui/packages/consul-ui/app/services/repository/auth-method.js
  ui/packages/consul-ui/app/services/repository/intention.js
  ui/packages/consul-ui/app/services/repository/kv.js
  ui/packages/consul-ui/app/services/repository/permission.js
  ui/packages/consul-ui/app/services/repository/service-instance.js
  ui/packages/consul-ui/tests/integration/services/repository/auth-method-test.js
Labels: theme/ui

#9717 [Website] Use new logo for Mercedes use case
  website/pages/home/img/quotes/mercedes-logo.svg
  website/pages/use-cases/img/mercedes-logo.svg
Labels: type/docs, type/docs-cherrypick

#9799 [docs] Consul intro
  website/content/docs/intro/index.mdx
Labels: type/docs, type/docs-cherrypick

#9806 connect: if the token given to the vault provider returns no data avoid a panic
  .changelog/9806.txt
  agent/connect/ca/provider_vault.go
Labels: backport/1.8, backport/1.9, theme/connect

#9808 docs: Fix code tag displaying on ACL binding rules
  website/content/api-docs/acl/binding-rules.mdx
Labels: type/docs, type/docs-cherrypick

#9817 example and default syslog CTS settings
  website/content/docs/nia/configuration.mdx
Labels: theme/consul-terraform-sync, type/docs

#9815 Update NIA Security Model for Beta
  website/content/docs/security/security-models/nia.mdx
Labels: type/docs, type/docs-cherrypick

#9775 ui: Blueprints update
  ui/packages/consul-ui/blueprints/adapter/files/__root__/__path__/__name__.js
  ui/packages/consul-ui/blueprints/model/files/__root__/__path__/__name__.js
  ui/packages/consul-ui/blueprints/repository/files/__root__/__path__/__name__.js
  ui/packages/consul-ui/blueprints/serializer/files/__root__/__path__/__name__.js
Labels: theme/ui

#9752 ui: Remove any trailing fullstop/period DNS characters from Gateways UI API
  .changelog/9752.txt
  agent/structs/config_entry_gateways.go
  agent/structs/config_entry_gateways_test.go
  agent/ui_endpoint_test.go
Labels: backport/1.8, backport/1.9, theme/ui

#9812 ui: Side navigation tweaks
  ui/packages/consul-ui/app/components/app/index.scss
  ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs
  ui/packages/consul-ui/app/components/main-nav-vertical/layout.scss
  ui/packages/consul-ui/app/components/main-nav-vertical/skin.scss
  ui/packages/consul-ui/app/components/menu-panel/skin.scss
  ui/packages/consul-ui/app/styles/base/color/frame-placeholders.scss
  ui/packages/consul-ui/app/styles/components.scss
  ui/packages/consul-ui/app/styles/components/footer.scss
  ui/packages/consul-ui/app/styles/components/footer/index.scss
  ui/packages/consul-ui/app/styles/components/footer/layout.scss
  ui/packages/consul-ui/app/styles/components/footer/skin.scss
  ui/packages/consul-ui/app/styles/layout.scss
  ui/packages/consul-ui/app/styles/layouts/containers.scss
  ui/packages/consul-ui/app/styles/layouts/index.scss
  ui/packages/consul-ui/app/styles/layouts/with-sticky-footer.scss
  ui/packages/consul-ui/app/styles/themes.scss
  ui/packages/consul-ui/app/styles/typography.scss
  ui/packages/consul-ui/app/styles/variables/custom-query.scss
Labels: theme/ui

#9828 docs/nia: update task api
  website/content/docs/nia/api/api-overview.mdx
  website/content/docs/nia/api/status.mdx
  website/content/docs/nia/api/tasks.mdx
  website/data/docs-navigation.js
Labels: theme/consul-terraform-sync, type/docs

#9826 add note about HTTP/2 support and setup
  website/content/docs/nia/configuration.mdx
  website/content/docs/nia/installation/requirements.mdx
Labels: theme/consul-terraform-sync, type/docs

#9833 docs/nia: api updates
  website/content/docs/nia/api/api-overview.mdx
  website/content/docs/nia/api/status.mdx
Labels: theme/consul-terraform-sync, type/docs

#9830 docs/nia: reorganize tf module details to top level nav
  website/content/docs/integrate/nia-integration.mdx
  website/content/docs/nia/architecture.mdx
  website/content/docs/nia/index.mdx
  website/content/docs/nia/installation/requirements.mdx
  website/content/docs/nia/network-drivers.mdx
  website/content/docs/nia/terraform-modules.mdx
  website/data/docs-navigation.js
Labels: theme/consul-terraform-sync, type/docs

#9703 Streaming filter tags + case insensitive lookups for Service Names
  .changelog/9703.txt
  agent/cache-types/streaming_health_services.go
  agent/cache-types/streaming_health_services_test.go
  agent/consul/state/catalog_events.go
  agent/dns.go
  agent/dns_test.go
  agent/health_endpoint_test.go
  agent/rpcclient/health/health.go
  agent/structs/structs.go
Labels: theme/streaming, type/bug

#9759 streaming: default rpc.enable_streaming to true
  agent/config/builder.go
  agent/config/runtime_test.go
  website/content/docs/agent/options.mdx
Labels: theme/config, theme/streaming, type/docs

#9188 Add more streaming tests
  agent/consul/state/catalog.go
  agent/consul/state/catalog_events.go
  agent/consul/state/catalog_events_test.go
  agent/consul/subscribe_backend_test.go
  agent/health_endpoint_test.go
  agent/rpc/subscribe/logger.go
  agent/testagent.go
  website/content/docs/agent/options.mdx
  website/content/docs/agent/telemetry.mdx
Labels: backport/1.9, theme/streaming, type/docs

#9781 update changelog and website checks
  .github/workflows/changelog-checker.yml
  .github/workflows/website-checker.yml
Labels: pr/no-changelog, theme/contributing
