Repository hashicorp/consul, pull requests merged in 2022-07, with the labels that each got.

#13651 ui: Adds initial peer detail page plus address tab
  ui/packages/consul-ui/app/abilities/peer.js
  ui/packages/consul-ui/app/components/consul/peer/address/list/index.hbs
  ui/packages/consul-ui/app/models/peer.js
  ui/packages/consul-ui/app/services/repository/peer.js
  ui/packages/consul-ui/app/templates/dc/peers/edit.hbs
  ui/packages/consul-ui/app/templates/dc/peers/edit/addresses.hbs
  ui/packages/consul-ui/app/templates/dc/peers/edit/index.hbs
  ui/packages/consul-ui/app/templates/dc/peers/index.hbs
  ui/packages/consul-ui/mock-api/v1/peering/_
  ui/packages/consul-ui/mock-api/v1/peering/establish
  ui/packages/consul-ui/mock-api/v1/peering/token
  ui/packages/consul-ui/mock-api/v1/peerings
  ui/packages/consul-ui/tests/unit/abilities/-test.js
  ui/packages/consul-ui/vendor/consul-ui/routes.js
Labels: theme/ui, pr/no-changelog

#13604 ui: Gradual deprecation of old StateChart interface
  ui/packages/consul-ui/app/components/state-chart/README.mdx
  ui/packages/consul-ui/app/components/state-machine/README.mdx
  ui/packages/consul-ui/app/components/state-machine/index.hbs
  ui/packages/consul-ui/app/components/state-machine/index.js
  ui/packages/consul-ui/app/components/state/README.mdx
  ui/packages/consul-ui/app/components/state/index.hbs
  ui/packages/consul-ui/app/components/state/index.js
  ui/packages/consul-ui/app/helpers/require.js
Labels: theme/ui, pr/no-changelog

#13648 ui: Peer listing with dc/ns/partition/name based unique IDs and polling deletion
  ui/packages/consul-ui/app/abilities/peer.js
  ui/packages/consul-ui/app/adapters/peer.js
  ui/packages/consul-ui/app/components/consul/peer/address/list/index.hbs
  ui/packages/consul-ui/app/models/peer.js
  ui/packages/consul-ui/app/routes/dc/peers/index.js
  ui/packages/consul-ui/app/serializers/peer.js
  ui/packages/consul-ui/app/services/repository/peer.js
  ui/packages/consul-ui/app/templates/dc/peers/edit.hbs
  ui/packages/consul-ui/app/templates/dc/peers/edit/addresses.hbs
  ui/packages/consul-ui/app/templates/dc/peers/edit/index.hbs
  ui/packages/consul-ui/app/templates/dc/peers/index.hbs
  ui/packages/consul-ui/mock-api/v1/peering/_
  ui/packages/consul-ui/mock-api/v1/peering/establish
  ui/packages/consul-ui/mock-api/v1/peering/token
  ui/packages/consul-ui/mock-api/v1/peerings
  ui/packages/consul-ui/tests/unit/abilities/-test.js
  ui/packages/consul-ui/vendor/consul-ui/routes.js
Labels: theme/ui, pr/no-changelog

#13634 ui: Add peer searching and sorting
  ui/packages/consul-ui/app/abilities/peer.js
  ui/packages/consul-ui/app/adapters/peer.js
  ui/packages/consul-ui/app/components/consul/peer/address/list/index.hbs
  ui/packages/consul-ui/app/components/consul/peer/search-bar/README.mdx
  ui/packages/consul-ui/app/components/consul/peer/search-bar/index.hbs
  ui/packages/consul-ui/app/components/peerings/search/index.hbs
  ui/packages/consul-ui/app/components/peerings/search/index.scss
  ui/packages/consul-ui/app/controllers/dc/peers/index.js
  ui/packages/consul-ui/app/models/peer.js
  ui/packages/consul-ui/app/routes/dc/peers/index.js
  ui/packages/consul-ui/app/search/predicates/peer.js
  ui/packages/consul-ui/app/serializers/peer.js
  ui/packages/consul-ui/app/services/repository/peer.js
  ui/packages/consul-ui/app/services/search.js
  ui/packages/consul-ui/app/services/sort.js
  ui/packages/consul-ui/app/sort/comparators/peer.js
  ui/packages/consul-ui/app/styles/components.scss
  ui/packages/consul-ui/app/templates/dc/peers/edit.hbs
  ui/packages/consul-ui/app/templates/dc/peers/edit/addresses.hbs
  ui/packages/consul-ui/app/templates/dc/peers/edit/index.hbs
  ui/packages/consul-ui/app/templates/dc/peers/index.hbs
  ui/packages/consul-ui/mock-api/v1/peering/_
  ui/packages/consul-ui/mock-api/v1/peering/establish
  ui/packages/consul-ui/mock-api/v1/peering/token
  ui/packages/consul-ui/mock-api/v1/peerings
  ui/packages/consul-ui/package.json
  ui/packages/consul-ui/tests/unit/abilities/-test.js
  ui/packages/consul-ui/vendor/consul-ui/routes.js
  ui/yarn.lock
Labels: theme/ui, pr/no-changelog

#13661 Revise possible states for a peering.
  agent/consul/state/peering.go
  agent/consul/state/peering_test.go
  agent/peering_endpoint_test.go
  agent/rpc/peering/service.go
  agent/rpc/peering/service_test.go
  agent/ui_endpoint_test.go
  api/peering.go
  api/peering_test.go
  proto/pbpeering/peering.go
  proto/pbpeering/peering.pb.go
  proto/pbpeering/peering.proto
Labels: theme/api, pr/no-changelog

#13662 ui: Fixup peering imported/exported service counts
  ui/packages/consul-ui/app/components/peerings/service-count/index.hbs
  ui/packages/consul-ui/app/components/peerings/service-count/index.js
  ui/packages/consul-ui/app/templates/dc/peers/index.hbs
Labels: theme/ui, pr/no-changelog

#13664 ui: Slight update to peering mocks to more properly match actual
  ui/packages/consul-ui/mock-api/v1/peering/_
  ui/packages/consul-ui/mock-api/v1/peerings
Labels: theme/ui, pr/no-changelog

#13673 chore: fix `release/1.10.x` previews
  website/.eslintrc.js
  website/.gitignore
  website/Makefile
  website/next-env.d.ts
  website/next.config.js
  website/package-lock.json
  website/package.json
  website/prettier.config.js
  website/redirects.js
  website/scripts/website-build.sh
  website/scripts/website-start.sh
Labels: type/docs

#13656 test: update mockery use to put mocks into test files
  agent/cache-types/mock_Agent.go
  agent/cache-types/mock_RPC.go
  agent/cache-types/mock_TrustBundleLister_test.go
  agent/cache-types/rpc.go
  agent/cache-types/testing.go
  agent/cache-types/trust_bundle.go
  agent/cache-types/trust_bundles.go
  agent/cache-types/trust_bundles_test.go
  agent/cache/cache.go
  agent/cache/mock_Request.go
  agent/cache/mock_Type.go
  agent/cache/request.go
  agent/cache/testing.go
  agent/cache/type.go
  agent/consul/autopilotevents/mock_Publisher_test.go
  agent/consul/autopilotevents/mock_StateStore_test.go
  agent/consul/autopilotevents/mock_timeProvider_test.go
  agent/consul/autopilotevents/ready_servers_events.go
  agent/consul/watch/server_local.go
Labels: theme/agent-cache, pr/no-changelog, pr/no-metrics-test

#13672 docs: improve large version change upgrade path
  website/.eslintrc.js
  website/.gitignore
  website/Makefile
  website/content/docs/discovery/checks.mdx
  website/content/docs/upgrading/instructions/index.mdx
  website/content/docs/upgrading/instructions/upgrade-to-1-10-x.mdx
  website/content/docs/upgrading/instructions/upgrade-to-1-2-x.mdx
  website/content/docs/upgrading/instructions/upgrade-to-1-6-x.mdx
  website/content/docs/upgrading/instructions/upgrade-to-1-8-x.mdx
  website/data/docs-nav-data.json
  website/next-env.d.ts
  website/next.config.js
  website/package-lock.json
  website/package.json
  website/prettier.config.js
  website/redirects.js
  website/scripts/website-build.sh
  website/scripts/website-start.sh
Labels: type/docs, pr/no-changelog, backport/1.10

#13686 ui: CopyableCode component
  .changelog/13686.txt
  ui/packages/consul-ui/app/components/certificate/README.mdx
  ui/packages/consul-ui/app/components/certificate/index.hbs
  ui/packages/consul-ui/app/components/certificate/index.js
  ui/packages/consul-ui/app/components/certificate/index.scss
  ui/packages/consul-ui/app/components/consul/auth-method/view/index.hbs
  ui/packages/consul-ui/app/components/copyable-code/README.mdx
  ui/packages/consul-ui/app/components/copyable-code/index.hbs
  ui/packages/consul-ui/app/components/copyable-code/index.scss
  ui/packages/consul-ui/app/components/definition-table/README.mdx
  ui/packages/consul-ui/app/components/definition-table/layout.scss
  ui/packages/consul-ui/app/components/secret-button/index.hbs
  ui/packages/consul-ui/app/components/secret-button/index.js
  ui/packages/consul-ui/app/components/secret-button/index.scss
  ui/packages/consul-ui/app/components/secret-button/layout.scss
  ui/packages/consul-ui/app/components/secret-button/skin.scss
  ui/packages/consul-ui/app/components/tabular-dl/layout.scss
  ui/packages/consul-ui/app/styles/base/icons/icons/index.scss
  ui/packages/consul-ui/app/styles/components.scss
  ui/packages/consul-ui/app/styles/debug.scss
  ui/packages/consul-ui/app/templates/dc/acls/policies/edit.hbs
  ui/packages/consul-ui/app/templates/dc/acls/roles/edit.hbs
  ui/packages/consul-ui/app/templates/dc/acls/tokens/edit.hbs
  ui/packages/consul-ui/tests/integration/components/secret-button-test.js
Labels: theme/ui

#13685 ui: Add filtering peer listing by State
  ui/packages/consul-ui/app/components/consul/peer/components.scss
  ui/packages/consul-ui/app/components/consul/peer/index.scss
  ui/packages/consul-ui/app/components/consul/peer/search-bar/index.hbs
  ui/packages/consul-ui/app/components/consul/peer/search-bar/index.scss
  ui/packages/consul-ui/app/filter/predicates/peer.js
  ui/packages/consul-ui/app/helpers/require.js
  ui/packages/consul-ui/app/routes/dc/peers/index.js
  ui/packages/consul-ui/app/services/filter.js
  ui/packages/consul-ui/app/styles/base/icons/icons/index.scss
  ui/packages/consul-ui/app/styles/components.scss
  ui/packages/consul-ui/app/templates/dc/peers/index.hbs
  ui/packages/consul-ui/translations/components/consul/en-us.yaml
Labels: theme/ui, pr/no-changelog

#13665 ui: Peer Deletion
  ui/packages/consul-ui/app/components/consul/peer/components.scss
  ui/packages/consul-ui/app/components/consul/peer/index.scss
  ui/packages/consul-ui/app/components/consul/peer/list/README.mdx
  ui/packages/consul-ui/app/components/consul/peer/list/index.hbs
  ui/packages/consul-ui/app/components/consul/peer/notifications/README.mdx
  ui/packages/consul-ui/app/components/consul/peer/notifications/index.hbs
  ui/packages/consul-ui/app/components/consul/peer/search-bar/index.hbs
  ui/packages/consul-ui/app/components/consul/peer/search-bar/index.scss
  ui/packages/consul-ui/app/filter/predicates/peer.js
  ui/packages/consul-ui/app/helpers/require.js
  ui/packages/consul-ui/app/models/peer.js
  ui/packages/consul-ui/app/routes/dc/peers/index.js
  ui/packages/consul-ui/app/services/data-sink/protocols/http.js
  ui/packages/consul-ui/app/services/filter.js
  ui/packages/consul-ui/app/services/repository/peer.js
  ui/packages/consul-ui/app/sort/comparators/peer.js
  ui/packages/consul-ui/app/styles/base/icons/icons/index.scss
  ui/packages/consul-ui/app/styles/components.scss
  ui/packages/consul-ui/app/templates/dc/peers/index.hbs
  ui/packages/consul-ui/translations/components/consul/en-us.yaml
Labels: theme/ui, pr/no-changelog

#13689 Fix path to consul-ecs Terraform modules
  website/content/docs/ecs/compatibility.mdx
  website/content/docs/ecs/enterprise.mdx
  website/content/docs/ecs/terraform/migrate-existing-tasks.mdx
  website/content/docs/ecs/terraform/secure-configuration.mdx
Labels: type/docs, type/docs-cherrypick, pr/no-changelog, pr/no-metrics-test, backport/1.12

#13698 peering: move peer replication to the external gRPC port
  agent/consul/leader_peering.go
  agent/consul/leader_peering_test.go
  agent/consul/peering_backend.go
  agent/consul/peering_backend_oss.go
  agent/consul/server.go
  agent/consul/server_test.go
  agent/grpc/public/services/peerstream/health_snapshot.go
  agent/grpc/public/services/peerstream/health_snapshot_test.go
  agent/grpc/public/services/peerstream/mock_ACLResolver.go
  agent/grpc/public/services/peerstream/replication.go
  agent/grpc/public/services/peerstream/server.go
  agent/grpc/public/services/peerstream/stream_resources.go
  agent/grpc/public/services/peerstream/stream_test.go
  agent/grpc/public/services/peerstream/stream_tracker.go
  agent/grpc/public/services/peerstream/stream_tracker_test.go
  agent/grpc/public/services/peerstream/subscription_blocking.go
  agent/grpc/public/services/peerstream/subscription_manager.go
  agent/grpc/public/services/peerstream/subscription_manager_test.go
  agent/grpc/public/services/peerstream/subscription_state.go
  agent/grpc/public/services/peerstream/subscription_state_test.go
  agent/grpc/public/services/peerstream/subscription_view.go
  agent/grpc/public/services/peerstream/subscription_view_test.go
  agent/grpc/public/services/peerstream/testing.go
  agent/peering_endpoint_test.go
  agent/rpc/peering/service.go
  agent/rpc/peering/service_test.go
  agent/rpc/peering/testing.go
  proto/pbpeering/generate.go
  proto/pbpeering/peering.go
  proto/pbpeering/peering.pb.binary.go
  proto/pbpeering/peering.pb.go
  proto/pbpeering/peering.proto
  proto/pbpeering/peering_grpc.pb.go
  proto/pbpeerstream/peerstream.go
  proto/pbpeerstream/peerstream.pb.binary.go
  proto/pbpeerstream/peerstream.pb.go
  proto/pbpeerstream/peerstream.proto
  proto/pbpeerstream/peerstream_grpc.pb.go
  proto/pbpeerstream/types.go
  sdk/testutil/server.go
  test/integration/connect/envoy/run-tests.sh
Labels: pr/no-changelog

#13678 Fix syntax for envoy bootstrap prometheus secret config
  command/connect/envoy/bootstrap_config.go
  command/connect/envoy/bootstrap_config_test.go
  command/connect/envoy/testdata/prometheus-metrics-tls-ca-file.golden
  command/connect/envoy/testdata/prometheus-metrics-tls-ca-path.golden
Labels: theme/cli, pr/no-changelog, pr/no-metrics-test, pr/no-docs

#13677 feat(cli): enable to delete config entry from an input file
  .changelog/13677.txt
  command/config/delete/config_delete.go
  command/config/delete/config_delete_test.go
  command/config/write/config_write.go
  command/config/write/config_write_test.go
  command/helpers/decode_shim.go
  command/helpers/helpers.go
  command/helpers/helpers_test.go
  website/content/commands/config/delete.mdx
Labels: type/docs, theme/cli

#13681 docs(consul-api-gateway): use VERSION env var in install steps
  website/content/docs/api-gateway/consul-api-gateway-install.mdx
Labels: type/docs, type/docs-cherrypick, pr/no-changelog

#13709 proto: ensure buf formatter has been applied to protobufs
  .circleci/config.yml
  proto/pbconfigentry/config_entry.pb.go
  proto/pbconfigentry/config_entry.proto
  proto/pbsubscribe/subscribe.pb.go
  proto/pbsubscribe/subscribe.proto
Labels: type/ci, pr/no-changelog, pr/no-metrics-test

#13711 update docs
  website/content/docs/nia/enterprise/index.mdx
Labels: type/docs, type/docs-cherrypick, theme/consul-terraform-sync

#13703 ui: use environment variable for feature flagging peers
  ui/packages/consul-ui/app/abilities/peer.js
  ui/packages/consul-ui/app/adapters/node.js
  ui/packages/consul-ui/app/adapters/service.js
  ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs
  ui/packages/consul-ui/app/helpers/feature-flag.js
  ui/packages/consul-ui/app/routes/dc/peers.js
  ui/packages/consul-ui/app/services/features.js
  ui/packages/consul-ui/app/utils/get-environment.js
  ui/packages/consul-ui/config/environment.js
  ui/packages/consul-ui/docs/bookmarklets.mdx
Labels: theme/ui, pr/no-changelog

#13714 Return error if ServerAddresses is empty
  agent/consul/peering_backend.go
Labels: pr/no-changelog, theme/cluster-peering

#13726 state: prohibit exported discovery chains to have cross-datacenter or cross-partition references
  agent/consul/state/config_entry.go
  agent/consul/state/config_entry_test.go
  agent/consul/state/peering.go
  agent/grpc/public/services/peerstream/subscription_manager_test.go
  agent/proxycfg/testing_mesh_gateway.go
  agent/xds/clusters.go
  agent/xds/endpoints.go
  agent/xds/testdata/clusters/mesh-gateway-with-exported-peered-services-http-with-router.latest.golden
  agent/xds/testdata/endpoints/mesh-gateway-with-exported-peered-services-http-with-router.latest.golden
  agent/xds/testdata/listeners/mesh-gateway-with-exported-peered-services-http-with-router.latest.golden
  agent/xds/testdata/routes/mesh-gateway-with-exported-peered-services-http-with-router.latest.golden
Labels: theme/envoy/xds, pr/no-changelog

#13727 state: prohibit changing an exported tcp discovery chain in a way that would break SAN validation
  agent/consul/state/config_entry.go
  agent/consul/state/config_entry_test.go
  agent/grpc/public/services/peerstream/subscription_manager_test.go
Labels: pr/no-changelog

#13728 peering: always send the mesh gateway SpiffeID even for tcp services
  agent/grpc/public/services/peerstream/stream_test.go
  agent/grpc/public/services/peerstream/subscription_manager.go
  agent/grpc/public/services/peerstream/subscription_manager_test.go
Labels: pr/no-changelog, pr/no-metrics-test

#13701 ui: Remove horizontal scrollbar from peering list rows
  ui/packages/consul-ui/app/components/consul/peer/index.scss
  ui/packages/consul-ui/app/components/consul/peer/list/index.scss
  ui/packages/consul-ui/app/styles/routes.scss
Labels: theme/ui, pr/no-changelog

#13702 ui: Remove UNDEFINED state from being undeleteable
  ui/packages/consul-ui/app/abilities/peer.js
  ui/packages/consul-ui/node-tests/config/environment.js
Labels: theme/ui, pr/no-changelog

#13732 peerstream: some cosmetic refactors to make this easier to follow
  agent/consul/leader_peering.go
  agent/grpc/public/services/peerstream/replication.go
  agent/grpc/public/services/peerstream/stream_resources.go
  agent/grpc/public/services/peerstream/stream_test.go
  proto/pbpeerstream/peerstream.pb.go
  proto/pbpeerstream/peerstream.proto
Labels: pr/no-changelog, pr/no-metrics-test, theme/cluster-peering

#13735 proto: add package prefixes for all proto files where it is safe
  GNUmakefile
  proto/pbacl/acl.pb.go
  proto/pbacl/acl.proto
  proto/pbautoconf/auto_config.pb.go
  proto/pbautoconf/auto_config.proto
  proto/pbcommon/common.pb.go
  proto/pbcommon/common.proto
  proto/pbconfig/config.pb.go
  proto/pbconfig/config.proto
  proto/pbconfigentry/config_entry.pb.go
  proto/pbconfigentry/config_entry.proto
  proto/pbconnect/connect.pb.go
  proto/pbconnect/connect.proto
  proto/pbpeering/peering.pb.go
  proto/pbpeering/peering.proto
  proto/pbpeering/peering_grpc.pb.go
  proto/pbpeerstream/peerstream.pb.go
  proto/pbpeerstream/peerstream.proto
  proto/pbpeerstream/peerstream_grpc.pb.go
  proto/pbservice/healthcheck.pb.go
  proto/pbservice/healthcheck.proto
  proto/pbservice/node.pb.go
  proto/pbservice/node.proto
  proto/pbservice/service.pb.go
  proto/pbservice/service.proto
  proto/pbstatus/status.pb.go
  proto/pbstatus/status.proto
  proto/pbsubscribe/subscribe.pb.go
  proto/pbsubscribe/subscribe.proto
Labels: pr/no-changelog

#13741 1.12.x: Fix broken stuff from auto-merge
  agent/proxycfg/testing_terminating_gateway.go
Labels: pr/no-changelog, pr/no-docs

#13742 1.11.x: Respect http2 protocol for upstreams of terminating gateways
  .changelog/13699.txt
  agent/xds/clusters.go
  agent/xds/clusters_test.go
  agent/xds/testdata/clusters/terminating-gateway-http2-upstream-subsets.envoy-1-20-x.golden
  agent/xds/testdata/clusters/terminating-gateway-http2-upstream.envoy-1-20-x.golden
Labels: theme/envoy/xds

#13744 Check if an upstream is implicit from either intentions or peered services
  agent/proxycfg/snapshot.go
  agent/proxycfg/upstreams.go
  agent/xds/clusters.go
  agent/xds/endpoints.go
  agent/xds/listeners.go
  agent/xds/routes.go
Labels: theme/envoy/xds, pr/no-changelog, theme/cluster-peering

#13746 Add changelog entries from latest releases
  CHANGELOG.md
Labels: pr/no-changelog

#13747 [1.10] Post-release updates
  CHANGELOG.md
  version/version.go
Labels: pr/no-changelog

#13748 [1.11] Post-release updates
  CHANGELOG.md
  version/version.go
Labels: pr/no-changelog

#13749 [1.12] Post-release updates
  CHANGELOG.md
  version/version.go
Labels: pr/no-changelog

#13710 ui: Thread through data-source invalidate method
  ui/packages/consul-ui/app/components/data-loader/README.mdx
  ui/packages/consul-ui/app/components/data-loader/chart.xstate.js
  ui/packages/consul-ui/app/components/data-loader/index.hbs
  ui/packages/consul-ui/app/components/data-loader/index.js
  ui/packages/consul-ui/app/components/data-source/README.mdx
  ui/packages/consul-ui/app/components/data-source/index.hbs
  ui/packages/consul-ui/app/components/data-source/index.js
Labels: theme/ui, pr/no-changelog

#13725 ui: Move peers to a subapplication
  .circleci/config.yml
  ui/package.json
  ui/packages/consul-peerings/app/components/consul/peer/address/list/index.hbs
  ui/packages/consul-peerings/app/components/consul/peer/components.scss
  ui/packages/consul-peerings/app/components/consul/peer/index.scss
  ui/packages/consul-peerings/app/components/consul/peer/list/README.mdx
  ui/packages/consul-peerings/app/components/consul/peer/list/index.hbs
  ui/packages/consul-peerings/app/components/consul/peer/notifications/README.mdx
  ui/packages/consul-peerings/app/components/consul/peer/notifications/index.hbs
  ui/packages/consul-peerings/app/components/consul/peer/search-bar/README.mdx
  ui/packages/consul-peerings/app/components/consul/peer/search-bar/index.hbs
  ui/packages/consul-peerings/app/components/consul/peer/search-bar/index.scss
  ui/packages/consul-peerings/app/components/consul/peer/selector/README.mdx
  ui/packages/consul-peerings/app/components/consul/peer/selector/index.hbs
  ui/packages/consul-peerings/app/templates/dc/peers/edit.hbs
  ui/packages/consul-peerings/app/templates/dc/peers/edit/addresses.hbs
  ui/packages/consul-peerings/app/templates/dc/peers/edit/index.hbs
  ui/packages/consul-peerings/app/templates/dc/peers/index.hbs
  ui/packages/consul-peerings/package.json
  ui/packages/consul-peerings/vendor/consul-peerings/routes.js
  ui/packages/consul-peerings/vendor/consul-peerings/services.js
  ui/packages/consul-ui/.docfy-config.js
  ui/packages/consul-ui/app/abilities/peer.js
  ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs
  ui/packages/consul-ui/app/routes/dc/peers.js
  ui/packages/consul-ui/app/routes/dc/peers/index.js
  ui/packages/consul-ui/app/utils/get-environment.js
  ui/packages/consul-ui/config/environment.js
  ui/packages/consul-ui/docs/bookmarklets.mdx
  ui/packages/consul-ui/ember-cli-build.js
  ui/packages/consul-ui/lib/startup/templates/body.html.js
  ui/packages/consul-ui/node-tests/config/environment.js
  ui/packages/consul-ui/package.json
  ui/packages/consul-ui/vendor/consul-ui/routes.js
  ui/packages/consul-ui/vendor/consul-ui/services.js
Labels: theme/ui, pr/no-changelog

#13734 ui: Add additional API requests for peering establishment
  ui/packages/consul-ui/app/services/repository/peer.js
Labels: theme/ui, pr/no-changelog

#13655 docs: add Envoy upgrade step to std upgrade docs
  website/content/docs/upgrading/index.mdx
Labels: type/docs, type/docs-cherrypick, pr/no-changelog, backport/1.10, backport/1.11, backport/1.12

#13756 ui: remove with-peers query param
  ui/packages/consul-ui/app/adapters/node.js
  ui/packages/consul-ui/app/adapters/service.js
  ui/packages/consul-ui/mock-api/v1/internal/ui/nodes
  ui/packages/consul-ui/mock-api/v1/internal/ui/services
  ui/packages/consul-ui/tests/acceptance/dc/intentions/navigation.feature
  ui/packages/consul-ui/tests/acceptance/dc/nodes/index.feature
  ui/packages/consul-ui/tests/acceptance/dc/services/list.feature
  ui/packages/consul-ui/tests/acceptance/page-navigation.feature
  ui/packages/consul-ui/tests/acceptance/token-header.feature
  ui/packages/consul-ui/tests/helpers/set-cookies.js
  ui/packages/consul-ui/tests/integration/adapters/node-test.js
  ui/packages/consul-ui/tests/integration/adapters/service-test.js
Labels: theme/ui, pr/no-changelog

#13772 Enable API support for partitions during peering establishment
  agent/peering_endpoint.go
  api/peering.go
  proto/pbpeering/peering.gen.go
Labels: theme/api, pr/no-changelog

#13773 Fix panic for replicating a node without a Node ID
  agent/grpc-external/services/peerstream/health_snapshot.go
  agent/grpc-external/services/peerstream/health_snapshot_test.go
  agent/grpc-external/services/peerstream/replication.go
Labels: pr/no-changelog

#13490 Made changes based on Adams suggestions
  website/content/docs/k8s/installation/vault/data-integration/bootstrap-token.mdx
  website/content/docs/k8s/installation/vault/data-integration/connect-ca.mdx
  website/content/docs/k8s/installation/vault/data-integration/enterprise-license.mdx
  website/content/docs/k8s/installation/vault/data-integration/gossip.mdx
  website/content/docs/k8s/installation/vault/data-integration/index.mdx
  website/content/docs/k8s/installation/vault/data-integration/partition-token.mdx
  website/content/docs/k8s/installation/vault/data-integration/replication-token.mdx
  website/content/docs/k8s/installation/vault/data-integration/server-tls.mdx
  website/content/docs/k8s/installation/vault/data-integration/snapshot-agent-config.mdx
  website/content/docs/k8s/installation/vault/data-integration/webhook-certs.mdx
  website/content/docs/k8s/installation/vault/systems-integration.mdx
  website/content/docs/k8s/installation/vault/wan-federation.mdx
Labels: type/docs, type/docs-cherrypick, pr/no-changelog, pr/no-metrics-test, backport/1.12

#13768 peering: add warning about AllowStaleRead
  internal/tools/proto-gen-rpc-glue/e2e/source.pb.go
  internal/tools/proto-gen-rpc-glue/e2e/source.rpcglue.pb.go.golden
  internal/tools/proto-gen-rpc-glue/main.go
  proto/pbpeering/peering.pb.go
  proto/pbpeering/peering.proto
  proto/pbpeering/peering.rpcglue.pb.go
Labels: pr/no-changelog, theme/cluster-peering

#13750 Latest submodule versions
  api/go.mod
  go.mod
  test/integration/consul-container/go.mod
Labels: pr/dependencies, pr/no-changelog, backport/1.12

#13718 peering: track imported services
  agent/consul/leader_peering_test.go
  agent/grpc-external/services/peerstream/replication.go
  agent/grpc-external/services/peerstream/stream_resources.go
  agent/grpc-external/services/peerstream/stream_test.go
  agent/grpc-external/services/peerstream/stream_tracker.go
  agent/rpc/peering/service.go
Labels: pr/no-changelog, theme/cluster-peering

#13733 server: ensure peer replication can successfully use TLS over external gRPC
  agent/agent.go
  agent/consul/leader_peering.go
  agent/consul/leader_peering_test.go
  agent/consul/peering_backend.go
  agent/consul/server_test.go
  agent/grpc-external/services/peerstream/stream_tracker.go
  agent/rpc/peering/service_test.go
  test/integration/connect/envoy/case-wanfed-gw/primary/common.hcl
  test/integration/connect/envoy/case-wanfed-gw/primary/server.hcl
  test/integration/connect/envoy/case-wanfed-gw/secondary/common.hcl
  tlsutil/config.go
  website/content/docs/agent/config/config-files.mdx
  website/content/docs/upgrading/upgrade-specific.mdx
Labels: theme/tls, theme/certificates, pr/no-changelog, theme/cluster-peering

#13779 test: fix flaky test TestAPI_CatalogNodes
  api/catalog_test.go
Labels: theme/api, pr/no-changelog

#13745 peerstream: dialer should reconnect when stream closes
  agent/consul/leader_peering_test.go
  agent/grpc-external/services/peerstream/stream_resources.go
Labels: pr/no-changelog, theme/cluster-peering

#13781 Add docs for peerStreamServer vs peeringServer.
  agent/consul/server.go
Labels: pr/no-changelog, theme/cluster-peering

#13731 Nia/cts tasks not required
  website/content/docs/nia/configuration.mdx
Labels: type/docs, theme/consul-terraform-sync

#13780 peerstream: fix test assertions
  agent/grpc-external/services/peerstream/stream_test.go
Labels: pr/no-changelog, theme/cluster-peering

#13767 peerstream: require a resource subscription to receive updates of that type
  agent/grpc-external/services/peerstream/replication.go
  agent/grpc-external/services/peerstream/stream_resources.go
  agent/grpc-external/services/peerstream/stream_test.go
  agent/grpc-external/services/peerstream/subscription_blocking.go
  agent/grpc-external/services/peerstream/subscription_manager.go
  agent/grpc-external/services/peerstream/subscription_manager_test.go
  agent/grpc-external/services/peerstream/testing.go
  proto/pbpeerstream/convert.go
  proto/pbpeerstream/peerstream.pb.binary.go
  proto/pbpeerstream/peerstream.pb.go
  proto/pbpeerstream/peerstream.proto
  proto/pbpeerstream/types.go
  proto/pbservice/convert.go
  proto/prototest/testing.go
Labels: pr/no-changelog, theme/cluster-peering

#13753 ui: wan federation message dc-dropdown
  ui/packages/consul-ui/app/components/consul/datacenter/selector/index.hbs
  ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs
  ui/packages/consul-ui/app/components/hashicorp-consul/index.scss
  ui/packages/consul-ui/app/components/main-nav-vertical/layout.scss
  ui/packages/consul-ui/tests/integration/components/consul/datacenter/selector-test.js
  ui/packages/consul-ui/tests/integration/components/hashicorp-consul-test.js
Labels: theme/ui, pr/no-changelog

#13754 ui: Adds Peer initiation form
  ui/packages/consul-peerings/app/components/consul/peer/form/initiate/README.mdx
  ui/packages/consul-peerings/app/components/consul/peer/form/initiate/actions/index.hbs
  ui/packages/consul-peerings/app/components/consul/peer/form/initiate/fieldsets/index.hbs
  ui/packages/consul-peerings/app/components/consul/peer/form/initiate/index.hbs
  ui/packages/consul-ui/translations/common/en-us.yaml
Labels: theme/ui, pr/no-changelog

#13755 ui: Add peer token generation form
  ui/packages/consul-peerings/app/components/consul/peer/form/generate/README.mdx
  ui/packages/consul-peerings/app/components/consul/peer/form/generate/actions/index.hbs
  ui/packages/consul-peerings/app/components/consul/peer/form/generate/chart.xstate.js
  ui/packages/consul-peerings/app/components/consul/peer/form/generate/fieldsets/index.hbs
  ui/packages/consul-peerings/app/components/consul/peer/form/generate/index.hbs
Labels: theme/ui, pr/no-changelog

#13752 docs: Resolve conflicts in docs
  website/content/docs/connect/cluster-peering/k8s.mdx
  website/content/docs/k8s/installation/vault/data-integration/bootstrap-token.mdx
  website/content/docs/k8s/installation/vault/data-integration/connect-ca.mdx
  website/content/docs/k8s/installation/vault/data-integration/enterprise-license.mdx
  website/content/docs/k8s/installation/vault/data-integration/gossip.mdx
  website/content/docs/k8s/installation/vault/data-integration/index.mdx
  website/content/docs/k8s/installation/vault/data-integration/partition-token.mdx
  website/content/docs/k8s/installation/vault/data-integration/replication-token.mdx
  website/content/docs/k8s/installation/vault/data-integration/server-tls.mdx
  website/content/docs/k8s/installation/vault/data-integration/snapshot-agent-config.mdx
  website/content/docs/k8s/installation/vault/data-integration/webhook-certs.mdx
  website/content/docs/k8s/installation/vault/wan-federation.mdx
  website/data/docs-nav-data.json
Labels: type/docs, pr/no-changelog

#13783 [1.12] Backport "Add version compatibility tests between Consul (#12702)"
  .circleci/config.yml
  GNUmakefile
  test/integration/consul-container/libs/node/consul-container.go
  test/integration/consul-container/libs/node/node.go
  test/integration/consul-container/libs/utils/utils.go
  test/integration/consul-container/upgrade/README.md
Labels: type/ci, pr/no-changelog

#13786 fix leader annotation
  internal/tools/proto-gen-rpc-glue/main.go
Labels: pr/no-changelog

#13796 peerstream: set keepalive enforcement to 15s
  agent/grpc-external/server.go
Labels: pr/no-changelog, theme/cluster-peering

#13787 Fix panic on acl token read with -self and -expanded
  .changelog/13787.txt
  command/acl/token/read/token_read.go
Labels: theme/cli, backport/1.12

#13799 ui: chore - fix CI test-suite
  ui/packages/consul-ui/app/components/consul/datacenter/selector/index.hbs
  ui/packages/consul-ui/app/components/hashicorp-consul/pageobject.js
  ui/packages/consul-ui/tests/integration/components/hashicorp-consul-test.js
Labels: theme/ui, pr/no-changelog

#13797 makefile: give better error for tool installed by wrong package
  build-support/scripts/devtools.sh
Labels: pr/no-changelog

#13278 Update Single DC Multi K8S doc
  website/content/docs/k8s/installation/deployment-configurations/single-dc-multi-k8s.mdx
Labels: type/docs, type/docs-cherrypick, pr/no-changelog, pr/no-metrics-test, backport/1.12

#13795 peering: refactor reconcile, cleanup
  agent/consul/leader_peering_test.go
  agent/grpc-external/services/peerstream/replication.go
  agent/grpc-external/services/peerstream/stream_tracker.go
  agent/rpc/peering/service.go
  api/peering_test.go
Labels: pr/no-changelog, theme/cluster-peering

#13758 Make envoy resources for inferred peered upstreams
  agent/proxycfg/connect_proxy.go
  agent/proxycfg/snapshot.go
  agent/proxycfg/testing_peering.go
  agent/xds/clusters.go
  agent/xds/clusters_test.go
  agent/xds/endpoints.go
  agent/xds/listeners.go
  agent/xds/listeners_test.go
  agent/xds/resources_test.go
  agent/xds/testdata/clusters/transparent-proxy-with-peered-upstreams.latest.golden
  agent/xds/testdata/endpoints/transparent-proxy-with-peered-upstreams.latest.golden
  agent/xds/testdata/endpoints/transparent-proxy.latest.golden
  agent/xds/testdata/listeners/transparent-proxy-with-peered-upstreams.latest.golden
  agent/xds/testdata/routes/transparent-proxy-with-peered-upstreams.latest.golden
  agent/xds/testdata/routes/transparent-proxy.latest.golden
Labels: theme/envoy/xds, pr/no-changelog, theme/cluster-peering

#13760 Extract AWS auth implementation out of Consul
  agent/consul/authmethod/awsauth/aws.go
  agent/consul/authmethod/awsauth/aws_test.go
  command/login/aws.go
  command/login/login_test.go
  go.mod
  go.sum
  internal/iamauth/README.md
  internal/iamauth/auth.go
  internal/iamauth/auth_test.go
  internal/iamauth/config.go
  internal/iamauth/config_test.go
  internal/iamauth/iamauthtest/testing.go
  internal/iamauth/responses/arn.go
  internal/iamauth/responses/responses.go
  internal/iamauth/responses/responses_test.go
  internal/iamauth/responsestest/testing.go
  internal/iamauth/token.go
  internal/iamauth/token_test.go
  internal/iamauth/util.go
  lib/glob.go
  lib/glob_test.go
Labels: theme/cli, pr/dependencies, theme/internals, pr/no-changelog

#13807 connect: Add support for Envoy 1.23, remove 1.19
  .changelog/13807.txt
  .circleci/config.yml
  agent/xds/envoy_versioning.go
  agent/xds/envoy_versioning_test.go
  agent/xds/proxysupport/proxysupport.go
  test/integration/connect/envoy/run-tests.sh
Labels: type/ci, theme/envoy/xds

#13792 ui: Peer token use form
  ui/packages/consul-peerings/app/components/consul/peer/form/generate/index.hbs
  ui/packages/consul-peerings/app/components/consul/peer/form/index.scss
  ui/packages/consul-peerings/app/components/consul/peer/form/token/actions/index.hbs
  ui/packages/consul-peerings/app/components/consul/peer/form/token/fieldsets/index.hbs
  ui/packages/consul-ui/app/styles/base/icons/icons/index.scss
  ui/packages/consul-ui/app/styles/components.scss
Labels: theme/ui, pr/no-changelog

#13794 ui: Add Peer Form
  ui/packages/consul-peerings/app/components/consul/peer/form/README.mdx
  ui/packages/consul-peerings/app/components/consul/peer/form/chart.xstate.js
  ui/packages/consul-peerings/app/components/consul/peer/form/index.hbs
  ui/packages/consul-peerings/app/components/consul/peer/form/index.scss
  ui/packages/consul-peerings/app/components/consul/peer/index.scss
Labels: theme/ui, pr/no-changelog

#13812 ui: no partition and peer in bucket-list at the same time
  ui/packages/consul-ui/app/components/consul/bucket/list/README.mdx
  ui/packages/consul-ui/app/components/consul/bucket/list/index.js
  ui/packages/consul-ui/app/components/consul/intention/list/table/index.hbs
  ui/packages/consul-ui/tests/integration/components/consul/bucket/list-test.js
Labels: theme/ui, pr/no-changelog

#13778 Backport of Latest submodule versions into release/1.12.x
  api/go.mod
  go.mod
  test/integration/consul-container/go.mod
  test/integration/consul-container/go.sum
Labels: theme/api, pr/dependencies, pr/no-changelog

#13405 docs: correct Vault CA multiple namespace support
  website/content/docs/connect/ca/vault.mdx
Labels: type/docs, type/docs-cherrypick, pr/no-changelog, backport/1.12

#13805 peering: Add send mutex to protect against concurrent sends
  agent/grpc-external/services/peerstream/stream_resources.go
Labels: pr/no-changelog, theme/cluster-peering

#13682 docs: suggest using token header, not query param
  website/content/docs/agent/config/config-files.mdx
Labels: type/docs, type/docs-cherrypick, pr/no-changelog, backport/1.11, backport/1.12

#12592 docs: fix a trailing comma in JSON body
  website/content/docs/connect/registration/sidecar-service.mdx
Labels: type/docs, type/docs-cherrypick, pr/no-changelog, pr/no-metrics-test

#13833 [OSS] proxycfg-glue: server-local implementation of `PeeredUpstreams`
  agent/agent.go
  agent/consul/state/catalog.go
  agent/proxycfg-glue/glue.go
  agent/proxycfg-glue/peered_upstreams.go
  agent/proxycfg-glue/peered_upstreams_test.go
Labels: pr/no-changelog

#13834 ui: Update peerings empty state copy
  ui/packages/consul-peerings/app/templates/dc/peers/index.hbs
Labels: theme/ui, pr/no-changelog

#13832 ui: Surface peer info in nodes.show view
  ui/packages/consul-ui/app/components/consul/peer/info/index.hbs
  ui/packages/consul-ui/app/components/consul/peer/info/index.scss
  ui/packages/consul-ui/app/styles/components.scss
  ui/packages/consul-ui/app/templates/dc/nodes/show.hbs
  ui/packages/consul-ui/app/templates/dc/services/show.hbs
  ui/packages/consul-ui/tests/pages/dc/services/show.js
Labels: theme/ui, pr/no-changelog

#13840 ui: peered services only show instance- and tags-tabs
  ui/packages/consul-ui/app/templates/dc/services/show.hbs
  ui/packages/consul-ui/tests/acceptance/dc/services/show-with-slashes.feature
Labels: theme/ui, pr/no-changelog

#13836 ui: Remove peering detail page
  ui/packages/consul-peerings/app/components/consul/peer/list/index.hbs
  ui/packages/consul-peerings/vendor/consul-peerings/routes.js
Labels: theme/ui, pr/no-changelog

#13837 ui: Allow searching for peerings by ID
  ui/packages/consul-peerings/vendor/consul-peerings/routes.js
  ui/packages/consul-ui/app/models/peer.js
  ui/packages/consul-ui/app/search/predicates/peer.js
Labels: theme/ui, pr/no-changelog

#13839 ui: Change initiate > establish for peering the modal tab
  ui/packages/consul-peerings/app/components/consul/peer/form/index.hbs
Labels: theme/ui, pr/no-changelog

#13770 Add Consul Lambda integration tests
  .circleci/config.yml
  test/integration/connect/envoy/case-mesh-to-lambda/capture.sh
  test/integration/connect/envoy/case-mesh-to-lambda/config_entries.hcl
  test/integration/connect/envoy/case-mesh-to-lambda/lambda_l1.json
  test/integration/connect/envoy/case-mesh-to-lambda/lambda_l2.json
  test/integration/connect/envoy/case-mesh-to-lambda/serverless.hcl
  test/integration/connect/envoy/case-mesh-to-lambda/service_defaults_l1.json
  test/integration/connect/envoy/case-mesh-to-lambda/service_defaults_l2.json
  test/integration/connect/envoy/case-mesh-to-lambda/service_gateway.hcl
  test/integration/connect/envoy/case-mesh-to-lambda/service_s1.hcl
  test/integration/connect/envoy/case-mesh-to-lambda/setup.sh
  test/integration/connect/envoy/case-mesh-to-lambda/vars.sh
  test/integration/connect/envoy/case-mesh-to-lambda/verify.bats
  test/integration/connect/envoy/helpers.bash
  test/integration/connect/envoy/run-tests.sh
Labels: theme/connect, type/ci, pr/no-changelog, pr/no-docs

#13806 peering: Add heartbeating to peering streams
  agent/grpc-external/services/peerstream/server.go
  agent/grpc-external/services/peerstream/stream_resources.go
  agent/grpc-external/services/peerstream/stream_test.go
Labels: pr/no-changelog, theme/cluster-peering

#13845 [SYNC] Rename peering internal to ~
  agent/consul/state/catalog_oss_test.go
  agent/structs/structs.go
Labels: pr/no-changelog, pr/no-metrics-test, theme/cluster-peering

#13819 [1.12] Set Go version to latest 1.17 series
  .circleci/config.yml
Labels: type/ci, pr/no-changelog

#13844 Update generate token endpoint to take external addresses
  agent/peering_endpoint_test.go
  agent/rpc/peering/service.go
  agent/rpc/peering/service_test.go
  api/go.mod
  api/go.sum
  api/peering.go
  api/peering_test.go
  go.sum
  proto/pbpeering/peering.gen.go
  proto/pbpeering/peering.pb.go
  proto/pbpeering/peering.proto
Labels: theme/api, pr/dependencies, pr/no-changelog, theme/cluster-peering

#13842 update docs
  website/content/docs/nia/cli/start.mdx
Labels: type/docs, theme/consul-terraform-sync

#13835 Add Cluster Peering Failover Support to Prepared Queries
  agent/consul/prepared_query/template_test.go
  agent/consul/prepared_query/walk_test.go
  agent/consul/prepared_query_endpoint.go
  agent/consul/prepared_query_endpoint_test.go
  agent/dns_test.go
  agent/prepared_query_endpoint_test.go
  agent/structs/prepared_query.go
  api/prepared_query.go
Labels: theme/api, pr/no-changelog

#13853 [OSS] proxycfg-glue: server-local implementation of `ExportedPeeredServices`
  agent/agent.go
  agent/proxycfg-glue/exported_peered_services.go
  agent/proxycfg-glue/exported_peered_services_test.go
  agent/proxycfg-glue/glue.go
  agent/proxycfg-glue/helpers_test.go
Labels: pr/no-changelog

#13854 ui: Improve peered service empty downstreams message
  ui/packages/consul-ui/app/components/topology-metrics/index.js
Labels: theme/ui, pr/no-changelog, pr/no-docs

#13729 Add ECS audit logging docs
  website/content/docs/ecs/enterprise.mdx
  website/content/docs/ecs/manual/secure-configuration.mdx
  website/content/docs/ecs/terraform/secure-configuration.mdx
Labels: type/docs, type/docs-cherrypick, pr/no-changelog, pr/no-metrics-test, backport/1.12

#13861 Rename some protobuf package names to be fqdn like
  proto-public/pbacl/acl.pb.go
  proto-public/pbacl/acl.proto
  proto-public/pbacl/acl_grpc.pb.go
  proto-public/pbconnectca/ca.pb.go
  proto-public/pbconnectca/ca.proto
  proto-public/pbconnectca/ca_grpc.pb.go
  proto-public/pbdataplane/dataplane.pb.go
  proto-public/pbdataplane/dataplane.proto
  proto-public/pbdataplane/dataplane_grpc.pb.go
  proto-public/pbserverdiscovery/serverdiscovery.pb.go
  proto-public/pbserverdiscovery/serverdiscovery.proto
  proto-public/pbserverdiscovery/serverdiscovery_grpc.pb.go
Labels: pr/no-changelog

#13811 peering: emit exported services count metric
  agent/consul/leader_peering.go
  agent/consul/leader_peering_test.go
  agent/consul/server.go
  agent/grpc-external/services/peerstream/stream_resources.go
  agent/setup.go
  logging/names.go
Labels: pr/no-changelog, theme/cluster-peering

#13809 docs: Updates k8s annotation docs
  website/content/docs/k8s/annotations-and-labels.mdx
Labels: type/docs, type/docs-cherrypick, pr/no-metrics-test, backport/1.12

#13848 [OSS] Add new peering ACL rule
  acl/acl_test.go
  acl/authorizer.go
  acl/authorizer_test.go
  acl/chained_authorizer.go
  acl/chained_authorizer_test.go
  acl/policy.go
  acl/policy_authorizer.go
  acl/policy_authorizer_test.go
  acl/policy_merger.go
  acl/policy_test.go
  acl/static_authorizer.go
  agent/acl_endpoint_test.go
  agent/structs/acl.go
Labels: theme/acls, pr/no-changelog

#13847 Fix goroutine leaks in proxycfg when using ingress gateway
  .changelog/13847.txt
  agent/proxycfg/ingress_gateway.go
  agent/proxycfg/upstreams.go
Labels: backport/1.11, pr/no-docs, backport/1.12

#13867 peering: add config to enable/disable peering
  agent/agent.go
  agent/config/builder.go
  agent/config/config.go
  agent/config/default.go
  agent/config/runtime.go
  agent/config/runtime_test.go
  agent/config/testdata/TestRuntimeConfig_Sanitize.golden
  agent/config/testdata/full-config.hcl
  agent/config/testdata/full-config.json
  agent/consul/config.go
  agent/consul/leader.go
  agent/consul/leader_peering_test.go
  agent/consul/server.go
  agent/rpc/peering/service.go
  agent/rpc/peering/service_test.go
  docs/config/checklist-adding-config-fields.md
  website/content/docs/agent/config/config-files.mdx
Labels: theme/config, pr/no-changelog, theme/cluster-peering

#13823 peering: use ShouldDial to validate peer role
  agent/rpc/peering/service.go
  agent/rpc/peering/service_test.go
Labels: theme/api, pr/no-changelog, pr/no-metrics-test, theme/cluster-peering

#13816 Enable/Disable Peering Support in the UI
  agent/uiserver/ui_template_data.go
  agent/uiserver/uiserver_test.go
Labels: pr/no-changelog

#13878 [OSS] Add ACL enforcement to peering endpoints
  acl/authorizer.go
  agent/cache-types/trust_bundle.go
  agent/cache-types/trust_bundle_test.go
  agent/cache-types/trust_bundles.go
  agent/cache-types/trust_bundles_test.go
  agent/consul/peering_backend.go
  agent/consul/peering_backend_oss_test.go
  agent/consul/peering_backend_test.go
  agent/peering_endpoint.go
  agent/proxycfg-glue/glue.go
  agent/proxycfg-glue/trust_bundle.go
  agent/proxycfg-glue/trust_bundle_test.go
  agent/proxycfg/connect_proxy.go
  agent/proxycfg/data_sources.go
  agent/proxycfg/mesh_gateway.go
  agent/proxycfg/state_test.go
  agent/proxycfg/testing.go
  agent/rpc/peering/service.go
  agent/rpc/peering/service_test.go
  agent/rpc/peering/testing.go
  api/peering.go
  api/peering_test.go
  proto/pbpeering/peering.gen.go
  proto/pbpeering/peering.go
  proto/pbpeering/peering.pb.go
  proto/pbpeering/peering.proto
  proto/pbpeering/peering.rpcglue.pb.go
Labels: theme/api, theme/acls, pr/no-changelog

#13879 Re-document peering disabled
  website/content/docs/agent/config/config-files.mdx
Labels: type/docs, pr/no-changelog, pr/no-docs

#13875 ui: add peers to node search
  ui/packages/consul-ui/app/controllers/_peered-resource.js
  ui/packages/consul-ui/app/controllers/dc/nodes/index.js
  ui/packages/consul-ui/app/controllers/dc/services/index.js
  ui/packages/consul-ui/app/search/predicates/node.js
  ui/packages/consul-ui/app/templates/dc/nodes/index.hbs
  ui/packages/consul-ui/app/templates/dc/services/index.hbs
  ui/packages/consul-ui/vendor/consul-ui/routes.js
Labels: theme/ui, pr/no-changelog

#13818 Update envoy metrics label extraction for peered clusters and listeners
  agent/xds/clusters.go
  agent/xds/endpoints.go
  agent/xds/listeners.go
  agent/xds/testdata/clusters/connect-proxy-with-peered-upstreams.latest.golden
  agent/xds/testdata/clusters/transparent-proxy-with-peered-upstreams.latest.golden
  agent/xds/testdata/endpoints/connect-proxy-with-peered-upstreams.latest.golden
  agent/xds/testdata/endpoints/transparent-proxy-with-peered-upstreams.latest.golden
  agent/xds/testdata/listeners/connect-proxy-with-peered-upstreams.latest.golden
  agent/xds/testdata/listeners/transparent-proxy-with-peered-upstreams.latest.golden
  command/connect/envoy/bootstrap_config.go
  command/connect/envoy/bootstrap_config_test.go
  command/connect/envoy/testdata/CONSUL_HTTP_ADDR-with-https-scheme-enables-tls.golden
  command/connect/envoy/testdata/access-log-path.golden
  command/connect/envoy/testdata/defaults-nodemeta.golden
  command/connect/envoy/testdata/defaults.golden
  command/connect/envoy/testdata/deprecated-grpc-addr-config.golden
  command/connect/envoy/testdata/existing-ca-file.golden
  command/connect/envoy/testdata/existing-ca-path.golden
  command/connect/envoy/testdata/extra_-multiple.golden
  command/connect/envoy/testdata/extra_-single.golden
  command/connect/envoy/testdata/grpc-addr-env.golden
  command/connect/envoy/testdata/grpc-addr-flag.golden
  command/connect/envoy/testdata/grpc-addr-unix.golden
  command/connect/envoy/testdata/ingress-gateway-address-specified.golden
  command/connect/envoy/testdata/ingress-gateway-no-auto-register.golden
  command/connect/envoy/testdata/ingress-gateway-nodemeta.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-and-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-without-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway.golden
  command/connect/envoy/testdata/prometheus-metrics-tls-ca-file.golden
  command/connect/envoy/testdata/prometheus-metrics-tls-ca-path.golden
  command/connect/envoy/testdata/prometheus-metrics.golden
  command/connect/envoy/testdata/token-arg.golden
  command/connect/envoy/testdata/token-env.golden
  command/connect/envoy/testdata/token-file-arg.golden
  command/connect/envoy/testdata/token-file-env.golden
  command/connect/envoy/testdata/xds-addr-config.golden
  command/connect/envoy/testdata/zipkin-tracing-config.golden
  test/integration/connect/envoy/case-cross-peers-http-router/primary/verify.bats
  test/integration/connect/envoy/case-cross-peers-http/primary/verify.bats
  test/integration/connect/envoy/case-cross-peers-resolver-redirect-tcp/primary/verify.bats
  test/integration/connect/envoy/case-cross-peers/primary/verify.bats
Labels: pr/no-changelog, pr/no-metrics-test, theme/cluster-peering

#13881 docs: add details around Consul latency requirements
  website/content/docs/agent/index.mdx
Labels: type/docs, type/docs-cherrypick, backport/1.10, pr/no-metrics-test, backport/1.11, backport/1.12

#13666 Preserve PeeringState on upsert
  agent/consul/state/peering.go
  agent/peering_endpoint_test.go
  agent/rpc/peering/service.go
Labels: pr/no-changelog, theme/cluster-peering

#13862 docs: add peering metric doc
  website/content/docs/agent/telemetry.mdx
Labels: type/docs, pr/no-changelog, pr/no-metrics-test, theme/cluster-peering

#13888 docs: typo for latency requirements
  website/content/docs/agent/index.mdx
Labels: type/docs, type/docs-cherrypick, pr/no-changelog, backport/1.10, pr/no-metrics-test, backport/1.11, backport/1.12

#13872 Remove extra logging from ingress upstream watch shutdown
  agent/proxycfg/ingress_gateway.go
Labels: pr/no-changelog, pr/no-docs, backport/1.12

#13857 Backport of Add ECS audit logging docs into stable-website
  website/content/docs/ecs/enterprise.mdx
  website/content/docs/ecs/manual/secure-configuration.mdx
  website/content/docs/ecs/terraform/secure-configuration.mdx
Labels: type/docs

#13858 Backport of Add ECS audit logging docs into release/1.12.x
  website/content/docs/ecs/enterprise.mdx
  website/content/docs/ecs/manual/secure-configuration.mdx
  website/content/docs/ecs/terraform/secure-configuration.mdx
Labels: type/docs

#13849 peering: read endpoints can now return failing status
  agent/grpc-external/services/peerstream/stream_resources.go
  agent/grpc-external/services/peerstream/stream_test.go
  agent/grpc-external/services/peerstream/stream_tracker.go
  agent/grpc-external/services/peerstream/stream_tracker_test.go
  agent/rpc/peering/service.go
Labels: pr/no-changelog, theme/cluster-peering

#13808 build: add a job to build and push UBI images to DockerHub
  .github/workflows/build.yml
Labels: theme/contributing, pr/no-changelog, pr/no-docs

#13896 Rename receive to recv in tracker
  agent/grpc-external/services/peerstream/stream_resources.go
  agent/grpc-external/services/peerstream/stream_test.go
  agent/grpc-external/services/peerstream/stream_tracker.go
Labels: pr/no-changelog, theme/cluster-peering

#12045 Partitions: Include ACL Info and API cross-ref for CLI Commands
  website/content/api-docs/admin-partitions.mdx
  website/content/commands/partition.mdx
  website/content/partials/http_api_and_cli_characteristics_links.mdx
Labels: type/docs, type/docs-cherrypick, pr/no-changelog, pr/no-metrics-test, backport/1.12

#13874 Allow hostname based addresses in peering token
  agent/rpc/peering/testing.go
  agent/rpc/peering/validate.go
  agent/rpc/peering/validate_test.go
Labels: pr/no-changelog

#13897 fixed typo
  website/content/docs/agent/telemetry.mdx
Labels: type/docs, pr/no-changelog

#13851 peering: prevent peering in same partition
  agent/rpc/peering/service.go
  agent/rpc/peering/service_test.go
Labels: pr/no-changelog, pr/no-metrics-test, theme/cluster-peering

#13877 ui: add deprecation worfklow addon
  ui/packages/consul-ui/config/deprecation-workflow.js
  ui/packages/consul-ui/package.json
  ui/yarn.lock
Labels: theme/ui, pr/no-changelog

#13813 ui: Add peering establishment to the peer listing page
  ui/packages/consul-peerings/app/components/consul/peer/list/index.hbs
  ui/packages/consul-peerings/app/templates/dc/peers/index.hbs
  ui/packages/consul-ui/app/components/buttons/index.scss
  ui/packages/consul-ui/app/styles/routes/dc/acls/index.scss
Labels: theme/ui, pr/no-changelog

#13814 ui: Make peered intentions read-only
  ui/packages/consul-ui/app/abilities/intention.js
  ui/packages/consul-ui/app/components/consul/intention/list/table/index.hbs
  ui/packages/consul-ui/app/models/intention.js
  ui/packages/consul-ui/tests/acceptance/dc/intentions/delete.feature
  ui/packages/consul-ui/tests/acceptance/dc/intentions/navigation.feature
  ui/packages/consul-ui/tests/acceptance/dc/services/show/intentions/index.feature
Labels: theme/ui, pr/no-changelog

#13905 chore: removed unused method AddService
  agent/acl_test.go
  agent/agent_endpoint_test.go
  agent/local/state.go
  agent/local/state_test.go
  agent/proxycfg-sources/catalog/config_source_test.go
  agent/proxycfg-sources/local/sync_test.go
  agent/user_event_test.go
Labels: pr/no-changelog

#13910 docs: update helm reference docs
  website/content/docs/k8s/helm.mdx
Labels: type/docs, type/docs-cherrypick, pr/no-changelog

#12903 Docs: Show CLI command-specific options before general options
  website/content/commands/acl/auth-method/create.mdx
Labels: type/docs, type/docs-cherrypick, pr/no-changelog, meta/staleproof, pr/no-metrics-test

#13914 docs: remove comparative info from ref docs site
  website/content/docs/intro/index.mdx
  website/content/docs/intro/vs/chef-puppet.mdx
  website/content/docs/intro/vs/custom.mdx
  website/content/docs/intro/vs/eureka.mdx
  website/content/docs/intro/vs/index.mdx
  website/content/docs/intro/vs/istio.mdx
  website/content/docs/intro/vs/nagios.mdx
  website/content/docs/intro/vs/proxies.mdx
  website/content/docs/intro/vs/serf.mdx
  website/content/docs/intro/vs/skydns.mdx
  website/content/docs/intro/vs/smartstack.mdx
  website/data/docs-nav-data.json
  website/redirects.js
Labels: type/docs, pr/no-changelog, backport/1.10, backport/1.11, backport/1.12

#13907 chore: clarify the error message: service.service must not be empty
  agent/consul/catalog_endpoint.go
Labels: pr/no-changelog

#13927 ci: Add nightly test workflow for 1.13, remove 1.10
  .github/workflows/nightly-test-1.13.x.yaml
Labels: theme/contributing, pr/no-changelog

#13924 peering: don't track imported services/nodes in usage
  agent/consul/state/state_store_test.go
  agent/consul/state/usage.go
  agent/consul/state/usage_test.go
  agent/grpc-external/services/peerstream/health_snapshot.go
Labels: pr/no-changelog, theme/cluster-peering

#13930 Add peer counts to emitted metrics.
  agent/consul/state/state_store_test.go
  agent/consul/state/usage.go
  agent/consul/state/usage_oss.go
  agent/consul/state/usage_test.go
  agent/consul/usagemetrics/usagemetrics.go
  agent/consul/usagemetrics/usagemetrics_oss.go
  agent/consul/usagemetrics/usagemetrics_oss_test.go
  website/content/docs/agent/telemetry.mdx
Labels: type/docs, pr/no-changelog, theme/cluster-peering, backport/1.13

#13939 fix (cli): import empty directory to kv
  command/kv/imp/kv_import.go
  command/kv/imp/kv_import_test.go
Labels: theme/cli, pr/no-changelog, backport/1.11, backport/1.12, backport/1.13

#13937 Manual backport of peering usage to 1.13.x
  agent/consul/state/state_store_test.go
  agent/consul/state/usage.go
  agent/consul/state/usage_oss.go
  agent/consul/state/usage_test.go
  agent/consul/usagemetrics/usagemetrics.go
  agent/consul/usagemetrics/usagemetrics_oss.go
  agent/consul/usagemetrics/usagemetrics_oss_test.go
  agent/grpc-external/services/peerstream/health_snapshot.go
  website/content/docs/agent/telemetry.mdx
Labels: type/docs, pr/no-changelog

#13945 ci: Use correct branch name for 1.13 nightly test
  .github/workflows/nightly-test-1.13.x.yaml
Labels: theme/contributing, pr/no-changelog

#13929 [sync] fix empty partitions matching
  agent/rpc/peering/service.go
Labels: pr/no-changelog, theme/cluster-peering, backport/1.13

#13951 inject gateway addons to destination clusters
  agent/proxycfg/testing_terminating_gateway.go
  agent/xds/clusters.go
  agent/xds/testdata/clusters/transparent-proxy-terminating-gateway-destinations-only.latest.golden
  agent/xds/testdata/listeners/transparent-proxy-terminating-gateway-destinations-only.latest.golden
Labels: pr/no-changelog, backport/1.13

#13925 Ensure connections are closed before WaitGroup marked as done
  connect/proxy/listener.go
Labels: theme/connect, pr/no-changelog

#13938 peering: retry establishing connection more quickly on certain errors
  agent/consul/leader_peering.go
  agent/consul/leader_peering_test.go
  agent/grpc-external/services/peerstream/stream_resources.go
  agent/grpc-external/services/peerstream/stream_test.go
Labels: pr/no-changelog, backport/1.13

#13887 block PeerName register requests
  agent/agent.go
  agent/catalog_endpoint_test.go
  agent/config/builder.go
  agent/config/config.go
  agent/config/default.go
  agent/config/runtime.go
  agent/config/testdata/TestRuntimeConfig_Sanitize.golden
  agent/consul/catalog_endpoint.go
  agent/consul/catalog_endpoint_test.go
  agent/consul/config.go
  agent/consul/health_endpoint_test.go
  agent/consul/internal_endpoint_test.go
  agent/dns_test.go
  agent/health_endpoint_test.go
  agent/testagent.go
  agent/ui_endpoint_test.go
Labels: theme/config, pr/no-changelog, theme/cluster-peering

#13966 docs: fix k8s prepared query upstream link
  website/content/docs/k8s/annotations-and-labels.mdx
Labels: type/docs, type/docs-cherrypick, pr/no-changelog, backport/1.11, backport/1.12, backport/1.13
