Repository hashicorp/consul, pull requests merged in 2023-08, with the labels that each got.

#18337 fix typo in create a mesh token docs
  website/content/docs/security/acl/tokens/create/create-a-mesh-gateway-token.mdx
Labels: type/docs, pr/no-changelog, backport/1.12, backport/1.14, backport/1.15, backport/1.16

#18340 Backport of fix typo in create a mesh token docs into release/1.15.x
  website/content/docs/security/acl/tokens/create/create-a-mesh-gateway-token.mdx
Labels: type/docs

#18339 Backport of fix typo in create a mesh token docs into release/1.14.x
  website/content/docs/security/acl/tokens/create/create-a-mesh-gateway-token.mdx
Labels: type/docs

#18341 Backport of fix typo in create a mesh token docs into release/1.16.x
  website/content/docs/security/acl/tokens/create/create-a-mesh-gateway-token.mdx
Labels: type/docs

#18319 [CC-5719] Add support for builtin global-read-only policy
  .changelog/18319.txt
  acl/acl.go
  acl/validation.go
  acl/validation_test.go
  agent/acl_endpoint_test.go
  agent/consul/acl_endpoint.go
  agent/consul/acl_endpoint_test.go
  agent/consul/auth/token_writer.go
  agent/consul/auth/token_writer_test.go
  agent/consul/fsm/snapshot_test.go
  agent/consul/leader.go
  agent/consul/leader_test.go
  agent/consul/state/acl.go
  agent/consul/state/acl_test.go
  agent/structs/acl.go
  agent/structs/acl_oss.go
  api/acl_test.go
  website/content/docs/security/acl/acl-policies.mdx
Labels: type/docs, theme/acls, backport/1.14, backport/1.15, backport/1.16

#18342 resource: adding various helpers for working with resources
  internal/resource/decode.go
  internal/resource/decode_test.go
  internal/resource/equality.go
  internal/resource/equality_test.go
  internal/resource/mappers/bimapper/bimapper.go
  internal/resource/mappers/bimapper/bimapper_test.go
  internal/resource/reference.go
  internal/resource/refkey.go
  internal/resource/refkey_test.go
  internal/resource/resourcetest/builder.go
  internal/resource/resourcetest/client.go
  internal/resource/resourcetest/decode.go
  internal/resource/resourcetest/validation.go
  internal/resource/stringer.go
Labels: pr/no-changelog, pr/no-metrics-test, pr/no-backport

#17756 Wasm integration tests for local and remote wasm files
  test/integration/consul-container/libs/cluster/container.go
  test/integration/consul-container/libs/service/connect.go
  test/integration/consul-container/libs/service/examples.go
  test/integration/consul-container/libs/service/helpers.go
  test/integration/consul-container/libs/topology/service_topology.go
  test/integration/consul-container/test/envoy_extensions/testdata/wasm_test_files/Dockerfile
  test/integration/consul-container/test/envoy_extensions/testdata/wasm_test_files/README.md
  test/integration/consul-container/test/envoy_extensions/testdata/wasm_test_files/build.sh
  test/integration/consul-container/test/envoy_extensions/testdata/wasm_test_files/go.mod
  test/integration/consul-container/test/envoy_extensions/testdata/wasm_test_files/go.sum
  test/integration/consul-container/test/envoy_extensions/testdata/wasm_test_files/nginx.conf
  test/integration/consul-container/test/envoy_extensions/testdata/wasm_test_files/wasm_add_header.go
  test/integration/consul-container/test/envoy_extensions/testdata/wasm_test_files/wasm_add_header.wasm
  test/integration/consul-container/test/envoy_extensions/wasm_test.go
  test/integration/consul-container/test/upgrade/common.go
Labels: pr/dependencies, pr/no-changelog, pr/no-backport

#18168 [HCP Telemetry] Periodic Refresh for Dynamic Telemetry Configuration
  .changelog/18168.txt
  agent/hcp/client/client.go
  agent/hcp/client/client_test.go
  agent/hcp/client/metrics_client.go
  agent/hcp/client/mock_metrics_client.go
  agent/hcp/client/telemetry_config.go
  agent/hcp/client/telemetry_config_test.go
  agent/hcp/deps.go
  agent/hcp/deps_test.go
  agent/hcp/manager_test.go
  agent/hcp/telemetry/custom_metrics.go
  agent/hcp/telemetry/filter.go
  agent/hcp/telemetry/filter_test.go
  agent/hcp/telemetry/otel_exporter.go
  agent/hcp/telemetry/otel_exporter_test.go
  agent/hcp/telemetry/otel_sink.go
  agent/hcp/telemetry/otel_sink_test.go
  agent/hcp/telemetry_provider.go
  agent/hcp/telemetry_provider_test.go
  go.mod
  go.sum
  test-integ/go.mod
  test-integ/go.sum
  test/integration/consul-container/go.mod
  test/integration/consul-container/go.sum
Labels: backport/1.15, backport/1.16

#18348 Backport of api gw 1.16 updates into release/1.16.x
  website/content/docs/api-gateway/configuration/gateway.mdx
  website/content/docs/api-gateway/configuration/index.mdx
  website/content/docs/api-gateway/configuration/routes.mdx
  website/content/docs/api-gateway/install.mdx
  website/content/docs/api-gateway/usage/usage.mdx
Labels: type/docs

#18344 Backport of [CC-5719] Add support for builtin global-read-only policy into release/1.15.x
  .changelog/18319.txt
  acl/acl.go
  acl/validation.go
  acl/validation_test.go
  agent/acl_endpoint_test.go
  agent/consul/acl_endpoint.go
  agent/consul/acl_endpoint_test.go
  agent/consul/auth/token_writer.go
  agent/consul/auth/token_writer_test.go
  agent/consul/fsm/snapshot_test.go
  agent/consul/leader.go
  agent/consul/leader_test.go
  agent/consul/state/acl.go
  agent/consul/state/acl_test.go
  agent/structs/acl.go
  agent/structs/acl_oss.go
  api/acl_test.go
  website/content/docs/security/acl/acl-policies.mdx
Labels: type/docs, theme/api, theme/acls, theme/cli, theme/config, theme/ui, theme/connect, theme/tls, type/ci, pr/dependencies, theme/envoy/xds, theme/contributing, theme/internals, theme/certificates, theme/agent-cache, theme/consul-terraform-sync

#18302 NET-4240 - Snapshots are failing on Windows
  .changelog/18302.txt
  go.mod
  go.sum
  test-integ/go.mod
  test-integ/go.sum
Labels: pr/dependencies, backport/1.14, backport/1.15, backport/1.16

#18355 Backport of NET-4240 - Snapshots are failing on Windows into release/1.15.x
  .changelog/18302.txt
  go.mod
  go.sum
  internal/tools/proto-gen-rpc-glue/e2e/go.mod
  internal/tools/proto-gen-rpc-glue/e2e/go.sum
Labels: pr/dependencies

#18356 Backport of NET-4240 - Snapshots are failing on Windows into release/1.16.x
  .changelog/18302.txt
  go.mod
  go.sum
Labels: pr/dependencies

#18354 Backport of NET-4240 - Snapshots are failing on Windows into release/1.14.x
  .changelog/18302.txt
  go.mod
  go.sum
  test/integration/consul-container/go.mod
  test/integration/consul-container/go.sum
Labels: pr/dependencies

#18316 Register ProxyStateTemplate Resource
  internal/mesh/exports.go
  internal/mesh/internal/types/proxy_state_template.go
  internal/mesh/internal/types/types.go
  proto-public/pbmesh/v1alpha1/proxy_state.pb.go
  proto-public/pbmesh/v1alpha1/proxy_state.proto
Labels: pr/no-changelog, pr/no-backport

#18358 [NET-5146] security: Update Go version to 1.20.7 and `x/net` to 0.13.0
  .changelog/18358.txt
  .github/workflows/build.yml
  api/go.mod
  api/go.sum
  build-support/docker/Build-Go.dockerfile
  envoyextensions/go.sum
  go.mod
  go.sum
  proto-public/go.mod
  proto-public/go.sum
  sdk/go.mod
  sdk/go.sum
  test-integ/go.mod
  test-integ/go.sum
  test/integration/connect/envoy/test-sds-server/go.mod
  test/integration/connect/envoy/test-sds-server/go.sum
  test/integration/consul-container/go.mod
  test/integration/consul-container/go.sum
  testing/deployer/go.mod
  testing/deployer/go.sum
  troubleshoot/go.mod
  troubleshoot/go.sum
Labels: theme/security, backport/1.14, backport/1.15, backport/1.16

#18359 Backport of [HCP Telemetry] Periodic Refresh for Dynamic Telemetry Configuration into release/1.16.x
  .changelog/18168.txt
  agent/hcp/client/client.go
  agent/hcp/client/client_test.go
  agent/hcp/client/metrics_client.go
  agent/hcp/client/mock_metrics_client.go
  agent/hcp/client/telemetry_config.go
  agent/hcp/client/telemetry_config_test.go
  agent/hcp/deps.go
  agent/hcp/deps_test.go
  agent/hcp/manager_test.go
  agent/hcp/telemetry/custom_metrics.go
  agent/hcp/telemetry/filter.go
  agent/hcp/telemetry/filter_test.go
  agent/hcp/telemetry/otel_exporter.go
  agent/hcp/telemetry/otel_exporter_test.go
  agent/hcp/telemetry/otel_sink.go
  agent/hcp/telemetry/otel_sink_test.go
  agent/hcp/telemetry_provider.go
  agent/hcp/telemetry_provider_test.go
  go.mod
  go.sum
Labels: pr/dependencies, pr/no-backport

#18360 Backport of [HCP Telemetry] Periodic Refresh for Dynamic Telemetry Configuration into release/1.15.x
  .changelog/18168.txt
  agent/hcp/client/client.go
  agent/hcp/client/client_test.go
  agent/hcp/client/metrics_client.go
  agent/hcp/client/mock_metrics_client.go
  agent/hcp/client/telemetry_config.go
  agent/hcp/client/telemetry_config_test.go
  agent/hcp/deps.go
  agent/hcp/deps_test.go
  agent/hcp/manager_test.go
  agent/hcp/telemetry/custom_metrics.go
  agent/hcp/telemetry/filter.go
  agent/hcp/telemetry/filter_test.go
  agent/hcp/telemetry/otel_exporter.go
  agent/hcp/telemetry/otel_exporter_test.go
  agent/hcp/telemetry/otel_sink.go
  agent/hcp/telemetry/otel_sink_test.go
  agent/hcp/telemetry_provider.go
  agent/hcp/telemetry_provider_test.go
  go.mod
  go.sum
Labels: pr/dependencies, pr/no-backport

#18363 Backport of [NET-5146] security: Update Go version to 1.20.7 and `x/net` to 0.13.0 into release/1.16.x
  .changelog/18358.txt
  .github/workflows/build.yml
  api/go.mod
  api/go.sum
  build-support/docker/Build-Go.dockerfile
  envoyextensions/go.sum
  go.mod
  go.sum
  proto-public/go.mod
  proto-public/go.sum
  sdk/go.mod
  sdk/go.sum
  test/integration/connect/envoy/test-sds-server/go.mod
  test/integration/connect/envoy/test-sds-server/go.sum
  test/integration/consul-container/go.mod
  test/integration/consul-container/go.sum
  troubleshoot/go.mod
  troubleshoot/go.sum
Labels: type/ci, theme/contributing

#18362 Backport of [NET-5146] security: Update Go version to 1.20.7 and `x/net` to 0.13.0 into release/1.15.x
  .changelog/18358.txt
  .github/workflows/build.yml
  api/go.mod
  api/go.sum
  build-support/docker/Build-Go.dockerfile
  envoyextensions/go.sum
  go.mod
  go.sum
  proto-public/go.mod
  proto-public/go.sum
  sdk/go.mod
  sdk/go.sum
  test/integration/connect/envoy/test-sds-server/go.mod
  test/integration/connect/envoy/test-sds-server/go.sum
  test/integration/consul-container/go.mod
  test/integration/consul-container/go.sum
  troubleshoot/go.mod
  troubleshoot/go.sum
Labels: type/ci, theme/contributing

#18369 [OSS] test: xds coverage for routes
  agent/proxycfg/testing_api_gateway.go
  agent/proxycfg/testing_mesh_gateway.go
  agent/proxycfg/testing_terminating_gateway.go
  agent/proxycfg/testing_upstreams.go
  agent/xds/clusters.go
  agent/xds/resources_test.go
  agent/xds/routes.go
  agent/xds/routes_test.go
  agent/xds/testdata/clusters/connect-proxy-with-chain-and-overrides.latest.golden
  agent/xds/testdata/clusters/mesh-gateway-with-exported-peered-services-http-with-router.latest.golden
  agent/xds/testdata/listeners/connect-proxy-with-chain-and-overrides.latest.golden
  agent/xds/testdata/routes/connect-proxy-lb-in-resolver.latest.golden
  agent/xds/testdata/routes/connect-proxy-resolver-with-lb.latest.golden
  agent/xds/testdata/routes/connect-proxy-route-to-lb-resolver.latest.golden
  agent/xds/testdata/routes/connect-proxy-splitter-overweight.latest.golden
  agent/xds/testdata/routes/ingress-lb-in-resolver.latest.golden
  agent/xds/testdata/routes/terminating-gateway-lb-config.latest.golden
Labels: theme/envoy/xds, pr/no-changelog, pr/no-backport

#18370 Backport of Fix policy lookup to allow for slashes into release/1.14.x
  agent/acl_endpoint.go
  command/acl/acl_helpers.go
  command/acl/acl_test.go
Labels: theme/cli

#18372 Backport of Fix policy lookup to allow for slashes into release/1.16.x
  agent/acl_endpoint.go
  command/acl/acl_helpers.go
  command/acl/acl_test.go
Labels: theme/cli

#18371 Backport of Fix policy lookup to allow for slashes into release/1.15.x
  agent/acl_endpoint.go
  command/acl/acl_helpers.go
  command/acl/acl_test.go
Labels: theme/cli

#18346 add some initial CODEOWNERS
  .github/CODEOWNERS
Labels: theme/contributing, pr/no-changelog, pr/no-metrics-test, backport/1.14, backport/1.15, backport/1.16

#18373 Backport of add some initial CODEOWNERS into release/1.14.x
  .github/CODEOWNERS
Labels: theme/contributing

#18374 Backport of add some initial CODEOWNERS into release/1.15.x
  .github/CODEOWNERS
Labels: theme/contributing

#18266 Backport of NET-4897 - update comment to include the current issue url from the go team. into release/1.16.x
  api/api.go
Labels: theme/api

#18212 Backport of docs: fix the description of client rpc into release/1.15.x
  agent/consul/client.go
  website/content/docs/agent/telemetry.mdx
Labels: type/docs

#18074 Backport of ui: fix typos for peer service imports into release/1.16.x
  ui/packages/consul-ui/translations/routes/en-us.yaml
Labels: theme/ui

#18377 Add redirects for mesh-gateway docs
  website/redirects.js
Labels: type/docs, pr/no-changelog, backport/1.14, backport/1.15, backport/1.16

#18378 Backport of Add redirects for mesh-gateway docs into release/1.14.x
  website/redirects.js
Labels: type/docs

#18380 Backport of Add redirects for mesh-gateway docs into release/1.16.x
  website/redirects.js
Labels: type/docs

#18221 expose grpc as http endpoint
  agent/agent_endpoint_test.go
  agent/agent_test.go
  agent/grpc-external/services/resource/testing/testing.go
  agent/http.go
  internal/resource/http/http.go
  internal/resource/http/http_test.go
  internal/resource/registry.go
Labels: pr/no-changelog, pr/no-backport

#18375 Backport of add some initial CODEOWNERS into release/1.16.x
  .github/CODEOWNERS
Labels: theme/contributing

#18387 bimapper: fix a bug and add some more test coverage
  internal/resource/mappers/bimapper/bimapper.go
  internal/resource/mappers/bimapper/bimapper_test.go
Labels: pr/no-changelog, pr/no-metrics-test, pr/no-backport

#18389 fix: go sum revert
  api/go.sum
  envoyextensions/go.sum
  go.sum
  test/integration/consul-container/go.sum
  troubleshoot/go.sum
Labels: theme/api, pr/dependencies, pr/no-changelog, pr/no-backport

#17212 [docs] Fix ServiceDefaults example in distributed tracing
  website/content/docs/connect/distributed-tracing.mdx
Labels: type/docs, pr/no-changelog, backport/1.14, backport/1.15, backport/1.16

#18391 Backport of [docs] Fix ServiceDefaults example in distributed tracing into release/1.14.x
  website/content/docs/connect/distributed-tracing.mdx
Labels: type/docs

#18367 Fix #17730 - Dev mode has new line
  .changelog/18367.txt
  agent/http.go
Labels: pr/no-backport

#18388 chore: make go-mod-tidy
  test/integration/consul-container/test/envoy_extensions/testdata/wasm_test_files/go.mod
  test/integration/consul-container/test/envoy_extensions/testdata/wasm_test_files/go.sum
Labels: pr/no-changelog, pr/no-metrics-test, pr/no-backport

#18397 resource: Make resource read tenancy aware
  agent/consul/server.go
  agent/consul/tenancy_bridge.go
  agent/consul/tenancy_bridge_oss.go
  agent/grpc-external/services/resource/delete.go
  agent/grpc-external/services/resource/delete_test.go
  agent/grpc-external/services/resource/list.go
  agent/grpc-external/services/resource/list_by_owner.go
  agent/grpc-external/services/resource/mock_TenancyBridge.go
  agent/grpc-external/services/resource/read.go
  agent/grpc-external/services/resource/read_test.go
  agent/grpc-external/services/resource/server.go
  agent/grpc-external/services/resource/server_oss.go
  agent/grpc-external/services/resource/server_oss_test.go
  agent/grpc-external/services/resource/server_test.go
  agent/grpc-external/services/resource/testing/testing.go
  agent/grpc-external/services/resource/watch.go
  agent/grpc-external/services/resource/write.go
  agent/grpc-external/services/resource/write_status.go
  agent/grpc-external/services/resource/write_test.go
  internal/mesh/internal/types/proxy_state_template.go
  internal/resource/demo/demo.go
  internal/resource/http/http_test.go
  internal/resource/registry.go
  internal/resource/registry_test.go
  internal/resource/resourcetest/builder.go
  internal/resource/tenancy.go
  proto/private/pbdemo/v1/demo.pb.binary.go
  proto/private/pbdemo/v1/demo.pb.go
  proto/private/pbdemo/v1/demo.proto
Labels: pr/no-changelog, pr/no-backport

#18401 Not using chmod - fixed integration test for Enterprise
  .github/workflows/test-integrations-windows.yml
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#18398 replaced ordered list of rate limit ops with flow diagram
  website/content/docs/agent/limits/index.mdx
  website/public/img/agent-rate-limiting-ops-order-dark.jpg
  website/public/img/agent-rate-limiting-ops-order.jpg
Labels: type/docs, pr/no-changelog, pr/no-metrics-test, backport/1.16

#18405 Backport of replaced ordered list of rate limit ops with flow diagram into release/1.16.x
  website/content/docs/agent/limits/index.mdx
  website/public/img/agent-rate-limiting-ops-order-dark.jpg
  website/public/img/agent-rate-limiting-ops-order.jpg
Labels: type/docs

#18408 replace diagrams, fix typos
  website/content/docs/agent/limits/index.mdx
  website/public/img/agent-rate-limiting-ops-order-dark.jpg
  website/public/img/agent-rate-limiting-ops-order.jpg
Labels: type/docs, pr/no-changelog, pr/no-metrics-test, pr/no-backport

#18404 Add ServiceEndpoints Mutation hook tests
  internal/catalog/internal/types/service_endpoints.go
  internal/catalog/internal/types/service_endpoints_test.go
  internal/resource/errors.go
  internal/resource/resourcetest/builder.go
  internal/resource/resourcetest/require.go
Labels: pr/no-changelog, pr/no-backport

#18390 catalog: add FailoverPolicy mutation and validation hooks
  internal/catalog/exports.go
  internal/catalog/internal/types/failover_policy.go
  internal/catalog/internal/types/failover_policy_test.go
  proto-public/pbcatalog/v1alpha1/failover_policy_extras.go
  proto-public/pbcatalog/v1alpha1/failover_policy_extras_test.go
Labels: pr/no-changelog, pr/no-metrics-test, pr/no-backport

#18411 chore: changes from the 1.14.9 release
  CHANGELOG.md
  version/VERSION
Labels: pr/no-changelog, pr/no-backport

#18412 chore: changes from the 1.15.5 release
  CHANGELOG.md
  version/VERSION
Labels: pr/no-changelog, pr/no-backport

#18413 Backport 1.16.x Upgrade test: remove outdated test and disable log due to verbosity (…
  .github/workflows/test-integrations.yml
  test/integration/consul-container/test/upgrade/basic/fullstopupgrade_test.go
Labels: type/ci, theme/contributing, pr/no-changelog, backport/1.15

#18416 Backport 1.15.x Upgrade test: remove outdated test and disable log du…
  .github/workflows/test-integrations.yml
  test/integration/consul-container/test/upgrade/basic/fullstopupgrade_test.go
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#18399 catalog: adding a controller to reconcile FailoverPolicy resources
  internal/catalog/exports.go
  internal/catalog/internal/controllers/failover/controller.go
  internal/catalog/internal/controllers/failover/controller_test.go
  internal/catalog/internal/controllers/failover/status.go
  internal/catalog/internal/controllers/register.go
  internal/catalog/internal/mappers/failovermapper/failover_mapper.go
  internal/catalog/internal/mappers/failovermapper/failover_mapper_test.go
  internal/resource/decode.go
  internal/resource/decode_test.go
  proto/private/prototest/testing.go
Labels: pr/no-changelog, pr/no-metrics-test, pr/no-backport

#18421 fix the error in ent repo
  agent/agent_endpoint_test.go
  agent/agent_test.go
Labels: pr/no-changelog, pr/no-backport

#18414 build: updates for 1.16.1 release
  CHANGELOG.md
  version/VERSION
Labels: pr/no-changelog, pr/no-backport

#18415 build: updates for 1.16.1 release
  CHANGELOG.md
  api/go.mod
  envoyextensions/go.mod
  envoyextensions/go.sum
  go.mod
  test-integ/go.mod
  test/integration/consul-container/go.mod
  testing/deployer/go.mod
  testing/deployer/go.sum
  troubleshoot/go.mod
Labels: theme/api, pr/dependencies, pr/no-changelog, pr/no-backport

#18419 update ECS links
  website/content/docs/ecs/index.mdx
Labels: type/docs, pr/no-changelog, pr/no-backport

#18418 docs: fix incorrect proxy-defaults config in Lua Envoy extension
  website/content/docs/connect/proxies/envoy-extensions/usage/lua.mdx
Labels: type/docs

#18432 Backport of update ECS links into release/1.16.x
  website/content/docs/ecs/index.mdx
Labels: type/docs

#18423 resource: Make resource write tenancy aware
  agent/consul/tenancy_bridge_oss.go
  agent/grpc-external/services/resource/delete.go
  agent/grpc-external/services/resource/mock_TenancyBridge.go
  agent/grpc-external/services/resource/read.go
  agent/grpc-external/services/resource/read_test.go
  agent/grpc-external/services/resource/server.go
  agent/grpc-external/services/resource/server_test.go
  agent/grpc-external/services/resource/testing/testing.go
  agent/grpc-external/services/resource/write.go
  agent/grpc-external/services/resource/write_test.go
  internal/mesh/internal/types/proxy_state_template.go
  internal/resource/demo/demo.go
  internal/resource/registry.go
  internal/resource/registry_test.go
  internal/resource/tenancy.go
Labels: pr/no-changelog, pr/no-backport

#18366 NET-4984: Update APIGW Config Entries for JWT Auth
  .changelog/_18366.txt
  agent/structs/config_entry_apigw_jwt_oss.go
  agent/structs/config_entry_gateways.go
  agent/structs/config_entry_oss.go
  agent/structs/structs.deepcopy.go
  agent/structs/structs.deepcopy_oss.go
  api/config_entry_gateways.go
  api/config_entry_gateways_test.go
  command/helpers/helpers.go
  proto/private/pbconfigentry/config_entry.gen.go
  proto/private/pbconfigentry/config_entry.pb.binary.go
  proto/private/pbconfigentry/config_entry.pb.go
  proto/private/pbconfigentry/config_entry.proto
  proto/private/pbconfigentry/config_entry_oss.go
Labels: theme/api, theme/cli, pr/no-docs, theme/api-gw, pr/no-backport

#18307 k8s compat - Openshift versions
  website/content/docs/k8s/compatibility.mdx
Labels: type/docs, pr/no-changelog, backport/1.16

#18442 Backport of k8s compat - Openshift versions into release/1.16.x
  website/content/docs/k8s/compatibility.mdx
Labels: type/docs

#18422 APIGW: Update HTTPRouteConfigEntry for JWT Auth
  .changelog/_18422.txt
  agent/structs/config_entry_apigw_jwt_oss.go
  agent/structs/config_entry_routes.go
  agent/structs/structs.deepcopy.go
  agent/structs/structs.deepcopy_oss.go
  api/config_entry_routes.go
  api/config_entry_routes_test.go
  proto/private/pbconfigentry/config_entry.gen.go
  proto/private/pbconfigentry/config_entry.pb.binary.go
  proto/private/pbconfigentry/config_entry.pb.go
  proto/private/pbconfigentry/config_entry.proto
  proto/private/pbconfigentry/config_entry_oss.go
Labels: theme/api, pr/no-docs, pr/no-backport

#18441 Updates helm docs to include changes from consul-k8s 1.1.4
  website/content/docs/k8s/helm.mdx
Labels: type/docs, pr/no-changelog, pr/no-backport

#18420 Net-2708/delete resource endpoint
  internal/resource/http/http.go
  internal/resource/http/http_test.go
Labels: pr/no-changelog, pr/no-backport

#18446 Disable deep-copy codegen verification for now.
  .github/workflows/go-tests.yml
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#18426 build: upgrade to latest buf v1.26.0
  Makefile
  proto/buf.yaml
  proto/private/pbsubscribe/subscribe.pb.go
Labels: pr/no-changelog, pr/no-metrics-test, pr/no-backport

#18425 NET-4952 Add docs for export command
  website/content/commands/services/export.mdx
  website/content/commands/services/index.mdx
  website/data/commands-nav-data.json
Labels: type/docs, pr/no-changelog, backport/1.16

#18449 Backport of NET-4952 Add docs for export command into release/1.16.x
  website/content/commands/services/export.mdx
  website/content/commands/services/index.mdx
  website/data/commands-nav-data.json
Labels: type/docs

#18250 Net-2712/resource hcl parsing
  go.mod
  go.sum
  internal/protohcl/any.go
  internal/protohcl/attributes.go
  internal/protohcl/blocks.go
  internal/protohcl/cty.go
  internal/protohcl/decoder.go
  internal/protohcl/doc.go
  internal/protohcl/naming.go
  internal/protohcl/oneof.go
  internal/protohcl/primitives.go
  internal/protohcl/testproto/buf.gen.yaml
  internal/protohcl/testproto/example.pb.go
  internal/protohcl/testproto/example.proto
  internal/protohcl/unmarshal.go
  internal/protohcl/unmarshal_test.go
  internal/protohcl/well_known_types.go
  internal/resource/registry.go
  internal/resourcehcl/any.go
  internal/resourcehcl/naming.go
  internal/resourcehcl/testdata/gvk-no-arguments.error
  internal/resourcehcl/testdata/gvk-no-arguments.hcl
  internal/resourcehcl/testdata/invalid-group.error
  internal/resourcehcl/testdata/invalid-group.hcl
  internal/resourcehcl/testdata/invalid-gvk.error
  internal/resourcehcl/testdata/invalid-gvk.hcl
  internal/resourcehcl/testdata/invalid-metadata.error
  internal/resourcehcl/testdata/invalid-metadata.hcl
  internal/resourcehcl/testdata/invalid-name.error
  internal/resourcehcl/testdata/invalid-name.hcl
  internal/resourcehcl/testdata/no-blocks-any-first.golden
  internal/resourcehcl/testdata/no-blocks-any-first.hcl
  internal/resourcehcl/testdata/no-blocks.golden
  internal/resourcehcl/testdata/no-blocks.hcl
  internal/resourcehcl/testdata/owner.golden
  internal/resourcehcl/testdata/owner.hcl
  internal/resourcehcl/testdata/simple-gvk.golden
  internal/resourcehcl/testdata/simple-gvk.hcl
  internal/resourcehcl/testdata/type-block.golden
  internal/resourcehcl/testdata/type-block.hcl
  internal/resourcehcl/testdata/unknown-field-block.error
  internal/resourcehcl/testdata/unknown-field-block.hcl
  internal/resourcehcl/testdata/unknown-field-object.error
  internal/resourcehcl/testdata/unknown-field-object.hcl
  internal/resourcehcl/testdata/unknown-type.error
  internal/resourcehcl/testdata/unknown-type.hcl
  internal/resourcehcl/testdata/upstreams.golden
  internal/resourcehcl/testdata/upstreams.hcl
  internal/resourcehcl/unmarshal.go
  internal/resourcehcl/unmarshal_test.go
Labels: pr/dependencies, pr/no-changelog, pr/no-backport

#18450 Update Helm docs for consul-k8s 1.2.1
  website/content/docs/k8s/helm.mdx
Labels: type/docs, pr/no-changelog, pr/no-backport

#18268 read endpoint
  internal/resource/http/http.go
  internal/resource/http/http_test.go
Labels: pr/no-changelog, pr/no-backport

#18447 Updates helm values for consul-k8s 1.0.9
  website/content/docs/k8s/helm.mdx
Labels: type/docs, pr/no-changelog, pr/no-backport

#18463 Fix incorrect yaml in examples
  website/content/docs/connect/config-entries/service-intentions.mdx
Labels: type/docs, pr/no-changelog, backport/1.16

#18461 NET-5187: Upgrade test timeout due to log producer errors
  test/integration/consul-container/libs/service/connect.go
Labels: pr/no-changelog, backport/1.15, backport/1.16

#18468 Updates 1.15.x for changes to helm docs
  website/content/docs/k8s/helm.mdx
Labels: type/docs, pr/no-changelog, pr/no-backport

#18469 Backport of Fix incorrect yaml in examples into release/1.16.x
  website/content/docs/connect/config-entries/service-intentions.mdx
Labels: type/docs

#18436 [NET-4799] [OSS] xdsv2: listeners L4 support for connect proxies
  agent/xds/clusters.go
  agent/xds/config/config.go
  agent/xds/config/config_test.go
  agent/xds/configfetcher/config_fetcher.go
  agent/xds/listeners.go
  agent/xds/listeners_apigateway.go
  agent/xds/listeners_ingress.go
  agent/xds/listeners_test.go
  agent/xds/naming/naming.go
  agent/xds/platform/net_fallback.go
  agent/xds/platform/net_linux.go
  agent/xds/proxystateconverter/clusters.go
  agent/xds/proxystateconverter/converter.go
  agent/xds/proxystateconverter/listeners.go
  agent/xds/resources.go
  agent/xds/routes.go
  agent/xds/server.go
  agent/xdsv2/cluster_resources.go
  agent/xdsv2/listener_resources.go
  agent/xdsv2/resources.go
  agent/xdsv2/route_resources.go
  proto-public/pbmesh/v1alpha1/proxy_state.pb.go
  proto-public/pbmesh/v1alpha1/proxy_state.proto
  test/integration/connect/envoy/helpers.bash
  test/integration/connect/envoy/helpers.windows.bash
Labels: theme/envoy/xds, pr/no-changelog, pr/no-backport

#18475 resource: Make resource list tenancy aware
  agent/grpc-external/services/resource/list.go
  agent/grpc-external/services/resource/list_test.go
  agent/grpc-external/services/resource/watch.go
  internal/mesh/internal/types/proxy_state_template.go
  internal/resource/demo/demo.go
  internal/resource/registry.go
  internal/resource/registry_test.go
Labels: pr/no-changelog, pr/no-backport

#18477 docs: specify manual server metadata intervention
  website/content/docs/agent/config/config-files.mdx
Labels: type/docs, pr/no-changelog, backport/1.15

#18478 docs: Update OpenShift compatibility
  website/content/docs/k8s/compatibility.mdx
Labels: type/docs, pr/no-changelog, backport/1.16

#18476 resource: Make resource delete tenancy aware
  agent/grpc-external/services/resource/delete.go
  agent/grpc-external/services/resource/delete_test.go
  agent/grpc-external/services/resource/read_test.go
  agent/grpc-external/services/resource/server_test.go
Labels: pr/no-changelog, pr/no-backport

#18481 Backport of docs: Update OpenShift compatibility into release/1.16.x
  website/content/docs/k8s/compatibility.mdx
Labels: type/docs

#18483 docs: specify manual server metadata intervention
  website/content/docs/agent/config/config-files.mdx
Labels: type/docs, pr/no-changelog, pr/no-backport

#18485 Add license-checker action that fails when any backported file contains BUSL header
  .github/scripts/license_checker.sh
  .github/workflows/license-checker.yml
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#18487 Backport of Add license-checker action that fails when any backported file contains BUSL header into release/1.15.x
  .github/scripts/license_checker.sh
  .github/workflows/license-checker.yml
Labels: type/ci, theme/contributing

#18488 Backport of Add license-checker action that fails when any backported file contains BUSL header into release/1.14.x
  .github/scripts/license_checker.sh
  .github/workflows/license-checker.yml
Labels: type/docs, theme/api, theme/health-checks, theme/acls, theme/cli, theme/config, theme/ui, theme/connect, theme/tls, theme/telemetry, type/ci, pr/dependencies, theme/envoy/xds, theme/contributing, theme/internals, theme/certificates, theme/agent-cache, theme/consul-terraform-sync

#18489 Backport of Add license-checker action that fails when any backported file contains BUSL header into release/1.16.x
  .github/scripts/license_checker.sh
  .github/workflows/license-checker.yml
Labels: type/ci, theme/contributing

#18474 docs: Update K8s TGW tutorial to reliably obtain role ID
  website/content/docs/k8s/connect/terminating-gateways.mdx
Labels: type/docs, pr/no-changelog, backport/1.13, backport/1.14, backport/1.15, backport/1.16

#18491 NET-5371 License checker pt2
  .github/scripts/license_checker.sh
  .github/workflows/license-checker.yml
Labels: type/ci, theme/contributing, pr/no-changelog, backport/1.14, backport/1.15, backport/1.16

#18493 Backport of NET-5371 License checker pt2 into release/1.14.x
  .github/scripts/license_checker.sh
  .github/workflows/license-checker.yml
Labels: type/ci, theme/contributing

#18495 Backport of NET-5371 License checker pt2 into release/1.16.x
  .github/scripts/license_checker.sh
  .github/workflows/license-checker.yml
Labels: type/ci, theme/contributing

#18494 Backport of NET-5371 License checker pt2 into release/1.15.x
  .github/scripts/license_checker.sh
  .github/workflows/license-checker.yml
Labels: type/ci, pr/dependencies

#18301 README - Update KV use case to Dynamic App Configuration
  README.md
  website/content/docs/dynamic-app-config/kv.mdx
Labels: type/docs, pr/no-changelog, backport/1.16

#18498 README - re-order badges and update hub link
  README.md
Labels: pr/no-changelog, pr/no-backport

#18497 manual backport of #18301
  README.md
  website/content/docs/dynamic-app-config/kv.mdx
Labels: type/docs, pr/no-changelog, pr/no-backport

#18484 [NET-5163] Support locality testing in consul-container
  sdk/testutil/retry/timer.go
  test/integration/consul-container/libs/assert/service.go
  test/integration/consul-container/libs/service/connect.go
  test/integration/consul-container/libs/service/helpers.go
  test/integration/consul-container/libs/topology/peering_topology.go
  test/integration/consul-container/libs/topology/service_topology.go
  test/integration/consul-container/test/envoy_extensions/ext_authz_test.go
  test/integration/consul-container/test/envoy_extensions/wasm_test.go
  test/integration/consul-container/test/jwtauth/jwt_auth_test.go
  test/integration/consul-container/test/tproxy/tproxy_test.go
  test/integration/consul-container/test/upgrade/ingress_gateway_grpc_test.go
  test/integration/consul-container/test/upgrade/l7_traffic_management/resolver_default_subset_test.go
  test/integration/consul-container/test/upgrade/peering/peering_control_plane_mgw_test.go
  test/integration/consul-container/test/upgrade/peering/peering_http_test.go
  test/integration/consul-container/test/wanfed/wanfed_peering_test.go
Labels: pr/no-changelog, backport/1.16

#18507 Backport of docs: Update K8s TGW tutorial to reliably obtain role ID into release/1.15.x
  website/content/docs/k8s/connect/terminating-gateways.mdx
Labels: type/docs

#18508 Backport of docs: Update K8s TGW tutorial to reliably obtain role ID into release/1.16.x
  website/content/docs/k8s/connect/terminating-gateways.mdx
Labels: type/docs

#18499 NET-4853 - xds v2 - implement base connect proxy functionality for clusters
  agent/xds/clusters.go
  agent/xds/clusters_test.go
  agent/xds/delta_envoy_extender_oss_test.go
  agent/xds/endpoints.go
  agent/xds/endpoints_test.go
  agent/xds/listeners.go
  agent/xds/listeners_test.go
  agent/xds/proxystateconverter/clusters.go
  agent/xds/proxystateconverter/converter.go
  agent/xds/proxystateconverter/endpoints.go
  agent/xds/proxystateconverter/failover_policy.go
  agent/xds/proxystateconverter/failover_policy_oss.go
  agent/xds/proxystateconverter/listeners.go
  agent/xds/rbac.go
  agent/xds/resources_test.go
  agent/xds/response/response.go
  agent/xds/routes.go
  agent/xds/routes_test.go
  agent/xds/xds_protocol_helpers_test.go
  agent/xdsv2/cluster_resources.go
  agent/xdsv2/endpoint_resources.go
  agent/xdsv2/listener_resources.go
  agent/xdsv2/resources.go
  agent/xdsv2/route_resources.go
  proto-public/pbmesh/v1alpha1/pbproxystate/cluster.pb.go
  proto-public/pbmesh/v1alpha1/pbproxystate/cluster.proto
  proto-public/pbmesh/v1alpha1/pbproxystate/transport_socket.pb.go
  proto-public/pbmesh/v1alpha1/pbproxystate/transport_socket.proto
Labels: theme/envoy/xds, pr/no-changelog, pr/no-backport

#18513 Fix HCL
  website/content/docs/connect/cluster-peering/usage/create-sameness-groups.mdx
Labels: type/docs, pr/no-changelog, backport/1.16

#18500 NET-4932 - xds v2 - implement base connect proxy functionality for endpoints
  agent/xds/clusters_test.go
  agent/xds/endpoints_test.go
  agent/xds/proxystateconverter/clusters.go
  agent/xds/proxystateconverter/converter.go
  agent/xds/proxystateconverter/endpoints.go
  agent/xds/proxystateconverter/locality_policy.go
  agent/xds/proxystateconverter/locality_policy_oss.go
  agent/xdsv2/endpoint_resources.go
  agent/xdsv2/resources.go
Labels: theme/envoy/xds, pr/no-changelog, pr/no-backport

#18514 Backport of Fix HCL into release/1.16.x
  website/content/docs/connect/cluster-peering/usage/create-sameness-groups.mdx
Labels: type/docs

#18439 Support custom watches on controller
  .changelog/18439.txt
  internal/controller/api.go
  internal/controller/api_test.go
  internal/controller/controller.go
  internal/controller/dependency_mappers.go
Labels: pr/no-backport

#18501 NET-4858 - xds v2 - implement base connect proxy functionality for routes
  agent/xds/clusters_test.go
  agent/xds/endpoints_test.go
  agent/xds/proxystateconverter/clusters.go
  agent/xds/proxystateconverter/converter.go
  agent/xds/proxystateconverter/routes.go
  agent/xds/routes_test.go
  agent/xdsv2/cluster_resources.go
  agent/xdsv2/listener_resources.go
  agent/xdsv2/resources.go
  agent/xdsv2/route_resources.go
  proto-public/pbmesh/v1alpha1/pbproxystate/cluster.pb.go
  proto-public/pbmesh/v1alpha1/pbproxystate/cluster.proto
  proto-public/pbmesh/v1alpha1/proxy_state.pb.go
  proto-public/pbmesh/v1alpha1/proxy_state.proto
Labels: theme/envoy/xds, pr/no-changelog, pr/no-backport

#18451 bimapper: allow to untrack links and support reference or id
  internal/catalog/internal/mappers/failovermapper/failover_mapper.go
  internal/resource/equality.go
  internal/resource/mappers/bimapper/bimapper.go
  internal/resource/mappers/bimapper/bimapper_test.go
Labels: pr/no-changelog, pr/no-backport

#18519 bimapper: fix data race
  internal/resource/mappers/bimapper/bimapper.go
Labels: pr/no-changelog, pr/no-backport

#18518 CI Split integration tests to run nightly and every PR
  .github/workflows/nightly-test-integrations.yml
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#18522 Fix broken links caught in weekly report
  website/content/api-docs/agent/service.mdx
  website/content/commands/exec.mdx
  website/content/docs/agent/config/config-files.mdx
  website/content/docs/agent/limits/usage/init-rate-limits.mdx
  website/content/docs/agent/limits/usage/limit-request-rates-from-ips.mdx
  website/content/docs/agent/limits/usage/monitor-rate-limits.mdx
  website/content/docs/agent/limits/usage/set-global-traffic-rate-limits.mdx
  website/content/docs/connect/ca/vault.mdx
  website/content/docs/connect/proxies/envoy-extensions/configuration/wasm.mdx
  website/content/docs/ecs/terraform/secure-configuration.mdx
  website/content/docs/enterprise/index.mdx
  website/content/docs/k8s/connect/onboarding-tproxy-mode.mdx
  website/content/docs/k8s/deployment-configurations/multi-cluster/vms-and-kubernetes.mdx
  website/content/docs/release-notes/consul/v1_11_x.mdx
  website/content/docs/release-notes/consul/v1_12_x.mdx
  website/content/docs/security/acl/acl-federated-datacenters.mdx
  website/content/docs/security/acl/acl-policies.mdx
  website/content/docs/security/acl/index.mdx
  website/content/docs/services/discovery/dns-static-lookups.mdx
  website/content/docs/upgrading/upgrade-specific.mdx
Labels: type/docs, pr/no-changelog, backport/1.14, backport/1.15, backport/1.16

#18535 NET-4943 - Implement ProxyTracker
  agent/proxy-tracker/mock_Logger.go
  agent/proxy-tracker/mock_SessionLimiter.go
  agent/proxy-tracker/proxy_tracker.go
  agent/proxy-tracker/proxy_tracker_test.go
Labels: pr/no-changelog, pr/no-backport

#18539 resource: Make resource watchlist tenancy aware
  agent/grpc-external/services/resource/list_test.go
  agent/grpc-external/services/resource/server_test.go
  agent/grpc-external/services/resource/watch.go
  agent/grpc-external/services/resource/watch_test.go
Labels: pr/no-changelog, pr/no-backport

#18540 Reduce required type arguments for DecodedResource
  internal/catalog/exports.go
  internal/catalog/internal/controllers/failover/controller.go
  internal/catalog/internal/mappers/failovermapper/failover_mapper.go
  internal/catalog/internal/mappers/failovermapper/failover_mapper_test.go
  internal/catalog/internal/types/failover_policy_test.go
  internal/resource/decode.go
  internal/resource/decode_test.go
  internal/resource/resourcetest/decode.go
Labels: pr/no-changelog, pr/no-metrics-test, pr/no-backport

#18538 CI: fix envoy versions in CI of release branch
  .github/workflows/nightly-test-integrations-1.15.x.yml
  .github/workflows/nightly-test-integrations-1.16.x.yml
  .github/workflows/reusable-dev-build.yml
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#18545 catalog: add failover mode enum validation
  internal/catalog/internal/types/failover_policy.go
  internal/catalog/internal/types/failover_policy_test.go
Labels: pr/no-changelog, pr/no-metrics-test, pr/no-backport

#18544 xds controller: resolve ServiceEndpoints references in ProxyStateTemp…
  internal/mesh/internal/controllers/xds/controller.go
  internal/mesh/internal/controllers/xds/controller_test.go
  internal/mesh/internal/controllers/xds/endpoint_builder.go
  internal/mesh/internal/controllers/xds/endpoint_builder_test.go
  internal/mesh/internal/controllers/xds/mock_updater.go
  internal/mesh/internal/controllers/xds/reconciliation_data.go
  internal/mesh/internal/controllers/xds/status/status.go
Labels: pr/no-changelog, pr/no-backport

#18448 mesh: adding type aliases for mesh resource usage
  internal/mesh/internal/types/decoded.go
  internal/resource/decode.go
Labels: pr/no-changelog, pr/no-metrics-test, pr/no-backport

#18550 Update trust bundle into proxy-state-template
  agent/consul/server.go
  internal/mesh/exports.go
  internal/mesh/internal/controllers/register.go
  internal/mesh/internal/controllers/xds/controller.go
  internal/mesh/internal/controllers/xds/controller_test.go
  internal/mesh/internal/controllers/xds/mock_updater.go
  internal/mesh/internal/controllers/xds/status/status.go
Labels: pr/no-changelog, pr/no-backport

#18554 catalog: validating Protocol and Health enums on Service, Workload, and ServiceEndpoints
  internal/catalog/internal/types/service.go
  internal/catalog/internal/types/service_endpoints.go
  internal/catalog/internal/types/service_endpoints_test.go
  internal/catalog/internal/types/service_test.go
  internal/catalog/internal/types/validators.go
  internal/catalog/internal/types/validators_test.go
  internal/catalog/internal/types/workload.go
  internal/catalog/internal/types/workload_test.go
Labels: pr/no-changelog, pr/no-metrics-test, pr/no-backport

#18555 chore: fix missing/incorrect license headers
  .copywrite.hcl
  agent/xds/configfetcher/config_fetcher.go
  agent/xds/proxystateconverter/locality_policy.go
  agent/xds/proxystateconverter/locality_policy_ce.go
  internal/mesh/internal/controllers/register.go
  internal/mesh/internal/controllers/xds/controller.go
  internal/mesh/internal/controllers/xds/controller_test.go
  internal/mesh/internal/controllers/xds/endpoint_builder.go
  internal/mesh/internal/controllers/xds/endpoint_builder_test.go
  internal/mesh/internal/controllers/xds/mock_updater.go
  internal/mesh/internal/controllers/xds/reconciliation_data.go
  internal/mesh/internal/controllers/xds/status/status.go
  internal/protohcl/any.go
  internal/protohcl/attributes.go
  internal/protohcl/blocks.go
  internal/protohcl/cty.go
  internal/protohcl/decoder.go
  internal/protohcl/doc.go
  internal/protohcl/naming.go
  internal/protohcl/oneof.go
  internal/protohcl/primitives.go
  internal/protohcl/testproto/buf.gen.yaml
  internal/protohcl/testproto/example.pb.go
  internal/protohcl/testproto/example.proto
  internal/protohcl/unmarshal.go
  internal/protohcl/unmarshal_test.go
  internal/protohcl/well_known_types.go
  internal/resourcehcl/any.go
  internal/resourcehcl/naming.go
  internal/resourcehcl/unmarshal.go
  internal/resourcehcl/unmarshal_test.go
Labels: theme/envoy/xds, pr/no-changelog, pr/no-metrics-test, pr/no-backport

#18464 fix for , non presence of consul-version meta
  .changelog/18464.txt
  ui/packages/consul-ui/app/serializers/application.js
  ui/packages/consul-ui/mock-api/v1/internal/ui/nodes
  ui/packages/consul-ui/tests/unit/serializers/application-test.js
Labels: theme/ui, backport/1.16

#18541 feat: add experiments flag to testserver sdk
  sdk/testutil/server.go
Labels: pr/no-changelog, pr/no-backport

#18558 bug: prevent go routine leakage due to existing DeferCheck
  .changelog/18558.txt
  agent/local/state.go
Labels: backport/1.15, backport/1.16

#18561 fix for , non presence of consul-version meta (#18464)
  .changelog/18464.txt
  ui/packages/consul-ui/app/serializers/application.js
  ui/packages/consul-ui/mock-api/v1/internal/ui/nodes
  ui/packages/consul-ui/tests/unit/serializers/application-test.js
Labels: theme/ui, pr/no-backport

#18528 NET-5382 & PLAT-1159: Do not trigger workflow if only doc files are in commit history
  .github/scripts/filter_changed_files_go_test.sh
  .github/workflows/go-tests.yml
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing, pr/no-changelog, backport/1.15, backport/1.16

#18569 Backport of NET-5382 & PLAT-1159: Do not trigger workflow if only doc files are in commit history into release/1.15.x
  .github/scripts/filter_changed_files_go_test.sh
  .github/workflows/go-tests.yml
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing

#18570 Backport of NET-5382 & PLAT-1159: Do not trigger workflow if only doc files are in commit history into release/1.16.x
  .github/scripts/filter_changed_files_go_test.sh
  .github/workflows/go-tests.yml
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing

#18560 UI: community verbiage
  .changelog/18560.txt
  ui/packages/consul-peerings/app/components/consul/peer/form/token/fieldsets/index.hbs
Labels: theme/ui, pr/no-backport

#18537 Backport of docs: Fix spelling errors across various pages on the site into release/1.16.x
  website/content/commands/intention/list.mdx
  website/content/commands/kv/index.mdx
  website/content/commands/services/deregister.mdx
  website/content/commands/services/register.mdx
  website/content/docs/agent/limits/usage/limit-request-rates-from-ips.mdx
  website/content/docs/agent/limits/usage/set-global-traffic-rate-limits.mdx
  website/content/docs/agent/wal-logstore/index.mdx
  website/content/docs/agent/wal-logstore/revert-to-boltdb.mdx
  website/content/docs/api-gateway/upgrades.mdx
  website/content/docs/architecture/anti-entropy.mdx
  website/content/docs/architecture/scale.mdx
  website/content/docs/connect/cluster-peering/index.mdx
  website/content/docs/connect/config-entries/control-plane-request-limit.mdx
  website/content/docs/connect/config-entries/exported-services.mdx
  website/content/docs/connect/config-entries/ingress-gateway.mdx
  website/content/docs/connect/config-entries/jwt-provider.mdx
  website/content/docs/connect/config-entries/service-defaults.mdx
  website/content/docs/connect/config-entries/service-intentions.mdx
  website/content/docs/connect/config-entries/service-resolver.mdx
  website/content/docs/connect/config-entries/service-router.mdx
  website/content/docs/connect/dataplane/consul-dataplane.mdx
  website/content/docs/connect/gateways/mesh-gateway/index.mdx
  website/content/docs/connect/gateways/mesh-gateway/peering-via-mesh-gateways.mdx
  website/content/docs/connect/intentions/create-manage-intentions.mdx
  website/content/docs/connect/proxies/envoy-extensions/configuration/wasm.mdx
  website/content/docs/connect/proxies/envoy-extensions/index.mdx
  website/content/docs/connect/proxies/envoy.mdx
  website/content/docs/consul-vs-other/service-mesh-compare.mdx
  website/content/docs/ecs/compatibility.mdx
  website/content/docs/enterprise/index.mdx
  website/content/docs/enterprise/license/utilization-reporting.mdx
  website/content/docs/enterprise/network-segments/create-network-segment.mdx
  website/content/docs/k8s/connect/index.mdx
  website/content/docs/k8s/deployment-configurations/vault/wan-federation.mdx
  website/content/docs/k8s/helm.mdx
  website/content/docs/k8s/service-sync.mdx
  website/content/docs/k8s/upgrade/index.mdx
  website/content/docs/nia/usage/requirements.mdx
  website/content/docs/nia/usage/run-ha.mdx
  website/content/docs/release-notes/consul-k8s/v1_0_x.mdx
  website/content/docs/release-notes/consul/v1_15_x.mdx
  website/content/docs/services/configuration/checks-configuration-reference.mdx
  website/content/docs/services/discovery/dns-overview.mdx
  website/content/docs/services/discovery/dns-static-lookups.mdx
  website/content/docs/services/services.mdx
  website/content/docs/services/usage/define-services.mdx
Labels: type/docs

#18572 CE port of enterprise extension
  agent/envoyextensions/registered_extensions.go
  agent/envoyextensions/registered_extensions_ce.go
  envoyextensions/extensioncommon/resources.go
  proto/private/prototest/testing.go
Labels: pr/no-changelog, pr/no-backport

#18575 NET-5147: Added placeholder structs for JWT functionality
  agent/proxycfg/api_gateway_ce.go
  agent/xds/gw_per_route_filters_ce.go
  agent/xds/jwt_authn_ce.go
  agent/xds/rbac.go
  agent/xds/resources_ce_test.go
  agent/xds/resources_test.go
Labels: theme/envoy/xds, pr/no-changelog, pr/no-docs, pr/no-backport

#18577 resource: Make resource writestatus tenancy aware
  agent/grpc-external/services/resource/write_status.go
  agent/grpc-external/services/resource/write_status_test.go
  agent/grpc-external/services/resource/write_test.go
Labels: pr/no-changelog, pr/no-backport

#18579 NET-5338 - NET-5338 - Run a v2 mode xds server
  agent/agent.go
  agent/agent_test.go
  agent/config/default.go
  agent/config/runtime_test.go
  agent/consul/server.go
  agent/proxy-tracker/mock_Logger.go
  agent/proxy-tracker/proxy_tracker.go
  agent/proxy-tracker/proxy_tracker_test.go
  agent/proxycfg-sources/catalog/config_source.go
  agent/proxycfg-sources/catalog/config_source_oss.go
  agent/proxycfg-sources/catalog/config_source_test.go
  agent/proxycfg-sources/catalog/mock_ConfigManager.go
  agent/proxycfg-sources/catalog/mock_Watcher.go
  agent/proxycfg-sources/local/config_source.go
  agent/proxycfg-sources/local/mock_ConfigManager.go
  agent/proxycfg-sources/local/sync.go
  agent/proxycfg/manager.go
  agent/proxycfg/manager_test.go
  agent/proxycfg/proxysnapshot.go
  agent/proxycfg/proxysnapshot_test.go
  agent/proxycfg_test.go
  agent/xds/delta.go
  agent/xds/delta_test.go
  agent/xds/protocol_trace.go
  agent/xds/proxystateconverter/converter.go
  agent/xds/proxystateconverter/endpoints.go
  agent/xds/server.go
  agent/xds/xds_protocol_helpers_test.go
  agent/xdsv2/endpoint_resources.go
  agent/xdsv2/resources.go
  internal/mesh/proxy_state_exports.go
  test/integration/connect/envoy/main_test.go
  test/integration/connect/envoy/run-tests.sh
Labels: theme/config, theme/envoy/xds, pr/no-changelog, pr/no-backport

#18578 CI: send slack notification on failed nightly job
  .github/scripts/notify_slack.sh
  .github/workflows/nightly-test-integrations-1.15.x.yml
  .github/workflows/nightly-test-integrations-1.16.x.yml
  .github/workflows/nightly-test-integrations.yml
Labels: pr/no-changelog, backport/1.15, backport/1.16

#18583 CE commit
  .changelog/18583.txt
  agent/configentry/merge_service_config.go
  agent/configentry/merge_service_config_test.go
  agent/configentry/resolve.go
  agent/structs/config_entry.go
  agent/structs/config_entry_ce.go
  agent/structs/structs.deepcopy.go
  api/config_entry.go
  proto/private/pbconfigentry/config_entry.gen.go
  proto/private/pbconfigentry/config_entry.pb.binary.go
  proto/private/pbconfigentry/config_entry.pb.go
  proto/private/pbconfigentry/config_entry.proto
Labels: theme/api, pr/no-backport

#18511 Fix broken link on sameness group page
  website/content/docs/connect/failover/index.mdx
Labels: type/docs, pr/no-changelog, backport/1.16

#18551 Fix typo in permissive mTLS docs
  website/content/docs/k8s/connect/onboarding-tproxy-mode.mdx
Labels: type/docs, pr/no-changelog, backport/1.16

#18588 Backport of Fix broken link on sameness group page into release/1.16.x
  website/content/docs/connect/failover/index.mdx
Labels: type/docs

#18567 Set concurrency for workflows
  .github/workflows/build-distros.yml
  .github/workflows/go-tests.yml
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing, pr/no-changelog, backport/1.13, backport/1.14, backport/1.15, backport/1.16

#18584 Reduce the frequency of HCP OTEL metric exports to minutely
  .changelog/18584.txt
  agent/hcp/deps.go
  agent/hcp/telemetry/otel_exporter.go
  agent/hcp/telemetry/otel_exporter_test.go
  agent/hcp/telemetry/otel_sink.go
Labels: pr/no-metrics-test, backport/1.15, backport/1.16

#18599 Reduce the frequency of metric exports to minutely (#18584)
  .changelog/18584.txt
  agent/hcp/deps.go
  agent/hcp/telemetry/otel_exporter.go
  agent/hcp/telemetry/otel_exporter_test.go
  agent/hcp/telemetry/otel_sink.go
Labels: pr/no-metrics-test, pr/no-backport

#18601 Reduce the frequency of metric exports to minutely (#18584)
  .changelog/18584.txt
  agent/hcp/deps.go
  agent/hcp/telemetry/otel_exporter.go
  agent/hcp/telemetry/otel_exporter_test.go
  agent/hcp/telemetry/otel_sink.go
Labels: pr/no-metrics-test, pr/no-backport

#18527 Backport of Fix broken links caught in weekly report into release/1.16.x
  website/content/api-docs/agent/service.mdx
  website/content/commands/exec.mdx
  website/content/docs/agent/config/config-files.mdx
  website/content/docs/agent/limits/usage/init-rate-limits.mdx
  website/content/docs/agent/limits/usage/limit-request-rates-from-ips.mdx
  website/content/docs/agent/limits/usage/monitor-rate-limits.mdx
  website/content/docs/agent/limits/usage/set-global-traffic-rate-limits.mdx
  website/content/docs/connect/ca/vault.mdx
  website/content/docs/connect/proxies/envoy-extensions/configuration/wasm.mdx
  website/content/docs/ecs/terraform/secure-configuration.mdx
  website/content/docs/enterprise/index.mdx
  website/content/docs/k8s/connect/onboarding-tproxy-mode.mdx
  website/content/docs/k8s/deployment-configurations/multi-cluster/vms-and-kubernetes.mdx
  website/content/docs/release-notes/consul/v1_11_x.mdx
  website/content/docs/release-notes/consul/v1_12_x.mdx
  website/content/docs/security/acl/acl-federated-datacenters.mdx
  website/content/docs/security/acl/acl-policies.mdx
  website/content/docs/security/acl/index.mdx
  website/content/docs/services/discovery/dns-static-lookups.mdx
  website/content/docs/upgrading/upgrade-specific.mdx
Labels: type/docs

#18611 Watch the ProxyTracker from xDS controller
  agent/agent.go
  agent/consul/server.go
  agent/proxycfg-sources/catalog/config_source.go
  agent/proxycfg-sources/catalog/config_source_test.go
  agent/proxycfg-sources/catalog/mock_ConfigManager.go
  agent/proxycfg-sources/catalog/mock_SessionLimiter.go
  agent/proxycfg-sources/catalog/mock_Watcher.go
  agent/proxycfg-sources/local/mock_ConfigManager.go
  agent/proxycfg/manager.go
  agent/proxycfg/manager_test.go
  agent/proxycfg_test.go
  agent/xds/delta.go
  agent/xds/proxystateconverter/converter.go
  agent/xds/server.go
  agent/xds/xds_protocol_helpers_test.go
  agent/xdsv2/resources.go
  internal/mesh/internal/controllers/xds/controller.go
  internal/mesh/internal/controllers/xds/controller_test.go
  internal/mesh/internal/controllers/xds/mock_updater.go
  internal/mesh/internal/controllers/xds/proxy_tracker_watch.go
  internal/mesh/proxy-tracker/mock_SessionLimiter.go
  internal/mesh/proxy-tracker/proxy_tracker.go
  internal/mesh/proxy-tracker/proxy_tracker_test.go
Labels: theme/envoy/xds, pr/no-changelog, pr/no-backport

#18612 Distinguish v2 catalog Protocol unset from default
  proto-public/pbcatalog/v1alpha1/protocol.pb.go
  proto-public/pbcatalog/v1alpha1/protocol.proto
  proto-public/pbcatalog/v1alpha1/service.pb.go
  proto-public/pbcatalog/v1alpha1/workload.pb.go
Labels: pr/no-changelog, pr/no-docs, pr/no-backport

#18336 Added OTEL access logging envoy extension
  .changelog/18336.txt
  agent/envoyextensions/builtin/ext-authz/ext_authz.go
  agent/envoyextensions/builtin/otel-access-logging/otel_access_logging.go
  agent/envoyextensions/builtin/otel-access-logging/otel_access_logging_test.go
  agent/envoyextensions/builtin/otel-access-logging/structs.go
  agent/envoyextensions/registered_extensions.go
  api/config_entry.go
  website/content/docs/connect/proxies/envoy-extensions/configuration/ext-authz.mdx
  website/content/docs/connect/proxies/envoy-extensions/configuration/otel-access-logging.mdx
  website/content/docs/connect/proxies/envoy-extensions/index.mdx
  website/content/docs/connect/proxies/envoy-extensions/usage/ext-authz.mdx
  website/content/docs/connect/proxies/envoy-extensions/usage/otel-access-logging.mdx
  website/data/docs-nav-data.json
Labels: theme/api, pr/no-backport

#18318 [HCP Telemetry] Move first TelemetryConfig Fetch into the TelemetryConfigProvider
  agent/hcp/client/telemetry_config.go
  agent/hcp/client/telemetry_config_test.go
  agent/hcp/deps.go
  agent/hcp/deps_test.go
  agent/hcp/telemetry/otel_exporter.go
  agent/hcp/telemetry/otel_exporter_test.go
  agent/hcp/telemetry/otel_sink.go
  agent/hcp/telemetry/otel_sink_test.go
  agent/hcp/telemetry/otlp_transform.go
  agent/hcp/telemetry/otlp_transform_test.go
  agent/hcp/telemetry_provider.go
  agent/hcp/telemetry_provider_test.go
  go.mod
  go.sum
  test-integ/go.mod
  test-integ/go.sum
  test/integration/consul-container/go.mod
  test/integration/consul-container/go.sum
  troubleshoot/go.sum
Labels: pr/no-changelog, backport/1.15, backport/1.16

#18614 update comments and docs about running envoy integration tests with the ENVOY_VERSION set.
  Makefile
  build-support/windows/build-consul-local-images.sh
  test/integration/connect/envoy/README.md
  test/integration/connect/envoy/run-tests.sh
  test/integration/connect/envoy/run-tests.windows.sh
Labels: pr/no-changelog, pr/no-backport

#18621 delete all v2 resources type when deleting a namespace (CE)
  agent/consul/client_test.go
  agent/consul/server.go
  internal/catalog/internal/types/service.go
Labels: pr/no-changelog, pr/no-backport

#18618 resource: Allow nil tenancy
  agent/grpc-external/services/resource/delete_test.go
  agent/grpc-external/services/resource/list_by_owner_test.go
  agent/grpc-external/services/resource/read_test.go
  agent/grpc-external/services/resource/server.go
  agent/grpc-external/services/resource/server_test.go
  agent/grpc-external/services/resource/write_status.go
  agent/grpc-external/services/resource/write_status_test.go
  agent/grpc-external/services/resource/write_test.go
Labels: pr/no-changelog, pr/no-backport
