Repository hashicorp/consul, pull requests merged in 2023-12, with the labels that each got.

#19783 NET-6692: Ensure 'upload test results' step is always run
  .github/workflows/nightly-test-integ-peering_commontopo.yml
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#19794 made node parition scoped
  internal/catalog/catalogtest/integration_test_data/v2beta1/node-1-health.json
  internal/catalog/catalogtest/integration_test_data/v2beta1/node-1.json
  internal/catalog/catalogtest/integration_test_data/v2beta1/node-2-health.json
  internal/catalog/catalogtest/integration_test_data/v2beta1/node-2.json
  internal/catalog/catalogtest/integration_test_data/v2beta1/node-3-health.json
  internal/catalog/catalogtest/integration_test_data/v2beta1/node-3.json
  internal/catalog/catalogtest/integration_test_data/v2beta1/node-4-health.json
  internal/catalog/catalogtest/integration_test_data/v2beta1/node-4.json
  internal/catalog/catalogtest/test_integration_v2beta1.go
  internal/catalog/catalogtest/test_lifecycle_v2beta1.go
  internal/catalog/internal/controllers/nodehealth/controller_test.go
  internal/catalog/internal/controllers/workloadhealth/controller_test.go
  internal/catalog/internal/mappers/nodemapper/node_mapper.go
  internal/catalog/internal/mappers/nodemapper/node_mapper_test.go
  internal/catalog/internal/types/health_status_test.go
  internal/catalog/internal/types/node.go
  proto-public/pbcatalog/v2beta1/node.pb.go
  proto-public/pbcatalog/v2beta1/node.proto
Labels: pr/no-changelog, pr/no-backport

#19797 Net 6585
  internal/mesh/internal/controllers/sidecarproxy/controller_test.go
Labels: pr/no-changelog, pr/no-backport, consul-india

#19811 skip TestCatalogUpgrade for consul versions < 1.18.0
  test/integration/consul-container/test/upgrade/catalog/catalog_test.go
Labels: pr/no-changelog, pr/no-backport

#19766 ci: fix test failure Slack notifications
  .github/workflows/go-tests.yml
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#19822 resource: block default namespace deletion + test refactorings
  agent/grpc-external/services/dataplane/get_envoy_bootstrap_params_test.go
  agent/grpc-external/services/resource/delete.go
  agent/grpc-external/services/resource/delete_ce.go
  agent/grpc-external/services/resource/delete_test.go
  agent/grpc-external/services/resource/list_by_owner_test.go
  agent/grpc-external/services/resource/list_test.go
  agent/grpc-external/services/resource/read_test.go
  agent/grpc-external/services/resource/server_ce_test.go
  agent/grpc-external/services/resource/server_test.go
  agent/grpc-external/services/resource/testing/builder.go
  agent/grpc-external/services/resource/testing/testing.go
  agent/grpc-external/services/resource/testing/testing_ce.go
  agent/grpc-external/services/resource/watch_test.go
  agent/grpc-external/services/resource/write.go
  agent/grpc-external/services/resource/write_status_test.go
  agent/grpc-external/services/resource/write_test.go
  internal/auth/internal/controllers/trafficpermissions/controller_test.go
  internal/catalog/catalogtest/run_test.go
  internal/catalog/internal/controllers/endpoints/controller_test.go
  internal/catalog/internal/controllers/endpoints/reconciliation_data_test.go
  internal/catalog/internal/controllers/failover/controller_test.go
  internal/catalog/internal/controllers/nodehealth/controller_test.go
  internal/catalog/internal/controllers/workloadhealth/controller_test.go
  internal/controller/api_test.go
  internal/mesh/internal/controllers/explicitdestinations/controller_test.go
  internal/mesh/internal/controllers/proxyconfiguration/controller_test.go
  internal/mesh/internal/controllers/proxyconfiguration/sort_test.go
  internal/mesh/internal/controllers/routes/controller_test.go
  internal/mesh/internal/controllers/routes/loader/loader_test.go
  internal/mesh/internal/controllers/sidecarproxy/cache/cache_test.go
  internal/mesh/internal/controllers/sidecarproxy/controller_test.go
  internal/mesh/internal/controllers/sidecarproxy/fetcher/data_fetcher_test.go
  internal/mesh/internal/controllers/xds/controller_test.go
  internal/mesh/internal/mappers/common/workload_selector_util_test.go
  internal/mesh/internal/mappers/workloadselectionmapper/workload_selection_mapper_test.go
  internal/multicluster/internal/controllers/exportedservices/controller_test.go
  internal/resource/decode_test.go
  internal/resource/demo/controller_test.go
  internal/resource/http/http_test.go
  internal/resource/reaper/controller_test.go
  internal/tenancy/tenancytest/namespace_controller_test.go
  internal/tenancy/tenancytest/namespace_test.go
Labels: pr/no-changelog, pr/no-backport

#19807 doc: clarify the portNames used in trafficpermission V2
  website/content/docs/k8s/multiport/reference/trafficpermissions.mdx
Labels: pr/no-changelog, backport/1.17

#18329 NET-3860 - [Supportability] consul troubleshoot CLI for verifying ports
  .changelog/18329.txt
  command/registry.go
  command/troubleshoot/ports/troubleshoot_ports.go
  troubleshoot/go.mod
  troubleshoot/go.sum
  troubleshoot/ports/hostport.go
  troubleshoot/ports/troubleshoot_ports.go
  troubleshoot/ports/troubleshoot_ports_test.go
  troubleshoot/ports/troubleshoot_protocol.go
  troubleshoot/ports/troubleshoot_tcp.go
  website/content/commands/troubleshoot/index.mdx
  website/content/commands/troubleshoot/ports.mdx
  website/data/commands-nav-data.json
Labels: theme/cli, backport/1.15, backport/1.16, consul-india

#19834 update l7expplicit dest test to test cross tenancy
  test-integ/catalogv2/explicit_destinations_l7_test.go
Labels: pr/no-changelog, pr/no-backport

#19836 NET-3860 - [Supportability] consul troubleshoot CLI for verifying ports
  .changelog/18329.txt
  command/registry.go
  command/troubleshoot/ports/troubleshoot_ports.go
  go.mod
  go.sum
  troubleshoot/go.mod
  troubleshoot/go.sum
  troubleshoot/ports/hostport.go
  troubleshoot/ports/troubleshoot_ports.go
  troubleshoot/ports/troubleshoot_ports_test.go
  troubleshoot/ports/troubleshoot_protocol.go
  troubleshoot/ports/troubleshoot_tcp.go
  website/content/commands/troubleshoot/index.mdx
  website/content/commands/troubleshoot/ports.mdx
  website/data/commands-nav-data.json
Labels: pr/no-backport, type/docs-cherrypick

#19827 [NET-6251] Nomad client templated policy
  .changelog/19827.txt
  agent/acl_endpoint_test.go
  agent/structs/acl_templated_policy.go
  agent/structs/acl_templated_policy_ce.go
  agent/structs/acltemplatedpolicy/policies/ce/nomad-client.hcl
  api/acl.go
  command/acl/templatedpolicy/formatter.go
  command/acl/templatedpolicy/formatter_test.go
  command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/nomad-client-templated-policy.json.golden
  command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/nomad-client-templated-policy.pretty-meta.golden
  command/acl/templatedpolicy/testdata/FormatTemplatedPolicy/ce/nomad-client-templated-policy.pretty.golden
Labels: theme/api, theme/cli, backport/1.17

#19707 Backport of cli: add a string method to gvk struct into release/1.17.x
  command/resource/helper.go
  command/resource/read/read_test.go
Labels: theme/cli

#19721 improve client RPC metrics consistency
  .changelog/19721.txt
  agent/consul/client.go
Labels: pr/no-metrics-test, backport/1.15, backport/1.16, backport/1.17

#19840 [NET-6650] Bump go version to 1.20.12
  .changelog/19840.txt
  .github/workflows/build.yml
  build-support/docker/Build-Go.dockerfile
Labels: backport/1.15, backport/1.16, backport/1.17

#19818 Manual Backport of [Cloud][CC-6925] Updates to pushing server state into release/1.16.x
  .changelog/19682.txt
  agent/consul/server.go
  agent/consul/server_test.go
  agent/grpc-middleware/testutil/testservice/simple.pb.go
  agent/hcp/client/client.go
  agent/hcp/client/mock_CloudConfig.go
  agent/hcp/testing.go
  go.mod
  go.sum
  internal/go-sso/oidcauth/oidc_test.go
  proto-public/annotations/ratelimit/ratelimit.pb.go
  proto-public/pbacl/acl.pb.go
  proto-public/pbcatalog/v1alpha1/dns.pb.go
  proto-public/pbcatalog/v1alpha1/health.pb.go
  proto-public/pbcatalog/v1alpha1/node.pb.go
  proto-public/pbcatalog/v1alpha1/protocol.pb.go
  proto-public/pbcatalog/v1alpha1/selector.pb.go
  proto-public/pbcatalog/v1alpha1/service.pb.go
  proto-public/pbcatalog/v1alpha1/service_endpoints.pb.go
  proto-public/pbcatalog/v1alpha1/vip.pb.go
  proto-public/pbcatalog/v1alpha1/workload.pb.go
  proto-public/pbconnectca/ca.pb.go
  proto-public/pbdataplane/dataplane.pb.go
  proto-public/pbdns/dns.pb.go
  proto-public/pbmesh/v1alpha1/connection.pb.go
  proto-public/pbmesh/v1alpha1/expose.pb.go
  proto-public/pbmesh/v1alpha1/proxy.pb.go
  proto-public/pbmesh/v1alpha1/routing.pb.go
  proto-public/pbmesh/v1alpha1/upstreams.pb.go
  proto-public/pbresource/resource.pb.go
  proto-public/pbserverdiscovery/serverdiscovery.pb.go
  proto/private/pbacl/acl.pb.go
  proto/private/pbautoconf/auto_config.pb.go
  proto/private/pbcommon/common.pb.go
  proto/private/pbconfig/config.pb.go
  proto/private/pbconfigentry/config_entry.pb.go
  proto/private/pbconnect/connect.pb.go
  proto/private/pbdemo/v1/demo.pb.go
  proto/private/pbdemo/v2/demo.pb.go
  proto/private/pboperator/operator.pb.go
  proto/private/pbpeering/peering.pb.go
  proto/private/pbpeerstream/peerstream.pb.go
  proto/private/pbservice/healthcheck.pb.go
  proto/private/pbservice/node.pb.go
  proto/private/pbservice/service.pb.go
  proto/private/pbstatus/status.pb.go
  proto/private/pbstorage/raft.pb.go
  proto/private/pbsubscribe/subscribe.pb.go
  test/key/ourdomain_with_intermediate.cer
  tlsutil/config.go
  tlsutil/mock.go
Labels: pr/dependencies, pr/no-backport

#19847 NET-6643: upgrade test from 1.10 to 1.15 (lts) of a single cluster
  test-integ/upgrade/usage_profiles/sd_wan_segments_test.go
  testing/deployer/go.mod
  testing/deployer/sprawl/acl.go
  testing/deployer/sprawl/boot.go
  testing/deployer/sprawl/internal/tfgen/agent.go
  testing/deployer/sprawl/sprawl.go
  testing/deployer/topology/images.go
Labels: pr/no-changelog, pr/no-backport

#19846 Backport of [NET-6650] Bump go version to 1.20.12 into release/1.17.x
  .changelog/19840.txt
  .github/workflows/build.yml
  build-support/docker/Build-Go.dockerfile
Labels: type/ci, theme/contributing

#19703 Backport of Default "stats_flush_interval" to 1 minute for Consul Telemetry Collector into release/1.17.x
  .changelog/19663.txt
  command/connect/envoy/bootstrap_config.go
  command/connect/envoy/bootstrap_config_test.go
  command/connect/envoy/testdata/telemetry-collector.golden
  website/content/docs/connect/proxies/envoy.mdx
Labels: type/docs, theme/cli

#19849 Backport stats flush interval 1.16.x
  .changelog/19663.txt
  .github/workflows/pr-labeler.yml
  command/connect/envoy/bootstrap_config.go
  command/connect/envoy/bootstrap_config_test.go
  command/connect/envoy/testdata/telemetry-collector.golden
  website/content/docs/connect/proxies/envoy.mdx
Labels: pr/no-changelog, pr/no-backport

#19821 NET-6784: Adding cli command to list exported services to a peer
  .changelog/19821.txt
  command/peering/exportedservices/exported_services.go
  command/peering/exportedservices/exported_services_test.go
  command/peering/peering.go
  command/registry.go
  website/content/commands/peering/exported-services.mdx
  website/content/commands/peering/index.mdx
  website/data/commands-nav-data.json
Labels: type/docs, theme/cli, consul-india, backport/1.17

#19851 Backport of NET-6784: Adding cli command to list exported services to a peer into release/1.17.x
  .changelog/19821.txt
  command/peering/exportedservices/exported_services.go
  command/peering/exportedservices/exported_services_test.go
  command/peering/peering.go
  command/registry.go
  website/content/commands/peering/exported-services.mdx
  website/content/commands/peering/index.mdx
  website/data/commands-nav-data.json
Labels: type/docs, theme/cli

#19844 Backport of [NET-6650] Bump go version to 1.20.12 into release/1.15.x
  .changelog/19840.txt
  .github/workflows/build.yml
  build-support/docker/Build-Go.dockerfile
Labels: pr/no-backport

#19853 chore: update version and changelog post-1.16.3
  CHANGELOG.md
  version/VERSION
Labels: pr/no-changelog, pr/no-backport

#19855 chore: update changelog for patch releases
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-backport

#19852 Ensure that the default namespace always exists even prior to resource creation
  internal/tenancy/internal/bridge/tenancy_bridge.go
  internal/tenancy/internal/bridge/tenancy_bridge_ce.go
Labels: pr/no-changelog, pr/no-backport

#19829 parse config protocol on write to optimize disco-chain compilation
  .changelog/19829.txt
  agent/consul/discoverychain/compile.go
  agent/consul/discoverychain/compile_test.go
  agent/consul/discoverychain/gateway_test.go
  agent/consul/state/config_entry.go
  agent/consul/state/config_entry_test.go
  agent/proxycfg/manager_test.go
  agent/proxycfg/testing_mesh_gateway.go
  agent/proxycfg/testing_tproxy.go
  agent/proxycfg/testing_upstreams.go
  agent/structs/config_entry.go
  agent/structs/discovery_chain.go
  agent/xds/resources_test.go
Labels: theme/envoy/xds, backport/1.15, backport/1.16, backport/1.17

#19845 Backport of [NET-6650] Bump go version to 1.20.12 into release/1.16.x
  .changelog/19840.txt
  .github/workflows/build.yml
  build-support/docker/Build-Go.dockerfile
Labels: type/ci, pr/dependencies

#19860 Add CE version of Gateway Upstream Disambiguation
  .changelog/19860.txt
  agent/consul/discoverychain/gateway.go
  agent/consul/discoverychain/gateway_test.go
  agent/xds/routes.go
Labels: theme/envoy/xds, backport/1.15, backport/1.16, backport/1.17

#19864 Fix a test flake where a retry timer was being reused causing tests after the first to exit early
  test/integration/consul-container/test/gateways/terminating_gateway_test.go
Labels: pr/no-changelog, backport/1.17

#19861 upgrade test(LTS): add segments to version 1.10
  test-integ/upgrade/usage_profiles/sd_wan_segments_test.go
  testing/deployer/sprawl/acl.go
  testing/deployer/sprawl/boot.go
  testing/deployer/sprawl/details.go
  testing/deployer/sprawl/internal/tfgen/agent.go
  testing/deployer/topology/topology.go
Labels: pr/no-changelog, pr/no-backport

#19791 Backport of Remove Duplicate UBI Tags into release/1.17.x
  .github/workflows/build.yml
Labels: type/ci, theme/contributing

#19874 Backport of Fix xDS missing endpoint race condition. into release/1.17.x
  .changelog/19866.txt
  agent/xds/delta.go
  agent/xds/delta_test.go
Labels: theme/envoy/xds

#19880 added redirect for conf entries 1.8.x (#19460)
  website/redirects.js
Labels: type/docs, pr/no-changelog, pr/no-backport

#19876 ci: sanitize commit message for Slack failure alerts
  .github/workflows/go-tests.yml
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#19879 security: update supported envoy version 1.28.0 in addition to 1.25.11, 1.26.6, 1.27.2, 1.28.0 to address CVE-2023-44487
  .changelog/19879.txt
  envoyextensions/xdscommon/envoy_versioning_test.go
  envoyextensions/xdscommon/proxysupport.go
  website/content/docs/connect/proxies/envoy.mdx
Labels: type/docs, pr/no-backport

#19871 Fix ClusterLoadAssignment timeouts dropping endpoints.
  .changelog/19871.txt
  agent/proxycfg/proxycfg.deepcopy.go
  agent/proxycfg/snapshot.go
  agent/proxycfg/snapshot_test.go
  agent/proxycfg/testing_peering.go
  agent/proxycfg/testing_terminating_gateway.go
  agent/proxycfg/testing_tproxy.go
  agent/xds/clusters.go
  agent/xds/config/config.go
  agent/xds/config/config_test.go
  agent/xds/delta_envoy_extender_ce_test.go
  agent/xds/listeners.go
  agent/xds/listeners_apigateway.go
  agent/xds/listeners_ingress.go
  agent/xds/resources_test.go
  agent/xds/testdata/clusters/xds-fetch-timeout-ms-ingress-with-router.latest.golden
  agent/xds/testdata/clusters/xds-fetch-timeout-ms-mgw-peering.latest.golden
  agent/xds/testdata/clusters/xds-fetch-timeout-ms-sidecar.latest.golden
  agent/xds/testdata/clusters/xds-fetch-timeout-ms-term-gw.latest.golden
  agent/xds/testdata/clusters/xds-fetch-timeout-ms-tproxy-http-peering.latest.golden
  agent/xds/testdata/clusters/xds-fetch-timeout-ms-tproxy-passthrough.latest.golden
  agent/xds/testdata/endpoints/xds-fetch-timeout-ms-ingress-with-router.latest.golden
  agent/xds/testdata/endpoints/xds-fetch-timeout-ms-mgw-peering.latest.golden
  agent/xds/testdata/endpoints/xds-fetch-timeout-ms-sidecar.latest.golden
  agent/xds/testdata/endpoints/xds-fetch-timeout-ms-term-gw.latest.golden
  agent/xds/testdata/endpoints/xds-fetch-timeout-ms-tproxy-http-peering.latest.golden
  agent/xds/testdata/endpoints/xds-fetch-timeout-ms-tproxy-passthrough.latest.golden
  agent/xds/testdata/listeners/xds-fetch-timeout-ms-ingress-with-router.latest.golden
  agent/xds/testdata/listeners/xds-fetch-timeout-ms-mgw-peering.latest.golden
  agent/xds/testdata/listeners/xds-fetch-timeout-ms-sidecar.latest.golden
  agent/xds/testdata/listeners/xds-fetch-timeout-ms-term-gw.latest.golden
  agent/xds/testdata/listeners/xds-fetch-timeout-ms-tproxy-http-peering.latest.golden
  agent/xds/testdata/listeners/xds-fetch-timeout-ms-tproxy-passthrough.latest.golden
  agent/xds/testdata/routes/xds-fetch-timeout-ms-ingress-with-router.latest.golden
  agent/xds/testdata/routes/xds-fetch-timeout-ms-mgw-peering.latest.golden
  agent/xds/testdata/routes/xds-fetch-timeout-ms-sidecar.latest.golden
  agent/xds/testdata/routes/xds-fetch-timeout-ms-term-gw.latest.golden
  agent/xds/testdata/routes/xds-fetch-timeout-ms-tproxy-http-peering.latest.golden
  agent/xds/testdata/routes/xds-fetch-timeout-ms-tproxy-passthrough.latest.golden
  agent/xds/testdata/secrets/xds-fetch-timeout-ms-ingress-with-router.latest.golden
  agent/xds/testdata/secrets/xds-fetch-timeout-ms-mgw-peering.latest.golden
  agent/xds/testdata/secrets/xds-fetch-timeout-ms-sidecar.latest.golden
  agent/xds/testdata/secrets/xds-fetch-timeout-ms-term-gw.latest.golden
  agent/xds/testdata/secrets/xds-fetch-timeout-ms-tproxy-http-peering.latest.golden
  agent/xds/testdata/secrets/xds-fetch-timeout-ms-tproxy-passthrough.latest.golden
  agent/xds/validateupstream-test/validateupstream_test.go
Labels: theme/envoy/xds, pr/no-backport

#19884 Backport of: Fix ClusterLoadAssignment timeouts dropping endpoints. into 1.17
  .changelog/19871.txt
  agent/proxycfg/proxycfg.deepcopy.go
  agent/proxycfg/snapshot.go
  agent/proxycfg/snapshot_test.go
  agent/proxycfg/testing_peering.go
  agent/proxycfg/testing_terminating_gateway.go
  agent/proxycfg/testing_tproxy.go
  agent/xds/clusters.go
  agent/xds/clusters_test.go
  agent/xds/config/config.go
  agent/xds/config/config_test.go
  agent/xds/delta_envoy_extender_ce_test.go
  agent/xds/listeners.go
  agent/xds/listeners_apigateway.go
  agent/xds/listeners_ingress.go
  agent/xds/listeners_test.go
  agent/xds/resources_test.go
  agent/xds/testdata/clusters/xds-fetch-timeout-ms-ingress-with-router.latest.golden
  agent/xds/testdata/clusters/xds-fetch-timeout-ms-mgw-peering.latest.golden
  agent/xds/testdata/clusters/xds-fetch-timeout-ms-sidecar.latest.golden
  agent/xds/testdata/clusters/xds-fetch-timeout-ms-term-gw.latest.golden
  agent/xds/testdata/clusters/xds-fetch-timeout-ms-tproxy-http-peering.latest.golden
  agent/xds/testdata/clusters/xds-fetch-timeout-ms-tproxy-passthrough.latest.golden
  agent/xds/testdata/endpoints/xds-fetch-timeout-ms-ingress-with-router.latest.golden
  agent/xds/testdata/endpoints/xds-fetch-timeout-ms-mgw-peering.latest.golden
  agent/xds/testdata/endpoints/xds-fetch-timeout-ms-sidecar.latest.golden
  agent/xds/testdata/endpoints/xds-fetch-timeout-ms-term-gw.latest.golden
  agent/xds/testdata/endpoints/xds-fetch-timeout-ms-tproxy-http-peering.latest.golden
  agent/xds/testdata/endpoints/xds-fetch-timeout-ms-tproxy-passthrough.latest.golden
  agent/xds/testdata/listeners/xds-fetch-timeout-ms-ingress-with-router.latest.golden
  agent/xds/testdata/listeners/xds-fetch-timeout-ms-mgw-peering.latest.golden
  agent/xds/testdata/listeners/xds-fetch-timeout-ms-sidecar.latest.golden
  agent/xds/testdata/listeners/xds-fetch-timeout-ms-term-gw.latest.golden
  agent/xds/testdata/listeners/xds-fetch-timeout-ms-tproxy-http-peering.latest.golden
  agent/xds/testdata/listeners/xds-fetch-timeout-ms-tproxy-passthrough.latest.golden
  agent/xds/testdata/routes/xds-fetch-timeout-ms-ingress-with-router.latest.golden
  agent/xds/testdata/routes/xds-fetch-timeout-ms-mgw-peering.latest.golden
  agent/xds/testdata/routes/xds-fetch-timeout-ms-sidecar.latest.golden
  agent/xds/testdata/routes/xds-fetch-timeout-ms-term-gw.latest.golden
  agent/xds/testdata/routes/xds-fetch-timeout-ms-tproxy-http-peering.latest.golden
  agent/xds/testdata/routes/xds-fetch-timeout-ms-tproxy-passthrough.latest.golden
  agent/xds/testdata/secrets/xds-fetch-timeout-ms-ingress-with-router.latest.golden
  agent/xds/testdata/secrets/xds-fetch-timeout-ms-mgw-peering.latest.golden
  agent/xds/testdata/secrets/xds-fetch-timeout-ms-sidecar.latest.golden
  agent/xds/testdata/secrets/xds-fetch-timeout-ms-term-gw.latest.golden
  agent/xds/testdata/secrets/xds-fetch-timeout-ms-tproxy-http-peering.latest.golden
  agent/xds/testdata/secrets/xds-fetch-timeout-ms-tproxy-passthrough.latest.golden
  agent/xds/validateupstream-test/validateupstream_test.go
Labels: theme/envoy/xds, pr/no-backport

#19887 [NET-6842] splitting go version on different lines
  .github/workflows/build.yml
Labels: type/ci, theme/contributing, pr/no-changelog, backport/1.15, backport/1.16, backport/1.17

#19885 Backport of: Fix ClusterLoadAssignment timeouts dropping endpoints. into 1.16
  .changelog/19871.txt
  agent/proxycfg/proxycfg.deepcopy.go
  agent/proxycfg/snapshot.go
  agent/proxycfg/snapshot_test.go
  agent/proxycfg/testing_peering.go
  agent/proxycfg/testing_terminating_gateway.go
  agent/proxycfg/testing_tproxy.go
  agent/xds/clusters.go
  agent/xds/clusters_test.go
  agent/xds/config/config.go
  agent/xds/config/config_test.go
  agent/xds/delta_envoy_extender_ce_test.go
  agent/xds/listeners.go
  agent/xds/listeners_apigateway.go
  agent/xds/listeners_ingress.go
  agent/xds/listeners_test.go
  agent/xds/resources_test.go
  agent/xds/routes.go
  agent/xds/testdata/clusters/xds-fetch-timeout-ms-ingress-with-router.latest.golden
  agent/xds/testdata/clusters/xds-fetch-timeout-ms-mgw-peering.latest.golden
  agent/xds/testdata/clusters/xds-fetch-timeout-ms-sidecar.latest.golden
  agent/xds/testdata/clusters/xds-fetch-timeout-ms-term-gw.latest.golden
  agent/xds/testdata/clusters/xds-fetch-timeout-ms-tproxy-passthrough.latest.golden
  agent/xds/testdata/endpoints/xds-fetch-timeout-ms-ingress-with-router.latest.golden
  agent/xds/testdata/endpoints/xds-fetch-timeout-ms-mgw-peering.latest.golden
  agent/xds/testdata/endpoints/xds-fetch-timeout-ms-sidecar.latest.golden
  agent/xds/testdata/endpoints/xds-fetch-timeout-ms-term-gw.latest.golden
  agent/xds/testdata/endpoints/xds-fetch-timeout-ms-tproxy-passthrough.latest.golden
  agent/xds/testdata/listeners/xds-fetch-timeout-ms-ingress-with-router.latest.golden
  agent/xds/testdata/listeners/xds-fetch-timeout-ms-mgw-peering.latest.golden
  agent/xds/testdata/listeners/xds-fetch-timeout-ms-sidecar.latest.golden
  agent/xds/testdata/listeners/xds-fetch-timeout-ms-term-gw.latest.golden
  agent/xds/testdata/listeners/xds-fetch-timeout-ms-tproxy-passthrough.latest.golden
  agent/xds/testdata/routes/xds-fetch-timeout-ms-ingress-with-router.latest.golden
  agent/xds/testdata/routes/xds-fetch-timeout-ms-mgw-peering.latest.golden
  agent/xds/testdata/routes/xds-fetch-timeout-ms-sidecar.latest.golden
  agent/xds/testdata/routes/xds-fetch-timeout-ms-term-gw.latest.golden
  agent/xds/testdata/routes/xds-fetch-timeout-ms-tproxy-passthrough.latest.golden
  agent/xds/testdata/secrets/xds-fetch-timeout-ms-ingress-with-router.latest.golden
  agent/xds/testdata/secrets/xds-fetch-timeout-ms-mgw-peering.latest.golden
  agent/xds/testdata/secrets/xds-fetch-timeout-ms-sidecar.latest.golden
  agent/xds/testdata/secrets/xds-fetch-timeout-ms-term-gw.latest.golden
  agent/xds/testdata/secrets/xds-fetch-timeout-ms-tproxy-passthrough.latest.golden
  agent/xds/validateupstream-test/validateupstream_test.go
Labels: theme/envoy/xds, pr/no-backport

#19890 Backport of [NET-6842] splitting go version on different lines into release/1.16.x
  .github/workflows/build.yml
Labels: type/ci, theme/contributing

#19891 Backport of [NET-6842] splitting go version on different lines into release/1.17.x
  .github/workflows/build.yml
Labels: type/ci, theme/contributing

#19886 Backport of: Fix ClusterLoadAssignment timeouts dropping endpoints. into 1.15
  .changelog/19871.txt
  agent/proxycfg/proxycfg.deepcopy.go
  agent/proxycfg/snapshot.go
  agent/proxycfg/snapshot_test.go
  agent/proxycfg/testing_peering.go
  agent/proxycfg/testing_terminating_gateway.go
  agent/proxycfg/testing_tproxy.go
  agent/xds/clusters.go
  agent/xds/clusters_test.go
  agent/xds/config/config.go
  agent/xds/config/config_test.go
  agent/xds/delta_envoy_extender_ce_test.go
  agent/xds/listeners.go
  agent/xds/listeners_ingress.go
  agent/xds/listeners_test.go
  agent/xds/resources_test.go
  agent/xds/routes.go
  agent/xds/testdata/clusters/xds-fetch-timeout-ms-ingress-with-router.latest.golden
  agent/xds/testdata/clusters/xds-fetch-timeout-ms-mgw-peering.latest.golden
  agent/xds/testdata/clusters/xds-fetch-timeout-ms-sidecar.latest.golden
  agent/xds/testdata/clusters/xds-fetch-timeout-ms-term-gw.latest.golden
  agent/xds/testdata/clusters/xds-fetch-timeout-ms-tproxy-passthrough.latest.golden
  agent/xds/testdata/endpoints/xds-fetch-timeout-ms-ingress-with-router.latest.golden
  agent/xds/testdata/endpoints/xds-fetch-timeout-ms-mgw-peering.latest.golden
  agent/xds/testdata/endpoints/xds-fetch-timeout-ms-sidecar.latest.golden
  agent/xds/testdata/endpoints/xds-fetch-timeout-ms-term-gw.latest.golden
  agent/xds/testdata/endpoints/xds-fetch-timeout-ms-tproxy-passthrough.latest.golden
  agent/xds/testdata/listeners/xds-fetch-timeout-ms-ingress-with-router.latest.golden
  agent/xds/testdata/listeners/xds-fetch-timeout-ms-mgw-peering.latest.golden
  agent/xds/testdata/listeners/xds-fetch-timeout-ms-sidecar.latest.golden
  agent/xds/testdata/listeners/xds-fetch-timeout-ms-term-gw.latest.golden
  agent/xds/testdata/listeners/xds-fetch-timeout-ms-tproxy-passthrough.latest.golden
  agent/xds/testdata/routes/xds-fetch-timeout-ms-ingress-with-router.latest.golden
  agent/xds/testdata/routes/xds-fetch-timeout-ms-mgw-peering.latest.golden
  agent/xds/testdata/routes/xds-fetch-timeout-ms-sidecar.latest.golden
  agent/xds/testdata/routes/xds-fetch-timeout-ms-term-gw.latest.golden
  agent/xds/testdata/routes/xds-fetch-timeout-ms-tproxy-passthrough.latest.golden
  agent/xds/testdata/secrets/xds-fetch-timeout-ms-ingress-with-router.latest.golden
  agent/xds/testdata/secrets/xds-fetch-timeout-ms-mgw-peering.latest.golden
  agent/xds/testdata/secrets/xds-fetch-timeout-ms-sidecar.latest.golden
  agent/xds/testdata/secrets/xds-fetch-timeout-ms-term-gw.latest.golden
  agent/xds/testdata/secrets/xds-fetch-timeout-ms-tproxy-passthrough.latest.golden
  agent/xds/validateupstream-test/validateupstream_test.go
Labels: pr/no-backport

#19893 Add documentation for proxy-config-map and xds_fetch_timeout_ms.
  website/content/docs/connect/proxies/envoy.mdx
  website/content/docs/k8s/annotations-and-labels.mdx
Labels: type/docs, pr/no-changelog, backport/1.15, backport/1.16, backport/1.17

#19895 Backport of Add documentation for proxy-config-map and xds_fetch_timeout_ms. into release/1.16.x
  website/content/docs/connect/proxies/envoy.mdx
  website/content/docs/k8s/annotations-and-labels.mdx
Labels: type/docs

#19896 Backport of Add documentation for proxy-config-map and xds_fetch_timeout_ms. into release/1.17.x
  website/content/docs/connect/proxies/envoy.mdx
  website/content/docs/k8s/annotations-and-labels.mdx
Labels: type/docs

#19897 Remove warning for consul 1.17 deprecation
  agent/http.go
  website/content/api-docs/api-structure.mdx
  website/content/docs/upgrading/upgrade-specific.mdx
Labels: pr/no-changelog, backport/1.15, backport/1.16, backport/1.17

#19908 fix: remove test to unblock CI
  ui/packages/consul-ui/tests/acceptance/dc/services/show/topology/metrics.feature
Labels: theme/ui, pr/no-changelog, backport/1.15, backport/1.16, backport/1.17

#19911 Backport of fix: remove test to unblock CI into release/1.17.x
  ui/packages/consul-ui/tests/acceptance/dc/services/show/topology/metrics.feature
Labels: theme/ui

#19910 Backport of fix: remove test to unblock CI into release/1.16.x
  ui/packages/consul-ui/tests/acceptance/dc/services/show/topology/metrics.feature
Labels: theme/ui

#19837 NET 6761
  test-integ/catalogv2/explicit_destinations_test.go
Labels: pr/no-changelog, pr/no-backport

#19883 NET-6771 - Adding sameness group protobuff in consul CE
  internal/multicluster/exports.go
  internal/multicluster/internal/types/decoded.go
  internal/multicluster/internal/types/types_ce.go
  proto-public/pbmulticluster/v2beta1/resource_types.gen.go
  proto-public/pbmulticluster/v2beta1/sameness_group.pb.binary.go
  proto-public/pbmulticluster/v2beta1/sameness_group.pb.go
  proto-public/pbmulticluster/v2beta1/sameness_group.proto
  proto-public/pbmulticluster/v2beta1/sameness_group_deepcopy.gen.go
  proto-public/pbmulticluster/v2beta1/sameness_group_json.gen.go
Labels: pr/no-changelog, pr/no-backport

#19913 Move enterprise multicluster types to Register function
  internal/multicluster/exports.go
  internal/multicluster/internal/controllers/exportedservices/controller_test.go
  internal/multicluster/internal/types/types.go
  internal/multicluster/internal/types/types_ce.go
Labels: pr/no-changelog, pr/no-backport, consul-india

#19795 Hash based config entry replication
  .changelog/19795.txt
  agent/config/runtime_test.go
  agent/configentry/compare.go
  agent/consul/config_replication.go
  agent/consul/config_replication_test.go
  agent/consul/fsm/snapshot_test.go
  agent/consul/state/config_entry.go
  agent/consul/state/intention_test.go
  agent/structs/config_entry.go
  agent/structs/config_entry_discoverychain.go
  agent/structs/config_entry_exports.go
  agent/structs/config_entry_gateways.go
  agent/structs/config_entry_inline_certificate.go
  agent/structs/config_entry_intentions.go
  agent/structs/config_entry_jwt_provider.go
  agent/structs/config_entry_mesh.go
  agent/structs/config_entry_routes.go
  agent/structs/config_entry_sameness_group.go
  agent/structs/config_entry_test.go
  proto/private/pbconfigentry/config_entry.gen.go
  proto/private/pbconfigentry/config_entry.pb.go
  proto/private/pbconfigentry/config_entry.proto
Labels: backport/1.15, backport/1.16, backport/1.17

#19907 NET-6900: stop reconciling services when peering is enabled
  .changelog/19907.txt
  ui/packages/consul-ui/app/services/repository.js
Labels: theme/ui, backport/1.17

#19917 Backport of NET-6900: stop reconciling services when peering is enabled into release/1.17.x
  .changelog/19907.txt
  ui/packages/consul-ui/app/services/repository.js
Labels: theme/ui

#19905 Backport of Remove warning for consul 1.17 deprecation into release/1.17.x
  agent/http.go
  website/content/api-docs/api-structure.mdx
  website/content/docs/upgrading/upgrade-specific.mdx
Labels: type/docs

#19912 fix: token list in Role details page is updated with tokens linked to…
  .changelog/19912.txt
  ui/packages/consul-ui/app/templates/dc/acls/roles/-form.hbs
Labels: theme/ui, backport/1.15, backport/1.16, backport/1.17

#19918 fix actions to no longer use envoy 1.24.x to match supported versions.
  .github/workflows/nightly-test-integrations.yml
  .github/workflows/test-integrations-windows.yml
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#19921 Backport of fix: token list in Role details page is updated with tokens linked to… into release/1.15.x
  .changelog/19912.txt
  ui/packages/consul-ui/app/templates/dc/acls/roles/-form.hbs
Labels: theme/ui, pr/no-backport

#19923 Backport of fix: token list in Role details page is updated with tokens linked to… into release/1.17.x
  .changelog/19912.txt
  ui/packages/consul-ui/app/templates/dc/acls/roles/-form.hbs
Labels: theme/ui, pr/no-backport

#19922 Backport of fix: token list in Role details page is updated with tokens linked to… into release/1.16.x
  .changelog/19912.txt
  ui/packages/consul-ui/app/templates/dc/acls/roles/-form.hbs
Labels: theme/ui, pr/no-backport

#19920 resource: add partition resource to proto-public to keep ENT and CE in sync
  proto-public/pbtenancy/v2beta1/partition.pb.binary.go
  proto-public/pbtenancy/v2beta1/partition.pb.go
  proto-public/pbtenancy/v2beta1/partition.proto
  proto-public/pbtenancy/v2beta1/partition_deepcopy.gen.go
  proto-public/pbtenancy/v2beta1/partition_json.gen.go
  proto-public/pbtenancy/v2beta1/resource_types.gen.go
Labels: pr/no-changelog, pr/no-backport

#19931 NET 6762
  test-integ/catalogv2/implicit_destinations_test.go
Labels: pr/no-changelog, pr/no-backport, consul-india

#19934 Upgrade test(LTS): use network area to federate cluster
  testing/deployer/sprawl/acl.go
  testing/deployer/sprawl/boot.go
  testing/deployer/sprawl/internal/tfgen/agent.go
  testing/deployer/sprawl/network_area_ce.go
  testing/deployer/topology/compile.go
  testing/deployer/topology/topology.go
Labels: pr/no-changelog, pr/no-backport

#19932 added tenancy to TestBuildL4TrafficPermissions
  agent/connect/uri_workload_identity.go
  agent/connect/uri_workload_identity_ce.go
  agent/connect/uri_workload_identity_ce_test.go
  agent/connect/uri_workload_identity_test.go
  internal/mesh/internal/controllers/sidecarproxy/builder/local_app_test.go
Labels: pr/no-changelog, pr/no-backport

#19929 NET-6785: updating peering docs to include stream status and remote data
  website/content/api-docs/peering.mdx
Labels: type/docs, pr/no-changelog, backport/1.15, backport/1.16, backport/1.17

#19937 Backport of NET-6785: updating peering docs to include stream status and remote data into release/1.16.x
  website/content/api-docs/peering.mdx
Labels: type/docs

#19938 Backport of NET-6785: updating peering docs to include stream status and remote data into release/1.17.x
  website/content/api-docs/peering.mdx
Labels: type/docs

#19936 Backport of NET-6785: updating peering docs to include stream status and remote data into release/1.15.x
  website/content/api-docs/peering.mdx
Labels: type/docs

#19593 Update telemetry.mdx RPC Metrics
  website/content/docs/agent/telemetry.mdx
Labels: type/docs, theme/telemetry, pr/no-changelog, pr/no-metrics-test, backport/1.12, backport/1.13, backport/1.14, backport/1.15, backport/1.16, backport/1.17

#19949 Backport of Update telemetry.mdx RPC Metrics into release/1.17.x
  website/content/docs/agent/telemetry.mdx
Labels: type/docs

#19948 Backport of Update telemetry.mdx RPC Metrics into release/1.16.x
  website/content/docs/agent/telemetry.mdx
Labels: type/docs

#19940 NET-6317 - update usage of deprecated fields: http2_protocol_options and access_log_path
  .changelog/19940.txt
  command/connect/envoy/bootstrap_config.go
  command/connect/envoy/bootstrap_config_test.go
  command/connect/envoy/bootstrap_tpl.go
  command/connect/envoy/envoy_test.go
  command/connect/envoy/testdata/CONSUL_GRPC_ADDR-with-https-scheme-enables-tls.golden
  command/connect/envoy/testdata/CONSUL_HTTP_ADDR-with-https-scheme-does-not-affect-grpc-tls.golden
  command/connect/envoy/testdata/access-log-path.golden
  command/connect/envoy/testdata/access-logs-enabled-custom.golden
  command/connect/envoy/testdata/access-logs-enabled.golden
  command/connect/envoy/testdata/acl-enabled-and-token.golden
  command/connect/envoy/testdata/acl-enabled-but-no-token.golden
  command/connect/envoy/testdata/both-CONSUL_HTTP_ADDR-PLAIN-and-CONSUL_GRPC_ADDR-TLS-is-tls.golden
  command/connect/envoy/testdata/both-CONSUL_HTTP_ADDR-TLS-and-CONSUL_GRPC_ADDR-PLAIN-is-plain.golden
  command/connect/envoy/testdata/custom-bootstrap.golden
  command/connect/envoy/testdata/defaults-nodemeta.golden
  command/connect/envoy/testdata/defaults.golden
  command/connect/envoy/testdata/deprecated-grpc-addr-config.golden
  command/connect/envoy/testdata/envoy-readiness-probe.golden
  command/connect/envoy/testdata/existing-ca-file.golden
  command/connect/envoy/testdata/existing-ca-path.golden
  command/connect/envoy/testdata/extra_-multiple.golden
  command/connect/envoy/testdata/extra_-single.golden
  command/connect/envoy/testdata/grpc-addr-env.golden
  command/connect/envoy/testdata/grpc-addr-flag.golden
  command/connect/envoy/testdata/grpc-addr-unix-with-tls.golden
  command/connect/envoy/testdata/grpc-addr-unix.golden
  command/connect/envoy/testdata/grpc-tls-addr-config.golden
  command/connect/envoy/testdata/ingress-gateway-address-specified.golden
  command/connect/envoy/testdata/ingress-gateway-no-auto-register.golden
  command/connect/envoy/testdata/ingress-gateway-nodemeta.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-and-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-without-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway.golden
  command/connect/envoy/testdata/prometheus-metrics-tls-ca-file.golden
  command/connect/envoy/testdata/prometheus-metrics-tls-ca-path.golden
  command/connect/envoy/testdata/prometheus-metrics.golden
  command/connect/envoy/testdata/stats-config-override.golden
  command/connect/envoy/testdata/telemetry-collector.golden
  command/connect/envoy/testdata/token-arg.golden
  command/connect/envoy/testdata/token-env.golden
  command/connect/envoy/testdata/token-file-arg.golden
  command/connect/envoy/testdata/token-file-env.golden
  command/connect/envoy/testdata/xds-addr-config.golden
  command/connect/envoy/testdata/zipkin-tracing-config.golden
  test/integration/connect/envoy/case-ingress-gateway-sds/service_gateway.hcl
  test/integration/consul-container/test/upgrade/ingress_gateway_sds_test.go
  troubleshoot/proxy/testdata/config.json
  website/content/docs/connect/gateways/ingress-gateway/tls-external-service.mdx
  website/content/docs/connect/proxies/envoy.mdx
Labels: type/docs, theme/cli, backport/1.15, backport/1.16, backport/1.17

#19943 cli: Deprecate the `-admin-access-log-path` flag from `consul connect envoy` command in favor of: `-admin-access-log-config`.
  .changelog/19943.txt
  CHANGELOG.md
  website/content/docs/release-notes/consul/v1_17_x.mdx
Labels: backport/1.17

#19955 Backport of cli: Deprecate the `-admin-access-log-path` flag from `consul connect envoy` command in favor of: `-admin-access-log-config`. into release/1.17.x
  .changelog/19943.txt
  CHANGELOG.md
  website/content/docs/release-notes/consul/v1_17_x.mdx
Labels: type/docs

#19953 Backport of NET-6317 - update usage of deprecated fields: http2_protocol_options and access_log_path into release/1.17.x
  .changelog/19940.txt
  command/connect/envoy/bootstrap_config.go
  command/connect/envoy/bootstrap_config_test.go
  command/connect/envoy/bootstrap_tpl.go
  command/connect/envoy/envoy_test.go
  command/connect/envoy/testdata/CONSUL_GRPC_ADDR-with-https-scheme-enables-tls.golden
  command/connect/envoy/testdata/CONSUL_HTTP_ADDR-with-https-scheme-does-not-affect-grpc-tls.golden
  command/connect/envoy/testdata/access-log-path.golden
  command/connect/envoy/testdata/access-logs-enabled-custom.golden
  command/connect/envoy/testdata/access-logs-enabled.golden
  command/connect/envoy/testdata/acl-enabled-and-token.golden
  command/connect/envoy/testdata/acl-enabled-but-no-token.golden
  command/connect/envoy/testdata/both-CONSUL_HTTP_ADDR-PLAIN-and-CONSUL_GRPC_ADDR-TLS-is-tls.golden
  command/connect/envoy/testdata/both-CONSUL_HTTP_ADDR-TLS-and-CONSUL_GRPC_ADDR-PLAIN-is-plain.golden
  command/connect/envoy/testdata/custom-bootstrap.golden
  command/connect/envoy/testdata/defaults-nodemeta.golden
  command/connect/envoy/testdata/defaults.golden
  command/connect/envoy/testdata/deprecated-grpc-addr-config.golden
  command/connect/envoy/testdata/envoy-readiness-probe.golden
  command/connect/envoy/testdata/existing-ca-file.golden
  command/connect/envoy/testdata/existing-ca-path.golden
  command/connect/envoy/testdata/extra_-multiple.golden
  command/connect/envoy/testdata/extra_-single.golden
  command/connect/envoy/testdata/grpc-addr-env.golden
  command/connect/envoy/testdata/grpc-addr-flag.golden
  command/connect/envoy/testdata/grpc-addr-unix-with-tls.golden
  command/connect/envoy/testdata/grpc-addr-unix.golden
  command/connect/envoy/testdata/grpc-tls-addr-config.golden
  command/connect/envoy/testdata/ingress-gateway-address-specified.golden
  command/connect/envoy/testdata/ingress-gateway-no-auto-register.golden
  command/connect/envoy/testdata/ingress-gateway-nodemeta.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-and-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-without-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway.golden
  command/connect/envoy/testdata/prometheus-metrics-tls-ca-file.golden
  command/connect/envoy/testdata/prometheus-metrics-tls-ca-path.golden
  command/connect/envoy/testdata/prometheus-metrics.golden
  command/connect/envoy/testdata/stats-config-override.golden
  command/connect/envoy/testdata/telemetry-collector.golden
  command/connect/envoy/testdata/token-arg.golden
  command/connect/envoy/testdata/token-env.golden
  command/connect/envoy/testdata/token-file-arg.golden
  command/connect/envoy/testdata/token-file-env.golden
  command/connect/envoy/testdata/xds-addr-config.golden
  command/connect/envoy/testdata/zipkin-tracing-config.golden
  test/integration/connect/envoy/case-ingress-gateway-sds/service_gateway.hcl
  test/integration/consul-container/test/upgrade/ingress_gateway_sds_test.go
  troubleshoot/proxy/testdata/config.json
  website/content/docs/connect/gateways/ingress-gateway/tls-external-service.mdx
  website/content/docs/connect/proxies/envoy.mdx
Labels: type/docs, theme/cli

#19952 Backport of NET-6317 - update usage of deprecated fields: http2_protocol_options and access_log_path into release/1.16.x
  .changelog/19940.txt
  command/connect/envoy/bootstrap_config.go
  command/connect/envoy/bootstrap_config_test.go
  command/connect/envoy/bootstrap_tpl.go
  command/connect/envoy/envoy_test.go
  command/connect/envoy/testdata/CONSUL_GRPC_ADDR-with-https-scheme-enables-tls.golden
  command/connect/envoy/testdata/CONSUL_HTTP_ADDR-with-https-scheme-does-not-affect-grpc-tls.golden
  command/connect/envoy/testdata/access-log-path.golden
  command/connect/envoy/testdata/access-logs-enabled-custom.golden
  command/connect/envoy/testdata/access-logs-enabled.golden
  command/connect/envoy/testdata/acl-enabled-and-token.golden
  command/connect/envoy/testdata/acl-enabled-but-no-token.golden
  command/connect/envoy/testdata/both-CONSUL_HTTP_ADDR-PLAIN-and-CONSUL_GRPC_ADDR-TLS-is-tls.golden
  command/connect/envoy/testdata/both-CONSUL_HTTP_ADDR-TLS-and-CONSUL_GRPC_ADDR-PLAIN-is-plain.golden
  command/connect/envoy/testdata/custom-bootstrap.golden
  command/connect/envoy/testdata/defaults-nodemeta.golden
  command/connect/envoy/testdata/defaults.golden
  command/connect/envoy/testdata/deprecated-grpc-addr-config.golden
  command/connect/envoy/testdata/envoy-readiness-probe.golden
  command/connect/envoy/testdata/existing-ca-file.golden
  command/connect/envoy/testdata/existing-ca-path.golden
  command/connect/envoy/testdata/extra_-multiple.golden
  command/connect/envoy/testdata/extra_-single.golden
  command/connect/envoy/testdata/grpc-addr-env.golden
  command/connect/envoy/testdata/grpc-addr-flag.golden
  command/connect/envoy/testdata/grpc-addr-unix-with-tls.golden
  command/connect/envoy/testdata/grpc-addr-unix.golden
  command/connect/envoy/testdata/grpc-tls-addr-config.golden
  command/connect/envoy/testdata/ingress-gateway-address-specified.golden
  command/connect/envoy/testdata/ingress-gateway-no-auto-register.golden
  command/connect/envoy/testdata/ingress-gateway-nodemeta.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-and-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-without-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway.golden
  command/connect/envoy/testdata/prometheus-metrics-tls-ca-file.golden
  command/connect/envoy/testdata/prometheus-metrics-tls-ca-path.golden
  command/connect/envoy/testdata/prometheus-metrics.golden
  command/connect/envoy/testdata/stats-config-override.golden
  command/connect/envoy/testdata/telemetry-collector.golden
  command/connect/envoy/testdata/token-arg.golden
  command/connect/envoy/testdata/token-env.golden
  command/connect/envoy/testdata/token-file-arg.golden
  command/connect/envoy/testdata/token-file-env.golden
  command/connect/envoy/testdata/xds-addr-config.golden
  command/connect/envoy/testdata/zipkin-tracing-config.golden
  test/integration/connect/envoy/case-ingress-gateway-sds/service_gateway.hcl
  test/integration/consul-container/test/upgrade/ingress_gateway_sds_test.go
  troubleshoot/proxy/testdata/config.json
  website/content/docs/connect/gateways/ingress-gateway/tls-external-service.mdx
  website/content/docs/connect/proxies/envoy.mdx
Labels: type/docs, theme/cli

#19957 Fix typo in service-defaults documentation
  website/content/docs/connect/config-entries/service-defaults.mdx
Labels: type/docs, pr/no-changelog, backport/1.14, backport/1.15, backport/1.16, backport/1.17

#19956 ci: upload test results to DataDog on test failure
  .github/workflows/nightly-test-integ-peering_commontopo.yml
  .github/workflows/nightly-test-integrations-1.15.x.yml
  .github/workflows/nightly-test-integrations-1.16.x.yml
  .github/workflows/nightly-test-integrations-1.17.x.yml
  .github/workflows/nightly-test-integrations.yml
  .github/workflows/reusable-unit-split.yml
  .github/workflows/reusable-unit.yml
  .github/workflows/test-integrations-windows.yml
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing, pr/no-changelog, backport/1.15, backport/1.16, backport/1.17

#19970 Fix bug with prepared queries using sameness-groups.
  .changelog/_7773.txt
  agent/consul/prepared_query_endpoint_test.go
Labels: pr/no-changelog, backport/1.16, backport/1.17

#19966 update changelog
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-backport

#19967 update changelog and version
  CHANGELOG.md
  version/VERSION
Labels: pr/no-backport

#19969 update changelog and version
  CHANGELOG.md
  version/VERSION
Labels: pr/no-backport

#19968 Xw/update changelog 1.16.4
  CHANGELOG.md
  version/VERSION
Labels: type/docs, theme/cli, pr/no-backport

#19961 Backport of Fix typo in service-defaults documentation into release/1.17.x
  website/content/docs/connect/config-entries/service-defaults.mdx
Labels: type/docs

#19960 Backport of Fix typo in service-defaults documentation into release/1.16.x
  website/content/docs/connect/config-entries/service-defaults.mdx
Labels: type/docs

#19959 Backport of Fix typo in service-defaults documentation into release/1.15.x
  website/content/docs/connect/config-entries/service-defaults.mdx
Labels: type/docs

#19958 Backport of Fix typo in service-defaults documentation into release/1.14.x
  website/content/docs/connect/config-entries/service-defaults.mdx
Labels: type/docs

#19975 added computed failover policy resource
  agent/consul/testdata/v2-resource-dependencies.md
  internal/catalog/internal/types/computed_failover_policy.go
  internal/catalog/internal/types/computed_failover_policy_test.go
  internal/catalog/internal/types/failover_policy.go
  internal/catalog/internal/types/failover_policy_test.go
  internal/catalog/internal/types/types.go
  proto-public/pbcatalog/v2beta1/computed_failover_policy.pb.binary.go
  proto-public/pbcatalog/v2beta1/computed_failover_policy.pb.go
  proto-public/pbcatalog/v2beta1/computed_failover_policy.proto
  proto-public/pbcatalog/v2beta1/computed_failover_policy_deepcopy.gen.go
  proto-public/pbcatalog/v2beta1/computed_failover_policy_json.gen.go
  proto-public/pbcatalog/v2beta1/resources.rtypes.go
Labels: pr/no-changelog, pr/no-backport

#19973 docs: typo formatting consul-k8s docs
  website/content/docs/k8s/installation/install-cli.mdx
Labels: type/docs, pr/no-changelog, backport/1.17

#19977 Backport of docs: typo formatting consul-k8s docs into release/1.17.x
  website/content/docs/k8s/installation/install-cli.mdx
Labels: type/docs, pr/no-backport

#19902 NET-6663 Modify sidecarproxy controller to skip xGateway resources
  internal/mesh/internal/controllers/sidecarproxy/controller.go
  internal/mesh/internal/controllers/sidecarproxy/controller_test.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#19718 Net 6603
  website/content/docs/k8s/k8s-cli.mdx
Labels: type/docs, pr/no-changelog, backport/1.15, backport/1.16, consul-india, backport/1.17

#19933 docs: Update network segments in compat matrix for Enterprise features
  website/content/docs/enterprise/index.mdx
Labels: type/docs, pr/no-changelog, backport/1.15, backport/1.16, backport/1.17

#19515 NET 6409
  website/content/docs/k8s/k8s-cli.mdx
Labels: type/docs, pr/no-changelog, backport/1.15, backport/1.16, consul-india, backport/1.17

#19984 Backport of docs: Update network segments in compat matrix for Enterprise features into release/1.17.x
  website/content/docs/enterprise/index.mdx
Labels: type/docs

#19935 agent: prevent empty server_metadata.json
  agent/consul/server_metadata.go
  agent/consul/server_metadata_test.go
Labels: pr/no-changelog, backport/1.17

#19994 docs: Update network segments in compat matrix for Enterprise features
  website/content/docs/enterprise/index.mdx
Labels: type/docs, pr/no-changelog, pr/no-backport

#19993 docs: Update network segments in compat matrix for Enterprise features
  website/content/docs/enterprise/index.mdx
  website/redirects.js
Labels: type/docs, pr/no-changelog, pr/no-backport

#19680 grpc client in tls mode
  command/resource/client/client.go
  command/resource/client/grpc-client.go
  command/resource/client/grpc-client_test.go
  command/resource/client/grpc-config.go
  command/resource/client/grpc-config_test.go
  command/resource/client/grpc-flags.go
  command/resource/client/grpc-flags_test.go
  command/resource/client/helper.go
  command/resource/client/helper_test.go
Labels: theme/cli, pr/no-changelog, pr/no-backport

#20002 Update Helm Documenation with changes from release 1.1.8
  website/content/docs/k8s/helm.mdx
Labels: type/docs, pr/no-changelog, pr/no-backport

#20003 Update Helm Documenation with changes from release 1.2.4
  website/content/docs/k8s/helm.mdx
Labels: type/docs, pr/no-changelog, pr/no-backport

#19992 [NET-5455] Allow disabling request and idle timeouts with -1 in service router and resolver
  .changelog/19992.txt
  agent/proxycfg/testing_upstreams.go
  agent/xds/proxystateconverter/routes.go
  agent/xds/routes.go
  agent/xds/testdata/clusters/connect-proxy-with-chain-and-splitter.latest.golden
  agent/xds/testdata/clusters/ingress-with-chain-and-splitter.latest.golden
  agent/xds/testdata/endpoints/connect-proxy-with-chain-and-splitter.latest.golden
  agent/xds/testdata/endpoints/ingress-with-chain-and-splitter.latest.golden
  agent/xds/testdata/routes/connect-proxy-with-chain-and-splitter.latest.golden
  agent/xds/testdata/routes/ingress-with-chain-and-splitter.latest.golden
Labels: theme/envoy/xds, pr/no-backport

#19995 feat: updated github checks with frontend-test-ce end frontend-test-e…
  .github/workflows/frontend.yml
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-metrics-test, backport/1.15, backport/1.16, backport/1.17

#19978 [NET-6969] security: Re-enable Go Module + secrets security scans for release branches
  .github/workflows/security-scan.yml
  .release/security-scan.hcl
  scan.hcl
Labels: type/ci, theme/contributing, pr/no-changelog, theme/security, backport/1.15, backport/1.16, backport/1.17

#20021 Backport of [NET-6969] security: Re-enable Go Module + secrets security scans for release branches into release/1.17.x
  .github/workflows/security-scan.yml
  .release/security-scan.hcl
  scan.hcl
Labels: type/ci, theme/contributing

#20020 Backport of [NET-6969] security: Re-enable Go Module + secrets security scans for release branches into release/1.16.x
  .github/workflows/security-scan.yml
  .release/security-scan.hcl
  scan.hcl
Labels: type/ci, theme/contributing

#19900 [NET-6899] Create name-aligned Service when reconciling MeshGateway resource
  internal/mesh/internal/controllers/meshgateways/controller.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#20014 Dockerfile: bump up to `ubi-minimal:9.3`
  .changelog/20014.txt
  Dockerfile
Labels: backport/1.15, backport/1.16, backport/1.17

#20023 [NET-7009] security: update x/crypto to 0.17.0
  .changelog/20023.txt
  api/go.mod
  api/go.sum
  envoyextensions/go.mod
  envoyextensions/go.sum
  go.mod
  go.sum
  proto-public/go.mod
  proto-public/go.sum
  sdk/go.mod
  sdk/go.sum
  test-integ/go.mod
  test-integ/go.sum
  test/integration/connect/envoy/test-sds-server/go.mod
  test/integration/connect/envoy/test-sds-server/go.sum
  test/integration/consul-container/go.mod
  test/integration/consul-container/go.sum
  testing/deployer/go.mod
  testing/deployer/go.sum
  troubleshoot/go.mod
  troubleshoot/go.sum
Labels: theme/api, pr/dependencies, backport/1.15, backport/1.16, backport/1.17

#20010 NET-6942 - Replace usage of deprecated Envoy field envoy.config.cluster.v3.Cluster.http_protocol_options.
  .changelog/20010.txt
  command/connect/envoy/bootstrap_config.go
  command/connect/envoy/bootstrap_config_test.go
  command/connect/envoy/testdata/envoy-readiness-probe.golden
  command/connect/envoy/testdata/ingress-gateway-address-specified.golden
  command/connect/envoy/testdata/ingress-gateway-no-auto-register.golden
  command/connect/envoy/testdata/ingress-gateway-nodemeta.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-and-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-without-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway.golden
  command/connect/envoy/testdata/prometheus-metrics-tls-ca-file.golden
  command/connect/envoy/testdata/prometheus-metrics-tls-ca-path.golden
  command/connect/envoy/testdata/prometheus-metrics.golden
  test/integration/connect/envoy/main_test.go
Labels: theme/cli, backport/1.15, backport/1.16, backport/1.17

#20035 Dockerfile: backport of #20014 for 1.17.x
  .changelog/20014.txt
  Dockerfile
Labels: pr/no-backport

#20034 Dockerfile: backport of #20014 for 1.15.x
  .changelog/20014.txt
  Dockerfile
Labels: pr/no-backport

#19901 [NET-6426] Add gateway proxy controller that generates empty proxy state template
  agent/consul/testdata/v2-resource-dependencies.md
  internal/controller/dependencies.go
  internal/mesh/internal/controllers/gatewayproxy/builder/builder.go
  internal/mesh/internal/controllers/gatewayproxy/controller.go
  internal/mesh/internal/controllers/gatewayproxy/fetcher/data_fetcher.go
  internal/mesh/internal/controllers/register.go
  internal/mesh/internal/types/decoded.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#20033 Backport of NET-6942 - Replace usage of deprecated Envoy field envoy.config.cluster.v3.Cluster.http_protocol_options. into release/1.17.x
  .changelog/20010.txt
  command/connect/envoy/bootstrap_config.go
  command/connect/envoy/bootstrap_config_test.go
  command/connect/envoy/testdata/envoy-readiness-probe.golden
  command/connect/envoy/testdata/ingress-gateway-address-specified.golden
  command/connect/envoy/testdata/ingress-gateway-no-auto-register.golden
  command/connect/envoy/testdata/ingress-gateway-nodemeta.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-and-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-without-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway.golden
  command/connect/envoy/testdata/prometheus-metrics-tls-ca-file.golden
  command/connect/envoy/testdata/prometheus-metrics-tls-ca-path.golden
  command/connect/envoy/testdata/prometheus-metrics.golden
  test/integration/connect/envoy/main_test.go
Labels: theme/cli

#20036 fix formatting issue in envoy bootstrapping.
  command/connect/envoy/bootstrap_config.go
  command/connect/envoy/bootstrap_config_test.go
  test/integration/connect/envoy/main_test.go
Labels: theme/cli, pr/no-changelog, backport/1.15, backport/1.16, backport/1.17

#20042 Backport of fix formatting issue in envoy bootstrapping. into release/1.16.x
  command/connect/envoy/bootstrap_config.go
  command/connect/envoy/bootstrap_config_test.go
  test/integration/connect/envoy/main_test.go
Labels: theme/cli

#20043 Backport of fix formatting issue in envoy bootstrapping. into release/1.17.x
  command/connect/envoy/bootstrap_config.go
  command/connect/envoy/bootstrap_config_test.go
  test/integration/connect/envoy/main_test.go
Labels: theme/cli

#20048 update makefile, compatibility tests, and nightlies to use latest envoy.
  .github/workflows/nightly-test-integrations.yml
  .github/workflows/test-integrations.yml
  Makefile
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#20040 NET-7025 - ci: test-integrations failures in compatibility tests. panics occuring in selectionTracker.TrackIDForSelection
  internal/resource/mappers/selectiontracker/selection_tracker.go
Labels: pr/no-changelog, backport/1.15, backport/1.16, backport/1.17

#20012 NET-6944 - Replace usage of deprecated Envoy field envoy.extensions.filters.http.lua.v3.Lua.inline_code
  .changelog/20012.txt
  agent/envoyextensions/builtin/lua/lua.go
  agent/xds/testdata/builtin_extension/listeners/lambda-and-lua-connect-proxy.latest.golden
  agent/xds/testdata/builtin_extension/listeners/lua-inbound-applies-to-inbound.latest.golden
  agent/xds/testdata/builtin_extension/listeners/lua-inbound-doesnt-apply-to-local-upstreams.latest.golden
  agent/xds/testdata/builtin_extension/listeners/lua-outbound-applies-to-local-upstreams-tproxy.latest.golden
  agent/xds/testdata/builtin_extension/listeners/lua-outbound-applies-to-local-upstreams.latest.golden
Labels: theme/envoy/xds, backport/1.15, backport/1.16, backport/1.17

#20053 Backport into 1.16 of NET-6944 - Replace usage of deprecated Envoy field envoy.extensions.filters.http.lua.v3.Lua.inline_code
  .changelog/20012.txt
  agent/envoyextensions/builtin/lua/lua.go
  agent/xds/testdata/builtin_extension/listeners/lambda-and-lua-connect-proxy.latest.golden
  agent/xds/testdata/builtin_extension/listeners/lua-inbound-applies-to-inbound.latest.golden
  agent/xds/testdata/builtin_extension/listeners/lua-inbound-doesnt-apply-to-local-upstreams.latest.golden
  agent/xds/testdata/builtin_extension/listeners/lua-outbound-applies-to-local-upstreams-tproxy.latest.golden
  agent/xds/testdata/builtin_extension/listeners/lua-outbound-applies-to-local-upstreams.latest.golden
Labels: theme/envoy/xds, pr/no-backport

#20054 Backport into 1.17 of NET-6944 - Replace usage of deprecated Envoy field envoy.extensions.filters.http.lua.v3.Lua.inline_code
  .changelog/20012.txt
  agent/envoyextensions/builtin/lua/lua.go
  agent/xds/testdata/builtin_extension/listeners/lambda-and-lua-connect-proxy.latest.golden
  agent/xds/testdata/builtin_extension/listeners/lua-inbound-applies-to-inbound.latest.golden
  agent/xds/testdata/builtin_extension/listeners/lua-inbound-doesnt-apply-to-local-upstreams.latest.golden
  agent/xds/testdata/builtin_extension/listeners/lua-outbound-applies-to-local-upstreams-tproxy.latest.golden
  agent/xds/testdata/builtin_extension/listeners/lua-outbound-applies-to-local-upstreams.latest.golden
Labels: theme/envoy/xds, pr/no-backport

#20011 NET-6943 - Replace usage of deprecated Envoy field envoy.config.router.v3.WeightedCluster.total_weight.
  .changelog/20011.txt
  agent/xds/routes.go
  agent/xds/testdata/builtin_extension/routes/propertyoverride-patch-specific-upstream-service-splitter.latest.golden
  agent/xds/testdata/routes/connect-proxy-lb-in-resolver.latest.golden
  agent/xds/testdata/routes/connect-proxy-with-chain-and-router.latest.golden
  agent/xds/testdata/routes/connect-proxy-with-chain-and-splitter.latest.golden
  agent/xds/testdata/routes/ingress-lb-in-resolver.latest.golden
  agent/xds/testdata/routes/ingress-splitter-with-resolver-redirect.latest.golden
  agent/xds/testdata/routes/ingress-with-chain-and-router-header-manip.latest.golden
  agent/xds/testdata/routes/ingress-with-chain-and-router.latest.golden
  agent/xds/testdata/routes/ingress-with-chain-and-splitter.latest.golden
  agent/xds/testdata/routes/mesh-gateway-with-exported-peered-services-http-with-router.latest.golden
  agent/xds/testdata/routes/splitter-with-resolver-redirect.latest.golden
  agent/xds/testdata/routes/xds-fetch-timeout-ms-ingress-with-router.latest.golden
  agent/xds/testdata/routes/xds-fetch-timeout-ms-sidecar.latest.golden
  agent/xdsv2/route_resources.go
  troubleshoot/proxy/testdata/upstreams/config.json
Labels: theme/envoy/xds, backport/1.15, backport/1.16, backport/1.17

#20016 [NET-6765] Audit the routes controller and add missing tenancy tests
  internal/mesh/internal/controllers/routes/controller_test.go
Labels: pr/no-changelog, pr/no-backport, consul-india
