Repository hashicorp/consul, pull requests merged in 2023-10, with the labels that each got.

#19023 TrafficPermissions: add ACL hooks
  acl/MockAuthorizer.go
  acl/acl_test.go
  acl/authorizer.go
  acl/chained_authorizer.go
  acl/chained_authorizer_test.go
  acl/policy_authorizer.go
  acl/static_authorizer.go
  internal/auth/internal/types/computed_traffic_permissions.go
  internal/auth/internal/types/computed_traffic_permissions_test.go
  internal/auth/internal/types/traffic_permissions.go
  internal/auth/internal/types/traffic_permissions_test.go
Labels: theme/acls, pr/no-changelog, pr/no-backport

#19042 docs: fix the description of meshgateway.mode=local in peering doc
  website/content/docs/k8s/connect/cluster-peering/usage/establish-peering.mdx
Labels: type/docs, pr/no-changelog, pr/no-backport

#19038 [NET-5788] Fix needed for JWTAuth in Consul Enterprise
  agent/xds/listeners_apigateway.go
Labels: theme/envoy/xds, pr/no-changelog, pr/no-backport

#18887 NET-5600/container-test-acl-enabled
  command/resource/client/client.go
  test/integration/consul-container/libs/cluster/agent.go
  test/integration/consul-container/libs/cluster/container.go
  test/integration/consul-container/test/resource/http_api/acl_enabled_test.go
  test/integration/consul-container/test/resource/http_api/client/client.go
  test/integration/consul-container/test/resource/http_api/helper.go
Labels: pr/no-changelog, pr/no-backport

#19041 chore: fix ce/ent drift in sdk and testing/deployer submodules
  sdk/testutil/io.go
  sdk/testutil/server.go
  sdk/testutil/testlog.go
  testing/deployer/go.mod
  testing/deployer/go.sum
  testing/deployer/sprawl/acl.go
  testing/deployer/sprawl/acl_rules.go
  testing/deployer/sprawl/boot.go
  testing/deployer/sprawl/catalog.go
  testing/deployer/sprawl/configentries.go
  testing/deployer/sprawl/consul.go
  testing/deployer/sprawl/details.go
  testing/deployer/sprawl/ent.go
  testing/deployer/sprawl/internal/build/docker.go
  testing/deployer/sprawl/internal/tfgen/digest.go
  testing/deployer/sprawl/internal/tfgen/gen.go
  testing/deployer/sprawl/internal/tfgen/io.go
  testing/deployer/sprawl/peering.go
  testing/deployer/sprawl/sprawl.go
  testing/deployer/sprawl/sprawltest/sprawltest.go
  testing/deployer/topology/compile.go
Labels: pr/no-changelog, pr/no-metrics-test, pr/no-backport

#19047 Reduce number of ports that consul test agents take
  agent/testagent.go
Labels: pr/no-changelog, pr/no-backport

#19048 Manual backport of #19031 to release/1.17.0-rc1
  .changelog/19031.txt
  agent/structs/config_entry_discoverychain.go
  agent/structs/config_entry_discoverychain_test.go
  api/config_entry_discoverychain.go
  api/config_entry_discoverychain_test.go
Labels: pr/no-metrics-test, pr/no-docs, pr/no-backport

#19049 NET-5590 - authorization: check for identity:write in CA certs, xds server, and getting envoy bootstrap params
  agent/consul/leader_connect_ca.go
  agent/consul/leader_connect_ca_test.go
  agent/grpc-external/services/dataplane/get_envoy_bootstrap_params.go
  agent/grpc-external/services/dataplane/get_envoy_bootstrap_params_test.go
  agent/grpc-external/testutils/acl.go
  internal/mesh/proxy-tracker/proxy_state_exports.go
  internal/mesh/proxy-tracker/proxy_state_exports_test.go
Labels: pr/no-changelog, pr/no-backport

#19028 Fix Traffic Permissions Default Deny
  agent/xds/rbac_test.go
  agent/xds/testdata/rbac/v2-default-allow-one-allow.golden
  agent/xds/testdata/rbac/v2-default-allow-one-deny.golden
  agent/xdsv2/listener_resources.go
  agent/xdsv2/rbac_resources.go
  internal/auth/internal/controllers/trafficpermissions/controller.go
  internal/auth/internal/controllers/trafficpermissions/controller_test.go
  internal/auth/internal/controllers/trafficpermissions/status.go
  internal/mesh/internal/controllers/sidecarproxy/builder/builder.go
  internal/mesh/internal/controllers/sidecarproxy/builder/local_app.go
  internal/mesh/internal/controllers/sidecarproxy/builder/local_app_test.go
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/source/l4-multiple-workload-addresses-with-specific-ports.golden
  internal/mesh/internal/controllers/sidecarproxy/controller_test.go
  internal/mesh/proxy-tracker/proxy_tracker_test.go
  proto-public/pbauth/v2beta1/computed_traffic_permissions.pb.go
  proto-public/pbauth/v2beta1/computed_traffic_permissions.proto
  proto-public/pbmesh/v2beta1/pbproxystate/traffic_permissions.pb.go
  proto-public/pbmesh/v2beta1/pbproxystate/traffic_permissions.proto
  proto-public/pbmesh/v2beta1/proxy_state.pb.go
  proto-public/pbmesh/v2beta1/proxy_state.proto
  test/integration/consul-container/test/multiport/explicit_destination_test.go
Labels: theme/envoy/xds, pr/no-changelog, pr/no-backport

#19045 Add workload identity hooks
  internal/auth/internal/types/workload_identity.go
  internal/auth/internal/types/workload_identity_test.go
Labels: pr/no-changelog, pr/no-backport

#19060 Fix Explicit Destination Integration Test
  test/integration/consul-container/test/multiport/explicit_destination_test.go
Labels: pr/no-changelog, pr/no-backport

#19061 Add upgrade warnings
  website/content/docs/upgrading/upgrade-specific.mdx
Labels: type/docs, pr/no-changelog, backport/1.16

#19053 chor: update rule to run frontend github tasks when changes are made …
  .github/workflows/frontend.yml
Labels: type/ci, theme/contributing, pr/no-changelog, backport/1.15, backport/1.16

#19062 Backport of Add upgrade warnings into release/1.16.x
  website/content/docs/upgrading/upgrade-specific.mdx
Labels: type/docs

#19063 [1.15.x] Update upgrade-specific.mdx
  website/content/docs/upgrading/upgrade-specific.mdx
Labels: type/docs, pr/no-changelog, pr/no-backport

#19066 [1.14.x] Update upgrade-specific.mdx
  website/content/docs/upgrading/upgrade-specific.mdx
Labels: pr/no-changelog, pr/no-backport

#19056 Fixes docs of Consul Debug - Adds info about Since Flag
  website/content/commands/debug.mdx
Labels: type/docs, pr/no-changelog, backport/1.14, backport/1.15, backport/1.16

#19073 Backport of Fixes docs of Consul Debug - Adds info about Since Flag into release/1.15.x
  website/content/commands/debug.mdx
Labels: type/docs

#19074 Backport of Fixes docs of Consul Debug - Adds info about Since Flag into release/1.16.x
  website/content/commands/debug.mdx
Labels: type/docs

#19072 Backport of Fixes docs of Consul Debug - Adds info about Since Flag into release/1.14.x
  website/content/commands/debug.mdx
Labels: type/docs

#19052 docs: clarify the requriment for cross-partition network
  website/content/docs/enterprise/admin-partitions.mdx
Labels: type/docs, pr/no-changelog, backport/1.14, backport/1.15, backport/1.16

#19081 Bump up compatibility test runner
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#19080 Backport of docs: clarify the requriment for cross-partition network into release/1.16.x
  website/content/docs/enterprise/admin-partitions.mdx
Labels: type/docs

#19079 Backport of docs: clarify the requriment for cross-partition network into release/1.15.x
  website/content/docs/enterprise/admin-partitions.mdx
Labels: type/docs

#19078 Backport of docs: clarify the requriment for cross-partition network into release/1.14.x
  website/content/docs/enterprise/admin-partitions.mdx
Labels: type/docs

#19077 [CE] Add workload bind type and templated policy
  .changelog/19077.txt
  agent/acl_endpoint_test.go
  agent/consul/acl_endpoint.go
  agent/consul/auth/binder.go
  agent/consul/auth/binder_test.go
  agent/structs/acl_templated_policy.go
  agent/structs/acl_templated_policy_ce.go
  agent/structs/acl_templated_policy_ce_test.go
  agent/structs/acltemplatedpolicy/policies/ce/workload-identity.hcl
  agent/structs/acltemplatedpolicy/schemas/workload-identity.json
  api/acl.go
Labels: theme/api, pr/no-backport

#19086 Docs/ce 475 retries timeouts for apigw
  website/content/docs/connect/config-entries/http-route.mdx
  website/content/docs/connect/gateways/api-gateway/configuration/routeretryfilter.mdx
  website/content/docs/connect/gateways/api-gateway/configuration/routetimeoutfilter.mdx
  website/data/docs-nav-data.json
Labels: type/docs, pr/no-changelog, pr/no-metrics-test, pr/no-backport

#19088 Retry flaky tests
  agent/health_endpoint_test.go
  agent/http_test.go
  agent/metrics_test.go
  agent/testagent.go
Labels: pr/no-changelog, pr/no-backport

#18959 Allow connections through Terminating Gateways from peered clusters NET-3463
  .changelog/18959.txt
  agent/proxycfg/proxycfg.deepcopy.go
  agent/proxycfg/snapshot.go
  agent/proxycfg/terminating_gateway.go
  agent/xds/listeners.go
  agent/xds/listeners_test.go
  agent/xds/testdata/builtin_extension/clusters/otel-access-logging-http.latest.golden
  agent/xds/testdata/builtin_extension/endpoints/otel-access-logging-http.latest.golden
  agent/xds/testdata/builtin_extension/listeners/otel-access-logging-http.latest.golden
  agent/xds/testdata/builtin_extension/routes/otel-access-logging-http.latest.golden
  agent/xds/testdata/listeners/terminating-gateway-with-peer-trust-bundle.latest.golden
  agent/xds/testdata/rbac/v2-default-deny.golden
  agent/xds/testdata/rbac/v2-kitchen-sink.golden
Labels: theme/envoy/xds, backport/1.15, backport/1.16

#19085 mesh: ensure we add the virtual port number for L7 implicit upstreams
  internal/mesh/internal/controllers/sidecarproxy/builder/destination_builder.go
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-multiple-implicit-destinations-tproxy.golden
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-single-implicit-destination-tproxy.golden
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-single-implicit-destination-with-multiple-workloads-tproxy.golden
Labels: pr/no-changelog, pr/no-metrics-test, pr/no-backport

#19092 Backport of Allow connections through Terminating Gateways from peered clusters NET-3463 into release/1.16.x
  .changelog/18959.txt
  agent/proxycfg/proxycfg.deepcopy.go
  agent/proxycfg/snapshot.go
  agent/proxycfg/terminating_gateway.go
  agent/xds/listeners.go
  agent/xds/listeners_test.go
  agent/xds/testdata/listeners/terminating-gateway-with-peer-trust-bundle.latest.golden
Labels: theme/envoy/xds

#19089 Replace `hub` with `gh` for member roles on JIRA sync checks
  .github/workflows/jira-pr.yaml
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#19090 Make raft-wal default when `resource-apis` is active
  agent/config/builder.go
  agent/config/default.go
  agent/config/runtime_test.go
  agent/consul/config.go
  agent/consul/server.go
  agent/setup.go
Labels: theme/config, pr/no-backport

#19008 Add traffic permissions integration tests.
  .github/workflows/test-integrations.yml
  Makefile
  internal/resource/resourcetest/builder.go
  internal/resource/resourcetest/client.go
  test/integration/consul-container/assets/Dockerfile-consul-dataplane
  test/integration/consul-container/libs/cluster/builder.go
  test/integration/consul-container/libs/cluster/dataplane.go
  test/integration/consul-container/libs/topology/peering_topology.go
  test/integration/consul-container/test/multiport/explicit_destination_test.go
  test/integration/consul-container/test/trafficpermissions/tcp_test.go
Labels: pr/no-changelog, pr/no-backport

#19076 Ensure that upstream configuration is properly normalized.
  .changelog/_6074.txt
  agent/configentry/merge_service_config.go
  agent/service_manager.go
  agent/structs/config_entry.go
  agent/structs/config_entry_ce.go
  agent/structs/config_entry_ce_test.go
  agent/structs/structs_ce.go
  website/content/docs/connect/proxies/proxy-config-reference.mdx
Labels: type/docs, pr/no-changelog, pr/no-backport

#19071 Docs/ce 470 locality aware
  website/content/api-docs/discovery-chain.mdx
  website/content/docs/agent/config/config-files.mdx
  website/content/docs/connect/cluster-peering/usage/create-sameness-groups.mdx
  website/content/docs/connect/cluster-peering/usage/peering-traffic-management.mdx
  website/content/docs/connect/config-entries/ingress-gateway.mdx
  website/content/docs/connect/config-entries/proxy-defaults.mdx
  website/content/docs/connect/config-entries/service-defaults.mdx
  website/content/docs/connect/config-entries/service-resolver.mdx
  website/content/docs/connect/config-entries/service-router.mdx
  website/content/docs/connect/gateways/terminating-gateway.mdx
  website/content/docs/connect/manage-traffic/discovery-chain.mdx
  website/content/docs/connect/manage-traffic/failover/index.mdx
  website/content/docs/connect/manage-traffic/index.mdx
  website/content/docs/connect/manage-traffic/limit-request-rates.mdx
  website/content/docs/connect/manage-traffic/route-to-local-upstreams.mdx
  website/content/docs/connect/proxies/envoy.mdx
  website/content/docs/connect/proxies/index.mdx
  website/content/docs/connect/proxies/integrate.mdx
  website/content/docs/internals/index.mdx
  website/content/docs/k8s/connect/cluster-peering/usage/create-sameness-groups.mdx
  website/content/docs/k8s/connect/cluster-peering/usage/l7-traffic.mdx
  website/content/docs/k8s/deployment-configurations/multi-cluster/index.mdx
  website/content/docs/k8s/l7-traffic/failover-tproxy.mdx
  website/content/docs/k8s/l7-traffic/route-to-virtual-services.mdx
  website/content/docs/services/configuration/services-configuration-reference.mdx
  website/data/docs-nav-data.json
  website/redirects.js
Labels: type/docs, pr/no-changelog, pr/no-metrics-test, pr/no-backport

#19108 protohcl: allow attribute syntax for all map fields
  internal/protohcl/decoder.go
  internal/protohcl/unmarshal_test.go
Labels: pr/no-changelog, pr/no-docs, pr/no-backport

#18322 NET-4135 - Fix NodeMeta filtering Catalog List Services API
  .changelog/18322.txt
  agent/consul/catalog_endpoint.go
  agent/consul/state/catalog.go
  agent/consul/state/catalog_test.go
  api/catalog_test.go
Labels: backport/1.14, backport/1.15, backport/1.16, consul-india

#19115 Backport - NET-4135 - Fix NodeMeta filtering Catalog List Services API (#18322)
  .changelog/18322.txt
  agent/consul/catalog_endpoint.go
  agent/consul/state/catalog.go
  agent/consul/state/catalog_test.go
  api/catalog_test.go
Labels: theme/api, pr/no-backport

#19116 Backport NET-4135 - Fix NodeMeta filtering Catalog List Services API (#18322)
  .changelog/18322.txt
  agent/consul/catalog_endpoint.go
  agent/consul/state/catalog.go
  agent/consul/state/catalog_test.go
  api/catalog_test.go
Labels: type/docs, theme/api, theme/acls, theme/cli, theme/config, theme/ui, theme/connect, theme/tls, theme/telemetry, type/ci, pr/dependencies, theme/envoy/xds, theme/contributing, theme/internals, theme/certificates, theme/agent-cache, theme/consul-terraform-sync, pr/no-backport

#19118 Stop windows integration tests
  .github/workflows/test-integrations-windows.yml
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#19121 Backport of Replace `hub` with `gh` for member roles on JIRA sync checks into release/1.15.x
  .github/workflows/jira-pr.yaml
Labels: type/ci, theme/contributing

#19122 Backport of Replace `hub` with `gh` for member roles on JIRA sync checks into release/1.16.x
  .github/workflows/jira-pr.yaml
Labels: type/ci, theme/contributing

#19106 Minor update to ratelimit wording
  website/content/docs/connect/config-entries/service-defaults.mdx
Labels: type/docs, pr/no-changelog, pr/no-backport

#19127 Backport of Update vault ca provider namespace configuration into release/1.16.x
  .changelog/19095.txt
  agent/connect/ca/provider_vault.go
  agent/connect/ca/provider_vault_test.go
  agent/connect/ca/testing.go
Labels: theme/connect

#19120 NET-5457 Support multiple virtual hosts for a single API gateway listener
  .changelog/19120.txt
  agent/consul/discoverychain/gateway.go
  agent/xds/listeners_apigateway.go
  agent/xds/routes.go
  agent/xds/routes_test.go
  agent/xds/testdata/routes/api-gateway-with-multiple-hostnames.latest.golden
Labels: theme/envoy/xds, theme/api-gw, pr/no-backport

#19082 v2tenancy: cluster scoped reads
  agent/grpc-external/services/resource/read.go
  agent/grpc-external/services/resource/read_test.go
  agent/grpc-external/services/resource/testing/testing.go
  internal/resource/demo/demo.go
  internal/resource/http/http_test.go
  proto/private/pbdemo/v1/demo.pb.binary.go
  proto/private/pbdemo/v1/demo.pb.go
  proto/private/pbdemo/v1/demo.proto
Labels: pr/no-changelog, pr/no-backport

#19123 [NET-5457] Fix CE code for jwt multiple virtual hosts bug
  agent/consul/discoverychain/gateway.go
  agent/xds/jwt_authn_ce.go
  agent/xds/listeners_apigateway.go
  agent/xds/routes.go
Labels: theme/envoy/xds, pr/no-changelog, pr/no-backport

#19132 centralize useV2Resources logic in deps and use that to configure server
  agent/agent.go
  agent/consul/options.go
  agent/consul/server.go
  agent/http.go
  agent/testagent.go
Labels: pr/no-changelog, pr/no-backport

#19043 mesh: Add ComputedProxyConfiguration and a controller that computes it.
  internal/catalog/exports.go
  internal/catalog/internal/controllers/endpoints/controller_test.go
  internal/catalog/internal/mappers/selectiontracker/selection_tracker_test.go
  internal/controller/helper.go
  internal/mesh/internal/controllers/proxyconfiguration/controller.go
  internal/mesh/internal/controllers/proxyconfiguration/controller_test.go
  internal/mesh/internal/controllers/proxyconfiguration/mapper/proxy_configuration_mapper.go
  internal/mesh/internal/controllers/proxyconfiguration/mapper/proxy_configuration_mapper_test.go
  internal/mesh/internal/controllers/proxyconfiguration/sort.go
  internal/mesh/internal/controllers/proxyconfiguration/sort_test.go
  internal/mesh/internal/controllers/register.go
  internal/mesh/internal/mappers/common/workload_selector_util.go
  internal/mesh/internal/mappers/common/workload_selector_util_test.go
  internal/mesh/internal/types/computed_proxy_configuration.go
  internal/mesh/internal/types/types.go
  internal/resource/mappers/selectiontracker/selection_tracker.go
  internal/resource/mappers/selectiontracker/selection_tracker_test.go
  proto-public/pbmesh/v2beta1/computed_proxy_configuration.pb.binary.go
  proto-public/pbmesh/v2beta1/computed_proxy_configuration.pb.go
  proto-public/pbmesh/v2beta1/computed_proxy_configuration.proto
  proto-public/pbmesh/v2beta1/resource_types.gen.go
Labels: pr/no-changelog, pr/no-backport

#19135 Add 1.17 release notes
  website/content/docs/release-notes/consul/v1_17_x.mdx
  website/data/docs-nav-data.json
Labels: type/docs, pr/no-changelog, pr/no-backport

#19134 fix flaking container tests
  test/integration/consul-container/libs/cluster/encryption.go
  test/integration/consul-container/test/ratelimit/ratelimit_test.go
Labels: pr/no-changelog, pr/no-backport

#19129 server: when the v2 catalog experiment is enabled reject api and rpc requests that are for the v1 catalog
  agent/ae/ae.go
  agent/agent.go
  agent/agent_endpoint_test.go
  agent/catalog_endpoint_test.go
  agent/config_endpoint_test.go
  agent/consul/options.go
  agent/consul/server.go
  agent/health_endpoint_test.go
  agent/http.go
  agent/rpc/middleware/interceptors.go
  agent/structs/errors.go
  agent/testagent.go
  agent/ui_endpoint_test.go
Labels: theme/health-checks, pr/no-changelog, pr/no-metrics-test, pr/no-backport

#19087 NET-5822 - Add default outbound router in TProxy
  agent/xdsv2/testdata/input/l4-single-implicit-destination-tproxy.golden
  agent/xdsv2/testdata/output/listeners/l4-single-implicit-destination-tproxy.golden
  internal/mesh/internal/controllers/sidecarproxy/builder/destination_builder.go
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/l4-implicit-and-explicit-destinations-tproxy.golden
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/l4-multiple-implicit-destinations-tproxy.golden
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/l4-single-implicit-destination-tproxy.golden
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-multiple-implicit-destinations-tproxy.golden
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-single-implicit-destination-tproxy.golden
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-single-implicit-destination-with-multiple-workloads-tproxy.golden
Labels: pr/no-changelog, pr/no-backport

#19107 cli: do not hide the resource HCL parsing error and replace it with a JSON error
  command/resource/helper.go
Labels: theme/cli, pr/no-changelog, pr/no-metrics-test, pr/no-backport

#19140 fix broken link
  website/content/docs/connect/manage-traffic/index.mdx
Labels: type/docs, pr/no-changelog, pr/no-metrics-test, backport/1.17

#19145 nightly test workflow for 1.17.x
  .github/workflows/nightly-test-1.17.x.yaml
Labels: type/ci, theme/contributing, pr/no-changelog, backport/1.17

#19146 sdk: update testutil.WaitForLeader to not use the v1 catalog api
  sdk/testutil/server.go
Labels: pr/no-changelog, pr/no-metrics-test, backport/1.17

#19101 test: fix container test enterprise drift
  api/go.mod
  test/integration/consul-container/go.mod
  test/integration/consul-container/go.sum
  test/integration/consul-container/libs/assert/envoy.go
  test/integration/consul-container/libs/cluster/agent.go
  test/integration/consul-container/libs/cluster/cluster.go
  test/integration/consul-container/libs/cluster/container.go
  test/integration/consul-container/libs/service/connect.go
  test/integration/consul-container/libs/service/gateway.go
  test/integration/consul-container/libs/service/helpers.go
Labels: theme/api, pr/no-changelog, pr/no-metrics-test, backport/1.17

#19147 release/1.15.x: Manual backport of #19095
  .changelog/19095.txt
  agent/connect/ca/provider_vault.go
  agent/connect/ca/provider_vault_test.go
  agent/connect/ca/testing.go
Labels: theme/connect, pr/no-docs, pr/no-backport

#19148 release/1.14.x: Manual backport of #19095
  .changelog/19095.txt
  agent/connect/ca/provider_vault_test.go
  agent/connect/ca/testing.go
Labels: theme/connect, pr/no-docs, pr/no-backport

#19152 Fix BUSL license checker to skip >= 1.17.x target branches
  .github/scripts/license_checker.sh
  .github/workflows/license-checker.yml
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#19150 Backport of test: fix container test enterprise drift into release/1.17.x
  api/go.mod
  test/integration/consul-container/go.mod
  test/integration/consul-container/go.sum
  test/integration/consul-container/libs/assert/envoy.go
  test/integration/consul-container/libs/cluster/agent.go
  test/integration/consul-container/libs/cluster/cluster.go
  test/integration/consul-container/libs/cluster/container.go
  test/integration/consul-container/libs/service/connect.go
  test/integration/consul-container/libs/service/gateway.go
  test/integration/consul-container/libs/service/helpers.go
Labels: theme/api

#19154 Fix BUSL license checker to skip >= 1.17.x target branches (#19152)
  .github/scripts/license_checker.sh
  .github/workflows/license-checker.yml
Labels: type/ci, theme/contributing, pr/no-changelog, backport/1.14, backport/1.15, backport/1.16

#19155 Backport of Fix BUSL license checker to skip >= 1.17.x target branches (#19152) into release/1.14.x
  .github/scripts/license_checker.sh
  .github/workflows/license-checker.yml
Labels: type/ci, theme/contributing

#19156 Backport of Fix BUSL license checker to skip >= 1.17.x target branches (#19152) into release/1.15.x
  .github/scripts/license_checker.sh
  .github/workflows/license-checker.yml
Labels: type/ci, theme/contributing

#19157 Backport of Fix BUSL license checker to skip >= 1.17.x target branches (#19152) into release/1.16.x
  .github/scripts/license_checker.sh
  .github/workflows/license-checker.yml
Labels: type/ci, theme/contributing

#19044 mesh: implement exposed paths
  internal/mesh/internal/controllers/sidecarproxy/builder/builder.go
  internal/mesh/internal/controllers/sidecarproxy/builder/destination_multiport_test.go
  internal/mesh/internal/controllers/sidecarproxy/builder/destinations.go
  internal/mesh/internal/controllers/sidecarproxy/builder/destinations_test.go
  internal/mesh/internal/controllers/sidecarproxy/builder/expose_paths.go
  internal/mesh/internal/controllers/sidecarproxy/builder/expose_paths_test.go
  internal/mesh/internal/controllers/sidecarproxy/builder/local_app.go
  internal/mesh/internal/controllers/sidecarproxy/builder/local_app_test.go
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-multiple-implicit-destinations-tproxy.golden
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-single-implicit-destination-tproxy.golden
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-single-implicit-destination-with-multiple-workloads-tproxy.golden
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/source/l7-expose-paths.golden
  proto-public/pbcatalog/v2beta1/workload_addon.go
  proto-public/pbcatalog/v2beta1/workload_addon_test.go
  proto-public/pbmesh/v2beta1/expose.pb.go
  proto-public/pbmesh/v2beta1/expose.proto
Labels: pr/no-changelog, pr/no-backport

#19142 NET-5799 - ensure catalog controllers and dependency mappers function correctly for tenancy fields
  internal/catalog/internal/controllers/workloadhealth/controller.go
  internal/catalog/internal/controllers/workloadhealth/controller_test.go
  internal/catalog/internal/mappers/nodemapper/node_mapper.go
Labels: pr/no-changelog, pr/no-backport

#19168 catalog: block unsupported failover policy settings for now
  internal/catalog/internal/types/failover_policy.go
  internal/catalog/internal/types/failover_policy_test.go
Labels: pr/no-changelog, pr/no-metrics-test, backport/1.17

#19166 Refactor connect_auth.go into agent_endpoint.go
  agent/agent_endpoint.go
  agent/connect_auth.go
Labels: pr/no-changelog, pr/no-backport

#19067 mesh: add computed destinations with a controller that computes them
  internal/mesh/internal/controllers/explicitdestinations/controller.go
  internal/mesh/internal/controllers/explicitdestinations/controller_test.go
  internal/mesh/internal/controllers/explicitdestinations/mapper/mapper.go
  internal/mesh/internal/controllers/explicitdestinations/status.go
  internal/mesh/internal/controllers/proxyconfiguration/controller.go
  internal/mesh/internal/controllers/proxyconfiguration/controller_test.go
  internal/mesh/internal/controllers/proxyconfiguration/mapper/proxy_configuration_mapper.go
  internal/mesh/internal/controllers/register.go
  internal/mesh/internal/controllers/sidecarproxy/controller_test.go
  internal/mesh/internal/mappers/workloadselectionmapper/workload_selection_mapper.go
  internal/mesh/internal/mappers/workloadselectionmapper/workload_selection_mapper_test.go
  internal/mesh/internal/types/computed_explicit_destinations.go
  internal/mesh/internal/types/destinations.go
  internal/mesh/internal/types/destinations_test.go
  internal/mesh/internal/types/types.go
  proto-public/pbcatalog/v2beta1/service_addon.go
  proto-public/pbcatalog/v2beta1/service_addon_test.go
  proto-public/pbmesh/v2beta1/computed_explicit_destinations.pb.binary.go
  proto-public/pbmesh/v2beta1/computed_explicit_destinations.pb.go
  proto-public/pbmesh/v2beta1/computed_explicit_destinations.proto
  proto-public/pbmesh/v2beta1/resource_types.gen.go
Labels: pr/no-changelog, pr/no-backport

#19175 get-envoy-bootstrap-params: when v2 is enabled, use computed proxy configuration
  agent/grpc-external/services/dataplane/get_envoy_bootstrap_params.go
  agent/grpc-external/services/dataplane/get_envoy_bootstrap_params_test.go
Labels: pr/no-changelog, pr/no-backport

#19180 Update metdata for locality-aware usage page
  website/content/docs/connect/manage-traffic/route-to-local-upstreams.mdx
Labels: type/docs, pr/no-changelog, pr/no-metrics-test, backport/1.17

#19182 Backport of Update metdata for locality-aware usage page into release/1.17.x
  website/content/docs/connect/manage-traffic/route-to-local-upstreams.mdx
Labels: type/docs

#19181 Add 1.17 upgrade-specific note for upstream normalization.
  website/content/docs/upgrading/upgrade-specific.mdx
Labels: type/docs, pr/no-changelog, backport/1.17

#19184 Backport of Add 1.17 upgrade-specific note for upstream normalization. into release/1.17.x
  website/content/docs/upgrading/upgrade-specific.mdx
Labels: type/docs

#19174 NET-5951 - Unique route names for implicit routes
  internal/mesh/internal/controllers/sidecarproxy/builder/destinations.go
  internal/mesh/internal/controllers/sidecarproxy/builder/naming.go
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/l4-implicit-and-explicit-destinations-tproxy.golden
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/l4-multi-destination.golden
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/l4-single-destination-ip-port-bind-address.golden
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/l4-single-destination-unix-socket-bind-address.golden
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/mixed-multi-destination.golden
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-multiple-implicit-destinations-tproxy.golden
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-single-implicit-destination-tproxy.golden
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-single-implicit-destination-with-multiple-workloads-tproxy.golden
Labels: pr/no-changelog, pr/no-backport

#19183 mesh: fix race in the sidecar-proxy controller test
  internal/mesh/internal/controllers/sidecarproxy/controller_test.go
Labels: pr/no-changelog, pr/no-backport

#19172 mesh: properly handle missing workload protocols
  internal/mesh/internal/controllers/sidecarproxy/builder/local_app.go
  internal/mesh/internal/controllers/sidecarproxy/cache/cache.go
  internal/mesh/internal/controllers/sidecarproxy/cache/cache_test.go
  internal/mesh/internal/controllers/sidecarproxy/controller.go
  internal/mesh/internal/controllers/sidecarproxy/controller_test.go
Labels: pr/no-changelog, pr/no-backport

#19084 Net-5771/apply command stdin input
  command/resource/apply/apply.go
  command/resource/apply/apply_test.go
  command/resource/helper.go
Labels: theme/cli, pr/no-changelog, pr/no-backport

#19096 Golden File Tests for TermGW w/ Cluster Peering
  agent/xds/listeners_test.go
  agent/xds/testdata/listeners/terminating-gateway-with-peer-trust-bundle.latest.golden
Labels: theme/envoy/xds, pr/no-changelog, backport/1.15, backport/1.16

#19173 Add namespace read write tests
  agent/grpc-external/services/resource/testing/testing.go
  internal/tenancy/internal/types/namespace.go
  internal/tenancy/internal/types/namespace_test.go
Labels: pr/no-changelog, pr/no-backport

#19176 mesh: ensure that xRoutes have ParentRefs that have matching Tenancy to the enclosing resource
  internal/mesh/internal/types/destinations_test.go
  internal/mesh/internal/types/grpc_route.go
  internal/mesh/internal/types/grpc_route_test.go
  internal/mesh/internal/types/http_route.go
  internal/mesh/internal/types/http_route_test.go
  internal/mesh/internal/types/tcp_route.go
  internal/mesh/internal/types/tcp_route_test.go
  internal/mesh/internal/types/xroute.go
  internal/mesh/internal/types/xroute_test.go
  internal/resource/resourcetest/tenancy.go
  internal/resource/tenancy.go
Labels: pr/no-changelog, pr/no-metrics-test, backport/1.17

#19193 Backport of mesh: ensure that xRoutes have ParentRefs that have matching Tenancy to the enclosing resource into release/1.17.x
  internal/mesh/internal/types/destinations_test.go
  internal/mesh/internal/types/grpc_route.go
  internal/mesh/internal/types/grpc_route_test.go
  internal/mesh/internal/types/http_route.go
  internal/mesh/internal/types/http_route_test.go
  internal/mesh/internal/types/tcp_route.go
  internal/mesh/internal/types/tcp_route_test.go
  internal/mesh/internal/types/xroute.go
  internal/mesh/internal/types/xroute_test.go
  internal/resource/resourcetest/tenancy.go
  internal/resource/tenancy.go
Labels: type/docs, theme/api, type/ci, theme/contributing

#19194 Backport of mesh: add computed destinations with a controller that computes them into release/1.17.x
  internal/mesh/internal/controllers/explicitdestinations/controller.go
  internal/mesh/internal/controllers/explicitdestinations/controller_test.go
  internal/mesh/internal/controllers/explicitdestinations/mapper/mapper.go
  internal/mesh/internal/controllers/explicitdestinations/status.go
  internal/mesh/internal/controllers/proxyconfiguration/controller.go
  internal/mesh/internal/controllers/proxyconfiguration/controller_test.go
  internal/mesh/internal/controllers/proxyconfiguration/mapper/proxy_configuration_mapper.go
  internal/mesh/internal/controllers/register.go
  internal/mesh/internal/controllers/sidecarproxy/controller_test.go
  internal/mesh/internal/mappers/workloadselectionmapper/workload_selection_mapper.go
  internal/mesh/internal/mappers/workloadselectionmapper/workload_selection_mapper_test.go
  internal/mesh/internal/types/computed_explicit_destinations.go
  internal/mesh/internal/types/destinations.go
  internal/mesh/internal/types/destinations_test.go
  internal/mesh/internal/types/types.go
  proto-public/pbcatalog/v2beta1/service_addon.go
  proto-public/pbcatalog/v2beta1/service_addon_test.go
  proto-public/pbmesh/v2beta1/computed_explicit_destinations.pb.binary.go
  proto-public/pbmesh/v2beta1/computed_explicit_destinations.pb.go
  proto-public/pbmesh/v2beta1/computed_explicit_destinations.proto
  proto-public/pbmesh/v2beta1/resource_types.gen.go
Labels: type/docs, theme/api, theme/health-checks, theme/cli, type/ci, theme/envoy/xds, theme/contributing

#19198 catalog: add metadata filtering to refine workload selectors
  internal/catalog/exports.go
  internal/catalog/internal/controllers/endpoints/reconciliation_data.go
  internal/catalog/internal/controllers/endpoints/reconciliation_data_test.go
  internal/catalog/internal/types/dns_policy.go
  internal/catalog/internal/types/health_checks.go
  internal/catalog/internal/types/service.go
  internal/catalog/internal/types/validators.go
  internal/catalog/internal/types/validators_test.go
  internal/mesh/internal/controllers/explicitdestinations/controller.go
  internal/mesh/internal/controllers/proxyconfiguration/controller.go
  internal/mesh/internal/types/destinations.go
  internal/mesh/internal/types/destinations_configuration.go
  internal/mesh/internal/types/destinations_configuration_test.go
  internal/mesh/internal/types/destinations_test.go
  internal/mesh/internal/types/proxy_configuration.go
  internal/mesh/internal/types/proxy_configuration_test.go
  internal/resource/filter.go
  internal/resource/filter_test.go
Labels: pr/no-changelog, pr/no-metrics-test, backport/1.17

#19205 server: run the api checks against the path without params
  agent/agent_endpoint_test.go
  agent/http.go
Labels: pr/no-changelog, pr/no-metrics-test, backport/1.17

#19204 Clone proto into deepcopy correctly
  internal/resource/protoc-gen-deepcopy/internal/generate/generate.go
  proto-public/annotations/ratelimit/ratelimit_deepcopy.gen.go
  proto-public/pbacl/acl_deepcopy.gen.go
  proto-public/pbauth/v2beta1/computed_traffic_permissions_deepcopy.gen.go
  proto-public/pbauth/v2beta1/traffic_permissions_deepcopy.gen.go
  proto-public/pbauth/v2beta1/workload_identity_deepcopy.gen.go
  proto-public/pbcatalog/v2beta1/dns_deepcopy.gen.go
  proto-public/pbcatalog/v2beta1/failover_policy_deepcopy.gen.go
  proto-public/pbcatalog/v2beta1/health_deepcopy.gen.go
  proto-public/pbcatalog/v2beta1/node_deepcopy.gen.go
  proto-public/pbcatalog/v2beta1/selector_deepcopy.gen.go
  proto-public/pbcatalog/v2beta1/service_deepcopy.gen.go
  proto-public/pbcatalog/v2beta1/service_endpoints_deepcopy.gen.go
  proto-public/pbcatalog/v2beta1/vip_deepcopy.gen.go
  proto-public/pbcatalog/v2beta1/workload_deepcopy.gen.go
  proto-public/pbconnectca/ca_deepcopy.gen.go
  proto-public/pbdataplane/dataplane_deepcopy.gen.go
  proto-public/pbdns/dns_deepcopy.gen.go
  proto-public/pbmesh/v2beta1/common_deepcopy.gen.go
  proto-public/pbmesh/v2beta1/computed_explicit_destinations_deepcopy.gen.go
  proto-public/pbmesh/v2beta1/computed_proxy_configuration_deepcopy.gen.go
  proto-public/pbmesh/v2beta1/computed_routes_deepcopy.gen.go
  proto-public/pbmesh/v2beta1/connection_deepcopy.gen.go
  proto-public/pbmesh/v2beta1/destination_policy_deepcopy.gen.go
  proto-public/pbmesh/v2beta1/destinations_configuration_deepcopy.gen.go
  proto-public/pbmesh/v2beta1/destinations_deepcopy.gen.go
  proto-public/pbmesh/v2beta1/expose_deepcopy.gen.go
  proto-public/pbmesh/v2beta1/grpc_route_deepcopy.gen.go
  proto-public/pbmesh/v2beta1/http_route_deepcopy.gen.go
  proto-public/pbmesh/v2beta1/http_route_retries_deepcopy.gen.go
  proto-public/pbmesh/v2beta1/http_route_timeouts_deepcopy.gen.go
  proto-public/pbmesh/v2beta1/pbproxystate/access_logs_deepcopy.gen.go
  proto-public/pbmesh/v2beta1/pbproxystate/address_deepcopy.gen.go
  proto-public/pbmesh/v2beta1/pbproxystate/cluster_deepcopy.gen.go
  proto-public/pbmesh/v2beta1/pbproxystate/endpoints_deepcopy.gen.go
  proto-public/pbmesh/v2beta1/pbproxystate/escape_hatches_deepcopy.gen.go
  proto-public/pbmesh/v2beta1/pbproxystate/header_mutations_deepcopy.gen.go
  proto-public/pbmesh/v2beta1/pbproxystate/listener_deepcopy.gen.go
  proto-public/pbmesh/v2beta1/pbproxystate/references_deepcopy.gen.go
  proto-public/pbmesh/v2beta1/pbproxystate/route_deepcopy.gen.go
  proto-public/pbmesh/v2beta1/pbproxystate/traffic_permissions_deepcopy.gen.go
  proto-public/pbmesh/v2beta1/pbproxystate/transport_socket_deepcopy.gen.go
  proto-public/pbmesh/v2beta1/proxy_configuration_deepcopy.gen.go
  proto-public/pbmesh/v2beta1/proxy_state_deepcopy.gen.go
  proto-public/pbmesh/v2beta1/tcp_route_deepcopy.gen.go
  proto-public/pbresource/annotations_deepcopy.gen.go
  proto-public/pbresource/resource_deepcopy.gen.go
  proto-public/pbserverdiscovery/serverdiscovery_deepcopy.gen.go
  proto-public/pbtenancy/v1alpha1/namespace_deepcopy.gen.go
Labels: pr/no-changelog, backport/1.17

#19208 chore: update version and nightly CI for 1.17
  .github/workflows/nightly-test-1.17.x.yaml
  version/VERSION
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#19186 mesh: add validation hook to proxy configuration
  internal/mesh/internal/controllers/proxyconfiguration/sort_test.go
  internal/mesh/internal/types/errors.go
  internal/mesh/internal/types/proxy_configuration.go
  internal/mesh/internal/types/proxy_configuration_test.go
  internal/resource/errors.go
  proto-public/pbmesh/v2beta1/proxy_configuration.pb.go
  proto-public/pbmesh/v2beta1/proxy_configuration.proto
  proto-public/pbmesh/v2beta1/routing.pb.go
  proto-public/pbmesh/v2beta1/routing.proto
Labels: pr/no-changelog, backport/1.17

#19202 mesh: add more validations to Destinations resource
  command/resource/testdata/nested_data.hcl
  internal/catalog/exports.go
  internal/catalog/internal/types/failover_policy.go
  internal/catalog/internal/types/service.go
  internal/catalog/internal/types/service_endpoints.go
  internal/catalog/internal/types/validators.go
  internal/catalog/internal/types/validators_test.go
  internal/catalog/internal/types/workload.go
  internal/mesh/internal/controllers/sidecarproxy/controller_test.go
  internal/mesh/internal/types/destinations.go
  internal/mesh/internal/types/destinations_test.go
  internal/mesh/internal/types/errors.go
  internal/resource/errors.go
Labels: pr/no-changelog, backport/1.17

#19211 Backport of mesh: add more validations to Destinations resource into release/1.17.x
  command/resource/testdata/nested_data.hcl
  internal/catalog/exports.go
  internal/catalog/internal/types/failover_policy.go
  internal/catalog/internal/types/service.go
  internal/catalog/internal/types/service_endpoints.go
  internal/catalog/internal/types/validators.go
  internal/catalog/internal/types/validators_test.go
  internal/catalog/internal/types/workload.go
  internal/mesh/internal/controllers/sidecarproxy/controller_test.go
  internal/mesh/internal/types/destinations.go
  internal/mesh/internal/types/destinations_test.go
  internal/mesh/internal/types/errors.go
  internal/resource/errors.go
Labels: theme/cli

#19143 catalog, mesh: implement missing ACL hooks
  agent/grpc-external/services/resource/read.go
  internal/auth/internal/types/computed_traffic_permissions.go
  internal/auth/internal/types/traffic_permissions.go
  internal/auth/internal/types/workload_identity.go
  internal/auth/internal/types/workload_identity_test.go
  internal/catalog/catalogtest/helpers/acl_hooks_test_helpers.go
  internal/catalog/exports.go
  internal/catalog/internal/controllers/nodehealth/controller_test.go
  internal/catalog/internal/testhelpers/acl_hooks_test_helpers.go
  internal/catalog/internal/types/acl_hooks.go
  internal/catalog/internal/types/dns_policy.go
  internal/catalog/internal/types/dns_policy_test.go
  internal/catalog/internal/types/failover_policy.go
  internal/catalog/internal/types/failover_policy_test.go
  internal/catalog/internal/types/health_checks.go
  internal/catalog/internal/types/health_checks_test.go
  internal/catalog/internal/types/health_status.go
  internal/catalog/internal/types/health_status_test.go
  internal/catalog/internal/types/node.go
  internal/catalog/internal/types/node_test.go
  internal/catalog/internal/types/service.go
  internal/catalog/internal/types/service_endpoints.go
  internal/catalog/internal/types/service_endpoints_test.go
  internal/catalog/internal/types/service_test.go
  internal/catalog/internal/types/types.go
  internal/catalog/internal/types/types_test.go
  internal/catalog/internal/types/virtual_ips.go
  internal/catalog/internal/types/virtual_ips_test.go
  internal/catalog/internal/types/workload.go
  internal/catalog/internal/types/workload_selecting.go
  internal/catalog/internal/types/workload_test.go
  internal/mesh/internal/mappers/workloadselectionmapper/workload_selection_mapper.go
  internal/mesh/internal/types/destination_policy.go
  internal/mesh/internal/types/destinations.go
  internal/mesh/internal/types/destinations_configuration.go
  internal/mesh/internal/types/destinations_configuration_test.go
  internal/mesh/internal/types/destinations_test.go
  internal/mesh/internal/types/proxy_configuration.go
  internal/mesh/internal/types/proxy_configuration_test.go
  internal/mesh/internal/types/proxy_state_template.go
  internal/mesh/internal/types/types.go
  internal/mesh/internal/types/types_test.go
  internal/mesh/internal/types/xroute.go
  internal/mesh/internal/types/xroute_test.go
  internal/resource/acls.go
  internal/resource/demo/demo.go
  internal/resource/errors.go
  internal/resource/registry.go
  internal/resource/resourcetest/acls.go
  internal/resource/resourcetest/tenancy.go
Labels: pr/no-changelog, backport/1.17

#19212 Backport of catalog, mesh: implement missing ACL hooks into release/1.17.x
  agent/grpc-external/services/resource/read.go
  internal/auth/internal/types/computed_traffic_permissions.go
  internal/auth/internal/types/traffic_permissions.go
  internal/auth/internal/types/workload_identity.go
  internal/auth/internal/types/workload_identity_test.go
  internal/catalog/catalogtest/helpers/acl_hooks_test_helpers.go
  internal/catalog/exports.go
  internal/catalog/internal/controllers/nodehealth/controller_test.go
  internal/catalog/internal/testhelpers/acl_hooks_test_helpers.go
  internal/catalog/internal/types/acl_hooks.go
  internal/catalog/internal/types/dns_policy.go
  internal/catalog/internal/types/dns_policy_test.go
  internal/catalog/internal/types/failover_policy.go
  internal/catalog/internal/types/failover_policy_test.go
  internal/catalog/internal/types/health_checks.go
  internal/catalog/internal/types/health_checks_test.go
  internal/catalog/internal/types/health_status.go
  internal/catalog/internal/types/health_status_test.go
  internal/catalog/internal/types/node.go
  internal/catalog/internal/types/node_test.go
  internal/catalog/internal/types/service.go
  internal/catalog/internal/types/service_endpoints.go
  internal/catalog/internal/types/service_endpoints_test.go
  internal/catalog/internal/types/service_test.go
  internal/catalog/internal/types/types.go
  internal/catalog/internal/types/types_test.go
  internal/catalog/internal/types/virtual_ips.go
  internal/catalog/internal/types/virtual_ips_test.go
  internal/catalog/internal/types/workload.go
  internal/catalog/internal/types/workload_selecting.go
  internal/catalog/internal/types/workload_test.go
  internal/mesh/internal/mappers/workloadselectionmapper/workload_selection_mapper.go
  internal/mesh/internal/types/destination_policy.go
  internal/mesh/internal/types/destinations.go
  internal/mesh/internal/types/destinations_configuration.go
  internal/mesh/internal/types/destinations_configuration_test.go
  internal/mesh/internal/types/destinations_test.go
  internal/mesh/internal/types/proxy_configuration.go
  internal/mesh/internal/types/proxy_configuration_test.go
  internal/mesh/internal/types/proxy_state_template.go
  internal/mesh/internal/types/types.go
  internal/mesh/internal/types/types_test.go
  internal/mesh/internal/types/xroute.go
  internal/mesh/internal/types/xroute_test.go
  internal/resource/acls.go
  internal/resource/demo/demo.go
  internal/resource/errors.go
  internal/resource/registry.go
  internal/resource/resourcetest/acls.go
  internal/resource/resourcetest/tenancy.go
Labels: theme/cli

#19187 NET-5073 - ProxyConfiguration: implement various connection options
  internal/mesh/internal/controllers/sidecarproxy/builder/expose_paths.go
  internal/mesh/internal/controllers/sidecarproxy/builder/local_app.go
  internal/mesh/internal/controllers/sidecarproxy/builder/local_app_test.go
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/source/local-and-inbound-connections.golden
  proto-public/pbmesh/v2beta1/connection.pb.go
  proto-public/pbmesh/v2beta1/connection.proto
Labels: pr/no-changelog, backport/1.17

#19177 mesh: add xRoute ACL hook tenancy tests
  internal/mesh/internal/types/xroute_test.go
  internal/resource/resourcetest/acls.go
Labels: pr/no-changelog, pr/no-metrics-test, backport/1.17

#19218 resource: enforce lowercase resource names
  .changelog/19218.txt
  agent/grpc-external/services/resource/delete.go
  agent/grpc-external/services/resource/delete_test.go
  agent/grpc-external/services/resource/list.go
  agent/grpc-external/services/resource/list_by_owner.go
  agent/grpc-external/services/resource/list_by_owner_test.go
  agent/grpc-external/services/resource/list_test.go
  agent/grpc-external/services/resource/read_test.go
  agent/grpc-external/services/resource/server.go
  agent/grpc-external/services/resource/server_test.go
  agent/grpc-external/services/resource/watch.go
  agent/grpc-external/services/resource/watch_test.go
  agent/grpc-external/services/resource/write_status.go
  agent/grpc-external/services/resource/write_status_test.go
  agent/grpc-external/services/resource/write_test.go
  internal/mesh/internal/controllers/xds/controller_test.go
  internal/resource/demo/controller.go
  internal/resource/demo/demo.go
  internal/resource/http/http_test.go
  internal/resource/resource.go
  internal/resource/tenancy.go
  internal/tenancy/internal/types/namespace_test.go
Labels: pr/no-changelog, pr/no-backport

#19178 mesh: add DestinationPolicy ACL hook tenancy tests
  internal/mesh/internal/types/destination_policy_test.go
  internal/resource/resourcetest/acls.go
Labels: pr/no-changelog, pr/no-metrics-test, backport/1.17

#19217 Backport of Relplat 897 copywrite bot workarounds into release/1.17.x
  Makefile
  api/.copywrite.hcl
  api/config_entry_routes_test.go
  api/config_entry_status_test.go
  api/internal.go
  api/internal_test.go
  api/operator_audit.go
  build-support/scripts/copywrite-exceptions.sh
  sdk/.copywrite.hcl
  sdk/testutil/retry/counter.go
  sdk/testutil/retry/timer.go
Labels: theme/api

#19179 catalog: add FailoverPolicy ACL hook tenancy test
  internal/catalog/internal/types/failover_policy_test.go
Labels: pr/no-changelog, pr/no-metrics-test, backport/1.17

#19221 Backport of mesh: add DestinationPolicy ACL hook tenancy tests into release/1.17.x
  internal/mesh/internal/types/destination_policy_test.go
  internal/resource/resourcetest/acls.go
Labels: theme/cli

#19222 Add reason why port 53 is not used by default
  website/content/docs/services/discovery/dns-configuration.mdx
Labels: type/docs, pr/no-changelog, backport/1.14, backport/1.15, backport/1.16, backport/1.17

#19227 v2tenancy: rename v1alpha1 -> v2beta1
  internal/catalog/catalogtest/run_test.go
  internal/catalog/catalogtest/test_integration_v2beta1.go
  internal/tenancy/exports.go
  internal/tenancy/internal/types/namespace.go
  internal/tenancy/internal/types/namespace_test.go
  internal/tenancy/internal/types/types.go
  proto-public/pbtenancy/v1alpha1/namespace.pb.go
  proto-public/pbtenancy/v2beta1/namespace.pb.binary.go
  proto-public/pbtenancy/v2beta1/namespace.pb.go
  proto-public/pbtenancy/v2beta1/namespace.proto
  proto-public/pbtenancy/v2beta1/namespace_deepcopy.gen.go
  proto-public/pbtenancy/v2beta1/namespace_json.gen.go
  proto-public/pbtenancy/v2beta1/resource_types.gen.go
  test/integration/consul-container/test/catalog/catalog_test.go
Labels: pr/no-changelog, pr/no-backport

#19225 [NET-5944] security: Update Go version to 1.20.10 and `x/net` to 0.17.0
  .changelog/19225.txt
  .github/workflows/build.yml
  api/go.mod
  api/go.sum
  build-support/docker/Build-Go.dockerfile
  envoyextensions/go.mod
  envoyextensions/go.sum
  go.mod
  go.sum
  proto-public/go.mod
  proto-public/go.sum
  sdk/go.mod
  sdk/go.sum
  test-integ/go.mod
  test-integ/go.sum
  test/integration/connect/envoy/test-sds-server/go.mod
  test/integration/connect/envoy/test-sds-server/go.sum
  test/integration/consul-container/go.mod
  test/integration/consul-container/go.sum
  testing/deployer/go.mod
  testing/deployer/go.sum
  troubleshoot/go.mod
  troubleshoot/go.sum
Labels: theme/api, type/ci, pr/dependencies, theme/contributing, theme/security, backport/1.14, backport/1.15, backport/1.16, backport/1.17

#19235 Backport of [NET-5944] security: Update Go version to 1.20.10 and `x/net` to 0.17.0 into release/1.17.x
  .changelog/19225.txt
  .github/workflows/build.yml
  api/go.mod
  api/go.sum
  build-support/docker/Build-Go.dockerfile
  envoyextensions/go.mod
  envoyextensions/go.sum
  go.mod
  go.sum
  proto-public/go.mod
  proto-public/go.sum
  sdk/go.mod
  sdk/go.sum
  test-integ/go.mod
  test-integ/go.sum
  test/integration/connect/envoy/test-sds-server/go.mod
  test/integration/connect/envoy/test-sds-server/go.sum
  test/integration/consul-container/go.mod
  test/integration/consul-container/go.sum
  testing/deployer/go.mod
  testing/deployer/go.sum
  troubleshoot/go.mod
  troubleshoot/go.sum
Labels: theme/api, type/ci, pr/dependencies, theme/contributing

#19239 NET-6097 - sidecar proxy controller - give name to first failover policy target
  internal/mesh/internal/controllers/sidecarproxy/builder/destinations.go
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/mixed-multi-destination.golden
Labels: pr/no-changelog, backport/1.17

#19226 Cc 5545: Upgrade HDS packages and modifiers
  ui/packages/consul-lock-sessions/app/components/consul/lock-session/list/index.hbs
  ui/packages/consul-peerings/app/components/consul/peer/address/list/index.hbs
  ui/packages/consul-ui/app/components/code-editor/README.mdx
  ui/packages/consul-ui/app/components/code-editor/index.hbs
  ui/packages/consul-ui/app/components/code-editor/index.js
  ui/packages/consul-ui/app/components/consul-copy-button/README.mdx
  ui/packages/consul-ui/app/components/consul-copy-button/chart.xstate.js
  ui/packages/consul-ui/app/components/consul-copy-button/index.hbs
  ui/packages/consul-ui/app/components/consul-copy-button/index.js
  ui/packages/consul-ui/app/components/consul-copy-button/index.scss
  ui/packages/consul-ui/app/components/consul-copy-button/layout.scss
  ui/packages/consul-ui/app/components/consul-copy-button/skin.scss
  ui/packages/consul-ui/app/components/consul/exposed-path/list/index.hbs
  ui/packages/consul-ui/app/components/consul/health-check/list/index.hbs
  ui/packages/consul-ui/app/components/consul/node/list/index.hbs
  ui/packages/consul-ui/app/components/consul/token/list/index.hbs
  ui/packages/consul-ui/app/components/consul/upstream-instance/list/index.hbs
  ui/packages/consul-ui/app/components/consul/upstream/list/index.hbs
  ui/packages/consul-ui/app/components/copyable-code/index.hbs
  ui/packages/consul-ui/app/components/disclosure-menu/menu/index.hbs
  ui/packages/consul-ui/app/components/horizontal-kv-list/README.mdx
  ui/packages/consul-ui/app/components/menu/index.hbs
  ui/packages/consul-ui/app/modifiers/aria-menu.js
  ui/packages/consul-ui/app/modifiers/css-prop.js
  ui/packages/consul-ui/app/modifiers/did-upsert.js
  ui/packages/consul-ui/app/modifiers/notification.js
  ui/packages/consul-ui/app/modifiers/on-outside.js
  ui/packages/consul-ui/app/modifiers/style.js
  ui/packages/consul-ui/app/modifiers/validate.js
  ui/packages/consul-ui/app/modifiers/with-copyable.js
  ui/packages/consul-ui/app/styles/components.scss
  ui/packages/consul-ui/app/templates/dc/nodes/show.hbs
  ui/packages/consul-ui/app/templates/dc/services/instance.hbs
  ui/packages/consul-ui/package.json
  ui/packages/consul-ui/translations/components/consul-copy-button/en-us.yaml
  ui/yarn.lock
Labels: theme/ui, pr/no-changelog, backport/1.17

#19246 [NET-5810] CE changes for multiple virtual hosts
  agent/xds/listeners_apigateway.go
  agent/xds/testdata/routes/api-gateway-with-multiple-hostnames.latest.golden
Labels: theme/envoy/xds, pr/no-changelog, pr/no-docs, backport/1.17

#19249 Downgrading node on CI to support v1.15.X
  .github/workflows/frontend.yml
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#19119 Net 4893- Ensure we're testing all the latest versions of Vault/Nomad
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing, theme/consul-nomad, theme/consul-vault, pr/no-changelog, backport/1.17

#19251 Backport of Net 4893- Ensure we're testing all the latest versions of Vault/Nomad into release/1.17.x
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing

#19105 docs: Fix example control-plane-request-limit HCL and JSON
  website/content/docs/connect/config-entries/control-plane-request-limit.mdx
Labels: type/docs, pr/no-changelog, backport/1.16, backport/1.17

#19254 Backport of docs: Fix example control-plane-request-limit HCL and JSON into release/1.16.x
  website/content/docs/connect/config-entries/control-plane-request-limit.mdx
Labels: type/docs

#19255 Backport of docs: Fix example control-plane-request-limit HCL and JSON into release/1.17.x
  website/content/docs/connect/config-entries/control-plane-request-limit.mdx
Labels: type/docs

#19253 test: add 1.17 nightly integrations test
  .github/workflows/nightly-test-integrations-1.17.x.yml
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#19257 fix expose paths
  internal/mesh/internal/controllers/sidecarproxy/builder/expose_paths.go
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/source/l7-expose-paths.golden
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/source/local-and-inbound-connections.golden
Labels: pr/no-changelog, backport/1.17

#19258 [Backport 1.17] fix expose paths
  internal/mesh/internal/controllers/sidecarproxy/builder/expose_paths.go
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/source/l7-expose-paths.golden
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/source/local-and-inbound-connections.golden
Labels: pr/no-backport

#19262 docs: Fix multi-port install
  website/content/docs/k8s/multiport/configure.mdx
Labels: type/docs, pr/no-changelog, backport/1.17

#19230 Prevent circular dependencies between v2 resources and generate a mermaid diagram with their dependencies
  agent/consul/server.go
  agent/consul/server_test.go
  agent/consul/testdata/v2-resource-dependencies.md
  internal/controller/dependencies.go
  internal/controller/dependencies_test.go
  internal/controller/testdata/dependencies.golden
Labels: pr/no-changelog, pr/no-backport

#19265 backport: docs: Fix multi-port install (#19262)
  website/content/docs/k8s/multiport/configure.mdx
Labels: type/docs, pr/no-changelog, pr/no-backport

#19278 build(docker): always publish full and minor version tags for dev images
  .github/workflows/build.yml
Labels: type/ci, theme/contributing, pr/no-changelog, backport/1.14, backport/1.15, backport/1.16, backport/1.17

#19282 Backport of build(docker): always publish full and minor version tags for dev images into release/1.17.x
  .github/workflows/build.yml
Labels: type/ci, theme/contributing

#19284 Backport of build(docker): always publish full and minor version tags…
  .github/workflows/build.yml
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#19286 fix nightly integration test: envoy version and n-2 version
  .github/workflows/nightly-test-integrations-1.17.x.yml
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#19283 [NET-6221] Ensure LB policy set for locality-aware routing (CE)
  agent/xds/endpoints.go
Labels: theme/envoy/xds, pr/no-changelog, backport/1.17

#19277 fix: allow snake case keys for ip based rate limit config entry
  .changelog/_7406.txt
  api/config_entry_rate_limit_ip.go
Labels: theme/api, pr/no-changelog, backport/1.16, backport/1.17

#19293 Backport of fix: allow snake case keys for ip based rate limit config entry into release/1.17.x
  .changelog/_7406.txt
  api/config_entry_rate_limit_ip.go
Labels: theme/api

#19288 reformatted the JSON schema server conf ref
  website/content/docs/ecs/reference/consul-server-json.mdx
Labels: type/docs, pr/no-changelog, pr/no-metrics-test, backport/1.17

#19294 Backport of reformatted the JSON schema server conf ref into release/1.17.x
  website/content/docs/ecs/reference/consul-server-json.mdx
Labels: type/docs

#19292 Backport of fix: allow snake case keys for ip based rate limit config entry into release/1.16.x
  .changelog/_7406.txt
  api/config_entry_rate_limit_ip.go
Labels: theme/api

#19260 acls,catalog,mesh: properly authorize workload selectors on writes
  acl/MockAuthorizer.go
  acl/acl_test.go
  acl/authorizer.go
  acl/chained_authorizer.go
  acl/chained_authorizer_test.go
  acl/policy_authorizer.go
  acl/policy_authorizer_test.go
  acl/static_authorizer.go
  internal/catalog/internal/testhelpers/acl_hooks_test_helpers.go
  internal/catalog/internal/types/acl_hooks.go
Labels: theme/acls, pr/no-changelog, backport/1.17

#19296 Backport of acls,catalog,mesh: properly authorize workload selectors on writes into release/1.17.x
  acl/MockAuthorizer.go
  acl/acl_test.go
  acl/authorizer.go
  acl/chained_authorizer.go
  acl/chained_authorizer_test.go
  acl/policy_authorizer.go
  acl/policy_authorizer_test.go
  acl/static_authorizer.go
  internal/catalog/internal/testhelpers/acl_hooks_test_helpers.go
  internal/catalog/internal/types/acl_hooks.go
Labels: theme/acls

#19299 NET-6239: Temporarily disable verify envoy check
  .github/scripts/verify_envoy_version.sh
  .github/workflows/verify-envoy-version.yml
Labels: type/ci, theme/contributing, pr/no-changelog, backport/1.17

#19300 Backport of NET-6239: Temporarily disable verify envoy check into release/1.17.x
  .github/scripts/verify_envoy_version.sh
  .github/workflows/verify-envoy-version.yml
Labels: type/ci, theme/contributing

#19276 Update supported Envoy versions
  .changelog/19276.txt
  .github/workflows/nightly-test-integrations-1.15.x.yml
  .github/workflows/nightly-test-integrations-1.16.x.yml
  .github/workflows/nightly-test-integrations-1.17.x.yml
  .github/workflows/nightly-test-integrations.yml
  .github/workflows/test-integrations-windows.yml
  .github/workflows/test-integrations.yml
  envoyextensions/xdscommon/envoy_versioning_test.go
  envoyextensions/xdscommon/proxysupport.go
  website/content/docs/connect/proxies/envoy.mdx
Labels: type/docs, type/ci, theme/contributing, pr/no-backport

#19298 mesh: provide missing domain to route configurations in ProxyStateTemplate
  internal/mesh/internal/controllers/sidecarproxy/builder/destinations.go
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/mixed-multi-destination.golden
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-and-l7-multiple-implicit-destinations-tproxy.golden
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-and-l7-single-implicit-destination-tproxy.golden
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-and-l7-single-implicit-destination-with-multiple-workloads-tproxy.golden
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/source/local-and-inbound-connections.golden
Labels: pr/no-changelog, backport/1.17

#19271 release/1.14.x - Update supported Envoy versions
  .changelog/19271.txt
  .github/workflows/test-integrations.yml
  agent/xds/envoy_versioning_test.go
  agent/xds/proxysupport/proxysupport.go
  website/content/docs/connect/proxies/envoy.mdx
Labels: type/docs, type/ci, theme/envoy/xds, theme/contributing, pr/no-backport

#19272 release/1.15.x - Update supported Envoy versions
  .changelog/19272.txt
  .github/workflows/test-integrations.yml
  envoyextensions/xdscommon/envoy_versioning_test.go
  envoyextensions/xdscommon/proxysupport.go
  website/content/docs/connect/proxies/envoy.mdx
Labels: type/docs, type/ci, theme/contributing, pr/no-backport

#19273 release/1.16.x - Update supported Envoy versions
  .changelog/19273.txt
  .github/workflows/test-integrations.yml
  envoyextensions/xdscommon/envoy_versioning_test.go
  envoyextensions/xdscommon/proxysupport.go
  website/content/docs/connect/proxies/envoy.mdx
Labels: type/docs, type/ci, theme/contributing, pr/no-backport

#19274 release/1.17.x - Update supported Envoy versions
  .changelog/19274.txt
  .github/workflows/nightly-test-integrations-1.15.x.yml
  .github/workflows/nightly-test-integrations-1.16.x.yml
  .github/workflows/nightly-test-integrations.yml
  .github/workflows/test-integrations-windows.yml
  .github/workflows/test-integrations.yml
  envoyextensions/xdscommon/envoy_versioning_test.go
  envoyextensions/xdscommon/proxysupport.go
  website/content/docs/connect/proxies/envoy.mdx
Labels: type/docs, type/ci, theme/contributing, pr/no-backport

#19301 [1.17.0 backport] acls,catalog,mesh: properly authorize workload selectors on writes
  acl/MockAuthorizer.go
  acl/acl_test.go
  acl/authorizer.go
  acl/chained_authorizer.go
  acl/chained_authorizer_test.go
  acl/policy_authorizer.go
  acl/policy_authorizer_test.go
  acl/static_authorizer.go
  internal/catalog/internal/testhelpers/acl_hooks_test_helpers.go
  internal/catalog/internal/types/acl_hooks.go
Labels: theme/acls, pr/no-changelog, pr/no-backport

#19275 release/1.17.0 - Update supported Envoy versions
  .changelog/19275.txt
  .github/workflows/nightly-test-integrations-1.15.x.yml
  .github/workflows/nightly-test-integrations-1.16.x.yml
  .github/workflows/nightly-test-integrations.yml
  .github/workflows/test-integrations-windows.yml
  .github/workflows/test-integrations.yml
  envoyextensions/xdscommon/envoy_versioning_test.go
  envoyextensions/xdscommon/proxysupport.go
  website/content/docs/connect/proxies/envoy.mdx
Labels: type/docs, type/ci, theme/contributing, pr/no-backport

#19303 enable verify envoy script
  .github/workflows/verify-envoy-version.yml
Labels: type/ci, theme/contributing, pr/no-changelog, backport/1.17

#19305 Backport of mesh: provide missing domain to route configurations in ProxyStateTemplate into release/1.17.0
  internal/mesh/internal/controllers/sidecarproxy/builder/destinations.go
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/mixed-multi-destination.golden
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-and-l7-multiple-implicit-destinations-tproxy.golden
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-and-l7-single-implicit-destination-tproxy.golden
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/destination/multiport-l4-and-l7-single-implicit-destination-with-multiple-workloads-tproxy.golden
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/source/local-and-inbound-connections.golden
Labels: pr/no-changelog, pr/no-backport

#19285 Vault CA bugfixes
  .changelog/19285.txt
  agent/connect/ca/provider_vault.go
  agent/connect/ca/provider_vault_test.go
Labels: theme/connect, backport/1.15, backport/1.16, backport/1.17

#19306 Backout Envoy 1.28.0
  .changelog/19276.txt
  .changelog/19306.txt
  .github/workflows/nightly-test-integrations.yml
  .github/workflows/test-integrations-windows.yml
  .github/workflows/test-integrations.yml
  envoyextensions/xdscommon/envoy_versioning_test.go
  envoyextensions/xdscommon/proxysupport.go
Labels: type/ci, theme/contributing, pr/no-docs, pr/no-backport

#19309 Backport of Vault CA bugfixes into release/1.17.x
  .changelog/19285.txt
  agent/connect/ca/provider_vault.go
  agent/connect/ca/provider_vault_test.go
Labels: theme/connect

#19315 skip envoy version check in ci
  .github/scripts/verify_envoy_version.sh
  .github/workflows/verify-envoy-version.yml
Labels: type/ci, theme/contributing, pr/no-changelog, backport/1.16, backport/1.17

#19220 Tenancy Bridge v2
  agent/consul/server.go
  agent/grpc-external/services/resource/list_by_owner.go
  agent/grpc-external/services/resource/read.go
  agent/grpc-external/services/resource/server.go
  agent/grpc-external/services/resource/server_test.go
  agent/grpc-external/services/resource/testing/testing.go
  agent/grpc-external/services/resource/testing/testing_ce.go
  agent/grpc-external/services/resource/write.go
  agent/grpc-external/services/resource/write_status.go
  internal/resource/http/http_test.go
  internal/resource/tenancy.go
  internal/tenancy/exports.go
  internal/tenancy/internal/bridge/tenancy_bridge.go
  internal/tenancy/internal/bridge/tenancy_bridge_ce.go
  internal/tenancy/internal/types/types_test.go
  internal/tenancy/tenancytest/namespace_test.go
Labels: pr/no-changelog, pr/no-backport
