Repository hashicorp/consul, pull requests merged in 2023-05, with the labels that each got.

#17201 Fix broken lightstep link
  website/content/docs/integrate/partnerships.mdx
Labels: pr/no-changelog, pr/no-backport

#17207 Use auth context when evaluating permissions for service config resolution
  agent/proxycfg-glue/resolved_service_config.go
Labels: pr/no-changelog, backport/1.14, backport/1.15

#17138 enable auto-tidy expired issuers in vault (as CA)
  .changelog/17138.txt
  agent/connect/ca/provider_vault.go
  agent/connect/ca/provider_vault_test.go
  agent/connect/ca/testing.go
Labels: type/enhancement, theme/connect, theme/consul-vault, theme/certificates, pr/no-docs, pr/no-backport

#16982 controller: make the `WorkQueue` generic
  agent/consul/controller/controller.go
  agent/consul/controller/controller_test.go
  agent/consul/controller/queue/defer.go
  agent/consul/controller/queue/queue.go
  agent/consul/controller/queue/rate.go
  agent/consul/controller/queue/rate_test.go
  agent/consul/controller/queue_test.go
  agent/consul/gateways/controller_gateways_test.go
Labels: pr/no-changelog

#17177 fix: integration tests
  test/integration/consul-container/libs/agent/builder.go
  test/integration/consul-container/libs/agent/container.go
  test/integration/consul-container/libs/service/assets/Dockerfile-consul-envoy
  test/integration/consul-container/libs/service/connect.go
  test/integration/consul-container/libs/service/gateway.go
  test/integration/consul-container/libs/utils/version.go
  test/integration/consul-container/libs/utils/version_oss.go
  test/integration/consul-container/test/upgrade/healthcheck_test.go
Labels: pr/no-changelog, pr/no-backport

#17186 upgrade test: use docker.mirror.hashicorp.services to avoid docker login
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing, pr/no-changelog, backport/1.15

#17190 List resources by owner
  agent/grpc-external/services/resource/list_by_owner.go
  agent/grpc-external/services/resource/list_by_owner_test.go
  agent/grpc-external/services/resource/mock_Backend.go
  agent/grpc-middleware/rate_limit_mappings.gen.go
  internal/storage/conformance/conformance.go
  internal/storage/inmem/backend.go
  internal/storage/inmem/store.go
  internal/storage/raft/backend.go
  internal/storage/storage.go
  proto-public/pbresource/resource.pb.binary.go
  proto-public/pbresource/resource.pb.go
  proto-public/pbresource/resource.proto
  proto-public/pbresource/resource_grpc.pb.go
Labels: pr/no-changelog, pr/no-backport

#17229 docs: correct misspelling
  website/content/docs/connect/dev.mdx
Labels: type/docs, pr/no-changelog, pr/no-backport

#17225 Register new catalog & mesh protobuf types with the resource registry
  agent/consul/server.go
  internal/catalog/exports.go
  internal/catalog/internal/types/dns_policy.go
  internal/catalog/internal/types/health_checks.go
  internal/catalog/internal/types/health_status.go
  internal/catalog/internal/types/node.go
  internal/catalog/internal/types/service.go
  internal/catalog/internal/types/service_endpoints.go
  internal/catalog/internal/types/types.go
  internal/catalog/internal/types/types_test.go
  internal/catalog/internal/types/virtual_ips.go
  internal/catalog/internal/types/workload.go
  internal/mesh/exports.go
  internal/mesh/internal/types/proxy_configuration.go
  internal/mesh/internal/types/types.go
  internal/mesh/internal/types/types_test.go
  internal/mesh/internal/types/upstreams.go
Labels: pr/no-changelog, pr/no-backport

#17166 ci: remove test splitting for compatibility tests
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing, pr/no-changelog, backport/1.13, backport/1.14, backport/1.15

#17249 chore(ci): fix backport assistant branch creation race
  .github/workflows/backport-assistant.yml
Labels: type/ci, theme/contributing, pr/no-changelog, backport/1.13, backport/1.14, backport/1.15

#17251 Backport of chore(ci): fix backport assistant branch creation race into release/1.13.x
  .github/workflows/backport-assistant.yml
Labels: type/ci, theme/contributing

#17252 Backport of chore(ci): fix backport assistant branch creation race into release/1.14.x
  .github/workflows/backport-assistant.yml
Labels: type/ci, theme/contributing

#17253 Backport of chore(ci): fix backport assistant branch creation race into release/1.15.x
  .github/workflows/backport-assistant.yml
Labels: type/ci, theme/contributing

#17242 Backport of upgrade test: use docker.mirror.hashicorp.services to avoid docker login into release/1.15.x
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing

#17254 manual backport of ci: remove test splitting for compatibility tests into release/1.14.x
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#17255 manual backport of ci: remove test splitting for compatibility tests into release/1.15.x
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#17069 Controller Implementation 🏗
  agent/consul/server.go
  internal/controller/api.go
  internal/controller/api_test.go
  internal/controller/controller.go
  internal/controller/doc.go
  internal/controller/lease.go
  internal/controller/manager.go
  internal/resource/demo/controller.go
  internal/resource/demo/controller_test.go
  internal/resource/demo/demo.go
Labels: theme/telemetry, theme/internals

#17262 Revert "ci: remove test splitting for compatibility tests"
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing, pr/no-changelog, backport/1.13, backport/1.14, backport/1.15

#17168 controller: deduplicate items in the queue 👯‍♀️
  agent/consul/controller/queue/defer.go
  agent/consul/controller/queue/queue.go
  agent/consul/controller/queue/rate.go
  agent/consul/controller/queue/rate_test.go
  agent/consul/controller/queue_test.go
  agent/consul/controller/reconciler.go
  internal/controller/api.go
  internal/controller/controller.go
Labels: pr/no-changelog

#17264 Backport of Revert "ci: remove test splitting for compatibility tests" into release/1.14.x
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing

#17241 Fix multiple issues related to proxycfg health queries.
  .changelog/17241.txt
  agent/consul/health_endpoint.go
  agent/consul/health_endpoint_test.go
  agent/proxycfg/state_test.go
  agent/proxycfg/upstreams.go
Labels: backport/1.13, backport/1.14, backport/1.15

#17224 resource: add helpers for more efficiently comparing IDs etc
  agent/grpc-external/services/resource/delete.go
  agent/grpc-external/services/resource/write.go
  internal/controller/controller.go
  internal/resource/demo/controller.go
  internal/resource/equality.go
  internal/resource/equality_test.go
  internal/resource/status.go
  internal/resource/status_test.go
Labels: pr/no-changelog

#17204 Hash namespace+proxy ID when creating socket path
  agent/proxycfg/connect_proxy.go
  agent/proxycfg/state_test.go
  agent/structs/config_entry.go
  agent/structs/config_entry_test.go
  agent/structs/structs.go
  agent/structs/structs_test.go
  agent/xds/testdata/listeners/hcp-metrics.latest.golden
  command/connect/envoy/bootstrap_config.go
  command/connect/envoy/bootstrap_config_test.go
  command/connect/envoy/testdata/hcp-metrics.golden
Labels: theme/cli, pr/no-changelog, backport/1.15

#17272 Backport of Post a PR comment if the backport runner fails into release/1.13.x
  .github/workflows/backport-assistant.yml
Labels: type/ci, theme/contributing

#17269 Fix multiple issues related to proxycfg health queries. (#17241)
  .changelog/17241.txt
  agent/consul/health_endpoint.go
  agent/consul/health_endpoint_test.go
  agent/proxycfg/upstreams.go
Labels: pr/no-changelog, pr/no-backport

#17256 Reaper controller for cascading deletes of owner resources
  agent/consul/server.go
  agent/grpc-external/services/resource/write_status.go
  agent/grpc-external/services/resource/write_status_test.go
  internal/resource/reaper/controller.go
  internal/resource/reaper/controller_test.go
  proto-public/pbresource/resource.pb.go
  proto-public/pbresource/resource.proto
  proto-public/pbresource/resource_grpc.pb.go
Labels: pr/no-changelog, pr/no-backport

#17236 snapshot: some improvments to the snapshot process
  .changelog/17236.txt
  agent/consul/server.go
  snapshot/snapshot.go
  website/content/commands/snapshot/save.mdx
Labels: type/docs, pr/no-changelog, backport/1.14, backport/1.15

#17273 Backport of Post a PR comment if the backport runner fails into release/1.14.x
  .github/workflows/backport-assistant.yml
Labels: type/ci, theme/contributing

#17158 Routes for API Gateway
  agent/consul/discoverychain/gateway.go
  agent/proxycfg/api_gateway.go
  agent/proxycfg/snapshot.go
  agent/xds/clusters.go
  agent/xds/endpoints.go
  agent/xds/routes.go
  test/integration/connect/envoy/case-api-gateway-http-hostnames/verify.bats
  test/integration/connect/envoy/case-api-gateway-http-simple/verify.bats
  test/integration/connect/envoy/case-api-gateway-http-tls-overlapping-hosts/verify.bats
  test/integration/connect/envoy/case-api-gateway-tcp-simple/verify.bats
  test/integration/connect/envoy/case-api-gateway-tcp-tls-overlapping-hosts/verify.bats
Labels: theme/envoy/xds

#17265 Backport of Revert "ci: remove test splitting for compatibility tests" into release/1.15.x
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing

#17277 Backport of snapshot: some improvments to the snapshot process into release/1.15.x
  .changelog/17236.txt
  agent/consul/server.go
  snapshot/snapshot.go
  website/content/commands/snapshot/save.mdx
Labels: type/docs

#17278 Fix ent bug caused by #17241.
  agent/consul/health_endpoint.go
Labels: pr/no-changelog, backport/1.13, backport/1.14, backport/1.15

#17208 backport PR 15979 to 1.15.x
  .changelog/15979.txt
  GNUmakefile
  agent/consul/config_endpoint_test.go
  agent/proxycfg/proxycfg.deepcopy.go
  agent/structs/config_entry.go
  agent/structs/config_entry_test.go
  agent/structs/structs.deepcopy.go
  agent/structs/structs.go
  agent/xds/clusters_test.go
  agent/xds/config.go
  agent/xds/testdata/clusters/custom-passive-healthcheck.latest.golden
  api/config_entry.go
  api/config_entry_test.go
  proto/pbconfigentry/config_entry.gen.go
  proto/pbconfigentry/config_entry.pb.go
  proto/pbconfigentry/config_entry.proto
  test/integration/connect/envoy/case-http/verify.bats
  test/integration/connect/envoy/case-upstream-config/service_s1.hcl
  test/integration/connect/envoy/case-upstream-config/verify.bats
Labels: theme/api, theme/envoy/xds, pr/no-backport

#17275 resource: optionally compare timestamps in `EqualStatus`
  internal/resource/demo/controller.go
  internal/resource/equality.go
  internal/resource/equality_test.go
Labels: pr/no-changelog

#17213 resource: add missing validation to the `List` and `WatchList` endpoints
  agent/grpc-external/services/resource/list.go
  agent/grpc-external/services/resource/list_test.go
  agent/grpc-external/services/resource/watch.go
  agent/grpc-external/services/resource/watch_test.go
Labels: pr/no-changelog

#17284 Backport of Fix ent bug caused by #17241. (#17278)
  agent/consul/health_endpoint.go
Labels: pr/no-changelog, pr/no-backport

#17287 backport pr 15979 into 1.14.x
  .changelog/15979.txt
  GNUmakefile
  agent/consul/config_endpoint_test.go
  agent/structs/config_entry.go
  agent/structs/config_entry_test.go
  agent/structs/structs.deepcopy.go
  agent/structs/structs.go
  agent/xds/clusters_test.go
  agent/xds/config.go
  agent/xds/testdata/clusters/custom-passive-healthcheck.latest.golden
  api/config_entry.go
  api/config_entry_test.go
  build-support/scripts/devtools.sh
  proto-public/pbacl/acl.pb.go
  proto-public/pbconnectca/ca.pb.go
  proto-public/pbdataplane/dataplane.pb.go
  proto-public/pbdns/dns.pb.go
  proto-public/pbserverdiscovery/serverdiscovery.pb.go
  proto/pbacl/acl.pb.go
  proto/pbautoconf/auto_config.pb.go
  proto/pbcommon/common.pb.go
  proto/pbconfig/config.pb.go
  proto/pbconfigentry/config_entry.gen.go
  proto/pbconfigentry/config_entry.pb.go
  proto/pbconfigentry/config_entry.proto
  proto/pbconnect/connect.pb.go
  proto/pbpeering/peering.pb.go
  proto/pbpeerstream/peerstream.pb.go
  proto/pbservice/healthcheck.pb.go
  proto/pbservice/node.pb.go
  proto/pbservice/service.pb.go
  proto/pbstatus/status.pb.go
  proto/pbsubscribe/subscribe.pb.go
  test/integration/connect/envoy/case-upstream-config/service_s1.hcl
  test/integration/connect/envoy/case-upstream-config/verify.bats
Labels: theme/api, theme/envoy/xds, pr/no-backport

#17206 ci:upload test results to datadog
  .github/workflows/go-tests.yml
  .github/workflows/reusable-unit-split.yml
  .github/workflows/reusable-unit.yml
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing, pr/no-changelog, backport/1.13, backport/1.14, backport/1.15, pr/no-backport

#17292 proto: clear out old ratelimit.tmp files before making new ones
  build-support/scripts/protobuf.sh
Labels: pr/no-changelog, pr/no-metrics-test, backport/1.15

#17270 grpc: ensure grpc resolver correctly uses lan/wan addresses on servers
  .changelog/17270.txt
  agent/consul/client_test.go
  agent/consul/server_serf.go
  agent/consul/subscribe_backend_test.go
  agent/grpc-internal/client_test.go
  agent/grpc-internal/handler_test.go
  agent/grpc-internal/resolver/resolver.go
  agent/grpc-internal/resolver/resolver_test.go
  agent/peering_endpoint_test.go
  agent/rpc/peering/service_test.go
  agent/setup.go
Labels: pr/no-metrics-test, pr/no-backport

#17285 [1.15.x] grpc: ensure grpc resolver correctly uses lan/wan addresses on servers
  .changelog/17270.txt
  agent/consul/client_test.go
  agent/consul/server_serf.go
  agent/consul/subscribe_backend_test.go
  agent/grpc-internal/client_test.go
  agent/grpc-internal/handler_test.go
  agent/grpc-internal/resolver/resolver.go
  agent/grpc-internal/resolver/resolver_test.go
  agent/peering_endpoint_test.go
  agent/rpc/peering/service_test.go
  agent/setup.go
Labels: pr/no-metrics-test, pr/no-backport

#17290 [1.13.x] grpc: ensure grpc resolver correctly uses lan/wan addresses on servers
  .changelog/17270.txt
  agent/consul/client_test.go
  agent/consul/server_serf.go
  agent/consul/subscribe_backend_test.go
  agent/grpc-external/services/peerstream/stream_test.go
  agent/grpc-external/services/peerstream/testing.go
  agent/grpc-internal/client_test.go
  agent/grpc-internal/handler_test.go
  agent/grpc-internal/resolver/resolver.go
  agent/grpc-internal/resolver/resolver_test.go
  agent/peering_endpoint_test.go
  agent/rpc/peering/service_test.go
  agent/setup.go
Labels: pr/no-metrics-test, pr/no-backport

#17310 Update consul-k8s install command so it is valid
  website/content/docs/k8s/installation/install-cli.mdx
Labels: type/docs, pr/no-changelog, backport/1.14, backport/1.15

#17300 Backport of ci:upload test results to datadog into release/1.13.x
  .github/workflows/go-tests.yml
  .github/workflows/reusable-unit-split.yml
  .github/workflows/reusable-unit.yml
  .github/workflows/test-integrations.yml
Labels: pr/no-changelog, pr/no-backport

#17301 Backport of ci:upload test results to datadog into release/1.14.x
  .github/workflows/go-tests.yml
  .github/workflows/reusable-unit-split.yml
  .github/workflows/reusable-unit.yml
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#17309 Backport flaky-test fix to 1.15
  test/integration/consul-container/test/snapshot/snapshot_restore_test.go
Labels: pr/no-changelog, pr/no-backport

#17316 Container test: fix container test slow image build
  .github/workflows/test-integrations.yml
  GNUmakefile
  test/integration/consul-container/assets/Dockerfile-consul-envoy
  test/integration/consul-container/assets/tproxy-startup.sh
  test/integration/consul-container/go.mod
  test/integration/consul-container/go.sum
  test/integration/consul-container/libs/cluster/app.go
  test/integration/consul-container/libs/service/common.go
  test/integration/consul-container/libs/service/connect.go
  test/integration/consul-container/libs/service/examples.go
  test/integration/consul-container/libs/service/gateway.go
  test/integration/consul-container/libs/utils/version.go
  test/integration/consul-container/test/upgrade/README.md
  test/integration/consul-container/test/upgrade/basic/basic_test.go
  test/integration/consul-container/test/upgrade/basic/fullstopupgrade_test.go
  test/integration/consul-container/test/upgrade/basic/healthcheck_test.go
  test/integration/consul-container/test/upgrade/l7_traffic_management/resolver_default_subset_test.go
  test/integration/consul-container/test/upgrade/peering/peering_control_plane_mgw_test.go
  test/integration/consul-container/test/upgrade/peering/peering_http_test.go
Labels: type/ci, theme/contributing, pr/no-changelog, backport/1.15, pr/no-backport

#17294 OSS: Add api endpoint for manually setting service VIPs
  agent/catalog_endpoint.go
  agent/catalog_endpoint_test.go
  agent/consul/fsm/commands_oss.go
  agent/consul/internal_endpoint.go
  agent/consul/internal_endpoint_test.go
  agent/consul/state/catalog.go
  agent/consul/state/catalog_test.go
  agent/http_register.go
  agent/structs/catalog.go
  api/internal.go
  api/internal_test.go
Labels: theme/api, pr/no-changelog, pr/no-metrics-test, pr/no-docs, pr/no-backport

#17295 Attach service virtual IP info to compiled discovery chain
  agent/consul/discovery_chain_endpoint_test.go
  agent/consul/discoverychain/compile.go
  agent/consul/state/catalog.go
  agent/consul/state/catalog_schema.go
  agent/consul/state/config_entry.go
  agent/consul/state/config_entry_test.go
  agent/discovery_chain_endpoint_test.go
  agent/structs/discovery_chain.go
  agent/structs/structs.deepcopy.go
Labels: pr/no-changelog, pr/no-metrics-test, pr/no-docs, pr/no-backport

#17211 Add type validations for the Catalog resources
  internal/catalog/internal/types/dns_policy.go
  internal/catalog/internal/types/dns_policy_test.go
  internal/catalog/internal/types/errors.go
  internal/catalog/internal/types/errors_test.go
  internal/catalog/internal/types/health_checks.go
  internal/catalog/internal/types/health_checks_test.go
  internal/catalog/internal/types/health_status.go
  internal/catalog/internal/types/health_status_test.go
  internal/catalog/internal/types/node.go
  internal/catalog/internal/types/node_test.go
  internal/catalog/internal/types/service.go
  internal/catalog/internal/types/service_endpoints.go
  internal/catalog/internal/types/service_endpoints_test.go
  internal/catalog/internal/types/service_test.go
  internal/catalog/internal/types/testdata/errDNSPassingWeightOutOfRange.golden
  internal/catalog/internal/types/testdata/errDNSWarningWeightOutOfRange.golden
  internal/catalog/internal/types/testdata/errInvalidNodeHostFormat.golden
  internal/catalog/internal/types/testdata/errInvalidPhysicalPort.golden
  internal/catalog/internal/types/testdata/errInvalidPortReference.golden
  internal/catalog/internal/types/testdata/errInvalidVirtualPort.golden
  internal/catalog/internal/types/testdata/errInvalidWorkloadHostFormat.golden
  internal/catalog/internal/types/testdata/errLocalityZoneNoRegion.golden
  internal/catalog/internal/types/testdata/errNotDNSLabel.golden
  internal/catalog/internal/types/testdata/errNotIPAddress.golden
  internal/catalog/internal/types/testdata/errTooMuchMesh.golden
  internal/catalog/internal/types/testdata/errUnixSocketMultiport.golden
  internal/catalog/internal/types/testdata/errVirtualPortReused.golden
  internal/catalog/internal/types/validators.go
  internal/catalog/internal/types/validators_test.go
  internal/catalog/internal/types/virtual_ips.go
  internal/catalog/internal/types/virtual_ips_test.go
  internal/catalog/internal/types/workload.go
  internal/catalog/internal/types/workload_test.go
  internal/resource/errors.go
  internal/resource/errors_test.go
  internal/resource/testdata/ErrDataParse.golden
  internal/resource/testdata/ErrEmpty.golden
  internal/resource/testdata/ErrInvalidField.golden
  internal/resource/testdata/ErrInvalidListElement.golden
  internal/resource/testdata/ErrInvalidMapKey.golden
  internal/resource/testdata/ErrInvalidMapValue.golden
  internal/resource/testdata/ErrInvalidReferenceType.golden
  internal/resource/testdata/ErrMissing.golden
  internal/resource/testdata/ErrOwnerInvalid.golden
  internal/resource/testdata/ErrReferenceTenancyNotEqual.golden
Labels: pr/no-changelog, pr/no-backport

#17326 test: remove an assertion from a test that is flakier before 1.15
  agent/peering_endpoint_test.go
Labels: pr/no-changelog, pr/no-metrics-test, backport/1.13

#17325 Add Network Filter Support for Envoy Extensions
  agent/xds/extensionruntime/runtime_config.go
  envoyextensions/extensioncommon/list_envoy_extender.go
  envoyextensions/extensioncommon/runtime_config.go
Labels: theme/envoy/xds, pr/no-changelog, pr/no-metrics-test, pr/no-docs, pr/no-backport

#17323 consul-container: mitigate the drift from ent repo
  test/integration/consul-container/libs/utils/version.go
  test/integration/consul-container/test/upgrade/basic/basic_test.go
  test/integration/consul-container/test/upgrade/basic/fullstopupgrade_test.go
  test/integration/consul-container/test/upgrade/basic/healthcheck_test.go
  test/integration/consul-container/test/upgrade/common.go
  test/integration/consul-container/test/upgrade/peering/peering_http_test.go
Labels: pr/no-changelog, pr/no-backport

#17128 [HCP Observability] OTELExporter
  agent/hcp/telemetry/doc.go
  agent/hcp/telemetry/otel_exporter.go
  agent/hcp/telemetry/otel_exporter_test.go
  agent/hcp/telemetry/otlp_transform.go
  agent/hcp/telemetry/otlp_transform_test.go
  go.mod
  go.sum
Labels: pr/dependencies

#17328 Sidecar Proxy Suffix Refactor
  agent/consul/state/config_entry_exported_services.go
  agent/grpc-external/services/peerstream/subscription_manager.go
  agent/sidecar_service.go
  agent/structs/structs.go
Labels: pr/no-changelog, backport/1.14, backport/1.15

#17305 Update HCP bootstrapping to support existing clusters 1.15.x version
  .changelog/16916.txt
  agent/agent.go
  agent/config/builder.go
  agent/config/runtime.go
  agent/config/runtime_test.go
  agent/config/testdata/TestRuntimeConfig_Sanitize.golden
  agent/consul/acl_server.go
  agent/consul/config.go
  agent/consul/config_cloud.go
  agent/consul/leader.go
  agent/consul/leader_test.go
  agent/hcp/bootstrap/bootstrap.go
  agent/hcp/bootstrap/bootstrap_test.go
  agent/hcp/bootstrap/testing.go
  agent/hcp/client.go
  agent/hcp/config/config.go
  agent/hcp/scada/mock_Provider.go
  agent/hcp/testing.go
  command/agent/agent.go
  go.mod
  go.sum
Labels: theme/cli, theme/config, pr/dependencies, pr/no-backport

#17303 Update HCP bootstrapping to support existing clusters 1.14.x version
  .changelog/16916.txt
  agent/agent.go
  agent/config/builder.go
  agent/config/runtime.go
  agent/config/runtime_test.go
  agent/config/testdata/TestRuntimeConfig_Sanitize.golden
  agent/consul/config.go
  agent/consul/config_cloud.go
  agent/consul/leader.go
  agent/consul/leader_test.go
  agent/hcp/bootstrap/bootstrap.go
  agent/hcp/bootstrap/bootstrap_test.go
  agent/hcp/bootstrap/testing.go
  agent/hcp/client.go
  agent/hcp/config/config.go
  agent/hcp/scada/mock_Provider.go
  agent/hcp/testing.go
  command/agent/agent.go
  go.mod
  go.sum
  test/integration/consul-container/go.mod
  test/integration/consul-container/go.sum
Labels: theme/cli, theme/config, pr/dependencies, pr/no-backport

#17296 Add new fields to HCP bootstrap config request and push state request
  agent/consul/server.go
  agent/hcp/client.go
  go.mod
  go.sum
Labels: pr/dependencies, pr/no-changelog, backport/1.14, backport/1.15

#17342 manual backport of #17296 to release/1.14.x
  agent/consul/server.go
  agent/hcp/client.go
  go.mod
  go.sum
  test/integration/consul-container/go.mod
  test/integration/consul-container/go.sum
Labels: pr/dependencies, pr/no-backport

#17343 manual backport of #17296 to release/1.15.x
  agent/consul/server.go
  agent/hcp/client.go
  go.mod
  go.sum
Labels: pr/dependencies, pr/no-backport

#17261 docs: update names in references to renamed tutorials
  website/content/api-docs/operator/index.mdx
  website/content/commands/operator/index.mdx
  website/content/docs/architecture/improving-consul-resilience.mdx
  website/content/docs/connect/cluster-peering/index.mdx
  website/content/docs/nia/index.mdx
  website/content/docs/upgrading/instructions/general-process.mdx
  website/content/docs/upgrading/upgrade-specific.mdx
Labels: type/docs, pr/no-changelog, pr/no-metrics-test, backport/1.12, backport/1.13, backport/1.14, backport/1.15

#17311 [release/1.15.3] Add cloud stanza documentation
  website/content/docs/agent/config/config-files.mdx
Labels: type/docs, pr/no-changelog, backport/1.14, backport/1.15

#17171 agent: prevent very old servers re-joining a cluster with stale data
  .changelog/17171.txt
  agent/agent.go
  agent/agent_test.go
  agent/config/builder.go
  agent/config/builder_test.go
  agent/config/config.go
  agent/config/default.go
  agent/config/runtime.go
  agent/config/runtime_test.go
  agent/config/testdata/TestRuntimeConfig_Sanitize.golden
  agent/config/testdata/full-config.hcl
  agent/config/testdata/full-config.json
  agent/consul/config.go
  agent/consul/server_metadata.go
  agent/consul/server_metadata_test.go
  website/content/docs/agent/config/config-files.mdx
Labels: theme/config, backport/1.15

#17315 docs: initial documentation for the new State Store
  docs/README.md
  docs/persistence/README.md
  docs/resources/README.md
  docs/resources/architecture-overview.png
  docs/resources/raft-backend.png
  internal/storage/raft/backend.go
  proto-public/pbresource/resource.pb.go
  proto-public/pbresource/resource.proto
Labels: pr/no-changelog

#17357 [1.15.x] agent: prevent very old servers re-joining a cluster with stale data
  .changelog/17171.txt
  agent/agent.go
  agent/agent_test.go
  agent/config/builder.go
  agent/config/builder_test.go
  agent/config/config.go
  agent/config/default.go
  agent/config/runtime.go
  agent/config/runtime_test.go
  agent/config/testdata/TestRuntimeConfig_Sanitize.golden
  agent/config/testdata/full-config.hcl
  agent/config/testdata/full-config.json
  agent/consul/config.go
  agent/consul/server_metadata.go
  agent/consul/server_metadata_test.go
  website/content/docs/agent/config/config-files.mdx
Labels: type/docs, theme/config, pr/no-backport

#17331 upgrade test: fix on-the-fly-image build and downsize runner
  .github/workflows/test-integrations.yml
  test/integration/consul-container/test/upgrade/ingress_gateway_sds_test.go
Labels: pr/no-changelog, pr/no-backport

#17214 Add Node health controller
  agent/consul/server.go
  internal/catalog/exports.go
  internal/catalog/internal/controllers/nodehealth/controller.go
  internal/catalog/internal/controllers/nodehealth/controller_test.go
  internal/catalog/internal/controllers/nodehealth/status.go
  internal/catalog/internal/controllers/register.go
  internal/controller/api.go
  internal/controller/api_test.go
  internal/resource/resourcetest/builder.go
Labels: pr/no-changelog, pr/no-backport

#17317 fix(connect envoy): set initial_fetch_timeout to wait for initial xDS…
  .changelog/17317.txt
  command/connect/envoy/bootstrap_tpl.go
  command/connect/envoy/testdata/CONSUL_GRPC_ADDR-with-https-scheme-enables-tls.golden
  command/connect/envoy/testdata/CONSUL_HTTP_ADDR-with-https-scheme-does-not-affect-grpc-tls.golden
  command/connect/envoy/testdata/access-log-path.golden
  command/connect/envoy/testdata/access-logs-enabled-custom.golden
  command/connect/envoy/testdata/access-logs-enabled.golden
  command/connect/envoy/testdata/acl-enabled-and-token.golden
  command/connect/envoy/testdata/acl-enabled-but-no-token.golden
  command/connect/envoy/testdata/both-CONSUL_HTTP_ADDR-PLAIN-and-CONSUL_GRPC_ADDR-TLS-is-tls.golden
  command/connect/envoy/testdata/both-CONSUL_HTTP_ADDR-TLS-and-CONSUL_GRPC_ADDR-PLAIN-is-plain.golden
  command/connect/envoy/testdata/defaults-nodemeta.golden
  command/connect/envoy/testdata/defaults.golden
  command/connect/envoy/testdata/deprecated-grpc-addr-config.golden
  command/connect/envoy/testdata/envoy-readiness-probe.golden
  command/connect/envoy/testdata/existing-ca-file.golden
  command/connect/envoy/testdata/existing-ca-path.golden
  command/connect/envoy/testdata/extra_-multiple.golden
  command/connect/envoy/testdata/extra_-single.golden
  command/connect/envoy/testdata/grpc-addr-env.golden
  command/connect/envoy/testdata/grpc-addr-flag.golden
  command/connect/envoy/testdata/grpc-addr-unix-with-tls.golden
  command/connect/envoy/testdata/grpc-addr-unix.golden
  command/connect/envoy/testdata/grpc-tls-addr-config.golden
  command/connect/envoy/testdata/hcp-metrics.golden
  command/connect/envoy/testdata/ingress-gateway-address-specified.golden
  command/connect/envoy/testdata/ingress-gateway-no-auto-register.golden
  command/connect/envoy/testdata/ingress-gateway-nodemeta.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-and-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-without-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway.golden
  command/connect/envoy/testdata/prometheus-metrics-tls-ca-file.golden
  command/connect/envoy/testdata/prometheus-metrics-tls-ca-path.golden
  command/connect/envoy/testdata/prometheus-metrics.golden
  command/connect/envoy/testdata/stats-config-override.golden
  command/connect/envoy/testdata/token-arg.golden
  command/connect/envoy/testdata/token-env.golden
  command/connect/envoy/testdata/token-file-arg.golden
  command/connect/envoy/testdata/token-file-env.golden
  command/connect/envoy/testdata/xds-addr-config.golden
  command/connect/envoy/testdata/zipkin-tracing-config.golden
Labels: theme/cli, backport/1.14, backport/1.15

#17336 1.15 fix submat view bug
  agent/grpc-external/services/peerstream/subscription_manager.go
  agent/sidecar_service.go
  agent/structs/config_entry_exports.go
  agent/structs/structs.go
Labels: pr/no-changelog, backport/1.14

#17367 counterpart of the ent in oss
  agent/consul/rate/handler.go
  agent/consul/rate/handler_oss.go
  agent/consul/rate/handler_test.go
Labels: pr/no-changelog, pr/no-backport

#17359 integ-test CI: retry if fail to install packages
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#17373 fix test on 1.14.x branch
  agent/structs/config_entry_test.go
Labels: pr/no-changelog, pr/no-docs, pr/no-backport

#17374 fix test on 1.15.x branch
  agent/structs/config_entry_test.go
Labels: pr/no-changelog, pr/no-docs, pr/no-backport

#17372 Backport of fix(connect envoy): set initial_fetch_timeout to wait for initial xDS into release/1.14
  .changelog/17317.txt
  command/connect/envoy/bootstrap_tpl.go
  command/connect/envoy/testdata/CONSUL_GRPC_ADDR-with-https-scheme-enables-tls.golden
  command/connect/envoy/testdata/CONSUL_HTTP_ADDR-with-https-scheme-does-not-affect-grpc-tls.golden
  command/connect/envoy/testdata/access-log-path.golden
  command/connect/envoy/testdata/both-CONSUL_HTTP_ADDR-PLAIN-and-CONSUL_GRPC_ADDR-TLS-is-tls.golden
  command/connect/envoy/testdata/both-CONSUL_HTTP_ADDR-TLS-and-CONSUL_GRPC_ADDR-PLAIN-is-plain.golden
  command/connect/envoy/testdata/defaults-nodemeta.golden
  command/connect/envoy/testdata/defaults.golden
  command/connect/envoy/testdata/deprecated-grpc-addr-config.golden
  command/connect/envoy/testdata/envoy-readiness-probe.golden
  command/connect/envoy/testdata/existing-ca-file.golden
  command/connect/envoy/testdata/existing-ca-path.golden
  command/connect/envoy/testdata/extra_-multiple.golden
  command/connect/envoy/testdata/extra_-single.golden
  command/connect/envoy/testdata/grpc-addr-env.golden
  command/connect/envoy/testdata/grpc-addr-flag.golden
  command/connect/envoy/testdata/grpc-addr-unix-with-tls.golden
  command/connect/envoy/testdata/grpc-addr-unix.golden
  command/connect/envoy/testdata/grpc-tls-addr-config.golden
  command/connect/envoy/testdata/ingress-gateway-address-specified.golden
  command/connect/envoy/testdata/ingress-gateway-no-auto-register.golden
  command/connect/envoy/testdata/ingress-gateway-nodemeta.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-and-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-without-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway.golden
  command/connect/envoy/testdata/prometheus-metrics-tls-ca-file.golden
  command/connect/envoy/testdata/prometheus-metrics-tls-ca-path.golden
  command/connect/envoy/testdata/prometheus-metrics.golden
  command/connect/envoy/testdata/stats-config-override.golden
  command/connect/envoy/testdata/token-arg.golden
  command/connect/envoy/testdata/token-env.golden
  command/connect/envoy/testdata/token-file-arg.golden
  command/connect/envoy/testdata/token-file-env.golden
  command/connect/envoy/testdata/xds-addr-config.golden
  command/connect/envoy/testdata/zipkin-tracing-config.golden
Labels: theme/cli

#17361 Backport of fix(connect envoy): set initial_fetch_timeout to wait for initial xDS… into release/1.15.x
  .changelog/17317.txt
  command/connect/envoy/bootstrap_tpl.go
  command/connect/envoy/testdata/CONSUL_GRPC_ADDR-with-https-scheme-enables-tls.golden
  command/connect/envoy/testdata/CONSUL_HTTP_ADDR-with-https-scheme-does-not-affect-grpc-tls.golden
  command/connect/envoy/testdata/access-log-path.golden
  command/connect/envoy/testdata/access-logs-enabled-custom.golden
  command/connect/envoy/testdata/access-logs-enabled.golden
  command/connect/envoy/testdata/acl-enabled-and-token.golden
  command/connect/envoy/testdata/acl-enabled-but-no-token.golden
  command/connect/envoy/testdata/both-CONSUL_HTTP_ADDR-PLAIN-and-CONSUL_GRPC_ADDR-TLS-is-tls.golden
  command/connect/envoy/testdata/both-CONSUL_HTTP_ADDR-TLS-and-CONSUL_GRPC_ADDR-PLAIN-is-plain.golden
  command/connect/envoy/testdata/defaults-nodemeta.golden
  command/connect/envoy/testdata/defaults.golden
  command/connect/envoy/testdata/deprecated-grpc-addr-config.golden
  command/connect/envoy/testdata/envoy-readiness-probe.golden
  command/connect/envoy/testdata/existing-ca-file.golden
  command/connect/envoy/testdata/existing-ca-path.golden
  command/connect/envoy/testdata/extra_-multiple.golden
  command/connect/envoy/testdata/extra_-single.golden
  command/connect/envoy/testdata/grpc-addr-env.golden
  command/connect/envoy/testdata/grpc-addr-flag.golden
  command/connect/envoy/testdata/grpc-addr-unix-with-tls.golden
  command/connect/envoy/testdata/grpc-addr-unix.golden
  command/connect/envoy/testdata/grpc-tls-addr-config.golden
  command/connect/envoy/testdata/hcp-metrics.golden
  command/connect/envoy/testdata/ingress-gateway-address-specified.golden
  command/connect/envoy/testdata/ingress-gateway-no-auto-register.golden
  command/connect/envoy/testdata/ingress-gateway-nodemeta.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-and-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway-register-with-service-without-proxy-id.golden
  command/connect/envoy/testdata/ingress-gateway.golden
  command/connect/envoy/testdata/prometheus-metrics-tls-ca-file.golden
  command/connect/envoy/testdata/prometheus-metrics-tls-ca-path.golden
  command/connect/envoy/testdata/prometheus-metrics.golden
  command/connect/envoy/testdata/stats-config-override.golden
  command/connect/envoy/testdata/token-arg.golden
  command/connect/envoy/testdata/token-env.golden
  command/connect/envoy/testdata/token-file-arg.golden
  command/connect/envoy/testdata/token-file-env.golden
  command/connect/envoy/testdata/xds-addr-config.golden
  command/connect/envoy/testdata/zipkin-tracing-config.golden
Labels: theme/cli, pr/no-backport

#17313 Backport of Update consul-k8s install command so it is valid into release/1.14.x
  website/content/docs/k8s/installation/install-cli.mdx
Labels: type/docs

#17314 Backport of Update consul-k8s install command so it is valid into release/1.15.x
  website/content/docs/k8s/installation/install-cli.mdx
Labels: type/docs

#17378 Backport of snapshot: some improvments to the snapshot process into release/1.14.x
  .changelog/17236.txt
  agent/consul/server.go
  snapshot/snapshot.go
  website/content/commands/snapshot/save.mdx
Labels: type/docs

#17382 Add changelog entry from 1.14.6, set version for next release
  CHANGELOG.md
  version/VERSION
Labels: pr/no-changelog, pr/no-backport

#17350 Backport of docs: update names in references to renamed tutorials into release/1.15.x
  website/content/api-docs/operator/index.mdx
  website/content/commands/operator/index.mdx
  website/content/docs/architecture/improving-consul-resilience.mdx
  website/content/docs/nia/index.mdx
  website/content/docs/upgrading/instructions/general-process.mdx
  website/content/docs/upgrading/upgrade-specific.mdx
Labels: type/docs, pr/no-changelog, pr/no-metrics-test

#17348 Backport of docs: update names in references to renamed tutorials into release/1.14.x
  website/content/api-docs/operator/index.mdx
  website/content/commands/operator/index.mdx
  website/content/docs/architecture/improving-consul-resilience.mdx
  website/content/docs/connect/cluster-peering/index.mdx
  website/content/docs/nia/index.mdx
  website/content/docs/upgrading/instructions/general-process.mdx
  website/content/docs/upgrading/upgrade-specific.mdx
Labels: type/docs, pr/no-changelog, pr/no-metrics-test

#17383 agent: don't write server metadata in dev mode
  agent/agent.go
Labels: pr/no-changelog, backport/1.15

#17346 Backport of docs: update names in references to renamed tutorials into release/1.12.x
  website/content/api-docs/operator/index.mdx
  website/content/commands/operator/index.mdx
  website/content/docs/architecture/improving-consul-resilience.mdx
  website/content/docs/nia/index.mdx
  website/content/docs/upgrading/instructions/general-process.mdx
  website/content/docs/upgrading/upgrade-specific.mdx
Labels: type/docs, pr/no-changelog, pr/no-metrics-test

#17365 test: fix oss/ent drift in gateway container tests
  test/integration/consul-container/test/gateways/gateway_endpoint_test.go
  test/integration/consul-container/test/gateways/http_route_test.go
  test/integration/consul-container/test/gateways/namespace_oss.go
  test/integration/consul-container/test/gateways/tenancy_oss.go
Labels: pr/no-changelog, pr/no-metrics-test, pr/no-backport

#17159 [HCP Observability] OTELSink
  agent/hcp/telemetry/gauge_store.go
  agent/hcp/telemetry/gauge_store_test.go
  agent/hcp/telemetry/otel_sink.go
  agent/hcp/telemetry/otel_sink_test.go
  go.mod
  go.sum
Labels: pr/dependencies

#17327 Rename hcp-metrics-collector to consul-telemetry-collector
  .changelog/17327.txt
  agent/proxycfg/connect_proxy.go
  agent/proxycfg/state_test.go
  agent/proxycfg/testing_connect_proxy.go
  agent/xds/resources_test.go
  agent/xds/testdata/clusters/telemetry-collector.latest.golden
  agent/xds/testdata/endpoints/hcp-metrics.latest.golden
  agent/xds/testdata/endpoints/telemetry-collector.latest.golden
  agent/xds/testdata/listeners/telemetry-collector.latest.golden
  agent/xds/testdata/routes/telemetry-collector.latest.golden
  agent/xds/testdata/secrets/telemetry-collector.latest.golden
  api/connect.go
  command/connect/envoy/bootstrap_config.go
  command/connect/envoy/bootstrap_config_test.go
  command/connect/envoy/envoy_test.go
  command/connect/envoy/testdata/telemetry-collector.golden
  website/content/commands/connect/envoy.mdx
  website/content/docs/connect/proxies/envoy.mdx
Labels: theme/api, theme/envoy/xds, backport/1.15

#17086 Add ACLs Enabled field to consul agent startup status message
  .changelog/17086.txt
  command/agent/agent.go
Labels: theme/cli, pr/no-backport

#17387 test: slight refactoring ahead of peering testing improvements
  test/integration/consul-container/libs/assert/envoy.go
  test/integration/consul-container/libs/assert/peering.go
  test/integration/consul-container/libs/assert/service.go
  test/integration/consul-container/libs/utils/tenancy.go
  test/integration/consul-container/libs/utils/version.go
  test/integration/consul-container/libs/utils/version_oss.go
Labels: pr/no-changelog, pr/no-metrics-test, pr/no-backport

#17389 fix two typos
  agent/grpc-external/services/peerstream/stream_resources.go
  internal/catalog/internal/controllers/nodehealth/controller.go
Labels: pr/no-changelog, pr/no-metrics-test, pr/no-backport

#17375 Pull virtual IPs for filter chains from discovery chains
  agent/proxycfg/testing_tproxy.go
  agent/xds/listeners.go
  agent/xds/testdata/listeners/transparent-proxy-with-resolver-redirect-upstream.latest.golden
Labels: theme/envoy/xds, pr/no-changelog, pr/no-metrics-test, pr/no-docs, pr/no-backport

#17394 consul-container test: no splitting and on single runner
  .github/workflows/test-integrations.yml
  test/integration/consul-container/libs/topology/peering_topology.go
  test/integration/consul-container/test/gateways/http_route_test.go
  test/integration/consul-container/test/peering/rotate_server_and_ca_then_fail_test.go
  test/integration/consul-container/test/snapshot/snapshot_restore_test.go
  test/integration/consul-container/test/upgrade/basic/fullstopupgrade_test.go
  test/integration/consul-container/test/upgrade/peering/peering_control_plane_mgw_test.go
  test/integration/consul-container/test/upgrade/peering/peering_http_test.go
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#17259 Docs/igw docs day refactor
  website/content/api-docs/agent/service.mdx
  website/content/commands/connect/envoy.mdx
  website/content/docs/connect/config-entries/ingress-gateway.mdx
  website/content/docs/connect/gateways/ingress-gateway.mdx
  website/content/docs/connect/gateways/ingress-gateway/index.mdx
  website/content/docs/connect/gateways/ingress-gateway/tls-external-service.mdx
  website/content/docs/connect/gateways/ingress-gateway/usage.mdx
  website/data/docs-nav-data.json
Labels: type/docs, pr/no-changelog, pr/no-metrics-test, backport/1.15

#17396 Backport of Docs/igw docs day refactor into release/1.15.x
  website/content/api-docs/agent/service.mdx
  website/content/commands/connect/envoy.mdx
  website/content/docs/connect/config-entries/ingress-gateway.mdx
  website/content/docs/connect/gateways/ingress-gateway.mdx
  website/content/docs/connect/gateways/ingress-gateway/index.mdx
  website/content/docs/connect/gateways/ingress-gateway/ingress-gateways-tls-external-service.mdx
  website/content/docs/connect/gateways/ingress-gateway/ingress-gateways-usage.mdx
  website/data/docs-nav-data.json
Labels: type/docs

#17399 Add changelog entries for Consul 1.13.8 + 1.14.7
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-backport

#17400 Post-release updates for 1.13.x
  CHANGELOG.md
  version/VERSION
Labels: pr/no-changelog, pr/no-backport

#17401 Post-release updates for 1.14.x
  CHANGELOG.md
  version/VERSION
Labels: pr/no-changelog, pr/no-backport

#17406 updates to links in services overview description paragraph
  website/content/docs/services/services.mdx
Labels: type/docs, pr/no-changelog, pr/no-metrics-test, backport/1.14, backport/1.15

#17408 Backport of updates to links in services overview description paragraph into release/1.15.x
  website/content/docs/services/services.mdx
Labels: type/docs

#17410 Modify getReadyUpstreams to filter upstreams by listener
  agent/proxycfg/api_gateway.go
  agent/proxycfg/snapshot.go
  agent/xds/endpoints.go
Labels: theme/envoy/xds, pr/no-changelog, pr/no-backport

#17412 [Backport] Rename hcp-metrics-collector to consul-telemetry-collector (#17327)
  .changelog/17327.txt
  agent/proxycfg/connect_proxy.go
  agent/proxycfg/state_test.go
  agent/proxycfg/testing_connect_proxy.go
  agent/xds/resources_test.go
  agent/xds/testdata/clusters/telemetry-collector.latest.golden
  agent/xds/testdata/endpoints/hcp-metrics.latest.golden
  agent/xds/testdata/endpoints/telemetry-collector.latest.golden
  agent/xds/testdata/listeners/telemetry-collector.latest.golden
  agent/xds/testdata/routes/telemetry-collector.latest.golden
  agent/xds/testdata/secrets/telemetry-collector.latest.golden
  api/connect.go
  command/connect/envoy/bootstrap_config.go
  command/connect/envoy/bootstrap_config_test.go
  command/connect/envoy/envoy_test.go
  command/connect/envoy/testdata/telemetry-collector.golden
  website/content/commands/connect/envoy.mdx
  website/content/docs/connect/proxies/envoy.mdx
Labels: type/docs, theme/api, theme/cli, theme/envoy/xds, pr/no-backport

#17215 Add the workload health controller
  agent/consul/server.go
  internal/catalog/exports.go
  internal/catalog/internal/controllers/register.go
  internal/catalog/internal/controllers/workloadhealth/controller.go
  internal/catalog/internal/controllers/workloadhealth/controller_test.go
  internal/catalog/internal/controllers/workloadhealth/status.go
  internal/catalog/internal/mappers/nodemapper/node_mapper.go
  internal/catalog/internal/mappers/nodemapper/node_mapper_test.go
Labels: pr/no-changelog, pr/no-backport

#17390 xds: generate endpoints directly from API gateway snapshot
  agent/proxycfg/api_gateway.go
  agent/proxycfg/snapshot.go
  agent/xds/endpoints.go
  agent/xds/resources_test.go
  test/integration/connect/envoy/case-api-gateway-http-hostnames/verify.bats
  test/integration/connect/envoy/case-api-gateway-http-simple/verify.bats
  test/integration/connect/envoy/case-api-gateway-http-tls-overlapping-hosts/verify.bats
  test/integration/connect/envoy/case-api-gateway-tcp-simple/verify.bats
  test/integration/connect/envoy/case-api-gateway-tcp-tls-overlapping-hosts/verify.bats
Labels: theme/envoy/xds, pr/no-changelog, pr/no-backport

#17414 JWT Authentication with service intentions: xds package update
  agent/consul/fsm/fsm.go
  agent/consul/state/config_entry_events.go
  agent/consul/state/events.go
  agent/consul/state/memdb.go
  agent/proxycfg-glue/config_entry.go
  agent/proxycfg/connect_proxy.go
  agent/proxycfg/proxycfg.deepcopy.go
  agent/proxycfg/snapshot.go
  agent/proxycfg/state.go
  agent/xds/jwt_authn.go
  agent/xds/jwt_authn_test.go
  agent/xds/listeners.go
  agent/xds/testdata/jwt_authn/intention-with-path.golden
  agent/xds/testdata/jwt_authn/local-provider.golden
  agent/xds/testdata/jwt_authn/multiple-providers-and-one-permission.golden
  agent/xds/testdata/jwt_authn/remote-provider.golden
  agent/xds/testdata/jwt_authn/top-level-provider-with-permission.golden
  proto/private/pbconfigentry/config_entry.gen.go
  proto/private/pbconfigentry/config_entry.go
  proto/private/pbconfigentry/config_entry.pb.binary.go
  proto/private/pbconfigentry/config_entry.pb.go
  proto/private/pbconfigentry/config_entry.proto
  proto/private/pbsubscribe/subscribe.pb.go
  proto/private/pbsubscribe/subscribe.proto
Labels: theme/envoy/xds, pr/no-changelog, pr/no-docs, pr/no-backport

#17423 Allow resource updates to omit an owner refs UID
  agent/grpc-external/services/resource/write.go
  agent/grpc-external/services/resource/write_test.go
Labels: pr/no-changelog, pr/no-backport

#17416 prototest: fix early return condition in AssertElementsMatch
  agent/grpc-external/services/peerstream/stream_test.go
  agent/grpc-external/services/resource/list_test.go
  proto/private/prototest/testing.go
  proto/private/prototest/testing_test.go
Labels: pr/no-changelog, pr/no-metrics-test, pr/no-backport

#17417 [1.15.x] prototest: fix early return condition in AssertElementsMatch
  agent/grpc-external/services/peerstream/stream_test.go
  proto/prototest/testing.go
  proto/prototest/testing_test.go
Labels: pr/no-changelog, pr/no-metrics-test, pr/no-backport

#17418 [1.14.x] prototest: fix early return condition in AssertElementsMatch
  agent/grpc-external/services/peerstream/stream_test.go
  proto/prototest/testing.go
  proto/prototest/testing_test.go
Labels: pr/no-changelog, pr/no-metrics-test, pr/no-backport

#17419 [1.13.x] prototest: fix early return condition in AssertElementsMatch
  proto/prototest/testing.go
  proto/prototest/testing_test.go
Labels: pr/no-changelog, pr/no-metrics-test, pr/no-backport

#17398 xds: generate listeners directly from API gateway snapshot
  agent/consul/discoverychain/gateway.go
  agent/consul/server_test.go
  agent/proxycfg/api_gateway.go
  agent/proxycfg/snapshot.go
  agent/structs/config_entry_gateways.go
  agent/xds/listeners.go
  agent/xds/listeners_apigateway.go
  agent/xds/listeners_ingress.go
Labels: theme/envoy/xds, pr/no-changelog, pr/no-backport

#17302 Backport of ci:upload test results to datadog into release/1.15.x
  .github/workflows/go-tests.yml
  .github/workflows/reusable-unit-split.yml
  .github/workflows/reusable-unit.yml
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#17415 Disable remote proxy patching except AWS Lambda
  .changelog/17415.txt
  agent/envoyextensions/builtin/aws-lambda/aws_lambda.go
  agent/envoyextensions/builtin/aws-lambda/aws_lambda_test.go
  agent/envoyextensions/builtin/http/localratelimit/ratelimit.go
  agent/envoyextensions/builtin/lua/lua.go
  agent/envoyextensions/builtin/wasm/structs.go
  agent/envoyextensions/builtin/wasm/wasm.go
  agent/envoyextensions/builtin/wasm/wasm_test.go
  agent/envoyextensions/registered_extensions_test.go
  agent/xds/delta_envoy_extender_oss_test.go
  agent/xds/delta_test.go
  agent/xds/extensionruntime/runtime_config.go
  agent/xds/extensionruntime/runtime_config_oss_test.go
  agent/xds/testdata/builtin_extension/clusters/lua-inbound-doesnt-apply-to-local-upstreams.latest.golden
  agent/xds/testdata/builtin_extension/clusters/lua-outbound-applies-to-local-upstreams.latest.golden
  agent/xds/testdata/builtin_extension/endpoints/lua-inbound-doesnt-apply-to-local-upstreams.latest.golden
  agent/xds/testdata/builtin_extension/endpoints/lua-outbound-applies-to-local-upstreams.latest.golden
  agent/xds/testdata/builtin_extension/listeners/lua-inbound-doesnt-applies-to-upstreams.latest.golden
  agent/xds/testdata/builtin_extension/listeners/lua-inbound-doesnt-apply-to-local-upstreams.latest.golden
  agent/xds/testdata/builtin_extension/listeners/lua-outbound-applies-to-local-upstreams.latest.golden
  agent/xds/testdata/builtin_extension/listeners/lua-outbound-applies-to-upstreams.latest.golden
  agent/xds/testdata/builtin_extension/routes/lua-inbound-doesnt-apply-to-local-upstreams.latest.golden
  agent/xds/testdata/builtin_extension/routes/lua-outbound-applies-to-local-upstreams.latest.golden
  agent/xds/xds_protocol_helpers_test.go
  api/config_entry.go
  envoyextensions/extensioncommon/basic_envoy_extender.go
  envoyextensions/extensioncommon/envoy_extender_test.go
  envoyextensions/extensioncommon/list_envoy_extender.go
  envoyextensions/extensioncommon/resources.go
  envoyextensions/extensioncommon/runtime_config.go
  envoyextensions/extensioncommon/runtime_config_test.go
  envoyextensions/extensioncommon/upstream_envoy_extender.go
  troubleshoot/proxy/validateupstream.go
  troubleshoot/validate/validate.go
  troubleshoot/validate/validate_test.go
Labels: theme/envoy/xds, theme/security, backport/1.15

#17231 Only synthesize anonymous token in primary DC
  .changelog/17231.txt
  agent/consul/acl_server.go
  test/integration/consul-container/test/wanfed/acl_bootstrap_replication_test.go
  test/integration/consul-container/test/wanfed/wanfed_peering_test.go
Labels: backport/1.15

#17434 extract some config entry helpers into package
  agent/configentry/compare.go
  agent/configentry/compare_test.go
  agent/consul/config_replication.go
  agent/consul/config_replication_test.go
Labels: pr/no-changelog, pr/no-metrics-test, pr/no-backport

#17425 [Release/1.15.x] net 3914 gha consul container test no splitting
  .github/workflows/test-integrations.yml
  test/integration/consul-container/libs/service/connect.go
  test/integration/consul-container/libs/service/examples.go
  test/integration/consul-container/libs/service/gateway.go
  test/integration/consul-container/libs/topology/peering_topology.go
  test/integration/consul-container/libs/utils/version.go
  test/integration/consul-container/test/gateways/http_route_test.go
  test/integration/consul-container/test/peering/rotate_server_and_ca_then_fail_test.go
  test/integration/consul-container/test/upgrade/common.go
  test/integration/consul-container/test/upgrade/fullstopupgrade_test.go
  test/integration/consul-container/test/upgrade/peering/peering_control_plane_mgw_test.go
  test/integration/consul-container/test/upgrade/peering/peering_http_test.go
Labels: pr/no-changelog, pr/no-backport

#17436 Add necessary plumbing to implement per server ip based rate limiting
  agent/consul/rate/handler.go
  agent/consul/rate/handler_test.go
  agent/consul/rate/mock_LeaderStatusProvider_test.go
  agent/consul/rate/mock_RequestLimitsHandler.go
  agent/consul/rate/mock_ServersStatusProvider_test.go
  agent/consul/server.go
  agent/metadata/server.go
Labels: pr/no-changelog, pr/no-backport

#17426 [OSS] gRPC Blocking Queries
  .changelog/17426.txt
  agent/blockingquery/blockingquery.go
  agent/blockingquery/blockingquery_test.go
  agent/cache-types/peerings.go
  agent/cache-types/peerings_test.go
  agent/cache-types/trust_bundle.go
  agent/cache-types/trust_bundle_test.go
  agent/cache-types/trust_bundles.go
  agent/cache-types/trust_bundles_test.go
  agent/consul/acl_endpoint.go
  agent/consul/gateway_locator.go
  agent/consul/gateway_locator_test.go
  agent/consul/internal_endpoint.go
  agent/consul/prepared_query_endpoint.go
  agent/consul/rpc.go
  agent/consul/rpc_test.go
  agent/consul/server.go
  agent/consul/snapshot_endpoint.go
  agent/consul/txn_endpoint.go
  agent/grpc-external/options_test.go
  agent/grpc-external/querymeta.go
  agent/grpc-external/querymeta_test.go
  agent/peering_endpoint.go
  agent/peering_endpoint_test.go
  agent/proxycfg-glue/peering_list.go
  agent/proxycfg-glue/peering_list_test.go
  agent/proxycfg-glue/trust_bundle.go
  agent/proxycfg/mesh_gateway.go
  agent/proxycfg/testing_mesh_gateway.go
  agent/rpc/peering/service.go
  agent/rpc/peering/service_test.go
  agent/structs/structs.go
  agent/xds/testdata/clusters/mesh-gateway-with-peer-through-mesh-gateway-enabled.latest.golden
  agent/xds/testdata/endpoints/mesh-gateway-with-peer-through-mesh-gateway-enabled.latest.golden
  agent/xds/testdata/listeners/mesh-gateway-with-peer-through-mesh-gateway-enabled.latest.golden
  internal/tools/proto-gen-rpc-glue/e2e/source.pb.go
  internal/tools/proto-gen-rpc-glue/e2e/source.rpcglue.pb.go.golden
  internal/tools/proto-gen-rpc-glue/main.go
  proto/private/pbpeering/peering.pb.go
  proto/private/pbpeering/peering.proto
  proto/private/pbpeering/peering.rpcglue.pb.go
  website/content/api-docs/peering.mdx
Labels: pr/no-metrics-test, backport/1.14, backport/1.15

#17395 docs: first pass at a resource/controller developer guide
  docs/persistence/README.md
  docs/resources/README.md
  docs/resources/guide.md
Labels: pr/no-changelog

#17443 Update service-intentions.mdx
  website/content/docs/connect/config-entries/service-intentions.mdx
Labels: type/docs, pr/no-changelog, backport/1.15

#17438 CI: upload test results to datadog
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing, pr/no-changelog, backport/1.14, backport/1.15

#17448 CI: do not upload test metrics to datadog on forks
  .github/workflows/reusable-unit-split.yml
  .github/workflows/reusable-unit.yml
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-metrics-test, backport/1.13, backport/1.14, backport/1.15

#17449 Backport of CI: do not upload test metrics to datadog on forks into release/1.13.x
  .github/workflows/reusable-unit-split.yml
  .github/workflows/reusable-unit.yml
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing

#17456 Fix namespaced peer service updates / deletes.
  .changelog/17456.txt
  agent/grpc-external/services/peerstream/replication.go
  agent/grpc-external/services/peerstream/stream_test.go
Labels: backport/1.14, backport/1.15

#17424 Fix ACL check on health endpoint
  .changelog/17424.txt
  agent/consul/health_endpoint.go
  agent/consul/health_endpoint_test.go
  website/content/docs/upgrading/upgrade-specific.mdx
Labels: pr/no-backport

#17447 Backport of CI: upload test results to datadog into release/1.15.x
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing

#17432 Manual backport 1.15.x of Disable remote proxy patching except AWS Lambda
  .changelog/17415.txt
  agent/envoyextensions/builtin/aws-lambda/aws_lambda.go
  agent/envoyextensions/builtin/aws-lambda/aws_lambda_test.go
  agent/envoyextensions/builtin/lua/lua.go
  agent/envoyextensions/registered_extensions_test.go
  agent/xds/delta_envoy_extender_oss_test.go
  agent/xds/delta_test.go
  agent/xds/extensionruntime/runtime_config.go
  agent/xds/extensionruntime/runtime_config_oss_test.go
  agent/xds/testdata/builtin_extension/clusters/lua-inbound-doesnt-apply-to-local-upstreams.latest.golden
  agent/xds/testdata/builtin_extension/clusters/lua-outbound-applies-to-local-upstreams.latest.golden
  agent/xds/testdata/builtin_extension/endpoints/lua-inbound-doesnt-apply-to-local-upstreams.latest.golden
  agent/xds/testdata/builtin_extension/endpoints/lua-outbound-applies-to-local-upstreams.latest.golden
  agent/xds/testdata/builtin_extension/listeners/lua-inbound-doesnt-applies-to-upstreams.latest.golden
  agent/xds/testdata/builtin_extension/listeners/lua-inbound-doesnt-apply-to-local-upstreams.latest.golden
  agent/xds/testdata/builtin_extension/listeners/lua-outbound-applies-to-local-upstreams.latest.golden
  agent/xds/testdata/builtin_extension/listeners/lua-outbound-applies-to-upstreams.latest.golden
  agent/xds/testdata/builtin_extension/routes/lua-inbound-doesnt-apply-to-local-upstreams.latest.golden
  agent/xds/testdata/builtin_extension/routes/lua-outbound-applies-to-local-upstreams.latest.golden
  agent/xds/xds_protocol_helpers_test.go
  api/config_entry.go
  api/go.mod
  envoyextensions/extensioncommon/basic_envoy_extender.go
  envoyextensions/extensioncommon/envoy_extender_test.go
  envoyextensions/extensioncommon/resources.go
  envoyextensions/extensioncommon/runtime_config.go
  envoyextensions/extensioncommon/runtime_config_test.go
  envoyextensions/extensioncommon/upstream_envoy_extender.go
  envoyextensions/go.mod
  troubleshoot/go.mod
  troubleshoot/proxy/validateupstream.go
  troubleshoot/validate/validate.go
  troubleshoot/validate/validate_test.go
Labels: theme/envoy/xds, pr/no-changelog, theme/security, pr/no-backport

#17459 chore(ci): skip cache for lint workflow
  .github/workflows/reusable-lint.yml
Labels: type/ci, theme/contributing, pr/no-changelog, backport/1.13, backport/1.14, backport/1.15

#17463 Backport of chore(ci): skip cache for lint workflow into release/1.13.x
  .github/workflows/reusable-lint.yml
Labels: type/ci, theme/contributing

#17392 xds: generate routes directly from API gateway snapshot
  agent/consul/discoverychain/gateway.go
  agent/xds/listeners_apigateway.go
  agent/xds/routes.go
Labels: theme/envoy/xds, pr/no-changelog, pr/no-backport

#17453 xds: Remove APIGateway ToIngress function
  agent/proxycfg/proxycfg.deepcopy.go
  agent/proxycfg/snapshot.go
  agent/proxycfg/snapshot_test.go
  agent/xds/clusters.go
  agent/xds/endpoints.go
  agent/xds/listeners_apigateway.go
  agent/xds/routes.go
Labels: pr/no-changelog, pr/no-backport

#17465 Backport of chore(ci): skip cache for lint workflow into release/1.15.x
  .github/workflows/reusable-lint.yml
Labels: type/ci, theme/contributing

#17467 Update common-errors.mdx
  website/content/docs/troubleshoot/common-errors.mdx
Labels: type/docs, pr/no-changelog, backport/1.13, backport/1.14, backport/1.15

#17469 This fixes an issue where TCP services that are exported cannot be configured to failover
  agent/consul/state/config_entry.go
  agent/consul/state/config_entry_test.go
  agent/xds/endpoints.go
Labels: pr/no-changelog, pr/no-backport

#17461 add docs for consul-k8s config read command
  website/content/docs/k8s/k8s-cli.mdx
Labels: type/docs, pr/no-changelog, backport/1.15

#17474 [Release/1.14.x] net 3914 gha consul container test no splitting
  .github/workflows/reusable-lint.yml
  .github/workflows/test-integrations.yml
  test/integration/consul-container/libs/cluster/cluster.go
  test/integration/consul-container/libs/service/connect.go
  test/integration/consul-container/libs/service/examples.go
  test/integration/consul-container/libs/service/gateway.go
  test/integration/consul-container/test/upgrade/healthcheck_test.go
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#17477 Update index.mdx
  website/content/docs/k8s/upgrade/index.mdx
Labels: type/docs, pr/no-changelog, backport/1.14, backport/1.15

#17479 Backport of Update index.mdx into release/1.14.x
  website/content/docs/k8s/upgrade/index.mdx
Labels: type/docs

#17480 Backport of Update index.mdx into release/1.15.x
  website/content/docs/k8s/upgrade/index.mdx
Labels: type/docs

#17486 ci: update backport assistant to 0.3.4
  .github/workflows/backport-assistant.yml
Labels: type/ci, theme/contributing, pr/no-changelog, backport/1.13, backport/1.14, backport/1.15

#17488 Backport of ci: update backport assistant to 0.3.4 into release/1.13.x
  .github/workflows/backport-assistant.yml
Labels: type/ci, theme/contributing

#17489 Backport of ci: update backport assistant to 0.3.4 into release/1.14.x
  .github/workflows/backport-assistant.yml
Labels: type/ci, theme/contributing

#16552 perf: Remove expensive reflection from raft/mesh hot path
  .changelog/16552.txt
  GNUmakefile
  agent/consul/state/catalog.go
  agent/consul/state/catalog_schema.deepcopy.go
  agent/consul/state/deep-copy.sh
Labels: backport/1.14, backport/1.15

#17491 ENT->OSS merge for Consolidate `ListEnvoyExtender` into `BasicEnvoyEx…
  agent/envoyextensions/builtin/aws-lambda/aws_lambda.go
  agent/envoyextensions/builtin/http/localratelimit/ratelimit.go
  agent/envoyextensions/builtin/lua/lua.go
  agent/envoyextensions/builtin/wasm/wasm.go
  envoyextensions/extensioncommon/basic_envoy_extender.go
  envoyextensions/extensioncommon/basic_extension_adapter.go
  envoyextensions/extensioncommon/envoy_extender_test.go
  envoyextensions/extensioncommon/list_envoy_extender.go
  envoyextensions/extensioncommon/resources.go
  envoyextensions/extensioncommon/resources_test.go
  troubleshoot/validate/validate.go
Labels: pr/no-changelog, pr/no-metrics-test, pr/no-docs, pr/no-backport

#17495 Add `builtin/ext-authz` Envoy Extension
  .changelog/17495.txt
  agent/envoyextensions/builtin/ext-authz/ext_authz.go
  agent/envoyextensions/builtin/ext-authz/ext_authz_test.go
  agent/envoyextensions/builtin/ext-authz/structs.go
  agent/envoyextensions/registered_extensions.go
  agent/xds/delta_envoy_extender_oss_test.go
  agent/xds/delta_envoy_extender_test.go
  agent/xds/testdata/builtin_extension/clusters/ext-authz-http-local-grpc-service.latest.golden
  agent/xds/testdata/builtin_extension/clusters/ext-authz-http-local-http-service.latest.golden
  agent/xds/testdata/builtin_extension/clusters/ext-authz-http-upstream-grpc-service.latest.golden
  agent/xds/testdata/builtin_extension/clusters/ext-authz-http-upstream-http-service.latest.golden
  agent/xds/testdata/builtin_extension/clusters/ext-authz-tcp-local-grpc-service.latest.golden
  agent/xds/testdata/builtin_extension/clusters/ext-authz-tcp-upstream-grpc-service.latest.golden
  agent/xds/testdata/builtin_extension/endpoints/ext-authz-http-local-grpc-service.latest.golden
  agent/xds/testdata/builtin_extension/endpoints/ext-authz-http-local-http-service.latest.golden
  agent/xds/testdata/builtin_extension/endpoints/ext-authz-http-upstream-grpc-service.latest.golden
  agent/xds/testdata/builtin_extension/endpoints/ext-authz-http-upstream-http-service.latest.golden
  agent/xds/testdata/builtin_extension/endpoints/ext-authz-tcp-local-grpc-service.latest.golden
  agent/xds/testdata/builtin_extension/endpoints/ext-authz-tcp-upstream-grpc-service.latest.golden
  agent/xds/testdata/builtin_extension/listeners/ext-authz-http-local-grpc-service.latest.golden
  agent/xds/testdata/builtin_extension/listeners/ext-authz-http-local-http-service.latest.golden
  agent/xds/testdata/builtin_extension/listeners/ext-authz-http-upstream-grpc-service.latest.golden
  agent/xds/testdata/builtin_extension/listeners/ext-authz-http-upstream-http-service.latest.golden
  agent/xds/testdata/builtin_extension/listeners/ext-authz-tcp-local-grpc-service.latest.golden
  agent/xds/testdata/builtin_extension/listeners/ext-authz-tcp-upstream-grpc-service.latest.golden
  agent/xds/testdata/builtin_extension/routes/ext-authz-http-local-grpc-service.latest.golden
  agent/xds/testdata/builtin_extension/routes/ext-authz-http-local-http-service.latest.golden
  agent/xds/testdata/builtin_extension/routes/ext-authz-http-upstream-grpc-service.latest.golden
  agent/xds/testdata/builtin_extension/routes/ext-authz-http-upstream-http-service.latest.golden
  agent/xds/testdata/builtin_extension/routes/ext-authz-tcp-local-grpc-service.latest.golden
  agent/xds/testdata/builtin_extension/routes/ext-authz-tcp-upstream-grpc-service.latest.golden
  api/config_entry.go
Labels: theme/api, theme/envoy/xds, pr/no-docs, pr/no-backport

#17487 Add `builtin/property-override` Envoy Extension
  .changelog/17487.txt
  agent/envoyextensions/builtin/property-override/property_override.go
  agent/envoyextensions/builtin/property-override/property_override_test.go
  agent/envoyextensions/builtin/property-override/structpatcher.go
  agent/envoyextensions/builtin/property-override/structpatcher_test.go
  agent/envoyextensions/registered_extensions.go
  agent/xds/delta_envoy_extender_oss_test.go
  agent/xds/testdata/builtin_extension/clusters/propertyoverride-add-keepalive.latest.golden
  agent/xds/testdata/builtin_extension/clusters/propertyoverride-add-outlier-detection-multiple.latest.golden
  agent/xds/testdata/builtin_extension/clusters/propertyoverride-add-outlier-detection.latest.golden
  agent/xds/testdata/builtin_extension/clusters/propertyoverride-add-round-robin-lb-config.latest.golden
  agent/xds/testdata/builtin_extension/clusters/propertyoverride-inbound-doesnt-apply-to-outbound.latest.golden
  agent/xds/testdata/builtin_extension/clusters/propertyoverride-outbound-doesnt-apply-to-inbound.latest.golden
  agent/xds/testdata/builtin_extension/clusters/propertyoverride-remove-outlier-detection.latest.golden
  agent/xds/testdata/builtin_extension/endpoints/propertyoverride-add-keepalive.latest.golden
  agent/xds/testdata/builtin_extension/endpoints/propertyoverride-add-outlier-detection-multiple.latest.golden
  agent/xds/testdata/builtin_extension/endpoints/propertyoverride-add-outlier-detection.latest.golden
  agent/xds/testdata/builtin_extension/endpoints/propertyoverride-add-round-robin-lb-config.latest.golden
  agent/xds/testdata/builtin_extension/endpoints/propertyoverride-inbound-doesnt-apply-to-outbound.latest.golden
  agent/xds/testdata/builtin_extension/endpoints/propertyoverride-outbound-doesnt-apply-to-inbound.latest.golden
  agent/xds/testdata/builtin_extension/endpoints/propertyoverride-remove-outlier-detection.latest.golden
  agent/xds/testdata/builtin_extension/listeners/propertyoverride-add-keepalive.latest.golden
  agent/xds/testdata/builtin_extension/listeners/propertyoverride-add-outlier-detection-multiple.latest.golden
  agent/xds/testdata/builtin_extension/listeners/propertyoverride-add-outlier-detection.latest.golden
  agent/xds/testdata/builtin_extension/listeners/propertyoverride-add-round-robin-lb-config.latest.golden
  agent/xds/testdata/builtin_extension/listeners/propertyoverride-inbound-doesnt-apply-to-outbound.latest.golden
  agent/xds/testdata/builtin_extension/listeners/propertyoverride-outbound-doesnt-apply-to-inbound.latest.golden
  agent/xds/testdata/builtin_extension/listeners/propertyoverride-remove-outlier-detection.latest.golden
  agent/xds/testdata/builtin_extension/routes/propertyoverride-add-keepalive.latest.golden
  agent/xds/testdata/builtin_extension/routes/propertyoverride-add-outlier-detection-multiple.latest.golden
  agent/xds/testdata/builtin_extension/routes/propertyoverride-add-outlier-detection.latest.golden
  agent/xds/testdata/builtin_extension/routes/propertyoverride-add-round-robin-lb-config.latest.golden
  agent/xds/testdata/builtin_extension/routes/propertyoverride-inbound-doesnt-apply-to-outbound.latest.golden
  agent/xds/testdata/builtin_extension/routes/propertyoverride-outbound-doesnt-apply-to-inbound.latest.golden
  agent/xds/testdata/builtin_extension/routes/propertyoverride-remove-outlier-detection.latest.golden
  api/config_entry.go
Labels: theme/envoy/xds, pr/no-metrics-test, pr/no-backport

#17497 Support `Listener` and `ClusterLoadAssignment` in `property-override`
  agent/envoyextensions/builtin/property-override/property_override.go
  agent/envoyextensions/builtin/property-override/property_override_test.go
  agent/xds/delta_envoy_extender_oss_test.go
  agent/xds/testdata/builtin_extension/clusters/propertyoverride-cluster-load-assignment-inbound-add.latest.golden
  agent/xds/testdata/builtin_extension/clusters/propertyoverride-cluster-load-assignment-outbound-add.latest.golden
  agent/xds/testdata/builtin_extension/clusters/propertyoverride-listener-inbound-add.latest.golden
  agent/xds/testdata/builtin_extension/clusters/propertyoverride-listener-outbound-add.latest.golden
  agent/xds/testdata/builtin_extension/endpoints/propertyoverride-cluster-load-assignment-inbound-add.latest.golden
  agent/xds/testdata/builtin_extension/endpoints/propertyoverride-cluster-load-assignment-outbound-add.latest.golden
  agent/xds/testdata/builtin_extension/endpoints/propertyoverride-listener-inbound-add.latest.golden
  agent/xds/testdata/builtin_extension/endpoints/propertyoverride-listener-outbound-add.latest.golden
  agent/xds/testdata/builtin_extension/listeners/propertyoverride-cluster-load-assignment-inbound-add.latest.golden
  agent/xds/testdata/builtin_extension/listeners/propertyoverride-cluster-load-assignment-outbound-add.latest.golden
  agent/xds/testdata/builtin_extension/listeners/propertyoverride-listener-inbound-add.latest.golden
  agent/xds/testdata/builtin_extension/listeners/propertyoverride-listener-outbound-add.latest.golden
  agent/xds/testdata/builtin_extension/routes/propertyoverride-cluster-load-assignment-inbound-add.latest.golden
  agent/xds/testdata/builtin_extension/routes/propertyoverride-cluster-load-assignment-outbound-add.latest.golden
  agent/xds/testdata/builtin_extension/routes/propertyoverride-listener-inbound-add.latest.golden
  agent/xds/testdata/builtin_extension/routes/propertyoverride-listener-outbound-add.latest.golden
  envoyextensions/extensioncommon/basic_envoy_extender.go
  envoyextensions/extensioncommon/basic_extension_adapter.go
  envoyextensions/extensioncommon/resources.go
Labels: theme/envoy/xds, pr/no-changelog, pr/no-metrics-test, pr/no-docs, pr/no-backport

#17500 OSS version changes for FIPS work
  command/version/formatter.go
  command/version/version.go
  version/fips.go
Labels: theme/cli, pr/no-changelog, pr/no-backport

#17460 HCP Telemetry Feature
  .changelog/17460.txt
  agent/consul/server.go
  agent/consul/server_test.go
  agent/hcp/bootstrap/bootstrap.go
  agent/hcp/bootstrap/bootstrap_test.go
  agent/hcp/client/client.go
  agent/hcp/client/client_test.go
  agent/hcp/client/metrics_client.go
  agent/hcp/client/metrics_client_test.go
  agent/hcp/client/mock_Client.go
  agent/hcp/client/mock_CloudConfig.go
  agent/hcp/config/config.go
  agent/hcp/deps.go
  agent/hcp/deps_test.go
  agent/hcp/discover/discover.go
  agent/hcp/manager.go
  agent/hcp/manager_test.go
  agent/hcp/telemetry/custom_metrics.go
  agent/hcp/telemetry/doc.go
  agent/hcp/telemetry/filter.go
  agent/hcp/telemetry/filter_test.go
  agent/hcp/telemetry/gauge_store.go
  agent/hcp/telemetry/gauge_store_test.go
  agent/hcp/telemetry/otel_exporter.go
  agent/hcp/telemetry/otel_exporter_test.go
  agent/hcp/telemetry/otel_sink.go
  agent/hcp/telemetry/otel_sink_test.go
  agent/hcp/telemetry/otlp_transform.go
  agent/hcp/telemetry/otlp_transform_test.go
  agent/setup.go
  command/agent/agent.go
  go.mod
  go.sum
  lib/telemetry.go
  lib/telemetry_test.go
Labels: theme/cli, pr/dependencies, theme/internals, backport/1.15

#17502 [Backport] Manual Backport of HCP Telemetry
  .changelog/17460.txt
  agent/consul/server.go
  agent/consul/server_test.go
  agent/hcp/bootstrap/bootstrap.go
  agent/hcp/bootstrap/bootstrap_test.go
  agent/hcp/client/client.go
  agent/hcp/client/client_test.go
  agent/hcp/client/metrics_client.go
  agent/hcp/client/metrics_client_test.go
  agent/hcp/client/mock_Client.go
  agent/hcp/client/mock_CloudConfig.go
  agent/hcp/config/config.go
  agent/hcp/deps.go
  agent/hcp/deps_test.go
  agent/hcp/discover/discover.go
  agent/hcp/manager.go
  agent/hcp/manager_test.go
  agent/hcp/telemetry/custom_metrics.go
  agent/hcp/telemetry/doc.go
  agent/hcp/telemetry/filter.go
  agent/hcp/telemetry/filter_test.go
  agent/hcp/telemetry/gauge_store.go
  agent/hcp/telemetry/gauge_store_test.go
  agent/hcp/telemetry/otel_exporter.go
  agent/hcp/telemetry/otel_exporter_test.go
  agent/hcp/telemetry/otel_sink.go
  agent/hcp/telemetry/otel_sink_test.go
  agent/hcp/telemetry/otlp_transform.go
  agent/hcp/telemetry/otlp_transform_test.go
  agent/setup.go
  command/agent/agent.go
  go.mod
  go.sum
  lib/telemetry.go
  lib/telemetry_test.go
Labels: theme/cli, pr/dependencies, theme/internals, pr/no-backport

#17505 Enable Network filters for Wasm Envoy Extension
  .changelog/17505.txt
  agent/envoyextensions/builtin/wasm/wasm.go
  agent/envoyextensions/builtin/wasm/wasm_test.go
  agent/xds/delta_envoy_extender_oss_test.go
  agent/xds/delta_envoy_extender_test.go
  agent/xds/testdata/builtin_extension/clusters/wasm-tcp-local-file-outbound.latest.golden
  agent/xds/testdata/builtin_extension/clusters/wasm-tcp-local-file.latest.golden
  agent/xds/testdata/builtin_extension/clusters/wasm-tcp-remote-file-outbound.latest.golden
  agent/xds/testdata/builtin_extension/clusters/wasm-tcp-remote-file.latest.golden
  agent/xds/testdata/builtin_extension/endpoints/wasm-tcp-local-file-outbound.latest.golden
  agent/xds/testdata/builtin_extension/endpoints/wasm-tcp-local-file.latest.golden
  agent/xds/testdata/builtin_extension/endpoints/wasm-tcp-remote-file-outbound.latest.golden
  agent/xds/testdata/builtin_extension/endpoints/wasm-tcp-remote-file.latest.golden
  agent/xds/testdata/builtin_extension/listeners/wasm-tcp-local-file-outbound.latest.golden
  agent/xds/testdata/builtin_extension/listeners/wasm-tcp-local-file.latest.golden
  agent/xds/testdata/builtin_extension/listeners/wasm-tcp-remote-file-outbound.latest.golden
  agent/xds/testdata/builtin_extension/listeners/wasm-tcp-remote-file.latest.golden
  agent/xds/testdata/builtin_extension/routes/wasm-tcp-local-file-outbound.latest.golden
  agent/xds/testdata/builtin_extension/routes/wasm-tcp-local-file.latest.golden
  agent/xds/testdata/builtin_extension/routes/wasm-tcp-remote-file-outbound.latest.golden
  agent/xds/testdata/builtin_extension/routes/wasm-tcp-remote-file.latest.golden
Labels: theme/envoy/xds, pr/no-docs, pr/no-backport
