Repository hashicorp/consul, pull requests merged in 2023-04, with the labels that each got.

#16749 Connect CA Primary Provider refactor
  agent/connect/ca/mock_Provider.go
  agent/connect/ca/provider.go
  agent/connect/ca/provider_aws.go
  agent/connect/ca/provider_aws_test.go
  agent/connect/ca/provider_consul.go
  agent/connect/ca/provider_consul_test.go
  agent/connect/ca/provider_vault.go
  agent/connect/ca/provider_vault_test.go
  agent/consul/leader_connect_ca.go
  agent/consul/leader_connect_ca_test.go
  agent/consul/leader_connect_test.go
Labels: theme/connect, pr/no-changelog, pr/no-backport

#16856 Update changelog with patch releases
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-backport

#16843 Update cli-flags.mdx - typo
  website/content/docs/agent/config/cli-flags.mdx
Labels: type/docs, pr/no-changelog, backport/1.15

#16776 Allow dialer to re-establish terminated peering
  .changelog/16776.txt
  agent/consul/leader_peering_test.go
  agent/consul/peering_backend.go
  agent/consul/peering_backend_test.go
Labels: backport/1.15

#16841 [Manual backport] Net 3478/backport service instances table
  agent/consul/state/usage.go
  agent/consul/state/usage_oss.go
  agent/consul/state/usage_test.go
  agent/consul/usagemetrics/usagemetrics.go
  agent/consul/usagemetrics/usagemetrics_oss.go
  agent/consul/usagemetrics/usagemetrics_oss_test.go
  agent/structs/structs.go
  agent/structs/structs_oss.go
Labels: pr/no-backport

#16747 CA mesh CA expiration to it's own section
  website/content/docs/agent/telemetry.mdx
Labels: type/docs, pr/no-changelog, pr/no-backport

#16852 docs: Fix broken doc in consul-k8s upgrade page
  website/content/docs/k8s/upgrade/index.mdx
Labels: type/docs, pr/no-changelog, backport/1.15

#16864 Backport of docs: Fix broken doc in consul-k8s upgrade page into release/1.15.x
  website/content/docs/k8s/upgrade/index.mdx
Labels: type/docs

#16867 [1.14.x] Allow dialer to re-establish terminated peering
  .changelog/16776.txt
  agent/consul/leader_peering_test.go
  agent/consul/peering_backend.go
  agent/consul/peering_backend_test.go
Labels: pr/no-backport

#16834 docs: add envoy to the proxycfg diagram
  agent/proxycfg/proxycfg.go
  docs/service-mesh/README.md
Labels: pr/no-changelog, pr/no-backport

#16863 fix: metrics labels are prefixed by consul in 1.13.x
  agent/consul/usagemetrics/usagemetrics.go
Labels: pr/no-backport

#16619 Raft storage backend
  agent/consul/controller/controller_test.go
  agent/consul/fsm/commands_oss.go
  agent/consul/fsm/commands_oss_test.go
  agent/consul/fsm/fsm.go
  agent/consul/fsm/snapshot.go
  agent/consul/fsm/snapshot_oss.go
  agent/consul/fsm/snapshot_oss_test.go
  agent/consul/fsm/snapshot_test.go
  agent/consul/gateways/controller_gateways_test.go
  agent/consul/issue_test.go
  agent/consul/raft_handle.go
  agent/consul/rpc.go
  agent/consul/server.go
  agent/grpc-external/services/resource/list.go
  agent/grpc-external/services/resource/list_test.go
  agent/grpc-external/services/resource/read.go
  agent/grpc-external/services/resource/read_test.go
  agent/grpc-external/services/resource/server.go
  agent/grpc-external/services/resource/server_test.go
  agent/grpc-external/services/resource/watch.go
  agent/grpc-external/services/resource/watch_test.go
  agent/grpc-internal/handler.go
  agent/grpc-internal/listener.go
  agent/grpc-middleware/rate_limit_mappings.gen.go
  agent/pool/conn.go
  agent/structs/structs.go
  command/intention/list/intention_list_test.go
  internal/storage/conformance/conformance.go
  internal/storage/inmem/snapshot.go
  internal/storage/inmem/snapshot_test.go
  internal/storage/inmem/store.go
  internal/storage/inmem/watch.go
  internal/storage/raft/backend.go
  internal/storage/raft/conformance_test.go
  internal/storage/raft/forwarding.go
  internal/storage/storage.go
  proto/buf.yaml
  proto/private/pbstorage/raft.pb.binary.go
  proto/private/pbstorage/raft.pb.go
  proto/private/pbstorage/raft.proto
  proto/private/pbstorage/raft_grpc.pb.go
Labels: theme/cli, pr/no-changelog

#16870 Backport of ci: increase deep-copy and lint-enum jobs to use large runner as they hang in ENT into release/1.15.x
  .github/workflows/go-tests.yml
Labels: theme/contributing, pr/no-changelog, pr/no-backport

#16876 ci: add arm64 testing
  .github/workflows/go-tests.yml
  .github/workflows/reusable-dev-build.yml
Labels: theme/contributing, pr/no-changelog, backport/1.13, backport/1.14, backport/1.15

#16880 Backport of ci: add arm64 testing into release/1.13.x
  .github/workflows/go-tests.yml
  .github/workflows/reusable-dev-build.yml
Labels: theme/contributing

#16882 Backport of ci: add arm64 testing into release/1.14.x
  .github/workflows/go-tests.yml
  .github/workflows/reusable-dev-build.yml
Labels: type/docs, theme/api, theme/health-checks, theme/acls, theme/cli, theme/config, theme/ui, theme/connect, theme/tls, theme/telemetry, type/ci, pr/dependencies, theme/envoy/xds, theme/contributing, theme/internals, theme/certificates, theme/agent-cache, theme/consul-terraform-sync, pr/no-changelog, pr/no-backport

#16881 Omit false positives from 404 checker
  .github/workflows/broken-link-check.yml
  website/content/docs/connect/config-entries/service-defaults.mdx
  website/content/docs/connect/intentions/create-manage-intentions.mdx
Labels: type/docs, theme/contributing, pr/no-changelog, pr/no-backport

#16883 ci: add arm64 testing into release/1.15.x
  .github/workflows/go-tests.yml
  .github/workflows/reusable-dev-build.yml
Labels: theme/contributing, pr/no-changelog, pr/no-backport

#16878 Update release/1.15.x to reflect release of 1.15.2
  CHANGELOG.md
  version/VERSION
Labels: pr/no-changelog, pr/no-backport

#16872 ci: fixes missing deps in frontend gha workflows
  .github/workflows/frontend.yml
Labels: pr/no-changelog, backport/1.13, backport/1.14, backport/1.15

#16827 ci: always test oss and conditionally test enterprise
  .github/workflows/go-tests.yml
  .github/workflows/reusable-unit-split.yml
  .github/workflows/reusable-unit.yml
Labels: theme/contributing, pr/no-changelog, backport/1.13, backport/1.14, backport/1.15

#16893 Backport of ci: fixes missing deps in frontend gha workflows into release/1.14.x
  .github/workflows/frontend.yml
Labels: theme/contributing

#16892 Backport of ci: fixes missing deps in frontend gha workflows into release/1.13.x
  .github/workflows/frontend.yml
Labels: theme/contributing

#16894 Backport of ci: fixes missing deps in frontend gha workflows into release/1.15.x
  .github/workflows/frontend.yml
Labels: theme/contributing

#16898 temporarily disable macos-arm64 tests job in go-tests
  .github/workflows/go-tests.yml
Labels: theme/contributing, pr/no-changelog, backport/1.13, backport/1.14, backport/1.15, pr/no-backport

#16901 Backport of temporarily disable macos-arm64 tests job in go-tests into release/1.14.x
  .github/workflows/go-tests.yml
Labels: theme/contributing

#16900 Backport of temporarily disable macos-arm64 tests job in go-tests into release/1.13.x
  .github/workflows/go-tests.yml
Labels: theme/contributing

#16786 Resource `Write` endpoint
  agent/consul/server.go
  agent/grpc-external/services/resource/list_test.go
  agent/grpc-external/services/resource/read_test.go
  agent/grpc-external/services/resource/server.go
  agent/grpc-external/services/resource/server_test.go
  agent/grpc-external/services/resource/watch_test.go
  agent/grpc-external/services/resource/write.go
  agent/grpc-external/services/resource/write_test.go
  go.mod
  go.sum
  internal/resource/demo/demo.go
  internal/resource/registry.go
  internal/storage/inmem/store.go
  proto/private/pbdemo/v1/demo.pb.binary.go
  proto/private/pbdemo/v1/demo.pb.go
  proto/private/pbdemo/v1/demo.proto
  proto/private/pbdemo/v2/demo.pb.binary.go
  proto/private/pbdemo/v2/demo.pb.go
  proto/private/pbdemo/v2/demo.proto
Labels: pr/dependencies, pr/no-changelog

#16756 Delete(...) endpoint for the resource service
  agent/grpc-external/services/resource/delete.go
  agent/grpc-external/services/resource/delete_test.go
  agent/grpc-external/services/resource/server.go
  agent/grpc-external/services/resource/server_test.go
Labels: pr/no-changelog, pr/no-backport

#16877 Wasm Envoy HTTP extension
  .changelog/16877.txt
  agent/envoyextensions/builtin/aws-lambda/aws_lambda.go
  agent/envoyextensions/builtin/aws-lambda/aws_lambda_test.go
  agent/envoyextensions/builtin/aws-lambda/copied.go
  agent/envoyextensions/builtin/http/localratelimit/copied.go
  agent/envoyextensions/builtin/http/localratelimit/ratelimit.go
  agent/envoyextensions/builtin/lua/lua.go
  agent/envoyextensions/builtin/wasm/structs.go
  agent/envoyextensions/builtin/wasm/wasm.go
  agent/envoyextensions/builtin/wasm/wasm_test.go
  agent/envoyextensions/registered_extensions.go
  agent/xds/delta_envoy_extender_oss_test.go
  agent/xds/extensionruntime/runtime_config.go
  agent/xds/extensionruntime/runtime_config_oss_test.go
  agent/xds/testdata/builtin_extension/clusters/wasm-http-local-file.latest.golden
  agent/xds/testdata/builtin_extension/clusters/wasm-http-remote-file.latest.golden
  agent/xds/testdata/builtin_extension/endpoints/wasm-http-local-file.latest.golden
  agent/xds/testdata/builtin_extension/endpoints/wasm-http-remote-file.latest.golden
  agent/xds/testdata/builtin_extension/listeners/wasm-http-local-file.latest.golden
  agent/xds/testdata/builtin_extension/listeners/wasm-http-remote-file.latest.golden
  agent/xds/testdata/builtin_extension/routes/wasm-http-local-file.latest.golden
  agent/xds/testdata/builtin_extension/routes/wasm-http-remote-file.latest.golden
  api/config_entry.go
  envoyextensions/extensioncommon/resources.go
  envoyextensions/extensioncommon/runtime_config.go
  test/integration/connect/envoy/case-mesh-to-lambda/verify.bats
  test/integration/connect/envoy/case-wasm/capture.sh
  test/integration/connect/envoy/case-wasm/data/dummy.wasm
  test/integration/connect/envoy/case-wasm/service_s1.hcl
  test/integration/connect/envoy/case-wasm/service_s2.hcl
  test/integration/connect/envoy/case-wasm/setup.sh
  test/integration/connect/envoy/case-wasm/vars.sh
  test/integration/connect/envoy/case-wasm/verify.bats
  test/integration/connect/envoy/helpers.bash
Labels: theme/api, theme/envoy/xds, pr/no-metrics-test, pr/no-docs, pr/no-backport

#16885 Fix API GW broken link
  website/content/docs/api-gateway/upgrades.mdx
Labels: type/docs, pr/no-changelog, pr/no-backport

#16905 ci: Add success jobs. make go-test-enterprise conditional. build-distros and go-tests trigger on push to main and release branches
  .github/workflows/build-artifacts.yml
  .github/workflows/build-distros.yml
  .github/workflows/frontend.yml
  .github/workflows/go-tests.yml
  .github/workflows/verify-ci.yml
Labels: theme/contributing, pr/no-changelog, backport/1.13, backport/1.14, backport/1.15

#16908 Backport of ci: Add success jobs. make go-test-enterprise conditional. build-distros and go-tests trigger on push to main and release branches into release/1.13.x
  .github/workflows/go-tests.yml
Labels: theme/contributing

#16913 Backport of ci: Add success jobs. make go-test-enterprise conditional. build-distros and go-tests trigger on push to main and release branches into release/1.15.x
  .github/workflows/go-tests.yml
Labels: theme/contributing

#16910 Backport of ci: Add success jobs. make go-test-enterprise conditional. build-distros and go-tests trigger on push to main and release branches into release/1.14.x
  .github/workflows/build-distros.yml
  .github/workflows/frontend.yml
  .github/workflows/go-tests.yml
  .github/workflows/verify-ci.yml
Labels: type/docs, theme/api, theme/health-checks, theme/acls, theme/cli, theme/config, theme/ui, theme/connect, theme/tls, theme/telemetry, type/ci, pr/dependencies, theme/envoy/xds, theme/contributing, theme/internals, theme/certificates, theme/agent-cache, theme/consul-terraform-sync

#16920 ci: increase ENT runner size for xl to match OSS. have build-distros use xl to match CircleCI
  .github/scripts/get_runner_classes.sh
  .github/workflows/build-artifacts.yml
  .github/workflows/build-distros.yml
Labels: theme/contributing, pr/no-changelog, backport/1.13, backport/1.14, backport/1.15

#16746 log warning about CA expiring sooner
  agent/consul/leader_metrics.go
  agent/consul/leader_metrics_test.go
  agent/metrics.go
Labels: theme/consul-vault, theme/certificates, pr/no-changelog, theme/logging, pr/no-docs, pr/no-backport

#16874 highlight the agent.tls cert metric with CA ones
  website/content/docs/agent/telemetry.mdx
Labels: type/docs, pr/no-changelog, pr/no-metrics-test, pr/no-backport

#16925 docs: improve upgrade path guidance
  website/content/docs/upgrading/instructions/index.mdx
  website/content/docs/upgrading/upgrade-specific.mdx
Labels: type/docs, pr/no-changelog, backport/1.15

#16919 Test: add noCleanup to TestServer stop
  sdk/testutil/server.go
Labels: pr/no-changelog, backport/1.14, backport/1.15

#16917 [docs] fix typo in LocalRequestTimeoutMs
  website/content/docs/connect/config-entries/service-defaults.mdx
Labels: type/docs, pr/no-changelog, backport/1.14, backport/1.15

#16858 Backport of Update cli-flags.mdx - typo into release/1.15.x
  website/content/docs/agent/config/cli-flags.mdx
Labels: type/docs, pr/no-changelog, pr/no-metrics-test

#16934 ci: add GOTAGS to build-distros
  .github/workflows/build-distros.yml
Labels: theme/contributing, pr/no-changelog, backport/1.13, backport/1.14, backport/1.15

#16926 APIGW: Routes with duplicate parents should be invalid
  agent/structs/config_entry_routes.go
  agent/structs/config_entry_routes_test.go
Labels: pr/no-changelog, pr/no-docs, pr/no-backport

#16937 Backport of ci: add GOTAGS to build-distros into release/1.13.x
  .github/workflows/build-distros.yml
Labels: theme/contributing

#16938 Backport of ci: add GOTAGS to build-distros into release/1.14.x
  .github/workflows/build-distros.yml
Labels: theme/contributing

#16939 Backport of ci: add GOTAGS to build-distros into release/1.15.x
  .github/workflows/build-distros.yml
Labels: theme/contributing

#16860 ci: remove verify-ci from circleci
  .circleci/config.yml
Labels: type/ci, pr/no-changelog, backport/1.13, backport/1.14, backport/1.15

#16943 Backport of ci: remove verify-ci from circleci into release/1.14.x
  .circleci/config.yml
Labels: type/ci

#16944 Backport of ci: remove verify-ci from circleci into release/1.15.x
  .circleci/config.yml
Labels: type/ci

#16942 Backport of ci: remove verify-ci from circleci into release/1.13.x
  .circleci/config.yml
Labels: type/ci

#16935 Backport of [docs] fix typo in LocalRequestTimeoutMs into release/1.14.x
  website/content/docs/connect/config-entries/service-defaults.mdx
Labels: type/docs, pr/no-metrics-test

#16949 update vault integration testing versions
  .github/workflows/test-integrations.yml
Labels: theme/testing, theme/contributing, pr/no-changelog, pr/no-docs, pr/no-backport

#16953 Backport of ci: build-artifacts - fix platform missing in manifest error into release/1.15.x
  .github/workflows/build-artifacts.yml
Labels: theme/contributing

#16842 Check acls on resource `Read`, `List`, and `WatchList`
  agent/consul/server.go
  agent/grpc-external/services/resource/list.go
  agent/grpc-external/services/resource/list_test.go
  agent/grpc-external/services/resource/mock_ACLResolver.go
  agent/grpc-external/services/resource/mock_Registry.go
  agent/grpc-external/services/resource/read.go
  agent/grpc-external/services/resource/read_test.go
  agent/grpc-external/services/resource/server.go
  agent/grpc-external/services/resource/server_test.go
  agent/grpc-external/services/resource/watch.go
  agent/grpc-external/services/resource/watch_test.go
  agent/grpc-external/services/resource/write_test.go
  agent/grpc-external/testutils/acl.go
  internal/resource/demo/demo.go
  internal/resource/registry.go
  internal/resource/registry_test.go
Labels: pr/no-changelog, pr/no-backport

#16950 Resource validation hook for `Write` endpoint
  agent/grpc-external/services/resource/write.go
  agent/grpc-external/services/resource/write_test.go
  internal/resource/demo/demo.go
  internal/resource/registry.go
  internal/resource/registry_test.go
Labels: pr/no-changelog, pr/no-backport

#16957 Remove deprecated service-defaults upstream behavior.
  .changelog/16957.txt
  agent/configentry/merge_service_config.go
  agent/configentry/resolve.go
  agent/consul/config_endpoint_test.go
  agent/proxycfg-glue/resolved_service_config.go
  agent/service_manager_test.go
  agent/structs/config_entry.go
  agent/structs/config_entry_test.go
  agent/structs/structs.deepcopy.go
  website/content/docs/upgrading/upgrade-specific.mdx
Labels: type/docs, pr/no-backport

#16873 Fix the indentation of the copyAnnotations example
  website/content/docs/k8s/helm.mdx
Labels: type/docs, pr/no-changelog, pr/no-backport

#16960 Update docs for service-defaults overrides.
  website/content/docs/connect/config-entries/service-defaults.mdx
  website/content/docs/upgrading/upgrade-specific.mdx
Labels: type/docs, pr/no-changelog, pr/no-backport

#16964 Remove global.name requirement for APs
  website/content/docs/enterprise/admin-partitions.mdx
Labels: type/docs, pr/no-changelog, pr/no-backport

#16941 ci: remove build-distros from CircleCI
  .circleci/config.yml
Labels: type/ci, pr/no-changelog, backport/1.13, backport/1.14, backport/1.15

#16890 feat: add reporting config with reload
  agent/agent.go
  agent/agent_oss_test.go
  agent/config/builder_oss.go
  agent/config/builder_oss_test.go
  agent/config/config.go
  agent/config/runtime.go
  agent/config/runtime_oss_test.go
  agent/config/testdata/TestRuntimeConfig_Sanitize.golden
  agent/config/testdata/full-config.hcl
  agent/config/testdata/full-config.json
  agent/consul/config.go
  agent/consul/server.go
  agent/consul/server_oss.go
  agent/consul/server_oss_test.go
Labels: pr/no-changelog, backport/1.13, backport/1.14

#16966 Added backport labels to PR template checklist
  .github/pull_request_template.md
Labels: theme/contributing, pr/no-changelog, pr/no-backport

#16976 Backport of ci: split frontend ember jobs into release/1.15.x
  .github/workflows/frontend.yml
Labels: theme/contributing

#16974 Backport of ci: split frontend ember jobs into release/1.13.x
  .github/workflows/frontend.yml
Labels: theme/contributing

#16871 Memdb Txn Commit race condition fix
  .changelog/16871.txt
  agent/consul/state/memdb.go
  agent/consul/state/memdb_test.go
  agent/consul/state/mock_publishFuncType.go
Labels: pr/no-backport

#16984 Add Sameness Groups to Exported Services Structs in the API Package
  api/config_entry_exports.go
Labels: theme/api, pr/no-changelog, pr/no-backport

#16906 circleci: remove frontend jobs
  .circleci/config.yml
Labels: type/ci, pr/no-changelog, backport/1.13, backport/1.14, backport/1.15

#16956 Enforce ACLs on resource `Write` and `Delete` endpoints
  agent/grpc-external/services/resource/delete.go
  agent/grpc-external/services/resource/delete_test.go
  agent/grpc-external/services/resource/write.go
  agent/grpc-external/services/resource/write_test.go
  internal/resource/demo/demo.go
  internal/resource/registry.go
  internal/resource/registry_test.go
Labels: pr/no-changelog, pr/no-backport

#16891 Update list of Envoy versions
  .changelog/16891.txt
  .circleci/config.yml
  agent/xds/envoy_versioning_test.go
  agent/xds/proxysupport/proxysupport.go
  website/content/docs/connect/proxies/envoy.mdx
Labels: type/docs, type/ci, theme/envoy/xds, pr/no-backport

#16888 Update list of Envoy versions
  .changelog/16888.txt
  .circleci/config.yml
  agent/xds/envoy_versioning_test.go
  agent/xds/proxysupport/proxysupport.go
  website/content/docs/connect/proxies/envoy.mdx
Labels: type/docs, type/ci, theme/envoy/xds, pr/no-backport

#16889 Update list of Envoy versions
  .changelog/16889.txt
  .circleci/config.yml
  envoyextensions/xdscommon/envoy_versioning_test.go
  envoyextensions/xdscommon/proxysupport.go
  website/content/docs/connect/proxies/envoy.mdx
Labels: backport/1.15

#16958 Add mutate hook to `Write` endpoint
  agent/grpc-external/services/resource/write.go
  agent/grpc-external/services/resource/write_test.go
  internal/resource/demo/demo.go
  internal/resource/registry.go
  internal/resource/registry_test.go
Labels: pr/no-changelog, pr/no-backport

#16931 upgrade test: config nodeName, nodeid, and inherited persistent data for consul container
  test/integration/consul-container/go.mod
  test/integration/consul-container/go.sum
  test/integration/consul-container/libs/cluster/agent.go
  test/integration/consul-container/libs/cluster/builder.go
  test/integration/consul-container/libs/cluster/container.go
Labels: pr/no-changelog, backport/1.15

#16989 Backport of Update list of Envoy versions into release/1.15.x
  .changelog/16889.txt
  .circleci/config.yml
  envoyextensions/xdscommon/envoy_versioning_test.go
  envoyextensions/xdscommon/proxysupport.go
  website/content/docs/connect/proxies/envoy.mdx
Labels: type/docs, type/ci

#16985 Refactor order-by-locality Sameness Test Setup
  agent/proxycfg/testing_upstreams.go
  agent/proxycfg/testing_upstreams_oss.go
Labels: pr/no-changelog, pr/no-backport

#16977 Backport of feat: add reporting config with reload
  agent/agent.go
  agent/agent_oss_test.go
  agent/config/builder_oss.go
  agent/config/builder_oss_test.go
  agent/config/config.go
  agent/config/runtime.go
  agent/config/runtime_oss_test.go
  agent/config/testdata/TestRuntimeConfig_Sanitize.golden
  agent/config/testdata/full-config.hcl
  agent/config/testdata/full-config.json
  agent/consul/config.go
  agent/consul/server.go
  agent/consul/server_oss.go
  agent/consul/server_oss_test.go
Labels: theme/config, pr/no-changelog, pr/no-backport

#16996 Fix delete when uid not provided
  agent/grpc-external/services/resource/delete.go
  agent/grpc-external/services/resource/delete_test.go
Labels: pr/no-changelog, pr/no-backport

#16983 Enforce Owner rules in `Write` endpoint
  agent/grpc-external/services/resource/server.go
  agent/grpc-external/services/resource/write.go
  agent/grpc-external/services/resource/write_test.go
Labels: pr/no-changelog, pr/no-backport

#16997 add IP rate limiting config update
  agent/consul/rate/handler.go
  agent/consul/rate/handler_oss.go
  agent/consul/rate/handler_test.go
  agent/consul/rate/mock_LeaderStatusProvider_test.go
  agent/consul/rate/mock_RequestLimitsHandler.go
  agent/consul/server.go
  agent/consul/server_test.go
Labels: pr/no-changelog, pr/no-backport

#16998 added sameness group OSS changes to support DNS
  agent/agent.go
  agent/consul/fsm/fsm.go
  agent/consul/state/config_entry_events.go
  agent/consul/state/events.go
  agent/consul/state/events_test.go
  agent/consul/state/memdb.go
  agent/dns.go
  agent/dns_oss.go
  agent/proxycfg-glue/config_entry.go
  agent/proxycfg-glue/intentions.go
  agent/proxycfg-glue/service_list.go
  agent/rpcclient/common.go
  agent/rpcclient/configentry/configentry.go
  agent/rpcclient/configentry/configentry_test.go
  agent/rpcclient/configentry/view.go
  agent/rpcclient/configentry/view_test.go
  agent/rpcclient/health/health.go
  agent/rpcclient/health/health_test.go
  agent/rpcclient/health/view.go
  agent/rpcclient/health/view_test.go
  agent/submatview/store.go
  agent/submatview/store_integration_test.go
  proto/private/pbconfigentry/config_entry.gen.go
  proto/private/pbconfigentry/config_entry.go
  proto/private/pbconfigentry/config_entry.pb.binary.go
  proto/private/pbconfigentry/config_entry.pb.go
  proto/private/pbconfigentry/config_entry.proto
  proto/private/pbsubscribe/subscribe.pb.go
  proto/private/pbsubscribe/subscribe.proto
  test/integration/consul-container/test/upgrade/README.md
Labels: pr/no-changelog, pr/no-backport

#17005 added missing error message content to troubleshooting
  website/content/docs/troubleshoot/common-errors.mdx
Labels: type/docs, pr/no-changelog, pr/no-metrics-test, backport/1.15

#17008 Backport of added missing error message content to troubleshooting into release/1.15.x
  website/content/docs/troubleshoot/common-errors.mdx
Labels: type/docs

#17007 Add PrioritizeByLocality to config entries.
  agent/consul/discoverychain/compile.go
  agent/structs/config_entry.go
  agent/structs/config_entry_discoverychain.go
  agent/structs/config_entry_discoverychain_oss.go
  agent/structs/config_entry_test.go
  agent/structs/discovery_chain.go
  agent/structs/structs.deepcopy.go
  api/config_entry.go
  api/config_entry_discoverychain.go
  proto/private/pbconfigentry/config_entry.gen.go
  proto/private/pbconfigentry/config_entry.pb.binary.go
  proto/private/pbconfigentry/config_entry.pb.go
  proto/private/pbconfigentry/config_entry.proto
  proto/private/pbsubscribe/subscribe.pb.go
Labels: theme/api, pr/no-changelog, pr/no-backport

#17009 fixed bad link
  website/content/docs/troubleshoot/common-errors.mdx
Labels: type/docs, pr/no-changelog, pr/no-metrics-test, backport/1.15

#17010 Backport of fixed bad link into release/1.15.x
  website/content/docs/troubleshoot/common-errors.mdx
Labels: type/docs

#17017 added an intro statement for the SI conf entry confiration model
  website/content/docs/connect/config-entries/service-intentions.mdx
Labels: type/docs, pr/no-changelog, pr/no-metrics-test, backport/1.15

#17018 Backport of added an intro statement for the SI conf entry confiration model into release/1.15.x
  website/content/docs/connect/config-entries/service-intentions.mdx
Labels: type/docs

#17004 Tenancy wildcard validaton for `Write`, `Read`, and `Delete` endpoints
  agent/grpc-external/services/resource/delete.go
  agent/grpc-external/services/resource/delete_test.go
  agent/grpc-external/services/resource/read.go
  agent/grpc-external/services/resource/read_test.go
  agent/grpc-external/services/resource/server.go
  agent/grpc-external/services/resource/write.go
  agent/grpc-external/services/resource/write_test.go
  internal/resource/demo/demo.go
Labels: pr/no-changelog, pr/no-backport

#17020 docs: update docs related to GH-16779
  CHANGELOG.md
  website/content/docs/release-notes/consul/v1_15_x.mdx
  website/content/docs/upgrading/upgrade-specific.mdx
Labels: type/docs, pr/no-changelog, backport/1.15

#17021 Backport of docs: update docs related to GH-16779 into release/1.15.x
  CHANGELOG.md
  website/content/docs/release-notes/consul/v1_15_x.mdx
  website/content/docs/upgrading/upgrade-specific.mdx
Labels: type/docs

#16978 server: wire up in-process Resource Service
  acl/resolver/danger.go
  agent/consul/server.go
  agent/grpc-external/services/peerstream/subscription_view.go
  agent/grpc-internal/pipe.go
  agent/grpc-internal/pipe_test.go
Labels: theme/acls, pr/no-changelog

#16887 add ability to start container tests in debug mode and attach a debugger
  GNUmakefile
  build-support/docker/Consul-Dev-Dbg.dockerfile
  test/integration/consul-container/libs/cluster/agent.go
  test/integration/consul-container/libs/cluster/builder.go
  test/integration/consul-container/libs/cluster/cluster.go
  test/integration/consul-container/libs/cluster/container.go
  test/integration/consul-container/libs/utils/version.go
  test/integration/consul-container/test/snapshot/snapshot_restore_test.go
  test/integration/consul-container/test/upgrade/basic_test.go
  test/integration/consul-container/test/upgrade/fullstopupgrade_test.go
  test/integration/consul-container/test/upgrade/healthcheck_test.go
Labels: pr/no-changelog, pr/no-backport

#16991 feat: set up reporting agent
  agent/consul/acl_server.go
  agent/consul/leader.go
  agent/consul/leader_connect.go
  agent/consul/leader_intentions.go
  agent/consul/leader_intentions_test.go
  agent/consul/leader_test.go
  agent/consul/reporting/reporting.go
  agent/consul/reporting/reporting_oss.go
  agent/consul/server.go
  agent/consul/server_oss.go
  agent/consul/system_metadata.go
  agent/consul/system_metadata_test.go
Labels: pr/dependencies, pr/no-changelog, backport/1.13, backport/1.14, backport/1.15

#15987 api: enable query options on agent force-leave endpoint
  .changelog/15987.txt
  api/agent.go
  api/agent_test.go
Labels: theme/api, meta/staleproof, pr/no-backport

#16754 Bump the golang.org/x/net to 0.7.0 to address CVE-2022-41723
  .changelog/16754.txt
  go.mod
  go.sum
Labels: pr/dependencies, backport/1.13, backport/1.14, backport/1.15

#16999 Don't send updates twice
  agent/hcp/manager_test.go
Labels: pr/no-changelog, backport/1.14, backport/1.15

#17027 Backport of Bump the golang.org/x/net to 0.7.0 to address CVE-2022-41723 into release/1.15.x
  .changelog/16754.txt
  go.mod
  go.sum
Labels: pr/dependencies

#17030 proxycfg: ensure that an irrecoverable error in proxycfg closes the x…
  .changelog/16497.txt
  agent/agent.go
  agent/config/builder.go
  agent/config/runtime.go
  agent/config/runtime_test.go
  agent/config/testdata/TestRuntimeConfig_Sanitize.golden
  agent/proxycfg-sources/local/sync.go
  agent/proxycfg/manager.go
  agent/proxycfg/state.go
  agent/proxycfg_test.go
  agent/testagent.go
Labels: theme/config, pr/no-backport

#16915 ci: add test-integrations
  .circleci/config.yml
  .github/workflows/test-integrations.yml
Labels: theme/contributing, pr/no-changelog, backport/1.13, backport/1.14, backport/1.15

#17040 Backport of ci: add test-integrations into release/1.14.x
  .circleci/config.yml
  .github/workflows/test-integrations.yml
Labels: type/docs, theme/api, theme/health-checks, theme/acls, theme/cli, theme/config, theme/ui, theme/connect, theme/tls, theme/telemetry, type/ci, pr/dependencies, theme/envoy/xds, theme/contributing, theme/internals, theme/certificates, theme/agent-cache, theme/consul-terraform-sync

#17041 Manual Backport of test-intergrations into release/1.15.x branch
  .circleci/config.yml
  .github/workflows/test-integrations.yml
Labels: type/docs, theme/api, theme/cli, theme/config, theme/ui, theme/tls, type/ci, pr/dependencies, theme/envoy/xds, theme/contributing, theme/internals, theme/certificates, theme/agent-cache, theme/consul-terraform-sync, pr/no-changelog, pr/no-backport

#17039 Backport of ci: add test-integrations into release/1.13.x
  .circleci/config.yml
  .github/workflows/test-integrations.yml
Labels: theme/contributing

#16928 ci: remove test-integrations CircleCI workflow
  .circleci/bash_env.sh
  .circleci/config.yml
  .circleci/scripts/rerun-fails-report.sh
  .circleci/terraform/load-test/.terraform.lock.hcl
  .circleci/terraform/load-test/main.tf
  .circleci/terraform/load-test/variables.tf
  .github/CONTRIBUTING.md
  .github/pr-labeler.yml
  .github/workflows/frontend.yml
  .github/workflows/nightly-test-1.12.x.yaml
  .github/workflows/nightly-test-1.13.x.yaml
  .github/workflows/nightly-test-1.14.x.yaml
  .github/workflows/nightly-test-1.15.x.yaml
  .github/workflows/nightly-test-main.yaml
  .github/workflows/reusable-lint.yml
  .github/workflows/test-integrations.yml
  GNUmakefile
  agent/checks/check_test.go
  agent/connect/ca/testing.go
  docs/README.md
  test/integration/connect/envoy/run-tests.sh
  test/load/README.md
  ui/packages/consul-ui/docs/upgrades.mdx
Labels: type/ci, pr/no-changelog, backport/1.13, backport/1.14, backport/1.15

#17048 Avoid decoding nil pointer in map walker
  .changelog/17048.txt
  lib/map_walker.go
  lib/map_walker_test.go
Labels: theme/internals, backport/1.13, backport/1.14, backport/1.15

#17049 ci: remove test-integrations CircleCI workflow in 1.15
  .circleci/bash_env.sh
  .circleci/config.yml
  .circleci/scripts/rerun-fails-report.sh
  .circleci/terraform/load-test/.terraform.lock.hcl
  .circleci/terraform/load-test/main.tf
  .circleci/terraform/load-test/variables.tf
  .github/CONTRIBUTING.md
  .github/pr-labeler.yml
  .github/workflows/frontend.yml
  .github/workflows/nightly-test-1.11.x.yaml
  .github/workflows/nightly-test-1.12.x.yaml
  .github/workflows/nightly-test-1.13.x.yaml
  .github/workflows/nightly-test-1.14.x.yaml
  .github/workflows/nightly-test-main.yaml
  .github/workflows/reusable-lint.yml
  .github/workflows/test-integrations.yml
  GNUmakefile
  agent/checks/check_test.go
  agent/connect/ca/testing.go
  docs/README.md
  test/integration/connect/envoy/run-tests.sh
  test/load/README.md
  ui/packages/consul-ui/docs/upgrades.mdx
Labels: theme/ui, theme/connect, type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#17053 Backport of Avoid decoding nil pointer in map walker into release/1.15.x
  .changelog/17048.txt
  lib/map_walker.go
  lib/map_walker_test.go
Labels: theme/internals

#17046 Revert "cache: refactor agent cache fetching to prevent unnecessary f…
  .changelog/16818.txt
  agent/agent_test.go
  agent/cache/cache.go
  agent/cache/cache_test.go
  agent/cache/entry.go
  agent/cache/watch.go
  agent/config/testdata/TestRuntimeConfig_Sanitize.golden
  agent/testagent.go
Labels: theme/config, theme/agent-cache, pr/no-changelog, pr/no-metrics-test, pr/no-backport

#17035 Permissive mTLS
  .changelog/17035.txt
  agent/configentry/merge_service_config.go
  agent/configentry/merge_service_config_test.go
  agent/configentry/resolve.go
  agent/configentry/resolve_test.go
  agent/consul/state/config_entry.go
  agent/consul/state/config_entry_test.go
  agent/structs/config_entry.go
  agent/structs/config_entry_mesh.go
  agent/structs/config_entry_test.go
  agent/structs/connect_proxy_config.go
  agent/xds/listeners.go
  agent/xds/listeners_test.go
  agent/xds/testdata/listeners/connect-proxy-with-tproxy-and-permissive-mtls.latest.golden
  api/config_entry.go
  api/config_entry_mesh.go
  api/config_entry_test.go
  proto/private/pbconfigentry/config_entry.gen.go
  proto/private/pbconfigentry/config_entry.go
  proto/private/pbconfigentry/config_entry.pb.go
  proto/private/pbconfigentry/config_entry.proto
  proto/private/pbservice/convert_test.go
  proto/private/pbservice/service.pb.go
  proto/private/pbservice/service.proto
Labels: theme/api, theme/envoy/xds, pr/no-backport

#17050 ci: remove test-integrations CircleCI workflow in 1.14 (#16928)
  .circleci/bash_env.sh
  .circleci/config.yml
  .circleci/scripts/rerun-fails-report.sh
  .circleci/terraform/load-test/.terraform.lock.hcl
  .circleci/terraform/load-test/main.tf
  .circleci/terraform/load-test/variables.tf
  .github/CONTRIBUTING.md
  .github/pr-labeler.yml
  .github/workflows/frontend.yml
  .github/workflows/nightly-test-1.11.x.yaml
  .github/workflows/nightly-test-1.12.x.yaml
  .github/workflows/nightly-test-1.13.x.yaml
  .github/workflows/nightly-test-main.yaml
  .github/workflows/reusable-lint.yml
  .github/workflows/test-integrations.yml
  GNUmakefile
  agent/checks/check_test.go
  agent/connect/ca/testing.go
  docs/README.md
  test/integration/connect/envoy/run-tests.sh
  test/load/README.md
  ui/packages/consul-ui/docs/upgrades.mdx
Labels: theme/ui, theme/connect, type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#17052 Backport of Avoid decoding nil pointer in map walker into release/1.14.x
  .changelog/17048.txt
  lib/map_walker.go
  lib/map_walker_test.go
Labels: theme/internals

#17051 Backport of Avoid decoding nil pointer in map walker into release/1.13.x
  .changelog/17048.txt
  lib/map_walker.go
  lib/map_walker_test.go
Labels: theme/internals

#17036 [NET-3090] Add new JWT provider config entry
  agent/consul/state/config_entry.go
  agent/consul/usagemetrics/usagemetrics_oss_test.go
  agent/structs/config_entry.go
  agent/structs/config_entry_jwt_provider.go
  agent/structs/config_entry_jwt_provider_oss.go
  agent/structs/config_entry_jwt_provider_test.go
  api/config_entry.go
  api/config_entry_jwt_provider.go
  api/config_entry_jwt_provider_test.go
Labels: theme/api, pr/do-not-merge, pr/no-changelog, pr/no-backport

#17037 [NET-3091] Update service intentions to support jwt provider references
  agent/consul/state/config_entry.go
  agent/consul/state/config_entry_schema.go
  agent/structs/config_entry_intentions.go
  agent/structs/config_entry_intentions_test.go
  agent/structs/intention.go
  agent/structs/structs.deepcopy.go
  api/config_entry_intentions.go
  proto/private/pbconfigentry/config_entry.gen.go
  proto/private/pbconfigentry/config_entry.pb.binary.go
  proto/private/pbconfigentry/config_entry.pb.go
  proto/private/pbconfigentry/config_entry.proto
Labels: theme/api, pr/no-changelog, pr/no-backport

#17056 ci: remove worklogs upload toget rid of warning
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing, pr/no-changelog, backport/1.13, backport/1.14, backport/1.15

#17058 Backport of ci: remove worklogs upload toget rid of warning into release/1.14.x
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing

#17059 Backport of ci: remove worklogs upload toget rid of warning into release/1.15.x
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing

#17032 fix broken links
  website/content/docs/connect/cluster-peering/tech-specs.mdx
  website/content/docs/connect/config-entries/service-resolver.mdx
  website/content/docs/connect/gateways/mesh-gateway/peering-via-mesh-gateways.mdx
  website/content/docs/enterprise/admin-partitions.mdx
  website/content/docs/k8s/helm.mdx
  website/content/docs/release-notes/consul/v1_14_x.mdx
  website/content/docs/upgrading/upgrade-specific.mdx
Labels: type/docs, pr/no-changelog, pr/no-backport

#17064 Add sameness groups to service intentions
  agent/connect/authz.go
  agent/connect/authz_test.go
  agent/connect_auth.go
  agent/consul/intention_endpoint.go
  agent/consul/intention_endpoint_test.go
  agent/consul/state/intention.go
  agent/consul/state/intention_oss.go
  agent/consul/state/intention_test.go
  agent/proxycfg-glue/glue.go
  agent/proxycfg-glue/intentions.go
  agent/proxycfg-glue/intentions_ent_test.go
  agent/proxycfg-glue/intentions_test.go
  agent/proxycfg/connect_proxy.go
  agent/proxycfg/manager_test.go
  agent/proxycfg/proxycfg.deepcopy.go
  agent/proxycfg/snapshot.go
  agent/proxycfg/state_test.go
  agent/proxycfg/terminating_gateway.go
  agent/proxycfg/testing.go
  agent/proxycfg/testing_connect_proxy.go
  agent/proxycfg/testing_terminating_gateway.go
  agent/structs/aclfilter/filter.go
  agent/structs/config_entry_intentions.go
  agent/structs/config_entry_intentions_oss.go
  agent/structs/config_entry_intentions_oss_test.go
  agent/structs/intention.go
  agent/structs/intention_test.go
  agent/structs/structs_filtering_test.go
  agent/xds/listeners.go
  agent/xds/rbac.go
  agent/xds/rbac_test.go
  api/connect_intention.go
  proto/private/pbconfigentry/config_entry.gen.go
  proto/private/pbconfigentry/config_entry.pb.go
  proto/private/pbconfigentry/config_entry.proto
Labels: theme/api, theme/connect, theme/envoy/xds, pr/no-changelog, pr/no-backport

#17019 Enforce operator:write acl on `WriteStatus` endpoint
  agent/grpc-external/services/resource/write_status.go
  agent/grpc-external/services/resource/write_status_test.go
Labels: pr/no-changelog, pr/no-backport

#17060 NET-3648: Add script to get consul and envoy version
  test/integration/consul-container/go.mod
  test/integration/consul-container/go.sum
  test/integration/consul-container/test/consul_envoy_version/consul_envoy_version.go
Labels: pr/no-changelog, backport/1.15

#17074 NET-3648: Add script to get consul and envoy version (#17060)
  test/integration/consul-container/go.mod
  test/integration/consul-container/go.sum
  test/integration/consul-container/test/consul_envoy_version/consul_envoy_version.go
Labels: pr/no-backport

#17077 fix the linter
  test/integration/consul-container/test/consul_envoy_version/consul_envoy_version.go
Labels: pr/no-changelog, pr/no-metrics-test, backport/1.15

#16936 Backport of [docs] fix typo in LocalRequestTimeoutMs into release/1.15.x
  website/content/docs/connect/config-entries/service-defaults.mdx
Labels: type/docs, pr/no-metrics-test

#17078 Fix a bug with sameness group disco chain config entry fetching
  agent/consul/state/config_entry.go
  agent/structs/config_entry_sameness_group.go
  api/config_entry_sameness_group.go
Labels: pr/no-changelog, pr/no-backport

#17031 Backport of feat: set up reporting agent into release/1.15.x
  agent/consul/acl_server.go
  agent/consul/leader.go
  agent/consul/leader_connect.go
  agent/consul/leader_intentions.go
  agent/consul/leader_intentions_test.go
  agent/consul/leader_test.go
  agent/consul/reporting/reporting.go
  agent/consul/reporting/reporting_oss.go
  agent/consul/server.go
  agent/consul/server_oss.go
  agent/consul/system_metadata.go
  agent/consul/system_metadata_test.go
Labels: pr/no-changelog, pr/no-backport

#16815 Add manual virtual IP support to state store
  agent/consul/fsm/commands_oss.go
  agent/consul/state/catalog.go
  agent/consul/state/catalog_schema.go
  agent/consul/state/catalog_test.go
  agent/structs/structs.go
Labels: pr/no-changelog, pr/no-backport

#16862 Include virtual services from discovery chain in intention topology
  agent/consul/state/catalog.go
  agent/consul/state/intention.go
  agent/consul/state/intention_test.go
Labels: pr/no-changelog, pr/no-backport

#17085 Backport of ci: fix test splits that have less test packages than runner count from hanging into release/1.15.x
  .github/workflows/test-integrations.yml
Labels: type/docs, theme/api, theme/cli, theme/config, theme/ui, theme/connect, theme/tls, type/ci, pr/dependencies, theme/envoy/xds, theme/contributing, theme/internals, theme/certificates, theme/agent-cache, theme/consul-terraform-sync

#17081 Bump raft to 1.5.0
  .changelog/17081.txt
  go.mod
  go.sum
Labels: pr/dependencies, backport/1.15

#17087 De-scope tenenacy requirements to OSS only for now.
  agent/grpc-external/services/resource/delete_test.go
  agent/grpc-external/services/resource/read_test.go
  agent/grpc-external/services/resource/server.go
  agent/grpc-external/services/resource/write.go
  agent/grpc-external/services/resource/write_test.go
Labels: pr/no-changelog, pr/no-backport

#17088 Backport 1.15: Bump raft to 1.5.0 (#17081)
  .changelog/17081.txt
  .github/workflows/test-integrations.yml
  go.mod
  go.sum
  test/integration/consul-container/go.mod
  test/integration/consul-container/go.sum
Labels: pr/dependencies, pr/no-backport

#17099 Fix virtual services being included in intention topology as downstreams
  agent/consul/state/intention.go
Labels: pr/no-changelog, pr/no-backport

#17102 Merge pull request #5200 from hashicorp/NET-3758
  .changelog/5200.txt
  .github/workflows/test-integrations.yml
  envoyextensions/xdscommon/envoy_versioning_test.go
  envoyextensions/xdscommon/proxysupport.go
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#17104 CI: remove uneeded AWS creds from test-integrations
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing, pr/no-changelog, backport/1.13, backport/1.14, backport/1.15

#17089 Add sameness group field to prepared queries
  agent/consul/discoverychain/compile.go
  agent/consul/prepared_query/walk_test.go
  agent/consul/prepared_query_endpoint.go
  agent/consul/prepared_query_endpoint_oss.go
  agent/consul/prepared_query_endpoint_oss_test.go
  agent/consul/prepared_query_endpoint_test.go
  agent/consul/state/config_entry_sameness_group.go
  agent/structs/config_entry_sameness_group_oss.go
  agent/structs/prepared_query.go
  agent/structs/prepared_query_test.go
  api/prepared_query.go
  website/content/api-docs/query.mdx
Labels: type/docs, theme/api, pr/no-changelog, pr/no-backport

#16994 APIGW Normalize Status Conditions
  agent/consul/fsm/commands_oss_test.go
  agent/consul/fsm_data_store.go
  agent/consul/gateways/controller_gateways.go
  agent/consul/gateways/controller_gateways_test.go
  agent/structs/config_entry_status.go
  api/config_entry_status.go
  api/config_entry_status_test.go
  api/go.mod
  api/go.sum
  envoyextensions/go.mod
  envoyextensions/go.sum
  go.mod
  go.sum
  test/integration/consul-container/go.mod
  test/integration/consul-container/go.sum
  test/integration/consul-container/test/gateways/gateway_endpoint_test.go
  troubleshoot/go.mod
  troubleshoot/go.sum
Labels: pr/no-changelog, pr/no-docs, backport/1.15

#17110 Backport of ci: fix runner calculation to exclude the top level directory as part of the calculation into release/1.14.x
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing

#17105 remove envoy endpoint flag from k8s docs
  website/content/docs/k8s/k8s-cli.mdx
Labels: type/docs, pr/no-changelog, backport/1.15

#17116 Backport of remove envoy endpoint flag from k8s docs into release/1.15.x
  website/content/docs/k8s/k8s-cli.mdx
Labels: type/docs

#17082 Clarify OpenTelemetry support for tracing
  website/content/docs/connect/distributed-tracing.mdx
Labels: type/docs, pr/no-changelog, pr/no-metrics-test, backport/1.15

#17111 Backport of ci: fix runner calculation to exclude the top level directory as part of the calculation into release/1.15.x
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing

#17117 Backport of Clarify OpenTelemetry support for tracing into release/1.15.x
  website/content/docs/connect/distributed-tracing.mdx
Labels: type/docs

#17093 Fix broken link in changelog
  CHANGELOG.md
Labels: type/docs, pr/no-changelog, pr/no-metrics-test, pr/no-backport

#17067 storage: fix bug where `WatchList` would (rarely) return duplicate events
  internal/storage/inmem/watch.go
Labels: pr/no-changelog

#17016 Controller Supervision
  agent/consul/server.go
  agent/grpc-external/services/resource/delete_test.go
  agent/grpc-external/services/resource/list_test.go
  agent/grpc-external/services/resource/read_test.go
  agent/grpc-external/services/resource/watch_test.go
  agent/grpc-external/services/resource/write_status_test.go
  agent/grpc-external/services/resource/write_test.go
  internal/controller/api.go
  internal/controller/controller.go
  internal/controller/lease.go
  internal/controller/manager.go
  internal/controller/supervisor.go
  internal/controller/supervisor_test.go
  internal/resource/demo/controller.go
  internal/resource/demo/demo.go
  lib/retry/retry.go
  logging/names.go
Labels: theme/telemetry, theme/internals, pr/no-changelog

#17120 De-flake snapshot test
  test/integration/consul-container/test/snapshot/snapshot_restore_test.go
Labels: pr/no-changelog, pr/no-backport

#17112 CI: remove uneeded AWS creds from test-integrations
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing, pr/no-backport

#17113 CI: remove uneeded AWS creds from test-integrations
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing, pr/no-backport

#17114 CI: remove uneeded AWS creds from test-integrations
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing, pr/no-backport
