Repository hashicorp/consul, pull requests merged in 2024-07, with the labels that each got.

#21384 Update retryable-http-client to resolve CVE-2024-6104
  .changelog/21384.txt
  go.mod
  go.sum
  test-integ/go.mod
  test-integ/go.sum
  test/integration/consul-container/go.mod
  test/integration/consul-container/go.sum
Labels: pr/dependencies, backport/all

#21510 security: fix AliasCheck panic (update)
  agent/checks/alias.go
Labels: pr/no-changelog, backport/all

#21513 Backport of NET-10288-Bump-go-to-resolve-CVE-2024-24791 into release/1.19.x
  .changelog/21507.txt
  .go-version
  go.mod
Labels: pr/dependencies

#21519 fix(txn): validate verbs
  .changelog/21519.txt
  agent/consul/kvs_endpoint.go
  agent/consul/state/txn.go
  agent/consul/state/txn_test.go
  agent/consul/txn_endpoint.go
  agent/consul/txn_endpoint_test.go
Labels: backport/1.19

#21245 [NET-5622] build: consolidate Envoy version management
  .github/workflows/nightly-test-integ-peering_commontopo.yml
  .github/workflows/nightly-test-integrations-1.15.x.yml
  .github/workflows/nightly-test-integrations-1.17.x.yml
  .github/workflows/nightly-test-integrations-1.18.x.yml
  .github/workflows/nightly-test-integrations-1.19.x.yml
  .github/workflows/nightly-test-integrations.yml
  .github/workflows/reusable-get-envoy-versions.yml
  .github/workflows/reusable-get-go-version.yml
  .github/workflows/test-integrations.yml
  Makefile
  command/connect/envoy/envoy.go
  command/connect/envoy/envoy_test.go
  envoyextensions/xdscommon/ENVOY_VERSIONS
  envoyextensions/xdscommon/envoy_versioning.go
  envoyextensions/xdscommon/envoy_versioning_test.go
  envoyextensions/xdscommon/proxysupport.go
  envoyextensions/xdscommon/proxysupport_test.go
  test/integration/connect/envoy/helpers.bash
  test/integration/connect/envoy/run-tests.sh
Labels: theme/cli, type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#21381 fix(dns): spam ttl logs for prepared queries
  .changelog/21381.txt
  agent/discovery/query_fetcher_v1.go
Labels: backport/1.19, backport/ent/1.18

#21378 [ui] Namespaced and file-specified deps for consul-ui
  .changelog/21378.txt
  ui/.yarnrc
  ui/package.json
  ui/packages/consul-ui/package.json
  ui/yarn.lock
Labels: theme/ui, backport/all

#21523 Backport of [ui] Namespaced and file-specified deps for consul-ui into release/1.19.x
  .changelog/21378.txt
  ui/.yarnrc
  ui/package.json
  ui/packages/consul-ui/package.json
  ui/yarn.lock
Labels: theme/ui

#21524 [NET-10290] Update ENVOY_VERSIONS
  .changelog/21524.txt
  envoyextensions/xdscommon/ENVOY_VERSIONS
Labels: theme/security, backport/all

#21292 Backport of [NET-5622] build: consolidate Envoy version management to release/1.19.x
  .github/workflows/reusable-get-envoy-versions.yml
  .github/workflows/reusable-get-go-version.yml
  .github/workflows/test-integrations.yml
  Makefile
  command/connect/envoy/envoy.go
  command/connect/envoy/envoy_test.go
  envoyextensions/xdscommon/ENVOY_VERSIONS
  envoyextensions/xdscommon/envoy_versioning.go
  envoyextensions/xdscommon/envoy_versioning_test.go
  envoyextensions/xdscommon/proxysupport.go
  envoyextensions/xdscommon/proxysupport_test.go
  test/integration/connect/envoy/helpers.bash
  test/integration/connect/envoy/run-tests.sh
Labels: theme/cli, type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#21527 Use debian:12 instead of centos:7 for artifact verification
  .github/scripts/verify_artifact.sh
Labels: theme/contributing, pr/no-changelog, backport/all

#21530 Use vault.centos.org instead of mirror.centos.org
  .github/scripts/verify_artifact.sh
  .github/scripts/verify_rpm.sh
Labels: theme/contributing, pr/no-changelog, pr/no-backport

#21531 Backport of Use vault.centos.org instead of mirror.centos.org into release/1.19.x
  .github/scripts/verify_artifact.sh
  .github/scripts/verify_rpm.sh
Labels: theme/contributing

#21382 [NET-10246] use correct enterprise meta for service name for LinkedService
  .changelog/21382.txt
  agent/consul/state/catalog.go
Labels: backport/all

#21291 Backport of Fix broken link in wal-logstore/index.mdx into release/1.19.x
  website/content/docs/agent/wal-logstore/index.mdx
Labels: type/docs

#21537 Update CHANGELOG.md
  CHANGELOG.md
Labels: pr/no-changelog, backport/1.19

#21538 Update CHANGELOG.md + VERSION
  CHANGELOG.md
  version/VERSION
Labels: pr/no-changelog, pr/no-backport

#21540 Update VERSION to prepare for 1.19.2-dev
  version/VERSION
Labels: pr/no-changelog, pr/no-backport

#21539 Add changelog entries for 1.15.13, 1.17.6, 1.18.3 and 1.19.1
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-backport

#21545 docs/WAF: failure zones refresh
  website/content/docs/architecture/improving-consul-resilience.mdx
  website/public/img/architecture/cluster-peering-diagram-dark.png
  website/public/img/architecture/cluster-peering-diagram-light.png
  website/public/img/architecture/cluster-peering-diagram.png
  website/public/img/architecture/consul-redundancy-zones-dark.png
  website/public/img/architecture/consul-redundancy-zones-light.png
  website/public/img/architecture/consul-singleDC-redundancyzones.png
Labels: type/docs, pr/no-changelog, pr/no-metrics-test, backport/all

#21553 Backport of docs/WAF: failure zones refresh into release/1.19.x
  website/content/docs/architecture/improving-consul-resilience.mdx
Labels: type/docs

#20800 [NET-7787] Update JWT docs for APIGateway
  website/content/docs/connect/gateways/api-gateway/secure-traffic/verify-jwts-k8s.mdx
  website/content/docs/connect/gateways/api-gateway/secure-traffic/verify-jwts-vms.mdx
Labels: type/docs, pr/no-changelog, pr/no-backport, backport/1.17, backport/1.19, backport/1.18

#21568 docs: Clarify cluster peering vs WAN federation comparison
  website/content/docs/connect/cluster-peering/index.mdx
Labels: type/docs, pr/no-changelog, pr/no-metrics-test, backport/all

#21569 Backport of docs: Clarify cluster peering vs WAN federation comparison into release/1.19.x
  website/content/docs/connect/cluster-peering/index.mdx
Labels: type/docs

#21572 ci: Update backport-assistant to 0.4.4
  .github/workflows/backport-assistant.yml
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#21570 ci: use workflow-scoped GH PAT for backports
  .github/workflows/backport-assistant.yml
Labels: type/ci, theme/contributing, pr/no-changelog, backport/all

#21573 Backport of ci: use workflow-scoped GH PAT for backports into release/1.19.x
  .github/workflows/backport-assistant.yml
Labels: type/ci, theme/contributing
