Repository hashicorp/consul, pull requests merged in 2024-01, with the labels that each got.

#19780 [DO NOT MERGE UNTIL EOY] update year in LICENSE and copywrite files
  .copywrite.hcl
  LICENSE
  api/.copywrite.hcl
  sdk/.copywrite.hcl
Labels: pr/no-changelog, backport/1.17

#20068 ci: increase runner size for security scans
  .github/workflows/security-scan.yml
Labels: type/ci, theme/contributing, pr/no-changelog, backport/1.15, backport/1.16, backport/1.17

#20070 Backport of ci: increase runner size for security scans into release/1.16.x
  .github/workflows/security-scan.yml
Labels: type/ci, theme/contributing

#20009 fix: add test which has been removed for metrics to unblock CI
  ui/packages/consul-partitions/app/components/consul/partition/selector/index.hbs
  ui/packages/consul-ui/tests/acceptance/dc/services/show/topology/metrics.feature
Labels: theme/ui, pr/no-changelog, pr/no-metrics-test, backport/1.17

#20052 Backport into 1.15 of NET-6944 - Replace usage of deprecated Envoy field envoy.extensions.filters.http.lua.v3.Lua.inline_code
  .changelog/20012.txt
  agent/envoyextensions/builtin/lua/lua.go
  agent/xds/testdata/builtin_extension/listeners/lambda-and-lua-connect-proxy.latest.golden
  agent/xds/testdata/builtin_extension/listeners/lua-inbound-applies-to-inbound.latest.golden
  agent/xds/testdata/builtin_extension/listeners/lua-inbound-doesnt-apply-to-local-upstreams.latest.golden
  agent/xds/testdata/builtin_extension/listeners/lua-outbound-applies-to-local-upstreams-tproxy.latest.golden
  agent/xds/testdata/builtin_extension/listeners/lua-outbound-applies-to-local-upstreams.latest.golden
Labels: pr/no-backport

#20075 Fix upgrade test envoy version
  .github/workflows/nightly-test-integrations.yml
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#19999 upgrade test(LTS): import remaining agent config from usage profile
  testing/deployer/sprawl/internal/tfgen/agent.go
  testing/deployer/topology/topology.go
Labels: pr/no-changelog, pr/no-backport

#20077 feat(v2): add consul service and workloads to catalog
  agent/consul/leader.go
  agent/consul/leader_registrator_v1.go
  agent/consul/leader_registrator_v1_test.go
  agent/consul/leader_registrator_v2.go
  agent/consul/leader_registrator_v2_test.go
  agent/consul/leader_test.go
  agent/consul/server.go
  agent/consul/server_test.go
  testrpc/wait.go
Labels: pr/no-changelog, pr/no-backport

#20079 Clean up and make the changelog entries consistent for the replacement of Envoy deprecated fields.
  .changelog/19940.txt
  .changelog/20010.txt
  .changelog/20011.txt
  .changelog/20012.txt
  .changelog/20013.txt
Labels: pr/no-changelog, pr/no-backport

#20078 NET-6945 - Replace usage of deprecated Envoy field envoy.config.core.v3.HeaderValueOption.append
  .changelog/20078.txt
  agent/xds/routes.go
  agent/xds/testdata/routes/api-gateway-with-http-route-timeoutfilter-one-set.latest.golden
  agent/xds/testdata/routes/api-gateway-with-http-route.latest.golden
  agent/xds/testdata/routes/connect-proxy-splitter-overweight.latest.golden
  agent/xds/testdata/routes/connect-proxy-with-chain-and-router.latest.golden
  agent/xds/testdata/routes/connect-proxy-with-chain-and-splitter.latest.golden
  agent/xds/testdata/routes/ingress-with-chain-and-router-header-manip.latest.golden
  agent/xds/testdata/routes/ingress-with-chain-and-router.latest.golden
  agent/xds/testdata/routes/ingress-with-chain-and-splitter.latest.golden
  agent/xds/testdata/routes/xds-fetch-timeout-ms-ingress-with-router.latest.golden
  agent/xds/testdata/routes/xds-fetch-timeout-ms-sidecar.latest.golden
  agent/xdsv2/route_resources.go
  proto-public/pbmesh/v2beta1/pbproxystate/header_mutations.pb.go
  proto-public/pbmesh/v2beta1/pbproxystate/header_mutations.proto
Labels: theme/envoy/xds, pr/no-backport

#20082 Add listeners to meshgateway spec
  proto-public/pbmesh/v2beta1/mesh_gateway.pb.binary.go
  proto-public/pbmesh/v2beta1/mesh_gateway.pb.go
  proto-public/pbmesh/v2beta1/mesh_gateway.proto
  proto-public/pbmesh/v2beta1/mesh_gateway_deepcopy.gen.go
  proto-public/pbmesh/v2beta1/mesh_gateway_json.gen.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#20083 Revert "Backport of NET-6943 - Replace usage of deprecated Envoy field envoy.config.router.v3.WeightedCluster.total_weight. into release/1.15.x (#20059)
  .changelog/20011.txt
  agent/xds/routes.go
  agent/xds/testdata/routes/connect-proxy-lb-in-resolver.latest.golden
  agent/xds/testdata/routes/connect-proxy-with-chain-and-router.latest.golden
  agent/xds/testdata/routes/connect-proxy-with-chain-and-splitter.latest.golden
  agent/xds/testdata/routes/ingress-lb-in-resolver.latest.golden
  agent/xds/testdata/routes/ingress-splitter-with-resolver-redirect.latest.golden
  agent/xds/testdata/routes/ingress-with-chain-and-router-header-manip.latest.golden
  agent/xds/testdata/routes/ingress-with-chain-and-router.latest.golden
  agent/xds/testdata/routes/ingress-with-chain-and-splitter.latest.golden
  agent/xds/testdata/routes/mesh-gateway-with-exported-peered-services-http-with-router.latest.golden
  agent/xds/testdata/routes/splitter-with-resolver-redirect.latest.golden
  agent/xds/testdata/routes/xds-fetch-timeout-ms-ingress-with-router.latest.golden
  agent/xds/testdata/routes/xds-fetch-timeout-ms-sidecar.latest.golden
  troubleshoot/proxy/testdata/upstreams/config.json
Labels: pr/no-backport

#20049 docs/consul: rename the Vault secret engine for Consul integration
  website/content/docs/k8s/deployment-configurations/vault/data-integration/bootstrap-token.mdx
  website/content/docs/k8s/deployment-configurations/vault/data-integration/enterprise-license.mdx
  website/content/docs/k8s/deployment-configurations/vault/data-integration/gossip.mdx
  website/content/docs/k8s/deployment-configurations/vault/data-integration/index.mdx
  website/content/docs/k8s/deployment-configurations/vault/data-integration/partition-token.mdx
  website/content/docs/k8s/deployment-configurations/vault/data-integration/replication-token.mdx
  website/content/docs/k8s/deployment-configurations/vault/data-integration/snapshot-agent-config.mdx
  website/content/docs/k8s/deployment-configurations/vault/systems-integration.mdx
  website/content/docs/k8s/deployment-configurations/vault/wan-federation.mdx
Labels: type/docs, pr/no-changelog, pr/no-metrics-test, backport/1.13, backport/1.14, backport/1.15, backport/1.16, backport/1.17

#19801 docs: remove unsupported critical flag from DNS weights
  website/content/docs/services/configuration/services-configuration-reference.mdx
Labels: type/docs, pr/no-changelog, backport/1.15, backport/1.16, backport/1.17

#20099 Backport of docs: remove unsupported critical flag from DNS weights into release/1.17.x
  website/content/docs/services/configuration/services-configuration-reference.mdx
Labels: type/docs

#20098 Backport of docs: remove unsupported critical flag from DNS weights into release/1.16.x
  website/content/docs/services/configuration/services-configuration-reference.mdx
Labels: type/docs

#20101 Use safeio to write server metadata file
  agent/agent.go
  agent/consul/server_metadata.go
Labels: pr/no-changelog, backport/1.15, backport/1.16, backport/1.17

#20103 Break up DNS tests into 3 files to help with GH UI and IDE issues.
  agent/dns_node_lookup_test.go
  agent/dns_service_lookup_test.go
  agent/dns_test.go
Labels: pr/no-changelog, pr/no-backport

#20100 Add sameness group references in exported services controller
  agent/consul/server.go
  internal/multicluster/exports.go
  internal/multicluster/internal/controllers/exportedservices/builder.go
  internal/multicluster/internal/controllers/exportedservices/controller.go
  internal/multicluster/internal/controllers/exportedservices/controller_test.go
  internal/multicluster/internal/controllers/exportedservices/expander/expander_ce.go
  internal/multicluster/internal/controllers/exportedservices/expander/expander_ce/expander.go
  internal/multicluster/internal/controllers/exportedservices/expander/expander_ce/expander_test.go
  internal/multicluster/internal/controllers/exportedservices/expander/types/types.go
  internal/multicluster/internal/controllers/exportedservices/helpers_ce.go
  internal/multicluster/internal/controllers/register.go
Labels: pr/no-changelog, pr/no-backport, consul-india

#20092 Backport of docs/consul: rename the Vault secret engine for Consul integration into release/1.17.x
  website/content/docs/k8s/deployment-configurations/vault/data-integration/bootstrap-token.mdx
  website/content/docs/k8s/deployment-configurations/vault/data-integration/enterprise-license.mdx
  website/content/docs/k8s/deployment-configurations/vault/data-integration/gossip.mdx
  website/content/docs/k8s/deployment-configurations/vault/data-integration/index.mdx
  website/content/docs/k8s/deployment-configurations/vault/data-integration/partition-token.mdx
  website/content/docs/k8s/deployment-configurations/vault/data-integration/replication-token.mdx
  website/content/docs/k8s/deployment-configurations/vault/data-integration/snapshot-agent-config.mdx
  website/content/docs/k8s/deployment-configurations/vault/systems-integration.mdx
  website/content/docs/k8s/deployment-configurations/vault/wan-federation.mdx
Labels: type/docs

#20094 Backport of docs/consul: rename the Vault secret engine for Consul integration into release/1.15.x
  website/content/docs/k8s/deployment-configurations/vault/data-integration/bootstrap-token.mdx
  website/content/docs/k8s/deployment-configurations/vault/data-integration/enterprise-license.mdx
  website/content/docs/k8s/deployment-configurations/vault/data-integration/gossip.mdx
  website/content/docs/k8s/deployment-configurations/vault/data-integration/index.mdx
  website/content/docs/k8s/deployment-configurations/vault/data-integration/partition-token.mdx
  website/content/docs/k8s/deployment-configurations/vault/data-integration/replication-token.mdx
  website/content/docs/k8s/deployment-configurations/vault/data-integration/snapshot-agent-config.mdx
  website/content/docs/k8s/deployment-configurations/vault/systems-integration.mdx
  website/content/docs/k8s/deployment-configurations/vault/wan-federation.mdx
Labels: type/docs

#19976 [CC-7041] Update and start the SCADA provider in HCP manager
  agent/agent.go
  agent/agent_test.go
  agent/consul/config.go
  agent/consul/config_cloud.go
  agent/consul/server.go
  agent/hcp/deps.go
  agent/hcp/manager.go
  agent/hcp/manager_test.go
  agent/hcp/scada/mock_Provider.go
  agent/hcp/scada/scada.go
  agent/hcp/scada/scada_test.go
  go.mod
  go.sum
Labels: pr/dependencies, pr/no-changelog, pr/no-backport

#20114 Make DNS test run across a matrix of dns and catalog versions.
  agent/dns_node_lookup_test.go
  agent/dns_service_lookup_test.go
  agent/dns_test.go
Labels: pr/no-changelog, pr/no-backport

#20030 Adjust type + field names for ComputedExportedServices
  internal/multicluster/internal/controllers/exportedservices/builder.go
  internal/multicluster/internal/controllers/exportedservices/controller_test.go
  internal/multicluster/internal/types/computed_exported_services_test.go
  internal/multicluster/internal/types/helpers_ce.go
  proto-public/pbmulticluster/v2beta1/computed_exported_services.pb.binary.go
  proto-public/pbmulticluster/v2beta1/computed_exported_services.pb.go
  proto-public/pbmulticluster/v2beta1/computed_exported_services.proto
  proto-public/pbmulticluster/v2beta1/computed_exported_services_deepcopy.gen.go
  proto-public/pbmulticluster/v2beta1/computed_exported_services_json.gen.go
Labels: pr/no-changelog, pr/no-backport

#20058 ci: Single source of truth for Go version in CI and Dockerfile
  .github/workflows/build-artifacts.yml
  .github/workflows/build-distros.yml
  .github/workflows/build.yml
  .github/workflows/go-tests.yml
  .github/workflows/nightly-test-integ-peering_commontopo.yml
  .github/workflows/nightly-test-integrations-1.15.x.yml
  .github/workflows/nightly-test-integrations-1.16.x.yml
  .github/workflows/nightly-test-integrations-1.17.x.yml
  .github/workflows/nightly-test-integrations.yml
  .github/workflows/reusable-check-go-mod.yml
  .github/workflows/reusable-dev-build-windows.yml
  .github/workflows/reusable-dev-build.yml
  .github/workflows/reusable-get-go-version.yml
  .github/workflows/reusable-lint.yml
  .github/workflows/reusable-unit-split.yml
  .github/workflows/reusable-unit.yml
  .github/workflows/security-scan.yml
  .github/workflows/test-integrations-windows.yml
  .github/workflows/test-integrations.yml
  .go-version
  Makefile
  build-support/docker/Build-Go.dockerfile
Labels: type/ci, theme/contributing, pr/no-changelog, backport/1.15, backport/1.16, backport/1.17

#20085 [NET-6426] Modify Reconcile Loop for Mesh Gateway Resources to Correctly Write Proxy State Template
  internal/mesh/internal/controllers/gatewayproxy/builder/builder.go
  internal/mesh/internal/controllers/gatewayproxy/controller.go
  internal/mesh/internal/controllers/gatewayproxy/fetcher/data_fetcher.go
  internal/mesh/internal/controllers/gatewayproxy/fetcher/data_fetcher_test.go
  internal/mesh/internal/controllers/register.go
  internal/mesh/internal/types/decoded.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-docs, pr/no-backport

#20127 fix: stop re-clicking dc dropdown in dc-switch test
  ui/packages/consul-ui/tests/acceptance/dc/nspaces/manage.feature
  ui/packages/consul-ui/tests/acceptance/dc/services/dc-switch.feature
Labels: theme/ui, pr/no-changelog, pr/no-backport

#19788 Add Link resource type and controller skeleton
  agent/config/builder.go
  agent/config/builder_test.go
  agent/consul/options.go
  agent/consul/server.go
  agent/consul/testdata/v2-resource-dependencies.md
  agent/consul/type_registry.go
  internal/hcp/exports.go
  internal/hcp/internal/controllers/link/controller.go
  internal/hcp/internal/controllers/link/controller_test.go
  internal/hcp/internal/controllers/link/status.go
  internal/hcp/internal/controllers/register.go
  internal/hcp/internal/types/link.go
  internal/hcp/internal/types/link_test.go
  internal/hcp/internal/types/types.go
  proto-public/pbhcp/v2/link.pb.binary.go
  proto-public/pbhcp/v2/link.pb.go
  proto-public/pbhcp/v2/link.proto
  proto-public/pbhcp/v2/link_deepcopy.gen.go
  proto-public/pbhcp/v2/link_json.gen.go
  proto-public/pbhcp/v2/resources.rtypes.go
Labels: pr/no-changelog, pr/no-backport

#20113 Update gateway.mdx
  website/content/docs/connect/gateways/api-gateway/configuration/gateway.mdx
Labels: type/docs, pr/no-changelog, backport/1.16, backport/1.17

#20130 Fix broken tests.
  agent/config_endpoint_test.go
  agent/consul/intention_endpoint_test.go
  agent/consul/leader_test.go
Labels: pr/no-changelog, backport/1.15, backport/1.16, backport/1.17

#20129 Backport of Update gateway.mdx into release/1.17.x
  website/content/docs/connect/gateways/api-gateway/configuration/gateway.mdx
Labels: type/docs

#20134 Fix broken tests.
  agent/consul/intention_endpoint_test.go
  agent/consul/leader_test.go
Labels: pr/no-changelog, pr/no-backport

#20135 Update gateway.mdx (#20113) - backport 1.16.x
  website/content/docs/api-gateway/configuration/gateway.mdx
Labels: type/docs, pr/no-backport

#20126 [NET-7106] Add kubebuilder validation annotations to ExportedServicesConsumer proto
  proto-public/pbmulticluster/v2beta1/exported_services_consumer.pb.go
  proto-public/pbmulticluster/v2beta1/exported_services_consumer.proto
Labels: pr/no-changelog, pr/no-backport

#20112 [NET-6593] agent: check for minimum RSA key size
  .changelog/20112.txt
  agent/auto-config/auto_encrypt_test.go
  agent/auto-config/tls.go
  agent/connect/generate.go
Labels: theme/connect, backport/1.15, backport/1.16, backport/1.17

#20141 Backport of [NET-6593] agent: check for minimum RSA key size into release/1.16.x
  .changelog/20112.txt
  agent/auto-config/auto_encrypt_test.go
  agent/auto-config/tls.go
  agent/connect/generate.go
Labels: theme/connect

#20046 NET-6813: adding resolver default subset test in agentless upgrade test
  test-integ/topoutil/asserter.go
  test-integ/upgrade/l7_traffic_management/common.go
  test-integ/upgrade/l7_traffic_management/resolver_test.go
  test/integration/consul-container/libs/assert/envoy.go
  test/integration/consul-container/test/upgrade/l7_traffic_management/resolver_default_subset_test.go
Labels: pr/no-changelog, pr/no-backport, consul-india

#20143 license: MPL'ify proto-public
  proto-public/.copywrite.hcl
  proto-public/pbauth/v2beta1/computed_traffic_permissions.pb.go
  proto-public/pbauth/v2beta1/computed_traffic_permissions.proto
  proto-public/pbauth/v2beta1/traffic_permissions.pb.go
  proto-public/pbauth/v2beta1/traffic_permissions.proto
  proto-public/pbauth/v2beta1/traffic_permissions_addon.go
  proto-public/pbauth/v2beta1/workload_identity.pb.go
  proto-public/pbauth/v2beta1/workload_identity.proto
  proto-public/pbcatalog/v2beta1/service_addon.go
  proto-public/pbcatalog/v2beta1/service_addon_test.go
  proto-public/pbcatalog/v2beta1/service_endpoints_addon.go
  proto-public/pbcatalog/v2beta1/service_endpoints_addon_test.go
  proto-public/pbcatalog/v2beta1/workload_addon.go
  proto-public/pbcatalog/v2beta1/workload_addon_test.go
  proto-public/pbhcp/v2/link.pb.go
  proto-public/pbhcp/v2/link.proto
  proto-public/pbmesh/v2beta1/pbproxystate/protocol_test.go
  proto-public/pbmesh/v2beta1/pbproxystate/traffic_permissions.pb.go
  proto-public/pbmesh/v2beta1/pbproxystate/traffic_permissions.proto
  proto-public/pbmesh/v2beta1/proxy_configuration_addon.go
  proto-public/pbmesh/v2beta1/proxy_configuration_addon_test.go
  proto-public/pbmesh/v2beta1/xroute_addons.go
  proto-public/pbmesh/v2beta1/xroute_addons_test.go
  proto-public/pbmulticluster/v2beta1/computed_exported_services.pb.go
  proto-public/pbmulticluster/v2beta1/computed_exported_services.proto
  proto-public/pbmulticluster/v2beta1/exported_services.pb.go
  proto-public/pbmulticluster/v2beta1/exported_services.proto
  proto-public/pbmulticluster/v2beta1/exported_services_consumer.pb.go
  proto-public/pbmulticluster/v2beta1/exported_services_consumer.proto
  proto-public/pbmulticluster/v2beta1/namespace_exported_services.pb.go
  proto-public/pbmulticluster/v2beta1/namespace_exported_services.proto
  proto-public/pbmulticluster/v2beta1/partition_exported_services.pb.go
  proto-public/pbmulticluster/v2beta1/partition_exported_services.proto
  proto-public/pbmulticluster/v2beta1/sameness_group.pb.go
  proto-public/pbmulticluster/v2beta1/sameness_group.proto
  proto-public/pbtenancy/v2beta1/namespace.pb.go
  proto-public/pbtenancy/v2beta1/namespace.proto
  proto-public/pbtenancy/v2beta1/partition.pb.go
  proto-public/pbtenancy/v2beta1/partition.proto
Labels: pr/no-changelog, backport/1.15, backport/1.16, backport/1.17

#20147 Fix broken link
  website/content/docs/k8s/connect/index.mdx
Labels: type/docs, pr/no-changelog, backport/1.12, backport/1.13, backport/1.14, backport/1.15, backport/1.16, backport/1.17

#20148 license: MPL'ify proto-public (manual backport for 1.17.x)
  proto-public/.copywrite.hcl
  proto-public/pbauth/v2beta1/computed_traffic_permissions.pb.go
  proto-public/pbauth/v2beta1/computed_traffic_permissions.proto
  proto-public/pbauth/v2beta1/traffic_permissions.pb.go
  proto-public/pbauth/v2beta1/traffic_permissions.proto
  proto-public/pbauth/v2beta1/traffic_permissions_addon.go
  proto-public/pbauth/v2beta1/workload_identity.pb.go
  proto-public/pbauth/v2beta1/workload_identity.proto
  proto-public/pbcatalog/v2beta1/service_addon.go
  proto-public/pbcatalog/v2beta1/service_addon_test.go
  proto-public/pbcatalog/v2beta1/service_endpoints_addon.go
  proto-public/pbcatalog/v2beta1/service_endpoints_addon_test.go
  proto-public/pbcatalog/v2beta1/workload_addon.go
  proto-public/pbcatalog/v2beta1/workload_addon_test.go
  proto-public/pbmesh/v2beta1/pbproxystate/protocol_test.go
  proto-public/pbmesh/v2beta1/pbproxystate/traffic_permissions.pb.go
  proto-public/pbmesh/v2beta1/pbproxystate/traffic_permissions.proto
  proto-public/pbmesh/v2beta1/proxy_configuration_addon.go
  proto-public/pbmesh/v2beta1/proxy_configuration_addon_test.go
  proto-public/pbmesh/v2beta1/xroute_addons.go
  proto-public/pbmesh/v2beta1/xroute_addons_test.go
  proto-public/pbtenancy/v1alpha1/namespace.pb.go
  proto-public/pbtenancy/v1alpha1/namespace.proto
Labels: pr/no-backport

#20156 license: MPL'ify proto-public (manual backport for 1.16.x)
  proto-public/.copywrite.hcl
  troubleshoot/ports/hostport.go
  troubleshoot/ports/troubleshoot_ports.go
  troubleshoot/ports/troubleshoot_ports_test.go
  troubleshoot/ports/troubleshoot_protocol.go
  troubleshoot/ports/troubleshoot_tcp.go
Labels: pr/no-backport

#20155 Backport of Fix broken link into release/1.17.x
  website/content/docs/k8s/connect/index.mdx
Labels: type/docs

#20154 Backport of Fix broken link into release/1.16.x
  website/content/docs/k8s/connect/index.mdx
Labels: type/docs

#20139 remove the skipping of slow tests in go-tests-ce and go-test-enterprise
  .github/workflows/go-tests.yml
  agent/consul/operator_backend_test.go
  lib/testhelpers/testhelpers.go
Labels: type/ci, theme/contributing, theme/internals, pr/no-changelog, backport/1.15, backport/1.16, backport/1.17

#20167 Sort peer list in expander
  internal/multicluster/internal/controllers/exportedservices/expander/expander_ce/expander.go
Labels: pr/no-changelog, pr/no-backport, consul-india

#20171 NET-7189 Add Protocol to MeshGatewayListeners
  proto-public/pbmesh/v2beta1/mesh_gateway.pb.go
  proto-public/pbmesh/v2beta1/mesh_gateway.proto
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#20160 Backport of ci: Single source of truth for Go version in CI and Dockerfile into release/1.17.x
  .github/workflows/build-artifacts.yml
  .github/workflows/build-distros.yml
  .github/workflows/build.yml
  .github/workflows/go-tests.yml
  .github/workflows/nightly-test-integrations-1.15.x.yml
  .github/workflows/nightly-test-integrations-1.16.x.yml
  .github/workflows/nightly-test-integrations.yml
  .github/workflows/reusable-check-go-mod.yml
  .github/workflows/reusable-dev-build-windows.yml
  .github/workflows/reusable-dev-build.yml
  .github/workflows/reusable-get-go-version.yml
  .github/workflows/reusable-lint.yml
  .github/workflows/reusable-unit-split.yml
  .github/workflows/reusable-unit.yml
  .github/workflows/security-scan.yml
  .github/workflows/test-integrations-windows.yml
  .github/workflows/test-integrations.yml
  .go-version
  Makefile
  build-support/docker/Build-Go.dockerfile
Labels: type/ci, theme/contributing, pr/no-backport

#20161 Backport of ci: Single source of truth for Go version in CI and Dockerfile into release/1.16.x
  .github/workflows/build-artifacts.yml
  .github/workflows/build-distros.yml
  .github/workflows/build.yml
  .github/workflows/go-tests.yml
  .github/workflows/nightly-test-integrations.yml
  .github/workflows/reusable-check-go-mod.yml
  .github/workflows/reusable-dev-build.yml
  .github/workflows/reusable-get-go-version.yml
  .github/workflows/reusable-lint.yml
  .github/workflows/reusable-unit-split.yml
  .github/workflows/reusable-unit.yml
  .github/workflows/security-scan.yml
  .github/workflows/test-integrations.yml
  .go-version
  GNUmakefile
  build-support/docker/Build-Go.dockerfile
Labels: type/ci, theme/contributing, pr/no-backport

#20162 Backport of ci: Single source of truth for Go version in CI and Dockerfile into release/1.15.x
  .github/workflows/build-artifacts.yml
  .github/workflows/build-distros.yml
  .github/workflows/build.yml
  .github/workflows/go-tests.yml
  .github/workflows/nightly-test-integrations.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/reusable-check-go-mod.yml
  .github/workflows/reusable-dev-build.yml
  .github/workflows/reusable-get-go-version.yml
  .github/workflows/reusable-lint.yml
  .github/workflows/reusable-unit-split.yml
  .github/workflows/reusable-unit.yml
  .github/workflows/security-scan.yml
  .github/workflows/test-integrations.yml
  .go-version
  GNUmakefile
  build-support/docker/Build-Go.dockerfile
Labels: pr/no-backport

#20173 chore: improve CI backports by backporting new workflows (1.17)
  .github/workflows/nightly-test-integ-peering_commontopo.yml
  .github/workflows/nightly-test-integrations-1.17.x.yml
Labels: type/ci, theme/contributing, pr/no-changelog, backport/1.15, backport/1.16

#20174 chore: improve CI backports by backporting new workflows (1.16)
  .github/workflows/nightly-test-integrations-1.15.x.yml
  .github/workflows/nightly-test-integrations-1.16.x.yml
  .github/workflows/reusable-dev-build-windows.yml
  .github/workflows/test-integrations-windows.yml
Labels: type/ci, theme/contributing, pr/no-changelog, backport/1.15

#20062 [NET-4968] Upgrade Go to 1.21
  .changelog/20062.txt
  .github/workflows/go-tests.yml
  .github/workflows/reusable-get-go-version.yml
  .github/workflows/reusable-lint.yml
  .go-version
  .golangci.yml
  Makefile
  api/api_test.go
  internal/mesh/internal/controllers/sidecarproxy/builder/local_app.go
Labels: backport/1.15, backport/1.16, backport/1.17

#20175 compliance: license checker to enforce MPL pre-EOY 2023 no longer necessary
  .github/scripts/license_checker.sh
  .github/workflows/license-checker.yml
Labels: type/ci, theme/contributing, pr/no-changelog, backport/1.15, backport/1.16, backport/1.17

#20185 Backport of compliance: license checker to enforce MPL pre-EOY 2023 no longer necessary into release/1.17.x
  .github/scripts/license_checker.sh
  .github/workflows/license-checker.yml
Labels: type/ci, theme/contributing

#20187 integ test: import missing changes from ent
  test-integ/topoutil/asserter.go
  test/integration/consul-container/libs/assert/envoy.go
Labels: pr/no-changelog, pr/no-backport

#20199 always run agent tests alone on their own runner
  .github/scripts/set_test_package_matrix.sh
Labels: theme/contributing, pr/no-changelog, pr/no-backport

#20200 agent: remove data race in agent config
  agent/agent.go
  agent/agent_endpoint.go
Labels: pr/no-changelog, pr/no-metrics-test, backport/1.15, backport/1.16, backport/1.17

#20194 v1 dns - add doc strings for functions and update function names to be consistent and more descriptive.
  agent/dns.go
Labels: pr/no-changelog, pr/no-backport

#20186 upgrade test (LTS): utility functions to support ent users
  test-integ/go.mod
  test-integ/topoutil/asserter.go
  test-integ/topoutil/http_consul.go
  test-integ/upgrade/l7_traffic_management/common.go
  testing/deployer/sprawl/sprawl.go
  testing/deployer/topology/topology.go
Labels: pr/no-changelog, pr/no-backport

#20192 docs: fix partition target in samenessgroups
  website/content/docs/k8s/connect/cluster-peering/usage/create-sameness-groups.mdx
Labels: type/docs, pr/no-changelog, pr/no-metrics-test, backport/1.16, backport/1.17

#20212 Various race condition and test fixes.
  agent/acl_endpoint_test.go
  agent/grpc-external/services/peerstream/stream_test.go
  agent/grpc-external/services/peerstream/testing.go
  agent/metrics_test.go
  agent/rpc/peering/service.go
  agent/rpc/peering/service_test.go
  agent/testagent.go
Labels: pr/no-changelog, backport/1.15, backport/1.16, backport/1.17

#20086 add acl token
  command/resource/client/grpc-config.go
  command/resource/client/grpc-config_test.go
  command/resource/client/grpc-flags.go
  command/resource/client/grpc-flags_test.go
Labels: pr/no-changelog, pr/no-backport

#20169 NET-6862: adding disk-io and disk usage metrics to k8s grafana dashboard
  grafana/consul-k8s-control-plane-monitoring.json
Labels: pr/no-changelog, pr/no-metrics-test, pr/no-backport, consul-india

#20072 [CC-7042] Update and enable the HCP metrics sink in the HCP manager
  agent/consul/server.go
  agent/hcp/client/http_client.go
  agent/hcp/client/http_client_test.go
  agent/hcp/client/metrics_client.go
  agent/hcp/client/metrics_client_test.go
  agent/hcp/config/config.go
  agent/hcp/config/mock_CloudConfig.go
  agent/hcp/deps.go
  agent/hcp/manager.go
  agent/hcp/manager_test.go
  agent/hcp/telemetry_provider.go
  agent/hcp/telemetry_provider_test.go
Labels: pr/no-changelog, pr/no-backport

#20207 Backport of docs: fix partition target in samenessgroups into release/1.16.x
  website/content/docs/k8s/connect/cluster-peering/usage/create-sameness-groups.mdx
Labels: type/docs

#20208 Backport of docs: fix partition target in samenessgroups into release/1.17.x
  website/content/docs/k8s/connect/cluster-peering/usage/create-sameness-groups.mdx
Labels: type/docs

#20218 Backport of chore: improve CI backports by backporting new workflows into release/1.15.x
  .github/workflows/nightly-test-integ-peering_commontopo.yml
  .github/workflows/nightly-test-integrations-1.15.x.yml
  .github/workflows/nightly-test-integrations-1.16.x.yml
  .github/workflows/nightly-test-integrations-1.17.x.yml
  .github/workflows/reusable-dev-build-windows.yml
  .github/workflows/test-integrations-windows.yml
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#20217 Backport of chore: improve CI backports by backporting new workflows into release/1.16.x
  .github/workflows/nightly-test-integ-peering_commontopo.yml
  .github/workflows/nightly-test-integrations-1.17.x.yml
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#20219 ci: Use Consul Go version for Vault int tests
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing, pr/no-changelog, backport/1.15, backport/1.16, backport/1.17

#20213 Add docs for k8s liveness / startup probes.
  website/content/docs/k8s/annotations-and-labels.mdx
  website/content/docs/k8s/helm.mdx
Labels: type/docs, pr/no-changelog, backport/1.15, backport/1.16, backport/1.17

#20226 Backport of Add docs for k8s liveness / startup probes. into release/1.16.x
  website/content/docs/k8s/annotations-and-labels.mdx
  website/content/docs/k8s/helm.mdx
Labels: type/docs

#20227 Backport of Add docs for k8s liveness / startup probes. into release/1.17.x
  website/content/docs/k8s/annotations-and-labels.mdx
  website/content/docs/k8s/helm.mdx
Labels: type/docs

#20159 NET-7178: add workload selector to MeshGateway protobuf definition
  proto-public/pbmesh/v2beta1/mesh_gateway.pb.go
  proto-public/pbmesh/v2beta1/mesh_gateway.proto
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#20224 feat(v2dns): addr. query support
  agent/discovery/discovery.go
  agent/dns.go
  agent/dns/router.go
  agent/dns/router_test.go
  agent/dns_node_lookup_test.go
  agent/dns_service_lookup_test.go
  agent/dns_test.go
Labels: pr/no-changelog, pr/no-backport

#20223 Backport of ci: Use Consul Go version for Vault int tests into release/1.17.x
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing

#20222 Backport of ci: Use Consul Go version for Vault int tests into release/1.16.x
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing

#20221 Backport of ci: Use Consul Go version for Vault int tests into release/1.15.x
  .github/workflows/test-integrations.yml
Labels: type/ci, theme/contributing

#20232 Add additional rules to iptables SDK
  sdk/iptables/iptables.go
  sdk/iptables/iptables_test.go
Labels: pr/no-changelog, pr/no-backport, consul-india

#20172 Remove unnecessary fetching of gateway
  internal/mesh/internal/controllers/gatewayproxy/controller.go
Labels: pr/no-changelog, pr/no-backport

#20245 DNS v2 - add virtual ip questions
  agent/agent.go
  agent/discovery/discovery.go
  agent/discovery/mock_CatalogDataFetcher.go
  agent/discovery/query_fetcher_v1.go
  agent/discovery/query_fetcher_v1_ce_test.go
  agent/discovery/query_fetcher_v1_test.go
  agent/discovery/query_fetcher_v2.go
  agent/dns/query_locality.go
  agent/dns/query_locality_ce.go
  agent/dns/query_locality_ce_test.go
  agent/dns/query_locality_test.go
  agent/dns/router.go
  agent/dns/router_query.go
  agent/dns/router_query_ce_test.go
  agent/dns/router_query_test.go
  agent/dns/router_test.go
  agent/dns/server.go
  agent/dns_ce.go
  agent/dns_ce_test.go
  agent/dns_test.go
Labels: pr/no-changelog, pr/no-backport

#20246 feat(v2dns): move DNSPolicy to workload/endpoints
  internal/catalog/internal/controllers/endpoints/controller.go
  internal/catalog/internal/controllers/endpoints/controller_test.go
  internal/catalog/internal/controllers/failover/controller_test.go
  internal/catalog/internal/controllers/nodehealth/controller_test.go
  internal/catalog/internal/types/dns_policy.go
  internal/catalog/internal/types/dns_policy_test.go
  internal/catalog/internal/types/service_endpoints.go
  internal/catalog/internal/types/service_endpoints_test.go
  internal/catalog/internal/types/types.go
  internal/catalog/internal/types/types_test.go
  internal/catalog/internal/types/validators.go
  internal/catalog/internal/types/validators_test.go
  internal/catalog/internal/types/workload.go
  internal/catalog/internal/types/workload_test.go
  proto-public/pbcatalog/v2beta1/dns.pb.binary.go
  proto-public/pbcatalog/v2beta1/dns.pb.go
  proto-public/pbcatalog/v2beta1/dns.proto
  proto-public/pbcatalog/v2beta1/dns_deepcopy.gen.go
  proto-public/pbcatalog/v2beta1/dns_json.gen.go
  proto-public/pbcatalog/v2beta1/resources.rtypes.go
  proto-public/pbcatalog/v2beta1/service_endpoints.pb.go
  proto-public/pbcatalog/v2beta1/service_endpoints.proto
  proto-public/pbcatalog/v2beta1/workload.pb.binary.go
  proto-public/pbcatalog/v2beta1/workload.pb.go
  proto-public/pbcatalog/v2beta1/workload.proto
  proto-public/pbcatalog/v2beta1/workload_deepcopy.gen.go
  proto-public/pbcatalog/v2beta1/workload_json.gen.go
Labels: pr/no-changelog, pr/no-backport

#20253 [NET6429] Add listeners for mesh-gateway v2
  internal/mesh/internal/controllers/gatewayproxy/builder/builder.go
  internal/mesh/internal/controllers/gatewayproxy/builder/builder_test.go
  internal/mesh/internal/controllers/gatewayproxy/controller.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-docs, pr/no-backport

#20239 Docs/consul ia experiment access adam
  website/content/docs/access/api-gateway/define-route/k8s-reroute-traffic.mdx
  website/content/docs/access/api-gateway/define-route/k8s-route-peered.mdx
  website/content/docs/access/api-gateway/define-route/k8s.mdx
  website/content/docs/access/api-gateway/define-route/peer.mdx
  website/content/docs/access/api-gateway/define-route/reroute.mdx
  website/content/docs/access/api-gateway/define-route/vm.mdx
  website/content/docs/access/api-gateway/deploy-listener/k8s.mdx
  website/content/docs/access/api-gateway/deploy-listener/vm.mdx
  website/content/docs/access/api-gateway/index.mdx
  website/content/docs/access/api-gateway/install.mdx
  website/content/docs/access/api-gateway/k8s-install.mdx
  website/content/docs/access/api-gateway/k8s-tech-specs.mdx
  website/content/docs/access/api-gateway/k8s-upgrade.mdx
  website/content/docs/access/api-gateway/secure-traffic/encrypt.mdx
  website/content/docs/access/api-gateway/secure-traffic/jwt-k8s.mdx
  website/content/docs/access/api-gateway/secure-traffic/jwt-vm.mdx
  website/content/docs/access/api-gateway/secure-traffic/k8s-jwt.mdx
  website/content/docs/access/api-gateway/secure-traffic/vm-jwt.mdx
  website/content/docs/access/api-gateway/secure-traffic/vm.mdx
  website/content/docs/access/api-gateway/tech-specs.mdx
  website/content/docs/access/ingress-gateway/create-k8s.mdx
  website/content/docs/access/ingress-gateway/create-vm.mdx
  website/content/docs/access/ingress-gateway/create.mdx
  website/content/docs/access/ingress-gateway/tls-external-service.mdx
  website/content/docs/common-error-messages/api-gateway.mdx
  website/content/docs/reference/k8s/api-gateway/index.mdx
  website/content/docs/reference/k8s/helm.mdx
  website/content/docs/upgrade/api-gateway.mdx
  website/data/docs-nav-data.json
  website/redirects.js
Labels: type/docs, pr/no-changelog, pr/no-metrics-test, pr/no-backport

#20255 update version
  api/go.mod
  api/go.sum
  envoyextensions/go.mod
  envoyextensions/go.sum
  go.mod
  test-integ/go.mod
  test/integration/consul-container/go.mod
  testing/deployer/go.mod
  troubleshoot/go.mod
  troubleshoot/go.sum
  version/VERSION
Labels: pr/no-changelog, pr/no-backport

#20254 Update version
  CHANGELOG.md
  version/VERSION
Labels: pr/no-changelog, pr/no-backport

#20256 update version
  CHANGELOG.md
  version/VERSION
Labels: pr/no-changelog, pr/no-backport

#20240 Update workload health controller to use the controller cache
  internal/catalog/catalogtest/test_integration_v2beta1.go
  internal/catalog/exports.go
  internal/catalog/internal/controllers/endpoints/controller.go
  internal/catalog/internal/controllers/endpoints/controller_test.go
  internal/catalog/internal/controllers/register.go
  internal/catalog/internal/controllers/workloadhealth/controller.go
  internal/catalog/internal/controllers/workloadhealth/controller_test.go
  internal/catalog/internal/controllers/workloadhealth/status.go
  internal/catalog/internal/mappers/nodemapper/node_mapper.go
  internal/catalog/internal/mappers/nodemapper/node_mapper_test.go
  internal/controller/testing.go
Labels: pr/no-changelog, pr/no-backport

#20261 NET-3860 - [Supportability] consul troubleshoot CLI for verifying por…
  .changelog/18329.txt
  command/registry.go
  command/troubleshoot/ports/troubleshoot_ports.go
  troubleshoot/go.mod
  troubleshoot/go.sum
  troubleshoot/ports/hostport.go
  troubleshoot/ports/troubleshoot_ports.go
  troubleshoot/ports/troubleshoot_ports_test.go
  troubleshoot/ports/troubleshoot_protocol.go
  troubleshoot/ports/troubleshoot_tcp.go
  website/content/commands/troubleshoot/index.mdx
  website/content/commands/troubleshoot/ports.mdx
  website/data/commands-nav-data.json
Labels: type/docs, theme/cli, pr/no-changelog, pr/no-backport

#20258 upgrade test: call validation func during upgrade
  test-integ/upgrade/basic/upgrade_basic_test.go
  test-integ/upgrade/l7_traffic_management/resolver_test.go
  testing/deployer/sprawl/sprawl.go
Labels: pr/no-changelog, pr/no-backport

#20168 Fix to not create a watch to `Internal.ServiceDump` when mesh gateway is not used
  .changelog/20168.txt
  agent/consul/internal_endpoint.go
  agent/consul/internal_endpoint_test.go
  agent/proxycfg/mesh_gateway.go
  agent/proxycfg/state.go
  agent/proxycfg/state_test.go
  agent/proxycfg/upstreams.go
  agent/structs/structs.go
Labels: backport/1.15, backport/1.16, backport/1.17

#20263 docs: update k8s upgrade instructions
  website/content/docs/k8s/upgrade/index.mdx
Labels: type/docs, pr/no-changelog, pr/no-backport

#20249 feat(v2dns): recursor support
  agent/dns/mock_dnsRecursor.go
  agent/dns/recursor.go
  agent/dns/recursor_test.go
  agent/dns/router.go
  agent/dns/router_query.go
  agent/dns/router_test.go
  agent/dns_service_lookup_test.go
  agent/dns_test.go
  internal/dnsutil/dns_test.go
Labels: pr/no-changelog, pr/no-backport

#20262 [NET-6431] Remove explicit endpoints function from PST builder
  internal/mesh/internal/controllers/gatewayproxy/builder/builder.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#20264 security: disable Vault secret scans due to false positives
  .release/security-scan.hcl
Labels: pr/no-changelog, backport/1.15, backport/1.16, backport/1.17

#20244 Failover policy cache
  agent/consul/server.go
  internal/catalog/catalogtest/run_test.go
  internal/catalog/exports.go
  internal/catalog/internal/controllers/failover/controller.go
  internal/catalog/internal/controllers/failover/controller_test.go
  internal/catalog/internal/controllers/failover/status.go
  internal/catalog/internal/controllers/register.go
  internal/catalog/internal/mappers/failovermapper/failover_mapper.go
  internal/catalog/internal/mappers/failovermapper/failover_mapper_test.go
  internal/mesh/internal/controllers/routes/controller.go
  internal/mesh/internal/controllers/routes/controller_test.go
  internal/mesh/internal/controllers/routes/loader/loader.go
  internal/mesh/internal/controllers/routes/loader/loader_test.go
  internal/mesh/internal/controllers/routes/xroutemapper/.mockery.yaml
  internal/mesh/internal/controllers/routes/xroutemapper/xroutemapper.go
  internal/mesh/internal/controllers/routes/xroutemapper/xroutemapper_test.go
  internal/mesh/internal/controllers/routes/xroutemapper/xroutemappermock/mock_ResolveFailoverServiceDestinations.go
Labels: pr/no-changelog, pr/no-backport

#20158 Sync cluster attributes from GNM to Link resource
  agent/hcp/client/client.go
  agent/hcp/client/client_test.go
  agent/hcp/client/mock_Client.go
  go.mod
  go.sum
  internal/hcp/internal/controllers/link/controller.go
  internal/hcp/internal/controllers/link/controller_test.go
  internal/hcp/internal/controllers/link/status.go
  internal/hcp/internal/controllers/register.go
  proto-public/pbhcp/v2/link.pb.go
  proto-public/pbhcp/v2/link.proto
  test-integ/go.mod
  test-integ/go.sum
  test/integration/consul-container/go.mod
  test/integration/consul-container/go.sum
Labels: pr/dependencies, pr/no-changelog, pr/no-backport

#20278 Deflake the catalog v2beta1 integration tests
  internal/catalog/catalogtest/test_integration_v2beta1.go
Labels: pr/no-changelog, pr/no-backport, backport/1.17

#20281 [NET-7339] security: update gopkg.in/yaml
  .changelog/20281.txt
  api/go.mod
  api/go.sum
  internal/tools/proto-gen-rpc-glue/go.mod
  internal/tools/proto-gen-rpc-glue/go.sum
  proto-public/go.mod
  proto-public/go.sum
  sdk/go.mod
  sdk/go.sum
Labels: theme/api, pr/no-backport

#20248 Migrate the node health controller to use the cache
  internal/catalog/internal/controllers/nodehealth/controller.go
  internal/catalog/internal/controllers/nodehealth/controller_test.go
Labels: pr/no-changelog, pr/no-backport

#20138 [CC-7031] Add initialization support to resource controllers
  agent/config/builder.go
  agent/consul/server.go
  agent/hcp/config/config.go
  agent/hcp/deps.go
  docs/v2-architecture/controller-architecture/controllers.md
  docs/v2-architecture/controller-architecture/guide.md
  internal/controller/controller.go
  internal/controller/controller_test.go
  internal/controller/runner.go
  internal/hcp/internal/controllers/link/controller.go
  internal/hcp/internal/controllers/link/controller_test.go
  internal/hcp/internal/controllers/register.go
  internal/hcp/internal/types/link.go
Labels: theme/config, pr/no-changelog, pr/no-backport

#20288 Backport/troubleshoot ports
  .changelog/18329.txt
  CHANGELOG.md
  command/registry.go
  command/troubleshoot/ports/troubleshoot_ports.go
  go.mod
  test-integ/go.mod
  test/integration/consul-container/go.mod
  troubleshoot/go.mod
  troubleshoot/go.sum
  troubleshoot/ports/hostport.go
  troubleshoot/ports/troubleshoot_ports.go
  troubleshoot/ports/troubleshoot_ports_test.go
  troubleshoot/ports/troubleshoot_protocol.go
  troubleshoot/ports/troubleshoot_tcp.go
  website/content/commands/troubleshoot/index.mdx
  website/content/commands/troubleshoot/ports.mdx
  website/data/commands-nav-data.json
Labels: type/docs, theme/cli, pr/dependencies, pr/no-changelog, pr/no-backport

#20291 Backport of security: disable Vault secret scans due to false positives into release/1.15.9
  .release/security-scan.hcl
Labels: pr/no-changelog, pr/no-backport

#19830 Create HCP management token in HCP manager
  agent/consul/leader.go
  agent/consul/server.go
  agent/hcp/manager.go
  agent/hcp/manager_test.go
Labels: pr/no-changelog, pr/no-backport

#20280 Backport of Deflake the catalog v2beta1 integration tests into release/1.17.x
  internal/catalog/catalogtest/test_integration_v2beta1.go
Labels: pr/no-changelog, pr/no-backport

#20299 v2: prevent use of the v2 experiments in secondary datacenters for now
  .changelog/20299.txt
  agent/config/builder.go
  agent/config/builder_test.go
  agent/consul/server.go
Labels: theme/config, pr/no-metrics-test, pr/no-backport

#20298 Add a separate test for initializer retries
  internal/controller/controller_test.go
Labels: pr/no-changelog, pr/no-backport

#20292 resource: retry non-CAS deletes automatically
  agent/grpc-external/services/resource/delete.go
  agent/grpc-external/services/resource/delete_test.go
  agent/grpc-external/services/resource/server.go
  agent/grpc-external/services/resource/server_test.go
  agent/grpc-external/services/resource/write.go
  agent/grpc-external/services/resource/write_status_test.go
  agent/grpc-external/services/resource/write_test.go
Labels: pr/no-changelog, pr/no-backport

#20220 Unconditionally add Access-Control-Expose-Headers HTTP header
  .changelog/20220.txt
  agent/hcp/bootstrap/bootstrap.go
  agent/hcp/bootstrap/bootstrap_test.go
  command/agent/agent.go
Labels: theme/cli, pr/no-backport

#19647 Case sensitive route match
  .changelog/19647.txt
  agent/structs/config_entry_discoverychain.go
  agent/structs/config_entry_discoverychain_test.go
  agent/structs/config_entry_test.go
  agent/xds/routes.go
  api/config_entry_discoverychain.go
  api/config_entry_discoverychain_test.go
  test/integration/connect/envoy/case-cfg-router-features/setup.sh
  test/integration/connect/envoy/case-cfg-router-features/verify.bats
  website/content/docs/connect/config-entries/service-router.mdx
Labels: type/docs, theme/api, theme/envoy/xds, backport/1.17

#20297 Stage 1.15.9
  version/VERSION
Labels: pr/no-changelog, pr/no-docs, pr/no-backport

#20295 Update troubleshoot module in main go.mod for new version
  go.mod
Labels: pr/dependencies, pr/no-changelog, pr/no-docs, pr/no-backport

#20270 Use null route cluster for default router when no matches on v2 mesh gateway
  internal/mesh/internal/controllers/gatewayproxy/builder/builder.go
  internal/mesh/internal/controllers/gatewayproxy/builder/builder_test.go
  internal/mesh/internal/controllers/gatewayproxy/controller.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#20293 upgrade test: run validation func at every node during upgrade
  test-integ/topoutil/asserter.go
  test-integ/upgrade/l7_traffic_management/common.go
  testing/deployer/sprawl/consul.go
Labels: pr/no-changelog, pr/no-backport

#20015 NET-5824 Exported services api
  .changelog/20015.txt
  agent/agent.go
  agent/config_endpoint.go
  agent/config_endpoint_test.go
  agent/consul/configentry_backend.go
  agent/consul/configentry_backend_ce.go
  agent/consul/configentry_backend_ce_test.go
  agent/consul/configentry_backend_test.go
  agent/consul/server_grpc.go
  agent/consul/state/config_entry_exported_services.go
  agent/consul/state/config_entry_exported_services_ce.go
  agent/consul/state/config_entry_exported_services_ce_test.go
  agent/grpc-external/services/configentry/server.go
  agent/grpc-external/services/configentry/server_ce_test.go
  agent/grpc-external/services/configentry/server_test.go
  agent/grpc-external/testutils/fsm.go
  agent/grpc-external/testutils/mock_server_transport_stream.go
  agent/grpc-external/utils.go
  agent/grpc-middleware/rate_limit_mappings.gen.go
  agent/http_register.go
  api/config_entry_exports.go
  api/exported_services.go
  internal/tools/protoc-gen-consul-rate-limit/main.go
  internal/tools/protoc-gen-consul-rate-limit/postprocess/main.go
  proto-public/annotations/ratelimit/ratelimit.pb.go
  proto-public/annotations/ratelimit/ratelimit.proto
  proto/private/pbconfigentry/config_entry.go
  proto/private/pbconfigentry/config_entry.pb.binary.go
  proto/private/pbconfigentry/config_entry.pb.go
  proto/private/pbconfigentry/config_entry.proto
  proto/private/pbconfigentry/config_entry_grpc.pb.go
Labels: consul-india, backport/1.17

#20315 Backport of NET-5824 Exported services api (#20015)
  .changelog/20015.txt
  agent/agent.go
  agent/config_endpoint.go
  agent/config_endpoint_test.go
  agent/consul/configentry_backend.go
  agent/consul/configentry_backend_ce.go
  agent/consul/configentry_backend_ce_test.go
  agent/consul/configentry_backend_test.go
  agent/consul/server.go
  agent/consul/state/config_entry_exported_services.go
  agent/consul/state/config_entry_exported_services_ce.go
  agent/consul/state/config_entry_exported_services_ce_test.go
  agent/grpc-external/services/configentry/server.go
  agent/grpc-external/services/configentry/server_ce_test.go
  agent/grpc-external/services/configentry/server_test.go
  agent/grpc-external/testutils/fsm.go
  agent/grpc-external/testutils/mock_server_transport_stream.go
  agent/grpc-external/utils.go
  agent/grpc-middleware/rate_limit_mappings.gen.go
  agent/http_register.go
  api/config_entry_exports.go
  api/exported_services.go
  internal/tools/protoc-gen-consul-rate-limit/main.go
  internal/tools/protoc-gen-consul-rate-limit/postprocess/main.go
  proto-public/annotations/ratelimit/ratelimit.pb.go
  proto-public/annotations/ratelimit/ratelimit.proto
  proto/private/pbconfigentry/config_entry.go
  proto/private/pbconfigentry/config_entry.pb.binary.go
  proto/private/pbconfigentry/config_entry.pb.go
  proto/private/pbconfigentry/config_entry.proto
  proto/private/pbconfigentry/config_entry_grpc.pb.go
Labels: theme/api, pr/no-backport

#20319 Update SCADA provider version
  go.mod
  go.sum
Labels: pr/dependencies, pr/no-changelog, pr/no-backport

#20275 💜 Cc 7187/purple banner for linking existing clusters
  .changelog/20275.txt
  ui/packages/consul-ui/app/components/hashicorp-consul/index.js
  ui/packages/consul-ui/app/components/link-to-hcp-banner/index.hbs
  ui/packages/consul-ui/app/components/link-to-hcp-banner/index.js
  ui/packages/consul-ui/app/services/env.js
  ui/packages/consul-ui/app/services/hcp-link-status.js
  ui/packages/consul-ui/app/styles/routes/dc/services/index.scss
  ui/packages/consul-ui/app/templates/dc/services/index.hbs
  ui/packages/consul-ui/tests/acceptance/link-to-hcp-banner-test.js
  ui/packages/consul-ui/tests/integration/components/link-to-hcp-banner-test.js
  ui/packages/consul-ui/translations/components/link-to-hcp-banner/en-us.yaml
Labels: theme/ui, pr/no-backport

#20317 docs: Update k8s/connect/create-sameness-groups
  website/content/docs/k8s/connect/cluster-peering/usage/create-sameness-groups.mdx
Labels: type/docs, pr/no-changelog, pr/no-metrics-test, backport/1.16, backport/1.17

#20318 Net 7074/decentralized exported services management
  agent/consul/server.go
  agent/consul/v2_config_entry_exports_shim.go
  internal/multicluster/exports.go
  internal/multicluster/internal/controllers/register.go
  internal/multicluster/internal/controllers/v1compat/controller.go
Labels: pr/no-changelog, pr/no-backport

#20276 Net 5092/internal l7 traffic permissions
  agent/xds/rbac_test.go
  agent/xds/response/response.go
  agent/xds/testdata/rbac/v2-default-allow--httpfilter.golden
  agent/xds/testdata/rbac/v2-default-deny--httpfilter.golden
  agent/xds/testdata/rbac/v2-ignore-empty-permissions--httpfilter.golden
  agent/xds/testdata/rbac/v2-kitchen-sink--httpfilter.golden
  agent/xdsv2/listener_resources.go
  agent/xdsv2/rbac_resources.go
  agent/xdsv2/testdata/listeners/source/multiple-workload-addresses-with-specific-ports.golden
  internal/auth/internal/types/errors.go
  internal/auth/internal/types/traffic_permissions.go
  internal/auth/internal/types/traffic_permissions_test.go
  internal/mesh/internal/controllers/sidecarproxy/builder/local_app.go
  internal/mesh/internal/controllers/sidecarproxy/builder/local_app_test.go
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/source/multiple-workload-addresses-with-specific-ports-default-bar.golden
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/source/multiple-workload-addresses-with-specific-ports-default-default.golden
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/source/multiple-workload-addresses-with-specific-ports-foo-bar.golden
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/source/multiple-workload-addresses-with-specific-ports-foo-default.golden
  internal/mesh/internal/controllers/sidecarproxy/builder/testdata/source/multiple-workload-addresses-with-specific-ports.golden
  internal/mesh/internal/controllers/xds/testdata/source/multiple-workload-addresses-with-specific-ports.golden
  proto-public/pbauth/v2beta1/traffic_permissions.pb.go
  proto-public/pbauth/v2beta1/traffic_permissions.proto
  proto-public/pbmesh/v2beta1/pbproxystate/traffic_permissions.pb.binary.go
  proto-public/pbmesh/v2beta1/pbproxystate/traffic_permissions.pb.go
  proto-public/pbmesh/v2beta1/pbproxystate/traffic_permissions.proto
  proto-public/pbmesh/v2beta1/pbproxystate/traffic_permissions_deepcopy.gen.go
  proto-public/pbmesh/v2beta1/pbproxystate/traffic_permissions_json.gen.go
Labels: theme/envoy/xds, pr/no-changelog, pr/no-backport

#20329 added computed failover controller
  agent/consul/testdata/v2-resource-dependencies.md
  internal/catalog/internal/controllers/failover/controller.go
  internal/catalog/internal/controllers/failover/controller_test.go
  internal/catalog/internal/controllers/failover/expander/expander_ce.go
  internal/catalog/internal/controllers/failover/expander/expander_ce/expander.go
  internal/catalog/internal/controllers/failover/expander/expander_ce/expander_test.go
  internal/catalog/internal/controllers/failover/expander/interface.go
  internal/catalog/internal/controllers/failover/helpers_ce.go
  internal/catalog/internal/controllers/failover/status.go
  internal/catalog/internal/controllers/register.go
  internal/catalog/internal/types/computed_failover_policy.go
  internal/catalog/internal/types/computed_failover_policy_test.go
  internal/catalog/internal/types/failover_policy.go
  internal/catalog/internal/types/failover_policy_test.go
  proto-public/pbcatalog/v2beta1/computed_failover_policy.pb.go
  proto-public/pbcatalog/v2beta1/computed_failover_policy.proto
Labels: pr/no-changelog, pr/no-backport, consul-india

#20306 [CC-7063] Fetch HCP agent bootstrap config in Link reconciler
  agent/consul/server.go
  agent/hcp/bootstrap/bootstrap.go
  agent/hcp/bootstrap/bootstrap_test.go
  agent/hcp/bootstrap/config-loader/loader.go
  agent/hcp/bootstrap/config-loader/loader_test.go
  agent/hcp/client/client.go
  agent/hcp/client/errors.go
  agent/hcp/deps.go
  agent/setup.go
  command/agent/agent.go
  internal/hcp/internal/controllers/link/controller.go
  internal/hcp/internal/controllers/link/controller_test.go
  internal/hcp/internal/controllers/link/status.go
  internal/hcp/internal/controllers/register.go
  internal/hcp/internal/types/link.go
  internal/hcp/internal/types/link_test.go
  internal/hcp/internal/types/testing.go
Labels: theme/cli, pr/no-changelog, pr/no-backport

#20326 Backport of docs: Update k8s/connect/create-sameness-groups into release/1.17.x
  website/content/docs/k8s/connect/cluster-peering/usage/create-sameness-groups.mdx
Labels: type/docs

#20250 NET-7153 Proto messages for API Gateway
  proto-public/pbmesh/v2beta1/api_gateway.pb.binary.go
  proto-public/pbmesh/v2beta1/api_gateway.pb.go
  proto-public/pbmesh/v2beta1/api_gateway.proto
  proto-public/pbmesh/v2beta1/api_gateway_deepcopy.gen.go
  proto-public/pbmesh/v2beta1/api_gateway_json.gen.go
  proto-public/pbmesh/v2beta1/resources.rtypes.go
Labels: pr/no-changelog, theme/api-gw, pr/no-backport

#20238 [NET-7265] Panic when passing an incorrect type to the data fetcher for gatewayproxy
  internal/mesh/internal/controllers/gatewayproxy/controller.go
  internal/mesh/internal/controllers/gatewayproxy/fetcher/data_fetcher.go
  internal/mesh/internal/controllers/gatewayproxy/fetcher/data_fetcher_test.go
  internal/mesh/internal/controllers/sidecarproxy/controller.go
  internal/mesh/internal/controllers/sidecarproxy/fetcher/data_fetcher.go
  internal/mesh/internal/controllers/sidecarproxy/fetcher/data_fetcher_test.go
Labels: theme/mesh-gw, pr/no-changelog, pr/no-backport

#20337 Add new changelog entries for 1.15.9, 1.16.5, 1.17.2
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-backport

#20340 Update version 1.15.10 dev
  CHANGELOG.md
  version/VERSION
Labels: pr/no-changelog, pr/no-backport

#20339 Update version 1.16.6 dev
  CHANGELOG.md
  version/VERSION
Labels: pr/no-changelog, pr/no-backport

#20338 Update version 1.17.3 dev
  CHANGELOG.md
  go.mod
  test-integ/go.mod
  test/integration/consul-container/go.mod
  troubleshoot/go.mod
  troubleshoot/go.sum
  version/VERSION
Labels: pr/no-changelog, pr/no-backport

#20313 move deny action to enterprise only for traffic permissions
  internal/auth/internal/controllers/trafficpermissions/controller_test.go
  internal/auth/internal/types/errors.go
  internal/auth/internal/types/traffic_permissions.go
  internal/auth/internal/types/traffic_permissions_ce_test.go
  internal/auth/internal/types/traffic_permissions_test.go
  internal/auth/internal/types/traffic_permissions_validator_ce.go
  test/integration/consul-container/test/trafficpermissions/tcp_test.go
Labels: pr/no-changelog, pr/no-backport

#20260 grpc CLI client list command
  command/registry.go
  command/resource/apply-grpc/apply.go
  command/resource/helper.go
  command/resource/list-grpc/list.go
  command/resource/list-grpc/list_test.go
  command/resource/resource-grpc.go
Labels: pr/no-changelog, pr/no-backport

#20320 feat(v2dns): add partial support for SOA records
  agent/discovery/discovery.go
  agent/dns/router.go
  agent/dns/router_test.go
  agent/dns_test.go
Labels: pr/no-changelog, pr/no-backport

#20328 added capability overview pages; fixed redirect issues
  website/content/docs/access/api-gateway/define-route/peer.mdx
  website/content/docs/access/api-gateway/index.mdx
  website/content/docs/access/index.mdx
  website/content/docs/access/ingress-gateway/index.mdx
  website/content/docs/access/k8s.mdx
  website/content/docs/access/vm.mdx
  website/content/docs/reference/k8s/api-gateway/index.mdx
  website/data/docs-nav-data.json
  website/redirects.js
Labels: type/docs, pr/no-changelog, pr/no-metrics-test, pr/no-backport

#20308 Add Link API docs
  .changelog/20308.txt
  website/content/api-docs/api-structure.mdx
  website/content/api-docs/hcp-link.mdx
  website/content/api-docs/index.mdx
  website/data/api-docs-nav-data.json
Labels: type/docs, pr/no-backport

#20321 Add finalizer to link resource
  internal/hcp/internal/controllers/link/controller.go
  internal/hcp/internal/controllers/link/controller_test.go
  internal/hcp/internal/controllers/link/finalizer.go
Labels: theme/cli, pr/no-changelog, pr/no-backport

#20311 resource: add MutateAndValidate endpoint
  agent/grpc-external/services/resource/mutate_and_validate.go
  agent/grpc-external/services/resource/mutate_and_validate_test.go
  agent/grpc-external/services/resource/testing/builder.go
  agent/grpc-external/services/resource/testing/testing_ce.go
  agent/grpc-external/services/resource/write.go
  agent/grpc-external/services/resource/write_mav_common_test.go
  agent/grpc-external/services/resource/write_test.go
  agent/grpc-middleware/rate_limit_mappings.gen.go
  grpcmocks/proto-public/pbresource/mock_ResourceServiceClient.go
  grpcmocks/proto-public/pbresource/mock_ResourceServiceServer.go
  proto-public/pbresource/resource.pb.binary.go
  proto-public/pbresource/resource.pb.go
  proto-public/pbresource/resource.proto
  proto-public/pbresource/resource_cloning_grpc.pb.go
  proto-public/pbresource/resource_deepcopy.gen.go
  proto-public/pbresource/resource_grpc.pb.go
  proto-public/pbresource/resource_json.gen.go
Labels: pr/no-changelog, pr/no-backport

#20336 docs: Fix example service registration for built-in proxy
  ui/packages/consul-ui/mock-api/v1/agent/services
  website/content/docs/connect/proxies/built-in.mdx
Labels: type/docs, theme/ui, pr/no-changelog, backport/1.15, backport/1.16, backport/1.17

#20352 Change logging of registered v2 resource endpoints to add /api prefix
  .changelog/20352.txt
  agent/http.go
  internal/resource/http/http.go
  internal/resource/http/http_test.go
Labels: backport/1.17

#20355 Change logging of registered v2 resource endpoints to add /api prefix
  .changelog/20352.txt
  agent/http.go
  internal/resource/http/http.go
  internal/resource/http/http_test.go
Labels: pr/no-backport

#20324 Net 7155- Consul API Gateway Controller Stub Work
  agent/consul/testdata/v2-resource-dependencies.md
  internal/mesh/internal/controllers/apigateways/controller.go
  internal/mesh/internal/controllers/register.go
Labels: pr/no-changelog, theme/api-gw, pr/no-backport

#20330 Cc 7145 hcp link status api
  ui/packages/consul-ui/app/components/link-to-hcp-banner/index.hbs
  ui/packages/consul-ui/app/components/link-to-hcp-banner/index.js
  ui/packages/consul-ui/app/services/hcp-link-status.js
  ui/packages/consul-ui/app/services/repository/hcp-link.js
  ui/packages/consul-ui/app/templates/application.hbs
  ui/packages/consul-ui/app/templates/dc/services/index.hbs
  ui/packages/consul-ui/mock-api/api/hcp/v2/link/global
  ui/packages/consul-ui/tests/integration/components/link-to-hcp-banner-test.js
Labels: theme/ui, pr/no-changelog, pr/no-backport

#20323 LTS - Add envoy support for 1.26, 1.27 and 1.28
  .changelog/20323.txt
  envoyextensions/xdscommon/envoy_versioning_test.go
  envoyextensions/xdscommon/proxysupport.go
  website/content/docs/connect/proxies/envoy.mdx
Labels: type/docs, pr/no-backport

#20304 Fix CICD docker image rate limits.
  test/integration/consul-container/libs/cluster/container.go
  testing/deployer/sprawl/internal/tfgen/gen.go
Labels: pr/no-changelog, backport/1.15, backport/1.16, backport/1.17

#20353 NET-5398: Update UI server to include if v2 is enabled
  .changelog/20353.txt
  agent/uiserver/ui_template_data.go
  agent/uiserver/uiserver_test.go
  ui/packages/consul-ui/app/utils/get-environment.js
  ui/packages/consul-ui/config/environment.js
  ui/packages/consul-ui/lib/startup/templates/body.html.js
  ui/packages/consul-ui/node-tests/config/environment.js
Labels: theme/ui, pr/no-backport

#20361 [NET-5075] Implement mesh gateway mode for explicit destinations
  internal/mesh/internal/controllers/sidecarproxy/controller.go
  internal/mesh/internal/controllers/sidecarproxy/fetcher/data_fetcher.go
  internal/mesh/internal/controllers/sidecarproxy/fetcher/data_fetcher_test.go
  internal/mesh/internal/types/proxy_configuration.go
  internal/mesh/internal/types/proxy_configuration_test.go
Labels: pr/no-changelog, pr/no-backport

#20368 GHA: Update broken-link-check.yml to check once a month
  .github/workflows/broken-link-check.yml
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#20344 Cc 7146/convert consul hcp to a simpler component for some upcoming changes
  ui/package.json
  ui/packages/consul-hcp/app/components/consul/hcp/home/index.hbs
  ui/packages/consul-hcp/app/components/consul/hcp/home/index.test.js
  ui/packages/consul-hcp/package.json
  ui/packages/consul-hcp/vendor/consul-hcp/routes.js
  ui/packages/consul-hcp/vendor/consul-hcp/services.js
  ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs
  ui/packages/consul-ui/app/components/hcp-nav-item/index.hbs
  ui/packages/consul-ui/app/components/hcp-nav-item/index.js
  ui/packages/consul-ui/ember-cli-build.js
  ui/packages/consul-ui/lib/startup/templates/body.html.js
  ui/packages/consul-ui/package.json
  ui/packages/consul-ui/tests/integration/components/consul/hcp/home-test.js
  ui/packages/consul-ui/tests/integration/components/hcp-nav-item-test.js
  ui/packages/consul-ui/tests/integration/components/link-to-hcp-banner-test.js
Labels: theme/ui, pr/no-changelog, backport/1.17

#20211 docs: Fix typos in docs
  website/content/docs/connect/config-entries/service-resolver.mdx
  website/content/docs/connect/manage-traffic/failover/sameness.mdx
Labels: type/docs, pr/no-changelog, pr/no-metrics-test, backport/1.17, type/docs-cherrypick

#20375 Backport of docs: Fix typos in docs into release/1.17.x
  website/content/docs/connect/config-entries/service-resolver.mdx
  website/content/docs/connect/manage-traffic/failover/sameness.mdx
Labels: type/docs, pr/no-changelog, pr/no-metrics-test

#20384 Increase number of supported envoy versions in failing CICD script
  .github/scripts/verify_envoy_version.sh
Labels: theme/contributing, pr/no-changelog, pr/no-backport
