Repository hashicorp/consul, pull requests merged in 2024-12, with the labels that each got.

#21988 Backport of docs: Adds initial sg documentation for the health API into release 1.20.x
  website/content/api-docs/health.mdx
Labels: type/docs, pr/no-changelog, pr/no-backport, type/docs-cherrypick

#22002 [Security] Bump envoy versions
  envoyextensions/xdscommon/ENVOY_VERSIONS
Labels: pr/no-changelog, backport/all

#22001 [Security] Bump crypto libraries
  .changelog/22001.txt
  .release/security-scan.hcl
  go.mod
  go.sum
  test-integ/go.mod
  test-integ/go.sum
  test/integration/consul-container/go.mod
  test/integration/consul-container/go.sum
Labels: pr/dependencies, pr/no-changelog, backport/all

#22009 Bump alpine image
  .release/security-scan.hcl
  Dockerfile
Labels: pr/no-changelog, backport/all

#22011 Update UBI Image
  .changelog/22011.txt
  Dockerfile
Labels: backport/all

#22015 Suppress redhat linux CVEs
  .changelog/22011.txt
  .release/security-scan.hcl
Labels: pr/no-changelog, backport/all

#22007 Backport of [Security] Bump crypto libraries into release/1.20.x
  .changelog/22001.txt
  .release/security-scan.hcl
  go.mod
  go.sum
  test-integ/go.mod
  test-integ/go.sum
  test/integration/consul-container/go.mod
  test/integration/consul-container/go.sum
Labels: pr/dependencies

#22020 chore: remove staff codeowners now that it requires mandatory review
  .github/CODEOWNERS
Labels: theme/contributing, pr/no-changelog, pr/no-metrics-test, backport/all

#22021 [Security] Bump net packages to resolve GO-2024-3333
  .changelog/22021.txt
  go.mod
  go.sum
  test-integ/go.mod
  test-integ/go.sum
  test/integration/consul-container/go.mod
  test/integration/consul-container/go.sum
Labels: pr/dependencies, backport/all

#22024 sec: bump envoy patch versions
  envoyextensions/xdscommon/ENVOY_VERSIONS
Labels: pr/no-changelog, backport/all

#22023 Backport of [Security] Bump net packages to resolve GO-2024-3333 into release/1.20.x
  .changelog/22021.txt
  go.mod
  go.sum
  test-integ/go.mod
  test-integ/go.sum
  test/integration/consul-container/go.mod
  test/integration/consul-container/go.sum
Labels: pr/dependencies

#22022 Backport of chore: remove staff codeowners now that it requires mandatory review into release/1.20.x
  .github/CODEOWNERS
Labels: theme/contributing

#21977 Backport of docs: fix broken link into release/1.20.x
  website/content/docs/dynamic-app-config/sessions/index.mdx
Labels: type/docs

#21965 Backport of Update API Group under backendRefs into release/1.20.x
  website/content/docs/connect/gateways/api-gateway/configuration/routes.mdx
  website/content/docs/connect/gateways/api-gateway/define-routes/route-to-peered-services.mdx
Labels: type/docs

#22032 Update api submodule versions to v1.31.0 for envoyextensions
  envoyextensions/go.mod
  envoyextensions/go.sum
  go.mod
  test-integ/go.mod
  test/integration/consul-container/go.mod
  troubleshoot/go.mod
Labels: type/docs, theme/api, theme/acls, theme/cli, theme/ui, type/ci, pr/dependencies, theme/envoy/xds, theme/contributing, theme/internals, pr/no-backport

#22033 Revert "Update api submodule versions to v1.31.0 for envoyextensions"
  envoyextensions/go.mod
  envoyextensions/go.sum
  go.mod
  test-integ/go.mod
  test/integration/consul-container/go.mod
  troubleshoot/go.mod
Labels: pr/dependencies, pr/no-backport

#22034 Update the submodules for 1.20.x
  go.mod
  test-integ/go.mod
  test/integration/consul-container/go.mod
Labels: pr/dependencies, pr/no-backport
