Repository hashicorp/consul, pull requests merged in 2025-09, with the labels that each got.

#22647 updated debug command doc
  website/content/commands/debug.mdx
Labels: type/docs, pr/no-changelog, backport/1.21

#22534 [SECVULN-8636] Filter ACL for anonymous token along with empty token
  .changelog/22534.txt
  agent/consul/acl_test.go
  agent/consul/intention_endpoint_test.go
  agent/consul/rpc.go
  agent/consul/rpc_test.go
Labels: backport/all

#22677 Manual backport of update group permission to auto-config.json into release/1.21.x
  .changelog/22626.txt
  agent/auto-config/persist.go
Labels: pr/no-backport

#22687 migrate from ember power select to HDS super select
  ui/packages/consul-ui/app/components/child-selector/index.hbs
  ui/packages/consul-ui/app/components/consul/intention/permission/form/index.hbs
  ui/packages/consul-ui/app/components/consul/intention/permission/header/form/index.hbs
  ui/packages/consul-ui/app/components/option-input/index.hbs
  ui/packages/consul-ui/app/components/policy-form/index.hbs
  ui/packages/consul-ui/app/modifiers/fix-super-select-aria.js
Labels: theme/ui

#22689 chore: updated backport assistant to use squash merge commit for cherry picking
  .github/workflows/backport-assistant.yml
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#22645 [UI] trigger fetch-data before dropdown is rendered.
  ui/packages/consul-ui/app/components/nav-selector/index.hbs
  ui/packages/consul-ui/mock-api/prefixed-api/v1/namespaces
Labels: theme/ui, pr/no-changelog, pr/no-backport

#22669 Backport of upgrade lycheeverse to fix vulnerability into release/1.21.x
  .changelog/22667.txt
  .github/workflows/broken-link-check.yml
Labels: type/ci, theme/contributing

#22682 fix: kv input validation
  .changelog/22682.txt
  agent/kvs_endpoint.go
  agent/kvs_endpoint_test.go
Labels: backport/all, backport/ent/1.18, backport/ent/1.19, backport/ent/1.20, backport/ent/1.21

#22697 chore: fixed the release version checking logic
  .github/workflows/ce-merge-trigger.yml
Labels: type/ci, theme/contributing, pr/no-changelog, backport/1.21

#22698 Backport of chore: fixed the release version checking logic into release/1.21.x
  .github/workflows/ce-merge-trigger.yml
Labels: type/ci, theme/contributing

#22700 chore: fixed the release version checking logic and approvers logic
  .github/workflows/ce-merge-trigger.yml
Labels: type/ci, theme/contributing, pr/no-changelog, backport/1.21

#22704 fixed the ce-merge trigger worlfow to pass PR number
  .github/workflows/ce-merge-trigger.yml
Labels: pr/no-changelog, backport/1.21

#22703 Backport of chore: fixed the relase version checking logic and approvers logic into release/1.21.x
  .github/workflows/ce-merge-trigger.yml
Labels: type/ci, theme/contributing

#22705 Backport of fixed the ce-merge trigger worlfow to pass PR number into release/1.21.x
  .github/workflows/ce-merge-trigger.yml
Labels: type/ci, theme/contributing

#22707 Backport of fixed the payload while passing dispatch event for CE to ENT merge into release/1.21.x
  .github/workflows/ce-merge-trigger.yml
Labels: type/ci, theme/contributing

#22709 fixed the ce-merge trigger workflow to pass PR number
  .github/workflows/ce-merge-trigger.yml
Labels: type/ci, theme/contributing, pr/no-changelog, backport/1.21

#22712 fixed the REPO empty issue while invoking repo dispatch
  .github/workflows/ce-merge-trigger.yml
Labels: type/ci, theme/contributing, pr/no-changelog, backport/1.21

#22715 fixed the payload variable
  .github/workflows/ce-merge-trigger.yml
Labels: type/ci, theme/contributing, pr/no-changelog, backport/1.21

#22692 fix accessibility isues of powerselectwithcreate component
  ui/packages/consul-ui/app/components/consul/intention/form/fieldsets/index.hbs
  ui/packages/consul-ui/app/components/consul/intention/form/fieldsets/skin.scss
  ui/packages/consul-ui/app/modifiers/fix-power-select-with-create-aria.js
Labels: theme/ui

#22691 [UI] peer page accessibility
  ui/packages/consul-ui/app/components/peerings/badge/index.scss
  ui/packages/consul-ui/app/styles/app.scss
  ui/packages/consul-ui/app/styles/tailwind-like.scss
Labels: theme/ui, pr/no-changelog, pr/no-backport

#22589 update ui server to replace ContentPath variable in js assets as well
  agent/uiserver/uiserver.go
  agent/uiserver/uiserver_test.go
Labels: theme/ui, pr/no-changelog, pr/update-ui-assets, backport/all

#22730 Backport of max_request_headers_kb param handling in Proxy Defaults and API Gateway Configs for Connect Proxy into release/1.21.x
  .changelog/22679.txt
  agent/structs/config_entry_gateways.go
  agent/structs/config_entry_gateways_test.go
  agent/structs/structs.deepcopy.go
  agent/xds/listeners_apigateway.go
  agent/xds/listeners_test.go
  agent/xds/resources_test.go
  agent/xds/testdata/clusters/api-gateway-with-http-max-request-headers.latest.golden
  agent/xds/testdata/endpoints/api-gateway-with-http-max-request-headers.latest.golden
  agent/xds/testdata/listeners/api-gateway-with-http-max-request-headers.latest.golden
  agent/xds/testdata/routes/api-gateway-with-http-max-request-headers.latest.golden
  agent/xds/testdata/secrets/api-gateway-with-http-max-request-headers.latest.golden
  api/config_entry_gateways.go
  api/config_entry_gateways_test.go
  proto/private/pbconfigentry/config_entry.gen.go
  proto/private/pbconfigentry/config_entry.pb.go
  proto/private/pbconfigentry/config_entry.proto
  test/integration/connect/envoy/case-api-gateway-max-request-headers-kb-proxy-defaults/capture.sh
  test/integration/connect/envoy/case-api-gateway-max-request-headers-kb-proxy-defaults/service_gateway.hcl
  test/integration/connect/envoy/case-api-gateway-max-request-headers-kb-proxy-defaults/service_s1.hcl
  test/integration/connect/envoy/case-api-gateway-max-request-headers-kb-proxy-defaults/setup.sh
  test/integration/connect/envoy/case-api-gateway-max-request-headers-kb-proxy-defaults/vars.sh
  test/integration/connect/envoy/case-api-gateway-max-request-headers-kb-proxy-defaults/verify.bats
  test/integration/connect/envoy/case-api-gateway-max-request-headers-kb/capture.sh
  test/integration/connect/envoy/case-api-gateway-max-request-headers-kb/service_gateway.hcl
  test/integration/connect/envoy/case-api-gateway-max-request-headers-kb/service_s1.hcl
  test/integration/connect/envoy/case-api-gateway-max-request-headers-kb/setup.sh
  test/integration/connect/envoy/case-api-gateway-max-request-headers-kb/vars.sh
  test/integration/connect/envoy/case-api-gateway-max-request-headers-kb/verify.bats
Labels: theme/api, theme/envoy/xds

#22720 UI - rishabh gupta/super select with create
  ui/packages/consul-ui/app/components/consul/intention/form/fieldsets/index.hbs
  ui/packages/consul-ui/app/components/consul/intention/form/fieldsets/skin.scss
  ui/packages/consul-ui/app/components/super-select-with-create/README.mdx
  ui/packages/consul-ui/app/components/super-select-with-create/index.hbs
  ui/packages/consul-ui/app/components/super-select-with-create/index.js
  ui/packages/consul-ui/app/components/super-select-with-create/index.scss
  ui/packages/consul-ui/app/modifiers/fix-power-select-with-create-aria.js
  ui/packages/consul-ui/app/styles/tailwind-like.scss
  ui/packages/consul-ui/tests/integration/components/super-select-with-create-test.js
Labels: theme/ui

#22734 update: consul-server-connection-manager to v0.1.12
  go.mod
  go.sum
  test-integ/go.mod
  test-integ/go.sum
  test/integration/consul-container/go.mod
  test/integration/consul-container/go.sum
  testing/deployer/go.mod
  testing/deployer/go.sum
Labels: pr/dependencies, pr/no-changelog, backport/all

#22555 CE-911 - Update "Secure Consul" tutorial for docs
  website/content/docs/secure/acl/best-practice.mdx
  website/content/docs/secure/encryption/best-practice.mdx
  website/content/docs/secure/encryption/index.mdx
  website/content/docs/secure/encryption/tls/mtls.mdx
  website/content/docs/secure/index.mdx
  website/data/docs-nav-data.json
Labels: type/docs, pr/no-changelog, pr/no-backport

#22742 Backport: max_request_headers_kb param handling in Service Defaults for Mesh Gateway
  .changelog/22722.txt
  agent/xds/listeners.go
  agent/xds/listeners_ingress.go
  agent/xds/listeners_test.go
  agent/xds/resources_test.go
  agent/xds/testdata/clusters/mesh-gateway-peering-service-max-request-headers.latest.golden
  agent/xds/testdata/endpoints/mesh-gateway-peering-service-max-request-headers.latest.golden
  agent/xds/testdata/listeners/mesh-gateway-peering-service-max-request-headers.latest.golden
  agent/xds/testdata/routes/mesh-gateway-peering-service-max-request-headers.latest.golden
  agent/xds/testdata/secrets/mesh-gateway-peering-service-max-request-headers.latest.golden
Labels: theme/envoy/xds, pr/no-backport

#22735 Latest Envoy version update - default v1.34.7
  .changelog/22735.txt
  envoyextensions/xdscommon/ENVOY_VERSIONS
  testing/deployer/topology/default_versions.go
Labels: backport/1.21

#22765 Latest Envoy version update - default v1.34.7 (#22735)
  .changelog/22735.txt
  envoyextensions/xdscommon/ENVOY_VERSIONS
  testing/deployer/topology/default_versions.go
Labels: pr/no-backport

#22761 added BinAddr field in agent/self API response
  agent/agent_endpoint.go
Labels: pr/no-changelog, pr/no-backport

#22771 add column headers on intention page and other minor a11y fixes
  ui/packages/consul-ui/app/components/consul/intention/list/table/index.hbs
  ui/packages/consul-ui/app/components/consul/intention/permission/form/index.hbs
  ui/packages/consul-ui/app/modifiers/fix-super-select-aria.js
Labels: theme/ui

#22732 PKCE and Adding private key JWT support for OIDC
  .changelog/22732.txt
  api/acl.go
  go.mod
  go.sum
  internal/go-sso/oidcauth/auth.go
  internal/go-sso/oidcauth/auth_test.go
  internal/go-sso/oidcauth/config.go
  internal/go-sso/oidcauth/config_test.go
  internal/go-sso/oidcauth/jwt.go
  internal/go-sso/oidcauth/oidc.go
  internal/go-sso/oidcauth/oidc_test.go
  internal/go-sso/oidcauth/oidcauthtest/testing.go
  ui/packages/consul-ui/app/components/consul/auth-method/view/index.hbs
  ui/packages/consul-ui/translations/models/en-us.yaml
Labels: type/enhancement, theme/api, theme/ui, pr/dependencies, pr/no-backport

#22776 Submodules Version upgrade
  api/go.mod
  envoyextensions/go.mod
  go.mod
  internal/tools/protoc-gen-consul-rate-limit/go.mod
  test-integ/go.mod
  test/integration/connect/envoy/test-sds-server/go.mod
  test/integration/connect/envoy/test-sds-server/go.sum
  test/integration/consul-container/go.mod
  testing/deployer/go.mod
  troubleshoot/go.mod
Labels: theme/api, pr/dependencies, pr/no-changelog, backport/ent/1.18, backport/ent/1.19, backport/1.21, backport/ent/1.20, backport/ent/1.21

#22775 Submodules Version upgrade
  api/go.mod
  envoyextensions/go.mod
  go.mod
  internal/tools/protoc-gen-consul-rate-limit/go.mod
  test-integ/go.mod
  test/integration/connect/envoy/test-sds-server/go.mod
  test/integration/connect/envoy/test-sds-server/go.sum
  test/integration/consul-container/go.mod
  testing/deployer/go.mod
  troubleshoot/go.mod
Labels: theme/api, pr/dependencies, pr/no-backport

#22780 Backport: deps: migrate mapstructure to go-viper (#22581)
  .changelog/22581.txt
  .github/CONTRIBUTING.md
  agent/config/config.go
  agent/connect/ca/provider_aws.go
  agent/connect/ca/provider_consul_config.go
  agent/connect/ca/provider_vault.go
  agent/consul/authmethod/authmethods.go
  agent/consul/fsm/commands_ce_test.go
  agent/consul/fsm/snapshot_ce.go
  agent/discovery_chain_endpoint.go
  agent/dns/context.go
  agent/envoyextensions/builtin/aws-lambda/aws_lambda.go
  agent/envoyextensions/builtin/ext-authz/ext_authz.go
  agent/envoyextensions/builtin/lua/lua.go
  agent/envoyextensions/builtin/otel-access-logging/otel_access_logging.go
  agent/envoyextensions/builtin/property-override/property_override.go
  agent/envoyextensions/builtin/wasm/structs.go
  agent/grpc-external/options.go
  agent/grpc-external/querymeta.go
  agent/http.go
  agent/proxycfg/connect_proxy.go
  agent/proxycfg/upstreams.go
  agent/structs/config_entry.go
  agent/structs/connect_ca.go
  agent/xds/config/config.go
  api/acl.go
  api/config_entry.go
  api/connect_ca.go
  api/go.mod
  api/go.sum
  api/watch/watch.go
  command/acl/acl_helpers.go
  command/connect/envoy/envoy.go
  command/connect/redirecttraffic/redirect_traffic.go
  command/connect/redirecttraffic/redirect_traffic_test.go
  command/flags/config.go
  command/flags/config_test.go
  command/helpers/helpers.go
  command/services/config.go
  connect/proxy/config.go
  envoyextensions/go.mod
  envoyextensions/go.sum
  go.mod
  go.sum
  lib/decode/decode_test.go
  lib/map_walker.go
  test-integ/go.mod
  test-integ/go.sum
  test/integration/consul-container/go.mod
  test/integration/consul-container/go.sum
  test/integration/consul-container/libs/cluster/agent.go
  testing/deployer/go.mod
  testing/deployer/go.sum
  troubleshoot/go.mod
  troubleshoot/go.sum
Labels: theme/api, theme/cli, theme/config, theme/connect, pr/dependencies, theme/envoy/xds, theme/contributing, theme/internals, pr/no-changelog, pr/no-backport

#22763 [CSL-11760] [Envoy Bootstrap] Defaults to IPv6 for admin-bind and grpc-addr in dual stack if its empty
  .changelog/22763.txt
  agent/agent_endpoint_test.go
  command/connect/envoy/envoy.go
  command/connect/envoy/envoy_test.go
  command/connect/envoy/testdata/admin-bind-flag-with-dual-stack.golden
  command/connect/envoy/testdata/defaults-with-dual-stack.golden
  command/connect/envoy/testdata/grpc-addr-flag-with-dual-stack.golden
Labels: theme/cli, pr/no-backport

#22772 update: set proxy.local_service_address to ::1 for IPv6 agent bind addr
  .changelog/22772.txt
  agent/sidecar_service.go
  agent/structs/connect_proxy_config.go
Labels: pr/no-backport

#22774 update: default proxy BindAddress to :: for IPv6 agent bind addr
  .changelog/22774.txt
  connect/proxy/config.go
Labels: theme/connect, pr/no-backport

#22783 Consul ENT default version change
  testing/deployer/topology/default_versions.go
Labels: pr/no-changelog, pr/no-backport

#22792 Backport: sec: perform constant time compare for sensitive values (#22537)
  .changelog/22537.txt
  agent/consul/acl.go
  agent/consul/acl_endpoint.go
  agent/consul/auth/token_writer.go
Labels: pr/no-changelog, pr/no-backport

#22793 Backport: sec: perform constant time compare for sensitive values (#22537)
  .changelog/22537.txt
  agent/consul/acl.go
  agent/consul/acl_endpoint.go
  agent/consul/auth/token_writer.go
Labels: pr/no-changelog, pr/no-backport

#22800 Prepare 1.21.5
  .release/security-scan.hcl
  CHANGELOG.md
  version/VERSION
Labels: pr/no-backport

#22671 fix path cleaning of proxied urls
  .changelog/22671.txt
  agent/ui_endpoint.go
  agent/ui_endpoint_test.go
Labels: backport/all, backport/ent/1.18, backport/ent/1.19, backport/ent/1.20, backport/ent/1.21

#22815 Backport of bug - fix menu dropdown not opening after delete into release/1.21.x
  .changelog/22752.txt
  ui/packages/consul-ui/app/components/list-collection/index.hbs
  ui/packages/consul-ui/app/components/list-collection/index.js
  ui/packages/consul-ui/tests/integration/components/list-collection-test.js
Labels: theme/ui

#22823 Removing dualstack flag from consul redirect and check from consul API
  agent/consul/state/catalog.go
  agent/consul/state/catalog_test.go
  command/connect/redirecttraffic/redirect_traffic.go
  command/flags/http.go
Labels: theme/cli, pr/no-changelog, pr/no-backport

#22825 docs: removed duplicate lines
  website/content/docs/east-west/cluster-peering/establish/k8s.mdx
Labels: type/docs, pr/no-changelog, pr/no-backport

#22828 supress cves and upgrade go version
  .changelog/22828.txt
  .gitignore
  .go-version
  .release/security-scan.hcl
  Dockerfile
  api/go.mod
  envoyextensions/go.mod
  go.mod
  internal/tools/proto-gen-rpc-glue/e2e/consul/go.mod
  internal/tools/proto-gen-rpc-glue/e2e/go.mod
  internal/tools/proto-gen-rpc-glue/go.mod
  internal/tools/protoc-gen-consul-rate-limit/go.mod
  proto-public/go.mod
  sdk/go.mod
  test-integ/go.mod
  test/integration/connect/envoy/test-sds-server/go.mod
  test/integration/consul-container/go.mod
  test/integration/consul-container/test/envoy_extensions/testdata/wasm_test_files/go.mod
  testing/deployer/go.mod
  troubleshoot/go.mod
Labels: backport/all

#22826 joining host port using net.JoinHostport
  agent/dns.go
  agent/hcp/client/client.go
  command/connect/proxy/proxy.go
  sdk/iptables/iptables.go
  test-integ/topoutil/asserter.go
  test-integ/topoutil/asserter_blankspace.go
  test/integration/consul-container/libs/assert/service.go
  testing/deployer/sprawl/catalog.go
  testing/deployer/sprawl/sprawl.go
  testing/deployer/util/consul.go
Labels: theme/cli, pr/no-changelog, pr/no-backport

#22831 Updated the changelogs and version for v1.21.5
  CHANGELOG.md
  version/VERSION
Labels: pr/no-changelog, pr/no-backport

#22796 Synced helm docs with consul-k8s
  website/content/docs/reference/k8s/helm.mdx
Labels: type/docs, pr/no-changelog, pr/no-backport

#22839 Backport of UI/bugfix/UI format allow fqdn into release/1.21.x
  .changelog/22779.txt
  ui/packages/consul-ui/app/utils/process-ip-address.js
  ui/packages/consul-ui/tests/integration/helpers/format-ipaddr-test.js
  ui/packages/consul-ui/tests/unit/utils/process-ip-address-test.js
Labels: theme/ui

#22856 adding comma
  .release/security-scan.hcl
Labels: pr/no-changelog, backport/1.22

#22857 Adding change log and version upgrade
  CHANGELOG.md
  version/VERSION
Labels: theme/api, type/ci, pr/dependencies, theme/contributing, pr/no-changelog, pr/no-backport

#22859 Backport of code owner updated into release/1.21.x
  .github/CODEOWNERS
Labels: theme/contributing

#22861 updating change log
  CHANGELOG.md
Labels: pr/no-changelog, backport/1.22
