Repository hashicorp/consul, pull requests merged in 2025-01, with the labels that each got.

#22037 Stage 1.20.2
  CHANGELOG.md
  version/VERSION
Labels: pr/no-backport

#22047 Added labels for redhat validation
  Dockerfile
Labels: pr/no-changelog, backport/1.20

#22050 Manual backport of Added labels for redhat validation into release/1.20.2
  Dockerfile
Labels: pr/no-backport

#22059 fix: security scanner gh token
  .github/workflows/security-scan.yml
Labels: type/ci, theme/contributing, pr/no-backport

#22061 fix: security scanner gh token
  .github/workflows/security-scan.yml
Labels: pr/no-backport

#22055 Update api to 1.21.4
  .changelog/22055.txt
  go.mod
Labels: pr/dependencies, pr/no-backport

#22056 Update api to 1.28.5
  .changelog/22056.txt
  go.mod
  test-integ/go.mod
  test/integration/consul-container/go.mod
Labels: pr/no-backport

#22058 Update api to 1.29.6
  .changelog/22058.txt
  go.mod
  test-integ/go.mod
  test/integration/consul-container/go.mod
Labels: pr/dependencies, pr/no-backport

#22084 sec: bump go and deps versions
  .changelog/22084.txt
  .go-version
  api/go.mod
  api/go.sum
  envoyextensions/go.mod
  envoyextensions/go.sum
  go.mod
  go.sum
  internal/tools/proto-gen-rpc-glue/e2e/consul/go.mod
  internal/tools/proto-gen-rpc-glue/e2e/go.mod
  internal/tools/proto-gen-rpc-glue/go.mod
  internal/tools/proto-gen-rpc-glue/go.sum
  internal/tools/protoc-gen-consul-rate-limit/go.mod
  proto-public/go.mod
  proto-public/go.sum
  sdk/go.mod
  sdk/go.sum
  test-integ/go.mod
  test-integ/go.sum
  test/integration/connect/envoy/test-sds-server/go.mod
  test/integration/connect/envoy/test-sds-server/go.sum
  test/integration/consul-container/go.mod
  test/integration/consul-container/go.sum
  test/integration/consul-container/test/envoy_extensions/testdata/wasm_test_files/go.mod
  test/integration/consul-container/test/envoy_extensions/testdata/wasm_test_files/go.sum
  testing/deployer/go.mod
  testing/deployer/go.sum
  troubleshoot/go.mod
  troubleshoot/go.sum
Labels: theme/api, pr/dependencies, backport/all

#22093 chore: Updated the changelogs for 1.20.2, 1.19.4, 1.18.6, 1.15.16
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-backport

#22089 chore: Update changelog 1.15.16
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-backport

#22091 chore: Updated changelog for 1.18.6
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-backport

#22094 chore: Updated changelog for 1.20.2
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-backport

#22099 Bump VERSION for 1.20.x
  version/VERSION
Labels: pr/no-changelog, pr/no-backport

#22098 Bump VERSION for 1.15.x
  version/VERSION
Labels: pr/no-changelog, pr/no-backport

#22097 Bump VERSION for 1.18.x
  version/VERSION
Labels: pr/no-changelog, pr/no-backport

#22096 Bump VERSION for 1.19.x
  version/VERSION
Labels: pr/no-changelog, pr/no-backport

#21991 Let education and web presence merge PRs to website directory files.
  .github/CODEOWNERS
Labels: theme/contributing, pr/no-changelog, pr/no-backport

#22109 Consume latest version of consul-awsauth dependency
  .changelog/22109.txt
  go.mod
  go.sum
Labels: pr/dependencies, backport/all

#22110 Backport of Consume latest version of consul-awsauth dependency into release/1.20.x
  .changelog/22109.txt
  go.mod
  go.sum
Labels: pr/dependencies

#22085 Backport of sec: bump go and deps versions into release/1.20.x
  .changelog/22084.txt
  .go-version
  api/go.mod
  api/go.sum
  envoyextensions/go.mod
  envoyextensions/go.sum
  go.mod
  go.sum
  internal/tools/proto-gen-rpc-glue/e2e/consul/go.mod
  internal/tools/proto-gen-rpc-glue/e2e/go.mod
  internal/tools/proto-gen-rpc-glue/go.mod
  internal/tools/proto-gen-rpc-glue/go.sum
  internal/tools/protoc-gen-consul-rate-limit/go.mod
  proto-public/go.mod
  proto-public/go.sum
  sdk/go.mod
  sdk/go.sum
  test-integ/go.mod
  test-integ/go.sum
  test/integration/connect/envoy/test-sds-server/go.mod
  test/integration/connect/envoy/test-sds-server/go.sum
  test/integration/consul-container/go.mod
  test/integration/consul-container/go.sum
  test/integration/consul-container/test/envoy_extensions/testdata/wasm_test_files/go.mod
  test/integration/consul-container/test/envoy_extensions/testdata/wasm_test_files/go.sum
  testing/deployer/go.mod
  testing/deployer/go.sum
  troubleshoot/go.mod
  troubleshoot/go.sum
Labels: theme/api, pr/dependencies
