Repository hashicorp/consul, pull requests merged in 2025-10, with the labels that each got.

#22867 Fix indentation for K8s annotation labels documentation.
  website/content/docs/reference/k8s/annotation-label.mdx
Labels: type/docs, pr/no-changelog, backport/1.21

#22873 ui: upgrade lint-staged and husky
  ui/packages/consul-ui/.husky/pre-commit
  ui/packages/consul-ui/package.json
  ui/pnpm-lock.yaml
Labels: theme/ui, pr/no-changelog, backport/all

#22874 Backport of ui: upgrade lint-staged and husky into release/1.21.x
  ui/packages/consul-ui/.husky/pre-commit
  ui/packages/consul-ui/package.json
  ui/pnpm-lock.yaml
Labels: theme/ui

#22855 ci: Run pnpm install before node setup
  .github/workflows/nightly-test-1.20.x.yaml
  .github/workflows/nightly-test-1.21.x.yaml
Labels: type/ci, theme/contributing, pr/no-changelog, backport/all

#22879 Backport of ci: Run pnpm install before node setup into release/1.21.x
  .github/workflows/nightly-test-1.20.x.yaml
  .github/workflows/nightly-test-1.21.x.yaml
Labels: type/ci, theme/contributing

#22878 Backport of ci: Run pnpm install before node setup into release/1.22.x
  .github/workflows/nightly-test-1.20.x.yaml
  .github/workflows/nightly-test-1.21.x.yaml
Labels: type/ci, theme/contributing

#22866 fixes the config merge from client config to dualstack check internal client initialization config
  agent/netutil/network.go
  command/connect/envoy/envoy.go
  command/connect/envoy/envoy_test.go
Labels: theme/api, theme/cli, pr/no-changelog, backport/1.22

#22846 Fixed Duplicate Port Validation issues in CLI registration
  agent/agent.go
  agent/agent_endpoint_test.go
  agent/config/config.go
  agent/config/runtime_test.go
  agent/structs/structs.go
  agent/structs/structs_test.go
  api/agent.go
  api/agent_test.go
Labels: type/bug, theme/api, theme/config, pr/no-changelog, pr/no-docs, backport/1.22

#22834 Update "Disaster recovery for WAN-federated datacenters"
  website/content/docs/error-messages/consul.mdx
  website/content/docs/manage/disaster-recovery/backup-restore.mdx
  website/content/docs/manage/disaster-recovery/federation.mdx
  website/content/docs/manage/disaster-recovery/index.mdx
  website/content/docs/manage/disaster-recovery/prepare.mdx
  website/content/docs/manage/disaster-recovery/restore/primary.mdx
  website/content/docs/manage/disaster-recovery/restore/secondary.mdx
  website/data/docs-nav-data.json
  website/redirects.js
Labels: type/docs, pr/no-changelog, backport/1.21
