Repository hashicorp/consul, pull requests merged in 2025-07, with the labels that each got.

#22440 Backport of build(deps-dev): bump prettier from 3.2.4 to 3.6.1 in /website into release/1.21.x
  website/package-lock.json
  website/package.json
Labels: type/docs

#22447 Backport of build(deps): bump github.com/mitchellh/go-testing-interface from 1.14.0 to 1.14.1 into release/1.21.x
  agent/connect/testing_ca.go
  agent/proxycfg/state_test.go
  agent/proxycfg/testing.go
  agent/proxycfg/testing_mesh_gateway.go
  agent/structs/testing_catalog.go
  go.mod
  go.sum
Labels: theme/connect, pr/dependencies

#22438 Backport of build(deps): bump golang.org/x/sync from 0.12.0 to 0.15.0 into release/1.21.x
  go.mod
  go.sum
  test-integ/go.mod
  test-integ/go.sum
  test/integration/consul-container/go.mod
  test/integration/consul-container/go.sum
Labels: pr/dependencies

#22473 Backport sync from CE for release/1.21.x
  .github/workflows/test-integrations.yml
  envoyextensions/xdscommon/ENVOY_VERSIONS
  go.mod
  go.sum
  website/package-lock.json
  website/package.json
Labels: type/docs, type/ci, pr/dependencies, theme/contributing, pr/no-changelog, pr/no-backport

#22488 Backport of Updating dependency for security issues into release/1.21.x
  Dockerfile
  go.mod
  go.sum
  testing/deployer/topology/default_versions.go
  ui/packages/consul-ui/app/helpers/format-ipaddr.js
  ui/packages/consul-ui/app/utils/process-ip-address.js
  ui/packages/consul-ui/tests/integration/helpers/format-ipaddr-test.js
  ui/packages/consul-ui/tests/unit/utils/process-ip-address-test.js
Labels: pr/dependencies

#22482 docs: CE-719 Clarify K8s target namespace
  website/content/docs/deploy/server/k8s/consul-k8s.mdx
  website/content/docs/deploy/server/k8s/enterprise.mdx
  website/content/docs/deploy/server/k8s/helm.mdx
  website/content/partials/alerts/k8s-namespace.mdx
Labels: type/docs, theme/kubernetes, pr/no-changelog, pr/no-metrics-test, backport/1.21

#22496 docs: Consul version compatibility updates (#22492)
  website/content/docs/k8s.mdx
  website/content/partials/tables/compatibility/consul-dataplane/lts.mdx
  website/content/partials/tables/compatibility/consul-dataplane/standard-release.mdx
  website/content/partials/tables/compatibility/envoy/lts.mdx
  website/content/partials/tables/compatibility/envoy/standard-release.mdx
  website/content/partials/tables/compatibility/k8s/providers.mdx
Labels: type/docs, pr/no-changelog, pr/no-backport

#22502 Prepare 1.21.3
  .release/security-scan.hcl
  CHANGELOG.md
  version/VERSION
Labels: pr/no-backport

#22495 docs: CE-913 update docker autoconf page
  website/content/docs/secure/auto-config/docker.mdx
Labels: type/docs, pr/no-changelog, pr/no-metrics-test, backport/1.21

#22507 docs: CE-913 update docker autoconf page (#22495)
  website/content/docs/secure/auto-config/docker.mdx
Labels: type/docs, pr/no-changelog, pr/no-metrics-test, pr/no-backport, type/docs-cherrypick

#22503 Upgrade Hashicorp design-system
  .github/workflows/frontend.yml
  ui/.nvmrc
  ui/package.json
  ui/packages/consul-ui/app/components/hashicorp-consul/index.scss
  ui/packages/consul-ui/app/styles/app.scss
  ui/packages/consul-ui/app/styles/base/reset/system.scss
  ui/packages/consul-ui/app/styles/tailwind.scss
  ui/packages/consul-ui/ember-cli-build.js
  ui/packages/consul-ui/package.json
  ui/packages/consul-ui/tailwind.config.js
  ui/yarn.lock
Labels: theme/ui, pr/no-changelog, backport/all
