Repository hashicorp/consul, pull requests merged in 2025-02, with the labels that each got.

#22113 metadata: memoize the parsed build versions
  .changelog/22113.txt
  agent/metadata/build.go
  agent/metadata/server.go
Labels: pr/no-metrics-test, backport/all

#22117 chore: Update changelog 1.18.7
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-backport

#22126 Bump VERSION for 1.18.x
  version/VERSION
Labels: pr/no-changelog, pr/no-backport

#22127 Fix CI: Updated upload-artifact and download-artifact to v4
  .github/CODEOWNERS
  .github/workflows/build.yml
  .github/workflows/nightly-test-integrations-1.15.x.yml
  .github/workflows/nightly-test-integrations-1.16.x.yml
  .github/workflows/nightly-test-integrations-1.17.x.yml
  .github/workflows/nightly-test-integrations.yml
  .github/workflows/reusable-dev-build-windows.yml
  .github/workflows/reusable-dev-build.yml
  .github/workflows/reusable-unit-split.yml
  .github/workflows/reusable-unit.yml
  .github/workflows/test-integrations-windows.yml
  .github/workflows/test-integrations.yml
Labels: type/ci, pr/no-changelog, pr/no-backport

#22125 chore: update changelog for 1.15.x
  CHANGELOG.md
  version/VERSION
Labels: pr/no-changelog, pr/no-backport

#22132 security: Upgrade go version to 1.22.12
  .changelog/22132.txt
  .go-version
  agent/consul/state/txn.go
  agent/consul/txn_endpoint.go
  api/go.mod
  envoyextensions/go.mod
  go.mod
  internal/tools/proto-gen-rpc-glue/e2e/consul/go.mod
  internal/tools/proto-gen-rpc-glue/e2e/go.mod
  internal/tools/proto-gen-rpc-glue/go.mod
  internal/tools/protoc-gen-consul-rate-limit/go.mod
  proto-public/go.mod
  sdk/go.mod
  test-integ/go.mod
  test/integration/connect/envoy/test-sds-server/go.mod
  test/integration/consul-container/go.mod
  testing/deployer/go.mod
  troubleshoot/go.mod
Labels: theme/api, pr/dependencies, backport/all

#22133 Backport of security: Upgrade go version to 1.22.12 into release/1.20.x
  .changelog/22132.txt
  .go-version
  agent/consul/state/txn.go
  agent/consul/txn_endpoint.go
  api/go.mod
  envoyextensions/go.mod
  go.mod
  internal/tools/proto-gen-rpc-glue/e2e/consul/go.mod
  internal/tools/proto-gen-rpc-glue/e2e/go.mod
  internal/tools/proto-gen-rpc-glue/go.mod
  internal/tools/protoc-gen-consul-rate-limit/go.mod
  proto-public/go.mod
  sdk/go.mod
  test-integ/go.mod
  test/integration/connect/envoy/test-sds-server/go.mod
  test/integration/consul-container/go.mod
  testing/deployer/go.mod
  troubleshoot/go.mod
Labels: theme/api, pr/dependencies

#22134 Update golangci-lint to 1.56.1
  Makefile
Labels: pr/no-changelog, backport/all

#22138 chore: Update supported Envoy versions in ENVOY_VERSIONS file
  .changelog/22138.txt
  envoyextensions/xdscommon/ENVOY_VERSIONS
Labels: backport/all

#22141 Changed log level for retryable error Scenarios
  .changelog/22141.txt
  agent/submatview/materializer.go
  agent/xds/delta.go
Labels: theme/envoy/xds, pr/no-backport

#22145 added changelog file
  .changelog/22120.txt
Labels: theme/telemetry, pr/no-backport

#22151 Update all the submodules
  go.mod
  test-integ/go.mod
  test/integration/consul-container/go.mod
Labels: pr/dependencies, pr/no-changelog, pr/no-backport

#22154 Stage 1.20.3
  CHANGELOG.md
  version/VERSION
Labels: pr/no-changelog, pr/no-backport

#22155 chore: update changelog and version for 1.18.8
  CHANGELOG.md
  version/VERSION
Labels: pr/no-changelog, pr/no-backport

#22157 chore: update changelog and version for 1.20.3
  CHANGELOG.md
  version/VERSION
Labels: pr/no-changelog, pr/no-backport

#22158 Fix lint-enums errors and update codeowners
  .github/CODEOWNERS
  agent/consul/state/txn.go
  agent/consul/txn_endpoint.go
Labels: pr/no-changelog, pr/no-backport

#22156 chore: update changelog and version for 1.19.5
  CHANGELOG.md
  version/VERSION
Labels: pr/no-changelog, pr/no-backport

#22171 Backport of fix bsd time log implementation part 2 into release/1.20.x
  logging/logfile_darwinandfreebsd.go
  logging/logfile_openbsd.go
Labels: theme/telemetry

#22172 retracting api submodule version 1.31.1
  .changelog/22172.txt
  api/go.mod
Labels: theme/api, backport/all

#22173 Backport of retracting api submodule version 1.31.1 into release/1.20.x
  .changelog/22172.txt
  api/go.mod
Labels: theme/api

#22174 upgraded consul/api submodule to v1.31.2
  .changelog/22174.txt
  go.mod
  test-integ/go.mod
  test/integration/consul-container/go.mod
Labels: pr/dependencies, backport/all

#22176 upgraded consul/api submodule to v1.31.2 (#22174)
  .changelog/22174.txt
  go.mod
  test-integ/go.mod
  test/integration/consul-container/go.mod
Labels: pr/dependencies, pr/no-backport

#22179 prepping for release 1.20.4
  CHANGELOG.md
  version/VERSION
Labels: pr/no-backport

#22182 post release 1.18.9
  CHANGELOG.md
  version/VERSION
Labels: pr/no-changelog, pr/no-backport

#22183 post release 1.19.6
  CHANGELOG.md
  version/VERSION
Labels: pr/no-changelog, pr/no-backport

#22181 post release 1.20.4
  CHANGELOG.md
  version/VERSION
Labels: pr/no-changelog, pr/no-backport

#22105 [ui] Read from localStorage to display a copyable access token and secret
  .changelog/22105.txt
  ui/packages/consul-ui/app/templates/settings.hbs
Labels: theme/ui, backport/1.20

#22184 logging fix for netbsd os
  .changelog/22184.txt
  logging/logfile_darwinandfreebsd.go
  logging/logfile_openbsd.go
Labels: theme/telemetry, backport/all

#22191 Backport of logging fix for netbsd os into release/1.20.x
  .changelog/22184.txt
  logging/logfile_darwinandfreebsd.go
  logging/logfile_openbsd.go
Labels: theme/telemetry
