Repository hashicorp/consul, pull requests merged in 2025-08, with the labels that each got.

#22529 July patch docs update
  website/content/partials/tables/compatibility/consul-dataplane/lts.mdx
  website/content/partials/tables/compatibility/consul-dataplane/standard-release.mdx
  website/content/partials/tables/compatibility/envoy/lts.mdx
  website/content/partials/tables/compatibility/envoy/standard-release.mdx
  website/content/partials/tables/compatibility/k8s/lts.mdx
  website/content/partials/tables/compatibility/k8s/version.mdx
Labels: type/docs, pr/no-changelog, backport/1.21

#22520 ui: Add generated license headers
  ui/packages/consul-ui/app/helpers/node-identity-template.js
  ui/packages/consul-ui/app/helpers/service-identity-template.js
  ui/packages/consul-ui/tests/integration/helpers/node-identity-template-test.js
  ui/packages/consul-ui/tests/integration/helpers/service-identity-template-test.js
Labels: theme/ui, pr/no-changelog, pr/no-backport

#22541 ui: Fix missing format for ip address in node list view
  ui/packages/consul-ui/app/components/consul/node/list/index.hbs
Labels: theme/ui, pr/no-changelog, backport/1.21, backport/ent/1.21

#22542 Backport of ui: Fix missing format for ip address in node list view into release/1.21.x
  ui/packages/consul-ui/app/components/consul/node/list/index.hbs
Labels: theme/ui

#22551 Updating hashicorp/actions-go-build action to v1.1.1
  .github/workflows/build.yml
Labels: type/ci, theme/contributing, pr/no-changelog, backport/all

#22554 Updating hashicorp/actions-go-build action to v1.1.1
  .github/workflows/build.yml
Labels: type/ci, theme/contributing, pr/no-changelog, pr/no-backport

#22552 Csl 9247 consul debug not collecting pprof
  .changelog/22552.txt
  command/debug/debug.go
  command/debug/debug_test.go
Labels: theme/cli, backport/1.19, backport/1.18, backport/1.20, backport/1.21

#22559 Csl 9247 consul debug not collecting pprof (#22552)
  .changelog/22552.txt
  command/debug/debug.go
  command/debug/debug_test.go
Labels: theme/cli, pr/no-backport

#22562 Backport of update: golang x modules to latest into release/1.21.x
  go.mod
  go.sum
  test-integ/go.mod
  test-integ/go.sum
  test/integration/consul-container/go.mod
  test/integration/consul-container/go.sum
Labels: pr/dependencies

#22566 UI - Remove footer landmark
  ui/packages/consul-ui/app/components/hashicorp-consul/index.hbs
  ui/packages/consul-ui/app/components/list-collection/index.js
  ui/packages/consul-ui/app/components/modal-dialog/index.hbs
  ui/packages/consul-ui/app/components/modal-dialog/layout.scss
  ui/packages/consul-ui/app/components/modal-dialog/skin.scss
  ui/packages/consul-ui/app/components/providers/dimension/README.mdx
  ui/packages/consul-ui/app/components/providers/dimension/index.js
  ui/packages/consul-ui/app/components/tabular-collection/index.js
Labels: theme/ui, pr/no-changelog, pr/no-backport

#22570 ui: CSL-11417 replace foreground-disabled with foreground-faint
  ui/packages/consul-ui/app/components/anchors/index.scss
  ui/packages/consul-ui/app/components/app-view/skin.scss
  ui/packages/consul-ui/app/components/confirmation-dialog/skin.scss
  ui/packages/consul-ui/app/components/consul/health-check/list/skin.scss
  ui/packages/consul-ui/app/components/form-elements/skin.scss
  ui/packages/consul-ui/app/components/freetext-filter/skin.scss
  ui/packages/consul-ui/app/components/hashicorp-consul/index.scss
  ui/packages/consul-ui/app/components/popover-select/index.scss
  ui/packages/consul-ui/app/components/topology-metrics/stats/index.scss
  ui/packages/consul-ui/app/styles/base/color/ui/frame-placeholders.scss
  ui/packages/consul-ui/app/styles/debug.scss
Labels: theme/ui, pr/no-changelog, pr/no-backport

#22576 Backport of build(deps): bump form-data from 3.0.1 to 3.0.4 in /ui into release/1.21.x
  ui/yarn.lock
Labels: theme/ui

#22567 add: testcase for IPv6 scenarios in peering establish api
  agent/rpc/peering/testing.go
  agent/rpc/peering/validate_test.go
Labels: pr/no-changelog, pr/no-docs, consul-india, backport/all

#22582 Backport of add: testcase for IPv6 scenarios in peering establish api into release/1.21.x
  agent/rpc/peering/testing.go
  agent/rpc/peering/validate_test.go
Labels: pr/no-changelog, pr/no-docs

#22588 update: post release changelog
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-backport

#22598 add charset
  .changelog/22598.txt
  agent/checks/check_test.go
  agent/consul/authmethod/kubeauth/testing.go
  agent/hcp/testing.go
  agent/http_test.go
  agent/kvs_endpoint.go
  agent/kvs_endpoint_test.go
  agent/txn_endpoint.go
  api/api.go
  api/api_test.go
  api/content_type.go
  command/resource/client/client.go
  internal/go-sso/oidcauth/oidcauthtest/testing.go
Labels: theme/api, theme/cli, backport/all, backport/ent/1.18, backport/ent/1.19, backport/ent/1.20, backport/ent/1.21

#22579 docs: CE-854 Multiport services and transparent proxy
  website/content/docs/connect/proxy/transparent-proxy/k8s.mdx
Labels: type/docs, pr/no-changelog, pr/no-metrics-test, backport/1.21

#22612 update consul awsauth to prevent authz bypass using url params for aw…
  .changelog/22612.txt
  go.mod
  go.sum
Labels: pr/dependencies, backport/all, backport/ent/1.18, backport/ent/1.19, backport/ent/1.20, backport/ent/1.21

#22532 CE-920 Update "Audit Logging"
  website/content/docs/monitor/log/audit.mdx
  website/content/partials/alerts/enterprise-alert.mdx
Labels: type/docs, pr/no-changelog, pr/no-backport

#22594 ui: add empty dt element under the header
  ui/packages/consul-ui/app/components/consul/token/list/index.hbs
Labels: theme/ui, pr/no-changelog, pr/no-backport

#22624 Add troubleshoot ports info in debug bundle
  .changelog/22624.txt
  command/debug/debug.go
  command/debug/debug_test.go
Labels: theme/cli, backport/1.21, backport/ent/1.21

#22629 Manual Backport of add charset (#22598)
  .changelog/22598.txt
  agent/checks/check_test.go
  agent/consul/authmethod/kubeauth/testing.go
  agent/hcp/testing.go
  agent/http_test.go
  agent/kvs_endpoint.go
  agent/kvs_endpoint_test.go
  agent/txn_endpoint.go
  api/api.go
  api/api_test.go
  api/content_type.go
  command/resource/client/client.go
  internal/go-sso/oidcauth/oidcauthtest/testing.go
Labels: theme/api, theme/cli, pr/no-backport

#22611 Backport of docs: CE-854 Multiport services and transparent proxy into release/1.21.x
  website/content/docs/connect/proxy/transparent-proxy/k8s.mdx
Labels: type/docs

#22521 CE-925 - Update "Setup Consul namespaces on VMs"
  website/content/docs/multi-tenant/namespace/index.mdx
  website/content/docs/multi-tenant/namespace/vm.mdx
  website/content/docs/multi-tenant/namespace/vm/configure-namespaces.mdx
  website/content/docs/multi-tenant/namespace/vm/delegate-token-management.mdx
  website/content/docs/multi-tenant/namespace/vm/index.mdx
  website/content/docs/register/service/namespace.mdx
  website/data/docs-nav-data.json
Labels: type/docs, pr/no-changelog, pr/no-backport

#22615 Backport of update consul awsauth to prevent authz bypass using url params for aw… into release/1.21.x
  .changelog/22612.txt
  go.mod
  go.sum
Labels: pr/dependencies

#22604 max_request_headers_kb param handling in Proxy Defaults for Connect Proxy
  .changelog/22604.txt
  agent/proxycfg/proxycfg.deepcopy.go
  agent/xds/config/config.go
  agent/xds/config/config_test.go
  agent/xds/listeners.go
  agent/xds/listeners_apigateway.go
  agent/xds/listeners_test.go
  agent/xds/resources_test.go
  agent/xds/testdata/clusters/connect-proxy-with-http-max-request-headers.latest.golden
  agent/xds/testdata/endpoints/connect-proxy-with-http-max-request-headers.latest.golden
  agent/xds/testdata/listeners/connect-proxy-with-http-max-request-headers.latest.golden
  agent/xds/testdata/routes/connect-proxy-with-http-max-request-headers.latest.golden
  agent/xds/testdata/secrets/connect-proxy-with-http-max-request-headers.latest.golden
  test/integration/connect/envoy/case-max-request-headers/capture.sh
  test/integration/connect/envoy/case-max-request-headers/service_s1.hcl
  test/integration/connect/envoy/case-max-request-headers/service_s2.hcl
  test/integration/connect/envoy/case-max-request-headers/setup.sh
  test/integration/connect/envoy/case-max-request-headers/verify.bats
  test/integration/connect/envoy/helpers.bash
Labels: theme/envoy/xds, backport/all
